/**
 * P0 Golden 100 rewrites — dish-accurate packs for classics that were on wrong blueprints.
 */

import type { GoldenRecipeDefinition } from "../types.js";
import type { GoldenRecipePageIngredient, GoldenRecipePageStep } from "../recipe-page-schema.js";

export type MealSpecificPack = {
  ingredients: GoldenRecipePageIngredient[];
  steps: GoldenRecipePageStep[];
  prepMinutes?: number;
  cookMinutes?: number;
};

type Ing = GoldenRecipePageIngredient;
type Step = GoldenRecipePageStep;

function m(name: string, quantity: number, unit: string, group?: string, notes?: string): Ing {
  return { name, quantity: String(quantity), unit, group, notes };
}

function mult(n: number, scale: number): number {
  return Math.round(n * scale * 10) / 10;
}

function step(
  n: number,
  title: string,
  instruction: string,
  minutes: number,
  heatLevel: Step["heatLevel"] = "",
): Step {
  return { stepNumber: n, title, instruction, minutes, heatLevel };
}

type PackBuilder = (scale: number, def: GoldenRecipeDefinition) => MealSpecificPack;

export const GOLDEN_P0_CLASSIC_PACKS: Record<string, PackBuilder> = {
  "chicken-parm": (scale) => ({
    prepMinutes: 35,
    cookMinutes: 60,
    ingredients: [
      m("Boneless chicken breasts, pounded ½ inch", mult(4, scale), "lb", "Main"),
      m("All-purpose flour", mult(2, scale), "cups", "Breading"),
      m("Large eggs, beaten", mult(4, scale), "count", "Breading"),
      m("Italian seasoned breadcrumbs", mult(3, scale), "cups", "Breading"),
      m("Grated parmesan cheese", mult(1.5, scale), "cups", "Breading"),
      m("Marinara sauce", mult(4, scale), "cups", "Sauce"),
      m("Fresh mozzarella, sliced", mult(24, scale), "oz", "Cheese"),
      m("Provolone slices", mult(16, scale), "count", "Cheese"),
      m("Spaghetti", mult(2, scale), "lb", "Pasta"),
      m("Olive oil", mult(0.5, scale), "cup", "Frying"),
      m("Kosher salt", mult(2, scale), "tbsp", "Seasoning"),
      m("Black pepper", mult(1, scale), "tbsp", "Seasoning"),
      m("Fresh basil, torn", mult(1, scale), "cup", "Finish"),
      m("Garlic bread loaves", mult(2, scale), "count", "Side", "optional"),
    ],
    steps: [
      step(
        1,
        "Pound and season cutlets",
        "Place chicken between plastic wrap and pound to an even ½ inch. Pat dry, then season both sides with salt and pepper. Set up a breading station: flour in one pan, beaten eggs in the second, breadcrumbs mixed with half the parmesan in the third.",
        15,
      ),
      step(
        2,
        "Bread the cutlets",
        "Dredge each cutlet in flour, shake off excess, dip in egg, then press into breadcrumb-parm mixture until fully coated. Place breaded cutlets on a rack and rest 10 minutes so the coating sets — wet breading falls off in the pan.",
        20,
      ),
      step(
        3,
        "Pan-fry until golden",
        "Heat olive oil in large skillets over medium-high until shimmering. Fry cutlets 3–4 minutes per side until deep golden and 155°F in the center. Work in batches; transfer to sheet pans lined with racks. Wipe excess oil if needed.",
        25,
        "medium-high",
      ),
      step(
        4,
        "Boil pasta and warm sauce",
        "Boil spaghetti in salted water until al dente; drain and toss with a ladle of marinara. Warm remaining marinara in a saucepan — do not boil hard or it splatters on the line.",
        15,
        "medium",
      ),
      step(
        5,
        "Top with cheese and bake",
        "Lay fried cutlets in buttered hotel pans. Spoon marinara over each, then shingle the sliced fresh mozzarella and provolone on top. Bake at 425°F 12–15 minutes until cheese bubbles and edges brown. Rest 3 minutes before serving — molten cheese burns rookies.",
        15,
        "high",
      ),
      step(
        6,
        "Serve Chicken Parm for the crew",
        "Plate cutlets with spaghetti and extra marinara on sheet trays. Finish with remaining parmesan and the torn fresh basil. Garlic bread goes on a separate tray so crust stays crisp.",
        5,
        "low",
      ),
    ],
  }),

  "chicken-caesar": (scale) => ({
    prepMinutes: 25,
    cookMinutes: 45,
    ingredients: [
      m("Romaine hearts, chopped", mult(6, scale), "count", "Salad"),
      m("Boneless chicken breasts", mult(4, scale), "lb", "Main"),
      m("Thick-cut bacon", mult(2, scale), "lb", "Salad"),
      m("Caesar dressing", mult(2, scale), "cups", "Salad"),
      m("Parmesan, shaved", mult(12, scale), "oz", "Salad"),
      m("Day-old bread cubes", mult(8, scale), "cups", "Croutons"),
      m("Olive oil", mult(0.5, scale), "cup", "Cooking"),
      m("Garlic powder", mult(2, scale), "tbsp", "Seasoning"),
      m("Kosher salt", mult(2, scale), "tbsp", "Seasoning"),
      m("Black pepper", mult(1, scale), "tbsp", "Seasoning"),
      m("Baguettes", mult(2, scale), "count", "Side"),
      m("Garlic butter", mult(1, scale), "cup", "Side"),
      m("Lemons", mult(4, scale), "count", "Finish"),
      m("Frozen diner fries", mult(4, scale), "lb", "Side", "optional"),
    ],
    steps: [
      step(
        1,
        "Prep romaine and dressing station",
        "Chop romaine hearts into bite-sized pieces; wash and spin dry — wet lettuce rejects dressing. Shave parmesan into a bowl. Set Caesar dressing, croutons, and lemon wedges in labeled containers before any heat goes on.",
        12,
      ),
      step(
        2,
        "Crisp the bacon",
        "Lay thick-cut bacon on sheet pans in a single layer. Bake at 400°F 15–18 minutes until shatter-crisp and deep mahogany — bacon clears its 145°F internal temp point long before it crisps, so here you cook for texture, not safety. Drain on paper towels; crumble when cool. Hold warm in a dry pan — wet bacon steams the salad.",
        18,
        "high",
      ),
      step(
        3,
        "Grill the chicken",
        "Heat a grill pan or flat-top over medium-high until a water drop sizzles. Season chicken breasts with salt, pepper, and garlic powder. Cook 5–6 minutes per side until deep grill marks show and thickest part reads 160°F. Rest 5 minutes tented with foil.",
        16,
        "medium-high",
      ),
      step(
        4,
        "Verify chicken at 165°F",
        "Slice rested chicken across the grain and probe the center of the thickest piece — must read 165°F before it hits the salad line. Any pink or under-temp slice goes back to the grill 2 minutes per side. Hold sliced chicken loosely covered at 140°F.",
        5,
      ),
      step(
        5,
        "Bake garlic bread",
        "Spread garlic butter on halved baguettes edge to edge. Bake at 400°F 8–10 minutes until edges are crisp and tops golden — garlic burns fast, so watch the last 2 minutes. Slice on a bias and hold in a warm pan.",
        10,
        "high",
      ),
      step(
        6,
        "Toast the croutons",
        "Toss day-old bread cubes with olive oil, salt, and garlic powder. Spread on a sheet pan and bake at 400°F 8–10 minutes until crunchy through the center — soft cores sog out dressed romaine in minutes.",
        10,
        "high",
      ),
      step(
        7,
        "Bake diner fries (optional)",
        "Spread frozen fries in a single layer on sheet pans. Bake at 425°F 20–22 minutes until deeply golden with audible crunch when shaken. Season with salt immediately out of the oven; hold in a warm pan with the door cracked.",
        22,
        "high",
      ),
      step(
        8,
        "Toss the Caesar",
        "Toss dried romaine with dressing gradually — coated leaves, not soup. Fold in half the parmesan, croutons, and crumbled bacon. Add dressing in two passes so bowls stay crisp until the crew hits the line.",
        10,
      ),
      step(
        9,
        "Plate hot chicken over salad",
        "Lay warm sliced chicken over the dressed romaine in hotel pans or individual bowls. Finish with remaining parmesan, bacon, and a lemon squeeze at the table. Garlic bread and fries go on separate trays.",
        5,
        "low",
      ),
      step(
        10,
        "Hold through call interruptions",
        "If tones drop, hold sliced chicken at 140°F covered loosely. Keep dressed salad cold and toss fresh batches after 20 minutes on the line — wilted Caesar kills crew morale.",
        5,
        "low",
      ),
      step(
        11,
        "Pack down leftovers safely",
        "Store dressed salad separately from chicken — acid wilts romaine overnight. Cool chicken in shallow pans within two hours; reheat to 165°F before the next meal.",
        10,
      ),
    ],
  }),

  "beef-stroganoff": (scale) => ({
    prepMinutes: 20,
    cookMinutes: 45,
    ingredients: [
      m("Beef sirloin or chuck, sliced thin", mult(3, scale), "lb", "Main"),
      m("Wide egg noodles", mult(2, scale), "lb", "Pasta"),
      m("Cremini mushrooms, sliced", mult(1.5, scale), "lb", "Aromatics"),
      m("Yellow onion, sliced", mult(2, scale), "large", "Aromatics"),
      m("Garlic cloves, minced", mult(6, scale), "cloves", "Aromatics"),
      m("Unsalted butter", mult(4, scale), "tbsp", "Sauce"),
      m("All-purpose flour", mult(3, scale), "tbsp", "Sauce"),
      m("Beef broth", mult(4, scale), "cups", "Sauce"),
      m("Sour cream", mult(2, scale), "cups", "Sauce", "room temperature"),
      m("Worcestershire sauce", mult(3, scale), "tbsp", "Sauce"),
      m("Dijon mustard", mult(2, scale), "tbsp", "Sauce"),
      m("Smoked paprika", mult(1, scale), "tbsp", "Seasoning"),
      m("Kosher salt", mult(1.5, scale), "tbsp", "Seasoning"),
      m("Black pepper", mult(1, scale), "tbsp", "Seasoning"),
      m("Fresh parsley, chopped", mult(0.5, scale), "cup", "Finish"),
    ],
    steps: [
      step(
        1,
        "Slice beef and prep mushrooms",
        "Slice beef across the grain into thin strips. Pat dry and season with salt, pepper, and paprika. Slice mushrooms and onion — uniform pieces cook evenly in one pan.",
        15,
      ),
      step(
        2,
        "Sear beef in batches",
        "Melt 2 tbsp butter in a large skillet over high heat. Sear beef in a single layer 2 minutes per side until browned but still pink inside. Transfer to a plate — do not crowd or you steam instead of sear.",
        12,
        "high",
      ),
      step(
        3,
        "Cook mushrooms and onions",
        "Add remaining butter to the pan. Cook mushrooms and onions over medium heat 10–12 minutes until deeply browned and moisture evaporates. Stir in garlic 30 seconds until fragrant.",
        12,
        "medium",
      ),
      step(
        4,
        "Build the stroganoff sauce",
        "Sprinkle flour over vegetables; cook 1 minute. Whisk in beef broth and Worcestershire; simmer 5 minutes until thickened. Remove from heat, stir in Dijon, then fold in sour cream — boiling curdles sour cream.",
        12,
        "medium-low",
      ),
      step(
        5,
        "Return beef and simmer gently",
        "Return beef and any juices to the pan. Simmer 5–8 minutes on low until beef is tender and sauce coats a spoon. Taste for salt — beef broth varies.",
        8,
        "low",
      ),
      step(
        6,
        "Boil noodles and serve",
        "Boil egg noodles in salted water until tender; drain well. Toss noodles with stroganoff on sheet trays or serve noodles first with sauce ladled over. Finish with parsley.",
        12,
        "medium",
      ),
    ],
  }),

  "mac-and-cheese-bake": (scale) => ({
    prepMinutes: 20,
    cookMinutes: 45,
    ingredients: [
      m("Elbow macaroni", mult(2, scale), "lb", "Main"),
      m("Unsalted butter", mult(6, scale), "tbsp", "Sauce"),
      m("All-purpose flour", mult(6, scale), "tbsp", "Sauce"),
      m("Whole milk", mult(8, scale), "cups", "Sauce"),
      m("Sharp cheddar, shredded", mult(24, scale), "oz", "Cheese"),
      m("Gruyere or Monterey Jack, shredded", mult(12, scale), "oz", "Cheese"),
      m("Dijon mustard", mult(2, scale), "tbsp", "Seasoning"),
      m("Kosher salt", mult(2, scale), "tbsp", "Seasoning"),
      m("Black pepper", mult(1, scale), "tsp", "Seasoning"),
      m("Panko breadcrumbs", mult(2, scale), "cups", "Topping"),
      m("Unsalted butter, melted", mult(4, scale), "tbsp", "Topping"),
      m("Grated parmesan", mult(0.5, scale), "cup", "Topping"),
    ],
    steps: [
      step(
        1,
        "Par-cook the macaroni",
        "Boil elbow macaroni in well-salted water 2 minutes shy of al dente — it finishes in the oven. Drain thoroughly; wet pasta makes a soupy bake.",
        12,
        "medium-high",
      ),
      step(
        2,
        "Make the cheese sauce",
        "Melt butter in a large pot over medium heat. Whisk in flour; cook 1 minute. Whisk in milk in steady streams until smooth. Simmer until thick enough to coat a spoon, then melt in cheddar and gruyere off the heat. Stir in Dijon, salt, and pepper.",
        15,
        "medium",
      ),
      step(
        3,
        "Combine pasta and sauce",
        "Fold drained macaroni into cheese sauce until every piece is coated. The sauce should look slightly loose — pasta absorbs liquid in the oven.",
        5,
      ),
      step(
        4,
        "Pan up and add topping",
        "Transfer to buttered hotel pans. Mix panko with melted butter and parmesan; scatter evenly over the top for a crunchy lid.",
        10,
      ),
      step(
        5,
        "Bake until bubbling",
        "Bake at 375°F 25–30 minutes until edges bubble and topping is deep golden. If the top browns before the center is hot, cover with foil and continue baking.",
        25,
        "medium",
      ),
      step(
        6,
        "Rest and serve",
        "Rest 5 minutes so the bake sets — scoops hold together on the line. Serve with a spatula, not a spoon, for clean portions.",
        5,
        "low",
      ),
    ],
  }),

  "chili-mac": (scale) => ({
    prepMinutes: 15,
    cookMinutes: 40,
    ingredients: [
      m("Ground beef (80/20)", mult(3, scale), "lb", "Main"),
      m("Elbow macaroni", mult(1.5, scale), "lb", "Pasta"),
      m("Yellow onion, diced", mult(2, scale), "large", "Aromatics"),
      m("Bell pepper, diced", mult(2, scale), "count", "Aromatics"),
      m("Garlic cloves, minced", mult(6, scale), "cloves", "Aromatics"),
      m("Kidney beans, drained", mult(2, scale), "cans", "Chili"),
      m("Diced tomatoes", mult(2, scale), "cans", "Chili"),
      m("Tomato paste", mult(3, scale), "tbsp", "Chili"),
      m("Beef broth", mult(2, scale), "cups", "Chili"),
      m("Chili powder", mult(3, scale), "tbsp", "Seasoning"),
      m("Ground cumin", mult(2, scale), "tbsp", "Seasoning"),
      m("Smoked paprika", mult(1, scale), "tbsp", "Seasoning"),
      m("Dried oregano", mult(1, scale), "tbsp", "Seasoning"),
      m("Vegetable oil", mult(2, scale), "tbsp", "Cooking"),
      m("Kosher salt", mult(1, scale), "tbsp", "Seasoning"),
      m("Black pepper", mult(1, scale), "tsp", "Seasoning"),
      m("Shredded cheddar", mult(16, scale), "oz", "Finish"),
      m("Sour cream", mult(2, scale), "cups", "Topping"),
      m("Green onions, sliced", mult(4, scale), "count", "Topping"),
    ],
    steps: [
      step(
        1,
        "Brown the beef",
        "Heat oil in a large Dutch oven over medium-high. Brown ground beef with onion and bell pepper, breaking into fine crumbles. Drain excess grease — greasy chili mac separates on the line.",
        15,
        "medium-high",
      ),
      step(
        2,
        "Simmer the chili base",
        "Add garlic, chili powder, cumin, paprika, and oregano; cook 1 minute. Stir in tomato paste, diced tomatoes, beans, and beef broth. Simmer 20–25 minutes until thickened and flavors meld. Season with salt and pepper.",
        25,
        "medium-low",
      ),
      step(
        3,
        "Cook macaroni separately",
        "Boil elbow macaroni in salted water until just al dente. Drain well — starch makes the pot gluey if you cook pasta in the chili too long.",
        10,
        "medium-high",
      ),
      step(
        4,
        "Combine chili and mac",
        "Stir cooked macaroni into the chili pot until evenly coated. The mix should look saucy, not dry — add a splash of broth if needed.",
        5,
        "medium",
      ),
      step(
        5,
        "Melt cheese on top",
        "Top with shredded cheddar. Cover 2 minutes to melt, or broil 2–3 minutes for browned cheese edges. Keep the pot on low for seconds.",
        5,
        "medium-low",
      ),
      step(
        6,
        "Serve Chili Mac Skillet",
        "Ladle into bowls or serve straight from the Dutch oven with sour cream and green onions on the side. This is chili AND mac — both should be obvious in every bite.",
        5,
        "low",
      ),
    ],
  }),

  "one-pot-chicken-rice": (scale) => ({
    prepMinutes: 15,
    cookMinutes: 35,
    ingredients: [
      m("Bone-in chicken thighs, skin-on", mult(4, scale), "lb", "Main"),
      m("Long-grain white rice", mult(3, scale), "cups", "Grain"),
      m("Chicken broth", mult(6, scale), "cups", "Liquid"),
      m("Yellow onion, diced", mult(1, scale), "large", "Aromatics"),
      m("Garlic cloves, minced", mult(4, scale), "cloves", "Aromatics"),
      m("Unsalted butter", mult(3, scale), "tbsp", "Cooking"),
      m("Dried thyme", mult(2, scale), "tsp", "Seasoning"),
      m("Bay leaves", mult(2, scale), "count", "Seasoning"),
      m("Frozen peas and carrots", mult(2, scale), "cups", "Vegetables"),
      m("Kosher salt", mult(2, scale), "tbsp", "Seasoning"),
      m("Black pepper", mult(1, scale), "tbsp", "Seasoning"),
      m("Fresh parsley, chopped", mult(0.25, scale), "cup", "Finish"),
      m("Lemon wedges", mult(8, scale), "count", "Finish", "optional"),
    ],
    steps: [
      step(
        1,
        "Season and brown chicken",
        "Pat chicken thighs dry; season all over with salt and pepper. Brown skin-side down in butter in a large Dutch oven over medium-high 6–8 minutes until golden. Flip briefly, then remove to a plate — you are building flavor, not finishing here.",
        12,
        "medium-high",
      ),
      step(
        2,
        "Sweat onion and toast rice",
        "In the same pot, cook onion in the chicken fat 4–5 minutes until soft. Stir in garlic and rice; toast 2 minutes until edges look translucent.",
        8,
        "medium",
      ),
      step(
        3,
        "Add broth and nestle chicken",
        "Pour in chicken broth, thyme, and bay leaves. Nestle chicken skin-side up on the rice. Bring to a simmer, then cover tightly and reduce heat to low.",
        5,
        "medium-low",
      ),
      step(
        4,
        "Simmer until rice is tender",
        "Cook covered 22–25 minutes without lifting the lid — steam escapes and rice goes crunchy. Chicken should read 165°F in the thickest part; rice should be tender and broth absorbed.",
        25,
        "low",
      ),
      step(
        5,
        "Steam vegetables and rest",
        "Scatter peas and carrots over the top; cover 5 minutes off heat so vegetables steam. Discard bay leaves. Fluff rice with a fork, taking care not to shred chicken.",
        5,
        "low",
      ),
      step(
        6,
        "Serve one-pot portions",
        "Plate chicken over rice on sheet trays or serve family-style from the pot. Finish with parsley and lemon wedges. Keep the seasoning simple — thyme, salt, and pepper only.",
        5,
        "low",
      ),
    ],
  }),

  "pulled-pork": (scale) => ({
    prepMinutes: 45,
    cookMinutes: 525,
    ingredients: [
      m("Boneless pork shoulder (butt)", mult(5, scale), "lb", "Main", "about 10 oz raw per firefighter"),
      m("Brown sugar", mult(0.5, scale), "cup", "Dry rub"),
      m("Smoked paprika", mult(3, scale), "tbsp", "Dry rub"),
      m("Garlic powder", mult(2, scale), "tbsp", "Dry rub"),
      m("Onion powder", mult(2, scale), "tbsp", "Dry rub"),
      m("Ground cumin", mult(1, scale), "tbsp", "Dry rub"),
      m("Chili powder", mult(2, scale), "tbsp", "Dry rub"),
      m("Kosher salt", mult(3, scale), "tbsp", "Dry rub"),
      m("Black pepper", mult(2, scale), "tbsp", "Dry rub"),
      m("Apple cider vinegar", mult(1, scale), "cup", "Finishing"),
      m("BBQ sauce", mult(3, scale), "cups", "Finishing"),
      m("Brioche buns or kaiser rolls", mult(24, scale), "count", "Buns"),
      m("Coleslaw mix", mult(2.5, scale), "lb", "Slaw"),
      m("Mayonnaise", mult(1, scale), "cup", "Slaw"),
      m("Pickle chips", mult(2, scale), "cups", "Toppings"),
      m("Yellow mustard", mult(0.5, scale), "cup", "Toppings", "optional"),
    ],
    steps: [
      step(
        1,
        "Apply dry rub",
        "Trim excess hard fat from pork shoulder, leaving about ¼ inch. Mix brown sugar, paprika, garlic powder, onion powder, cumin, chili powder, salt, and pepper. Coat pork all over and press rub into the surface. Rest at room temp 30 minutes while the oven or slow cooker comes up.",
        30,
      ),
      step(
        2,
        "Low-and-slow cook",
        "Roast at 275°F in a covered roaster or run a slow cooker on low 8–10 hours until the pork probes tender at an internal temp of 203°F and shreds with a fork — well past the 145°F safe point, collagen needs the extra heat to melt. Add a splash of water if the pan looks dry halfway through — you want steam, not a dry roast.",
        480,
        "low",
      ),
      step(
        3,
        "Rest and shred",
        "Rest pork covered 30 minutes — juices redistribute. Shred with two forks, discarding large fat chunks. Toss with apple cider vinegar first, then fold in BBQ sauce to taste. Keep some sauce on the side for the line.",
        30,
        "low",
      ),
      step(
        4,
        "Quick slaw",
        "Toss coleslaw mix with mayonnaise, a splash of vinegar, salt, and pepper. Keep cold until service — hot pork plus cold slaw is the move.",
        10,
      ),
      step(
        5,
        "Warm buns and set the line",
        "Split buns and warm in a 300°F oven 5 minutes wrapped in foil. Set pork in a deep hotel pan, buns stacked beside, slaw and pickles in separate bowls.",
        10,
        "medium",
      ),
      step(
        6,
        "Build pulled pork sandwiches",
        "Crew piles pork on buns and tops with slaw and pickles. This is BBQ pulled pork — soft buns and tangy slaw, not Italian subs.",
        10,
        "low",
      ),
    ],
  }),

  "breakfast-sausage-pizza": (scale) => ({
    prepMinutes: 20,
    cookMinutes: 35,
    ingredients: [
      m("Pizza dough balls (15 oz)", mult(4, scale), "count", "Crust"),
      m("Breakfast sausage, bulk", mult(3, scale), "lb", "Main"),
      m("Whole milk", mult(4, scale), "cups", "Gravy"),
      m("Unsalted butter", mult(6, scale), "tbsp", "Gravy"),
      m("All-purpose flour", mult(6, scale), "tbsp", "Gravy"),
      m("Country sausage gravy mix", mult(2, scale), "packets", "Gravy", "optional shortcut"),
      m("Large eggs", mult(12, scale), "count", "Topping"),
      m("Shredded cheddar-mozzarella blend", mult(24, scale), "oz", "Cheese"),
      m("Black pepper", mult(2, scale), "tsp", "Seasoning"),
      m("Dried sage", mult(1, scale), "tsp", "Seasoning"),
      m("Kosher salt", mult(1, scale), "tbsp", "Seasoning"),
      m("Vegetable oil", mult(3, scale), "tbsp", "Pan"),
    ],
    steps: [
      step(
        1,
        "Brown breakfast sausage",
        "Cook bulk sausage in a skillet over medium-high, breaking into small crumbles until fully cooked and browned. Drain grease — greasy gravy splits on the pizza.",
        15,
        "medium-high",
      ),
      step(
        2,
        "Make country gravy",
        "Melt butter in a pot; whisk in flour 1 minute. Whisk in milk and simmer until thick. Stir in half the cooked sausage. Season with salt, pepper, and sage. Gravy should coat a spoon — thin gravy soaks the crust.",
        12,
        "medium",
      ),
      step(
        3,
        "Par-bake crusts",
        "Oil two sheet pans or large rectangular pans. Stretch dough to fit; dock with a fork. Par-bake at 400°F 8 minutes until set but pale — this prevents a soggy breakfast pizza.",
        10,
        "medium",
      ),
      step(
        4,
        "Top with gravy, sausage, cheese, and eggs",
        "Spread sausage gravy on par-baked crusts. Scatter remaining sausage and cheese. Crack eggs over the top — space them so each slice gets half an egg.",
        10,
      ),
      step(
        5,
        "Bake until eggs set",
        "Bake at 400°F 12–15 minutes until cheese melts and egg whites are set with jammy yolks. Rotate pans once if your oven runs hot in back.",
        15,
        "medium",
      ),
      step(
        6,
        "Cut and serve breakfast pizza",
        "Rest 3 minutes, then cut into squares for the hall line. Breakfast Sausage Gravy Pizza — sausage, gravy, eggs, cheese. Not pepperoni night.",
        5,
        "low",
      ),
    ],
  }),

  "detroit-style-pizza": (scale) => ({
    prepMinutes: 110,
    cookMinutes: 45,
    ingredients: [
      m("Bread flour", mult(5, scale), "cups", "Dough"),
      m("Instant yeast", mult(2, scale), "tsp", "Dough"),
      m("Warm water", mult(2, scale), "cups", "Dough", "110°F"),
      m("Granulated sugar", mult(2, scale), "tsp", "Dough"),
      m("Kosher salt", mult(2, scale), "tsp", "Dough"),
      m("Olive oil", mult(4, scale), "tbsp", "Dough"),
      m("Brick cheese or mild cheddar, shredded", mult(32, scale), "oz", "Cheese", "to the edges"),
      m("Cup-and-char pepperoni", mult(16, scale), "oz", "Topping"),
      m("Crushed tomatoes", mult(2, scale), "cups", "Sauce"),
      m("Dried oregano", mult(2, scale), "tsp", "Sauce"),
      m("Garlic powder", mult(1, scale), "tsp", "Sauce"),
      m("Unsalted butter", mult(4, scale), "tbsp", "Pan"),
    ],
    steps: [
      step(
        1,
        "Mix and rise the dough",
        "Stir yeast into warm water with sugar; rest 5 minutes until foamy. Mix flour, salt, oil, and yeast water until a sticky dough forms. Knead 8 minutes. Rise covered 1–1½ hours until doubled — Detroit crust needs an airy, relaxed dough.",
        90,
      ),
      step(
        2,
        "Press into oiled pans",
        "Generously butter and oil two 9x13 steel or dark cake pans — not a round stone. Press dough into corners and up sides slightly. Do not stretch thin; Detroit is thick and airy.",
        15,
      ),
      step(
        3,
        "Cheese to the edges",
        "Scatter cheese edge-to-edge so it touches the pan walls — this creates the frico crispy cheese skirt. Top with pepperoni if using. Rest 15–20 minutes while the oven preheats to 550°F or your oven max on the bottom rack.",
        20,
      ),
      step(
        4,
        "First bake",
        "Bake on the bottom rack 12–14 minutes until cheese caramelizes at the edges and the bottom sounds hollow when tapped. Edges should look fried, not pale.",
        14,
        "high",
      ),
      step(
        5,
        "Sauce stripes on top",
        "Whisk crushed tomatoes with oregano and garlic powder. Remove pizza from oven and spoon sauce in two or three lengthwise stripes ON TOP of the baked cheese — Detroit puts sauce after the bake. Return to oven 5–7 minutes.",
        7,
        "high",
      ),
      step(
        6,
        "Rest and cut rectangles",
        "Rest 5 minutes, then cut into rectangular slices with a bench scraper. Serve on sheet trays — crispy cheese edges face out so the crew sees the Detroit signature.",
        5,
        "low",
      ),
    ],
  }),

  "pepperoni-pizza-night": (scale) => ({
    prepMinutes: 30,
    cookMinutes: 145,
    ingredients: [
      m("Bread flour", mult(6, scale), "cups", "Dough"),
      m("Active dry yeast", mult(2.5, scale), "tsp", "Dough"),
      m("Warm water", mult(2, scale), "cups", "Dough", "110°F"),
      m("Olive oil", mult(3, scale), "tbsp", "Dough"),
      m("Kosher salt", mult(2, scale), "tsp", "Dough"),
      m("Crushed tomatoes", mult(3, scale), "cans", "Sauce", "28 oz"),
      m("Garlic cloves, minced", mult(4, scale), "cloves", "Sauce"),
      m("Dried oregano", mult(2, scale), "tbsp", "Sauce"),
      m("Fresh mozzarella, torn", mult(32, scale), "oz", "Cheese"),
      m("Low-moisture mozzarella, shredded", mult(16, scale), "oz", "Cheese"),
      m("Pepperoni slices", mult(16, scale), "oz", "Topping"),
      m("Grated parmesan", mult(1, scale), "cup", "Finish"),
    ],
    steps: [
      step(
        1,
        "Proof dough for multiple pies",
        "Bloom yeast in warm water 5 minutes. Mix flour, salt, oil, and yeast water; knead 8–10 minutes until smooth. Rise 1–1½ hours until doubled. For eight hungry firefighters, plan three large pies or four medium — scale dough portions accordingly.",
        90,
      ),
      step(
        2,
        "Simmer pizza sauce",
        "Simmer crushed tomatoes with garlic and oregano 15 minutes until slightly thickened. Cool briefly — hot sauce melts dough and makes a soggy center.",
        15,
        "medium",
      ),
      step(
        3,
        "Heat oven and stone or steel",
        "Place pizza stone or steel in the oven; preheat to 500°F at least 45 minutes. Prep cheese and pepperoni while the oven saturates — surface temp matters more than air temp.",
        45,
        "high",
      ),
      step(
        4,
        "Stretch, sauce, cheese, pepperoni",
        "Divide dough; stretch by hand to 12–14 inch rounds. Sauce lightly — wet centers sag. Layer mozzarella and pepperoni; leave a ½ inch rim. Work on parchment or a floured peel.",
        20,
      ),
      step(
        5,
        "Bake until blistered",
        "Bake each pie 10–14 minutes until cheese bubbles with brown spots and the underside sounds hollow. Rotate once for hot spots. Keep finished pies on racks, not stacked — steam kills crust.",
        12,
        "high",
      ),
      step(
        6,
        "Rest, cut, and run the line",
        "Rest 2 minutes, cut into 8 slices per pie, and fan on sheet trays. Classic Pepperoni Pizza night — dough, tomato sauce, mozzarella, pepperoni. Keep a backup pie warming at 200°F.",
        5,
        "low",
      ),
    ],
  }),

  "slider-bar": (scale) => ({
    prepMinutes: 30,
    cookMinutes: 25,
    ingredients: [
      m("Ground beef (80/20)", mult(4, scale), "lb", "Main"),
      m("Slider buns", mult(36, scale), "count", "Buns", "3–4 per person"),
      m("American cheese slices", mult(36, scale), "count", "Cheese"),
      m("Kosher salt", mult(2, scale), "tbsp", "Seasoning"),
      m("Black pepper", mult(1, scale), "tbsp", "Seasoning"),
      m("Unsalted butter", mult(4, scale), "tbsp", "Buns"),
      m("Iceberg lettuce, shredded", mult(1, scale), "head", "Toppings bar"),
      m("Roma tomatoes, sliced", mult(6, scale), "count", "Toppings bar"),
      m("Red onion, thin sliced", mult(2, scale), "count", "Toppings bar"),
      m("Dill pickle chips", mult(3, scale), "cups", "Toppings bar"),
      m("Ketchup", mult(2, scale), "cups", "Sauces"),
      m("Yellow mustard", mult(1, scale), "cup", "Sauces"),
      m("Mayonnaise", mult(1, scale), "cup", "Sauces"),
      m("BBQ sauce", mult(1, scale), "cup", "Sauces", "optional"),
    ],
    steps: [
      step(
        1,
        "Form mini patties",
        "Divide ground beef into 2-ounce portions (about 32–36 patties for a full hall). Roll gently into balls, then flatten into thin patties slightly wider than the buns — they shrink on the griddle. Indent the center with your thumb so they cook flat.",
        20,
      ),
      step(
        2,
        "Season and griddle in batches",
        "Season patties with salt and pepper. Griddle over medium-high 2–3 minutes per side until browned and 160°F. Work in batches so the griddle stays hot — crowded patties steam.",
        15,
        "medium-high",
      ),
      step(
        3,
        "Melt cheese on patties",
        "Top each patty with American cheese in the last minute; cover with a dome lid or foil tent until melted. Transfer finished sliders to sheet trays in a warm oven at 200°F.",
        5,
        "medium",
      ),
      step(
        4,
        "Toast buns",
        "Butter cut slider buns and toast cut-side down on the griddle until golden. Pile toasted bottoms and tops in separate foil-lined pans.",
        8,
        "medium",
      ),
      step(
        5,
        "Build the toppings bar",
        "Line up lettuce, tomato, onion, pickles, ketchup, mustard, and mayo in labeled bowls with tongs and spoons. Put cold toppings on ice if service runs past an hour.",
        10,
      ),
      step(
        6,
        "Serve build-your-own sliders",
        "Crew grabs a bottom bun, adds patty with cheese, builds toppings, and caps with the top bun. Hall Slider Bar feeds 8–12 hungry firefighters when you have enough buns and patties — plan seconds before the line opens.",
        10,
        "low",
      ),
    ],
  }),

  "baked-ziti": (scale) => ({
    prepMinutes: 25,
    cookMinutes: 50,
    ingredients: [
      m("Ziti or rigatoni", mult(2, scale), "lb", "Main"),
      m("Ground beef (80/20)", mult(2.5, scale), "lb", "Main"),
      m("Marinara sauce", mult(4, scale), "cups", "Sauce"),
      m("Crushed tomatoes", mult(1, scale), "can", "Sauce", "28 oz"),
      m("Whole-milk ricotta", mult(24, scale), "oz", "Cheese"),
      m("Low-moisture mozzarella, shredded", mult(24, scale), "oz", "Cheese"),
      m("Grated parmesan", mult(8, scale), "oz", "Cheese"),
      m("Yellow onion, diced", mult(1, scale), "large", "Aromatics"),
      m("Garlic cloves, minced", mult(5, scale), "cloves", "Aromatics"),
      m("Dried Italian seasoning", mult(2, scale), "tbsp", "Seasoning"),
      m("Olive oil", mult(3, scale), "tbsp", "Cooking"),
      m("Kosher salt", mult(2, scale), "tbsp", "Seasoning"),
      m("Black pepper", mult(1, scale), "tsp", "Seasoning"),
      m("Fresh basil, chopped", mult(0.5, scale), "cup", "Finish"),
    ],
    steps: [
      step(
        1,
        "Brown beef and build sauce",
        "Brown ground beef in olive oil with onion until deeply colored. Add garlic and Italian seasoning; cook 1 minute. Stir in crushed tomatoes and marinara; simmer 15 minutes until thick enough to coat a spoon.",
        20,
        "medium-high",
      ),
      step(
        2,
        "Par-cook ziti",
        "Boil ziti in salted water 3 minutes shy of al dente. Drain — baked ziti finishes in the oven, not the pot.",
        10,
        "high",
      ),
      step(
        3,
        "Mix ricotta filling",
        "Stir ricotta with half the parmesan, salt, and pepper until smooth. This layer keeps the bake creamy — skipping ricotta gives you red pasta, not baked ziti.",
        8,
      ),
      step(
        4,
        "Layer in hotel pans",
        "Spread half the meat sauce, then half the pasta, dollops of ricotta, and half the mozzarella. Repeat layers. Top with remaining sauce, mozzarella, and parmesan.",
        12,
      ),
      step(
        5,
        "Bake until bubbling",
        "Bake covered at 375°F 25 minutes, then uncover and bake 10–15 minutes until cheese browns at the edges. Rest 10 minutes before cutting — molten cheese needs to set.",
        35,
        "medium",
      ),
      step(
        6,
        "Serve Baked Ziti",
        "Scoop squares from the pan onto sheet trays. Finish with basil. This is a cheesy pasta bake, not a cream-pasta toss.",
        5,
        "low",
      ),
    ],
  }),

  "pulled-pork-mac": (scale) => ({
    prepMinutes: 45,
    cookMinutes: 510,
    ingredients: [
      m("Boneless pork shoulder", mult(5, scale), "lb", "Main", "about 10 oz raw per firefighter"),
      m("Brown sugar", mult(0.25, scale), "cup", "Rub"),
      m("Smoked paprika", mult(2, scale), "tbsp", "Rub"),
      m("Garlic powder", mult(2, scale), "tbsp", "Rub"),
      m("Kosher salt", mult(2, scale), "tbsp", "Rub"),
      m("Black pepper", mult(1, scale), "tbsp", "Rub"),
      m("Apple cider vinegar", mult(0.5, scale), "cup", "BBQ"),
      m("BBQ sauce", mult(2, scale), "cups", "BBQ"),
      m("Elbow macaroni", mult(2.5, scale), "lb", "Pasta"),
      m("Unsalted butter", mult(6, scale), "tbsp", "Cheese sauce"),
      m("All-purpose flour", mult(6, scale), "tbsp", "Cheese sauce"),
      m("Whole milk", mult(6, scale), "cups", "Cheese sauce"),
      m("Sharp cheddar, shredded", mult(20, scale), "oz", "Cheese"),
      m("Monterey Jack, shredded", mult(12, scale), "oz", "Cheese"),
      m("Panko breadcrumbs", mult(1, scale), "cup", "Topping", "optional"),
    ],
    steps: [
      step(
        1,
        "Rub and slow-cook pork",
        "Coat pork shoulder with brown sugar, paprika, garlic powder, salt, and pepper. Slow-roast covered at 275°F or slow-cooker on low 8 hours until shreddable at 203°F.",
        480,
        "low",
      ),
      step(
        2,
        "Shred and sauce pork",
        "Rest pork 20 minutes, then shred. Toss with vinegar and BBQ sauce — pulled pork mac needs actual pulled pork, not marinara chicken pasta.",
        25,
        "low",
      ),
      step(
        3,
        "Make mac and cheese",
        "Boil macaroni al dente. Make cheese sauce with butter, flour, milk, cheddar, and Monterey Jack. Fold pasta into sauce.",
        20,
        "medium",
      ),
      step(
        4,
        "Combine and pan up",
        "Fold shredded BBQ pork into mac and cheese. Transfer to buttered hotel pans; top with optional panko.",
        10,
      ),
      step(
        5,
        "Bake until bubbling",
        "Bake at 375°F 20–25 minutes until edges bubble and top browns. Hold at 200°F for the line.",
        25,
        "medium",
      ),
      step(
        6,
        "Serve for a big crew feed",
        "Scoop hearty portions — protein and mac in every serving. Extra BBQ sauce on the side for crews who want more smoke.",
        5,
        "low",
      ),
    ],
  }),

  "carolina-mustard-pork": (scale) => ({
    prepMinutes: 40,
    cookMinutes: 480,
    ingredients: [
      m("Boneless pork shoulder", mult(5, scale), "lb", "Main", "about 10 oz raw per firefighter"),
      m("Yellow mustard", mult(1, scale), "cup", "Mustard sauce"),
      m("Apple cider vinegar", mult(0.75, scale), "cup", "Mustard sauce"),
      m("Brown sugar", mult(0.25, scale), "cup", "Mustard sauce"),
      m("Hot sauce", mult(2, scale), "tbsp", "Mustard sauce"),
      m("Garlic powder", mult(2, scale), "tbsp", "Rub"),
      m("Onion powder", mult(2, scale), "tbsp", "Rub"),
      m("Kosher salt", mult(2, scale), "tbsp", "Rub"),
      m("Black pepper", mult(1, scale), "tbsp", "Rub"),
      m("Soft hamburger buns", mult(24, scale), "count", "Buns"),
      m("Coleslaw mix", mult(2.5, scale), "lb", "Slaw"),
      m("Mayonnaise", mult(0.75, scale), "cup", "Slaw"),
      m("Pickle chips", mult(2, scale), "cups", "Toppings"),
    ],
    steps: [
      step(
        1,
        "Season the shoulder",
        "Mix salt, pepper, garlic powder, and onion powder; rub all over pork shoulder. Let sit 30 minutes while the oven or slow cooker heats — this is pulled pork, not grilled chops.",
        30,
      ),
      step(
        2,
        "Low-and-slow until shreddable",
        "Cook covered at 275°F or slow-cooker on low 8–10 hours until pork probes tender at 203°F. Add a splash of vinegar if the pan looks dry.",
        480,
        "low",
      ),
      step(
        3,
        "Shred and finish with mustard sauce",
        "Rest pork 20 minutes, then shred. Whisk mustard, vinegar, brown sugar, and hot sauce; toss pork with enough sauce to coat — Carolina mustard pull should taste tangy, not like soy glaze.",
        25,
        "low",
      ),
      step(
        4,
        "Quick slaw and warm buns",
        "Toss coleslaw with mayo and a spoon of mustard sauce. Warm buns wrapped in foil at 300°F.",
        10,
        "medium",
      ),
      step(
        5,
        "Build mustard pulled pork sandwiches",
        "Pile pork on buns with slaw and pickles. Keep extra mustard sauce for the line — this is Carolina Mustard Pulled Pork, not grilled tenderloin slices.",
        10,
        "low",
      ),
    ],
  }),

  "batch-lasagna": (scale) => ({
    prepMinutes: 35,
    cookMinutes: 65,
    ingredients: [
      m("Lasagna noodles", mult(2, scale), "lb", "Main"),
      m("Ground beef and Italian sausage", mult(4, scale), "lb", "Main"),
      m("Marinara sauce", mult(6, scale), "cups", "Sauce"),
      m("Crushed tomatoes", mult(1, scale), "can", "Sauce", "28 oz"),
      m("Whole-milk ricotta", mult(32, scale), "oz", "Cheese"),
      m("Mozzarella, shredded", mult(24, scale), "oz", "Cheese"),
      m("Parmesan, grated", mult(8, scale), "oz", "Cheese"),
      m("Yellow onion, diced", mult(2, scale), "large", "Aromatics"),
      m("Garlic cloves, minced", mult(6, scale), "cloves", "Aromatics"),
      m("Dried Italian seasoning", mult(2, scale), "tbsp", "Seasoning"),
      m("Eggs", mult(2, scale), "count", "Cheese"),
      m("Olive oil", mult(3, scale), "tbsp", "Cooking"),
      m("Kosher salt", mult(2, scale), "tbsp", "Seasoning"),
      m("Black pepper", mult(1, scale), "tsp", "Seasoning"),
    ],
    steps: [
      step(1, "Brown meat sauce", "Brown beef and sausage with onion and garlic. Add crushed tomatoes and marinara; simmer 20 minutes until thick. Season with Italian seasoning, salt, and pepper.", 25, "medium-high"),
      step(2, "Mix ricotta filling", "Stir ricotta with eggs, half the parmesan, salt, and pepper until smooth.", 10),
      step(3, "Cook lasagna sheets", "Boil lasagna noodles in salted water until pliable; drain and lay flat on oiled sheet pans so they do not stick.", 12, "high"),
      step(4, "Layer in hotel pans", "Spread meat sauce, noodles, ricotta dollops, mozzarella, and repeat. Finish with sauce and cheese on top — batch lasagna is layered, not tossed in a pot.", 20),
      step(5, "Bake covered then brown", "Bake covered at 375°F 45 minutes, then uncover and bake 15–20 minutes until bubbling and golden.", 60, "medium"),
      step(6, "Rest and cut squares", "Rest 15 minutes before cutting so layers hold. Serve squares from the pan for crew portions.", 15, "low"),
    ],
  }),

  "chicken-alfredo-bake": (scale) => ({
    prepMinutes: 25,
    cookMinutes: 45,
    ingredients: [
      m("Penne or rigatoni", mult(2, scale), "lb", "Main"),
      m("Boneless chicken breasts or thighs", mult(4, scale), "lb", "Main"),
      m("Unsalted butter", mult(8, scale), "tbsp", "Sauce"),
      m("Garlic cloves, minced", mult(8, scale), "cloves", "Sauce"),
      m("Heavy cream", mult(4, scale), "cups", "Sauce"),
      m("Grated parmesan", mult(12, scale), "oz", "Sauce"),
      m("Mozzarella, shredded", mult(16, scale), "oz", "Cheese"),
      m("Olive oil", mult(3, scale), "tbsp", "Cooking"),
      m("Kosher salt", mult(2, scale), "tbsp", "Seasoning"),
      m("Black pepper", mult(1, scale), "tbsp", "Seasoning"),
      m("Fresh parsley, chopped", mult(0.5, scale), "cup", "Finish"),
    ],
    steps: [
      step(1, "Season and sear chicken", "Pat chicken dry; season with salt and pepper. Sear in olive oil until golden and 160°F; rest and slice or cube.", 15, "medium-high"),
      step(
        2,
        "Par-cook pasta",
        "Boil penne in well-salted water 2 minutes shy of al dente — it finishes in the oven. Drain thoroughly and spread on sheet pans so it does not clump before saucing.",
        10,
        "high",
      ),
      step(3, "Make alfredo sauce", "Melt butter; cook garlic 30 seconds. Add cream and simmer; whisk in parmesan until silky. No crushed tomatoes — this is alfredo.", 12, "medium"),
      step(4, "Combine and pan up", "Toss pasta and chicken with alfredo. Transfer to buttered hotel pans; top with mozzarella.", 10),
      step(5, "Bake until bubbling", "Bake at 375°F 20–25 minutes until cheese browns at edges.", 25, "medium"),
      step(6, "Serve Chicken Alfredo Bake", "Rest 5 minutes; scoop portions with a spatula. Finish with parsley.", 5, "low"),
    ],
  }),

  "skillet-chicken-alfredo": (scale) => ({
    prepMinutes: 15,
    cookMinutes: 30,
    ingredients: [
      m("Fettuccine or penne", mult(2, scale), "lb", "Main"),
      m("Boneless chicken breasts, sliced", mult(3, scale), "lb", "Main"),
      m("Unsalted butter", mult(6, scale), "tbsp", "Sauce"),
      m("Garlic cloves, minced", mult(6, scale), "cloves", "Sauce"),
      m("Heavy cream", mult(3, scale), "cups", "Sauce"),
      m("Grated parmesan", mult(8, scale), "oz", "Sauce"),
      m("Olive oil", mult(2, scale), "tbsp", "Cooking"),
      m("Kosher salt", mult(1.5, scale), "tbsp", "Seasoning"),
      m("Black pepper", mult(1, scale), "tsp", "Seasoning"),
      m("Fresh parsley, chopped", mult(0.25, scale), "cup", "Finish"),
    ],
    steps: [
      step(1, "Cook pasta", "Boil pasta in salted water to al dente; reserve 1 cup pasta water before draining.", 12, "high"),
      step(2, "Sear chicken strips", "Season and sear chicken in olive oil until 165°F; set aside.", 10, "medium-high"),
      step(3, "Build alfredo in the skillet", "Melt butter; cook garlic. Add cream and parmesan; simmer until thick. Splash pasta water if needed.", 8, "medium"),
      step(4, "Toss pasta and chicken", "Add pasta and chicken to the skillet; toss until coated. Adjust consistency with pasta water — glossy, not tomato-red.", 5, "medium"),
      step(5, "Serve from the skillet", "Finish with parsley and extra parmesan. Skillet Chicken Alfredo goes straight from pan to sheet trays.", 5, "low"),
    ],
  }),

  "turkey-meatball-zoodles": (scale) => ({
    prepMinutes: 20,
    cookMinutes: 35,
    ingredients: [
      m("Ground turkey", mult(3, scale), "lb", "Main"),
      m("Breadcrumbs", mult(2, scale), "cups", "Meatballs"),
      m("Egg", mult(2, scale), "count", "Meatballs"),
      m("Parmesan, grated", mult(4, scale), "oz", "Meatballs"),
      m("Garlic cloves, minced", mult(4, scale), "cloves", "Meatballs"),
      m("Fresh zucchini, spiralized", mult(8, scale), "lb", "Noodles"),
      m("Marinara sauce", mult(4, scale), "cups", "Sauce"),
      m("Olive oil", mult(3, scale), "tbsp", "Cooking"),
      m("Kosher salt", mult(2, scale), "tbsp", "Seasoning"),
      m("Black pepper", mult(1, scale), "tsp", "Seasoning"),
      m("Fresh basil, torn", mult(0.5, scale), "cup", "Finish"),
    ],
    steps: [
      step(1, "Form turkey meatballs", "Mix turkey, breadcrumbs, egg, parmesan, garlic, salt, and pepper. Roll into golf-ball-size meatballs.", 15),
      step(2, "Bake meatballs", "Bake on sheet pans at 425°F 15–18 minutes until 165°F and lightly browned.", 18, "high"),
      step(3, "Spiralize zucchini", "Spiralize zucchini into noodles; pat dry — wet zoodles steam instead of sear.", 10),
      step(4, "Warm marinara", "Simmer marinara in a large skillet. Add baked meatballs to coat.", 8, "medium"),
      step(5, "Sauté zoodles quickly", "Sauté zoodles in olive oil 2–3 minutes just until bright green — do not boil dried pasta; these are zucchini noodles.", 4, "medium-high"),
      step(6, "Plate meatballs over zoodles", "Serve sauced meatballs over zoodles with basil. Lighter base, same hall portions.", 5, "low"),
    ],
  }),
};
