/**
 * Pizza Night Golden 100 — dish-accurate packs (excluding P0 classics already in golden-p0-classic-packs).
 */

import type { GoldenRecipeDefinition } from "../types.js";
import type { MealSpecificPack } from "./golden-p0-classic-packs.js";
import type { GoldenRecipePageIngredient, GoldenRecipePageStep } from "../recipe-page-schema.js";

type Ing = GoldenRecipePageIngredient;
type Step = GoldenRecipePageStep;

function m(name: string, quantity: number, unit: string, group?: string, notes?: string): Ing {
  return { name, quantity: String(quantity), unit, group, notes };
}

function mult(n: number, scale: number): number {
  return Math.round(n * scale * 10) / 10;
}

function step(
  n: number,
  title: string,
  instruction: string,
  minutes: number,
  heatLevel: Step["heatLevel"] = "",
): Step {
  return { stepNumber: n, title, instruction, minutes, heatLevel };
}

type PackBuilder = (scale: number, def: GoldenRecipeDefinition) => MealSpecificPack;

export const PIZZA_NIGHT_PACKS: Record<string, PackBuilder> = {
  "bbq-chicken-pizza": (scale) => ({
    prepMinutes: 35,
    cookMinutes: 55,
    ingredients: [
      m("Pizza dough balls (15 oz)", mult(4, scale), "count", "Crust"),
      m("Cooked chicken breast, shredded", mult(3, scale), "lb", "Main", "or rotisserie"),
      m("BBQ sauce", mult(2, scale), "cups", "Sauce"),
      m("Smoked paprika", mult(2, scale), "tsp", "Seasoning"),
      m("Garlic powder", mult(1, scale), "tsp", "Seasoning"),
      m("Kosher salt", mult(1, scale), "tbsp", "Seasoning"),
      m("Black pepper", mult(1, scale), "tsp", "Seasoning"),
      m("Low-moisture mozzarella, shredded", mult(20, scale), "oz", "Cheese"),
      m("Smoked gouda, shredded", mult(8, scale), "oz", "Cheese"),
      m("Red onion, thin sliced", mult(2, scale), "large", "Topping"),
      m("Fresh cilantro, chopped", mult(1, scale), "cup", "Finish"),
      m("Olive oil", mult(3, scale), "tbsp", "Crust"),
      m("Cornmeal", mult(0.5, scale), "cup", "Peel", "for sliding"),
    ],
    steps: [
      step(
        1,
        "Season and toss the chicken",
        "Toss shredded chicken with half the BBQ sauce, paprika, garlic powder, salt, and pepper. Taste — sauce should be bold because cheese mellows it. Keep remaining sauce for the line.",
        12,
      ),
      step(
        2,
        "Heat oven and stone or steel",
        "Place a pizza stone or inverted sheet pan in the oven. Preheat to 500°F at least 40 minutes. Shred cheese and slice red onion while the oven saturates — surface temp matters more than air temp.",
        40,
        "high",
      ),
      step(
        3,
        "Stretch dough and oil rims",
        "On a floured surface, stretch each dough ball to a 12–14 inch round. Leave a ½ inch rim. Brush rims lightly with olive oil so edges brown. Work on parchment dusted with cornmeal so pies slide on the peel.",
        15,
      ),
      step(
        4,
        "Sauce, cheese, chicken, onion",
        "Spread a thin ring of BBQ sauce on each crust — less than tomato night; sweet sauce pools in the center. Layer mozzarella and gouda, then chicken and red onion. Do not overload wet chicken or the center sags.",
        12,
      ),
      step(
        5,
        "Bake until edges char",
        "Bake each pie 10–13 minutes until cheese bubbles with brown spots and the bottom sounds hollow when tapped. Rotate once for hot spots. Hold finished pies on racks, not stacked — steam kills crust.",
        13,
        "high",
      ),
      step(
        6,
        "Rest, cilantro, and cut",
        "Rest 2 minutes so cheese sets. Drizzle remaining BBQ sauce in thin ribbons and scatter cilantro. Cut into 8 slices per pie and fan on sheet trays for eight hungry firefighters. Backup pie holds at 200°F uncovered up to 15 minutes.",
        5,
        "low",
      ),
    ],
  }),

  "white-garlic-chicken-pizza": (scale) => ({
    prepMinutes: 40,
    cookMinutes: 55,
    ingredients: [
      m("Pizza dough balls (15 oz)", mult(4, scale), "count", "Crust"),
      m("Cooked chicken breast, sliced", mult(3, scale), "lb", "Main"),
      m("Whole milk", mult(3, scale), "cups", "White sauce"),
      m("Unsalted butter", mult(6, scale), "tbsp", "White sauce"),
      m("All-purpose flour", mult(6, scale), "tbsp", "White sauce"),
      m("Garlic cloves, minced", mult(8, scale), "cloves", "White sauce"),
      m("Grated parmesan", mult(1.5, scale), "cups", "Cheese"),
      m("Fresh mozzarella, torn", mult(24, scale), "oz", "Cheese"),
      m("Ricotta, dollops", mult(12, scale), "oz", "Cheese"),
      m("Fresh spinach, chopped", mult(8, scale), "oz", "Topping"),
      m("Kosher salt", mult(1.5, scale), "tbsp", "Seasoning"),
      m("Black pepper", mult(1, scale), "tsp", "Seasoning"),
      m("Dried Italian seasoning", mult(2, scale), "tsp", "Seasoning"),
      m("Olive oil", mult(3, scale), "tbsp", "Crust"),
    ],
    steps: [
      step(
        1,
        "Roast garlic and wilt spinach",
        "Toss spinach with a drizzle of olive oil and a pinch of salt; wilt in a hot skillet 2 minutes until collapsed. Squeeze out excess water — wet spinach steams the crust. Set aside.",
        8,
        "medium-high",
      ),
      step(
        2,
        "Make garlic béchamel",
        "Melt butter in a saucepan over medium heat. Cook minced garlic 1 minute until fragrant but not brown. Whisk in flour 1 minute, then milk in steady streams until smooth. Simmer until thick enough to coat a spoon. Off heat, stir in half the parmesan, salt, pepper, and Italian seasoning. Cool 5 minutes — hot white sauce melts raw dough.",
        15,
        "medium",
      ),
      step(
        3,
        "Preheat stone to 500°F",
        "Heat pizza stone or steel at 500°F at least 40 minutes. Tear mozzarella and measure ricotta while the oven saturates.",
        40,
        "high",
      ),
      step(
        4,
        "Stretch and white-sauce the pies",
        "Stretch dough to 12–14 inch rounds with a ½ inch rim. Spread a thin layer of garlic white sauce — you should still see dough in spots. Top with mozzarella, sliced chicken, wilted spinach, ricotta dollops, and remaining parmesan.",
        15,
      ),
      step(
        5,
        "Bake until golden and set",
        "Bake 11–14 minutes until cheese browns in spots and the underside is crisp. White pies need color on top and bottom — pale centers mean underbaked dough. Rotate once if the back of the oven runs hot.",
        13,
        "high",
      ),
      step(
        6,
        "Rest and serve white garlic chicken",
        "Rest 2 minutes, then cut into 8 slices per pie. White Garlic Chicken Pizza — creamy sauce, roasted garlic flavor, chicken and spinach. Not red-sauce night; keep backup pies on racks at 200°F.",
        5,
        "low",
      ),
    ],
  }),

  "meat-lovers-sheet-pizza": (scale) => ({
    prepMinutes: 25,
    cookMinutes: 45,
    ingredients: [
      m("Pizza dough balls (15 oz)", mult(4, scale), "count", "Crust"),
      m("Pizza sauce", mult(3, scale), "cups", "Sauce"),
      m("Low-moisture mozzarella, shredded", mult(32, scale), "oz", "Cheese"),
      m("Pepperoni slices", mult(12, scale), "oz", "Meats"),
      m("Italian sausage, cooked crumbles", mult(2, scale), "lb", "Meats"),
      m("Canadian bacon, diced", mult(12, scale), "oz", "Meats"),
      m("Bacon, cooked and crumbled", mult(12, scale), "oz", "Meats"),
      m("Ground beef, browned", mult(1.5, scale), "lb", "Meats"),
      m("Dried oregano", mult(2, scale), "tsp", "Seasoning"),
      m("Grated parmesan", mult(0.5, scale), "cup", "Finish"),
      m("Olive oil", mult(4, scale), "tbsp", "Pan"),
    ],
    steps: [
      step(
        1,
        "Brown sausage and beef",
        "Cook Italian sausage and ground beef in a skillet over medium-high, breaking into fine crumbles until fully browned. Drain grease — greasy sheet pizza pools in the tray. Combine with cooked bacon and Canadian bacon in a bowl.",
        18,
        "medium-high",
      ),
      step(
        2,
        "Oil and stretch sheet pans",
        "Oil two half-sheet pans (18x13). Press and stretch dough to the corners; dock all over with a fork so air escapes. A tight fit feeds the crew from two trays instead of juggling four round pies.",
        12,
      ),
      step(
        3,
        "Par-bake crusts",
        "Par-bake at 425°F 8 minutes until set and pale golden — this carries the weight of five meats without a raw center.",
        8,
        "medium",
      ),
      step(
        4,
        "Sauce, cheese, and load meats",
        "Spread pizza sauce edge to edge. Layer mozzarella, then pepperoni, sausage-beef mix, and more mozzarella. Meat Lover's means crowded but not swimming — if toppings slide, you went too heavy in one spot.",
        12,
      ),
      step(
        5,
        "Bake until edges are crisp",
        "Bake at 425°F 18–22 minutes until cheese is deeply browned at the edges and the center reads 190°F on a thermometer through the cheese. Rotate pans halfway. Bottom should sound hollow when tapped on the pan edge.",
        20,
        "medium-high",
      ),
      step(
        6,
        "Rest and cut squares",
        "Rest 5 minutes so cheese sets — runny cheese burns rookies on the line. Cut into squares with a bench scraper; sprinkle parmesan. One tray feeds four; two trays feed eight with seconds.",
        5,
        "low",
      ),
    ],
  }),

  "margherita-pizza": (scale) => ({
    prepMinutes: 30,
    cookMinutes: 60,
    ingredients: [
      m("Bread flour", mult(6, scale), "cups", "Dough"),
      m("Active dry yeast", mult(2.5, scale), "tsp", "Dough"),
      m("Warm water", mult(2, scale), "cups", "Dough", "110°F"),
      m("Olive oil", mult(3, scale), "tbsp", "Dough"),
      m("Kosher salt", mult(2, scale), "tsp", "Dough"),
      m("San Marzano crushed tomatoes", mult(2, scale), "cans", "Sauce", "28 oz"),
      m("Garlic cloves, smashed", mult(3, scale), "cloves", "Sauce"),
      m("Fresh mozzarella, sliced", mult(32, scale), "oz", "Cheese"),
      m("Fresh basil leaves", mult(2, scale), "cups", "Finish"),
      m("Extra-virgin olive oil", mult(0.25, scale), "cup", "Finish"),
      m("Flaky sea salt", mult(1, scale), "tsp", "Finish"),
    ],
    steps: [
      step(
        1,
        "Proof dough for blistered crust",
        "Bloom yeast in warm water 5 minutes. Mix flour, salt, oil, and yeast water; knead 8–10 minutes until smooth. Rise 1–1½ hours until doubled. Margherita needs relaxed gluten for leopard spotting on the rim.",
        90,
      ),
      step(
        2,
        "Make quick tomato sauce",
        "Simmer crushed tomatoes with smashed garlic 12 minutes until slightly thickened. Season lightly with salt — fresh mozzarella brings salt too. Cool briefly; hot sauce melts dough.",
        12,
        "medium",
      ),
      step(
        3,
        "Heat stone to maximum practical temp",
        "Preheat stone or steel at 500°F at least 45 minutes. Drain mozzarella on paper towels and slice evenly — wet cheese makes a soggy center.",
        45,
        "high",
      ),
      step(
        4,
        "Stretch, light sauce, mozzarella only",
        "Stretch dough to 12–14 inch rounds. Sauce sparingly — red should peek through cheese. Arrange mozzarella slices in one layer with slight overlap. No toppings yet; basil goes on after the bake.",
        15,
      ),
      step(
        5,
        "Bake for leopard spots",
        "Bake 9–12 minutes until crust is spotted brown and cheese has melted with a few golden blisters. Rotate once. Underbaked Margherita tastes like cheese on raw bread — look for color on the underside.",
        11,
        "high",
      ),
      step(
        6,
        "Basil, olive oil, rest, and cut",
        "Immediately scatter whole basil leaves and drizzle olive oil. Finish with flaky salt. Rest 2 minutes, cut into 8 slices. Fresh Margherita Pizza — tomato, mozzarella, basil. Serve fast; basil wilts on a hot hold.",
        5,
        "low",
      ),
    ],
  }),

  "honey-soppressata-pizza": (scale) => ({
    prepMinutes: 30,
    cookMinutes: 55,
    ingredients: [
      m("Pizza dough balls (15 oz)", mult(4, scale), "count", "Crust"),
      m("Crushed tomatoes", mult(2, scale), "cans", "Sauce", "28 oz"),
      m("Garlic cloves, minced", mult(4, scale), "cloves", "Sauce"),
      m("Dried oregano", mult(2, scale), "tsp", "Sauce"),
      m("Fresh mozzarella, torn", mult(24, scale), "oz", "Cheese"),
      m("Low-moisture mozzarella, shredded", mult(8, scale), "oz", "Cheese"),
      m("Soppressata or spicy salami, sliced", mult(16, scale), "oz", "Topping"),
      m("Hot honey", mult(0.5, scale), "cup", "Finish"),
      m("Red pepper flakes", mult(1, scale), "tsp", "Finish"),
      m("Grated parmesan", mult(0.5, scale), "cup", "Finish"),
      m("Olive oil", mult(2, scale), "tbsp", "Crust"),
    ],
    steps: [
      step(
        1,
        "Simmer quick pizza sauce",
        "Simmer crushed tomatoes with garlic and oregano 12 minutes until slightly thick. Cool 5 minutes — hot sauce on raw dough makes a wet center.",
        12,
        "medium",
      ),
      step(
        2,
        "Preheat stone to 500°F",
        "Heat stone or steel at 500°F at least 40 minutes. Tear mozzarella and slice soppressata thin — thick coins curl and shield the cheese from browning.",
        40,
        "high",
      ),
      step(
        3,
        "Stretch rounds and sauce lightly",
        "Stretch dough to 12–14 inches with a defined rim. Sauce in a thin layer; leave the rim clean for blistering. Brush rims with olive oil.",
        12,
      ),
      step(
        4,
        "Cheese and soppressata",
        "Layer fresh and shredded mozzarella, then soppressata in an even shingle pattern — gaps mean bare bites, piles mean greasy pools. A light dusting of parmesan is optional before the bake.",
        10,
      ),
      step(
        5,
        "Bake until salami edges curl",
        "Bake 10–13 minutes until cheese bubbles and soppressata edges crisp and cup slightly. Rotate for even color. Hot Honey Soppressata needs char on the meat, not pale pink disks.",
        12,
        "high",
      ),
      step(
        6,
        "Hot honey drizzle and cut",
        "Rest 2 minutes. Drizzle hot honey in thin zigzags and hit with a pinch of red pepper flakes. Cut into 8 slices per pie. Sweet heat hits after the bake — honey burns if added too early.",
        5,
        "low",
      ),
    ],
  }),

  "buffalo-chicken-pizza": (scale) => ({
    prepMinutes: 35,
    cookMinutes: 50,
    ingredients: [
      m("Pizza dough balls (15 oz)", mult(4, scale), "count", "Crust"),
      m("Cooked chicken breast, diced", mult(3, scale), "lb", "Main"),
      m("Frank's-style hot sauce", mult(1, scale), "cup", "Sauce"),
      m("Unsalted butter, melted", mult(6, scale), "tbsp", "Sauce"),
      m("Ranch dressing", mult(1.5, scale), "cups", "Sauce", "for drizzle"),
      m("Low-moisture mozzarella, shredded", mult(24, scale), "oz", "Cheese"),
      m("Blue cheese crumbles", mult(8, scale), "oz", "Cheese"),
      m("Celery, thin sliced", mult(4, scale), "stalks", "Finish"),
      m("Green onions, sliced", mult(4, scale), "stalks", "Finish"),
      m("Kosher salt", mult(1, scale), "tbsp", "Seasoning"),
    ],
    steps: [
      step(
        1,
        "Toss chicken in buffalo butter",
        "Whisk hot sauce with melted butter. Toss diced chicken until coated; taste for heat — cheese and ranch mellow it. Reserve a few tablespoons of plain buffalo for after the bake.",
        10,
      ),
      step(
        2,
        "Preheat stone to 500°F",
        "Heat stone or steel at 500°F at least 40 minutes. Shred mozzarella and crumble blue cheese while the oven saturates.",
        40,
        "high",
      ),
      step(
        3,
        "Stretch dough — light red sauce optional",
        "Stretch four 12–14 inch rounds. Buffalo Chicken is a white-ish pie: skip tomato or use only a whisper of pizza sauce if your crew expects red. Brush rims with butter from the buffalo bowl.",
        12,
      ),
      step(
        4,
        "Mozzarella, buffalo chicken, blue cheese",
        "Layer mozzarella, then buffalo chicken, then blue cheese crumbles. Do not drown in sauce before baking — wet buffalo pools in the center.",
        10,
      ),
      step(
        5,
        "Bake until cheese browns",
        "Bake 10–13 minutes until cheese bubbles and edges spot brown. Chicken is already cooked; you are setting cheese and finishing crust. Rotate once for hot spots.",
        12,
        "high",
      ),
      step(
        6,
        "Ranch drizzle, celery, and cut",
        "Rest 2 minutes. Drizzle ranch and reserved buffalo in thin lines. Scatter celery and green onions for crunch — not baked in or they go limp. Cut into 8 slices; Buffalo Chicken Pizza eats like game day on a crust.",
        5,
        "low",
      ),
    ],
  }),

  "firehall-supreme-pizza": (scale) => ({
    prepMinutes: 35,
    cookMinutes: 60,
    ingredients: [
      m("Pizza dough balls (15 oz)", mult(4, scale), "count", "Crust"),
      m("Pizza sauce", mult(3, scale), "cups", "Sauce"),
      m("Low-moisture mozzarella, shredded", mult(28, scale), "oz", "Cheese"),
      m("Pepperoni slices", mult(8, scale), "oz", "Toppings"),
      m("Italian sausage, cooked crumbles", mult(1.5, scale), "lb", "Toppings"),
      m("Bell peppers, diced", mult(3, scale), "count", "Toppings"),
      m("Yellow onion, diced", mult(2, scale), "large", "Toppings"),
      m("Mushrooms, sliced", mult(12, scale), "oz", "Toppings"),
      m("Black olives, sliced", mult(1, scale), "cup", "Toppings"),
      m("Grated parmesan", mult(0.5, scale), "cup", "Finish"),
      m("Dried oregano", mult(2, scale), "tsp", "Seasoning"),
    ],
    steps: [
      step(
        1,
        "Prep and sauté vegetables",
        "Sauté peppers, onion, and mushrooms in a dry-hot skillet 8 minutes until moisture evaporates — wet veg steams supreme pies. Brown sausage crumbles separately and drain grease.",
        15,
        "medium-high",
      ),
      step(
        2,
        "Preheat stone to 500°F",
        "Heat stone or steel at 500°F at least 40 minutes. Portion all toppings in bowls so the line moves fast — supreme night is a topping sprint.",
        40,
        "high",
      ),
      step(
        3,
        "Stretch four loaded rounds",
        "Stretch dough to 12–14 inches. Sauce evenly with a ½ inch clean rim. First layer: half the mozzarella. This locks toppings so they do not slide off in the peel jiggle.",
        15,
      ),
      step(
        4,
        "Layer meats, veg, cheese, pepperoni",
        "Add sausage, peppers, onions, mushrooms, olives, remaining mozzarella, and pepperoni. Sprinkle oregano. Firehall Supreme means every slice has something — distribute, don't dump in the middle.",
        12,
      ),
      step(
        5,
        "Bake until loaded center sets",
        "Bake 12–15 minutes until cheese is browned at edges and the center is fully set — loaded pies need the longer end of the range. Rotate once. If center looks wet, give 2 more minutes; soggy supreme disappoints the hall.",
        14,
        "high",
      ),
      step(
        6,
        "Parmesan, rest, and crew cut",
        "Rest 3 minutes, parmesan, cut 8 slices per pie. Fan on sheet trays for the line. Keep backup pie at 200°F on a rack — stacked boxes soften the crust.",
        5,
        "low",
      ),
    ],
  }),

  "four-cheese-white-pizza": (scale) => ({
    prepMinutes: 35,
    cookMinutes: 55,
    ingredients: [
      m("Pizza dough balls (15 oz)", mult(4, scale), "count", "Crust"),
      m("Whole milk ricotta", mult(2, scale), "cups", "Cheese"),
      m("Fresh mozzarella, torn", mult(24, scale), "oz", "Cheese"),
      m("Low-moisture mozzarella, shredded", mult(12, scale), "oz", "Cheese"),
      m("Grated parmesan", mult(1, scale), "cup", "Cheese"),
      m("Grated fontina or provolone", mult(8, scale), "oz", "Cheese"),
      m("Garlic cloves, minced", mult(6, scale), "cloves", "Seasoning"),
      m("Extra-virgin olive oil", mult(4, scale), "tbsp", "Seasoning"),
      m("Kosher salt", mult(1, scale), "tbsp", "Seasoning"),
      m("Black pepper", mult(1, scale), "tsp", "Seasoning"),
      m("Fresh thyme leaves", mult(2, scale), "tbsp", "Finish"),
    ],
    steps: [
      step(
        1,
        "Season ricotta and garlic oil",
        "Stir ricotta with half the garlic, salt, pepper, and a drizzle of olive oil until creamy. Warm remaining garlic gently in olive oil 2 minutes — do not brown or it tastes bitter on a white pie.",
        10,
        "low",
      ),
      step(
        2,
        "Preheat stone to 500°F",
        "Heat stone or steel at 500°F at least 40 minutes. Tear fresh mozzarella and grate hard cheeses while the oven saturates.",
        40,
        "high",
      ),
      step(
        3,
        "Stretch and schmear ricotta",
        "Stretch dough to 12–14 inch rounds. Spread seasoned ricotta in a thin even layer — thick ricotta pockets stay cold in the center. Brush rims with garlic oil.",
        12,
      ),
      step(
        4,
        "Four-cheese layer",
        "Add fresh mozzarella, shredded mozzarella, fontina, and parmesan. Four-Cheese White Pizza has no tomato — if you see red sauce, you grabbed the wrong pan.",
        8,
      ),
      step(
        5,
        "Bake until golden and bubbling",
        "Bake 11–14 minutes until cheeses melt together with golden spots and the crust underside is crisp. White pies show doneness on cheese color, not pepperoni curl.",
        13,
        "high",
      ),
      step(
        6,
        "Thyme, rest, and cut",
        "Scatter thyme leaves after the bake. Rest 2 minutes, cut 8 slices per pie. Rich pie — one backup tray at 200°F is enough for seconds without turning greasy.",
        5,
        "low",
      ),
    ],
  }),

  "hawaiian-pizza": (scale) => ({
    prepMinutes: 25,
    cookMinutes: 50,
    ingredients: [
      m("Pizza dough balls (15 oz)", mult(4, scale), "count", "Crust"),
      m("Pizza sauce", mult(2.5, scale), "cups", "Sauce"),
      m("Low-moisture mozzarella, shredded", mult(24, scale), "oz", "Cheese"),
      m("Diced ham", mult(2, scale), "lb", "Topping"),
      m("Pineapple tidbits, drained", mult(20, scale), "oz", "Topping", "press dry"),
      m("Red onion, thin sliced", mult(1, scale), "large", "Topping"),
      m("Dried oregano", mult(1, scale), "tsp", "Seasoning"),
      m("Red pepper flakes", mult(0.5, scale), "tsp", "Seasoning", "optional"),
    ],
    steps: [
      step(
        1,
        "Drain pineapple hard",
        "Spread pineapple on paper towels and press dry — wet pineapple is the number one cause of soggy Hawaiian centers. Toss ham with a pinch of oregano if you like.",
        10,
      ),
      step(
        2,
        "Preheat stone to 500°F",
        "Heat stone or steel at 500°F at least 40 minutes. Shred mozzarella and slice red onion while the oven saturates.",
        40,
        "high",
      ),
      step(
        3,
        "Stretch, sauce, and first cheese",
        "Stretch four 12–14 inch rounds. Sauce lightly; Hawaiian needs less sauce than supreme because pineapple releases juice. Layer half the mozzarella.",
        12,
      ),
      step(
        4,
        "Ham, pineapple, onion, more cheese",
        "Distribute ham, pineapple, and red onion evenly — clumps mean some slices are all fruit. Top with remaining mozzarella. Optional red pepper flakes for crews who like heat with sweet.",
        10,
      ),
      step(
        5,
        "Bake until edges spot brown",
        "Bake 10–13 minutes until cheese browns and pineapple edges caramelize slightly. Rotate once. If liquid pools in the center, your pineapple was still too wet.",
        12,
        "high",
      ),
      step(
        6,
        "Rest and cut for the hall",
        "Rest 2 minutes, cut 8 slices per pie. Hawaiian Pizza divides rooms — serve with confidence and a backup pie at 200°F for the converts.",
        5,
        "low",
      ),
    ],
  }),

  "jalapeno-popper-pizza": (scale) => ({
    prepMinutes: 35,
    cookMinutes: 50,
    ingredients: [
      m("Pizza dough balls (15 oz)", mult(4, scale), "count", "Crust"),
      m("Cream cheese, softened", mult(16, scale), "oz", "Base"),
      m("Sour cream", mult(1, scale), "cup", "Base"),
      m("Low-moisture mozzarella, shredded", mult(24, scale), "oz", "Cheese"),
      m("Cheddar, shredded", mult(8, scale), "oz", "Cheese"),
      m("Bacon, cooked and crumbled", mult(12, scale), "oz", "Topping"),
      m("Pickled jalapeños, sliced", mult(2, scale), "cups", "Topping"),
      m("Fresh jalapeños, thin sliced", mult(4, scale), "count", "Topping", "optional"),
      m("Garlic powder", mult(1, scale), "tsp", "Seasoning"),
      m("Kosher salt", mult(1, scale), "tbsp", "Seasoning"),
    ],
    steps: [
      step(
        1,
        "Whip popper spread",
        "Beat cream cheese with sour cream, garlic powder, and salt until smooth. Fold in half the bacon. This replaces tomato sauce — keep it spreadable, not chunky.",
        10,
      ),
      step(
        2,
        "Preheat stone to 475°F",
        "Heat stone or steel at 475°F at least 35 minutes. Cream cheese pies scorch above 500°F on the bottom before the center sets.",
        35,
        "high",
      ),
      step(
        3,
        "Stretch rounds and spread base",
        "Stretch dough to 12–14 inches. Spread a thin layer of popper cream cheese mix edge to edge, leaving a rim. Too thick and the center stays cool.",
        12,
      ),
      step(
        4,
        "Cheese, jalapeños, bacon",
        "Layer mozzarella and cheddar, pickled jalapeños, fresh jalapeños if using, and remaining bacon. Press jalapeños into cheese so they do not roll off on the peel.",
        10,
      ),
      step(
        5,
        "Bake until cheddar bubbles",
        "Bake 11–14 minutes until cheddar edges brown and the crust is crisp underneath. Jalapeño Popper Pizza should taste like the appetizer — if it tastes like plain cheese bread, add more jalapeños next time.",
        13,
        "medium-high",
      ),
      step(
        6,
        "Rest and cut",
        "Rest 3 minutes — cream cheese stays molten. Cut 8 slices per pie. Warn the crew about fresh jalapeño heat; keep ranch nearby for rookies.",
        5,
        "low",
      ),
    ],
  }),

  "nashville-hot-chicken-pizza": (scale) => ({
    prepMinutes: 45,
    cookMinutes: 55,
    ingredients: [
      m("Pizza dough balls (15 oz)", mult(4, scale), "count", "Crust"),
      m("Boneless chicken thighs", mult(3, scale), "lb", "Main"),
      m("Buttermilk", mult(2, scale), "cups", "Chicken"),
      m("Hot sauce", mult(0.5, scale), "cup", "Chicken"),
      m("All-purpose flour", mult(2, scale), "cups", "Chicken"),
      m("Cayenne pepper", mult(2, scale), "tbsp", "Heat"),
      m("Brown sugar", mult(2, scale), "tbsp", "Heat"),
      m("Paprika", mult(2, scale), "tbsp", "Heat"),
      m("Vegetable oil", mult(2, scale), "cups", "Frying", "for shallow fry"),
      m("Pickle brine", mult(0.25, scale), "cup", "Heat paste"),
      m("Low-moisture mozzarella, shredded", mult(24, scale), "oz", "Cheese"),
      m("Pickle chips", mult(2, scale), "cups", "Finish"),
      m("White bread slices, toasted and crumbled", mult(8, scale), "count", "Finish", "optional crunch"),
    ],
    steps: [
      step(
        1,
        "Marinate and fry hot chicken",
        "Soak chicken in buttermilk and hot sauce 20 minutes (or overnight if time allows). Mix flour with half the cayenne, paprika, and salt. Fry chicken in 350°F oil until 165°F inside and deeply golden. Drain on a rack — wet fried chicken steams the pizza.",
        30,
        "medium-high",
      ),
      step(
        2,
        "Coat chicken in Nashville paste",
        "Stir remaining cayenne, brown sugar, paprika, and pickle brine into a paste. Toss hot fried chicken in the paste until glossy and fiery. Slice into strips.",
        8,
      ),
      step(
        3,
        "Preheat stone to 500°F",
        "Heat stone or steel at 500°F at least 40 minutes while chicken rests. Shred mozzarella.",
        40,
        "high",
      ),
      step(
        4,
        "Stretch, light sauce, cheese, hot chicken",
        "Stretch four rounds. Use only a thin smear of pizza sauce or skip red entirely. Mozzarella first, then Nashville chicken strips and optional bread crumb crunch.",
        12,
      ),
      step(
        5,
        "Bake to set cheese and crust",
        "Bake 10–12 minutes until cheese bubbles — chicken is already cooked. You're marrying hot chicken to crisp crust. Rotate once.",
        11,
        "high",
      ),
      step(
        6,
        "Pickles, rest, and cut",
        "Top with pickle chips after the bake. Rest 2 minutes, cut 8 slices. Nashville Hot Chicken Pizza hits fast — have milk on the table for rookies who underestimated cayenne.",
        5,
        "low",
      ),
    ],
  }),

  "pesto-chicken-pizza": (scale) => ({
    prepMinutes: 30,
    cookMinutes: 50,
    ingredients: [
      m("Pizza dough balls (15 oz)", mult(4, scale), "count", "Crust"),
      m("Basil pesto", mult(1.5, scale), "cups", "Sauce"),
      m("Cooked chicken breast, sliced", mult(3, scale), "lb", "Main"),
      m("Fresh mozzarella, torn", mult(24, scale), "oz", "Cheese"),
      m("Cherry tomatoes, halved", mult(2, scale), "cups", "Topping"),
      m("Grated parmesan", mult(0.5, scale), "cup", "Cheese"),
      m("Pine nuts, toasted", mult(0.5, scale), "cup", "Finish"),
      m("Balsamic glaze", mult(0.25, scale), "cup", "Finish"),
      m("Kosher salt", mult(1, scale), "tsp", "Seasoning"),
    ],
    steps: [
      step(
        1,
        "Season chicken and prep toppings",
        "Slice cooked chicken and season lightly with salt. Halve cherry tomatoes and toast pine nuts in a dry skillet until golden — watch them; pine nuts go from toast to trash in seconds.",
        10,
        "medium",
      ),
      step(
        2,
        "Preheat stone to 500°F",
        "Heat stone or steel at 500°F at least 40 minutes. Pesto burns if the stone is not fully saturated.",
        40,
        "high",
      ),
      step(
        3,
        "Stretch and pesto base",
        "Stretch dough to 12–14 inches. Spread pesto in a thin even layer — thick pesto globs stay raw-tasting in the center. Leave a clean rim for blistering.",
        12,
      ),
      step(
        4,
        "Mozzarella, chicken, tomatoes",
        "Layer fresh mozzarella, chicken, and cherry tomatoes cut-side up so they roast. Sprinkle parmesan. No tomato sauce on pesto night.",
        10,
      ),
      step(
        5,
        "Bake until pesto edges darken",
        "Bake 10–13 minutes until cheese melts and pesto oil sizzles at the edges. Tomatoes should wrinkle slightly. Rotate once.",
        12,
        "high",
      ),
      step(
        6,
        "Pine nuts, balsamic, and cut",
        "Scatter pine nuts and drizzle balsamic glaze after the bake. Rest 2 minutes, cut 8 slices. Pesto Chicken Pizza — green sauce, bright finish, hall-approved.",
        5,
        "low",
      ),
    ],
  }),

  "philly-cheesesteak-pizza": (scale) => ({
    prepMinutes: 35,
    cookMinutes: 55,
    ingredients: [
      m("Pizza dough balls (15 oz)", mult(4, scale), "count", "Crust"),
      m("Ribeye or sirloin, thin sliced", mult(3, scale), "lb", "Main"),
      m("Bell peppers, sliced", mult(3, scale), "count", "Veg"),
      m("Yellow onions, sliced", mult(3, scale), "large", "Veg"),
      m("Provolone slices", mult(24, scale), "count", "Cheese"),
      m("Low-moisture mozzarella, shredded", mult(12, scale), "oz", "Cheese"),
      m("Garlic aioli or mayo", mult(0.5, scale), "cup", "Base"),
      m("Worcestershire sauce", mult(2, scale), "tbsp", "Seasoning"),
      m("Kosher salt", mult(1.5, scale), "tbsp", "Seasoning"),
      m("Black pepper", mult(1, scale), "tbsp", "Seasoning"),
      m("Vegetable oil", mult(3, scale), "tbsp", "Pan"),
    ],
    steps: [
      step(
        1,
        "Sear steak and vegetables",
        "Heat oil in a large skillet over high heat. Sear steak in batches 2 minutes until browned but not overcooked — it finishes on the pie. Sauté peppers and onions in the same pan 10 minutes until soft and charred at edges. Season with salt, pepper, and Worcestershire.",
        20,
        "high",
      ),
      step(
        2,
        "Combine steak, veg, and provolone",
        "Chop steak roughly and toss with peppers, onions, and torn provolone off heat so cheese starts to melt. This is your cheesesteak topping — keep warm.",
        5,
      ),
      step(
        3,
        "Preheat stone to 500°F",
        "Heat stone or steel at 500°F at least 40 minutes. Stretch dough while the stone saturates.",
        40,
        "high",
      ),
      step(
        4,
        "Aioli base and load topping",
        "Stretch rounds to 12–14 inches. Spread a thin layer of garlic aioli instead of tomato sauce. Layer mozzarella, then the hot steak-pepper-onion-provolone mix evenly.",
        12,
      ),
      step(
        5,
        "Bake until provolone browns",
        "Bake 11–14 minutes until cheese on top browns and the crust is crisp. Philly Cheesesteak Pizza should smell like the sandwich — if it smells only like bread, you skimped on the filling.",
        13,
        "high",
      ),
      step(
        6,
        "Rest and cut",
        "Rest 3 minutes so molten cheese sets. Cut 8 slices per pie. Serve fast — cheesesteak topping stays best when the pie is hot off the stone.",
        5,
        "low",
      ),
    ],
  }),

  "sicilian-sheet-pizza": (scale) => ({
    prepMinutes: 100,
    cookMinutes: 40,
    ingredients: [
      m("Bread flour", mult(5, scale), "cups", "Dough"),
      m("Instant yeast", mult(2, scale), "tsp", "Dough"),
      m("Warm water", mult(2, scale), "cups", "Dough", "110°F"),
      m("Olive oil", mult(4, scale), "tbsp", "Dough"),
      m("Kosher salt", mult(2, scale), "tsp", "Dough"),
      m("Crushed tomatoes", mult(2, scale), "cups", "Sauce"),
      m("Garlic cloves, minced", mult(4, scale), "cloves", "Sauce"),
      m("Dried oregano", mult(2, scale), "tbsp", "Sauce"),
      m("Low-moisture mozzarella, shredded", mult(24, scale), "oz", "Cheese"),
      m("Grated parmesan", mult(0.75, scale), "cup", "Cheese"),
      m("Pepperoni slices", mult(8, scale), "oz", "Topping", "optional"),
      m("Olive oil", mult(3, scale), "tbsp", "Pan"),
    ],
    steps: [
      step(
        1,
        "Mix soft Sicilian dough",
        "Bloom yeast in warm water 5 minutes. Mix flour, salt, 2 tbsp oil, and yeast water until a sticky, soft dough forms. Knead 6–8 minutes. Rise 1 hour until puffy — Sicilian is thick and airy, not cracker-thin.",
        75,
      ),
      step(
        2,
        "Oil pans and press dough",
        "Oil two 9x13 or half-sheet pans generously. Press dough to fill corners; do not over-stretch thin. Dimple surface with oiled fingertips — those dimples hold olive oil and sauce.",
        15,
      ),
      step(
        3,
        "Second rise in the pan",
        "Cover and rise 30–45 minutes until dough looks pillowy and fills the pan edge to edge. Preheat oven to 475°F with racks in lower third.",
        40,
      ),
      step(
        4,
        "Sauce stripes and cheese",
        "Whisk crushed tomatoes with garlic and oregano. Spoon sauce in stripes or patches on top — Sicilian often shows dough between sauce. Top with mozzarella, parmesan, and pepperoni if using.",
        10,
      ),
      step(
        5,
        "Bake until bottom is fried-crisp",
        "Bake on the lower rack 22–28 minutes until the bottom is deep golden and the center reads 190°F through the cheese. Edges should look fried in oil, not pale steamed bread.",
        25,
        "high",
      ),
      step(
        6,
        "Rest and cut squares",
        "Rest 5 minutes in the pan, then lift or cut in the pan into squares. Sicilian Sheet Pan Pizza feeds eight from two trays with thick crust and crisp underside — crew grabs with napkins.",
        5,
        "low",
      ),
    ],
  }),

  "smoked-brisket-bbq-pizza": (scale) => ({
    prepMinutes: 30,
    cookMinutes: 45,
    ingredients: [
      m("Pizza dough balls (15 oz)", mult(4, scale), "count", "Crust"),
      m("Cooked brisket, chopped", mult(3, scale), "lb", "Main", "smoked or braised"),
      m("BBQ sauce", mult(2, scale), "cups", "Sauce"),
      m("Apple cider vinegar", mult(2, scale), "tbsp", "Sauce"),
      m("Low-moisture mozzarella, shredded", mult(20, scale), "oz", "Cheese"),
      m("Smoked gouda, shredded", mult(8, scale), "oz", "Cheese"),
      m("Red onion, thin sliced", mult(2, scale), "large", "Topping"),
      m("Pickled jalapeños", mult(1, scale), "cup", "Topping", "optional"),
      m("Coleslaw", mult(2, scale), "cups", "Finish", "cold, for after bake"),
    ],
    steps: [
      step(
        1,
        "Warm and chop brisket",
        "Chop cooked brisket into small cubes; toss with a few tablespoons BBQ sauce and vinegar. Warm gently in a skillet — cold brisket drops the oven temp and steams the pie.",
        12,
        "medium-low",
      ),
      step(
        2,
        "Preheat stone to 500°F",
        "Heat stone or steel at 500°F at least 40 minutes. This pie uses leftover smoked brisket; you are not smoking meat tonight.",
        40,
        "high",
      ),
      step(
        3,
        "Stretch rounds and BBQ base",
        "Stretch four 12–14 inch rounds. Spread a thin layer of BBQ sauce — less than a saucy sandwich. Brush rims with oil.",
        12,
      ),
      step(
        4,
        "Cheese, brisket, onion",
        "Layer mozzarella and gouda, then brisket and red onion. Pickled jalapeños if your hall likes heat. Do not pile brisket an inch thick or the center never crisps.",
        10,
      ),
      step(
        5,
        "Bake until cheese spots brown",
        "Bake 10–13 minutes until cheese browns and crust sounds hollow. Brisket is cooked; focus on crust and cheese set. Rotate once.",
        12,
        "high",
      ),
      step(
        6,
        "Slaw on top, rest, and cut",
        "Rest 2 minutes. Top with cold coleslaw in the center of each pie or serve slaw on the side — hot slaw wilts. Cut 8 slices. Smoked Brisket BBQ Pizza is hall BBQ night on a crust.",
        5,
        "low",
      ),
    ],
  }),

  "taco-pizza": (scale) => ({
    prepMinutes: 30,
    cookMinutes: 50,
    ingredients: [
      m("Pizza dough balls (15 oz)", mult(4, scale), "count", "Crust"),
      m("Ground beef (80/20)", mult(2.5, scale), "lb", "Main"),
      m("Taco seasoning", mult(4, scale), "tbsp", "Seasoning"),
      m("Refried beans, warmed", mult(2, scale), "cans", "Base"),
      m("Low-moisture mozzarella, shredded", mult(20, scale), "oz", "Cheese"),
      m("Cheddar, shredded", mult(8, scale), "oz", "Cheese"),
      m("Pico de gallo", mult(2, scale), "cups", "Finish"),
      m("Shredded iceberg lettuce", mult(4, scale), "cups", "Finish"),
      m("Crushed tortilla chips", mult(2, scale), "cups", "Finish"),
      m("Sour cream", mult(1.5, scale), "cups", "Finish"),
      m("Pickled jalapeños", mult(1, scale), "cup", "Topping"),
    ],
    steps: [
      step(
        1,
        "Brown taco meat",
        "Brown ground beef over medium-high, breaking into fine crumbles. Drain grease. Stir in taco seasoning and ½ cup water; simmer 5 minutes until thick and glossy. Taste for salt.",
        15,
        "medium-high",
      ),
      step(
        2,
        "Preheat stone to 475°F",
        "Heat stone or steel at 475°F at least 35 minutes. Warm refried beans gently so they spread — cold beans tear the dough.",
        35,
        "high",
      ),
      step(
        3,
        "Stretch and thin bean layer",
        "Stretch four 12–14 inch rounds. Spread a thin layer of refried beans instead of pizza sauce. Beans are thick; use the back of a spoon in an even smear.",
        12,
      ),
      step(
        4,
        "Cheese, meat, jalapeños",
        "Layer mozzarella, cheddar, seasoned beef, and pickled jalapeños. Save lettuce, pico, chips, and sour cream for after the bake — they go limp or soggy if baked.",
        10,
      ),
      step(
        5,
        "Bake until cheese browns at edges",
        "Bake 11–14 minutes until cheese is fully melted and crust is crisp. Taco Pizza should cut clean; if beans squeeze out, you spread too thick.",
        13,
        "medium-high",
      ),
      step(
        6,
        "Cold toppings and cut",
        "Rest 2 minutes. Top with lettuce, pico, crushed chips, and sour cream in stripes. Cut 8 slices per pie and serve immediately — this pie does not hold well on a steam table.",
        5,
        "low",
      ),
    ],
  }),

  "veggie-supreme-pizza": (scale) => ({
    prepMinutes: 35,
    cookMinutes: 55,
    ingredients: [
      m("Pizza dough balls (15 oz)", mult(4, scale), "count", "Crust"),
      m("Pizza sauce", mult(3, scale), "cups", "Sauce"),
      m("Low-moisture mozzarella, shredded", mult(28, scale), "oz", "Cheese"),
      m("Bell peppers, diced", mult(4, scale), "count", "Veg"),
      m("Red onion, diced", mult(2, scale), "large", "Veg"),
      m("Mushrooms, sliced", mult(16, scale), "oz", "Veg"),
      m("Black olives, sliced", mult(1.5, scale), "cups", "Veg"),
      m("Baby spinach, chopped", mult(6, scale), "oz", "Veg"),
      m("Marinated artichoke hearts, drained", mult(12, scale), "oz", "Veg"),
      m("Grated parmesan", mult(0.5, scale), "cup", "Finish"),
      m("Dried oregano", mult(2, scale), "tsp", "Seasoning"),
      m("Olive oil", mult(2, scale), "tbsp", "Veg"),
    ],
    steps: [
      step(
        1,
        "Sauté watery vegetables",
        "Sauté mushrooms, peppers, and onion in olive oil over medium-high 10 minutes until moisture evaporates and edges brown. Wilt spinach 1 minute; squeeze dry. Wet veg on pizza = soggy Veggie Supreme.",
        15,
        "medium-high",
      ),
      step(
        2,
        "Preheat stone to 500°F",
        "Heat stone or steel at 500°F at least 40 minutes. Drain artichokes and quarter if large.",
        40,
        "high",
      ),
      step(
        3,
        "Stretch, sauce, first cheese",
        "Stretch four 12–14 inch rounds. Sauce evenly; layer half the mozzarella. This anchors vegetables so they do not slide off at the peel.",
        12,
      ),
      step(
        4,
        "Load vegetables and top cheese",
        "Distribute sautéed veg, olives, and artichokes evenly. Top with remaining mozzarella and oregano. Veggie Supreme should look crowded but color still peeks through.",
        10,
      ),
      step(
        5,
        "Bake until center is fully set",
        "Bake 12–15 minutes until cheese browns at edges and the vegetable center is hot through. Loaded veg pies need the full time — pale cheese over wet veg means underbaked. Rotate once.",
        14,
        "high",
      ),
      step(
        6,
        "Parmesan, rest, and cut",
        "Rest 3 minutes, sprinkle parmesan, cut 8 slices per pie. Fan on sheet trays for eight. No meat does not mean light eaters — keep a backup pie at 200°F on a rack.",
        5,
        "low",
      ),
    ],
  }),
};
