/**
 * Twelve master editorial categories — full identity, imagery, scoring, subcategories.
 */

import type { MasterCategoryDefinition } from "./schema.js";
import { MASTER_CATEGORY_SCHEMA_VERSION } from "./constants.js";
import { FOOD_IMAGERY_STYLE_VERSION } from "../food-imagery/master-style.js";

type CategoryInput = Omit<MasterCategoryDefinition, "schemaVersion" | "imagery"> & {
  imagery: Omit<MasterCategoryDefinition["imagery"], "styleVersion"> & {
    styleVersion?: string;
  };
};

function cat(partial: CategoryInput): MasterCategoryDefinition {
  const { imagery, ...rest } = partial;
  return {
    schemaVersion: MASTER_CATEGORY_SCHEMA_VERSION,
    ...rest,
    imagery: { styleVersion: FOOD_IMAGERY_STYLE_VERSION, ...imagery },
  };
}

export const MASTER_CATEGORY_DEFINITIONS: MasterCategoryDefinition[] = [
  cat({
    id: "firehall_classics",
    slug: "firehall-classics",
    displayName: "Firehall Classics",
    tagline: "The meals crews already argue about",
    editorialDescription:
      "Hall-proven spreads that feel like tradition — parm nights, taco lines, smash burgers, and the recipes firefighters actually request again. Curated, attributed, and built for the table not the algorithm.",
    emoji: "🚒",
    sortOrder: 1,
    feedPriority: 100,
    emotional: {
      headline: "Station tradition on a plate",
      shiftContexts: ["slow_night", "weekend_watch", "post_call"],
      crewDynamics: ["full_hall", "pair_cook"],
      cravingType: "familiar pride",
      trustPromise: "These are the meals the hall already trusts.",
      firefighterHook: "The lineup your crew already knows by heart",
    },
    visual: {
      themeToken: "ember",
      palettePrimary: "#8B2500",
      paletteAccent: "#E65100",
      lighting: "warm station-house glow, golden highlights on cheese and char",
      typographyMood: "confident heritage — bold slab, tight tracking",
      textureNotes: ["melty cheese", "charred edges", "steam from pasta pots"],
      steamLevel: "subtle",
      platingDensity: "hearty",
    },
    imagery: {
      shotPresetAffinity: ["pasta", "tacos", "burger", "bowl", "grill"],
      promptLighting: "warm tungsten station-kitchen light, appetizing specular on protein",
      promptMood: "crew-favorite spread energy, generous portions, real hall night",
      promptTexture: "cheese pull, char marks, glossy sauce where appropriate",
      negativePromptHints: ["diet food", "tiny portions", "clinical plating"],
    },
    recommendation: {
      shiftUrgency: 0.35,
      crewScale: 0.75,
      comfortSeeking: 0.85,
      performanceFocus: 0.4,
      socialSharing: 0.9,
      skillFloor: 0.55,
      appetiteBoost: 12,
    },
    scoring: {
      titleKeywords: ["firehall", "hall", "classic", "parm", "smash", "crew favorite"],
      mealTypeAffinity: ["pasta", "tacos", "burger", "sandwich", "bowl"],
      cuisineAffinity: ["american", "italian", "mexican", "bbq"],
      proteinAffinity: ["chicken", "beef", "pork"],
    },
    tagSlugs: ["station_favorite", "comfort", "high_protein", "feeds_hard"],
    legacyExplorePools: ["trending", "comfort", "handheld", "pasta"],
    subcategories: [
      { id: "wheel-winners", slug: "wheel-winners", displayName: "Wheel Winners", matchTags: ["classic", "wheel"] },
      { id: "parm-pasta-nights", slug: "parm-pasta-nights", displayName: "Parm & Pasta Nights", matchTags: ["parm", "pasta", "italian"] },
      { id: "line-specials", slug: "line-specials", displayName: "Line Specials", matchTags: ["taco", "burger", "sandwich"] },
    ],
  }),

  cat({
    id: "bbq_grill_nights",
    slug: "bbq-grill-nights",
    displayName: "BBQ & Grill Nights",
    tagline: "Smoke, char, and backyard energy at the hall",
    editorialDescription:
      "Grill-forward nights when the crew wants char, smoke, and protein you can smell from the bay. Ribs, pulled pork, seared steaks, and sheet-pan grill spreads scaled for hungry shifts.",
    emoji: "🔥",
    sortOrder: 2,
    feedPriority: 88,
    emotional: {
      headline: "Char and smoke when the hall slows down",
      shiftContexts: ["slow_night", "weekend_watch"],
      crewDynamics: ["full_hall", "large_batch"],
      cravingType: "smokehouse craving",
      trustPromise: "Real grill cues — marks, glaze, and crew-scale protein.",
      firefighterHook: "When the grill's hot and the hall's hungry",
    },
    visual: {
      themeToken: "smoke",
      palettePrimary: "#3E2723",
      paletteAccent: "#BF360C",
      lighting: "dramatic side light, ember highlights, smoke wisps in bokeh",
      typographyMood: "bold industrial — smokestack confidence",
      textureNotes: ["grill marks", "glazed bark", "charred corn"],
      steamLevel: "subtle",
      platingDensity: "hearty",
    },
    imagery: {
      shotPresetAffinity: ["grill", "burger", "tacos"],
      promptLighting: "grill-side dramatic light, char detail sharp, warm smoke tone",
      promptMood: "backyard BBQ at the station, masculine appetite, generous meat",
      promptTexture: "grill marks, sauce gloss, smoke-kissed crust",
      negativePromptHints: ["raw center", "pale protein", "salad-forward"],
    },
    recommendation: {
      shiftUrgency: 0.4,
      crewScale: 0.8,
      comfortSeeking: 0.7,
      performanceFocus: 0.55,
      socialSharing: 0.85,
      skillFloor: 0.45,
      appetiteBoost: 11,
    },
    scoring: {
      titleKeywords: ["bbq", "barbecue", "grill", "smoked", "ribs", "brisket", "char"],
      mealTypeAffinity: ["grill", "burger", "sandwich", "sheet_pan"],
      cuisineAffinity: ["bbq", "american", "mexican"],
      proteinAffinity: ["beef", "pork", "chicken"],
    },
    tagSlugs: ["grill_night", "high_protein", "feeds_hard"],
    legacyExplorePools: ["bbq"],
    subcategories: [
      { id: "smokehouse", slug: "smokehouse", displayName: "Smokehouse", matchTags: ["smoked", "ribs", "brisket"] },
      { id: "grill-protein", slug: "grill-protein", displayName: "Grill Protein", matchTags: ["steak", "chicken", "grill"] },
      { id: "sandwich-line", slug: "sandwich-line", displayName: "Sandwich Line", matchTags: ["pulled", "sandwich"] },
    ],
  }),

  cat({
    id: "quick_shift_meals",
    slug: "quick-shift-meals",
    displayName: "Quick Shift Meals",
    tagline: "On the table before tones drop again",
    editorialDescription:
      "Fast, decisive dinners for nights when the board is loud and the window is short. Stir-fries, skillets, and 30-minute crew plates with clear steps and minimal fuss.",
    emoji: "⏱️",
    sortOrder: 3,
    feedPriority: 92,
    emotional: {
      headline: "Tones could drop any minute",
      shiftContexts: ["busy_night", "pre_shift"],
      crewDynamics: ["solo_cook", "pair_cook"],
      cravingType: "urgent fuel",
      trustPromise: "Respect your time — realistic minutes, not fantasy prep.",
      firefighterHook: "Feed the crew before the next run",
    },
    visual: {
      themeToken: "steel",
      palettePrimary: "#37474F",
      paletteAccent: "#FF6F00",
      lighting: "bright practical kitchen light, crisp edges, energetic contrast",
      typographyMood: "urgent clarity — sans, high legibility",
      textureNotes: ["wok sheen", "sizzling pan", "fresh garnish pop"],
      steamLevel: "prominent",
      platingDensity: "standard",
    },
    imagery: {
      shotPresetAffinity: ["bowl", "skillet", "stir_fry", "plated_main"],
      promptLighting: "bright busy-kitchen practical light, steam visible",
      promptMood: "fast weeknight energy, everything looks hot and ready",
      promptTexture: "sizzle gloss, fresh steam, distinct zones in bowl",
      negativePromptHints: ["slow braise", "multi-hour", "tiny garnish only"],
    },
    recommendation: {
      shiftUrgency: 0.95,
      crewScale: 0.5,
      comfortSeeking: 0.35,
      performanceFocus: 0.6,
      socialSharing: 0.5,
      skillFloor: 0.65,
      appetiteBoost: 6,
    },
    scoring: {
      titleKeywords: ["quick", "fast", "30", "stir", "skillet", "easy"],
      mealTypeAffinity: ["stir_fry", "skillet", "bowl", "wrap", "sheet_pan"],
      cuisineAffinity: ["asian", "mexican", "american"],
      proteinAffinity: ["chicken", "beef", "any"],
      maxMinutesBoost: 35,
    },
    tagSlugs: ["quick_cleanup", "one_pan"],
    legacyExplorePools: ["quick", "bowl", "one_pot"],
    subcategories: [
      { id: "under-30", slug: "under-30", displayName: "Under 30 Minutes", matchTags: ["quick", "30"] },
      { id: "stir-fry-skillet", slug: "stir-fry-skillet", displayName: "Stir-Fry & Skillet", matchTags: ["stir", "skillet", "wok"] },
      { id: "panic-proof", slug: "panic-proof", displayName: "Panic-Proof Plates", matchTags: ["easy", "simple"] },
    ],
  }),

  cat({
    id: "comfort_food",
    slug: "comfort-food",
    displayName: "Comfort Food",
    tagline: "Post-call emotional reset",
    editorialDescription:
      "Heavy, warm, stick-to-your-ribs food for when the shift was long. Mac-level cheese pulls, chili ladles, casseroles, and mash — food that says sit down, breathe, eat.",
    emoji: "🍲",
    sortOrder: 4,
    feedPriority: 90,
    emotional: {
      headline: "Recover after the hard ones",
      shiftContexts: ["post_call", "slow_night"],
      crewDynamics: ["full_hall", "pair_cook"],
      cravingType: "emotional warmth",
      trustPromise: "Cohesive comfort — not random starch dumps.",
      firefighterHook: "When the call was brutal and the crew needs warmth",
    },
    visual: {
      themeToken: "gold",
      palettePrimary: "#5D4037",
      paletteAccent: "#FFB300",
      lighting: "soft warm hearth light, cozy shadows, steam-forward",
      typographyMood: "soft serif warmth — Sunday dinner at the hall",
      textureNotes: ["cheese stretch", "creamy mash", "ladle steam"],
      steamLevel: "prominent",
      platingDensity: "hearty",
    },
    imagery: {
      shotPresetAffinity: ["soup_chili", "pasta", "bowl", "plated_main"],
      promptLighting: "cozy golden hearth light, steam rising, rich shadows",
      promptMood: "post-shift comfort, emotional recovery, generous bowls",
      promptTexture: "creamy, cheesy, steam, stick-to-ribs density",
      negativePromptHints: ["light salad", "diet branding", "sparse plating"],
    },
    recommendation: {
      shiftUrgency: 0.25,
      crewScale: 0.7,
      comfortSeeking: 0.98,
      performanceFocus: 0.2,
      socialSharing: 0.75,
      skillFloor: 0.5,
      appetiteBoost: 10,
    },
    scoring: {
      titleKeywords: ["comfort", "mac", "cheese", "chili", "stew", "casserole", "hearty", "loaded"],
      mealTypeAffinity: ["soup_chili", "stew", "pasta", "casserole", "one_pot", "bowl"],
      cuisineAffinity: ["american", "italian", "cajun"],
      proteinAffinity: ["beef", "chicken", "pork"],
    },
    tagSlugs: ["comfort", "feeds_hard"],
    legacyExplorePools: ["comfort", "hearty", "slow"],
    subcategories: [
      { id: "cheesy-loaded", slug: "cheesy-loaded", displayName: "Cheesy & Loaded", matchTags: ["mac", "cheese", "loaded"] },
      { id: "bowls-stews", slug: "bowls-stews", displayName: "Bowls & Stews", matchTags: ["chili", "stew", "soup"] },
      { id: "casserole-night", slug: "casserole-night", displayName: "Casserole Night", matchTags: ["casserole", "bake"] },
    ],
  }),

  cat({
    id: "healthy_performance",
    slug: "healthy-performance",
    displayName: "Healthy & Performance",
    tagline: "Built for firefighters training hard",
    editorialDescription:
      "Protein-forward, lighter cleanup plates that still respect appetite. Grilled chicken, grain bowls, and Mediterranean-leaning hall food — not diet culture, performance culture.",
    emoji: "💪",
    sortOrder: 5,
    feedPriority: 75,
    emotional: {
      headline: "Fuel the job, not the guilt",
      shiftContexts: ["training_day", "pre_shift"],
      crewDynamics: ["solo_cook", "pair_cook", "full_hall"],
      cravingType: "performance fuel",
      trustPromise: "Satisfying portions — lighter, not sad.",
      firefighterHook: "Train hard, eat like it matters",
    },
    visual: {
      themeToken: "ocean",
      palettePrimary: "#00695C",
      paletteAccent: "#26A69A",
      lighting: "clean daylight-balanced, fresh herbs, vibrant but not clinical",
      typographyMood: "athletic clean — confident, not preachy",
      textureNotes: ["grill char", "fresh herbs", "grain texture"],
      steamLevel: "none",
      platingDensity: "standard",
    },
    imagery: {
      shotPresetAffinity: ["bowl", "salad", "grill", "plated_main"],
      promptLighting: "fresh clean daylight, appetizing not sterile",
      promptMood: "performance fuel, satisfied crew, vibrant ingredients",
      promptTexture: "grill marks, fresh herbs, visible protein portion",
      negativePromptHints: ["sad diet plate", "tiny portion", "deprivation"],
    },
    recommendation: {
      shiftUrgency: 0.55,
      crewScale: 0.55,
      comfortSeeking: 0.25,
      performanceFocus: 0.95,
      socialSharing: 0.6,
      skillFloor: 0.6,
      appetiteBoost: 4,
    },
    scoring: {
      titleKeywords: ["grilled", "lean", "bowl", "high protein", "herb", "mediterranean", "light"],
      mealTypeAffinity: ["bowl", "salad", "grill", "sheet_pan"],
      cuisineAffinity: ["mediterranean", "greek", "asian"],
      proteinAffinity: ["chicken", "fish", "turkey"],
    },
    tagSlugs: ["high_protein", "high_fiber", "lean"],
    legacyExplorePools: ["healthy", "bowl"],
    subcategories: [
      { id: "protein-bowls", slug: "protein-bowls", displayName: "Protein Bowls", matchTags: ["bowl", "protein"] },
      { id: "grill-lean", slug: "grill-lean", displayName: "Grill Lean", matchTags: ["grill", "chicken", "fish"] },
      { id: "training-week", slug: "training-week", displayName: "Training Week", matchTags: ["lean", "healthy"] },
    ],
  }),

  cat({
    id: "pizza_night",
    slug: "pizza-night",
    displayName: "Pizza Night",
    tagline: "Hall table pizza — not delivery boxes",
    editorialDescription:
      "Dedicated pizza culture: dough decisions, bake timing, topping logic, and crew-scale pie nights. Separate generator, same Firehall trust bar.",
    emoji: "🍕",
    sortOrder: 6,
    feedPriority: 85,
    emotional: {
      headline: "Friday energy without the franchise",
      shiftContexts: ["weekend_watch", "slow_night"],
      crewDynamics: ["full_hall", "rookie_led"],
      cravingType: "communal fun",
      trustPromise: "Pizza Night is its own craft — intentional, not frozen.",
      firefighterHook: "When the hall smells like a pizzeria",
    },
    visual: {
      themeToken: "ember",
      palettePrimary: "#C62828",
      paletteAccent: "#FFAB00",
      lighting: "oven-glow warmth, cheese bubble highlights, rustic board",
      typographyMood: "playful bold — neighborhood pizzeria meets hall",
      textureNotes: ["cheese bubble", "charred crust", "stretch pull"],
      steamLevel: "subtle",
      platingDensity: "hearty",
    },
    imagery: {
      shotPresetAffinity: ["pizza"],
      promptLighting: "warm oven glow, cheese stretch moment, rustic board",
      promptMood: "communal pizza night, crew-sized pie, appetizing not greasy",
      promptTexture: "bubbling cheese, leopard crust, controlled oil sheen",
      negativePromptHints: ["frozen pizza box", "delivery logo", "soggy center"],
    },
    recommendation: {
      shiftUrgency: 0.45,
      crewScale: 0.85,
      comfortSeeking: 0.75,
      performanceFocus: 0.3,
      socialSharing: 0.95,
      skillFloor: 0.5,
      appetiteBoost: 9,
    },
    scoring: {
      titleKeywords: ["pizza", "pie", "pepperoni", "mozzarella", "flatbread"],
      mealTypeAffinity: ["pizza"],
      cuisineAffinity: ["italian", "american"],
      proteinAffinity: ["any", "pork", "beef"],
    },
    tagSlugs: ["game_day", "comfort"],
    legacyExplorePools: ["trending", "handheld"],
    subcategories: [
      { id: "classic-pies", slug: "classic-pies", displayName: "Classic Pies", matchTags: ["pepperoni", "cheese"] },
      { id: "creative-toppings", slug: "creative-toppings", displayName: "Creative Toppings", matchTags: ["specialty", "creative"] },
      { id: "sheet-pan-pizza", slug: "sheet-pan-pizza", displayName: "Sheet Pan Pizza", matchTags: ["sheet", "feed"] },
    ],
  }),

  cat({
    id: "big_crew_feeders",
    slug: "big-crew-feeders",
    displayName: "Big Crew Feeders",
    tagline: "Feeds 8–20 without chaos",
    editorialDescription:
      "Large-batch math, one-pot scaling, and tray dinners for big halls. Built for seconds, thirds, and the rookie who shows up hungry.",
    emoji: "🍽️",
    sortOrder: 7,
    feedPriority: 82,
    emotional: {
      headline: "Nobody leaves hungry",
      shiftContexts: ["weekend_watch", "slow_night"],
      crewDynamics: ["large_batch", "full_hall"],
      cravingType: "abundance",
      trustPromise: "Portions and steps that scale — not home-recipe fantasy.",
      firefighterHook: "When the whole hall rolls in starving",
    },
    visual: {
      themeToken: "copper",
      palettePrimary: "#4E342E",
      paletteAccent: "#FF8F00",
      lighting: "wide table spread, multiple vessels, family-style depth",
      typographyMood: "generous scale — big headlines, confident portions",
      textureNotes: ["full sheet pans", "ladle steam", "stacked proteins"],
      steamLevel: "prominent",
      platingDensity: "hearty",
    },
    imagery: {
      shotPresetAffinity: ["sheet_pan", "soup_chili", "bowl", "plated_main"],
      promptLighting: "wide generous spread, family-style, multiple dishes implied",
      promptMood: "big hall abundance, crew-scale portions, ladle-ready",
      promptTexture: "generous portions, steam from big pots, sheet pan depth",
      negativePromptHints: ["single tiny plate", "tasting menu", "minimal portion"],
    },
    recommendation: {
      shiftUrgency: 0.35,
      crewScale: 0.98,
      comfortSeeking: 0.65,
      performanceFocus: 0.45,
      socialSharing: 0.8,
      skillFloor: 0.45,
      appetiteBoost: 8,
    },
    scoring: {
      titleKeywords: ["feeds", "batch", "crowd", "tray", "sheet", "pot", "hall"],
      mealTypeAffinity: ["sheet_pan", "one_pot", "soup_chili", "casserole", "pasta"],
      cuisineAffinity: ["american", "mexican", "italian"],
      proteinAffinity: ["beef", "chicken", "pork"],
      minCrewSizeBoost: 8,
    },
    tagSlugs: ["feeds_hard", "high_protein"],
    legacyExplorePools: ["hearty", "one_pot", "trending"],
    subcategories: [
      { id: "sheet-pan-trays", slug: "sheet-pan-trays", displayName: "Sheet Pan & Trays", matchTags: ["sheet", "tray"] },
      { id: "one-pot-big", slug: "one-pot-big", displayName: "One-Pot Big Batches", matchTags: ["pot", "dutch", "batch"] },
      { id: "line-feed", slug: "line-feed", displayName: "Line Feed", matchTags: ["feeds", "line"] },
    ],
  }),

  cat({
    id: "breakfast_brunch",
    slug: "breakfast-brunch",
    displayName: "Breakfast & Brunch",
    tagline: "Morning shift or all-day hall brunch",
    editorialDescription:
      "Eggs, hashes, pancakes-at-dinner energy, and brunch spreads when the hall eats like a diner. Comfort without the dinner-only box.",
    emoji: "🍳",
    sortOrder: 8,
    feedPriority: 70,
    emotional: {
      headline: "Diner energy at the station",
      shiftContexts: ["pre_shift", "slow_night", "weekend_watch"],
      crewDynamics: ["full_hall", "pair_cook"],
      cravingType: "morning comfort",
      trustPromise: "Breakfast-for-dinner done on purpose.",
      firefighterHook: "When the hall wants eggs and coffee vibes",
    },
    visual: {
      themeToken: "hearth",
      palettePrimary: "#F57C00",
      paletteAccent: "#FFF8E1",
      lighting: "soft morning window light, golden yolks, steam from coffee-adjacent warmth",
      typographyMood: "diner friendly — rounded, approachable",
      textureNotes: ["crispy bacon", "runny yolk", "butter gloss"],
      steamLevel: "subtle",
      platingDensity: "standard",
    },
    imagery: {
      shotPresetAffinity: ["breakfast", "plated_main", "skillet"],
      promptLighting: "soft morning kitchen light, golden breakfast tones",
      promptMood: "diner brunch energy, appetizing breakfast-for-dinner",
      promptTexture: "crispy edges, yolk richness, butter sheen",
      negativePromptHints: ["dinner steak focus", "dark moody only"],
    },
    recommendation: {
      shiftUrgency: 0.5,
      crewScale: 0.65,
      comfortSeeking: 0.8,
      performanceFocus: 0.35,
      socialSharing: 0.7,
      skillFloor: 0.6,
      appetiteBoost: 7,
    },
    scoring: {
      titleKeywords: ["breakfast", "brunch", "egg", "pancake", "waffle", "hash", "bacon"],
      mealTypeAffinity: ["breakfast", "skillet", "sandwich", "plated_main"],
      cuisineAffinity: ["american", "canadian"],
      proteinAffinity: ["pork", "chicken", "any"],
    },
    tagSlugs: ["comfort", "shift_night"],
    legacyExplorePools: ["breakfast"],
    subcategories: [
      { id: "egg-skillets", slug: "egg-skillets", displayName: "Egg Skillets", matchTags: ["egg", "skillet"] },
      { id: "diner-plates", slug: "diner-plates", displayName: "Diner Plates", matchTags: ["pancake", "waffle", "hash"] },
      { id: "brunch-spread", slug: "brunch-spread", displayName: "Brunch Spread", matchTags: ["brunch"] },
    ],
  }),

  cat({
    id: "global_flavors",
    slug: "global-flavors",
    displayName: "Global Flavors",
    tagline: "World plates scaled for the hall",
    editorialDescription:
      "Mexican, Italian, Asian, Mediterranean, and Caribbean-leaning nights — real cuisine identity, not vague 'Asian Beef Main' metadata. Tortillas when it says tacos.",
    emoji: "🌍",
    sortOrder: 9,
    feedPriority: 78,
    emotional: {
      headline: "Travel the menu without leaving the hall",
      shiftContexts: ["slow_night", "weekend_watch"],
      crewDynamics: ["full_hall", "pair_cook"],
      cravingType: "flavor adventure",
      trustPromise: "Coherent cuisine — title, ingredients, and image align.",
      firefighterHook: "Big flavors the whole table argues about",
    },
    visual: {
      themeToken: "ocean",
      palettePrimary: "#1565C0",
      paletteAccent: "#D84315",
      lighting: "vibrant cultural color, authentic garnish, not fusion confusion",
      typographyMood: "worldly editorial — confident, specific",
      textureNotes: ["fresh herbs", "spice gloss", "charred tortilla"],
      steamLevel: "subtle",
      platingDensity: "standard",
    },
    imagery: {
      shotPresetAffinity: ["tacos", "bowl", "pasta", "grill"],
      promptLighting: "vibrant authentic cuisine lighting, culturally coherent props",
      promptMood: "specific world cuisine, not generic fusion bowl",
      promptTexture: "cuisine-appropriate texture — char, herbs, sauce",
      negativePromptHints: ["generic grey bowl", "wrong cuisine props", "fusion mashup"],
    },
    recommendation: {
      shiftUrgency: 0.45,
      crewScale: 0.7,
      comfortSeeking: 0.55,
      performanceFocus: 0.5,
      socialSharing: 0.8,
      skillFloor: 0.5,
      appetiteBoost: 8,
    },
    scoring: {
      titleKeywords: ["mexican", "italian", "thai", "korean", "indian", "greek", "teriyaki", "curry", "jerk"],
      mealTypeAffinity: ["tacos", "pasta", "stir_fry", "bowl", "wrap"],
      cuisineAffinity: ["mexican", "italian", "asian", "thai", "indian", "mediterranean", "korean", "japanese"],
      proteinAffinity: ["chicken", "beef", "pork", "fish"],
    },
    tagSlugs: ["shift_night"],
    legacyExplorePools: ["handheld", "pasta", "bowl"],
    subcategories: [
      { id: "latin-night", slug: "latin-night", displayName: "Latin Night", matchTags: ["mexican", "taco", "burrito"] },
      { id: "asian-stir", slug: "asian-stir", displayName: "Asian Stir & Bowls", matchTags: ["teriyaki", "stir", "rice"] },
      { id: "med-italian", slug: "med-italian", displayName: "Med & Italian", matchTags: ["italian", "pasta", "greek"] },
    ],
  }),

  cat({
    id: "game_day_watch_party",
    slug: "game-day-watch-party",
    displayName: "Game Day & Watch Party",
    tagline: "Wings, dips, and hall couch energy",
    editorialDescription:
      "Handheld chaos for playoffs, fight nights, and the couch at the station. Sliders, wings, nachos, and shareable trays — social food with Firehall discipline.",
    emoji: "🏈",
    sortOrder: 10,
    feedPriority: 80,
    emotional: {
      headline: "Feed the couch crew",
      shiftContexts: ["weekend_watch", "slow_night"],
      crewDynamics: ["full_hall", "rookie_led"],
      cravingType: "social snacking",
      trustPromise: "Shareable — not sad frozen apps.",
      firefighterHook: "Playoffs, pay-per-view, and a hungry hall couch",
    },
    visual: {
      themeToken: "ember",
      palettePrimary: "#1B5E20",
      paletteAccent: "#FFD600",
      lighting: "high-energy snack spread, finger-food close-ups, bold color pops",
      typographyMood: "sports-night bold — loud, fun, confident",
      textureNotes: ["crispy wings", "melty nacho cheese", "dip gloss"],
      steamLevel: "none",
      platingDensity: "hearty",
    },
    imagery: {
      shotPresetAffinity: ["burger", "tacos", "sandwich"],
      promptLighting: "fun watch-party spread lighting, crispy finger food hero",
      promptMood: "game day shareable energy, crowd appetizers, not formal dinner",
      promptTexture: "crispy wings, cheese melt, dip texture",
      negativePromptHints: ["formal plating", "fine dining", "tiny amuse bouche"],
    },
    recommendation: {
      shiftUrgency: 0.4,
      crewScale: 0.75,
      comfortSeeking: 0.7,
      performanceFocus: 0.25,
      socialSharing: 0.98,
      skillFloor: 0.55,
      appetiteBoost: 9,
    },
    scoring: {
      titleKeywords: ["wing", "slider", "nacho", "dip", "game day", "watch", "loaded", "finger"],
      mealTypeAffinity: ["loaded_fries", "burger", "sandwich", "tacos", "wrap"],
      cuisineAffinity: ["american", "mexican", "bbq"],
      proteinAffinity: ["chicken", "beef", "pork"],
    },
    tagSlugs: ["game_day", "comfort"],
    legacyExplorePools: ["game_day", "handheld"],
    subcategories: [
      { id: "wings-dips", slug: "wings-dips", displayName: "Wings & Dips", matchTags: ["wing", "dip", "buffalo"] },
      { id: "sliders-line", slug: "sliders-line", displayName: "Sliders Line", matchTags: ["slider", "burger"] },
      { id: "nacho-trays", slug: "nacho-trays", displayName: "Nacho Trays", matchTags: ["nacho", "loaded"] },
    ],
  }),

  cat({
    id: "meal_prep_leftovers",
    slug: "meal-prep-leftovers",
    displayName: "Meal Prep & Leftovers",
    tagline: "Cook once, feed the hall twice",
    editorialDescription:
      "Batch-friendly meals that reheat on shift two, locker-friendly portions, and intentional leftovers — not sad repeat microwave mystery.",
    emoji: "📦",
    sortOrder: 11,
    feedPriority: 65,
    emotional: {
      headline: "Sunday cook, Tuesday save",
      shiftContexts: ["meal_prep_sunday", "pre_shift"],
      crewDynamics: ["solo_cook", "pair_cook"],
      cravingType: "practical planning",
      trustPromise: "Reheat instructions and storage reality included.",
      firefighterHook: "When you need tomorrow handled tonight",
    },
    visual: {
      themeToken: "steel",
      palettePrimary: "#455A64",
      paletteAccent: "#78909C",
      lighting: "clean organized prep containers, label-ready clarity, still appetizing",
      typographyMood: "organized practical — checklist friendly",
      textureNotes: ["portion containers", "fresh reheat steam", "layered grains"],
      steamLevel: "subtle",
      platingDensity: "standard",
    },
    imagery: {
      shotPresetAffinity: ["bowl", "sheet_pan", "plated_main"],
      promptLighting: "clean meal-prep clarity, fresh reheat steam on serve shot",
      promptMood: "organized batch cooking, still craveable on reheat",
      promptTexture: "distinct meal-prep zones, fresh garnish on reheat",
      negativePromptHints: ["soggy reheat", "mystery container grey mush"],
    },
    recommendation: {
      shiftUrgency: 0.3,
      crewScale: 0.6,
      comfortSeeking: 0.5,
      performanceFocus: 0.7,
      socialSharing: 0.4,
      skillFloor: 0.65,
      appetiteBoost: 3,
    },
    scoring: {
      titleKeywords: ["meal prep", "batch", "leftover", "reheat", "make ahead", "freezer"],
      mealTypeAffinity: ["bowl", "sheet_pan", "one_pot", "casserole"],
      cuisineAffinity: ["american", "mediterranean", "asian"],
      proteinAffinity: ["chicken", "beef", "turkey"],
    },
    tagSlugs: ["meal_prep", "freezer_friendly"],
    legacyExplorePools: ["slow", "one_pot", "healthy"],
    subcategories: [
      { id: "batch-protein", slug: "batch-protein", displayName: "Batch Protein", matchTags: ["batch", "chicken", "beef"] },
      { id: "freezer-hall", slug: "freezer-hall", displayName: "Freezer Hall", matchTags: ["freezer", "freeze"] },
      { id: "reheat-winners", slug: "reheat-winners", displayName: "Reheat Winners", matchTags: ["reheat", "leftover"] },
    ],
  }),

  cat({
    id: "rookie_friendly",
    slug: "rookie-friendly",
    displayName: "Rookie-Friendly Meals",
    tagline: "Hard to screw up under pressure",
    editorialDescription:
      "Forgiving techniques, clear temps, and steps that assume chaos — for probies on cook duty or vets on no-sleep nights. Confidence on the line.",
    emoji: "🎓",
    sortOrder: 12,
    feedPriority: 86,
    emotional: {
      headline: "Nobody gets thrown under the bus",
      shiftContexts: ["busy_night", "pre_shift"],
      crewDynamics: ["rookie_led", "solo_cook"],
      cravingType: "confidence",
      trustPromise: "Explicit temps, times, and recovery steps.",
      firefighterHook: "When the probie drew cook duty",
    },
    visual: {
      themeToken: "steel",
      palettePrimary: "#0277BD",
      paletteAccent: "#4FC3F7",
      lighting: "clear bright instructional clarity, approachable not intimidating",
      typographyMood: "friendly coach — clear steps, zero ego",
      textureNotes: ["obvious doneness cues", "simple one-pan", "clear protein cut"],
      steamLevel: "subtle",
      platingDensity: "standard",
    },
    imagery: {
      shotPresetAffinity: ["sheet_pan", "bowl", "skillet", "plated_main"],
      promptLighting: "bright clear approachable kitchen, obvious appetizing result",
      promptMood: "confidence-building home-cook success, not cheffy intimidation",
      promptTexture: "clearly cooked protein, simple appetizing finish",
      negativePromptHints: ["complex fine dining", "ambiguous raw", "chef tweezer garnish"],
    },
    recommendation: {
      shiftUrgency: 0.6,
      crewScale: 0.5,
      comfortSeeking: 0.45,
      performanceFocus: 0.4,
      socialSharing: 0.55,
      skillFloor: 0.95,
      appetiteBoost: 5,
    },
    scoring: {
      titleKeywords: ["easy", "simple", "beginner", "basic", "one pan", "sheet pan"],
      mealTypeAffinity: ["sheet_pan", "one_pot", "skillet", "bowl", "burger"],
      cuisineAffinity: ["american", "italian", "mexican"],
      proteinAffinity: ["chicken", "beef", "any"],
      maxMinutesBoost: 45,
    },
    tagSlugs: ["rookie_friendly", "quick_cleanup", "one_pan"],
    legacyExplorePools: ["quick", "one_pot"],
    subcategories: [
      { id: "one-pan-wins", slug: "one-pan-wins", displayName: "One-Pan Wins", matchTags: ["one pan", "sheet"] },
      { id: "temp-clear", slug: "temp-clear", displayName: "Clear Temps & Times", matchTags: ["165", "temp"] },
      { id: "probie-first", slug: "probie-first", displayName: "Probie First Meals", matchTags: ["easy", "simple"] },
    ],
  }),
];

export const MASTER_CATEGORIES_BY_ID: Record<
  MasterCategoryDefinition["id"],
  MasterCategoryDefinition
> = Object.fromEntries(MASTER_CATEGORY_DEFINITIONS.map((c) => [c.id, c])) as Record<
  MasterCategoryDefinition["id"],
  MasterCategoryDefinition
>;
