-- Firehall Meals — Postgres init schema (production-critical persistence only).
--
-- Moves auth/billing/preferences/meal-history/cloud-sync out of local SQLite
-- (server/sqlite.ts) so Firehall Meals Pro has a real, durable, concurrent-
-- safe source of truth. Ported 1:1 from the SQLite migrations listed below;
-- see docs/database-backup.md and PRODUCTION DATABASE MIGRATION PLAN for
-- context. Hall Pro (hall_subscriptions, halls, hall_memberships) and
-- analytics_events are INTENTIONALLY NOT included — they stay on SQLite.
--
-- Ported from: 014_user_accounts, 020_shift_reminders, 045_ingredient_preferences,
-- 048_auth_identities, 047_user_meal_history, 017_user_cloud_sync,
-- 044_user_data_snapshots_canonical_keys, 016_billing, 046_stripe_billing,
-- 042_firefighter_plus_plan.
--
-- Conventions carried over from SQLite (kept identical on purpose to
-- minimize application-code churn):
--   * booleans are INTEGER 0/1, not native BOOLEAN
--   * JSON payloads are TEXT (JSON.stringify/JSON.parse at the app layer)
--   * timestamps are TIMESTAMPTZ; app layer reads them back as JS Date and
--     calls .toISOString() to reproduce the exact string shape SQLite gave
-- Postgres DOES enforce these foreign keys (SQLite's sql.js wrapper never
-- did — see server/sqlite.ts pragma() no-op), which is a genuine integrity
-- improvement, not a behavior change application code depends on.

CREATE TABLE IF NOT EXISTS users (
  user_id TEXT PRIMARY KEY,
  email TEXT UNIQUE,
  auth_provider TEXT NOT NULL CHECK (auth_provider IN ('guest', 'email', 'google', 'apple')),
  provider_subject TEXT,
  is_guest INTEGER NOT NULL DEFAULT 0,
  device_session_id TEXT,
  hall_pro_enabled INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_login_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_device_session ON users(device_session_id);

CREATE TABLE IF NOT EXISTS user_profiles (
  user_id TEXT PRIMARY KEY REFERENCES users(user_id) ON DELETE CASCADE,
  first_name TEXT,
  last_name TEXT,
  display_name TEXT,
  profile_photo_url TEXT,
  department TEXT,
  hall_name TEXT,
  shift_label TEXT,
  crew_size INTEGER,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS user_preferences (
  user_id TEXT PRIMARY KEY REFERENCES users(user_id) ON DELETE CASCADE,
  preferred_proteins_json TEXT NOT NULL DEFAULT '[]',
  dietary_restrictions_json TEXT NOT NULL DEFAULT '[]',
  appliance_preferences_json TEXT NOT NULL DEFAULT '[]',
  excluded_ingredients_json TEXT NOT NULL DEFAULT '[]',
  shift_reminders_enabled INTEGER NOT NULL DEFAULT 0,
  shift_days_json TEXT NOT NULL DEFAULT '[]',
  shift_reminder_time TEXT NOT NULL DEFAULT '18:00',
  shift_reminder_timezone TEXT NOT NULL DEFAULT 'America/New_York',
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS auth_sessions (
  session_token_hash TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_auth_sessions_user ON auth_sessions(user_id);

CREATE TABLE IF NOT EXISTS auth_magic_links (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  token_hash TEXT NOT NULL UNIQUE,
  email TEXT NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  used_at TIMESTAMPTZ,
  return_to TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_auth_magic_links_email ON auth_magic_links(email);

CREATE TABLE IF NOT EXISTS user_saved_recipes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  recipe_key TEXT NOT NULL,
  recipe_json TEXT NOT NULL,
  saved_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(user_id, recipe_key)
);

CREATE INDEX IF NOT EXISTS idx_user_saved_recipes_user ON user_saved_recipes(user_id);

-- GOOGLE SIGN-IN SAFETY — (provider, provider_subject) -> single user_id,
-- enforced at the database level via the composite primary key.
CREATE TABLE IF NOT EXISTS auth_identities (
  provider TEXT NOT NULL CHECK (provider IN ('email', 'google', 'apple')),
  provider_subject TEXT NOT NULL,
  user_id TEXT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  email_at_link_time TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (provider, provider_subject)
);

CREATE INDEX IF NOT EXISTS idx_auth_identities_user_id ON auth_identities(user_id);

-- Firehall Meals Pro V1 Feature 3 — Meal Memory. Append-only event log.
CREATE TABLE IF NOT EXISTS user_meal_history (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  recipe_slug TEXT NOT NULL,
  cooked_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_user_meal_history_user_cooked
  ON user_meal_history(user_id, cooked_at DESC, id DESC);

-- Cloud sync snapshots (personal-first sync + legacy hall_* keys).
CREATE TABLE IF NOT EXISTS user_data_snapshots (
  user_id TEXT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  data_key TEXT NOT NULL CHECK (data_key IN (
    'hall_favorites',
    'hall_history',
    'wheel_streak',
    'hall_profile',
    'personal_favorites',
    'personal_meal_history',
    'cooking_preferences'
  )),
  snapshot_json TEXT NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  PRIMARY KEY (user_id, data_key)
);

CREATE INDEX IF NOT EXISTS idx_user_data_snapshots_user ON user_data_snapshots(user_id);

-- Monetization: plan catalog / feature flags / personal subscriptions.
-- hall_subscriptions is DELIBERATELY NOT ported — Hall Pro stays on SQLite.
CREATE TABLE IF NOT EXISTS plan_catalog (
  plan_id TEXT PRIMARY KEY,
  display_name TEXT NOT NULL,
  tagline TEXT NOT NULL DEFAULT '',
  price_label TEXT NOT NULL DEFAULT 'Free',
  enabled INTEGER NOT NULL DEFAULT 1,
  sort_order INTEGER NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS plan_feature_flags (
  plan_id TEXT NOT NULL REFERENCES plan_catalog(plan_id) ON DELETE CASCADE,
  feature_key TEXT NOT NULL,
  enabled INTEGER NOT NULL DEFAULT 1,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (plan_id, feature_key)
);

CREATE TABLE IF NOT EXISTS user_subscriptions (
  user_id TEXT PRIMARY KEY REFERENCES users(user_id) ON DELETE CASCADE,
  plan_id TEXT NOT NULL REFERENCES plan_catalog(plan_id),
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'trialing', 'past_due', 'cancelled')),
  source TEXT NOT NULL DEFAULT 'self_select' CHECK (source IN ('self_select', 'admin_grant', 'stripe')),
  selected_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at TIMESTAMPTZ,
  stripe_customer_id TEXT,
  stripe_subscription_id TEXT,
  stripe_price_id TEXT,
  cancel_at_period_end INTEGER NOT NULL DEFAULT 0,
  current_period_end TIMESTAMPTZ,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_user_subscriptions_plan ON user_subscriptions(plan_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_user_subscriptions_stripe_customer
  ON user_subscriptions(stripe_customer_id) WHERE stripe_customer_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_user_subscriptions_stripe_subscription
  ON user_subscriptions(stripe_subscription_id) WHERE stripe_subscription_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS billing_global_flags (
  flag_key TEXT PRIMARY KEY,
  enabled INTEGER NOT NULL DEFAULT 1,
  description TEXT,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Stripe webhook idempotency — Stripe redelivers events; never double-apply.
CREATE TABLE IF NOT EXISTS stripe_webhook_events (
  event_id TEXT PRIMARY KEY,
  event_type TEXT NOT NULL,
  received_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Seed data (matches 016_billing.sql / 042_firefighter_plus_plan.sql).
-- Note: hall_pro sort_order matches the final state after 042's UPDATE.
INSERT INTO plan_catalog (plan_id, display_name, tagline, price_label, enabled, sort_order) VALUES
  ('guest', 'Guest', 'Cook tonight — no account needed', 'Free', 1, 0),
  ('personal', 'Personal', 'Free forever — sync your meals across every device.', 'Free', 1, 1),
  ('firefighter_plus', 'Firehall Meals Pro', 'Find the right meal faster.', '$4.99/month', 1, 2),
  ('hall_pro', 'Hall Pro', 'Shared hall identity for your crew', 'Coming soon', 1, 3)
ON CONFLICT (plan_id) DO NOTHING;

INSERT INTO billing_global_flags (flag_key, enabled, description) VALUES
  ('monetization_enabled', 1, 'Master switch for plan selection UI'),
  ('payments_enabled', 0, 'Stripe/checkout — off until launch')
ON CONFLICT (flag_key) DO NOTHING;
