-- Firehall Meals Goals + Progress (V1) — additive, backward-compatible.
--
-- Per-meal tag capture: real, already-served RecipeTags.high_protein /
-- .high_fiber booleans (the exact same tags shown elsewhere in the app —
-- see shared/schema.ts RecipeTags) captured at "Mark as Cooked" time.
-- NULL (unknown) for any row recorded before this shipped, or for a recipe
-- that never had recipe_tags — never backfilled, never guessed.
ALTER TABLE user_meal_history ADD COLUMN IF NOT EXISTS is_high_protein INTEGER;
ALTER TABLE user_meal_history ADD COLUMN IF NOT EXISTS is_high_fiber INTEGER;

-- One row per (user, goal_type, calendar month) — the user's chosen target
-- for that goal that month. Progress itself is ALWAYS computed live from
-- user_meal_history at read time (see server/goals/store.ts) — never
-- duplicated or cached here, so it can never drift from real history.
CREATE TABLE IF NOT EXISTS user_goals (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  goal_type TEXT NOT NULL CHECK (goal_type IN (
    'new_meals', 'shift_meals', 'high_protein_shifts', 'healthier_meals',
    'plant_forward_meals', 'nutrition_goal_match'
  )),
  target INTEGER NOT NULL CHECK (target > 0),
  month_key TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (user_id, goal_type, month_key)
);

CREATE INDEX IF NOT EXISTS idx_user_goals_user_month ON user_goals(user_id, month_key);
