-- Personal firefighter schedule — repeating pattern + one-off overrides.
--
-- Future shifts are NOT stored. Shift instances are generated
-- deterministically from the pattern and overrides by shared/schedule/engine.ts,
-- so editing the pattern never leaves stale rows and nothing needs backfilling.
--
-- One personal schedule per user (crew/hall linking is out of scope).
-- All local date/time values are interpreted in user_schedules.timezone.

CREATE TABLE IF NOT EXISTS user_schedules (
  user_id TEXT PRIMARY KEY REFERENCES users(user_id) ON DELETE CASCADE,
  -- IANA zone, validated by the application (Intl).
  timezone TEXT NOT NULL,
  -- Local date + clock time at which cycle position 0 begins.
  anchor_date DATE NOT NULL,
  start_time TEXT NOT NULL CHECK (start_time ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$'),
  -- Ordered repeating sequence: [{"kind":"on"|"off","minutes":int}, ...].
  -- Always read and written as a whole, so it lives on the row.
  pattern_json TEXT NOT NULL,
  -- Informational: which shortcut produced the pattern. Never interpreted.
  preset_id TEXT,
  default_crew_size INTEGER NOT NULL CHECK (default_crew_size BETWEEN 1 AND 200),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- One-off changes. Never mutate the pattern.
--   extra  : Add Extra Shift — start_local/end_local required, shift_key NULL.
--   cancel : Not Working This Shift — shift_key required.
--   modify : modified start/end and/or temporary crew size — shift_key required.
-- shift_key is the generated occurrence's scheduled local start
-- ('YYYY-MM-DDTHH:MM'). Overrides whose key no longer matches the pattern
-- (after a pattern edit) are kept but ignored by the engine.
CREATE TABLE IF NOT EXISTS user_schedule_overrides (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES user_schedules(user_id) ON DELETE CASCADE,
  kind TEXT NOT NULL CHECK (kind IN ('extra', 'cancel', 'modify')),
  shift_key TEXT,
  start_local TEXT,
  end_local TEXT,
  crew_size INTEGER CHECK (crew_size IS NULL OR crew_size BETWEEN 1 AND 200),
  note TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (
    (kind = 'extra' AND shift_key IS NULL AND start_local IS NOT NULL AND end_local IS NOT NULL)
    OR (kind = 'cancel' AND shift_key IS NOT NULL AND start_local IS NULL AND end_local IS NULL AND crew_size IS NULL)
    OR (kind = 'modify' AND shift_key IS NOT NULL
        AND (start_local IS NOT NULL OR end_local IS NOT NULL OR crew_size IS NOT NULL))
  )
);

-- At most one cancel-or-modify per generated occurrence.
CREATE UNIQUE INDEX IF NOT EXISTS idx_user_schedule_overrides_occurrence
  ON user_schedule_overrides(user_id, shift_key)
  WHERE shift_key IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_user_schedule_overrides_user
  ON user_schedule_overrides(user_id);
