import fs from "node:fs";
import path from "node:path";

/** Primary writable dir (Vite public — copied into dist on build). */
export function clientGeneratedImageDir(): string {
  return path.join(process.cwd(), "client", "public", "images", "generated");
}

/** Runtime mirror for production static server (no rebuild required). */
export function distGeneratedImageDir(): string {
  return path.join(process.cwd(), "dist", "public", "images", "generated");
}

export function imageExtensionForBuffer(buf: Buffer): "jpg" | "png" {
  if (buf[0] === 0x89 && buf[1] === 0x50) return "png";
  return "jpg";
}

/** Write generated bytes to all serve locations so dev + prod + Replit deploy see the file. */
export function mirrorGeneratedImageFile(filename: string, buffer: Buffer): {
  primaryPath: string;
  mirrored: string[];
} {
  const dirs = [clientGeneratedImageDir()];
  if (process.env.NODE_ENV === "production") {
    dirs.push(distGeneratedImageDir());
  }

  const mirrored: string[] = [];
  let primaryPath = "";

  for (const dir of dirs) {
    fs.mkdirSync(dir, { recursive: true });
    const absolute = path.join(dir, filename);
    fs.writeFileSync(absolute, buffer);
    if (!primaryPath) primaryPath = absolute;
    mirrored.push(absolute);
  }

  return { primaryPath, mirrored };
}

export function resolveAbsolutePathForPublicUrl(publicPath: string): string | null {
  const rel = publicPath.replace(/^\//, "");
  const candidates = [
    path.join(process.cwd(), "dist", "public", rel),
    path.join(process.cwd(), "client", "public", rel),
  ];
  for (const p of candidates) {
    if (fs.existsSync(p)) return p;
  }
  return null;
}

export function publicImageFileExists(publicPath: string): boolean {
  return resolveAbsolutePathForPublicUrl(publicPath) != null;
}
