/**
 * Pizza Night curated catalog — exactly 20 hall-tested pies.
 */

import { goldenEntry } from "../golden-100/entry.js";
import type { GoldenRecipeDefinition } from "../golden-100/types.js";

/** Alphabetical by title — do not reorder without updating the Pizza Night page sort. */
export const PIZZA_NIGHT_RECIPES: GoldenRecipeDefinition[] = [
  goldenEntry({
    slug: "bbq-chicken-pizza",
    title: "BBQ Chicken Pizza",
    cat: "pizza_night",
    protein: "chicken",
    cuisine: "american",
    format: "pizza",
    pools: ["handheld", "bbq"],
    hook: "Sweet BBQ, red onion, cilantro",
    search: "bbq chicken pizza",
    img: { shotPreset: "pizza" },
  }),
  goldenEntry({
    slug: "breakfast-sausage-pizza",
    title: "Breakfast Sausage Gravy Pizza",
    cat: "pizza_night",
    protein: "pork",
    cuisine: "american",
    format: "pizza",
    pools: ["breakfast", "handheld"],
    hook: "Brunch pie for the late shift",
    search: "breakfast sausage gravy pizza",
    img: { shotPreset: "pizza", lightingStyle: "morning_soft" },
  }),
  goldenEntry({
    slug: "buffalo-chicken-pizza",
    title: "Buffalo Chicken Pizza",
    cat: "pizza_night",
    protein: "chicken",
    cuisine: "american",
    format: "pizza",
    pools: ["handheld", "game_day"],
    hook: "Blue cheese, hot sauce, crispy chicken",
    search: "buffalo chicken pizza",
    img: { shotPreset: "pizza" },
  }),
  goldenEntry({
    slug: "pepperoni-pizza-night",
    title: "Classic Pepperoni Pizza",
    cat: "pizza_night",
    protein: "pork",
    cuisine: "italian",
    format: "pizza",
    pools: ["handheld", "trending"],
    hook: "Friday hall pie — not delivery",
    search: "homemade pepperoni pizza",
    img: { shotPreset: "pizza", lightingStyle: "warm_editorial" },
  }),
  goldenEntry({
    slug: "detroit-style-pizza",
    title: "Detroit-Style Pepperoni Pizza",
    cat: "pizza_night",
    protein: "pork",
    cuisine: "american",
    format: "pizza",
    pools: ["handheld"],
    hook: "Crispy cheese edges, thick crust",
    search: "detroit style pepperoni pizza",
    img: { shotPreset: "pizza" },
  }),
  goldenEntry({
    slug: "firehall-supreme-pizza",
    title: "Firehall Supreme Pizza",
    cat: "pizza_night",
    protein: "pork",
    cuisine: "american",
    format: "pizza",
    pools: ["handheld", "big_crew"],
    hook: "Pepperoni, sausage, peppers, mushrooms",
    search: "supreme pizza loaded toppings",
    img: { shotPreset: "pizza" },
  }),
  goldenEntry({
    slug: "four-cheese-white-pizza",
    title: "Four-Cheese White Pizza",
    cat: "pizza_night",
    protein: "vegetarian",
    cuisine: "italian",
    format: "pizza",
    pools: ["handheld"],
    hook: "Creamy white pie, no red sauce",
    search: "four cheese white pizza",
    img: { shotPreset: "pizza" },
  }),
  goldenEntry({
    slug: "margherita-pizza",
    title: "Fresh Margherita Pizza",
    cat: "pizza_night",
    protein: "vegetarian",
    cuisine: "italian",
    format: "pizza",
    pools: ["handheld"],
    hook: "Basil, mozzarella, blistered crust",
    search: "margherita pizza fresh mozzarella",
    img: { shotPreset: "pizza" },
  }),
  goldenEntry({
    slug: "hawaiian-pizza",
    title: "Hawaiian Pizza",
    cat: "pizza_night",
    protein: "pork",
    cuisine: "american",
    format: "pizza",
    pools: ["handheld"],
    hook: "Ham, pineapple, sweet-savory",
    search: "hawaiian pizza ham pineapple",
    img: { shotPreset: "pizza" },
  }),
  goldenEntry({
    slug: "honey-soppressata-pizza",
    title: "Hot Honey Soppressata Pizza",
    cat: "pizza_night",
    protein: "pork",
    cuisine: "italian",
    format: "pizza",
    pools: ["handheld"],
    hook: "Sweet heat, charred salami",
    search: "hot honey soppressata pizza",
    img: { shotPreset: "pizza" },
  }),
  goldenEntry({
    slug: "jalapeno-popper-pizza",
    title: "Jalapeño Popper Pizza",
    cat: "pizza_night",
    protein: "pork",
    cuisine: "american",
    format: "pizza",
    pools: ["handheld", "game_day"],
    hook: "Cream cheese, bacon, pickled heat",
    search: "jalapeno popper pizza",
    img: { shotPreset: "pizza" },
  }),
  goldenEntry({
    slug: "meat-lovers-sheet-pizza",
    title: "Meat Lover's Sheet Pan Pizza",
    cat: "pizza_night",
    protein: "pork",
    cuisine: "american",
    format: "pizza",
    pools: ["handheld", "big_crew"],
    hook: "Feeds the crew from one tray",
    search: "meat lovers sheet pan pizza",
    img: { shotPreset: "pizza" },
  }),
  goldenEntry({
    slug: "nashville-hot-chicken-pizza",
    title: "Nashville Hot Chicken Pizza",
    cat: "pizza_night",
    protein: "chicken",
    cuisine: "american",
    format: "pizza",
    pools: ["handheld", "trending"],
    hook: "Cayenne heat, pickles, ranch drizzle",
    search: "nashville hot chicken pizza",
    img: { shotPreset: "pizza" },
  }),
  goldenEntry({
    slug: "pesto-chicken-pizza",
    title: "Pesto Chicken Pizza",
    cat: "pizza_night",
    protein: "chicken",
    cuisine: "italian",
    format: "pizza",
    pools: ["handheld"],
    hook: "Basil pesto, sun-dried tomato, chicken",
    search: "pesto chicken pizza",
    img: { shotPreset: "pizza" },
  }),
  goldenEntry({
    slug: "philly-cheesesteak-pizza",
    title: "Philly Cheesesteak Pizza",
    cat: "pizza_night",
    protein: "beef",
    cuisine: "american",
    format: "pizza",
    pools: ["handheld"],
    hook: "Steak, peppers, provolone on dough",
    search: "philly cheesesteak pizza",
    img: { shotPreset: "pizza" },
  }),
  goldenEntry({
    slug: "sicilian-sheet-pizza",
    title: "Sicilian Sheet Pan Pizza",
    cat: "pizza_night",
    protein: "pork",
    cuisine: "italian",
    format: "pizza",
    pools: ["handheld", "big_crew"],
    hook: "Thick focaccia-style squares",
    search: "sicilian sheet pan pizza",
    img: { shotPreset: "pizza" },
  }),
  goldenEntry({
    slug: "smoked-brisket-bbq-pizza",
    title: "Smoked Brisket BBQ Pizza",
    cat: "pizza_night",
    protein: "beef",
    cuisine: "american",
    format: "pizza",
    pools: ["handheld", "bbq"],
    hook: "Leftover brisket, tangy sauce",
    search: "smoked brisket bbq pizza",
    img: { shotPreset: "pizza" },
  }),
  goldenEntry({
    slug: "taco-pizza",
    title: "Taco Pizza",
    cat: "pizza_night",
    protein: "beef",
    cuisine: "american",
    format: "pizza",
    pools: ["handheld", "game_day"],
    hook: "Seasoned beef, lettuce, chips on top",
    search: "taco pizza ground beef",
    img: { shotPreset: "pizza" },
  }),
  goldenEntry({
    slug: "veggie-supreme-pizza",
    title: "Veggie Supreme Pizza",
    cat: "pizza_night",
    protein: "vegetarian",
    cuisine: "italian",
    format: "pizza",
    pools: ["handheld", "healthy"],
    hook: "Roasted peppers, mushrooms, olives",
    search: "veggie supreme pizza",
    img: { shotPreset: "pizza" },
  }),
  goldenEntry({
    slug: "white-garlic-chicken-pizza",
    title: "White Garlic Chicken Pizza",
    cat: "pizza_night",
    protein: "chicken",
    cuisine: "italian",
    format: "pizza",
    pools: ["handheld"],
    hook: "Creamy white pie, roasted garlic",
    search: "white sauce chicken pizza",
    img: { shotPreset: "pizza" },
  }),
];

export const PIZZA_NIGHT_COUNT = PIZZA_NIGHT_RECIPES.length;
