import { bbqRecipe, manifestEntry } from "../bbq-30/recipe-build.js";
import type { BbqRecipe } from "../bbq-30/types.js";
import { BBQ_30_RECIPES } from "../bbq-30/recipes.js";
import { BATCH_30_BBQ_GRILL_RECIPES } from "./batch-30-bbq-grill-recipes.js";

const BBQ_30_BATCH_SLUGS = [
  "carolina-vinegar-pulled-pork",
  "honey-chipotle-chicken-thighs",
  "smoked-chicken-quarters-white-sauce",
  "brisket-style-beef-sandwiches-au-jus",
  "hot-honey-grilled-sausage-peppers",
  "bbq-bacon-cheddar-burgers",
] as const;

function pickFromBbq30(slugs: readonly string[]): BbqRecipe[] {
  return slugs.map((slug) => {
    const recipe = BBQ_30_RECIPES.find((r) => r.manifest.slug === slug);
    if (!recipe) throw new Error(`Missing BBQ_30 recipe: ${slug}`);
    return recipe;
  });
}

const NEW_BATCH_25_RECIPES: BbqRecipe[] = [
  bbqRecipe({
    manifest: manifestEntry({
      slug: "texas-central-brisket-crew",
      title: "Texas Central Brisket for the Crew",
      subtitle: "Salt-and-pepper bark, post-oak smoke, and sliced platters for ten",
      protein: "beef",
      cuisine: "American",
      mealFormat: "bbq",
      pools: ["bbq", "beef", "big_crew"],
      hook: "Central Texas whole-packer smoke that feeds the hall without fuss",
      prep: 45,
      cook: 480,
      difficulty: "hard",
    }),
    description:
      "Adapted from classic Central Texas pit tradition (Amazing Ribs, Meat Church): a whole packer brisket gets a simple salt-and-pepper rub, smokes low over post oak until probe-tender, rests, and slices against the grain for the crew.",
    whyCrewsLikeIt:
      "Real brisket night credibility without a sweet glaze. Slices clean, holds in foil at 170°F between calls, and tastes better after a short rest.",
    stationTimingNotes:
      "Start 10–12 hours before service. Once wrapped, brisket can finish in a 275°F oven. Hold whole wrapped in a cooler up to 4 hours, or slice and hold covered at 170°F with a splash of beef broth for 90 minutes.",
    allergyNotes: "Rub is gluten-free. Serve pickles and white bread on the side; check labels for allergens.",
    equipment: ["smoker", "butcher paper", "foil", "instant-read thermometer", "probe thermometer", "sharp slicing knife", "cooler"],
    ingredients: [
      { name: "whole packer brisket", quantity: 14, unit: "lb", notes: "trimmed" },
      { name: "kosher salt", quantity: 0.33, unit: "cup" },
      { name: "coarse black pepper", quantity: 0.33, unit: "cup" },
      { name: "garlic powder", quantity: 1, unit: "tbsp" },
      { name: "yellow mustard", quantity: 3, unit: "tbsp", notes: "binder" },
      { name: "beef broth", quantity: 2, unit: "cups", notes: "for holding" },
      { name: "dill pickle chips", quantity: 2, unit: "cups" },
      { name: "white onion", quantity: 1, unit: "whole", notes: "thin-sliced" },
      { name: "white bread", quantity: 20, unit: "slices" },
    ],
    stepLines: [
      { title: "Trim the packer", instruction: "Trim fat cap to 1/4 inch. Square the ends and remove hard silver skin so the rub adheres evenly. Let brisket sit at room temp 45 minutes while smoker preheats.", minutes: 45 },
      { title: "Season and rest", instruction: "Coat brisket with mustard binder. Mix salt, pepper, and garlic powder; pack rub evenly on all sides. Rest on a rack 20 minutes while smoker stabilizes at 250°F with post oak.", minutes: 20 },
      { title: "Smoke to color", instruction: "Place brisket fat-side up on smoker at 250°F. Smoke until bark is dark mahogany and internal temp hits 165°F in the flat, about 6–7 hours. Spritz with water only if surface looks dry.", minutes: 360, heatLevel: "low" },
      { title: "Wrap through the stall", instruction: "Wrap tightly in butcher paper when bark color looks right. Continue at 250°F until probe slides like butter and flat reads 203°F, about 3–4 hours.", minutes: 180 },
      { title: "Rest in the cooler", instruction: "Rest wrapped brisket at least 60 minutes in an insulated cooler so juices redistribute. Do not unwrap early or slices will run dry.", minutes: 60 },
      { title: "Slice and hold", instruction: "Slice flat against the grain into 1/4-inch slices. Toss lightly with warm beef broth. Hold covered at 170°F in a hotel pan with foil until service.", minutes: 20 },
      { title: "Tonight's board", instruction: "Serve sliced brisket on butcher paper with pickles, raw onion, and white bread. Call temps: flat pulled at 203°F, held at 170°F max.", minutes: 5 },
      { title: "Leftovers", instruction: "Chop trim and ends into chopped-beef sandwiches with extra broth. Reheat slices covered at 325°F until 165°F internal.", minutes: 10 },
    ],
    proTips: [
      "Pull at 203°F in the flat—don't chase a higher number or lean slices dry out.",
      "Save the point for burnt ends on a future shift or dice into beans.",
      "If the stall runs long, wrap earlier rather than opening the smoker repeatedly.",
    ],
    tonightSpread: ["Sliced brisket on butcher paper, pickles, onion, and white bread.", "Simple pinto beans and saltines for a Texas-style plate."],
    leftovers: ["Chopped brisket tacos with pickled onion.", "Brisket hash with potatoes and eggs for morning shift."],
    searchTerms: ["texas brisket", "central texas", "packer brisket", "post oak"],
    relatedSlugs: ["firehall-burnt-ends-platter", "pepper-smoked-brisket-flat", "brisket-style-beef-sandwiches-au-jus"],
    cleanupDifficulty: "heavy",
  }),

  bbqRecipe({
    manifest: manifestEntry({
      slug: "firehall-burnt-ends-platter",
      title: "Firehall Burnt Ends Platter",
      subtitle: "Caramelized brisket point cubes, sticky glaze, and pickles for ten",
      protein: "beef",
      cuisine: "American",
      mealFormat: "bbq",
      pools: ["bbq", "beef", "comfort"],
      hook: "Kansas City-style burnt ends without waiting on a full packer cook",
      prep: 30,
      cook: 420,
      difficulty: "hard",
    }),
    description:
      "Adapted from classic Kansas City burnt-end tradition (Amazing Ribs, BBQ Pit Boys): brisket point smokes until tender, gets cubed, glazed, and finished until the edges turn sticky and charred.",
    whyCrewsLikeIt:
      "Burnt ends are the reward cut—loud, sweet, and smoky. They hold warm in a covered pan and disappear fast at the line.",
    stationTimingNotes:
      "Smoke point early. Cube and glaze right before service or hold glazed cubes covered at 170°F up to 45 minutes. Re-crisp under broiler 2 minutes if they soften.",
    allergyNotes: "Glaze contains honey. Check BBQ sauce labels for gluten and fish (Worcestershire).",
    equipment: ["smoker", "foil", "sheet pans", "instant-read thermometer", "mixing bowl", "tongs"],
    ingredients: [
      { name: "brisket point", quantity: 6, unit: "lb", notes: "or untrimmed point from a packer" },
      { name: "kosher salt", quantity: 3, unit: "tbsp" },
      { name: "coarse black pepper", quantity: 3, unit: "tbsp" },
      { name: "brown sugar", quantity: 3, unit: "tbsp" },
      { name: "smoked paprika", quantity: 2, unit: "tbsp" },
      { name: "garlic powder", quantity: 2, unit: "tbsp" },
      { name: "BBQ sauce", quantity: 1.5, unit: "cups" },
      { name: "honey", quantity: 0.25, unit: "cup" },
      { name: "apple cider vinegar", quantity: 2, unit: "tbsp" },
      { name: "unsalted butter", quantity: 3, unit: "tbsp" },
      { name: "dill pickle chips", quantity: 1.5, unit: "cups" },
      { name: "white bread", quantity: 15, unit: "slices" },
    ],
    stepLines: [
      { title: "Season the point", instruction: "Pat point dry. Mix salt, pepper, brown sugar, paprika, and garlic powder; rub all sides. Rest 15 minutes while smoker heats to 275°F.", minutes: 15 },
      { title: "Smoke until tender", instruction: "Smoke point fat-side up at 275°F until bark is set and internal temp reaches 165°F, about 4 hours.", minutes: 240, heatLevel: "low" },
      { title: "Wrap and finish", instruction: "Wrap in foil with a splash of apple cider vinegar. Continue at 275°F until probe-tender and 203°F internal, about 2–3 hours.", minutes: 150 },
      { title: "Rest and cube", instruction: "Rest wrapped 30 minutes. Cube point into 1-inch bites, discarding excess hard fat and gristle.", minutes: 30 },
      { title: "Build the glaze", instruction: "Simmer BBQ sauce, honey, vinegar, and butter until glossy. Toss cubed burnt ends to coat evenly.", minutes: 8 },
      { title: "Caramelize the edges", instruction: "Spread glazed cubes on sheet pans. Return to smoker or 375°F oven 15–20 minutes, stirring once, until edges char and glaze sets sticky.", minutes: 20, heatLevel: "medium" },
      { title: "Hold and serve", instruction: "Hold covered at 170°F with foil vented slightly. Serve on a platter with pickles and white bread for burnt-end sandwiches.", minutes: 5 },
      { title: "Leftovers", instruction: "Reheat covered at 325°F with extra sauce. Chop into mac and cheese or loaded fries.", minutes: 10 },
    ],
    proTips: [
      "Point needs 203°F—lean on probe tenderness, not the clock.",
      "Stir once during the glaze bake so edges caramelize evenly.",
      "If you only have a flat, save it for sliced service; burnt ends want point fat.",
    ],
    tonightSpread: ["Burnt ends in a hotel pan with extra glaze on the side.", "Pickles and white bread for quick sandwiches."],
    leftovers: ["Burnt-end grilled cheese with extra pickles.", "Fold into baked beans for a smoky second-day pot."],
    searchTerms: ["burnt ends", "kansas city", "brisket point", "sticky glaze"],
    relatedSlugs: ["texas-central-brisket-crew", "pepper-smoked-brisket-flat", "smoked-baked-beans-crew"],
    cleanupDifficulty: "medium",
  }),

  bbqRecipe({
    manifest: manifestEntry({
      slug: "overnight-smoked-brisket-hold",
      title: "Overnight Smoked Brisket Hold",
      subtitle: "Low-and-slow packer that finishes before shift and holds hot for ten",
      protein: "beef",
      cuisine: "American",
      mealFormat: "bbq",
      pools: ["bbq", "beef", "big_crew"],
      hook: "Start at midnight, slice at dinner—built for hall scheduling",
      prep: 40,
      cook: 480,
      difficulty: "hard",
    }),
    description:
      "Adapted from classic overnight brisket hold methods (Traeger, Hey Grill Hey): a trimmed packer rides 225°F through the night, wraps in the stall, finishes probe-tender, and rests in a cooler until the crew rolls in.",
    whyCrewsLikeIt:
      "The cook happens while the hall sleeps. By dinner you have rested, slice-ready brisket without babysitting the pit between calls.",
    stationTimingNotes:
      "Plan 12–14 hours total. Hold whole wrapped brisket in a cooler up to 6 hours. For extended hold, slice and pan with broth at 170°F—never above 175°F or lean meat dries.",
    allergyNotes: "Rub is gluten-free. Broth may contain soy—check labels.",
    equipment: ["smoker", "probe thermometer", "butcher paper", "foil", "cooler", "instant-read thermometer", "slicing knife"],
    ingredients: [
      { name: "whole packer brisket", quantity: 12, unit: "lb", notes: "trimmed" },
      { name: "kosher salt", quantity: 0.25, unit: "cup" },
      { name: "coarse black pepper", quantity: 0.25, unit: "cup" },
      { name: "onion powder", quantity: 1, unit: "tbsp" },
      { name: "beef broth", quantity: 3, unit: "cups", notes: "for holding" },
      { name: "yellow mustard", quantity: 2, unit: "tbsp", notes: "binder" },
      { name: "pickle chips", quantity: 2, unit: "cups" },
      { name: "Texas toast", quantity: 10, unit: "slices" },
    ],
    stepLines: [
      { title: "Prep and season", instruction: "Trim fat cap to 1/4 inch. Coat with mustard, then salt, pepper, and onion powder. Rest 30 minutes while smoker preheats to 225°F.", minutes: 30 },
      { title: "Overnight smoke", instruction: "Place brisket fat-side up at 225°F. Smoke undisturbed until internal temp reaches 160–165°F and bark is set, about 7–8 hours.", minutes: 420, heatLevel: "low" },
      { title: "Wrap for the finish", instruction: "Wrap in butcher paper with a splash of broth. Continue at 225°F until flat probes 203°F and feels like soft butter, about 3–4 hours.", minutes: 180 },
      { title: "Cooler rest", instruction: "Rest wrapped brisket in an insulated cooler at least 90 minutes—this is where the magic happens for slice-ready meat.", minutes: 90 },
      { title: "Slice for service", instruction: "Unwrap, slice flat against the grain 1/4 inch thick. Toss lightly with warm broth. Reserve point for burnt ends or chop for sandwiches.", minutes: 25 },
      { title: "170°F warm hold", instruction: "Transfer sliced brisket to a hotel pan, add 1/2 cup broth, cover tightly with foil, and hold at 170°F until the line opens.", minutes: 10 },
      { title: "Tonight's board", instruction: "Brisket tray with broth for moistening, pickles, and toast. Call it: overnight brisket—slice and stack.", minutes: 5 },
      { title: "Leftovers", instruction: "Vacuum or wrap tight; reheat slices in hot broth at 325°F covered until 165°F internal.", minutes: 10 },
    ],
    proTips: [
      "Use a leave-in probe alarm so you don't have to wake up to check temps.",
      "Cooler rest is not optional—it's how you hit a 6 AM finish with noon service.",
      "If brisket finishes early, keep it whole wrapped in the cooler; slice on demand.",
    ],
    tonightSpread: ["Sliced brisket in a hotel pan with broth.", "Pickles, onion, and Texas toast for sandwiches."],
    leftovers: ["Brisket breakfast burritos with eggs and salsa.", "Chop into chili for the next cold shift."],
    searchTerms: ["overnight brisket", "brisket hold", "225 smoke", "cooler rest"],
    relatedSlugs: ["texas-central-brisket-crew", "firehall-burnt-ends-platter", "brisket-style-beef-sandwiches-au-jus"],
    cleanupDifficulty: "heavy",
  }),

  bbqRecipe({
    manifest: manifestEntry({
      slug: "pepper-smoked-brisket-flat",
      title: "Pepper-Crusted Smoked Brisket Flat",
      subtitle: "Lean flat with bold pepper bark sliced thin for ten",
      protein: "beef",
      cuisine: "American",
      mealFormat: "bbq",
      pools: ["bbq", "beef", "sandwich"],
      hook: "Texas-style pepper bark on a flat that slices clean and holds on the line",
      prep: 30,
      cook: 420,
      difficulty: "hard",
    }),
    description:
      "Adapted from classic Texas pepper brisket flat tradition (BBQ Pit Boys, Weber): a trimmed flat gets equal parts salt and coarse pepper, smokes until 203°F, and slices thin for sandwiches or plates.",
    whyCrewsLikeIt:
      "Flat is leaner than point but still delivers smoke-night credibility. Thin slices stretch across the hall and reheat without turning greasy.",
    stationTimingNotes:
      "Trim early. Flat can stall for hours—wrap when bark color is right. Hold sliced beef at 170°F with broth; never above 175°F.",
    allergyNotes: "Rub is gluten-free. White bread contains gluten.",
    equipment: ["smoker", "butcher paper", "instant-read thermometer", "slicing knife", "cooler", "hotel pan"],
    ingredients: [
      { name: "whole brisket flat", quantity: 8, unit: "lb", notes: "trimmed" },
      { name: "kosher salt", quantity: 0.33, unit: "cup" },
      { name: "coarse black pepper", quantity: 0.33, unit: "cup" },
      { name: "garlic powder", quantity: 1, unit: "tbsp" },
      { name: "yellow mustard", quantity: 2, unit: "tbsp", notes: "binder" },
      { name: "beef broth", quantity: 2, unit: "cups", notes: "for holding" },
      { name: "pickle chips", quantity: 2, unit: "cups" },
      { name: "white bread", quantity: 20, unit: "slices" },
      { name: "raw white onion", quantity: 1, unit: "whole", notes: "thin-sliced" },
    ],
    stepLines: [
      { title: "Trim and season", instruction: "Trim fat cap to 1/4 inch. Coat flat with mustard, then pack evenly with salt, pepper, and garlic powder. Rest 30 minutes while smoker preheats to 225°F.", minutes: 40 },
      { title: "Smoke the flat", instruction: "Place flat fat-side up at 225°F with oak or post oak. Smoke until internal temp reaches 165°F and bark is set, about 4–5 hours.", minutes: 240, heatLevel: "low" },
      { title: "Wrap through the stall", instruction: "Wrap in butcher paper when bark color looks right and internal temp stalls near 165°F. Continue until probe-tender at 203°F, about 2–3 hours.", minutes: 150 },
      { title: "Rest the brisket", instruction: "Rest wrapped flat at least 45 minutes in a cooler so juices redistribute. Unwrap and slice against the grain into 1/4-inch slices.", minutes: 45 },
      { title: "Hold with broth", instruction: "Toss sliced beef lightly with warm broth. Transfer to hotel pan, cover with foil, hold at 170°F until service.", minutes: 10 },
      { title: "Serve Texas-style", instruction: "Serve on buttered white bread with pickles and raw onion, or on platters for plate service.", minutes: 15 },
      { title: "Leftovers", instruction: "Chop trimmings into chopped-beef sandwiches with extra broth. Reheat slices covered at 325°F until 165°F.", minutes: 10 },
    ],
    proTips: [
      "Flat dries faster than point—pull at 203°F, not higher.",
      "Slice only what you need for first service; keep remainder whole until second pass.",
      "If time is tight, finish wrapped flat in a 275°F oven while monitoring probe tenderness.",
    ],
    tonightSpread: ["Thin-sliced brisket on butcher paper with white bread, pickles, and onion.", "Simple pinto beans for a classic smoke-night plate."],
    leftovers: ["Chop into chili for the next cold-night pot.", "Reheat in broth on toasted rolls with horseradish mayo."],
    searchTerms: ["brisket flat", "pepper crust", "texas brisket", "thin sliced"],
    relatedSlugs: ["texas-central-brisket-crew", "firehall-burnt-ends-platter", "brisket-style-beef-sandwiches-au-jus"],
    cleanupDifficulty: "medium",
  }),

  bbqRecipe({
    manifest: manifestEntry({
      slug: "kansas-city-pulled-pork-sandwiches",
      title: "Kansas City Pulled Pork Sandwiches",
      subtitle: "Sweet-smoky shoulder, thick BBQ sauce, and soft buns for ten",
      protein: "pork",
      cuisine: "American",
      mealFormat: "sandwich",
      pools: ["bbq", "handheld", "big_crew"],
      hook: "KC-style pull that holds hot and builds sandwiches fast",
      prep: 25,
      cook: 480,
      difficulty: "medium",
    }),
    description:
      "Adapted from classic Kansas City pulled pork tradition (Amazing Ribs, Meat Church): pork shoulder smokes with a balanced sweet rub, gets pulled into juices, and served with thick tomato-molasses BBQ sauce on soft buns.",
    whyCrewsLikeIt:
      "KC sauce is crowd-pleasing and forgiving. Pulled pork holds covered at 170°F for hours and the sandwich line moves fast.",
    stationTimingNotes:
      "Start early shift. Once pulled, hold covered at 170°F with a ladle of sauce and drippings for up to 2 hours. Wrap earlier if the smoker schedule slips.",
    allergyNotes: "Buns contain gluten. BBQ sauce may contain Worcestershire (fish).",
    equipment: ["smoker", "foil", "instant-read thermometer", "large pan", "heat-proof gloves", "tongs"],
    ingredients: [
      { name: "bone-in pork shoulder", quantity: 10, unit: "lb" },
      { name: "kosher salt", quantity: 4, unit: "tbsp" },
      { name: "brown sugar", quantity: 4, unit: "tbsp" },
      { name: "smoked paprika", quantity: 2, unit: "tbsp" },
      { name: "garlic powder", quantity: 2, unit: "tbsp" },
      { name: "onion powder", quantity: 2, unit: "tbsp" },
      { name: "yellow mustard", quantity: 0.25, unit: "cup", notes: "binder" },
      { name: "ketchup", quantity: 1, unit: "cup" },
      { name: "molasses", quantity: 0.25, unit: "cup" },
      { name: "apple cider vinegar", quantity: 0.25, unit: "cup" },
      { name: "Worcestershire sauce", quantity: 2, unit: "tbsp" },
      { name: "buns", quantity: 12, unit: "whole" },
      { name: "coleslaw mix", quantity: 10, unit: "cups" },
    ],
    stepLines: [
      { title: "Season the shoulder", instruction: "Coat shoulder with mustard binder. Mix salt, brown sugar, paprika, garlic, and onion powder; rub all over. Rest 20 minutes while smoker heats to 250°F.", minutes: 20 },
      { title: "Smoke low", instruction: "Smoke shoulder fat-side up at 250°F until bark is dark and internal temp hits 165°F, about 5–6 hours.", minutes: 330, heatLevel: "low" },
      { title: "Build KC sauce", instruction: "Simmer ketchup, molasses, vinegar, and Worcestershire 10 minutes until thick. Reserve 1 cup for finishing; rest for pulling.", minutes: 10 },
      { title: "Wrap and finish", instruction: "Wrap tightly in foil. Continue at 250°F (or 275°F oven) until probe slides like butter and internal temp is 203°F, about 2–3 hours.", minutes: 150 },
      { title: "Rest and pull", instruction: "Rest wrapped 45 minutes. Pour juices into a pan. Pull pork, discarding large fat. Stir in juices and KC sauce to taste.", minutes: 50 },
      { title: "170°F hold", instruction: "Transfer pulled pork to hotel pan, cover with foil, hold at 170°F until service. Stir in extra sauce if surface dries.", minutes: 5 },
      { title: "Tonight's board", instruction: "Pulled pork pan with ladle, buns, slaw, and extra sauce. Build-your-own sandwich line.", minutes: 5 },
      { title: "Leftovers", instruction: "Reheat covered with splash of water or sauce at 325°F until 165°F. Use in nachos or loaded potatoes.", minutes: 10 },
    ],
    proTips: [
      "203°F is the pull temp—don't stop at 190°F or you'll fight the shoulder.",
      "Mix slaw into the sandwich for classic KC crunch.",
      "Finishing sauce after pulling keeps flavor bright without cooking off vinegar.",
    ],
    tonightSpread: ["Pulled pork in a hotel pan with ladle.", "Buns, slaw, pickles, and extra KC sauce on the side."],
    leftovers: ["Pulled pork quesadillas with pepper jack.", "BBQ pork fried rice with scallions."],
    searchTerms: ["kansas city pulled pork", "kc bbq", "pork shoulder smoke", "sweet bbq"],
    relatedSlugs: ["memphis-dry-rub-pulled-pork", "carolina-vinegar-pulled-pork", "smoked-baked-beans-crew"],
    cleanupDifficulty: "heavy",
  }),

  bbqRecipe({
    manifest: manifestEntry({
      slug: "memphis-dry-rub-pulled-pork",
      title: "Memphis Dry-Rub Pulled Pork",
      subtitle: "Paprika-coffee rub, no sauce on the meat, and slaw buns for ten",
      protein: "pork",
      cuisine: "American",
      mealFormat: "sandwich",
      pools: ["bbq", "handheld", "big_crew"],
      hook: "Memphis-style pull where the rub does the talking",
      prep: 30,
      cook: 480,
      difficulty: "medium",
    }),
    description:
      "Adapted from classic Memphis dry-rub tradition (Amazing Ribs, Meat Church): shoulder gets a bold paprika-coffee rub, smokes without saucing the meat, and serves with tangy slaw on buns—sauce on the side only.",
    whyCrewsLikeIt:
      "Dry-rub pork tastes clean and smoky, not sweet. Holds beautifully at 170°F and lets crews choose their sauce level.",
    stationTimingNotes:
      "Apply rub the night before if possible. Hold pulled pork covered at 170°F up to 2 hours. Keep sauce separate so bark stays crisp.",
    allergyNotes: "Rub is gluten-free. Buns contain gluten. Coffee rub is optional for caffeine-sensitive crews.",
    equipment: ["smoker", "foil", "instant-read thermometer", "large pan", "mixing bowl", "tongs"],
    ingredients: [
      { name: "bone-in pork shoulder", quantity: 10, unit: "lb" },
      { name: "kosher salt", quantity: 4, unit: "tbsp" },
      { name: "brown sugar", quantity: 3, unit: "tbsp" },
      { name: "smoked paprika", quantity: 3, unit: "tbsp" },
      { name: "garlic powder", quantity: 2, unit: "tbsp" },
      { name: "onion powder", quantity: 2, unit: "tbsp" },
      { name: "ground cumin", quantity: 1, unit: "tbsp" },
      { name: "instant coffee", quantity: 2, unit: "tbsp", notes: "fine ground" },
      { name: "black pepper", quantity: 2, unit: "tbsp" },
      { name: "yellow mustard", quantity: 0.25, unit: "cup", notes: "binder" },
      { name: "buns", quantity: 12, unit: "whole" },
      { name: "coleslaw mix", quantity: 12, unit: "cups" },
      { name: "mayonnaise", quantity: 0.5, unit: "cup" },
      { name: "apple cider vinegar", quantity: 0.25, unit: "cup" },
      { name: "BBQ sauce", quantity: 1, unit: "cup", notes: "optional, on the side" },
    ],
    stepLines: [
      { title: "Build Memphis rub", instruction: "Mix salt, brown sugar, paprika, garlic, onion, cumin, coffee, and pepper. Coat shoulder with mustard, then pack rub on all sides. Rest 30 minutes.", minutes: 30 },
      { title: "Smoke at 250°F", instruction: "Smoke shoulder fat-side up at 250°F until bark is mahogany and internal temp reaches 165°F, about 5–6 hours. Do not mop or sauce the meat.", minutes: 330, heatLevel: "low" },
      { title: "Wrap to 203°F", instruction: "Wrap in foil when bark is set. Continue at 250°F until probe-tender and 203°F internal, about 2–3 hours.", minutes: 150 },
      { title: "Rest and pull", instruction: "Rest wrapped 45 minutes. Pull into a pan with defatted juices only—no sauce mixed in. Keep bark pieces mixed through for texture.", minutes: 50 },
      { title: "Tangy slaw", instruction: "Toss slaw with mayo, vinegar, and pinch of salt. Chill until service.", minutes: 10 },
      { title: "Hold at 170°F", instruction: "Cover pulled pork with foil and hold at 170°F. Serve sauce on the side in a squeeze bottle.", minutes: 5 },
      { title: "Tonight's board", instruction: "Dry-rub pork, slaw, buns, optional sauce. Call it Memphis-style—slaw on the sandwich, sauce if you want it.", minutes: 5 },
      { title: "Leftovers", instruction: "Reheat covered with a splash of apple juice. Chop into tacos with slaw and hot sauce.", minutes: 10 },
    ],
    proTips: [
      "Coffee in the rub adds depth without making the pork taste like breakfast.",
      "Never sauce the meat before pulling—Memphis style keeps bark intact.",
      "Mix some slaw into the sandwich for the classic contrast of smoky and tangy.",
    ],
    tonightSpread: ["Pulled pork in a pan with bark visible.", "Slaw, buns, and optional sauce on the side."],
    leftovers: ["Memphis pork nachos with slaw on top.", "Pork and pickle grilled cheese."],
    searchTerms: ["memphis dry rub", "coffee rub pork", "dry rub pulled pork", "memphis bbq"],
    relatedSlugs: ["kansas-city-pulled-pork-sandwiches", "texas-smoked-pulled-pork-shoulder", "carolina-vinegar-pulled-pork"],
    cleanupDifficulty: "heavy",
  }),

  bbqRecipe({
    manifest: manifestEntry({
      slug: "texas-smoked-pulled-pork-shoulder",
      title: "Texas Smoked Pulled Pork Shoulder",
      subtitle: "Salt-and-pepper shoulder, no sweet sauce, and pickles for ten",
      protein: "pork",
      cuisine: "American",
      mealFormat: "bbq",
      pools: ["bbq", "pork", "big_crew"],
      hook: "Texas pit-style shoulder that pulls clean and holds all shift",
      prep: 25,
      cook: 480,
      difficulty: "medium",
    }),
    description:
      "Adapted from classic Texas smoked pork shoulder tradition (Hey Grill Hey, BBQ Pit Boys): bone-in shoulder gets a simple salt-and-pepper rub, smokes over oak until 203°F, and pulls with defatted drippings—no sweet sauce.",
    whyCrewsLikeIt:
      "Texas pork is about smoke and meat, not sugar. It holds at 170°F for hours and pairs with pickles and white bread like brisket.",
    stationTimingNotes:
      "Start early. Wrap when bark color is right. Hold pulled pork covered at 170°F with a splash of defatted drippings. Pickles and onions stay cold on ice.",
    allergyNotes: "Rub is gluten-free. White bread contains gluten.",
    equipment: ["smoker", "foil", "instant-read thermometer", "large pan", "heat-proof gloves"],
    ingredients: [
      { name: "bone-in pork shoulder", quantity: 10, unit: "lb" },
      { name: "kosher salt", quantity: 4, unit: "tbsp" },
      { name: "coarse black pepper", quantity: 3, unit: "tbsp" },
      { name: "garlic powder", quantity: 1, unit: "tbsp" },
      { name: "yellow mustard", quantity: 3, unit: "tbsp", notes: "binder" },
      { name: "white bread", quantity: 15, unit: "slices" },
      { name: "dill pickle chips", quantity: 2, unit: "cups" },
      { name: "raw white onion", quantity: 1, unit: "whole", notes: "thin-sliced" },
      { name: "hot sauce", quantity: 0.5, unit: "cup", notes: "optional, on the side" },
    ],
    stepLines: [
      { title: "Season Texas-style", instruction: "Coat shoulder with mustard. Pack salt, pepper, and garlic powder on all sides. Rest 20 minutes while smoker heats to 275°F with oak.", minutes: 20 },
      { title: "Smoke the shoulder", instruction: "Smoke fat-side up at 275°F until bark is dark and internal temp reaches 165°F, about 4–5 hours.", minutes: 270, heatLevel: "low" },
      { title: "Wrap and finish", instruction: "Wrap in foil with a splash of apple cider vinegar. Continue at 275°F until probe-tender and 203°F, about 2–3 hours.", minutes: 150 },
      { title: "Rest and pull", instruction: "Rest wrapped 40 minutes. Skim fat from juices. Pull pork, mixing in defatted drippings to moisten.", minutes: 45 },
      { title: "170°F warm hold", instruction: "Transfer to hotel pan, cover with foil, hold at 170°F. Stir before service if top dries.", minutes: 5 },
      { title: "Tonight's board", instruction: "Pulled pork tray with pickles, onion, white bread, and hot sauce on the side. Texas-style—no sweet glaze.", minutes: 5 },
      { title: "Leftovers", instruction: "Reheat covered at 325°F with splash of broth until 165°F. Use in breakfast tacos with eggs.", minutes: 10 },
    ],
    proTips: [
      "275°F speeds the cook vs 225°F—still tender if you hit 203°F.",
      "Skim fat from drippings or pulled pork turns greasy on the hold line.",
      "Hot sauce on the side keeps purists and heat-seekers both happy.",
    ],
    tonightSpread: ["Pulled pork in a hotel pan.", "Pickles, onion, white bread, and hot sauce."],
    leftovers: ["Texas pork breakfast tacos with scrambled eggs.", "Mix into smoked baked beans for second-day depth."],
    searchTerms: ["texas pulled pork", "smoked pork shoulder", "salt pepper pork", "oak smoke"],
    relatedSlugs: ["kansas-city-pulled-pork-sandwiches", "alabama-white-sauce-pulled-pork", "carolina-vinegar-pulled-pork"],
    cleanupDifficulty: "heavy",
  }),

  bbqRecipe({
    manifest: manifestEntry({
      slug: "alabama-white-sauce-pulled-pork",
      title: "Alabama White Sauce Pulled Pork",
      subtitle: "Smoked shoulder finished with tangy mayo-vinegar sauce for ten",
      protein: "pork",
      cuisine: "American",
      mealFormat: "sandwich",
      pools: ["bbq", "handheld", "big_crew"],
      hook: "Northern Alabama white sauce on pulled pork—bright, tangy, holds well",
      prep: 25,
      cook: 480,
      difficulty: "medium",
    }),
    description:
      "Adapted from classic Alabama white BBQ sauce tradition (Amazing Ribs, Hey Grill Hey): pork shoulder smokes with a simple rub, gets pulled, and tossed with tangy mayo-vinegar white sauce for sandwiches.",
    whyCrewsLikeIt:
      "White sauce cuts through rich pork and stays creamy on the hold line. Different from red BBQ without being weird—crews love the tang.",
    stationTimingNotes:
      "Make white sauce early and chill. Pull pork and toss with sauce just before service, or hold sauced pork covered at 170°F up to 90 minutes.",
    allergyNotes: "White sauce contains egg (mayo). Buns contain gluten.",
    equipment: ["smoker", "foil", "instant-read thermometer", "large pan", "mixing bowl", "whisk"],
    ingredients: [
      { name: "bone-in pork shoulder", quantity: 10, unit: "lb" },
      { name: "kosher salt", quantity: 4, unit: "tbsp" },
      { name: "black pepper", quantity: 2, unit: "tbsp" },
      { name: "smoked paprika", quantity: 2, unit: "tbsp" },
      { name: "garlic powder", quantity: 2, unit: "tbsp" },
      { name: "yellow mustard", quantity: 0.25, unit: "cup", notes: "binder" },
      { name: "mayonnaise", quantity: 1.5, unit: "cups" },
      { name: "apple cider vinegar", quantity: 0.75, unit: "cup" },
      { name: "lemon juice", quantity: 3, unit: "tbsp" },
      { name: "prepared horseradish", quantity: 2, unit: "tbsp" },
      { name: "cayenne", quantity: 1, unit: "tsp" },
      { name: "buns", quantity: 12, unit: "whole" },
      { name: "dill pickles", quantity: 1, unit: "cup", notes: "chopped" },
    ],
    stepLines: [
      { title: "Season the shoulder", instruction: "Coat with mustard binder. Rub with salt, pepper, paprika, and garlic powder. Rest 20 minutes while smoker heats to 250°F.", minutes: 20 },
      { title: "Smoke to 165°F", instruction: "Smoke shoulder fat-side up at 250°F until bark is set and internal temp hits 165°F, about 5–6 hours.", minutes: 330, heatLevel: "low" },
      { title: "Make white sauce", instruction: "Whisk mayo, vinegar, lemon juice, horseradish, cayenne, and pinch of salt. Chill until service.", minutes: 8 },
      { title: "Wrap to 203°F", instruction: "Wrap in foil. Continue at 250°F until probe-tender and 203°F internal, about 2–3 hours.", minutes: 150 },
      { title: "Rest, pull, and sauce", instruction: "Rest wrapped 40 minutes. Pull pork into a pan. Toss with white sauce to coat—start with 1 cup and add to taste.", minutes: 45 },
      { title: "Hold at 170°F", instruction: "Cover sauced pork with foil and hold at 170°F. Keep extra white sauce cold on ice for finishing.", minutes: 5 },
      { title: "Tonight's board", instruction: "White-sauce pulled pork, buns, chopped pickles, extra sauce. Alabama-style sandwiches.", minutes: 5 },
      { title: "Leftovers", instruction: "Reheat covered at 325°F. Refresh with cold white sauce after reheating so it stays tangy.", minutes: 10 },
    ],
    proTips: [
      "Toss with sauce after pulling—never mop raw shoulder with serving sauce.",
      "Horseradish is the secret bite; don't skip it.",
      "Chopped pickles on the sandwich add crunch that white sauce loves.",
    ],
    tonightSpread: ["Sauced pulled pork in a hotel pan.", "Buns, pickles, and extra white sauce on ice."],
    leftovers: ["White-sauce pork wraps with lettuce.", "Mix into potato salad for a tangy second-day lunch."],
    searchTerms: ["alabama white sauce", "white bbq pork", "mayo vinegar sauce", "northern alabama"],
    relatedSlugs: ["smoked-chicken-quarters-white-sauce", "carolina-vinegar-pulled-pork", "smoked-potato-salad-tray"],
    cleanupDifficulty: "heavy",
  }),

  bbqRecipe({
    manifest: manifestEntry({
      slug: "competition-bbq-chicken-thighs",
      title: "Competition BBQ Chicken Thighs",
      subtitle: "Skinned thighs, sweet rub, and glaze finish for ten judges—or ten firefighters",
      protein: "chicken",
      cuisine: "American",
      mealFormat: "grill",
      pools: ["bbq", "chicken", "trending"],
      hook: "Comp-turn thighs that hold warm and still look pro on the tray",
      prep: 30,
      cook: 90,
      difficulty: "medium",
    }),
    description:
      "Adapted from classic competition chicken thigh tradition (Traeger, Meat Church): bone-in thighs get trimmed and squared, rubbed, smoked at 275°F, glazed, and finished until skin bites and meat hits 175°F.",
    whyCrewsLikeIt:
      "Thighs are competition forgiving and hall practical. They hold covered at 170°F and still eat tender after a long hold.",
    stationTimingNotes:
      "Trim thighs early. Smoke in two batches if needed. Hold finished thighs covered at 170°F up to 45 minutes; glaze right before service.",
    allergyNotes: "Glaze contains honey. Rub is gluten-free.",
    equipment: ["smoker", "grill (optional)", "instant-read thermometer", "sheet pans", "basting brush", "sharp knife"],
    ingredients: [
      { name: "bone-in chicken thighs", quantity: 12, unit: "pieces", notes: "about 6 lb, skin-on" },
      { name: "kosher salt", quantity: 2, unit: "tbsp" },
      { name: "brown sugar", quantity: 3, unit: "tbsp" },
      { name: "smoked paprika", quantity: 2, unit: "tbsp" },
      { name: "garlic powder", quantity: 2, unit: "tbsp" },
      { name: "onion powder", quantity: 1, unit: "tbsp" },
      { name: "cayenne", quantity: 1, unit: "tsp" },
      { name: "honey", quantity: 0.33, unit: "cup" },
      { name: "BBQ sauce", quantity: 0.5, unit: "cup" },
      { name: "apple cider vinegar", quantity: 2, unit: "tbsp" },
      { name: "butter", quantity: 3, unit: "tbsp" },
    ],
    stepLines: [
      { title: "Trim competition-style", instruction: "Skin thighs and trim excess fat and flap meat for uniform pieces about 4 oz each. Square edges so they cook evenly. Pat dry.", minutes: 25 },
      { title: "Apply sweet rub", instruction: "Mix salt, brown sugar, paprika, garlic, onion, and cayenne. Coat thighs evenly. Rest 15 minutes while smoker heats to 275°F.", minutes: 15 },
      { title: "Smoke to 150°F", instruction: "Smoke thighs at 275°F until internal temp reaches 150°F and color looks even, about 45–55 minutes.", minutes: 50, heatLevel: "medium" },
      { title: "Build competition glaze", instruction: "Simmer honey, BBQ sauce, vinegar, and butter until glossy. Keep warm for basting.", minutes: 5 },
      { title: "Glaze and finish", instruction: "Brush thighs with glaze. Finish at 375°F on smoker or grill 8–10 minutes until glaze sets and internal temp hits 175°F.", minutes: 10, heatLevel: "high" },
      { title: "Rest and hold", instruction: "Rest thighs 5 minutes. Hold covered at 170°F with foil vented slightly until service.", minutes: 5 },
      { title: "Tonight's board", instruction: "Arrange thighs on a tray, glaze side up. Extra glaze on the side for dipping.", minutes: 3 },
      { title: "Leftovers", instruction: "Pull meat for wraps. Reheat covered at 325°F until 165°F internal.", minutes: 8 },
    ],
    proTips: [
      "175°F for dark meat thighs—165°F can read chewy on competition-style trims.",
      "Square pieces cook and glaze evenly; ragged thighs burn at the tips.",
      "Keep glaze warm but not boiling or honey will taste bitter.",
    ],
    tonightSpread: ["Glazed thighs on a sheet pan.", "Extra glaze in a ramekin for dipping."],
    leftovers: ["Chop into chicken salad with celery and grapes.", "Slice onto Caesar salad for a smoky lunch."],
    searchTerms: ["competition chicken", "bbq chicken thighs", "glazed thighs", "275 smoke"],
    relatedSlugs: ["honey-chipotle-chicken-thighs", "smoked-bbq-chicken-wings-tray", "hickory-smoked-chicken-breast"],
    cleanupDifficulty: "medium",
  }),

  bbqRecipe({
    manifest: manifestEntry({
      slug: "smoked-bbq-chicken-wings-tray",
      title: "Smoked BBQ Chicken Wings Tray",
      subtitle: "Dry-rub smoke, crisp finish, and sticky sauce for ten",
      protein: "chicken",
      cuisine: "American",
      mealFormat: "grill",
      pools: ["bbq", "chicken", "handheld"],
      hook: "Wings that smoke first, crisp second, and hold in a tray between calls",
      prep: 15,
      cook: 75,
      difficulty: "easy",
    }),
    description:
      "Adapted from classic smoked wing tradition (Hey Grill Hey, Weber): split wings get a dry rub, smoke at 250°F, then finish hot and toss in house BBQ sauce for a tray that feeds ten fast.",
    whyCrewsLikeIt:
      "Wings are handheld morale. Smoke adds depth without fryer mess, and they hold covered at 170°F for 30 minutes.",
    stationTimingNotes:
      "Season wings early. Smoke in two batches on wire racks. Finish and sauce right before service, or hold sauced wings covered at 170°F up to 30 minutes.",
    allergyNotes: "Sauce may contain Worcestershire (fish). Rub is gluten-free.",
    equipment: ["smoker", "grill or oven", "wire rack", "sheet pans", "large mixing bowl", "instant-read thermometer"],
    ingredients: [
      { name: "chicken wings", quantity: 8, unit: "lb", notes: "split into flats and drums" },
      { name: "kosher salt", quantity: 2, unit: "tbsp" },
      { name: "brown sugar", quantity: 2, unit: "tbsp" },
      { name: "smoked paprika", quantity: 2, unit: "tbsp" },
      { name: "garlic powder", quantity: 2, unit: "tbsp" },
      { name: "black pepper", quantity: 1, unit: "tbsp" },
      { name: "baking powder", quantity: 1, unit: "tbsp", notes: "helps crisp skin" },
      { name: "BBQ sauce", quantity: 1.5, unit: "cups" },
      { name: "hot sauce", quantity: 2, unit: "tbsp" },
      { name: "butter", quantity: 4, unit: "tbsp" },
      { name: "celery sticks", quantity: 2, unit: "cups" },
      { name: "ranch dressing", quantity: 1, unit: "cup", notes: "optional dip" },
    ],
    stepLines: [
      { title: "Season the wings", instruction: "Pat wings dry. Toss with salt, brown sugar, paprika, garlic powder, pepper, and baking powder until evenly coated. Rest 10 minutes.", minutes: 10 },
      { title: "Smoke at 250°F", instruction: "Arrange wings on wire racks skin-side up. Smoke at 250°F until internal temp reaches 160°F, about 45–50 minutes.", minutes: 48, heatLevel: "low" },
      { title: "Crisp finish", instruction: "Increase heat to 425°F (grill or oven) 12–15 minutes until skin crisps and wings hit 165°F internal.", minutes: 14, heatLevel: "high" },
      { title: "Build wing sauce", instruction: "Simmer BBQ sauce, hot sauce, and butter until smooth. Keep warm for tossing.", minutes: 5 },
      { title: "Toss and tray", instruction: "Toss hot wings in sauce to coat. Spread on sheet pans for service.", minutes: 5 },
      { title: "Hold at 170°F", instruction: "Cover loosely with foil and hold at 170°F up to 30 minutes. Re-toss if sauce pools.", minutes: 5 },
      { title: "Tonight's board", instruction: "Wings on a tray with celery and ranch. Napkins mandatory.", minutes: 3 },
      { title: "Leftovers", instruction: "Re-crisp on a sheet pan at 400°F 8 minutes. Toss with fresh sauce.", minutes: 10 },
    ],
    proTips: [
      "Baking powder dries skin for crisp without deep frying.",
      "165°F is the floor—pull when clear juices run from the thickest drum.",
      "Toss in batches so every wing gets sauce, not just the bottom layer.",
    ],
    tonightSpread: ["Sauced wings on a tray with celery sticks.", "Ranch or blue cheese on the side."],
    leftovers: ["Pull meat for wing tacos with slaw.", "Chop into a smoky chicken dip for game night."],
    searchTerms: ["smoked wings", "bbq wings", "crispy wings", "wing tray"],
    relatedSlugs: ["competition-bbq-chicken-thighs", "honey-chipotle-chicken-thighs", "smoked-chicken-quarters-white-sauce"],
    cleanupDifficulty: "medium",
  }),

  bbqRecipe({
    manifest: manifestEntry({
      slug: "hickory-smoked-chicken-breast",
      title: "Hickory Smoked Chicken Breast",
      subtitle: "Brined breasts, hickory smoke, and herb butter for ten",
      protein: "chicken",
      cuisine: "American",
      mealFormat: "grill",
      pools: ["bbq", "chicken", "high_protein"],
      hook: "Lean breast that actually stays juicy on the smoker",
      prep: 20,
      cook: 60,
      difficulty: "medium",
    }),
    description:
      "Adapted from classic smoked chicken breast technique (Weber, Traeger): boneless breasts get a quick brine, smoke over hickory at 275°F to 165°F, and finish with herb butter for a crew-friendly protein tray.",
    whyCrewsLikeIt:
      "Breast is the macro choice. Brine and pull-at-temp discipline keep it moist, and sliced breast holds at 170°F better than most lean proteins.",
    stationTimingNotes:
      "Brine can happen early shift. Smoke to 165°F exactly—don't overshoot. Hold sliced breast covered at 170°F with a splash of butter up to 45 minutes.",
    allergyNotes: "Brine is dairy-free. Herb butter contains dairy.",
    equipment: ["smoker", "instant-read thermometer", "sheet pans", "mixing bowl", "wire rack"],
    ingredients: [
      { name: "boneless skinless chicken breasts", quantity: 6, unit: "lb", notes: "about 10 pieces, even thickness" },
      { name: "kosher salt", quantity: 0.25, unit: "cup", notes: "for brine" },
      { name: "brown sugar", quantity: 3, unit: "tbsp", notes: "for brine" },
      { name: "water", quantity: 8, unit: "cups", notes: "for brine" },
      { name: "smoked paprika", quantity: 2, unit: "tbsp" },
      { name: "garlic powder", quantity: 1, unit: "tbsp" },
      { name: "black pepper", quantity: 1, unit: "tbsp" },
      { name: "unsalted butter", quantity: 6, unit: "tbsp", notes: "softened" },
      { name: "fresh parsley", quantity: 0.25, unit: "cup", notes: "chopped" },
      { name: "lemon juice", quantity: 2, unit: "tbsp" },
    ],
    stepLines: [
      { title: "Quick brine", instruction: "Dissolve salt and brown sugar in water. Submerge breasts 30 minutes in the fridge. Pat completely dry after brining.", minutes: 30 },
      { title: "Season and prep smoker", instruction: "Mix paprika, garlic powder, and pepper; coat breasts evenly. Preheat smoker to 275°F with hickory.", minutes: 10 },
      { title: "Smoke to 155°F", instruction: "Smoke breasts on a wire rack at 275°F until internal temp reaches 155°F, about 25–30 minutes.", minutes: 28, heatLevel: "medium" },
      { title: "Herb butter finish", instruction: "Mix butter, parsley, and lemon juice. Brush breasts during final 5 minutes of smoke.", minutes: 5 },
      { title: "Pull at 165°F", instruction: "Remove when thickest breast hits 165°F internal. Rest 5 minutes before slicing.", minutes: 5 },
      { title: "Slice and hold", instruction: "Slice on a bias 1/2 inch thick. Toss lightly with melted butter. Hold covered at 170°F until service.", minutes: 8 },
      { title: "Tonight's board", instruction: "Sliced breast on a tray with extra herb butter melting on top. Pair with smoked potato salad.", minutes: 3 },
      { title: "Leftovers", instruction: "Chill and slice for salads. Reheat covered at 325°F with butter until 165°F.", minutes: 8 },
    ],
    proTips: [
      "165°F is the ceiling for breast—every degree past dries the line.",
      "Pound thick ends gently so all pieces finish together.",
      "Brine is insurance; don't skip the rest after pulling.",
    ],
    tonightSpread: ["Sliced breast on a tray with herb butter.", "Smoked potato salad and green beans."],
    leftovers: ["Chicken Caesar wraps with shaved parmesan.", "Dice into a white chili for second-day lunch."],
    searchTerms: ["smoked chicken breast", "hickory chicken", "brined breast", "275 smoke"],
    relatedSlugs: ["competition-bbq-chicken-thighs", "smoked-chicken-quarters-white-sauce", "smoked-potato-salad-tray"],
    cleanupDifficulty: "easy",
  }),

  bbqRecipe({
    manifest: manifestEntry({
      slug: "santa-maria-tri-tip-roast",
      title: "Santa Maria Tri-Tip Roast",
      subtitle: "California salt-pepper-garlic rub, oak smoke, and salsa for ten",
      protein: "beef",
      cuisine: "American",
      mealFormat: "grill",
      pools: ["bbq", "beef", "trending"],
      hook: "West Coast tri-tip that slices fast and feeds the whole hall",
      prep: 20,
      cook: 90,
      difficulty: "medium",
    }),
    description:
      "Adapted from classic Santa Maria tri-tip tradition (Amazing Ribs, Weber): tri-tip gets a salt-pepper-garlic rub, smokes over oak at 275°F to 130°F, then sears and slices against the grain with pinquito beans and salsa.",
    whyCrewsLikeIt:
      "Tri-tip cooks in under two hours and slices like steak night without the cost. Holds sliced at 170°F with jus for 45 minutes.",
    stationTimingNotes:
      "Season 30 minutes ahead. Smoke to 130°F, sear hot, rest 10 minutes, slice. Hold sliced tri-tip covered at 170°F with beef jus.",
    allergyNotes: "Rub is gluten-free. Salsa is gluten-free. Check bean labels.",
    equipment: ["smoker", "grill", "instant-read thermometer", "slicing knife", "sheet pan"],
    ingredients: [
      { name: "tri-tip roast", quantity: 6, unit: "lb" },
      { name: "kosher salt", quantity: 2, unit: "tbsp" },
      { name: "black pepper", quantity: 2, unit: "tbsp" },
      { name: "granulated garlic", quantity: 2, unit: "tbsp" },
      { name: "neutral oil", quantity: 2, unit: "tbsp" },
      { name: "beef broth", quantity: 1, unit: "cup", notes: "for holding" },
      { name: "pinto beans", quantity: 4, unit: "cups", notes: "cooked, warmed" },
      { name: "pico de gallo", quantity: 2, unit: "cups" },
      { name: "flour tortillas", quantity: 12, unit: "whole", notes: "optional" },
    ],
    stepLines: [
      { title: "Season Santa Maria-style", instruction: "Mix salt, pepper, and garlic. Coat tri-tip with oil, then pack rub on all sides. Rest 30 minutes while smoker heats to 275°F with oak.", minutes: 30 },
      { title: "Smoke to 130°F", instruction: "Smoke tri-tip at 275°F until internal temp reaches 125–130°F for medium-rare, about 45–55 minutes.", minutes: 50, heatLevel: "medium" },
      { title: "Sear over high heat", instruction: "Sear over direct heat at 450°F+ 3–4 minutes per side until crust forms and internal temp reaches 135°F for medium.", minutes: 10, heatLevel: "high" },
      { title: "Rest and slice", instruction: "Rest 10 minutes. Slice against the grain into thin slices—tri-tip grain changes direction; rotate as you cut.", minutes: 12 },
      { title: "Hold at 170°F", instruction: "Toss slices lightly with warm beef broth. Cover with foil and hold at 170°F until service.", minutes: 5 },
      { title: "Warm beans and salsa", instruction: "Heat pinto beans in a pot. Set pico de gallo cold on the line.", minutes: 8 },
      { title: "Tonight's board", instruction: "Sliced tri-tip, beans, salsa, optional tortillas. Call temps: pulled at 135°F medium, held at 170°F.", minutes: 5 },
      { title: "Leftovers", instruction: "Slice thin for tri-tip sandwiches with salsa and mayo. Reheat in broth at 325°F until 145°F.", minutes: 8 },
    ],
    proTips: [
      "Tri-tip grain shifts mid-roast—pay attention when slicing or bites turn chewy.",
      "125°F off smoke + sear gets you medium-rare; push to 130°F before sear for medium.",
      "Oak is traditional; hickory works if that's what's in the pit.",
    ],
    tonightSpread: ["Sliced tri-tip on a board with jus.", "Warm pinto beans, pico de gallo, and tortillas."],
    leftovers: ["Tri-tip tacos with salsa and avocado.", "Chop into a steak salad with ranch."],
    searchTerms: ["santa maria tri tip", "california tri tip", "oak smoked", "tri tip roast"],
    relatedSlugs: ["reverse-seared-ribeye-crew", "smoked-picanha-steak-platter", "texas-central-brisket-crew"],
    cleanupDifficulty: "medium",
  }),

  bbqRecipe({
    manifest: manifestEntry({
      slug: "reverse-seared-ribeye-crew",
      title: "Reverse-Seared Ribeye for the Crew",
      subtitle: "Smoked then seared boneless ribeyes, compound butter, for ten",
      protein: "beef",
      cuisine: "American",
      mealFormat: "grill",
      pools: ["bbq", "beef", "high_protein"],
      hook: "Steakhouse crust with smoker depth—ten ribeyes, one plan",
      prep: 25,
      cook: 75,
      difficulty: "medium",
    }),
    description:
      "Adapted from classic reverse-sear technique (Meat Church, Hey Grill Hey): boneless ribeyes smoke low at 225°F to 115°F, rest, then sear hard to 130°F medium-rare with garlic-herb compound butter.",
    whyCrewsLikeIt:
      "Reverse sear gives even edge-to-edge pink and a real crust. Steaks hold tented at 170°F up to 20 minutes without overcooking if pulled right.",
    stationTimingNotes:
      "Season early. Smoke in batches if smoker space is tight. Sear to order if possible; otherwise hold tented at 170°F max 20 minutes.",
    allergyNotes: "Compound butter contains dairy. Rub is gluten-free.",
    equipment: ["smoker", "cast iron or grill", "instant-read thermometer", "sheet pans", "tongs"],
    ingredients: [
      { name: "boneless ribeye steaks", quantity: 10, unit: "pieces", notes: "about 12 oz each, 1.25 inch thick" },
      { name: "kosher salt", quantity: 3, unit: "tbsp" },
      { name: "coarse black pepper", quantity: 2, unit: "tbsp" },
      { name: "smoked paprika", quantity: 1, unit: "tbsp" },
      { name: "garlic powder", quantity: 1, unit: "tbsp" },
      { name: "neutral oil", quantity: 3, unit: "tbsp" },
      { name: "unsalted butter", quantity: 8, unit: "tbsp", notes: "softened" },
      { name: "fresh rosemary", quantity: 2, unit: "tbsp", notes: "minced" },
      { name: "garlic cloves", quantity: 3, unit: "whole", notes: "minced" },
    ],
    stepLines: [
      { title: "Season the ribeyes", instruction: "Pat steaks dry. Coat with oil, then salt, pepper, paprika, and garlic powder on all sides. Rest 20 minutes at room temp.", minutes: 20 },
      { title: "Smoke low at 225°F", instruction: "Smoke steaks at 225°F until internal temp reaches 115°F for medium-rare, about 35–45 minutes.", minutes: 40, heatLevel: "low" },
      { title: "Compound butter", instruction: "Mix softened butter, rosemary, and minced garlic. Roll into a log or keep soft for finishing.", minutes: 5 },
      { title: "Sear hard", instruction: "Sear in screaming-hot cast iron or over grill at 500°F+ 90 seconds per side until crust forms and internal hits 130°F medium-rare.", minutes: 8, heatLevel: "high" },
      { title: "Butter baste", instruction: "Add compound butter to pan off direct flame; tilt and baste steaks 30 seconds. Rest 5 minutes tented with foil.", minutes: 6 },
      { title: "Hold at 170°F", instruction: "If holding, tent with foil and place in 170°F oven up to 20 minutes. Do not exceed 145°F internal on the line.", minutes: 5 },
      { title: "Tonight's board", instruction: "Steaks on a board with extra compound butter melting on top. Call temps: 130°F medium-rare pull.", minutes: 5 },
      { title: "Leftovers", instruction: "Slice cold for steak sandwiches with horseradish mayo. Reheat gently in au jus—don't re-sear.", minutes: 5 },
    ],
    proTips: [
      "115°F off the smoker + hard sear lands medium-rare—adjust to 120°F for medium.",
      "Dry surface = better crust; pat again before searing.",
      "Don't skip the rest or juices run when you cut on the line.",
    ],
    tonightSpread: ["Ribeyes on a board with compound butter.", "Grilled asparagus and garlic bread."],
    leftovers: ["Steak and egg breakfast sandwiches.", "Slice over a wedge salad with blue cheese."],
    searchTerms: ["reverse sear ribeye", "smoked steak", "compound butter", "130 medium rare"],
    relatedSlugs: ["santa-maria-tri-tip-roast", "smoked-picanha-steak-platter", "brisket-style-beef-sandwiches-au-jus"],
    cleanupDifficulty: "medium",
  }),

  bbqRecipe({
    manifest: manifestEntry({
      slug: "smoked-picanha-steak-platter",
      title: "Smoked Picanha Steak Platter",
      subtitle: "Fat-cap Brazilian cut, coarse salt, and chimichurri for ten",
      protein: "beef",
      cuisine: "American",
      mealFormat: "grill",
      pools: ["bbq", "beef", "trending"],
      hook: "Show-stopping fat cap with smoker depth and a bright sauce",
      prep: 20,
      cook: 60,
      difficulty: "medium",
    }),
    description:
      "Adapted from classic Brazilian picanha tradition (Traeger, Hey Grill Hey): picanha roasts get coarse salt, smoke at 275°F to 125°F, sear fat-side down, and slice with chimichurri for a crew platter.",
    whyCrewsLikeIt:
      "Picanha is the steak that looks expensive and cooks forgiving. Sliced with chimichurri, it holds at 170°F for 30 minutes without losing character.",
    stationTimingNotes:
      "Score fat cap lightly before salt. Smoke whole, sear, rest 10 minutes, slice. Hold sliced beef covered at 170°F with chimichurri on the side.",
    allergyNotes: "Chimichurri is dairy-free. Rub is gluten-free.",
    equipment: ["smoker", "grill", "instant-read thermometer", "slicing knife", "sheet pan"],
    ingredients: [
      { name: "picanha roast", quantity: 6, unit: "lb", notes: "fat cap on, about 2 roasts" },
      { name: "coarse kosher salt", quantity: 3, unit: "tbsp" },
      { name: "black pepper", quantity: 1, unit: "tbsp" },
      { name: "fresh parsley", quantity: 1, unit: "cup", notes: "for chimichurri" },
      { name: "fresh oregano", quantity: 2, unit: "tbsp" },
      { name: "garlic cloves", quantity: 4, unit: "whole" },
      { name: "red wine vinegar", quantity: 0.25, unit: "cup" },
      { name: "olive oil", quantity: 0.5, unit: "cup" },
      { name: "red pepper flakes", quantity: 1, unit: "tsp" },
    ],
    stepLines: [
      { title: "Prep picanha", instruction: "Score fat cap in crosshatch without cutting into meat. Coat fat cap heavily with coarse salt and pepper. Let sit 20 minutes.", minutes: 20 },
      { title: "Smoke at 275°F", instruction: "Smoke picanha fat-side up at 275°F until internal temp reaches 120–125°F, about 35–45 minutes.", minutes: 40, heatLevel: "medium" },
      { title: "Build chimichurri", instruction: "Pulse parsley, oregano, garlic, vinegar, oil, and pepper flakes until chunky. Rest at room temp.", minutes: 8 },
      { title: "Sear fat cap", instruction: "Sear fat-side down over direct heat at 500°F+ 4–5 minutes until fat crisps and internal hits 130°F medium-rare.", minutes: 8, heatLevel: "high" },
      { title: "Rest and slice", instruction: "Rest 10 minutes. Slice against the grain into 1/4-inch slices, keeping fat cap on each slice.", minutes: 12 },
      { title: "Hold at 170°F", instruction: "Arrange slices on a platter, cover loosely with foil, hold at 170°F. Serve chimichurri cold on the side.", minutes: 5 },
      { title: "Tonight's board", instruction: "Picanha platter with chimichurri, grilled limes, and farro or rice if you want starch.", minutes: 5 },
      { title: "Leftovers", instruction: "Slice thin for steak sandwiches with chimichurri. Reheat gently at 325°F until 145°F.", minutes: 8 },
    ],
    proTips: [
      "Salt the fat cap hard—it's the flavor engine on picanha.",
      "Slice thin; thick slices chew tough even when temp is perfect.",
      "Chimichurri on the side keeps bright flavor; don't cook it.",
    ],
    tonightSpread: ["Sliced picanha on a board with fat cap showing.", "Chimichurri bowl and grilled limes."],
    leftovers: ["Picanha bowls with rice and black beans.", "Chimichurri steak wraps with pickled onion."],
    searchTerms: ["picanha", "brazilian steak", "fat cap", "chimichurri"],
    relatedSlugs: ["reverse-seared-ribeye-crew", "santa-maria-tri-tip-roast", "hot-honey-grilled-sausage-peppers"],
    cleanupDifficulty: "medium",
  }),

  bbqRecipe({
    manifest: manifestEntry({
      slug: "firehall-double-smash-burgers-bbq",
      title: "Firehall Double Smash Burgers BBQ",
      subtitle: "Double patties, BBQ sauce, and crispy onions for ten",
      protein: "beef",
      cuisine: "American",
      mealFormat: "burger",
      pools: ["bbq", "handheld", "comfort"],
      hook: "Smash burger energy with BBQ sauce built for the hall line",
      prep: 25,
      cook: 25,
      difficulty: "easy",
    }),
    description:
      "Adapted from classic smash burger and BBQ hall traditions (BBQ Pit Boys, Hey Grill Hey): double 3-oz patties get smashed on a hot griddle, stacked with cheddar, BBQ sauce, and crispy onions for ten hungry firefighters.",
    whyCrewsLikeIt:
      "Double smash is morale in handheld form. Cooks fast, holds wrapped 10 minutes, and beats plain grill night every time.",
    stationTimingNotes:
      "Portion balls early and keep cold. Cook bacon and onions first. Wrap finished burgers in foil and hold at 170°F up to 10 minutes—toast buns last minute.",
    allergyNotes: "Buns contain gluten. Sauce contains Worcestershire (may contain fish). Dairy in cheese.",
    equipment: ["flat-top griddle or cast iron", "spatulas", "instant-read thermometer", "sheet pans", "foil"],
    ingredients: [
      { name: "ground beef (80/20)", quantity: 5, unit: "lb" },
      { name: "kosher salt", quantity: 2, unit: "tbsp" },
      { name: "black pepper", quantity: 1, unit: "tbsp" },
      { name: "American or cheddar cheese slices", quantity: 20, unit: "slices" },
      { name: "brioche buns", quantity: 10, unit: "whole" },
      { name: "yellow onion", quantity: 2, unit: "whole", notes: "thin-sliced for crisping" },
      { name: "ketchup", quantity: 0.5, unit: "cup" },
      { name: "BBQ sauce", quantity: 0.5, unit: "cup" },
      { name: "Worcestershire sauce", quantity: 1, unit: "tbsp" },
      { name: "pickle chips", quantity: 1, unit: "cup" },
      { name: "neutral oil", quantity: 2, unit: "tbsp" },
    ],
    stepLines: [
      { title: "Portion smash balls", instruction: "Divide beef into 20 balls about 3 oz each. Keep cold until cooking. Mix ketchup, BBQ sauce, and Worcestershire for hall BBQ sauce.", minutes: 15 },
      { title: "Crisp the onions", instruction: "Cook sliced onions in oil over medium-high until deep golden and crisp, about 12 minutes. Drain on paper towels.", minutes: 12 },
      { title: "Smash first patties", instruction: "Heat griddle to medium-high. Place balls on surface, smash flat immediately with a stiff spatula. Season with salt and pepper. Cook 2 minutes until crust forms.", minutes: 5, heatLevel: "high" },
      { title: "Flip, cheese, stack", instruction: "Flip patties, add cheese, cook 1 minute. Stack double patties per bun bottom. Repeat in batches until all 10 doubles are built.", minutes: 15, heatLevel: "high" },
      { title: "Check doneness", instruction: "Thickest patty should hit 160°F internal. If needed, finish on cooler griddle zone without burning cheese.", minutes: 3 },
      { title: "Toast buns", instruction: "Butter bun tops and toast on griddle 30 seconds until golden.", minutes: 2 },
      { title: "Hold at 170°F", instruction: "Wrap completed burgers in foil and hold at 170°F up to 10 minutes. Sauce and pickles added at the line.", minutes: 3 },
      { title: "Tonight's board", instruction: "Burgers wrapped in foil, crispy onions, BBQ sauce, pickles. Call it: double smash BBQ—grab and go.", minutes: 3 },
    ],
    proTips: [
      "Cold beef smashes cleaner—don't let balls warm on the counter.",
      "Smash once hard; re-smashing pushes out juice.",
      "Crispy onions go on at service or they steam soft in the wrap.",
    ],
    tonightSpread: ["Wrapped double smash burgers in a foil-lined pan.", "Crispy onions, BBQ sauce, and pickles at the line."],
    leftovers: ["Chop patties into a BBQ burger hash with potatoes.", "Crumble over loaded fries with extra sauce."],
    searchTerms: ["double smash burger", "bbq burger", "smash patty", "griddle burger"],
    relatedSlugs: ["bbq-bacon-cheddar-burgers", "hot-honey-grilled-sausage-peppers", "jalapeno-cheddar-smoked-sausages"],
    cleanupDifficulty: "medium",
  }),

  bbqRecipe({
    manifest: manifestEntry({
      slug: "jalapeno-cheddar-smoked-sausages",
      title: "Jalapeño Cheddar Smoked Sausages",
      subtitle: "Smoked links, pepper jack melt, and grilled peppers for ten",
      protein: "pork",
      cuisine: "American",
      mealFormat: "grill",
      pools: ["bbq", "handheld", "quick"],
      hook: "Smoked links with cheese and heat—fast line, big flavor",
      prep: 15,
      cook: 45,
      difficulty: "easy",
    }),
    description:
      "Adapted from classic smoked sausage platter tradition (Traeger, Weber): jalapeño-cheddar links smoke at 275°F until 165°F internal, then grill with peppers and onions for a handheld tray.",
    whyCrewsLikeIt:
      "Sausage night is zero drama. Links hold covered at 170°F, and the line moves fast with buns or tortillas.",
    stationTimingNotes:
      "Score links lightly before smoking. Smoke ahead, then grill-mark before service. Hold in a covered pan at 170°F with peppers.",
    allergyNotes: "Links may contain dairy and gluten fillers—check labels. Buns contain gluten.",
    equipment: ["smoker", "grill", "instant-read thermometer", "tongs", "sheet pan"],
    ingredients: [
      { name: "jalapeño cheddar sausage links", quantity: 12, unit: "links" },
      { name: "bell peppers", quantity: 4, unit: "whole", notes: "sliced" },
      { name: "yellow onions", quantity: 2, unit: "whole", notes: "sliced" },
      { name: "neutral oil", quantity: 2, unit: "tbsp" },
      { name: "kosher salt", quantity: 1, unit: "tsp" },
      { name: "black pepper", quantity: 1, unit: "tsp" },
      { name: "sub rolls", quantity: 10, unit: "whole" },
      { name: "mustard", quantity: 0.5, unit: "cup" },
      { name: "pickled jalapeños", quantity: 0.5, unit: "cup" },
    ],
    stepLines: [
      { title: "Prep the links", instruction: "Score sausage casings lightly. Toss peppers and onions with oil, salt, and pepper.", minutes: 8 },
      { title: "Smoke at 275°F", instruction: "Smoke sausages at 275°F until internal temp reaches 155°F, about 30–35 minutes.", minutes: 32, heatLevel: "medium" },
      { title: "Grill finish", instruction: "Grill sausages and peppers over medium-high 8–10 minutes until links hit 165°F and peppers char lightly.", minutes: 10, heatLevel: "high" },
      { title: "Rest and hold", instruction: "Rest links 3 minutes. Transfer to a covered pan with peppers and onions. Hold at 170°F until service.", minutes: 5 },
      { title: "Toast rolls", instruction: "Split rolls and toast cut-side down on the grill 1 minute until marked.", minutes: 3 },
      { title: "Tonight's board", instruction: "Sausages and peppers in a pan, rolls, mustard, pickled jalapeños. Build-your-own sandwich line.", minutes: 3 },
      { title: "Leftovers", instruction: "Slice into a breakfast scramble with eggs. Reheat covered at 325°F until 165°F.", minutes: 8 },
    ],
    proTips: [
      "165°F internal on sausage—don't guess by color alone.",
      "Score casings so they don't burst on the grill finish.",
      "Pickled jalapeños add acid that balances rich cheese links.",
    ],
    tonightSpread: ["Smoked links with peppers and onions in a hotel pan.", "Toasted rolls, mustard, and pickled jalapeños."],
    leftovers: ["Sausage and pepper hoagies with extra mustard.", "Chop into a smoky pasta skillet with cream."],
    searchTerms: ["jalapeno cheddar sausage", "smoked sausage", "grilled peppers", "275 smoke"],
    relatedSlugs: ["hot-honey-grilled-sausage-peppers", "firehall-double-smash-burgers-bbq", "smoked-baked-beans-crew"],
    cleanupDifficulty: "easy",
  }),

  bbqRecipe({
    manifest: manifestEntry({
      slug: "smoked-mac-and-cheese-crew",
      title: "Smoked Mac and Cheese for the Crew",
      subtitle: "Creamy three-cheese bake with a light smoke kiss for ten",
      protein: "vegetarian",
      cuisine: "American",
      mealFormat: "side",
      pools: ["bbq", "comfort", "big_crew"],
      hook: "The side that turns brisket night into a full spread",
      prep: 25,
      cook: 75,
      difficulty: "easy",
    }),
    description:
      "Adapted from classic smoked mac and cheese tradition (Hey Grill Hey, Traeger): elbow pasta bakes in a creamy three-cheese sauce, then rides the smoker at 275°F for 30 minutes for subtle smoke and a golden top.",
    whyCrewsLikeIt:
      "Mac is the side crews fight over. Smoker time adds depth without overpowering, and it holds covered at 170°F for 45 minutes.",
    stationTimingNotes:
      "Build sauce and par-cook pasta ahead. Assemble in foil pans. Smoke 30 minutes, then hold covered at 170°F. Stir before service if top dries.",
    allergyNotes: "Contains dairy, gluten (pasta). Use GF pasta if needed.",
    equipment: ["smoker", "large pot", "foil pans", "whisk", "wood spoon"],
    ingredients: [
      { name: "elbow macaroni", quantity: 2, unit: "lb" },
      { name: "unsalted butter", quantity: 6, unit: "tbsp" },
      { name: "all-purpose flour", quantity: 0.25, unit: "cup" },
      { name: "whole milk", quantity: 4, unit: "cups" },
      { name: "heavy cream", quantity: 1, unit: "cup" },
      { name: "sharp cheddar", quantity: 3, unit: "cups", notes: "shredded" },
      { name: "Gruyère", quantity: 1, unit: "cup", notes: "shredded" },
      { name: "smoked gouda", quantity: 1, unit: "cup", notes: "shredded" },
      { name: "kosher salt", quantity: 2, unit: "tsp" },
      { name: "black pepper", quantity: 1, unit: "tsp" },
      { name: "smoked paprika", quantity: 1, unit: "tsp" },
      { name: "panko breadcrumbs", quantity: 1, unit: "cup" },
    ],
    stepLines: [
      { title: "Par-cook pasta", instruction: "Boil macaroni in salted water 2 minutes shy of package directions. Drain well.", minutes: 10 },
      { title: "Build cheese sauce", instruction: "Melt butter, whisk in flour 1 minute. Whisk in milk and cream until smooth. Simmer until thick, then melt in cheddar, Gruyère, and gouda. Season with salt, pepper, and paprika.", minutes: 15 },
      { title: "Combine and pan", instruction: "Fold pasta into cheese sauce. Transfer to buttered foil pans. Top with panko mixed with 2 tbsp melted butter.", minutes: 8 },
      { title: "Smoke at 275°F", instruction: "Smoke uncovered at 275°F 30 minutes until top is golden and internal temp reaches 165°F in the center.", minutes: 30, heatLevel: "medium" },
      { title: "Rest and hold", instruction: "Rest 10 minutes. Cover with foil and hold at 170°F until service. Stir edges into center if a skin forms.", minutes: 10 },
      { title: "Tonight's board", instruction: "Mac in foil pans with serving spoons. Pair with any smoked meat on the line.", minutes: 3 },
      { title: "Leftovers", instruction: "Reheat covered at 325°F with splash of milk until 165°F. Top with hot sauce for shift lunch.", minutes: 10 },
    ],
    proTips: [
      "Undercook pasta—it finishes in the sauce and smoke.",
      "Smoked gouda doubles the smoke note without extra pit time.",
      "165°F in the center means safe hold temp for the crew line.",
    ],
    tonightSpread: ["Smoked mac in foil pans with serving spoons.", "Extra cracked pepper at the table."],
    leftovers: ["Fried mac bites coated in panko for next shift.", "Stir in pulled pork for a one-pan second day."],
    searchTerms: ["smoked mac and cheese", "bbq side", "three cheese mac", "275 smoke"],
    relatedSlugs: ["smoked-baked-beans-crew", "firehall-burnt-ends-platter", "kansas-city-pulled-pork-sandwiches"],
    cleanupDifficulty: "medium",
  }),

  bbqRecipe({
    manifest: manifestEntry({
      slug: "smoked-baked-beans-crew",
      title: "Smoked Baked Beans for the Crew",
      subtitle: "Molasses-brown sugar beans with burnt-end depth for ten",
      protein: "vegetarian",
      cuisine: "American",
      mealFormat: "side",
      pools: ["bbq", "comfort", "big_crew"],
      hook: "The pot that makes every BBQ plate feel complete",
      prep: 20,
      cook: 180,
      difficulty: "easy",
    }),
    description:
      "Adapted from classic pit-style baked beans tradition (BBQ Pit Boys, Amazing Ribs): canned beans simmer with molasses, brown sugar, and bacon, then smoke at 275°F for 2 hours until thick and smoky.",
    whyCrewsLikeIt:
      "Beans hold forever at 170°F, stretch any meat plate, and taste better the longer they sit on the smoker.",
    stationTimingNotes:
      "Simmer base on the stove, then transfer to foil pans on the smoker. Hold covered at 170°F up to 3 hours. Stir before service.",
    allergyNotes: "Contains pork (bacon). Check sauce labels for gluten.",
    equipment: ["smoker", "Dutch oven or pot", "foil pans", "wood spoon"],
    ingredients: [
      { name: "canned pinto beans", quantity: 4, unit: "cans", notes: "15 oz, drained and rinsed" },
      { name: "canned kidney beans", quantity: 2, unit: "cans", notes: "15 oz, drained and rinsed" },
      { name: "bacon", quantity: 0.75, unit: "lb", notes: "diced" },
      { name: "yellow onion", quantity: 1, unit: "whole", notes: "diced" },
      { name: "ketchup", quantity: 1, unit: "cup" },
      { name: "molasses", quantity: 0.33, unit: "cup" },
      { name: "brown sugar", quantity: 0.33, unit: "cup" },
      { name: "yellow mustard", quantity: 2, unit: "tbsp" },
      { name: "apple cider vinegar", quantity: 2, unit: "tbsp" },
      { name: "Worcestershire sauce", quantity: 1, unit: "tbsp" },
      { name: "BBQ sauce", quantity: 0.5, unit: "cup" },
    ],
    stepLines: [
      { title: "Render bacon", instruction: "Cook diced bacon in a pot until crisp. Remove half for topping; leave rest with fat.", minutes: 10 },
      { title: "Sweat onion", instruction: "Cook diced onion in bacon fat until soft, about 6 minutes.", minutes: 6 },
      { title: "Build bean base", instruction: "Add beans, ketchup, molasses, brown sugar, mustard, vinegar, Worcestershire, and BBQ sauce. Simmer 20 minutes until starting to thicken.", minutes: 20 },
      { title: "Smoke at 275°F", instruction: "Transfer to foil pans. Smoke uncovered at 275°F 2 hours, stirring once, until thick and smoky.", minutes: 120, heatLevel: "medium" },
      { title: "Hold at 170°F", instruction: "Cover with foil and hold at 170°F until service. Top with reserved crisp bacon before serving.", minutes: 5 },
      { title: "Tonight's board", instruction: "Beans in a pot with ladle alongside any smoked meat. Call it the hall pot—everyone gets a scoop.", minutes: 3 },
      { title: "Leftovers", instruction: "Reheat covered at 325°F until 165°F. Fold into burritos with pulled pork.", minutes: 10 },
    ],
    proTips: [
      "Uncovered smoke thickens the pot—stir the edges so they don't crust.",
      "Mix bean varieties for texture; all pintos turn mushy.",
      "Reserved crisp bacon goes on at service or it softens.",
    ],
    tonightSpread: ["Smoked beans in a Dutch oven with ladle.", "Crisp bacon bits in a side bowl for topping."],
    leftovers: ["Bean and brisket burritos.", "Top loaded nachos with beans and cheese."],
    searchTerms: ["smoked baked beans", "bbq beans", "molasses beans", "pit beans"],
    relatedSlugs: ["firehall-burnt-ends-platter", "kansas-city-pulled-pork-sandwiches", "smoked-mac-and-cheese-crew"],
    cleanupDifficulty: "easy",
  }),

  bbqRecipe({
    manifest: manifestEntry({
      slug: "smoked-potato-salad-tray",
      title: "Smoked Potato Salad Tray",
      subtitle: "Smoked potatoes, tangy mustard dressing, and herbs for ten",
      protein: "vegetarian",
      cuisine: "American",
      mealFormat: "side",
      pools: ["bbq", "comfort", "big_crew"],
      hook: "Cold side with smoke depth that pairs with every protein on the pit",
      prep: 25,
      cook: 90,
      difficulty: "easy",
    }),
    description:
      "Adapted from classic BBQ potato salad tradition (Weber, Hey Grill Hey): Yukon golds smoke at 250°F until tender, get diced, and fold into a tangy mustard-mayo dressing for a tray that feeds ten.",
    whyCrewsLikeIt:
      "Potato salad is the cold anchor on a hot smoke board. Smoked spuds add depth without weirdness, and it holds refrigerated 24 hours.",
    stationTimingNotes:
      "Smoke potatoes ahead—they need to cool before dressing. Keep finished salad cold on ice until service. Do not hold warm.",
    allergyNotes: "Contains egg (mayo) and mustard. Use mayo-free dressing for egg allergy.",
    equipment: ["smoker", "sheet pans", "large mixing bowl", "knife", "cutting board"],
    ingredients: [
      { name: "Yukon gold potatoes", quantity: 6, unit: "lb", notes: "halved" },
      { name: "neutral oil", quantity: 2, unit: "tbsp" },
      { name: "kosher salt", quantity: 2, unit: "tbsp" },
      { name: "black pepper", quantity: 1, unit: "tbsp" },
      { name: "mayonnaise", quantity: 1.25, unit: "cups" },
      { name: "yellow mustard", quantity: 0.25, unit: "cup" },
      { name: "apple cider vinegar", quantity: 3, unit: "tbsp" },
      { name: "celery", quantity: 4, unit: "stalks", notes: "diced" },
      { name: "red onion", quantity: 1, unit: "whole", notes: "diced fine" },
      { name: "dill pickles", quantity: 0.5, unit: "cup", notes: "chopped" },
      { name: "fresh dill", quantity: 0.25, unit: "cup", notes: "chopped" },
      { name: "hard-boiled eggs", quantity: 4, unit: "whole", notes: "chopped (optional)" },
    ],
    stepLines: [
      { title: "Prep potatoes", instruction: "Halve potatoes, toss with oil, salt, and pepper. Arrange cut-side down on sheet pans.", minutes: 12 },
      { title: "Smoke at 250°F", instruction: "Smoke potatoes at 250°F until fork-tender and internal temp reaches 205°F, about 60–75 minutes.", minutes: 70, heatLevel: "low" },
      { title: "Cool and dice", instruction: "Cool potatoes 20 minutes until warm, not hot. Dice into 1/2-inch cubes.", minutes: 25 },
      { title: "Build dressing", instruction: "Whisk mayo, mustard, vinegar, and pinch of salt until smooth.", minutes: 5 },
      { title: "Fold salad", instruction: "Fold potatoes with dressing, celery, onion, pickles, dill, and eggs if using. Season to taste.", minutes: 10 },
      { title: "Chill for service", instruction: "Refrigerate at least 30 minutes so flavors meld. Keep on ice at the line.", minutes: 30 },
      { title: "Tonight's board", instruction: "Potato salad in a cold pan on ice alongside smoked meats. Refresh with dill before serving.", minutes: 3 },
      { title: "Leftovers", instruction: "Keeps refrigerated 24 hours. Thin with vinegar if dressing tightens overnight.", minutes: 3 },
    ],
    proTips: [
      "205°F internal on potatoes means creamy center after dice.",
      "Dress while potatoes are warm—they absorb flavor better.",
      "Keep cold: this is the relief side on a hot smoke board.",
    ],
    tonightSpread: ["Smoked potato salad in a cold tray on ice.", "Extra dill and cracked pepper for finishing."],
    leftovers: ["Loaded potato salad bowls with chopped brisket.", "Spread on grilled bread for a smoky picnic toast."],
    searchTerms: ["smoked potato salad", "bbq side", "mustard potato salad", "cold side"],
    relatedSlugs: ["smoked-chicken-quarters-white-sauce", "alabama-white-sauce-pulled-pork", "hickory-smoked-chicken-breast"],
    cleanupDifficulty: "easy",
  }),
];

export const BATCH_25_BBQ_RECIPES: BbqRecipe[] = [
  ...pickFromBbq30(BBQ_30_BATCH_SLUGS),
  ...NEW_BATCH_25_RECIPES,
];

export { BATCH_30_BBQ_GRILL_RECIPES } from "./batch-30-bbq-grill-recipes.js";
export const BBQ_CATALOG_RECIPES: BbqRecipe[] = [
  ...BATCH_25_BBQ_RECIPES,
  ...BATCH_30_BBQ_GRILL_RECIPES,
];

export const BBQ_CATALOG_RECIPE_COUNT = BBQ_CATALOG_RECIPES.length;
