/**
 * Personal schedule persistence (Postgres: user_schedules, user_schedule_overrides).
 * Stores only the pattern, overrides and meal-slot preferences — shift
 * instances and meal slots are generated by shared/schedule/ on read.
 */
import { verifyPgConnection } from "../db/pg-client.js";
import { pgAll, pgOne, pgRun } from "../db/pg-sql.js";
import type {
  PersonalSchedule,
  ScheduleBlock,
  ScheduleOverride,
} from "../../shared/schedule/types.js";
import { mealSlotPreferencesSchema, type ScheduleOverrideInput } from "../../shared/schedule/schema.js";
import type { MealSlotPreferences } from "../../shared/schedule/meal-slots.js";

export async function initScheduleStore(): Promise<void> {
  await verifyPgConnection();
}

interface ScheduleRow {
  timezone: string;
  anchor_date: string;
  start_time: string;
  pattern_json: string;
  preset_id: string | null;
  default_crew_size: number;
  updated_at: Date;
}

interface OverrideRow {
  id: number;
  kind: "extra" | "cancel" | "modify";
  shift_key: string | null;
  start_local: string | null;
  end_local: string | null;
  crew_size: number | null;
  note: string | null;
}

const SCHEDULE_COLUMNS = `timezone, to_char(anchor_date, 'YYYY-MM-DD') AS anchor_date, start_time,
  pattern_json, preset_id, default_crew_size, updated_at`;

function parseBlocks(json: string): ScheduleBlock[] {
  try {
    const parsed = JSON.parse(json);
    return Array.isArray(parsed)
      ? parsed.filter(
          (b): b is ScheduleBlock =>
            !!b && (b.kind === "on" || b.kind === "off") && Number.isInteger(b.minutes),
        )
      : [];
  } catch {
    return [];
  }
}

function toSchedule(row: ScheduleRow): PersonalSchedule & { updatedAt: string } {
  return {
    timezone: row.timezone,
    anchorDate: row.anchor_date,
    startTime: row.start_time,
    blocks: parseBlocks(row.pattern_json),
    defaultCrewSize: row.default_crew_size,
    presetId: row.preset_id,
    updatedAt: row.updated_at instanceof Date ? row.updated_at.toISOString() : String(row.updated_at),
  };
}

function toOverride(row: OverrideRow): ScheduleOverride {
  const id = String(row.id);
  if (row.kind === "extra") {
    return {
      id,
      kind: "extra",
      startLocal: row.start_local!,
      endLocal: row.end_local!,
      crewSize: row.crew_size,
      note: row.note,
    };
  }
  if (row.kind === "cancel") {
    return { id, kind: "cancel", shiftKey: row.shift_key!, note: row.note };
  }
  return {
    id,
    kind: "modify",
    shiftKey: row.shift_key!,
    startLocal: row.start_local,
    endLocal: row.end_local,
    crewSize: row.crew_size,
    note: row.note,
  };
}

export async function getScheduleForUser(
  userId: string,
): Promise<(PersonalSchedule & { updatedAt: string }) | null> {
  const row = await pgOne<ScheduleRow>(`SELECT ${SCHEDULE_COLUMNS} FROM user_schedules WHERE user_id = $1`, [userId]);
  return row ? toSchedule(row) : null;
}

/** Create or replace the pattern. Existing overrides are kept (orphans are ignored by the engine). */
export async function upsertScheduleForUser(
  userId: string,
  s: PersonalSchedule,
): Promise<PersonalSchedule & { updatedAt: string }> {
  const row = await pgOne<ScheduleRow>(
    `INSERT INTO user_schedules (user_id, timezone, anchor_date, start_time, pattern_json, preset_id, default_crew_size)
     VALUES ($1, $2, $3::date, $4, $5, $6, $7)
     ON CONFLICT (user_id) DO UPDATE SET
       timezone = excluded.timezone,
       anchor_date = excluded.anchor_date,
       start_time = excluded.start_time,
       pattern_json = excluded.pattern_json,
       preset_id = excluded.preset_id,
       default_crew_size = excluded.default_crew_size,
       updated_at = now()
     RETURNING ${SCHEDULE_COLUMNS}`,
    [
      userId,
      s.timezone,
      s.anchorDate,
      s.startTime,
      JSON.stringify(s.blocks.map((b) => ({ kind: b.kind, minutes: b.minutes }))),
      s.presetId ?? null,
      s.defaultCrewSize,
    ],
  );
  return toSchedule(row!);
}

/** Deletes the schedule and (by cascade) its overrides. */
export async function deleteScheduleForUser(userId: string): Promise<boolean> {
  const existing = await pgOne(`SELECT 1 FROM user_schedules WHERE user_id = $1`, [userId]);
  if (!existing) return false;
  await pgRun(`DELETE FROM user_schedules WHERE user_id = $1`, [userId]);
  return true;
}

export async function listOverridesForUser(userId: string): Promise<ScheduleOverride[]> {
  const rows = await pgAll<OverrideRow>(
    `SELECT id, kind, shift_key, start_local, end_local, crew_size, note
     FROM user_schedule_overrides WHERE user_id = $1 ORDER BY id`,
    [userId],
  );
  return rows.map(toOverride);
}

/**
 * Adds an override. Cancel/modify are one-per-occurrence: a new one for the
 * same shift replaces the previous (e.g. modify → cancel).
 */
export async function saveOverrideForUser(userId: string, input: ScheduleOverrideInput): Promise<ScheduleOverride> {
  const shiftKey = input.kind === "extra" ? null : input.shiftKey;
  const startLocal = input.kind === "cancel" ? null : (input.startLocal ?? null);
  const endLocal = input.kind === "cancel" ? null : (input.endLocal ?? null);
  const crewSize = input.kind === "cancel" ? null : (input.crewSize ?? null);
  const note = input.note ?? null;

  const row =
    shiftKey == null
      ? await pgOne<OverrideRow>(
          `INSERT INTO user_schedule_overrides (user_id, kind, shift_key, start_local, end_local, crew_size, note)
           VALUES ($1, $2, NULL, $3, $4, $5, $6)
           RETURNING id, kind, shift_key, start_local, end_local, crew_size, note`,
          [userId, input.kind, startLocal, endLocal, crewSize, note],
        )
      : await pgOne<OverrideRow>(
          `INSERT INTO user_schedule_overrides (user_id, kind, shift_key, start_local, end_local, crew_size, note)
           VALUES ($1, $2, $3, $4, $5, $6, $7)
           ON CONFLICT (user_id, shift_key) WHERE shift_key IS NOT NULL DO UPDATE SET
             kind = excluded.kind,
             start_local = excluded.start_local,
             end_local = excluded.end_local,
             crew_size = excluded.crew_size,
             note = excluded.note,
             updated_at = now()
           RETURNING id, kind, shift_key, start_local, end_local, crew_size, note`,
          [userId, input.kind, shiftKey, startLocal, endLocal, crewSize, note],
        );
  return toOverride(row!);
}

/** Stored preferences, re-validated on read; anything invalid falls back to defaults ({}). */
export async function getMealSlotPreferencesForUser(userId: string): Promise<MealSlotPreferences> {
  const row = await pgOne<{ prefs_json: string }>(
    `SELECT prefs_json FROM user_meal_slot_preferences WHERE user_id = $1`,
    [userId],
  );
  if (!row) return {};
  try {
    const parsed = mealSlotPreferencesSchema.safeParse(JSON.parse(row.prefs_json));
    return parsed.success ? parsed.data : {};
  } catch {
    return {};
  }
}

export async function saveMealSlotPreferencesForUser(
  userId: string,
  prefs: MealSlotPreferences,
): Promise<MealSlotPreferences> {
  await pgRun(
    `INSERT INTO user_meal_slot_preferences (user_id, prefs_json)
     VALUES ($1, $2)
     ON CONFLICT (user_id) DO UPDATE SET prefs_json = excluded.prefs_json, updated_at = now()`,
    [userId, JSON.stringify(prefs)],
  );
  return prefs;
}

export async function deleteOverrideForUser(userId: string, id: number): Promise<boolean> {
  const existing = await pgOne(`SELECT 1 FROM user_schedule_overrides WHERE id = $1 AND user_id = $2`, [id, userId]);
  if (!existing) return false;
  await pgRun(`DELETE FROM user_schedule_overrides WHERE id = $1 AND user_id = $2`, [id, userId]);
  return true;
}
