import type { ExploreSectionDef } from "./explore-editorial.js";

/**
 * Full curated Explore rails — visually distinct editorial collections.
 * Crew Favorites + Trending Tonight are injected server-side at the top.
 */
export const EXPLORE_DISCOVERY_SECTIONS: ExploreSectionDef[] = [
  {
    id: "trending_tonight",
    title: "Trending Tonight",
    subtitle: "What crews are saving and cooking this week",
    layout: "rail",
    priority: 5,
    poolTag: "trending",
    theme: "ember",
    appetiteBoost: 12,
    queries: [
      { q: "popular dinner recipe" },
      { q: "viral dinner recipe" },
      { q: "easy crowd dinner" },
    ],
    limit: 8,
    sort: "popularity",
  },
  {
    id: "bbq_grill",
    title: "BBQ & Grill",
    subtitle: "Char, smoke, and grill-night energy",
    layout: "rail",
    priority: 15,
    poolTag: "bbq",
    theme: "smoke",
    appetiteBoost: 11,
    queries: [
      { q: "bbq chicken dinner" },
      { q: "grilled ribs dinner" },
      { q: "pulled pork dinner" },
      { q: "smoked brisket dinner" },
    ],
    limit: 6,
  },
  {
    id: "comfort_food",
    title: "Comfort Food",
    subtitle: "Stick-to-your-ribs crew pleasers",
    layout: "rail",
    priority: 20,
    poolTag: "comfort",
    theme: "gold",
    appetiteBoost: 10,
    queries: [
      { q: "mac and cheese dinner" },
      { q: "meatloaf mashed potatoes" },
      { q: "chicken pot pie" },
      { q: "beef chili hearty" },
    ],
    limit: 6,
  },
  {
    id: "fast_30",
    title: "Fast 30-Minute Meals",
    subtitle: "On the table before the next call",
    layout: "rail",
    priority: 25,
    poolTag: "quick",
    theme: "ember",
    appetiteBoost: 6,
    queries: [
      { q: "quick dinner", maxReadyTime: 30 },
      { q: "30 minute chicken dinner", maxReadyTime: 30 },
      { q: "easy pasta dinner", maxReadyTime: 30 },
      { q: "stir fry dinner", maxReadyTime: 30 },
    ],
    limit: 6,
    sort: "time",
  },
  {
    id: "hearty_soups",
    title: "Soups & Chili",
    subtitle: "Big pots, ladles, and second helpings",
    layout: "rail",
    priority: 30,
    poolTag: "hearty",
    theme: "copper",
    appetiteBoost: 8,
    queries: [
      { q: "beef chili dinner" },
      { q: "chicken noodle soup dinner" },
      { q: "potato soup hearty" },
      { q: "taco soup dinner" },
    ],
    limit: 6,
  },
  {
    id: "healthy_good",
    title: "Healthy But Good",
    subtitle: "Lighter plates that still satisfy the crew",
    layout: "rail",
    priority: 35,
    poolTag: "healthy",
    theme: "ocean",
    appetiteBoost: 4,
    queries: [
      { q: "healthy chicken dinner" },
      { q: "grilled salmon vegetables" },
      { q: "lean turkey dinner" },
      { q: "mediterranean chicken dinner" },
    ],
    limit: 6,
  },
  {
    id: "chicken_dinners",
    title: "Chicken Dinners",
    subtitle: "The hall's most-cooked protein",
    layout: "rail",
    priority: 40,
    poolTag: "chicken",
    theme: "steel",
    appetiteBoost: 7,
    queries: [
      { q: "chicken dinner" },
      { q: "crispy chicken dinner" },
      { q: "baked chicken dinner" },
    ],
    limit: 6,
  },
  {
    id: "beef_dinners",
    title: "Beef Dinners",
    subtitle: "Steaks, roasts, and hearty beef nights",
    layout: "rail",
    priority: 45,
    poolTag: "beef",
    theme: "smoke",
    appetiteBoost: 8,
    queries: [
      { q: "beef dinner" },
      { q: "steak dinner" },
      { q: "ground beef dinner" },
    ],
    limit: 6,
  },
  {
    id: "pasta_night",
    title: "Pasta Night",
    subtitle: "Twirl-worthy plates for the hall",
    layout: "rail",
    priority: 50,
    poolTag: "pasta",
    theme: "gold",
    appetiteBoost: 7,
    queries: [
      { q: "pasta dinner" },
      { q: "spaghetti meat sauce" },
      { q: "baked ziti dinner" },
      { q: "creamy pasta dinner" },
    ],
    limit: 6,
  },
  {
    id: "handhelds",
    title: "Sandwiches & Wraps",
    subtitle: "Handhelds, tacos, and built bowls",
    layout: "rail",
    priority: 55,
    poolTag: "handheld",
    theme: "steel",
    queries: [
      { q: "sandwich dinner" },
      { q: "tacos dinner" },
      { q: "burger dinner" },
      { q: "wrap dinner" },
    ],
    limit: 6,
  },
  {
    id: "breakfast_dinner",
    title: "Breakfast for Dinner",
    subtitle: "Pancakes, hashes, and all-day comfort",
    layout: "rail",
    priority: 60,
    poolTag: "breakfast",
    theme: "gold",
    queries: [
      { q: "breakfast for dinner" },
      { q: "pancakes bacon dinner" },
      { q: "hash browns eggs dinner" },
    ],
    limit: 6,
  },
  {
    id: "slow_cooker",
    title: "Slow Cooker",
    subtitle: "Set it during downtime — feed the crew later",
    layout: "rail",
    priority: 65,
    poolTag: "slow",
    theme: "copper",
    queries: [
      { q: "slow cooker dinner" },
      { q: "crockpot pot roast" },
      { q: "slow cooker pulled pork" },
    ],
    limit: 6,
  },
  {
    id: "one_pot",
    title: "Easy Cleanup",
    subtitle: "One pot, sheet pan, or skillet — less dishes",
    layout: "rail",
    priority: 70,
    poolTag: "one_pot",
    theme: "copper",
    queries: [
      { q: "one pot dinner" },
      { q: "sheet pan dinner" },
      { q: "skillet dinner" },
    ],
    limit: 6,
  },
  {
    id: "bowls_rice",
    title: "Bowls & Rice",
    subtitle: "Built bowls and rice-based crew feeds",
    layout: "rail",
    priority: 75,
    poolTag: "bowl",
    theme: "ocean",
    queries: [
      { q: "rice bowl dinner" },
      { q: "burrito bowl dinner" },
      { q: "buddha bowl dinner" },
    ],
    limit: 6,
  },
];
