/**
 * Pizza Night concept registry — categories, weights, hall metadata, pairing hints.
 */

export type PizzaCategory =
  | "classic"
  | "firehall"
  | "gourmet"
  | "bbq"
  | "white"
  | "spicy"
  | "breakfast"
  | "healthy"
  | "dessert"
  | "international"
  | "viral"
  | "fridge";

export type PizzaStylePref = "classic" | "creative" | "comfort" | "healthier";
export type PizzaHeat = "mild" | "medium" | "spicy";

export interface PizzaConceptMeta {
  id: string;
  title: string;
  category: PizzaCategory;
  /** Higher = more likely when eligible */
  weight: number;
  styles: PizzaStylePref[];
  heat: PizzaHeat[];
  /** Allergens that disqualify this concept */
  excludesAllergens?: string[];
  badges: string[];
  spiceLevel: 0 | 1 | 2 | 3;
  difficulty: "easy" | "medium" | "adventurous";
  estimatedCost: "$" | "$$" | "$$$";
  heroEmoji: string;
  /** CSS gradient for hero placeholder */
  heroGradient: string;
  crust: string;
  sauceStyle: string;
  recommendedSides: string[];
  dippingSauces: string[];
  optionalToppings: string[];
  substitutions: string[];
  /** Featured in rotation / wheel */
  featured?: boolean;
  /** Seasonal boost month 1-12 */
  seasonalMonth?: number;
  quickShift?: boolean;
  crewFavorite?: boolean;
}

export const PIZZA_CONCEPT_REGISTRY: PizzaConceptMeta[] = [
  { id: "pepperoni_classic", title: "Classic Pepperoni Pizza", category: "classic", weight: 14, styles: ["classic", "comfort"], heat: ["mild", "medium"], badges: ["Crew Favourite", "Quick Shift Meal"], spiceLevel: 1, difficulty: "easy", estimatedCost: "$$", heroEmoji: "🍕", heroGradient: "from-red-950 via-orange-950 to-zinc-950", crust: "Regular or thin", sauceStyle: "Tomato", recommendedSides: ["Caesar salad", "Wings"], dippingSauces: ["Garlic butter", "Ranch"], optionalToppings: ["Extra pepperoni", "Hot honey"], substitutions: ["Turkey pepperoni for leaner"], featured: true, quickShift: true, crewFavorite: true },
  { id: "hot_honey_pepperoni", title: "Hot Honey Pepperoni Pizza", category: "gourmet", weight: 12, styles: ["creative", "classic"], heat: ["medium", "spicy"], badges: ["Hall Pick"], spiceLevel: 2, difficulty: "easy", estimatedCost: "$$", heroEmoji: "🍯", heroGradient: "from-amber-950 via-red-950 to-zinc-950", crust: "Thin crisp", sauceStyle: "Tomato", recommendedSides: ["Arugula salad"], dippingSauces: ["Hot honey extra"], optionalToppings: ["Chili flakes"], substitutions: [], featured: true, crewFavorite: true },
  { id: "hot_honey_soppressata", title: "Hot Honey Soppressata Pizza", category: "gourmet", weight: 10, styles: ["creative"], heat: ["medium", "spicy"], badges: ["Gourmet Night"], spiceLevel: 2, difficulty: "medium", estimatedCost: "$$$", heroEmoji: "🌶️", heroGradient: "from-orange-950 via-rose-950 to-black", crust: "Thin", sauceStyle: "Tomato", recommendedSides: ["Pickled peppers"], dippingSauces: ["Hot honey"], optionalToppings: ["Fresh basil post-bake"], substitutions: ["Soppressata → spicy salami"] },
  { id: "meat_lovers", title: "Meat Lovers Pizza", category: "firehall", weight: 13, styles: ["comfort", "classic"], heat: ["mild", "medium"], badges: ["Feeds the Hall", "Crew Favourite"], spiceLevel: 1, difficulty: "medium", estimatedCost: "$$$", heroEmoji: "🥓", heroGradient: "from-red-950 via-zinc-900 to-black", crust: "Regular thick", sauceStyle: "Tomato", recommendedSides: ["Coleslaw", "Garlic bread"], dippingSauces: ["Ranch", "Marinara"], optionalToppings: ["Extra bacon"], substitutions: [], featured: true, crewFavorite: true, quickShift: false },
  { id: "supreme_classic", title: "Firehouse Supreme Pizza", category: "firehall", weight: 12, styles: ["classic", "comfort"], heat: ["mild", "medium"], badges: ["Feeds 4–8", "Crew Favourite"], spiceLevel: 1, difficulty: "medium", estimatedCost: "$$$", heroEmoji: "🚒", heroGradient: "from-red-900 via-zinc-900 to-black", crust: "Regular", sauceStyle: "Tomato", recommendedSides: ["Garden salad"], dippingSauces: ["Ranch"], optionalToppings: ["Hot peppers"], substitutions: [], featured: true, crewFavorite: true },
  { id: "margherita", title: "Margherita Pizza", category: "classic", weight: 11, styles: ["classic", "healthier"], heat: ["mild"], badges: ["Quick Shift Meal"], spiceLevel: 0, difficulty: "easy", estimatedCost: "$$", heroEmoji: "🍅", heroGradient: "from-red-900 via-green-950 to-zinc-950", crust: "Thin", sauceStyle: "Tomato", recommendedSides: ["Caprese salad"], dippingSauces: ["Balsamic glaze"], optionalToppings: ["Fresh burrata"], substitutions: ["Part-skim mozzarella"], quickShift: true },
  { id: "buffalo_chicken", title: "Buffalo Chicken Pizza", category: "spicy", weight: 12, styles: ["comfort", "creative"], heat: ["medium", "spicy"], badges: ["Game Night"], spiceLevel: 2, difficulty: "medium", estimatedCost: "$$", heroEmoji: "🍗", heroGradient: "from-orange-950 via-red-950 to-zinc-950", crust: "Regular", sauceStyle: "Buffalo + ranch", recommendedSides: ["Celery sticks"], dippingSauces: ["Blue cheese", "Ranch"], optionalToppings: ["Blue cheese crumbles"], substitutions: [], featured: true, crewFavorite: true },
  { id: "bbq_chicken", title: "BBQ Chicken Pizza", category: "bbq", weight: 12, styles: ["comfort", "classic"], heat: ["mild", "medium"], badges: ["Crew Favourite"], spiceLevel: 1, difficulty: "easy", estimatedCost: "$$", heroEmoji: "🔥", heroGradient: "from-amber-950 via-orange-950 to-black", crust: "Regular", sauceStyle: "BBQ", recommendedSides: ["Corn on the cob"], dippingSauces: ["Extra BBQ"], optionalToppings: ["Pickled red onion"], substitutions: [], featured: true },
  { id: "bbq_chicken_bacon_ranch", title: "BBQ Chicken Bacon Ranch Pizza", category: "bbq", weight: 11, styles: ["comfort", "creative"], heat: ["mild", "medium"], badges: ["Loaded Hall Pie"], spiceLevel: 1, difficulty: "medium", estimatedCost: "$$$", heroEmoji: "🥓", heroGradient: "from-amber-900 via-red-950 to-zinc-950", crust: "Regular", sauceStyle: "BBQ + ranch", recommendedSides: ["Ranch slaw"], dippingSauces: ["Ranch"], optionalToppings: ["Corn", "Cilantro"], substitutions: [] },
  { id: "chicken_bacon_ranch", title: "Chicken Bacon Ranch Pizza", category: "white", weight: 11, styles: ["comfort"], heat: ["mild"], badges: ["Comfort Hall"], spiceLevel: 0, difficulty: "easy", estimatedCost: "$$", heroEmoji: "🧀", heroGradient: "from-zinc-800 via-amber-950 to-black", crust: "Regular", sauceStyle: "Ranch white", recommendedSides: ["Wedge salad"], dippingSauces: ["Ranch"], optionalToppings: ["Green onion"], substitutions: [] },
  { id: "nashville_hot_chicken", title: "Nashville Hot Chicken Pizza", category: "spicy", weight: 10, styles: ["creative", "comfort"], heat: ["spicy"], badges: ["Spicy Shift"], spiceLevel: 3, difficulty: "medium", estimatedCost: "$$", heroEmoji: "🌶️", heroGradient: "from-red-600/30 via-orange-950 to-black", crust: "Regular", sauceStyle: "Hot oil + ranch", recommendedSides: ["Cool coleslaw"], dippingSauces: ["Ranch", "Pickle juice aioli"], optionalToppings: ["Pickles"], substitutions: ["Mild hot oil for less heat"] },
  { id: "philly_cheesesteak", title: "Philly Cheesesteak Pizza", category: "firehall", weight: 10, styles: ["comfort", "classic"], heat: ["mild", "medium"], badges: ["Feeds the Hall"], spiceLevel: 1, difficulty: "medium", estimatedCost: "$$$", heroEmoji: "🥩", heroGradient: "from-amber-950 via-zinc-900 to-black", crust: "Regular", sauceStyle: "Light tomato or steak sauce", recommendedSides: ["Fries"], dippingSauces: ["Cheese sauce"], optionalToppings: ["Roasted peppers"], substitutions: ["Chicken steak strips"] },
  { id: "taco_pizza", title: "Taco Pizza", category: "international", weight: 10, styles: ["creative", "comfort"], heat: ["medium", "spicy"], badges: ["Taco Tuesday"], spiceLevel: 2, difficulty: "medium", estimatedCost: "$$", heroEmoji: "🌮", heroGradient: "from-yellow-950 via-orange-950 to-black", crust: "Regular", sauceStyle: "Salsa + refried layer", recommendedSides: ["Chips & guac"], dippingSauces: ["Sour cream", "Salsa"], optionalToppings: ["Jalapeños", "Lettuce after bake"], substitutions: [] },
  { id: "donair_style", title: "Donair Pizza", category: "international", weight: 9, styles: ["classic", "comfort"], heat: ["mild"], badges: ["Canadian Hall"], spiceLevel: 1, difficulty: "medium", estimatedCost: "$$", heroEmoji: "🇨🇦", heroGradient: "from-purple-950 via-zinc-900 to-black", crust: "Regular", sauceStyle: "Donair sauce", recommendedSides: ["Garlic fingers"], dippingSauces: ["Sweet donair sauce"], optionalToppings: ["Tomatoes", "Onions"], substitutions: [] },
  { id: "hawaiian", title: "Hawaiian Pizza", category: "classic", weight: 8, styles: ["classic"], heat: ["mild"], badges: ["Crowd Pleaser"], spiceLevel: 0, difficulty: "easy", estimatedCost: "$$", heroEmoji: "🍍", heroGradient: "from-yellow-950 via-orange-950 to-zinc-950", crust: "Regular", sauceStyle: "Tomato", recommendedSides: ["Side salad"], dippingSauces: ["Garlic butter"], optionalToppings: ["Bacon extra"], substitutions: [] },
  { id: "veggie_supreme", title: "Mediterranean Veggie Supreme", category: "healthy", weight: 10, styles: ["healthier", "classic"], heat: ["mild"], badges: ["Veg-Forward"], spiceLevel: 0, difficulty: "easy", estimatedCost: "$$", heroEmoji: "🥗", heroGradient: "from-green-950 via-emerald-950 to-black", crust: "Regular", sauceStyle: "Tomato", recommendedSides: ["Greek salad"], dippingSauces: ["Balsamic"], optionalToppings: ["Feta", "Olives"], substitutions: ["Vegan cheese"] },
  { id: "mediterranean_veggie", title: "Mediterranean Veggie Pizza", category: "healthy", weight: 9, styles: ["healthier"], heat: ["mild"], badges: ["Lighter Hall Option"], spiceLevel: 0, difficulty: "easy", estimatedCost: "$$", heroEmoji: "🫒", heroGradient: "from-teal-950 via-green-950 to-black", crust: "Thin", sauceStyle: "Tomato + olive oil", recommendedSides: ["Hummus plate"], dippingSauces: ["Tzatziki"], optionalToppings: ["Artichokes", "Sun-dried tomato"], substitutions: [] },
  { id: "garlic_parm_white", title: "Garlic Parmesan White Pizza", category: "white", weight: 10, styles: ["classic", "comfort"], heat: ["mild"], badges: ["White Pie"], spiceLevel: 0, difficulty: "easy", estimatedCost: "$$", heroEmoji: "🧄", heroGradient: "from-zinc-700 via-amber-950 to-black", crust: "Thin", sauceStyle: "Garlic cream (no tomato)", recommendedSides: ["Caesar"], dippingSauces: ["Marinara for dunk"], optionalToppings: ["Spinach", "Chicken"], substitutions: [] },
  { id: "garlic_parmesan_chicken", title: "Garlic Parmesan Chicken Pizza", category: "white", weight: 10, styles: ["comfort"], heat: ["mild", "medium"], badges: ["Crew Favourite"], spiceLevel: 1, difficulty: "medium", estimatedCost: "$$", heroEmoji: "🍗", heroGradient: "from-stone-800 via-amber-950 to-black", crust: "Regular", sauceStyle: "Alfredo garlic", recommendedSides: ["Roasted broccoli"], dippingSauces: ["Ranch"], optionalToppings: ["Roasted garlic"], substitutions: [] },
  { id: "pesto_burrata", title: "Pesto Burrata Pizza", category: "gourmet", weight: 9, styles: ["creative", "healthier"], heat: ["mild"], excludesAllergens: ["nuts"], badges: ["Gourmet Night"], spiceLevel: 0, difficulty: "medium", estimatedCost: "$$$", heroEmoji: "🧀", heroGradient: "from-green-950 via-emerald-900 to-black", crust: "Thin", sauceStyle: "Pesto + light tomato", recommendedSides: ["Arugula"], dippingSauces: ["Balsamic"], optionalToppings: ["Cherry tomatoes"], substitutions: ["Basil oil if nut-free pesto unavailable"] },
  { id: "pesto_chicken", title: "Pesto Chicken Pizza", category: "gourmet", weight: 9, styles: ["creative", "healthier"], heat: ["mild", "medium"], excludesAllergens: ["nuts"], badges: ["Fresh & Bright"], spiceLevel: 1, difficulty: "medium", estimatedCost: "$$", heroEmoji: "🌿", heroGradient: "from-green-950 via-zinc-900 to-black", crust: "Thin", sauceStyle: "Pesto", recommendedSides: ["Side salad"], dippingSauces: [], optionalToppings: ["Sun-dried tomato"], substitutions: ["Nut-free pesto"] },
  { id: "white_pizza_classic", title: "Four-Cheese White Pizza", category: "white", weight: 9, styles: ["classic", "comfort"], heat: ["mild"], badges: ["Cheese Lovers"], spiceLevel: 0, difficulty: "easy", estimatedCost: "$$", heroEmoji: "🧀", heroGradient: "from-stone-700 via-amber-900 to-black", crust: "Regular", sauceStyle: "Ricotta + garlic base", recommendedSides: ["Marinara dip"], dippingSauces: ["Marinara"], optionalToppings: ["Hot honey drizzle"], substitutions: [] },
  { id: "mac_cheese", title: "Mac & Cheese Pizza", category: "viral", weight: 8, styles: ["creative", "comfort"], heat: ["mild"], badges: ["Viral Hall Pie"], spiceLevel: 0, difficulty: "adventurous", estimatedCost: "$$$", heroEmoji: "🧀", heroGradient: "from-yellow-900 via-amber-950 to-black", crust: "Thick pan", sauceStyle: "Cheese sauce base", recommendedSides: ["Nothing — it's rich"], dippingSauces: ["Ranch"], optionalToppings: ["Bacon", "Jalapeño"], substitutions: [] },
  { id: "breakfast_pizza", title: "Breakfast Bacon & Egg Pizza", category: "breakfast", weight: 9, styles: ["comfort", "classic"], heat: ["mild"], excludesAllergens: ["eggs"], badges: ["Morning Shift"], spiceLevel: 0, difficulty: "medium", estimatedCost: "$$", heroEmoji: "🍳", heroGradient: "from-amber-900 via-orange-950 to-black", crust: "Regular", sauceStyle: "Light tomato or hollandaise drizzle", recommendedSides: ["Hash browns"], dippingSauces: ["Hot sauce"], optionalToppings: ["Maple drizzle"], substitutions: ["Egg-free vegan scramble"], seasonalMonth: 11 },
  { id: "high_protein_chicken", title: "High-Protein Chicken & Veg Pizza", category: "healthy", weight: 9, styles: ["healthier"], heat: ["mild", "medium"], badges: ["Macro Friendly", "Quick Shift Meal"], spiceLevel: 1, difficulty: "easy", estimatedCost: "$$", heroEmoji: "💪", heroGradient: "from-slate-800 via-emerald-950 to-black", crust: "Thin whole wheat if available", sauceStyle: "Tomato light", recommendedSides: ["Protein shake"], dippingSauces: ["Greek yogurt ranch"], optionalToppings: ["Extra chicken"], substitutions: ["Part-skim cheese"], quickShift: true },
  { id: "jalapeno_popper", title: "Jalapeño Popper Pizza", category: "spicy", weight: 10, styles: ["creative", "comfort"], heat: ["medium", "spicy"], badges: ["Spicy Shift"], spiceLevel: 2, difficulty: "medium", estimatedCost: "$$", heroEmoji: "🫑", heroGradient: "from-green-950 via-lime-950 to-black", crust: "Regular", sauceStyle: "Cream cheese + ranch", recommendedSides: ["Cool ranch slaw"], dippingSauces: ["Ranch"], optionalToppings: ["Bacon"], substitutions: [] },
  { id: "smoked_brisket", title: "Smoked Brisket BBQ Pizza", category: "bbq", weight: 9, styles: ["comfort", "creative"], heat: ["mild", "medium"], badges: ["Weekend Hall"], spiceLevel: 1, difficulty: "adventurous", estimatedCost: "$$$", heroEmoji: "🥩", heroGradient: "from-amber-950 via-stone-900 to-black", crust: "Regular", sauceStyle: "BBQ", recommendedSides: ["Pickles", "Coleslaw"], dippingSauces: ["BBQ"], optionalToppings: ["Pickled onions"], substitutions: ["Pulled pork"] },
  { id: "butter_chicken", title: "Butter Chicken Pizza", category: "international", weight: 9, styles: ["creative", "comfort"], heat: ["medium"], badges: ["International Night"], spiceLevel: 2, difficulty: "medium", estimatedCost: "$$$", heroEmoji: "🍛", heroGradient: "from-orange-950 via-amber-950 to-black", crust: "Regular", sauceStyle: "Butter chicken sauce", recommendedSides: ["Naan strips"], dippingSauces: ["Raita"], optionalToppings: ["Cilantro", "Red onion"], substitutions: [] },
  { id: "big_mac_pizza", title: "Big Mac Style Pizza", category: "viral", weight: 8, styles: ["creative"], heat: ["mild"], badges: ["Viral"], spiceLevel: 0, difficulty: "medium", estimatedCost: "$$$", heroEmoji: "🍔", heroGradient: "from-yellow-950 via-red-950 to-black", crust: "Regular", sauceStyle: "Special sauce + ketchup/mustard", recommendedSides: ["Fries"], dippingSauces: ["Special sauce"], optionalToppings: ["Shredded lettuce after bake", "Pickles"], substitutions: [] },
  { id: "cheeseburger_pizza", title: "Cheeseburger Pizza", category: "viral", weight: 8, styles: ["comfort", "creative"], heat: ["mild"], badges: ["Game Night"], spiceLevel: 0, difficulty: "medium", estimatedCost: "$$$", heroEmoji: "🍔", heroGradient: "from-amber-950 via-yellow-950 to-black", crust: "Regular", sauceStyle: "Ketchup + mustard", recommendedSides: ["Fries"], dippingSauces: ["Burger sauce"], optionalToppings: ["Dill pickles", "Diced tomato after bake"], substitutions: [] },
  { id: "meatball_ricotta", title: "Meatball Ricotta Pizza", category: "classic", weight: 9, styles: ["classic", "comfort"], heat: ["mild"], badges: ["Sunday Hall"], spiceLevel: 1, difficulty: "medium", estimatedCost: "$$$", heroEmoji: "🧆", heroGradient: "from-red-950 via-stone-900 to-black", crust: "Regular", sauceStyle: "Tomato", recommendedSides: ["Garlic bread"], dippingSauces: ["Marinara"], optionalToppings: ["Fresh basil"], substitutions: [] },
  { id: "spicy_italian", title: "Spicy Italian Sausage Pizza", category: "spicy", weight: 10, styles: ["classic", "comfort"], heat: ["medium", "spicy"], badges: ["Spicy Shift"], spiceLevel: 2, difficulty: "easy", estimatedCost: "$$", heroEmoji: "🌭", heroGradient: "from-red-950 via-orange-950 to-black", crust: "Regular", sauceStyle: "Tomato", recommendedSides: ["Antipasto"], dippingSauces: ["Chili oil"], optionalToppings: ["Hot peppers"], substitutions: [] },
  { id: "greek_chicken", title: "Greek Chicken Pizza", category: "international", weight: 8, styles: ["healthier", "classic"], heat: ["mild"], badges: ["Lighter Option"], spiceLevel: 1, difficulty: "medium", estimatedCost: "$$", heroEmoji: "🇬🇷", heroGradient: "from-blue-950 via-stone-900 to-black", crust: "Regular", sauceStyle: "Tomato light + oregano", recommendedSides: ["Greek salad"], dippingSauces: ["Tzatziki"], optionalToppings: ["Feta", "Kalamata olives"], substitutions: [] },
  { id: "mushroom_truffle", title: "Mushroom Truffle Pizza", category: "gourmet", weight: 7, styles: ["creative", "healthier"], heat: ["mild"], badges: ["Gourmet Night"], spiceLevel: 0, difficulty: "adventurous", estimatedCost: "$$$", heroEmoji: "🍄", heroGradient: "from-stone-800 via-zinc-900 to-black", crust: "Thin", sauceStyle: "White garlic", recommendedSides: ["Truffle fries"], dippingSauces: [], optionalToppings: ["Wild mushrooms mix"], substitutions: ["Truffle oil light drizzle"] },
  { id: "leftovers_pizza", title: "What's in the Fridge Pizza", category: "fridge", weight: 6, styles: ["classic", "comfort", "creative"], heat: ["mild", "medium", "spicy"], badges: ["Use It Up", "Quick Shift Meal"], spiceLevel: 1, difficulty: "easy", estimatedCost: "$", heroEmoji: "🧊", heroGradient: "from-slate-800 via-zinc-900 to-black", crust: "Whatever you have", sauceStyle: "Tomato, BBQ, or olive oil", recommendedSides: ["Side salad from leftover veg"], dippingSauces: ["Whatever's open"], optionalToppings: ["Any cooked proteins", "Any cheese", "Any veg"], substitutions: ["No rules — clear the fridge"], quickShift: true },
  { id: "build_your_own", title: "Build Your Own Hall Pizza", category: "firehall", weight: 5, styles: ["classic", "creative", "comfort", "healthier"], heat: ["mild", "medium", "spicy"], badges: ["Custom Crew Pie"], spiceLevel: 1, difficulty: "easy", estimatedCost: "$$", heroEmoji: "👨‍🍳", heroGradient: "from-primary/30 via-orange-950 to-black", crust: "Your choice", sauceStyle: "Your choice", recommendedSides: ["Crew votes toppings"], dippingSauces: ["Ranch", "Marinara"], optionalToppings: ["Unlimited"], substitutions: [] },
  { id: "nutella_dessert", title: "Nutella Dessert Pizza", category: "dessert", weight: 6, styles: ["creative"], heat: ["mild"], excludesAllergens: ["nuts"], badges: ["Dessert Shift"], spiceLevel: 0, difficulty: "easy", estimatedCost: "$", heroEmoji: "🍫", heroGradient: "from-amber-950 via-brown-950 to-black", crust: "Sugar or pizza dough", sauceStyle: "Nutella base", recommendedSides: ["Vanilla ice cream"], dippingSauces: [], optionalToppings: ["Strawberries", "Marshmallows", "Powdered sugar"], substitutions: ["Chocolate hazelnut spread"], seasonalMonth: 12 },
  { id: "spinach_artichoke", title: "Spinach Artichoke Dip Pizza", category: "white", weight: 8, styles: ["comfort", "creative"], heat: ["mild"], badges: ["Appetizer Pie"], spiceLevel: 1, difficulty: "medium", estimatedCost: "$$", heroEmoji: "🥬", heroGradient: "from-green-950 via-lime-950 to-black", crust: "Regular", sauceStyle: "Creamy spinach artichoke", recommendedSides: ["Chips"], dippingSauces: [], optionalToppings: ["Extra artichoke hearts"], substitutions: [] },
  { id: "club_house", title: "Club House Pizza", category: "firehall", weight: 7, styles: ["comfort"], heat: ["mild"], badges: ["Canadian Classic"], spiceLevel: 0, difficulty: "medium", estimatedCost: "$$$", heroEmoji: "🥪", heroGradient: "from-yellow-950 via-amber-950 to-black", crust: "Regular", sauceStyle: "Tomato light", recommendedSides: ["Soup"], dippingSauces: ["Mayo"], optionalToppings: ["Tomato", "Lettuce after bake"], substitutions: [] },
  { id: "alfredo_chicken", title: "Alfredo Chicken Broccoli Pizza", category: "white", weight: 8, styles: ["comfort", "healthier"], heat: ["mild"], badges: ["Balanced Comfort"], spiceLevel: 0, difficulty: "easy", estimatedCost: "$$", heroEmoji: "🥦", heroGradient: "from-green-950 via-stone-800 to-black", crust: "Regular", sauceStyle: "Alfredo", recommendedSides: ["Side salad"], dippingSauces: [], optionalToppings: ["Red pepper flakes"], substitutions: [] },
];

export const PIZZA_CONCEPT_IDS = PIZZA_CONCEPT_REGISTRY.map((c) => c.id) as readonly string[];

export type PizzaConceptId = (typeof PIZZA_CONCEPT_IDS)[number];

export function getPizzaConceptMeta(id: string): PizzaConceptMeta | undefined {
  return PIZZA_CONCEPT_REGISTRY.find((c) => c.id === id);
}

/** Legacy ID aliases from older builds */
export const PIZZA_ID_ALIASES: Record<string, string> = {
  supreme_classic: "supreme_classic",
  veggie_supreme: "veggie_supreme",
};
