import type { BreakfastRecipePageDraft } from "./new-breakfast-pages.js";

const now = new Date().toISOString();
const hero = (slug: string) => `/images/breakfast/${slug}.jpg`;
const thumb = (slug: string) => `/images/thumbs/breakfast/${slug}.jpg`;

export const BATCH_WAVE1_BREAKFAST_PAGES: BreakfastRecipePageDraft[] = [
  {
    slug: "sheet-pan-eggs-sausage-crew",
    title: "Sheet-Pan Eggs & Sausage",
    subtitle: "Roasted peppers, browned sausage, and baked eggs for a 8–10 person hall breakfast.",
    description:
      "This firefighter-friendly sheet-pan breakfast roasts peppers and onions beside browned sausage, then bakes eggs right on top. It gives the hall a hot, hearty tray with a short service window and no griddle traffic.",
    filters: ["feed_a_crew", "high_protein", "quick_breakfasts"],
    tags: ["sheet-pan", "eggs", "sausage", "peppers", "one-pan"],
    crewSize: 10,
    baseServings: 10,
    prepTime: 15,
    cookTime: 30,
    totalTime: 45,
    difficulty: "easy",
    ingredients: [
      { group: "Protein", quantity: "2 lb", name: "breakfast sausage", notes: "bulk or casings removed" },
      { group: "Protein", quantity: "18", name: "large eggs" },
      { group: "Vegetables", quantity: "3", name: "bell peppers", notes: "sliced" },
      { group: "Vegetables", quantity: "2", name: "yellow onions", notes: "sliced thin" },
      { group: "Seasoning", quantity: "2 tbsp", name: "olive oil", notes: "plus kosher salt, black pepper, and smoked paprika" },
      { group: "Finish", quantity: "2 cups", name: "shredded cheddar", notes: "optional, for the last few minutes" },
      { group: "Serve", quantity: "1", name: "bottle hot sauce", notes: "and toast or tortillas for the line" },
    ],
    steps: [
      { stepNumber: 1, title: "Heat oven and prep pans", tempF: 425, minutes: 5, instruction: "Heat oven to 425°F. Line two rimmed half-sheet pans with parchment or foil and oil lightly. Two pans give vegetables room to roast; crowding makes them steam and turn soft." },
      { stepNumber: 2, title: "Brown the sausage", minutes: 8, instruction: "Cook sausage in a large skillet over medium-high, breaking it into small crumbles until no pink remains and it reaches 165°F. Drain excess fat, but leave one tablespoon in the pan for flavor." },
      { stepNumber: 3, title: "Roast peppers and onions", tempF: 425, minutes: 15, instruction: "Toss peppers and onions with oil, salt, pepper, and smoked paprika. Spread across the pans and roast 12–15 minutes until edges brown. Rotate pans halfway; pale vegetables mean the oven was too cool or the pan was crowded." },
      { stepNumber: 4, title: "Add sausage and eggs", tempF: 400, minutes: 12, instruction: "Lower oven to 400°F. Divide sausage over the vegetables, then make 18 small wells and crack in eggs. Keep eggs separated so beginner cooks can portion cleanly; if an egg spills, nudge it back with a spoon before baking." },
      { stepNumber: 5, title: "Bake until safely set", tempF: 400, minutes: 10, instruction: "Bake 8–12 minutes until whites are fully opaque and reach 165°F; yolks can stay soft if the crew prefers. Add cheddar for the final 2 minutes. Do not overbake—rubbery yolks are the usual failure mode." },
      { stepNumber: 6, title: "Serve or hold for calls", minutes: 5, instruction: "Serve directly from the sheet pans with toast, tortillas, and hot sauce. For a short call hold, cover loosely and keep at 200°F for up to 15 minutes; uncovered eggs dry out and covered eggs lose roasted texture." },
    ],
    stationWorkflow: [
      "Brown sausage while the oven preheats and vegetables roast so the final egg bake is the only last-minute step.",
      "Set one pan at each end of the hall line to prevent a bottleneck when both rigs return at once.",
      "If a call interrupts service, hold at 200°F no longer than 15 minutes; cook a fresh small egg batch if the delay runs longer.",
    ],
    cleanupNotes: [
      "Discard parchment or foil after service and soak the sausage skillet immediately to prevent rendered fat from setting.",
      "Wipe egg drips from sheet-pan rims while warm; baked egg protein is much harder to remove cold.",
    ],
    leftovers: [
      "Refrigerate portions within 2 hours and reheat sausage and egg portions to 165°F before serving.",
      "Chop cold leftovers into breakfast burrito filling with fresh cheese and salsa.",
    ],
    heroImage: hero("sheet-pan-eggs-sausage-crew"),
    thumbImage: thumb("sheet-pan-eggs-sausage-crew"),
    imageAlt: "Sheet-pan breakfast with baked eggs, browned sausage, roasted peppers, and onions",
    publishedAt: now,
    updatedAt: now,
    readMinutes: 7,
    seoTitle: "Sheet-Pan Eggs & Sausage | Firehall Breakfast",
  },
  {
    slug: "hash-brown-breakfast-casserole",
    title: "Hash Brown Breakfast Casserole",
    subtitle: "A cheese, egg, hash brown, and breakfast meat bake that holds for late eaters.",
    description:
      "This hall-ready hash brown breakfast casserole layers crisp-edged potatoes, eggs, cheese, and breakfast meat in a deep pan. It is built for firefighter crews whose morning meal may be interrupted, because clean squares hold better than made-to-order eggs.",
    filters: ["feed_a_crew", "high_protein", "healthy_breakfasts"],
    tags: ["casserole", "hash-browns", "eggs", "sausage", "make-ahead"],
    crewSize: 10,
    baseServings: 10,
    prepTime: 20,
    cookTime: 50,
    totalTime: 70,
    difficulty: "easy",
    ingredients: [
      { group: "Base", quantity: "2 lb", name: "frozen shredded hash browns", notes: "thawed and squeezed dry" },
      { group: "Base", quantity: "4 tbsp", name: "melted butter", notes: "plus spray for the pan" },
      { group: "Protein", quantity: "1 1/2 lb", name: "breakfast sausage or diced ham", notes: "cooked and drained" },
      { group: "Custard", quantity: "16", name: "large eggs" },
      { group: "Custard", quantity: "2 cups", name: "whole milk", notes: "or half-and-half" },
      { group: "Cheese", quantity: "3 cups", name: "shredded cheddar", notes: "divided" },
      { group: "Vegetables", quantity: "1", name: "small onion", notes: "diced and sautéed" },
      { group: "Seasoning", quantity: "1 tsp", name: "garlic powder", notes: "plus salt, black pepper, and paprika" },
    ],
    steps: [
      { stepNumber: 1, title: "Heat oven and dry hash browns", tempF: 375, minutes: 5, instruction: "Heat oven to 375°F and Grease a deep 9x13 baking dish. Squeeze thawed hash browns firmly in a clean towel; wet potatoes are the main reason this casserole gets a soggy bottom." },
      { stepNumber: 2, title: "Build the potato crust", tempF: 375, minutes: 18, instruction: "Mix hash browns with melted butter, garlic powder, salt, and pepper. Press into the pan in an even layer and bake 15–18 minutes until edges begin to brown. This par-bake keeps the base from tasting boiled." },
      { stepNumber: 3, title: "Cook the filling", minutes: 10, instruction: "Brown sausage to 165°F, or warm cooked ham, then drain well. Sauté onion until soft. Spread meat, onion, and two cups of cheese over the hot potato crust; greasy meat will make pools in the finished bake." },
      { stepNumber: 4, title: "Whisk and pour custard", minutes: 5, instruction: "Whisk eggs, milk, paprika, salt, and pepper until smooth. Pour slowly over the filling, pausing to let it settle into corners. Do not stir after pouring or the potato layer will break apart." },
      { stepNumber: 5, title: "Bake until the center sets", tempF: 375, minutes: 30, instruction: "Bake 28–32 minutes until the center is set, reaches 165°F, and no liquid egg shakes in the middle. Add remaining cheese for the final 5 minutes. If the top browns early, tent loosely with foil." },
      { stepNumber: 6, title: "Rest, cut, and hold", minutes: 10, instruction: "Rest 10 minutes before cutting into 10 squares; cutting early causes loose, wet portions. Hold covered at 200°F up to 30 minutes for late eaters, then uncover for the last 5 minutes to protect the top." },
    ],
    stationWorkflow: [
      "Assemble the casserole the night before, cover, and refrigerate; add 10 minutes to baking time when it goes in cold.",
      "Use a thermometer in the center, not the browned edge, to confirm the egg custard reaches 165°F.",
      "Keep uncut squares in the warm pan during calls and cut only the portions needed for the first line.",
    ],
    cleanupNotes: [
      "Soak the casserole pan with hot soapy water immediately; baked potato starch and egg set hard after cooling.",
      "Drain sausage in a lined bowl rather than down the sink to keep rendered fat out of plumbing.",
    ],
    leftovers: [
      "Cool leftovers promptly, refrigerate up to 4 days, and reheat covered portions to 165°F.",
      "Crisp a cold square in a skillet and top it with salsa for a quick next-shift breakfast.",
    ],
    heroImage: hero("hash-brown-breakfast-casserole"),
    thumbImage: thumb("hash-brown-breakfast-casserole"),
    imageAlt: "Golden hash brown breakfast casserole squares with eggs, sausage, and melted cheddar",
    publishedAt: now,
    updatedAt: now,
    readMinutes: 8,
    seoTitle: "Hash Brown Breakfast Casserole | Firehall Breakfast",
  },
  {
    slug: "bagel-sandwich-line",
    title: "Bagel Sandwich Line",
    subtitle: "Build-your-own bagel sandwiches with eggs, cheese, and proteins for staggered crews.",
    description:
      "A firefighter hall breakfast line that lets every crew member build a hot bagel sandwich without waiting for individual orders. Egg sheets, cheese, and warm proteins stay organized in baking dishes so morning service continues even when the crew arrives in waves.",
    filters: ["breakfast_sandwiches", "feed_a_crew", "quick_breakfasts"],
    tags: ["bagels", "sandwiches", "egg-sheet", "build-your-own", "handheld"],
    crewSize: 10,
    baseServings: 10,
    prepTime: 20,
    cookTime: 25,
    totalTime: 45,
    difficulty: "easy",
    ingredients: [
      { group: "Bagels", quantity: "12", name: "bagels", notes: "assorted, sliced" },
      { group: "Egg sheet", quantity: "18", name: "large eggs", notes: "whisked with 1/2 cup milk" },
      { group: "Protein", quantity: "10", name: "breakfast sausage patties", notes: "or Canadian bacon slices" },
      { group: "Protein", quantity: "10 slices", name: "cooked bacon", notes: "optional second protein" },
      { group: "Cheese", quantity: "12 slices", name: "cheddar, Swiss, or American cheese" },
      { group: "Toppings", quantity: "8 oz", name: "cream cheese", notes: "plus sliced tomato, spinach, and hot sauce" },
      { group: "Seasoning", quantity: "1 tsp", name: "kosher salt", notes: "plus black pepper for eggs" },
    ],
    steps: [
      { stepNumber: 1, title: "Heat oven and prep the egg pan", tempF: 350, minutes: 5, instruction: "Heat oven to 350°F. Line a rimmed quarter-sheet pan with parchment and spray it well. The parchment overhang is a beginner-friendly handle for lifting the cooked egg sheet out cleanly." },
      { stepNumber: 2, title: "Bake the egg sheet", tempF: 350, minutes: 14, instruction: "Whisk eggs, milk, salt, and pepper and pour into the prepared pan. Bake 12–14 minutes until just set and 165°F in the center. Stop before it browns; overbaked egg sheets become rubbery in held sandwiches." },
      { stepNumber: 3, title: "Warm proteins and toast bagels", tempF: 325, minutes: 10, instruction: "Heat sausage patties to 165°F and crisp bacon if using. Toast bagel halves cut-side up at 325°F for 5–7 minutes. Keep toasted bagels uncovered so trapped steam does not soften them." },
      { stepNumber: 4, title: "Cut the egg portions", minutes: 5, instruction: "Lift the egg sheet onto a board and cut into 10 to 12 squares with a knife wiped between cuts. Stack cheese on the hot egg squares so it begins melting before the line opens." },
      { stepNumber: 5, title: "Set the sandwich line", minutes: 5, instruction: "Arrange bagels, eggs, warm sausage, bacon, cheese, cream cheese, vegetables, and sauces in order. Put tongs in each protein pan and label hot versus cold toppings so service stays safe and fast." },
      { stepNumber: 6, title: "Hold components for staggered arrivals", tempF: 200, minutes: 5, instruction: "Hold egg squares and proteins covered in a 200°F oven for up to 20 minutes; keep bagels and cold toppings outside the oven. Replenish small batches rather than building all sandwiches early, or bread turns soggy." },
    ],
    stationWorkflow: [
      "Bake one egg sheet while another cook toasts bagels and warms sausage so the line opens all at once.",
      "Keep hot proteins above 140°F and cold tomato, spinach, and cream cheese below 40°F during extended service.",
      "For a call, cover the hot baking dish and leave sandwiches unassembled; crews can build fresh when they return.",
    ],
    cleanupNotes: [
      "Lift and discard the parchment egg liner before washing the sheet pan; it removes nearly all baked-on egg.",
      "Wipe toaster crumbs and cream-cheese smears immediately so the breakfast line can convert quickly to lunch prep.",
    ],
    leftovers: [
      "Refrigerate egg and meat components separately; reheat protein and eggs to 165°F before rebuilding sandwiches.",
      "Use leftover bagels for bagel chips or breakfast strata rather than refrigerating assembled sandwiches.",
    ],
    heroImage: hero("bagel-sandwich-line"),
    thumbImage: thumb("bagel-sandwich-line"),
    imageAlt: "Build-your-own bagel sandwich line with egg squares, cheese, sausage, bacon, and toppings",
    publishedAt: now,
    updatedAt: now,
    readMinutes: 7,
    seoTitle: "Bagel Sandwich Line | Firehall Breakfast",
  },
  {
    slug: "overnight-oat-bar-crew",
    title: "Overnight Oat Bar for the Crew",
    subtitle: "Scoop-and-go overnight oats with toppings for a staggered morning hall service.",
    description:
      "This firefighter breakfast oat bar is assembled the night before, then set out as a scoop-and-go station with fruit, nuts, and nut butter. It is ideal for a hall crew that needs a filling morning option without turning on the stove after a late call.",
    filters: ["healthy_breakfasts", "feed_a_crew", "quick_breakfasts"],
    tags: ["overnight-oats", "oat-bar", "make-ahead", "healthy", "scoop-and-go"],
    crewSize: 10,
    baseServings: 10,
    prepTime: 15,
    cookTime: 5,
    totalTime: 20,
    difficulty: "easy",
    ingredients: [
      { group: "Oat base", quantity: "5 cups", name: "old-fashioned rolled oats", notes: "not instant or steel-cut" },
      { group: "Oat base", quantity: "5 cups", name: "milk", notes: "dairy or unsweetened oat milk" },
      { group: "Oat base", quantity: "2 cups", name: "plain Greek yogurt", notes: "for extra protein" },
      { group: "Oat base", quantity: "1/2 cup", name: "chia seeds", notes: "for thickening" },
      { group: "Sweetener", quantity: "1/2 cup", name: "maple syrup", notes: "adjust to taste" },
      { group: "Toppings", quantity: "3 cups", name: "mixed berries", notes: "fresh or thawed and drained" },
      { group: "Toppings", quantity: "1 cup", name: "chopped nuts or granola", notes: "keep dry until service" },
      { group: "Toppings", quantity: "1 cup", name: "peanut or almond butter", notes: "plus cinnamon and sliced bananas" },
    ],
    steps: [
      { stepNumber: 1, title: "Mix the overnight oat base", minutes: 8, instruction: "In a large food-safe container, whisk milk, Greek yogurt, chia seeds, maple syrup, and a pinch of salt until smooth. Stir in oats until every oat is wet; dry pockets remain hard even after chilling." },
      { stepNumber: 2, title: "Chill overnight", minutes: 0, instruction: "Cover and refrigerate at 40°F or below for at least 6 hours and up to 24 hours. Do not leave the dairy-based mixture on the counter to thicken; refrigerator time is both the texture step and the food-safety step." },
      { stepNumber: 3, title: "Check texture before service", minutes: 3, instruction: "Stir the oats in the morning. Add milk a few tablespoons at a time if too thick, or let them rest 10 more minutes if loose. Beginners should avoid adding all extra milk at once because oats continue to absorb moisture." },
      { stepNumber: 4, title: "Set a cold topping bar", minutes: 5, instruction: "Set berries, banana, nut butter, cinnamon, and dry granola in separate bowls with clean spoons. Keep granola and nuts dry until topping so they stay crisp, and label nut-containing toppings for the hall crew." },
      { stepNumber: 5, title: "Serve scoop-and-go", minutes: 5, instruction: "Portion about 1 cup oats per firefighter into bowls or lidded containers. Keep the oat base over ice or return it to the refrigerator between waves; do not hold dairy oats at room temperature for more than 2 hours." },
      { stepNumber: 6, title: "Manage call interruptions", minutes: 0, instruction: "Cover the oat container and refrigerate toppings when the alarm sounds. Re-set only the amount needed when the crew returns; the bar is cold-service friendly, but fruit and dairy must remain temperature controlled." },
    ],
    stationWorkflow: [
      "Mix the base after dinner or before shift change so it is fully hydrated for the next morning.",
      "Place the oat container on the cold end of the breakfast line and refresh toppings in small bowls rather than leaving all food out.",
      "Pack individual lidded portions first when the hall expects a training departure or staggered apparatus checks.",
    ],
    cleanupNotes: [
      "Rinse oat containers and serving spoons immediately; dried oats and chia gel are much harder to scrub later.",
      "Keep nut butter utensils separate from other toppings to reduce cross-contact on the service line.",
    ],
    leftovers: [
      "Refrigerate leftover overnight oats within 2 hours and use within 3 days; they are served cold and do not require reheating.",
      "For a warm option, heat a dairy-free portion gently until steaming; any leftover meat or egg add-on must be reheated separately to 165°F.",
    ],
    heroImage: hero("overnight-oat-bar-crew"),
    thumbImage: thumb("overnight-oat-bar-crew"),
    imageAlt: "Crew-sized overnight oat bar with berries, banana, nut butter, granola, and scoop-and-go bowls",
    publishedAt: now,
    updatedAt: now,
    readMinutes: 6,
    seoTitle: "Overnight Oat Bar for the Crew | Firehall Breakfast",
  },
];

export const BATCH_WAVE1_BREAKFAST_COUNT = BATCH_WAVE1_BREAKFAST_PAGES.length;
