import type { BreakfastRecipePage } from "../breakfast-schema.js";

/**
 * High-Protein / Healthy Breakfast Expansion.
 * Nutrition is intentionally omitted here — the generator
 * (scripts/generate-breakfast-catalog.ts) computes real per-serving macros
 * from these ingredient lists via shared/nutrition/calculate.ts before publish.
 */
export type BreakfastRecipePageDraft = Omit<BreakfastRecipePage, "nutrition">;

const now = new Date().toISOString();
const hero = (slug: string) => `/images/breakfast/${slug}.jpg`;
const thumb = (slug: string) => `/images/thumbs/breakfast/${slug}.jpg`;

export const BATCH_HIGH_PROTEIN_BREAKFAST_PAGES: BreakfastRecipePageDraft[] = [
  {
    slug: "firehouse-breakfast-protein-bowls",
    title: "Firehouse Breakfast Protein Bowls",
    subtitle: "Roasted sweet potato, eggs, and chicken sausage in a savory high-protein breakfast bowl.",
    description:
      "Roasted sweet potato cubes are topped with scrambled eggs, browned chicken sausage, salsa, and a spoon of cottage cheese. It is a savory, fully composed breakfast bowl built to hold real protein instead of just carbs.",
    filters: ["feed_a_crew", "high_protein", "healthy_breakfasts"],
    tags: ["breakfast-bowl", "sweet-potato", "eggs", "chicken-sausage", "high-protein"],
    crewSize: 8,
    baseServings: 8,
    prepTime: 15,
    cookTime: 25,
    totalTime: 40,
    difficulty: "easy",
    ingredients: [
      { group: "Base", quantity: "3.5 lb", name: "sweet potato", notes: "peeled, 1/2-inch cubes" },
      { group: "Base", quantity: "3 tbsp", name: "olive oil" },
      { group: "Protein", quantity: "2 lb", name: "chicken sausage", notes: "casings removed, or turkey sausage" },
      { group: "Protein", quantity: "16", name: "large eggs" },
      { group: "Protein", quantity: "2 tbsp", name: "butter" },
      { group: "Toppings", quantity: "1 1/2 cups", name: "cottage cheese" },
      { group: "Toppings", quantity: "1 1/2 cups", name: "salsa" },
      { group: "Toppings", quantity: "1/2 cup", name: "green onions", notes: "sliced" },
      { group: "Toppings", quantity: "2", name: "avocado", notes: "sliced", optional: true },
    ],
    steps: [
      { stepNumber: 1, title: "Roast the sweet potato", minutes: 22, tempF: 425, instruction: "Heat oven to 425°F. Toss sweet potato cubes with olive oil, salt, and pepper on a sheet pan. Roast 20–22 minutes, turning once, until browned at the edges and fork-tender." },
      { stepNumber: 2, title: "Brown the chicken sausage", minutes: 10, instruction: "While the potatoes roast, brown chicken sausage in a large skillet over medium-high, breaking it into crumbles, 8–10 minutes until cooked through and browned." },
      { stepNumber: 3, title: "Scramble the eggs", minutes: 6, instruction: "Lower heat to medium-low. Melt butter in a separate pan, add whisked eggs, and stir gently until just set and still glossy. Season with salt and pepper." },
      { stepNumber: 4, title: "Hold everything separately", minutes: 5, instruction: "Keep sweet potato, sausage, and eggs in separate covered dishes in a 200°F oven until ready to build bowls — combining them too early turns the eggs rubbery." },
      { stepNumber: 5, title: "Build the bowls", minutes: 8, instruction: "Layer roasted sweet potato in each bowl, add a portion of sausage and scrambled eggs, then top with cottage cheese, salsa, green onions, and avocado if using." },
    ],
    stationWorkflow: [
      "Get sweet potatoes into the oven first — they take the longest of any component.",
      "Cook sausage and eggs in separate pans so eggs stay soft instead of picking up grease.",
      "Hold sweet potato and sausage covered at 200°F; scramble eggs closer to service so they stay tender.",
    ],
    cleanupNotes: [
      "Wipe down the egg pan while it's still warm — cooked egg sets hard once it cools completely.",
      "Soak the sausage skillet in hot water while plates are served to loosen any browned bits.",
    ],
    leftovers: [
      "Store sweet potato, sausage, and eggs in separate containers up to 4 days; reheat eggs gently on low power.",
      "Rebuild bowls with cold cottage cheese, salsa, and avocado added fresh rather than reheated.",
    ],
    heroImage: hero("firehouse-breakfast-protein-bowls"),
    thumbImage: thumb("firehouse-breakfast-protein-bowls"),
    imageAlt: "Firehouse breakfast protein bowl with roasted sweet potato, scrambled eggs, chicken sausage, and salsa",
    publishedAt: now,
    updatedAt: now,
    readMinutes: 6,
    seoTitle: "Firehouse Breakfast Protein Bowls | Firehall Breakfast",
  },
  {
    slug: "peanut-butter-protein-overnight-oats",
    title: "Peanut Butter Protein Overnight Oats",
    subtitle: "No-cook overnight oats built with Greek yogurt and peanut butter for a grab-and-go breakfast.",
    description:
      "Rolled oats soak overnight in milk and Greek yogurt with peanut butter and a touch of honey, then get topped with banana and extra peanut butter in the morning. No stove time and no line — just jars in the fridge.",
    filters: ["quick_breakfasts", "healthy_breakfasts"],
    tags: ["overnight-oats", "no-cook", "peanut-butter", "greek-yogurt", "make-ahead"],
    crewSize: 8,
    baseServings: 8,
    prepTime: 12,
    cookTime: 5,
    totalTime: 17,
    difficulty: "easy",
    ingredients: [
      { group: "Base", quantity: "4 cups", name: "rolled oats" },
      { group: "Base", quantity: "4 cups", name: "whole milk", notes: "or oat milk" },
      { group: "Protein", quantity: "3 cups", name: "greek yogurt", notes: "plain" },
      { group: "Flavor", quantity: "1 cup", name: "peanut butter", notes: "plus more for topping" },
      { group: "Flavor", quantity: "1/3 cup", name: "honey" },
      { group: "Flavor", quantity: "1 tsp", name: "vanilla extract", optional: true },
      { group: "Topping", quantity: "3", name: "banana", notes: "sliced", optional: true },
    ],
    steps: [
      { stepNumber: 1, title: "Whisk the base", minutes: 5, instruction: "Whisk milk, Greek yogurt, peanut butter, honey, and vanilla in a large bowl or pitcher until the peanut butter is fully incorporated and no streaks remain." },
      { stepNumber: 2, title: "Add the oats", minutes: 3, instruction: "Stir in rolled oats until evenly coated in the peanut butter-yogurt mixture." },
      { stepNumber: 3, title: "Portion into jars", minutes: 6, instruction: "Divide the mixture evenly into 8 jars or containers with lids. Seal and refrigerate at least 6 hours, or overnight, until the oats soften and thicken." },
      { stepNumber: 4, title: "Top and serve", minutes: 0, instruction: "Stir each jar before eating — the mixture settles overnight. Top with sliced banana and an extra spoonful of peanut butter if desired." },
    ],
    stationWorkflow: [
      "Batch-mix the base the night before so morning service is just grab-and-go.",
      "Keep jars labeled with the date; overnight oats are best within 4 days.",
      "Set out banana and extra peanut butter as optional toppings rather than mixing them in ahead.",
    ],
    cleanupNotes: [
      "Rinse peanut butter measuring cups immediately in hot water before it hardens on the sides.",
      "Wash jars right after emptying — dried oat residue is much harder to scrub off once set.",
    ],
    leftovers: [
      "Keeps well sealed in the refrigerator up to 4 days.",
      "If oats thicken too much overnight, stir in a splash of milk before eating.",
    ],
    heroImage: hero("peanut-butter-protein-overnight-oats"),
    thumbImage: thumb("peanut-butter-protein-overnight-oats"),
    imageAlt: "Jar of peanut butter protein overnight oats topped with sliced banana",
    publishedAt: now,
    updatedAt: now,
    readMinutes: 4,
    seoTitle: "Peanut Butter Protein Overnight Oats | Firehall Breakfast",
  },
  {
    slug: "berry-vanilla-protein-overnight-oats",
    title: "Berry Vanilla Protein Overnight Oats",
    subtitle: "Greek yogurt overnight oats with vanilla and mixed berries, ready straight from the fridge.",
    description:
      "Oats soak overnight in milk, Greek yogurt, and vanilla, then get topped with mixed berries and a drizzle of honey. It is a lighter, fruit-forward alternative to the peanut butter version for crews who want something brighter in the morning.",
    filters: ["quick_breakfasts", "healthy_breakfasts"],
    tags: ["overnight-oats", "no-cook", "berries", "greek-yogurt", "make-ahead"],
    crewSize: 8,
    baseServings: 8,
    prepTime: 10,
    cookTime: 5,
    totalTime: 15,
    difficulty: "easy",
    ingredients: [
      { group: "Base", quantity: "4 cups", name: "rolled oats" },
      { group: "Base", quantity: "4 cups", name: "whole milk", notes: "or almond milk" },
      { group: "Protein", quantity: "3 cups", name: "greek yogurt", notes: "plain" },
      { group: "Flavor", quantity: "1/3 cup", name: "honey" },
      { group: "Flavor", quantity: "2 tsp", name: "vanilla extract" },
      { group: "Topping", quantity: "4 cups", name: "mixed berries", notes: "fresh or thawed" },
      { group: "Topping", quantity: "1/2 cup", name: "chia seeds", notes: "optional protein and fiber boost", optional: true },
    ],
    steps: [
      { stepNumber: 1, title: "Whisk the base", minutes: 4, instruction: "Whisk milk, Greek yogurt, honey, and vanilla together in a large bowl or pitcher until smooth." },
      { stepNumber: 2, title: "Add oats and chia", minutes: 3, instruction: "Stir in rolled oats and chia seeds if using, mixing until fully coated." },
      { stepNumber: 3, title: "Portion and chill", minutes: 5, instruction: "Divide evenly into 8 jars, seal, and refrigerate at least 6 hours or overnight until thickened." },
      { stepNumber: 4, title: "Top with berries", minutes: 0, instruction: "Stir each jar before serving, then top with mixed berries. Add a little extra milk if the oats seem too thick." },
    ],
    stationWorkflow: [
      "Prep this the night before a busy shift so breakfast requires zero stove time.",
      "Keep berries separate until serving so they don't turn the oats watery in storage.",
      "Batch mix the base in one pitcher, then portion into jars for speed.",
    ],
    cleanupNotes: [
      "Rinse the mixing pitcher right away — yogurt residue dries stubborn if left overnight.",
      "Wash jars promptly after use to avoid stuck-on oats.",
    ],
    leftovers: [
      "Keeps sealed in the refrigerator up to 4 days.",
      "Add berries fresh each morning rather than storing them mixed in for the whole batch.",
    ],
    heroImage: hero("berry-vanilla-protein-overnight-oats"),
    thumbImage: thumb("berry-vanilla-protein-overnight-oats"),
    imageAlt: "Jar of berry vanilla protein overnight oats topped with mixed berries",
    publishedAt: now,
    updatedAt: now,
    readMinutes: 4,
    seoTitle: "Berry Vanilla Protein Overnight Oats | Firehall Breakfast",
  },
  {
    slug: "turkey-sausage-egg-white-sandwiches",
    title: "Turkey Sausage Egg White Breakfast Sandwiches",
    subtitle: "A leaner breakfast sandwich built on turkey sausage, egg whites, and whole English muffins.",
    description:
      "Turkey sausage patties and fluffy egg whites are stacked on toasted English muffins with a slice of cheese. It is a lighter take on the hall's usual breakfast sandwich, built for crews watching fat without giving up a real handheld breakfast.",
    filters: ["breakfast_sandwiches", "high_protein", "healthy_breakfasts"],
    tags: ["sandwiches", "turkey-sausage", "egg-whites", "english-muffin", "leaner"],
    crewSize: 8,
    baseServings: 8,
    prepTime: 10,
    cookTime: 16,
    totalTime: 26,
    difficulty: "easy",
    ingredients: [
      { group: "Protein", quantity: "2 lb", name: "turkey sausage", notes: "formed into 8 thin patties" },
      { group: "Protein", quantity: "24", name: "egg whites", notes: "or 3 cups liquid egg whites" },
      { group: "Build", quantity: "8", name: "english muffin", notes: "split" },
      { group: "Build", quantity: "8 slices", name: "cheddar cheese", notes: "or reduced-fat cheese" },
      { group: "Build", quantity: "1 tbsp", name: "butter", notes: "for the pan" },
      { group: "Build", quantity: "1", name: "hot sauce", optional: true },
    ],
    steps: [
      { stepNumber: 1, title: "Toast the muffins", minutes: 5, instruction: "Split and toast English muffins on a griddle or under the broiler until golden. Hold warm on a tray." },
      { stepNumber: 2, title: "Cook the turkey sausage", minutes: 8, instruction: "Cook turkey sausage patties in a skillet over medium heat 4 minutes per side until browned and 165°F internal. Turkey sausage has less fat than pork, so watch closely — it can dry out if pushed too hot." },
      { stepNumber: 3, title: "Cook the egg whites", minutes: 6, instruction: "Melt butter in a nonstick pan over medium-low. Pour in egg whites and cook gently, stirring occasionally, until just set — egg whites firm up faster than whole eggs, so pull them a little early." },
      { stepNumber: 4, title: "Assemble the sandwiches", minutes: 6, instruction: "Layer sausage, a portion of egg whites, and cheese on the bottom muffin half. Close and hold wrapped in foil on a warm tray until served." },
      { stepNumber: 5, title: "Hold and serve", minutes: 0, instruction: "Hold wrapped sandwiches in a 200°F oven up to 15 minutes if serving is staggered. Serve with hot sauce on the side." },
    ],
    stationWorkflow: [
      "Toast muffins first since they hold well wrapped while the rest finishes.",
      "Cook sausage and egg whites in separate pans so timing for each stays accurate.",
      "Assemble sandwiches just before service — egg whites lose their texture if they sit built too long.",
    ],
    cleanupNotes: [
      "Wipe the egg white pan while still warm — a nonstick surface is easiest to clean before it cools.",
      "Drain the sausage skillet promptly; turkey sausage renders less fat than pork but it still sets up if left to cool in the pan.",
    ],
    leftovers: [
      "Store sausage and egg whites separately from muffins to avoid sogginess.",
      "Reheat sausage and eggs covered at 300°F for 8 minutes, then rebuild sandwiches fresh.",
    ],
    heroImage: hero("turkey-sausage-egg-white-sandwiches"),
    thumbImage: thumb("turkey-sausage-egg-white-sandwiches"),
    imageAlt: "Turkey sausage and egg white breakfast sandwich on a toasted English muffin",
    publishedAt: now,
    updatedAt: now,
    readMinutes: 5,
    seoTitle: "Turkey Sausage Egg White Sandwiches | Firehall Breakfast",
  },
  {
    slug: "black-bean-egg-white-breakfast-burritos",
    title: "Black Bean & Egg White Breakfast Burritos",
    subtitle: "Vegetarian breakfast burritos built on egg whites, black beans, and pepper jack.",
    description:
      "Egg whites scramble up with black beans, bell pepper, and onion, then get wrapped in a warm tortilla with pepper jack and salsa. It is a fully vegetarian, higher-protein burrito option next to the hall's usual sausage versions.",
    filters: ["feed_a_crew", "healthy_breakfasts"],
    tags: ["burritos", "vegetarian", "egg-whites", "black-beans", "make-ahead"],
    crewSize: 8,
    baseServings: 8,
    prepTime: 15,
    cookTime: 16,
    totalTime: 31,
    difficulty: "easy",
    ingredients: [
      { group: "Eggs", quantity: "24", name: "egg whites", notes: "or 3 cups liquid egg whites" },
      { group: "Fillings", quantity: "2 cans", name: "black beans", notes: "drained, rinsed" },
      { group: "Fillings", quantity: "2", name: "bell pepper", notes: "diced" },
      { group: "Fillings", quantity: "1", name: "yellow onion", notes: "diced" },
      { group: "Fillings", quantity: "1 1/2 cups", name: "pepper jack cheese", notes: "shredded" },
      { group: "Build", quantity: "12", name: "flour tortilla", notes: "10-inch" },
      { group: "Build", quantity: "1 cup", name: "salsa" },
      { group: "Build", quantity: "1", name: "hot sauce", optional: true },
    ],
    steps: [
      { stepNumber: 1, title: "Sauté the vegetables", minutes: 6, instruction: "Heat a splash of oil in a large skillet over medium. Cook onion and bell pepper 5–6 minutes until softened." },
      { stepNumber: 2, title: "Warm the black beans", minutes: 5, instruction: "Add black beans to the pan with the vegetables and warm through, 4–5 minutes, seasoning with a pinch of salt and cumin if desired." },
      { stepNumber: 3, title: "Scramble the egg whites", minutes: 6, instruction: "Move beans and vegetables to one side of the pan or a separate pan. Pour in egg whites and scramble gently over medium-low until just set — they firm up fast, so don't walk away." },
      { stepNumber: 4, title: "Build and wrap for the line", minutes: 10, instruction: "Warm tortillas briefly. Fill with egg whites, bean-vegetable mixture, cheese, and a spoon of salsa. Fold in the sides, then roll forward tightly. Hold seam-side down on a warm tray." },
      { stepNumber: 5, title: "Serve and hold", minutes: 0, instruction: "Hold wrapped burritos in a 200°F oven, uncovered for a crisper tortilla or covered for a softer one. Serve with hot sauce on the side." },
    ],
    stationWorkflow: [
      "Cook vegetables and beans first since they hold well while the egg whites finish.",
      "Scramble egg whites gently and pull them slightly underdone — they keep setting off the heat.",
      "Wrap burritos tightly so fillings stay contained through the line.",
    ],
    cleanupNotes: [
      "Wipe the egg white pan while warm to prevent set residue from sticking.",
      "Rinse the bean pan promptly — bean starch dries stubborn if left to sit.",
    ],
    leftovers: [
      "Wrap cooled burritos individually in foil and refrigerate up to 4 days, or freeze up to 2 months.",
      "Reheat wrapped in foil at 350°F for 15–18 minutes, or unwrapped in a skillet for a crisper tortilla.",
    ],
    heroImage: hero("black-bean-egg-white-breakfast-burritos"),
    thumbImage: thumb("black-bean-egg-white-breakfast-burritos"),
    imageAlt: "Black bean and egg white breakfast burrito sliced open on a plate",
    publishedAt: now,
    updatedAt: now,
    readMinutes: 5,
    seoTitle: "Black Bean Egg White Breakfast Burritos | Firehall Breakfast",
  },
  {
    slug: "cottage-cheese-veggie-egg-bake",
    title: "Cottage Cheese Veggie Egg Bake",
    subtitle: "A vegetarian egg bake with cottage cheese folded in for extra protein and a creamier texture.",
    description:
      "Eggs, cottage cheese, spinach, and roasted bell pepper bake into a firm, sliceable casserole. Cottage cheese adds protein and a slightly creamier texture than a standard egg bake, without any meat in the pan.",
    filters: ["feed_a_crew", "healthy_breakfasts"],
    tags: ["egg-bake", "cottage-cheese", "vegetarian", "spinach", "9x13"],
    crewSize: 8,
    baseServings: 8,
    prepTime: 15,
    cookTime: 34,
    totalTime: 49,
    difficulty: "easy",
    ingredients: [
      { group: "Eggs", quantity: "12", name: "large eggs" },
      { group: "Eggs", quantity: "1 1/2 cups", name: "cottage cheese" },
      { group: "Vegetables", quantity: "1", name: "yellow onion", notes: "diced" },
      { group: "Vegetables", quantity: "2", name: "bell pepper", notes: "diced" },
      { group: "Vegetables", quantity: "6 oz", name: "baby spinach", notes: "sautéed and squeezed dry" },
      { group: "Cheese", quantity: "1 1/2 cups", name: "shredded cheese", notes: "cheddar or mozzarella" },
      { group: "Seasoning", quantity: "1 tsp", name: "dried thyme" },
    ],
    steps: [
      { stepNumber: 1, title: "Heat the oven and prep the pan", minutes: 0, tempF: 375, instruction: "Heat oven to 375°F. Grease a 9x13 pan." },
      { stepNumber: 2, title: "Sauté the vegetables", minutes: 8, instruction: "Sauté onion and bell pepper in a splash of oil over medium 5–6 minutes until softened. Add spinach and cook just until wilted, then squeeze out excess liquid before it goes in the pan." },
      { stepNumber: 3, title: "Whisk the egg-cottage cheese base", minutes: 5, instruction: "Whisk eggs and cottage cheese together with thyme, salt, and pepper until mostly smooth — small curds of cottage cheese are fine and expected." },
      { stepNumber: 4, title: "Build and bake", minutes: 31, tempF: 375, instruction: "Spread the sautéed vegetables in the pan, pour the egg mixture over the top, and scatter with cheese. Bake 28–31 minutes until the center is set and the top is lightly browned." },
      { stepNumber: 5, title: "Rest and slice", minutes: 10, instruction: "Rest 10 minutes before slicing so squares hold together for the line instead of falling apart." },
    ],
    stationWorkflow: [
      "Squeeze sautéed spinach dry before adding it — excess water waters down the bake and slows setting.",
      "Whisk the egg-cottage cheese base well so it pours evenly over the vegetables.",
      "Rest the finished bake before cutting so slices come out clean.",
    ],
    cleanupNotes: [
      "Soak the baking dish immediately after service — baked egg sets hard once it cools.",
      "Wipe the sauté pan while warm to prevent vegetable residue from sticking.",
    ],
    leftovers: [
      "Cool completely, then refrigerate covered up to 4 days.",
      "Reheat individual slices covered at 325°F for 10 minutes, or in the microwave at 50% power.",
    ],
    heroImage: hero("cottage-cheese-veggie-egg-bake"),
    thumbImage: thumb("cottage-cheese-veggie-egg-bake"),
    imageAlt: "Sliced cottage cheese vegetable egg bake in a baking dish",
    publishedAt: now,
    updatedAt: now,
    readMinutes: 5,
    seoTitle: "Cottage Cheese Veggie Egg Bake | Firehall Breakfast",
  },
  {
    slug: "turkey-sausage-sweet-potato-skillet",
    title: "Turkey Sausage & Sweet Potato Breakfast Skillet",
    subtitle: "A leaner cast-iron breakfast built on turkey sausage, sweet potato, and eggs.",
    description:
      "Turkey sausage and diced sweet potato crisp together in a cast-iron skillet, finished with eggs cracked over the top. It follows the hall's classic breakfast skillet format with a leaner sausage and a sweeter, more fiber-forward potato base.",
    filters: ["skillets", "high_protein", "healthy_breakfasts"],
    tags: ["cast-iron", "turkey-sausage", "sweet-potato", "eggs", "one-pan"],
    crewSize: 8,
    baseServings: 8,
    prepTime: 15,
    cookTime: 24,
    totalTime: 39,
    difficulty: "easy",
    ingredients: [
      { group: "Base", quantity: "3 lb", name: "sweet potato", notes: "diced 1/2-inch" },
      { group: "Protein", quantity: "2 lb", name: "turkey sausage", notes: "casings removed" },
      { group: "Protein", quantity: "14", name: "large eggs" },
      { group: "Aromatics", quantity: "1", name: "yellow onion", notes: "diced" },
      { group: "Aromatics", quantity: "1", name: "bell pepper", notes: "diced" },
      { group: "Aromatics", quantity: "2 tbsp", name: "olive oil" },
      { group: "Finish", quantity: "1 cup", name: "shredded cheese", notes: "cheddar", optional: true },
    ],
    steps: [
      { stepNumber: 1, title: "Par-cook the sweet potato", minutes: 8, instruction: "Microwave diced sweet potato with a splash of water in a covered bowl until just tender. This cuts skillet time significantly and helps it crisp rather than steam." },
      { stepNumber: 2, title: "Build the crispy base", minutes: 12, instruction: "Heat cast iron over medium-high with oil. Add sweet potato in a single layer; let it sit 3–4 minutes for color before tossing. Add onion and pepper and cook until softened." },
      { stepNumber: 3, title: "Brown the turkey sausage", minutes: 8, instruction: "Push vegetables to one side. Add turkey sausage and break into crumbles, cooking 7–8 minutes until browned and 165°F. Fold everything together once cooked through." },
      { stepNumber: 4, title: "Make wells for the eggs", minutes: 3, instruction: "Make shallow wells across the skillet and crack an egg into each well. Season with salt and pepper." },
      { stepNumber: 5, title: "Cover and finish", minutes: 6, instruction: "Cover with a lid or inverted sheet pan over medium-low heat until egg whites are fully set and yolks are cooked to preference. Add cheese in the last minute to melt if using." },
    ],
    stationWorkflow: [
      "Par-cook sweet potato in the microwave first to save real skillet time.",
      "Build the crispy base before adding sausage so both get proper browning.",
      "Add eggs last so they finish exactly when the rest of the skillet is ready.",
    ],
    cleanupNotes: [
      "Deglaze the cast iron with hot water while still warm, then scrub once cool enough to handle.",
      "Wipe down cutting boards immediately after raw sausage prep before eggs go anywhere near them.",
    ],
    leftovers: [
      "Reheat the potato-sausage base covered at 325°F for 10 minutes; fry fresh eggs rather than reheating set yolks.",
      "Chop leftovers into a breakfast wrap with hot sauce for a fast next-shift meal.",
    ],
    heroImage: hero("turkey-sausage-sweet-potato-skillet"),
    thumbImage: thumb("turkey-sausage-sweet-potato-skillet"),
    imageAlt: "Cast-iron skillet with turkey sausage, sweet potato, and eggs for the crew",
    publishedAt: now,
    updatedAt: now,
    readMinutes: 6,
    seoTitle: "Turkey Sausage Sweet Potato Skillet | Firehall Breakfast",
  },
  {
    slug: "savory-cottage-cheese-breakfast-bowls",
    title: "Savory Cottage Cheese Breakfast Bowls",
    subtitle: "A fast, no-cook breakfast bowl built on cottage cheese, cucumber, tomato, and everything seasoning.",
    description:
      "Cottage cheese is topped with diced cucumber, cherry tomatoes, avocado, and an everything-bagel seasoning for a savory, no-cook breakfast. It is built for mornings when nobody wants to fire up the stove but still wants real protein.",
    filters: ["quick_breakfasts", "healthy_breakfasts"],
    tags: ["cottage-cheese", "no-cook", "vegetarian", "quick", "savory"],
    crewSize: 8,
    baseServings: 8,
    prepTime: 15,
    cookTime: 5,
    totalTime: 20,
    difficulty: "easy",
    ingredients: [
      { group: "Base", quantity: "64 oz", name: "cottage cheese" },
      { group: "Toppings", quantity: "3", name: "cucumber", notes: "diced" },
      { group: "Toppings", quantity: "2 2/3 cups", name: "cherry tomatoes", notes: "halved" },
      { group: "Toppings", quantity: "3", name: "avocado", notes: "diced" },
      { group: "Toppings", quantity: "3 tbsp", name: "everything bagel seasoning", optional: true },
      { group: "Toppings", quantity: "1", name: "hot sauce", optional: true },
      { group: "Toppings", quantity: "1", name: "olive oil", notes: "for drizzling", optional: true },
    ],
    steps: [
      { stepNumber: 1, title: "Prep the line", minutes: 8, instruction: "Dice cucumber and avocado, halve cherry tomatoes, and set cottage cheese and each topping out in separate bowls so the crew can build their own without cross-contamination." },
      { stepNumber: 2, title: "Build order", minutes: 4, instruction: "Scoop cottage cheese into a bowl first, then top with cucumber, tomatoes, and avocado. Finish with everything seasoning and a light drizzle of olive oil." },
      { stepNumber: 3, title: "Hold briefly", minutes: 0, instruction: "This bowl holds about 20 minutes covered in the fridge before the cucumber and tomato start releasing water — build close to serving time when possible." },
      { stepNumber: 4, title: "Serve cold", minutes: 0, instruction: "Serve cold with hot sauce on the side for anyone who wants heat. This is a fast, no-stove option when the hall is busy." },
    ],
    stationWorkflow: [
      "Set out cottage cheese and all toppings in separate bowls for a self-serve build.",
      "Keep tomatoes and cucumber cold until the moment of assembly so bowls don't get watery.",
      "Have everything seasoning and hot sauce within reach at the end of the line.",
    ],
    cleanupNotes: [
      "Rinse the cutting board right after dicing vegetables — no cooked residue to worry about, but keep raw-produce boards separate from any meat prep that day.",
      "Store unused toppings back in the fridge immediately rather than leaving them out.",
    ],
    leftovers: [
      "Best assembled fresh — store cottage cheese and toppings separately if planning ahead.",
      "Cottage cheese itself keeps up to a week; diced vegetables are best used within 2 days.",
    ],
    heroImage: hero("savory-cottage-cheese-breakfast-bowls"),
    thumbImage: thumb("savory-cottage-cheese-breakfast-bowls"),
    imageAlt: "Savory cottage cheese breakfast bowl with cucumber, tomato, and avocado",
    publishedAt: now,
    updatedAt: now,
    readMinutes: 4,
    seoTitle: "Savory Cottage Cheese Breakfast Bowls | Firehall Breakfast",
  },
  {
    slug: "egg-white-black-bean-breakfast-quesadillas",
    title: "Egg White & Black Bean Breakfast Quesadillas",
    subtitle: "Crisp breakfast quesadillas filled with egg whites, black beans, and pepper jack.",
    description:
      "Egg whites, black beans, and pepper jack get folded into a tortilla and griddled until crisp outside and melted inside. It is a fast, handheld, vegetarian breakfast with a leaner fat profile than a whole-egg quesadilla.",
    filters: ["quick_breakfasts", "healthy_breakfasts"],
    tags: ["quesadillas", "egg-whites", "vegetarian", "black-beans", "quick"],
    crewSize: 8,
    baseServings: 8,
    prepTime: 10,
    cookTime: 16,
    totalTime: 26,
    difficulty: "easy",
    ingredients: [
      { group: "Eggs", quantity: "20", name: "egg whites", notes: "or 2.5 cups liquid egg whites" },
      { group: "Fillings", quantity: "1 can", name: "black beans", notes: "drained, rinsed" },
      { group: "Fillings", quantity: "2 cups", name: "pepper jack cheese", notes: "shredded" },
      { group: "Fillings", quantity: "1/2 cup", name: "salsa" },
      { group: "Build", quantity: "8", name: "flour tortilla", notes: "10-inch" },
      { group: "Build", quantity: "2 tbsp", name: "olive oil", notes: "for the griddle" },
    ],
    steps: [
      { stepNumber: 1, title: "Scramble the egg whites", minutes: 6, instruction: "Cook egg whites in a nonstick skillet over medium-low, stirring gently, until just set. Pull them a little early since they continue to firm up off the heat." },
      { stepNumber: 2, title: "Warm the black beans", minutes: 4, instruction: "Warm black beans in a small saucepan with a splash of water and a pinch of cumin until heated through." },
      { stepNumber: 3, title: "Fill the tortillas", minutes: 6, instruction: "Lay tortillas flat and cover one half with cheese, egg whites, beans, and a spoon of salsa. Fold in half over the filling." },
      { stepNumber: 4, title: "Griddle until crisp", minutes: 8, instruction: "Heat a lightly oiled griddle or skillet over medium. Cook quesadillas 3–4 minutes per side until golden and crisp outside and the cheese has melted through." },
      { stepNumber: 5, title: "Slice and serve", minutes: 2, instruction: "Rest 1 minute, then slice into wedges. Serve immediately while the tortilla is still crisp — quesadillas soften fast once stacked." },
    ],
    stationWorkflow: [
      "Cook egg whites and beans ahead so assembly and griddling go quickly.",
      "Fill tortillas just before griddling — a filled, unheated quesadilla gets soggy waiting.",
      "Slice each quesadilla right before serving so the crust stays crisp.",
    ],
    cleanupNotes: [
      "Wipe the griddle between batches so melted cheese doesn't build up and burn.",
      "Clean the egg white pan while warm for the easiest scrub.",
    ],
    leftovers: [
      "Store cooked quesadillas in the fridge up to 3 days.",
      "Reheat in a dry skillet over medium heat to re-crisp rather than microwaving them soft.",
    ],
    heroImage: hero("egg-white-black-bean-breakfast-quesadillas"),
    thumbImage: thumb("egg-white-black-bean-breakfast-quesadillas"),
    imageAlt: "Sliced egg white breakfast quesadilla with black beans and pepper jack cheese",
    publishedAt: now,
    updatedAt: now,
    readMinutes: 5,
    seoTitle: "Egg White Breakfast Quesadillas | Firehall Breakfast",
  },
  {
    slug: "high-protein-breakfast-burrito-bowls",
    title: "High-Protein Breakfast Burrito Bowls",
    subtitle: "A deconstructed breakfast burrito over rice with ground turkey, eggs, and black beans.",
    description:
      "Seasoned ground turkey, scrambled eggs, black beans, and brown rice build into a bowl instead of a wrap, finished with pico de gallo, cheese, and avocado. It is a fork-and-bowl format for crews who want burrito flavor without the tortilla.",
    filters: ["feed_a_crew", "high_protein", "healthy_breakfasts"],
    tags: ["breakfast-bowl", "ground-turkey", "black-beans", "eggs", "meal-prep"],
    crewSize: 8,
    baseServings: 8,
    prepTime: 15,
    cookTime: 25,
    totalTime: 40,
    difficulty: "easy",
    ingredients: [
      { group: "Base", quantity: "2 cups", name: "brown rice", notes: "uncooked" },
      { group: "Protein", quantity: "2 lb", name: "ground turkey" },
      { group: "Protein", quantity: "16", name: "large eggs" },
      { group: "Protein", quantity: "2 cans", name: "black beans", notes: "drained, rinsed" },
      { group: "Seasoning", quantity: "2 tbsp", name: "taco seasoning" },
      { group: "Toppings", quantity: "1 1/2 cups", name: "pico de gallo", notes: "or diced tomato and onion" },
      { group: "Toppings", quantity: "1 1/2 cups", name: "shredded cheese", notes: "cheddar or Mexican blend" },
      { group: "Toppings", quantity: "2", name: "avocado", notes: "sliced" },
      { group: "Toppings", quantity: "1 cup", name: "greek yogurt", notes: "plain, in place of sour cream", optional: true },
    ],
    steps: [
      { stepNumber: 1, title: "Cook the rice", minutes: 40, instruction: "Cook brown rice according to package directions. This takes the longest, so start it first and hold covered until bowls are built." },
      { stepNumber: 2, title: "Brown the ground turkey", minutes: 10, instruction: "Brown ground turkey in a large skillet over medium-high, breaking it into crumbles. Stir in taco seasoning and a splash of water, and simmer 2 minutes until coated." },
      { stepNumber: 3, title: "Warm the black beans", minutes: 5, instruction: "Warm black beans in a small saucepan with a pinch of salt and cumin while the turkey finishes." },
      { stepNumber: 4, title: "Scramble the eggs", minutes: 6, instruction: "In a separate nonstick pan, scramble eggs over medium-low until just set. Keep them soft — they will finish warming once bowls are built." },
      { stepNumber: 5, title: "Build the bowls", minutes: 8, instruction: "Layer rice, ground turkey, black beans, and scrambled eggs in each bowl. Top with pico de gallo, cheese, avocado, and a spoon of Greek yogurt if using." },
    ],
    stationWorkflow: [
      "Start the rice first since it takes the longest of any component.",
      "Cook turkey, beans, and eggs in separate pans so each stays properly textured.",
      "Set toppings out buffet-style so crew members can build bowls to their own taste.",
    ],
    cleanupNotes: [
      "Wipe the egg pan while still warm — cooked egg is much harder to scrub once cool.",
      "Rinse the rice pot promptly so starch doesn't dry stuck to the bottom.",
    ],
    leftovers: [
      "Store rice, turkey, beans, and eggs in separate containers up to 4 days for the cleanest reheats.",
      "Add pico, avocado, and yogurt fresh each time rather than storing them mixed in.",
    ],
    heroImage: hero("high-protein-breakfast-burrito-bowls"),
    thumbImage: thumb("high-protein-breakfast-burrito-bowls"),
    imageAlt: "High-protein breakfast burrito bowl with ground turkey, eggs, black beans, and avocado",
    publishedAt: now,
    updatedAt: now,
    readMinutes: 6,
    seoTitle: "High-Protein Breakfast Burrito Bowls | Firehall Breakfast",
  },
  {
    slug: "turkey-bacon-white-bean-breakfast-hash",
    title: "Turkey Bacon & White Bean Breakfast Hash",
    subtitle: "A leaner skillet hash built on turkey bacon, white beans, and crisped potatoes.",
    description:
      "Turkey bacon and white beans fold into a crisped potato hash with peppers and onion, finished with eggs cooked over the top. White beans add fiber and body next to a leaner bacon than the hall's usual pork versions.",
    filters: ["skillets", "healthy_breakfasts"],
    tags: ["hash", "turkey-bacon", "white-beans", "eggs", "one-pan"],
    crewSize: 8,
    baseServings: 8,
    prepTime: 15,
    cookTime: 26,
    totalTime: 41,
    difficulty: "easy",
    ingredients: [
      { group: "Base", quantity: "3 lb", name: "russet potato", notes: "diced 1/2-inch" },
      { group: "Protein", quantity: "1 lb", name: "turkey bacon", notes: "diced" },
      { group: "Protein", quantity: "2 cans", name: "white beans", notes: "drained, rinsed" },
      { group: "Protein", quantity: "14", name: "large eggs" },
      { group: "Aromatics", quantity: "1", name: "yellow onion", notes: "diced" },
      { group: "Aromatics", quantity: "1", name: "bell pepper", notes: "diced" },
      { group: "Aromatics", quantity: "2 tbsp", name: "olive oil" },
    ],
    steps: [
      { stepNumber: 1, title: "Par-cook the potatoes", minutes: 8, instruction: "Microwave diced potatoes with a splash of water in a covered bowl until just tender. This cuts skillet time and helps them crisp instead of steam." },
      { stepNumber: 2, title: "Crisp the turkey bacon", minutes: 8, instruction: "Cook diced turkey bacon in a large skillet or two batches on a griddle over medium-high until browned and crisp at the edges. Remove and set aside, leaving the rendered fat in the pan." },
      { stepNumber: 3, title: "Crisp the potatoes", minutes: 10, instruction: "Add olive oil to the pan, then add par-cooked potatoes in a single layer. Let sit 3–4 minutes for color before tossing. Add onion and bell pepper and cook until softened and browned in spots." },
      { stepNumber: 4, title: "Fold in bacon and beans", minutes: 4, instruction: "Return turkey bacon to the pan along with white beans. Toss to combine and warm through." },
      { stepNumber: 5, title: "Top with eggs and finish", minutes: 6, instruction: "Make shallow wells in the hash and crack an egg into each. Cover with a lid or inverted sheet pan over medium-low until egg whites are set and yolks reach preference." },
    ],
    stationWorkflow: [
      "Par-cook potatoes in the microwave first to save real skillet time.",
      "Crisp turkey bacon before the potatoes so its rendered fat flavors the hash.",
      "Add eggs last so they finish exactly when the rest of the pan is ready.",
    ],
    cleanupNotes: [
      "Deglaze the skillet with hot water while still warm, then scrub once cool enough to handle.",
      "Wipe down cutting boards immediately after raw turkey bacon prep.",
    ],
    leftovers: [
      "Reheat the potato-bean base covered at 325°F for 10 minutes; fry fresh eggs rather than reheating set yolks.",
      "Keeps refrigerated up to 3 days.",
    ],
    heroImage: hero("turkey-bacon-white-bean-breakfast-hash"),
    thumbImage: thumb("turkey-bacon-white-bean-breakfast-hash"),
    imageAlt: "Skillet of turkey bacon and white bean breakfast hash with eggs cooked on top",
    publishedAt: now,
    updatedAt: now,
    readMinutes: 6,
    seoTitle: "Turkey Bacon White Bean Breakfast Hash | Firehall Breakfast",
  },
  {
    slug: "turkey-sausage-spinach-feta-egg-white-scramble",
    title: "Turkey Sausage, Spinach & Feta Egg White Scramble",
    subtitle: "A leaner scramble built on egg whites, turkey sausage, spinach, and feta.",
    description:
      "Egg whites scramble with browned turkey sausage, wilted spinach, and crumbled feta for a savory, leaner breakfast with a Mediterranean-leaning flavor. It holds well on the line and reheats cleanly for a next-shift breakfast.",
    filters: ["healthy_breakfasts", "high_protein"],
    tags: ["scramble", "egg-whites", "turkey-sausage", "spinach", "feta"],
    crewSize: 8,
    baseServings: 8,
    prepTime: 12,
    cookTime: 18,
    totalTime: 30,
    difficulty: "easy",
    ingredients: [
      { group: "Protein", quantity: "2 lb", name: "turkey sausage", notes: "casings removed" },
      { group: "Eggs", quantity: "28", name: "egg whites", notes: "or 3.5 cups liquid egg whites" },
      { group: "Vegetables", quantity: "8 oz", name: "baby spinach" },
      { group: "Cheese", quantity: "1 1/2 cups", name: "feta cheese", notes: "crumbled" },
      { group: "Aromatics", quantity: "1", name: "yellow onion", notes: "diced" },
      { group: "Aromatics", quantity: "2 tbsp", name: "olive oil" },
    ],
    steps: [
      { stepNumber: 1, title: "Brown the turkey sausage", minutes: 9, instruction: "Heat olive oil in a large skillet over medium-high. Brown turkey sausage, breaking it into crumbles, 8–9 minutes until cooked through." },
      { stepNumber: 2, title: "Soften the onion and spinach", minutes: 6, instruction: "Add onion to the pan with the sausage and cook until softened, about 4 minutes. Add spinach and cook just until wilted, 1–2 minutes." },
      { stepNumber: 3, title: "Scramble in the egg whites", minutes: 7, instruction: "Lower heat to medium-low. Pour egg whites over the sausage mixture and stir gently until just set — egg whites firm up faster than whole eggs, so pull the pan a little early." },
      { stepNumber: 4, title: "Finish with feta", minutes: 2, instruction: "Fold in crumbled feta off the heat so it stays soft rather than melting completely into the eggs." },
      { stepNumber: 5, title: "Hold and serve", minutes: 0, instruction: "Hold covered on low heat up to 10 minutes if service is staggered. Serve directly from the pan." },
    ],
    stationWorkflow: [
      "Brown sausage and soften vegetables before adding egg whites so the pan isn't overcrowded.",
      "Scramble egg whites gently and pull them slightly underdone — they keep setting off the heat.",
      "Fold feta in last so it stays in soft crumbles instead of melting away.",
    ],
    cleanupNotes: [
      "Wipe the pan while still warm — cooked egg white sets hard once it cools completely.",
      "Wash cutting boards immediately after raw sausage prep.",
    ],
    leftovers: [
      "Refrigerate covered up to 3 days.",
      "Reheat gently on low power or in a covered skillet over low heat to keep the eggs from turning rubbery.",
    ],
    heroImage: hero("turkey-sausage-spinach-feta-egg-white-scramble"),
    thumbImage: thumb("turkey-sausage-spinach-feta-egg-white-scramble"),
    imageAlt: "Skillet of turkey sausage, spinach, and feta egg white scramble",
    publishedAt: now,
    updatedAt: now,
    readMinutes: 5,
    seoTitle: "Turkey Sausage Spinach Feta Egg White Scramble | Firehall Breakfast",
  },
];
