import type { BreakfastRecipePageDraft } from "./new-breakfast-pages.js";

const now = new Date().toISOString();
const hero = (slug: string) => `/images/breakfast/${slug}.jpg`;
const thumb = (slug: string) => `/images/thumbs/breakfast/${slug}.jpg`;

export const BATCH_25_BREAKFAST_PAGES: BreakfastRecipePageDraft[] = [
  {
    slug: "huevos-rancheros-crew",
    title: "Huevos Rancheros for the Crew",
    subtitle: "Crisp tortillas, ranchero sauce, and sunny eggs for a full hall.",
    description:
      "Adapted from classic Mexican ranch-style breakfast tradition for firehall service: corn tortillas fried crisp, topped with warm ranchero sauce, black beans, and eggs cooked to order. Built to feed eight hungry firefighters with a make-ahead sauce and a hot griddle line.",
    filters: ["feed_a_crew", "high_protein", "skillets"],
    tags: ["huevos-rancheros", "eggs", "tortillas", "ranchero", "beans"],
    crewSize: 8,
    baseServings: 8,
    prepTime: 20,
    cookTime: 30,
    totalTime: 50,
    difficulty: "medium",
    ingredients: [
      { group: "Sauce", quantity: "2 cans", name: "fire-roasted diced tomatoes", notes: "28 oz each, with juices" },
      { group: "Sauce", quantity: "1", name: "white onion", notes: "diced fine" },
      { group: "Sauce", quantity: "4", name: "garlic cloves", notes: "minced" },
      { group: "Sauce", quantity: "2", name: "chipotle peppers in adobo", notes: "minced, plus 1 tbsp adobo sauce" },
      { group: "Base", quantity: "16", name: "corn tortillas", notes: "6-inch, fresh" },
      { group: "Base", quantity: "2 cans", name: "black beans", notes: "15 oz, drained and warmed with cumin" },
      { group: "Protein", quantity: "16", name: "large eggs" },
      { group: "Finish", quantity: "2 cups", name: "queso fresco", notes: "crumbled, plus cilantro and lime wedges" },
    ],
    steps: [
      { stepNumber: 1, title: "Simmer ranchero sauce", minutes: 20, instruction: "Sauté onion in oil over medium heat until soft, about 6 minutes. Add garlic and chipotle, cook 1 minute, then add tomatoes and adobo sauce. Simmer uncovered, stirring occasionally, until thickened enough to coat a spoon." },
      { stepNumber: 2, title: "Warm beans and prep line", minutes: 8, instruction: "Heat black beans with a pinch of cumin and salt in a covered pot over low heat. Set up a griddle station with warm tortillas, sauce, beans, cheese, and cilantro so eggs can go straight to plates." },
      { stepNumber: 3, title: "Crisp the tortillas", minutes: 10, instruction: "Heat a lightly oiled griddle or cast iron over medium-high until shimmering. Fry tortillas 30–45 seconds per side until crisp at the edges but still pliable in the center. Hold stacked and covered with a towel." },
      { stepNumber: 4, title: "Fry eggs to order", minutes: 12, instruction: "Fry eggs in a thin film of oil over medium heat until whites are fully set (165°F) and yolks are runny or jammy. Season each egg with salt and pepper as it comes off the griddle." },
      { stepNumber: 5, title: "Plate and serve", minutes: 5, instruction: "Layer two tortillas per plate with beans and a generous ladle of ranchero sauce. Top each stack with two fried eggs, crumbled queso fresco, cilantro, and a lime wedge. Serve immediately while tortillas stay crisp." },
    ],
    stationWorkflow: [
      "Simmer ranchero sauce first—it holds warm on the back burner while the griddle handles tortillas and eggs.",
      "Assign one cook to tortilla frying and another to eggs so nothing sits under a heat lamp getting rubbery.",
      "Plate in batches of four; hold finished plates covered for no more than 3 minutes before the line clears.",
    ],
    cleanupNotes: [
      "Deglaze the sauce pot with hot water while still warm so tomato sugars do not cement to the bottom.",
      "Wipe the griddle with a bench scraper and oil paper towels between egg batches to prevent burnt bits.",
    ],
    leftovers: [
      "Ranchero sauce reheats well covered on the stove; add a splash of water and fresh cilantro at service.",
      "Chop leftover tortillas and eggs into a chilaquiles-style skillet bake with extra sauce for the next shift.",
    ],
    heroImage: hero("huevos-rancheros-crew"),
    thumbImage: thumb("huevos-rancheros-crew"),
    imageAlt: "Huevos rancheros with fried eggs, ranchero sauce, and crisp corn tortillas for the crew",
    publishedAt: now,
    updatedAt: now,
    readMinutes: 8,
    seoTitle: "Huevos Rancheros for the Crew | Firehall Breakfast",
  },
  {
    slug: "eggs-benedict-hall-style",
    title: "Eggs Benedict Hall Style",
    subtitle: "Poached eggs, Canadian bacon, and hollandaise on toasted English muffins.",
    description:
      "Adapted from classic New York brunch tradition for a firehall breakfast line: split English muffins toasted crisp, topped with warmed Canadian bacon, poached eggs, and a stable blender hollandaise. Portions cleanly for eight with a two-pan poaching setup.",
    filters: ["feed_a_crew", "high_protein", "breakfast_sandwiches"],
    tags: ["eggs-benedict", "hollandaise", "poached-eggs", "canadian-bacon", "brunch"],
    crewSize: 8,
    baseServings: 8,
    prepTime: 25,
    cookTime: 25,
    totalTime: 50,
    difficulty: "hard",
    ingredients: [
      { group: "Hollandaise", quantity: "8", name: "large egg yolks" },
      { group: "Hollandaise", quantity: "1 lb", name: "unsalted butter", notes: "melted and hot" },
      { group: "Hollandaise", quantity: "3 tbsp", name: "lemon juice", notes: "fresh, plus zest" },
      { group: "Hollandaise", quantity: "1 tsp", name: "Dijon mustard", notes: "helps emulsify" },
      { group: "Build", quantity: "8", name: "English muffins", notes: "split and toasted" },
      { group: "Build", quantity: "16", name: "Canadian bacon slices", notes: "warmed in a dry skillet" },
      { group: "Protein", quantity: "8", name: "large eggs", notes: "very fresh for poaching" },
      { group: "Finish", quantity: "2 tbsp", name: "white vinegar", notes: "for poaching water, plus chives" },
    ],
    steps: [
      { stepNumber: 1, title: "Make hollandaise", minutes: 10, instruction: "Blend yolks, lemon juice, mustard, and a pinch of salt 30 seconds. With blender running on medium, slowly stream in hot melted butter until thick and glossy. Hold in a thermos or over a warm water bath—not direct heat." },
      { stepNumber: 2, title: "Toast muffins and warm bacon", tempF: 350, minutes: 8, instruction: "Split and toast English muffins at 350°F until edges are crisp, about 6 minutes. Warm Canadian bacon in a dry skillet over medium until lightly browned at the edges; hold covered on a warm tray." },
      { stepNumber: 3, title: "Set poaching water", minutes: 5, instruction: "Bring two wide pots of water to a gentle simmer with a tablespoon of vinegar each—the surface should barely ripple, not roll. Crack each egg into a small cup before sliding into the water." },
      { stepNumber: 4, title: "Poach the eggs", minutes: 10, instruction: "Slide eggs into simmering water one at a time. Poach 3–4 minutes until whites are fully set (165°F) and yolks remain runny. Lift with a slotted spoon, drain on paper towels, and trim ragged edges for clean plates." },
      { stepNumber: 5, title: "Assemble and sauce", minutes: 5, instruction: "Place two muffin halves per plate, top each with bacon and a poached egg. Spoon hollandaise generously over each egg, finish with chives and lemon zest, and serve within 2 minutes while yolks are still liquid." },
    ],
    stationWorkflow: [
      "Make hollandaise first and hold warm—never reheat over direct flame or it will break.",
      "Run two poaching pots in parallel so eight eggs finish within the same 4-minute window.",
      "Toast muffins in batches right before poaching starts; cold muffins kill the dish on the plate.",
    ],
    cleanupNotes: [
      "Rinse poaching pots immediately with cold water so egg whites do not cook onto the sides.",
      "Wash blender and whisk while hollandaise is still warm—set butter is miserable to scrub cold.",
    ],
    leftovers: [
      "Hollandaise does not reheat well; make a half batch if crew size is uncertain.",
      "Use leftover Canadian bacon and muffins in a breakfast sandwich bake with scrambled eggs.",
    ],
    heroImage: hero("eggs-benedict-hall-style"),
    thumbImage: thumb("eggs-benedict-hall-style"),
    imageAlt: "Eggs Benedict with poached eggs, Canadian bacon, and hollandaise on English muffins",
    publishedAt: now,
    updatedAt: now,
    readMinutes: 9,
    seoTitle: "Eggs Benedict Hall Style | Firehall Breakfast",
  },
  {
    slug: "corned-beef-hash-breakfast",
    title: "Corned Beef Hash Breakfast",
    subtitle: "Crisp diced potatoes and corned beef with eggs cracked on top.",
    description:
      "Adapted from classic American diner hash tradition for a hungry firehall crew: Yukon gold potatoes diced and pan-fried until deeply golden, folded with shredded corned beef and onions, then finished with eggs cooked sunny-side up in the same skillet.",
    filters: ["skillets", "high_protein", "feed_a_crew"],
    tags: ["corned-beef", "hash", "potatoes", "eggs", "diner"],
    crewSize: 8,
    baseServings: 8,
    prepTime: 15,
    cookTime: 35,
    totalTime: 50,
    difficulty: "medium",
    ingredients: [
      { group: "Hash", quantity: "4 lb", name: "Yukon gold potatoes", notes: "peeled and diced 1/2-inch" },
      { group: "Hash", quantity: "2 lb", name: "cooked corned beef", notes: "shredded or diced small" },
      { group: "Hash", quantity: "2", name: "yellow onions", notes: "diced" },
      { group: "Hash", quantity: "1", name: "green bell pepper", notes: "diced, optional" },
      { group: "Seasoning", quantity: "2 tsp", name: "black pepper", notes: "plus salt to taste—corned beef is salty" },
      { group: "Fat", quantity: "1/4 cup", name: "vegetable oil", notes: "plus butter for finishing" },
      { group: "Protein", quantity: "8", name: "large eggs" },
      { group: "Finish", quantity: "1/2 cup", name: "fresh parsley", notes: "chopped, plus hot sauce at the line" },
    ],
    steps: [
      { stepNumber: 1, title: "Par-cook potatoes", minutes: 10, instruction: "Microwave diced potatoes with a splash of water in a covered bowl until just tender, about 8 minutes. Drain thoroughly and spread on a towel to dry—wet potatoes will steam instead of crisp." },
      { stepNumber: 2, title: "Crisp the hash base", minutes: 15, instruction: "Heat oil in two large skillets over medium-high until shimmering. Add potatoes in a single layer without crowding; let sit 4 minutes for crust before stirring. Cook until deeply golden on most sides." },
      { stepNumber: 3, title: "Add corned beef and onion", minutes: 8, instruction: "Fold in onion, pepper, and corned beef. Press the mixture into the pan and cook undisturbed 3 minutes to build a crust. Season with pepper; taste before adding salt because corned beef carries plenty." },
      { stepNumber: 4, title: "Make wells for eggs", minutes: 3, instruction: "Divide hash between warm serving skillets or one large cast iron. Make eight shallow wells and crack an egg into each. Season eggs with pepper." },
      { stepNumber: 5, title: "Cover and finish eggs", minutes: 6, instruction: "Cover skillets over medium-low heat until egg whites are fully set (165°F) and yolks are runny or jammy to preference. Scatter parsley and serve straight from the pan with hot sauce." },
    ],
    stationWorkflow: [
      "Dry potatoes aggressively—this is the difference between diner hash and cafeteria mush.",
      "Use two skillets in parallel if one pan cannot fit eight eggs without crowding.",
      "Serve family-style from cast iron so the crew gets the crisp bottom layer first.",
    ],
    cleanupNotes: [
      "Deglaze hash pans with hot water while warm; corned beef fat sets hard if left to cool.",
      "Scrape potato starch from cutting boards immediately before it dries and glues itself on.",
    ],
    leftovers: [
      "Reheat hash covered at 325°F for 12 minutes; fry fresh eggs to order on top rather than reheating set yolks.",
      "Press cold leftovers into patties and griddle until crisp for handheld hash cakes at the next breakfast.",
    ],
    heroImage: hero("corned-beef-hash-breakfast"),
    thumbImage: thumb("corned-beef-hash-breakfast"),
    imageAlt: "Corned beef hash with crispy potatoes and sunny-side eggs in a cast-iron skillet",
    publishedAt: now,
    updatedAt: now,
    readMinutes: 8,
    seoTitle: "Corned Beef Hash Breakfast | Firehall Breakfast",
  },
  {
    slug: "chicken-and-waffles-crew",
    title: "Chicken and Waffles for the Crew",
    subtitle: "Crispy buttermilk fried chicken on Belgian waffles with maple butter.",
    description:
      "Adapted from classic Southern soul-food tradition for firehall brunch: buttermilk-brined chicken thighs fried until shatter-crisp, served on warm Belgian waffles with whipped maple butter and a drizzle of hot honey at the line.",
    filters: ["feed_a_crew", "high_protein", "bbq_breakfast"],
    tags: ["chicken-and-waffles", "fried-chicken", "waffles", "southern", "brunch"],
    crewSize: 8,
    baseServings: 8,
    prepTime: 30,
    cookTime: 40,
    totalTime: 70,
    difficulty: "hard",
    ingredients: [
      { group: "Chicken", quantity: "4 lb", name: "bone-in chicken thighs", notes: "skin-on, patted dry" },
      { group: "Chicken", quantity: "2 cups", name: "buttermilk", notes: "for brine, plus 1 cup for dredge" },
      { group: "Chicken", quantity: "2 cups", name: "all-purpose flour", notes: "seasoned with salt, pepper, paprika, garlic powder" },
      { group: "Waffles", quantity: "4 cups", name: "Belgian waffle mix", notes: "prepared per package for 8 waffles" },
      { group: "Waffles", quantity: "2 cups", name: "whole milk", notes: "for batter" },
      { group: "Fry", quantity: "2 qt", name: "peanut or vegetable oil", notes: "for shallow frying" },
      { group: "Finish", quantity: "1/2 cup", name: "unsalted butter", notes: "whipped with 1/4 cup maple syrup" },
      { group: "Finish", quantity: "1/4 cup", name: "hot honey", notes: "or honey plus cayenne" },
    ],
    steps: [
      { stepNumber: 1, title: "Brine the chicken", minutes: 20, instruction: "Soak chicken thighs in buttermilk with a tablespoon of salt for at least 30 minutes (or overnight). Remove from fridge 20 minutes before frying so pieces cook evenly." },
      { stepNumber: 2, title: "Mix waffle batter", minutes: 10, instruction: "Prepare Belgian waffle batter per package directions using milk and melted butter. Rest batter 10 minutes while oil heats so starch hydrates and waffles stay crisp outside." },
      { stepNumber: 3, title: "Fry the chicken", tempF: 350, minutes: 20, instruction: "Heat oil in a heavy Dutch oven to 350°F on a thermometer. Dredge chicken in seasoned flour, shake off excess, and fry in batches 12–14 minutes until golden and internal temperature reaches 165°F. Drain on a wire rack." },
      { stepNumber: 4, title: "Bake waffles", tempF: 375, minutes: 15, instruction: "Cook waffles on a Belgian iron until deep golden, then hold crisp on a rack in a 200°F oven. Do not stack or steam will soften the crust." },
      { stepNumber: 5, title: "Plate and serve", minutes: 5, instruction: "Place one waffle per plate, top with two fried chicken thighs, a knob of maple butter, and a drizzle of hot honey. Serve immediately while chicken skin audibly crunches." },
    ],
    stationWorkflow: [
      "Fry chicken in batches while waffles bake—coordinate so both hit the line within 5 minutes.",
      "Hold fried chicken on a wire rack in a 200°F oven, never on paper towels which trap steam.",
      "Whip maple butter ahead and keep hot honey in squeeze bottles for fast finishing at the line.",
    ],
    cleanupNotes: [
      "Strain fry oil through a fine mesh once cooled; discard if flour bits are heavily browned.",
      "Wipe waffle iron plates while still warm with a damp cloth—dried batter is stubborn once set.",
    ],
    leftovers: [
      "Reheat chicken on a rack at 375°F for 10 minutes to restore crunch; toast waffles separately.",
      "Dice leftover chicken into waffle sandwich sliders with pickles and hot sauce for a quick lunch.",
    ],
    heroImage: hero("chicken-and-waffles-crew"),
    thumbImage: thumb("chicken-and-waffles-crew"),
    imageAlt: "Crispy fried chicken on Belgian waffles with maple butter for the crew",
    publishedAt: now,
    updatedAt: now,
    readMinutes: 10,
    seoTitle: "Chicken and Waffles for the Crew | Firehall Breakfast",
  },
  {
    slug: "chilaquiles-verde-bake",
    title: "Chilaquiles Verde Bake",
    subtitle: "Tortilla chips baked in green salsa with eggs, crema, and cotija.",
    description:
      "Adapted from classic Mexican chilaquiles verde tradition for a hotel-pan breakfast bake: sturdy tortilla chips tossed in simmered tomatillo salsa, baked until edges crisp, then topped with baked eggs and crema for ten portions.",
    filters: ["feed_a_crew", "high_protein", "skillets"],
    tags: ["chilaquiles", "verde", "tomatillo", "eggs", "bake"],
    crewSize: 10,
    baseServings: 10,
    prepTime: 20,
    cookTime: 30,
    totalTime: 50,
    difficulty: "medium",
    ingredients: [
      { group: "Salsa", quantity: "2 lb", name: "tomatillos", notes: "husked and rinsed" },
      { group: "Salsa", quantity: "1", name: "white onion", notes: "quartered" },
      { group: "Salsa", quantity: "4", name: "jalapeños", notes: "stemmed, seeds optional" },
      { group: "Salsa", quantity: "1 cup", name: "chicken broth", notes: "low-sodium" },
      { group: "Build", quantity: "16 cups", name: "thick tortilla chips", notes: "restaurant-style, not thin" },
      { group: "Protein", quantity: "10", name: "large eggs" },
      { group: "Finish", quantity: "1 cup", name: "Mexican crema", notes: "or thinned sour cream" },
      { group: "Finish", quantity: "1 cup", name: "cotija cheese", notes: "crumbled, plus cilantro and radish slices" },
    ],
    steps: [
      { stepNumber: 1, title: "Roast and blend salsa", tempF: 425, minutes: 15, instruction: "Roast tomatillos, onion, and jalapeños on a sheet pan at 425°F until charred in spots, about 12 minutes. Blend with broth until smooth, then simmer in a pot 10 minutes until slightly thickened." },
      { stepNumber: 2, title: "Heat the oven", tempF: 375, minutes: 0, instruction: "Heat oven to 375°F. Grease a deep hotel pan or two 9x13 dishes. Warm salsa off heat—you want it hot but not boiling when it hits the chips." },
      { stepNumber: 3, title: "Toss chips with salsa", minutes: 5, instruction: "Toss chips with just enough warm salsa to coat—about two-thirds of the batch. Reserve remaining salsa for serving. Chips should look sauced but not swimming or they will turn to mush." },
      { stepNumber: 4, title: "Bake and add eggs", tempF: 375, minutes: 15, instruction: "Spread chips in the pan and bake 8 minutes. Make ten wells, crack an egg into each, and bake 10–12 more minutes until whites are set (165°F) and yolks are jammy." },
      { stepNumber: 5, title: "Finish and portion", minutes: 5, instruction: "Drizzle crema in zigzags, scatter cotija and cilantro, and serve with reserved warm salsa and lime wedges. Portion with a wide spatula to keep layers intact." },
    ],
    stationWorkflow: [
      "Use thick chips only—thin restaurant chips dissolve before eggs finish baking.",
      "Hold extra salsa warm for crew members who want a saucier plate at the line.",
      "Cut radishes and cilantro while the first bake runs so garnish is ready at the oven door.",
    ],
    cleanupNotes: [
      "Soak the hotel pan immediately with hot water—baked salsa and cheese glue sets fast.",
      "Rinse the blender with warm water before tomatillo skins dry inside the jar.",
    ],
    leftovers: [
      "Chilaquiles soften overnight; re-crisp on a sheet pan at 375°F for 8 minutes before reheating.",
      "Fold leftovers into breakfast burritos with scrambled eggs and extra hot salsa.",
    ],
    heroImage: hero("chilaquiles-verde-bake"),
    thumbImage: thumb("chilaquiles-verde-bake"),
    imageAlt: "Baked chilaquiles verde with eggs, crema, and cotija in a hotel pan",
    publishedAt: now,
    updatedAt: now,
    readMinutes: 8,
    seoTitle: "Chilaquiles Verde Bake | Firehall Breakfast",
  },
  {
    slug: "shrimp-and-grits-breakfast",
    title: "Shrimp and Grits Breakfast",
    subtitle: "Creamy stone-ground grits topped with Cajun-spiced shrimp and andouille.",
    description:
      "Adapted from classic Lowcountry Carolina breakfast tradition for firehall service: slow-stirred stone-ground grits with sharp cheddar, topped with sautéed shrimp, andouille, and a pan sauce bright with lemon and scallions.",
    filters: ["feed_a_crew", "high_protein", "skillets"],
    tags: ["shrimp-and-grits", "grits", "seafood", "cajun", "southern"],
    crewSize: 8,
    baseServings: 8,
    prepTime: 15,
    cookTime: 35,
    totalTime: 50,
    difficulty: "medium",
    ingredients: [
      { group: "Grits", quantity: "2 cups", name: "stone-ground grits", notes: "not instant" },
      { group: "Grits", quantity: "8 cups", name: "whole milk", notes: "plus 2 cups water" },
      { group: "Grits", quantity: "2 cups", name: "sharp cheddar", notes: "shredded" },
      { group: "Grits", quantity: "4 tbsp", name: "unsalted butter", notes: "for finishing grits" },
      { group: "Shrimp", quantity: "2 lb", name: "large shrimp", notes: "peeled and deveined" },
      { group: "Shrimp", quantity: "8 oz", name: "andouille sausage", notes: "sliced into coins" },
      { group: "Seasoning", quantity: "2 tbsp", name: "Cajun seasoning", notes: "plus salt and pepper" },
      { group: "Finish", quantity: "1/2 cup", name: "scallions", notes: "sliced, plus lemon wedges" },
    ],
    steps: [
      { stepNumber: 1, title: "Cook the grits", minutes: 25, instruction: "Bring milk and water to a gentle boil in a heavy pot. Whisk in grits, reduce to low, and cook 20–25 minutes stirring often until thick and creamy. Fold in cheddar, butter, salt, and pepper; hold covered on low." },
      { stepNumber: 2, title: "Brown the andouille", minutes: 6, instruction: "Sauté andouille coins in a large skillet over medium-high until edges crisp and fat renders, about 5 minutes. Transfer to a warm plate, leaving fat in the pan." },
      { stepNumber: 3, title: "Sear the shrimp", minutes: 8, instruction: "Pat shrimp dry, toss with Cajun seasoning, and sear in the andouille fat over high heat in a single layer. Cook 2 minutes per side until pink and internal temperature reaches 145°F. Do not overcrowd." },
      { stepNumber: 4, title: "Build the pan sauce", minutes: 4, instruction: "Return andouille to the pan with shrimp. Add a splash of water or stock, scrape browned bits, and finish with lemon juice and half the scallions. Taste and adjust salt." },
      { stepNumber: 5, title: "Plate and serve", minutes: 5, instruction: "Spoon creamy grits into warm bowls, top with shrimp-andouille mixture, and garnish with remaining scallions and lemon wedges. Serve immediately while grits stay loose." },
    ],
    stationWorkflow: [
      "Start grits first—they need constant stirring and cannot wait for shrimp to finish.",
      "Pat shrimp completely dry before seasoning or they steam instead of sear.",
      "Hold grits in a bain-marie on low with a splash of milk stirred in every 10 minutes.",
    ],
    cleanupNotes: [
      "Fill the grits pot with hot water immediately—starch sets like concrete once cooled.",
      "Rinse shrimp shells and prep surfaces with sanitizer before handling other ingredients.",
    ],
    leftovers: [
      "Grits tighten when chilled; reheat with milk whisked in over low heat until creamy again.",
      "Chop leftover shrimp into a breakfast taco filling with hot sauce and scrambled eggs.",
    ],
    heroImage: hero("shrimp-and-grits-breakfast"),
    thumbImage: thumb("shrimp-and-grits-breakfast"),
    imageAlt: "Creamy grits topped with Cajun shrimp and andouille for the crew",
    publishedAt: now,
    updatedAt: now,
    readMinutes: 8,
    seoTitle: "Shrimp and Grits Breakfast | Firehall Breakfast",
  },
  {
    slug: "country-fried-steak-eggs",
    title: "Country Fried Steak and Eggs Breakfast",
    subtitle: "Pounded cube steak, pepper gravy, and eggs over mashed potatoes.",
    description:
      "Adapted from classic Texas diner chicken-fried steak tradition for a firehall plate breakfast: cube steak pounded thin, breaded and fried crisp, smothered in black pepper gravy and served with eggs and buttery mashed potatoes.",
    filters: ["feed_a_crew", "high_protein", "skillets"],
    tags: ["country-fried-steak", "gravy", "eggs", "diner", "steak"],
    crewSize: 8,
    baseServings: 8,
    prepTime: 25,
    cookTime: 30,
    totalTime: 55,
    difficulty: "medium",
    ingredients: [
      { group: "Steak", quantity: "3 lb", name: "cube steak", notes: "pounded 1/4-inch thin" },
      { group: "Steak", quantity: "2 cups", name: "all-purpose flour", notes: "seasoned with salt, pepper, garlic powder" },
      { group: "Steak", quantity: "2 cups", name: "buttermilk", notes: "for dredge" },
      { group: "Gravy", quantity: "1/4 cup", name: "pan drippings", notes: "plus 1/4 cup flour for roux" },
      { group: "Gravy", quantity: "4 cups", name: "whole milk", notes: "warm" },
      { group: "Gravy", quantity: "2 tsp", name: "coarse black pepper", notes: "freshly cracked" },
      { group: "Sides", quantity: "5 lb", name: "Yukon gold potatoes", notes: "peeled, boiled, and mashed with butter" },
      { group: "Protein", quantity: "8", name: "large eggs", notes: "fried sunny-side up" },
    ],
    steps: [
      { stepNumber: 1, title: "Prep and bread steaks", minutes: 15, instruction: "Season cube steaks with salt and pepper. Dredge in seasoned flour, dip in buttermilk, then coat again in flour pressing firmly so breading adheres. Rest breaded steaks on a rack 10 minutes so coating sets." },
      { stepNumber: 2, title: "Fry the steaks", tempF: 350, minutes: 12, instruction: "Heat 1/2 inch oil in a large skillet to 350°F. Fry steaks in batches 3–4 minutes per side until deeply golden and internal temperature reaches 145°F for medium. Hold on a rack in a 200°F oven." },
      { stepNumber: 3, title: "Make pepper gravy", minutes: 8, instruction: "Pour off all but 1/4 cup drippings. Whisk in flour over medium heat 2 minutes until blonde. Slowly whisk in warm milk, simmer until thick enough to coat a spoon, and finish with cracked black pepper." },
      { stepNumber: 4, title: "Mash potatoes and fry eggs", minutes: 10, instruction: "Boil potatoes until fork-tender, drain, and mash with butter, salt, and warm milk until smooth. Fry eggs in a clean skillet over medium heat until whites are set (165°F) and yolks are runny." },
      { stepNumber: 5, title: "Plate and serve", minutes: 5, instruction: "Mound mashed potatoes on each plate, top with a fried steak, ladle pepper gravy generously over the top, and crown with a sunny-side egg. Serve immediately while breading stays crisp." },
    ],
    stationWorkflow: [
      "Bread all steaks before frying starts so the line does not stall between batches.",
      "Keep mashed potatoes in a covered hotel pan on low with a splash of cream stirred in.",
      "Fry eggs in a separate pan while gravy simmers—never cook eggs in gravy grease.",
    ],
    cleanupNotes: [
      "Strain fry oil once cooled and wipe splatter from stovetop before it caramelizes.",
      "Deglaze the gravy pan with hot water while warm to lift flour roux from corners.",
    ],
    leftovers: [
      "Reheat steaks on a rack at 375°F for 8 minutes; add fresh gravy rather than microwaving breading.",
      "Chop leftover steak into a breakfast burrito with gravy, potatoes, and hot sauce.",
    ],
    heroImage: hero("country-fried-steak-eggs"),
    thumbImage: thumb("country-fried-steak-eggs"),
    imageAlt: "Country fried steak with pepper gravy, mashed potatoes, and a fried egg",
    publishedAt: now,
    updatedAt: now,
    readMinutes: 9,
    seoTitle: "Country Fried Steak and Eggs | Firehall Breakfast",
  },
  {
    slug: "green-chile-breakfast-burritos",
    title: "Green Chile Breakfast Burritos",
    subtitle: "Flour tortillas stuffed with eggs, potatoes, bacon, and Hatch chile sauce.",
    description:
      "Adapted from classic New Mexico breakfast burrito tradition for firehall handheld service: scrambled eggs, crispy potatoes, bacon, and melted cheese rolled in warm flour tortillas and smothered with roasted green chile sauce.",
    filters: ["feed_a_crew", "high_protein", "breakfast_sandwiches"],
    tags: ["breakfast-burrito", "green-chile", "hatch", "bacon", "handheld"],
    crewSize: 10,
    baseServings: 10,
    prepTime: 25,
    cookTime: 25,
    totalTime: 50,
    difficulty: "medium",
    ingredients: [
      { group: "Filling", quantity: "18", name: "large eggs", notes: "soft-scrambled" },
      { group: "Filling", quantity: "2 lb", name: "bacon", notes: "cooked crisp and crumbled" },
      { group: "Filling", quantity: "4 cups", name: "diced breakfast potatoes", notes: "crisped on the griddle" },
      { group: "Filling", quantity: "3 cups", name: "shredded cheddar", notes: "sharp or medium" },
      { group: "Sauce", quantity: "3 cups", name: "roasted green chile sauce", notes: "Hatch-style, mild or hot" },
      { group: "Build", quantity: "10", name: "large flour tortillas", notes: "12-inch, warmed" },
      { group: "Finish", quantity: "1 cup", name: "sour cream", notes: "for the line" },
      { group: "Finish", quantity: "1/2 cup", name: "cilantro", notes: "chopped, plus lime wedges" },
    ],
    steps: [
      { stepNumber: 1, title: "Crisp potatoes and bacon", minutes: 15, instruction: "Cook bacon in sheet pans at 400°F until crisp, drain, and crumble. Render bacon fat on the griddle and crisp diced potatoes in a single layer until golden on all sides; season with salt and pepper." },
      { stepNumber: 2, title: "Scramble eggs", minutes: 8, instruction: "Soft-scramble eggs in batches over low heat with butter—they should look glossy and barely set. Fold in half the cheese off heat so it melts gently without squeezing out moisture." },
      { stepNumber: 3, title: "Warm tortillas and sauce", minutes: 5, instruction: "Warm green chile sauce in a pot over low heat. Steam or griddle tortillas until pliable so they roll without tearing at the seams." },
      { stepNumber: 4, title: "Roll the burritos", minutes: 10, instruction: "Divide eggs, potatoes, bacon, and cheese across tortillas. Fold sides in, roll tight, and place seam-side down on a sheet pan. Optional: griddle seam-side down 2 minutes to seal." },
      { stepNumber: 5, title: "Serve smothered or wrapped", minutes: 5, instruction: "Serve burritos whole in foil for handheld line service, or split two per plate and ladle warm green chile sauce over the top with sour cream and cilantro. Add lime at the line." },
    ],
    stationWorkflow: [
      "Set up a rolling station with all fillings in hotel pans before scrambling the last batch of eggs.",
      "Warm tortillas in batches of five so they do not dry out on a hot holding surface.",
      "Keep green chile sauce on low with a ladle ready—smothered burritos need sauce at serving temp.",
    ],
    cleanupNotes: [
      "Wipe bacon grease from sheet pans while still warm with paper towels before washing.",
      "Soak griddle scrapers immediately after potato service—starch burns on fast.",
    ],
    leftovers: [
      "Wrap burritos individually in foil and reheat at 325°F for 15 minutes; open foil last 5 minutes to crisp.",
      "Chop leftover burritos into a chilaquiles bake with extra green chile sauce and cheese.",
    ],
    heroImage: hero("green-chile-breakfast-burritos"),
    thumbImage: thumb("green-chile-breakfast-burritos"),
    imageAlt: "Green chile breakfast burritos with eggs, bacon, and potatoes for the crew",
    publishedAt: now,
    updatedAt: now,
    readMinutes: 8,
    seoTitle: "Green Chile Breakfast Burritos | Firehall Breakfast",
  },
  {
    slug: "migas-for-the-crew",
    title: "Migas for the Crew",
    subtitle: "Scrambled eggs with crispy tortilla strips, peppers, and queso fresco.",
    description:
      "Adapted from classic Tex-Mex migas tradition for firehall skillet service: corn tortillas cut into strips and fried crisp, folded into soft-scrambled eggs with sautéed peppers, onion, and tomato, finished with queso fresco and salsa.",
    filters: ["skillets", "feed_a_crew", "quick_breakfasts"],
    tags: ["migas", "eggs", "tortillas", "tex-mex", "skillet"],
    crewSize: 8,
    baseServings: 8,
    prepTime: 15,
    cookTime: 20,
    totalTime: 35,
    difficulty: "easy",
    ingredients: [
      { group: "Tortillas", quantity: "12", name: "corn tortillas", notes: "cut into thin strips" },
      { group: "Veg", quantity: "2", name: "poblano peppers", notes: "seeded and diced" },
      { group: "Veg", quantity: "1", name: "white onion", notes: "diced" },
      { group: "Veg", quantity: "2", name: "Roma tomatoes", notes: "diced, seeds drained" },
      { group: "Protein", quantity: "16", name: "large eggs" },
      { group: "Fat", quantity: "1/3 cup", name: "vegetable oil", notes: "for frying strips" },
      { group: "Seasoning", quantity: "1 tsp", name: "ground cumin", notes: "plus salt and pepper" },
      { group: "Finish", quantity: "1 cup", name: "queso fresco", notes: "crumbled, plus salsa and cilantro" },
    ],
    steps: [
      { stepNumber: 1, title: "Fry tortilla strips", minutes: 8, instruction: "Heat oil in a large skillet over medium-high until shimmering. Fry tortilla strips in batches until golden and crisp, about 2 minutes per batch. Drain on paper towels and season lightly with salt." },
      { stepNumber: 2, title: "Sauté peppers and onion", minutes: 6, instruction: "Remove all but 2 tablespoons oil from the pan. Sauté poblano and onion over medium-high until softened and lightly charred at the edges, about 5 minutes. Add tomato and cumin; cook 1 minute." },
      { stepNumber: 3, title: "Scramble eggs into the mix", minutes: 8, instruction: "Beat eggs with salt and pepper. Pour into the skillet over medium-low heat, folding gently with a spatula. When eggs are halfway set, fold in half the tortilla strips so some stay crisp and some soften." },
      { stepNumber: 4, title: "Finish and garnish", minutes: 3, instruction: "Remove from heat while eggs still look glossy. Fold in remaining tortilla strips for crunch. Scatter queso fresco and cilantro over the top." },
      { stepNumber: 5, title: "Serve family-style", minutes: 2, instruction: "Serve straight from the skillet with warm salsa and extra tortilla strips on the side. Do not hold more than 5 minutes or crisp strips will steam soft." },
    ],
    stationWorkflow: [
      "Fry tortilla strips first and hold uncovered—covering traps steam and kills crunch.",
      "Use two skillets if feeding ten so eggs finish in one batch without overcooking.",
      "Prep all veg dice before the first tortilla hits oil so the scramble moves fast.",
    ],
    cleanupNotes: [
      "Strain and save fry oil if clean; wipe skillet while warm to remove stuck tortilla bits.",
      "Sweep tortilla crumbs from prep surfaces before switching to egg service.",
    ],
    leftovers: [
      "Migas do not reheat well; scale the recipe down rather than cooking extra.",
      "Use leftover tortilla strips as crunchy topping for soup or salad at lunch.",
    ],
    heroImage: hero("migas-for-the-crew"),
    thumbImage: thumb("migas-for-the-crew"),
    imageAlt: "Migas skillet with scrambled eggs, crispy tortilla strips, and queso fresco",
    publishedAt: now,
    updatedAt: now,
    readMinutes: 7,
    seoTitle: "Migas for the Crew | Firehall Breakfast",
  },
  {
    slug: "breakfast-fried-rice-crew",
    title: "Breakfast Fried Rice for the Crew",
    subtitle: "Day-old rice wok-fried with bacon, eggs, peas, and scallions.",
    description:
      "Adapted from classic Chinese-American breakfast fried rice tradition for firehall wok service: chilled long-grain rice stir-fried over high heat with bacon, scrambled eggs, peas, carrots, and soy-sesame seasoning.",
    filters: ["feed_a_crew", "quick_breakfasts", "high_protein"],
    tags: ["fried-rice", "bacon", "eggs", "wok", "asian"],
    crewSize: 8,
    baseServings: 8,
    prepTime: 15,
    cookTime: 20,
    totalTime: 35,
    difficulty: "medium",
    ingredients: [
      { group: "Rice", quantity: "6 cups", name: "cooked long-grain rice", notes: "day-old, chilled and broken up" },
      { group: "Protein", quantity: "1 lb", name: "bacon", notes: "diced, cooked until crisp" },
      { group: "Protein", quantity: "8", name: "large eggs", notes: "beaten" },
      { group: "Veg", quantity: "1 cup", name: "frozen peas", notes: "thawed" },
      { group: "Veg", quantity: "1 cup", name: "diced carrots", notes: "small dice" },
      { group: "Veg", quantity: "6", name: "scallions", notes: "sliced, whites and greens separated" },
      { group: "Seasoning", quantity: "3 tbsp", name: "soy sauce", notes: "low-sodium" },
      { group: "Seasoning", quantity: "1 tbsp", name: "toasted sesame oil", notes: "plus neutral oil for wok" },
    ],
    steps: [
      { stepNumber: 1, title: "Prep all components", minutes: 10, instruction: "Break chilled rice into loose grains with wet hands. Cook diced bacon until crisp, drain, and reserve 2 tablespoons fat. Beat eggs with a pinch of salt. Keep peas, carrots, and scallions in separate bowls." },
      { stepNumber: 2, title: "Scramble eggs in the wok", minutes: 4, instruction: "Heat wok or large skillet over high until smoking lightly. Add a tablespoon of oil, pour in eggs, and scramble quickly into soft curds. Remove to a plate immediately while still tender." },
      { stepNumber: 3, title: "Stir-fry vegetables", minutes: 5, instruction: "Add bacon fat to the wok. Stir-fry carrots and scallion whites 2 minutes, then add peas and rice. Press rice against the hot surface in sections to toast grains without mashing." },
      { stepNumber: 4, title: "Season and combine", minutes: 5, instruction: "Drizzle soy sauce around the rim of the wok so it sizzles and caramelizes. Toss rice until evenly golden. Fold in bacon, scrambled eggs, and scallion greens off heat." },
      { stepNumber: 5, title: "Toss with sesame oil and portion", minutes: 3, instruction: "Drizzle sesame oil over the top and toss once. Taste for salt and transfer to a warm hotel pan for the line with chili crisp or hot sauce alongside." },
    ],
    stationWorkflow: [
      "Use day-old rice only—fresh rice steams and clumps in the wok.",
      "Cook in two wok batches if needed so rice toasts instead of steaming.",
      "Scramble eggs separately so they stay fluffy rather than disappearing into the rice.",
    ],
    cleanupNotes: [
      "Wok wash with hot water and a bamboo brush while still warm—do not soak cast iron woks.",
      "Wipe soy sauce spills from the stove immediately; caramelized soy is tough to remove.",
    ],
    leftovers: [
      "Reheat fried rice in a hot wok with a splash of water and soy—not the microwave.",
      "Wrap leftovers in omelette-style sheets for a quick egg roll breakfast variation.",
    ],
    heroImage: hero("breakfast-fried-rice-crew"),
    thumbImage: thumb("breakfast-fried-rice-crew"),
    imageAlt: "Breakfast fried rice with bacon, eggs, peas, and scallions in a wok",
    publishedAt: now,
    updatedAt: now,
    readMinutes: 7,
    seoTitle: "Breakfast Fried Rice for the Crew | Firehall Breakfast",
  },
  {
    slug: "belgian-waffle-platter",
    title: "Belgian Waffle Platter",
    subtitle: "Crisp yeasted waffles with whipped butter, syrup, and fresh berries.",
    description:
      "Adapted from classic Belgian Liège-style brunch tradition for firehall batch service: yeasted waffle batter baked crisp on a Belgian iron, served on a platter with whipped butter, warm maple syrup, and seasonal berries for eight.",
    filters: ["feed_a_crew", "quick_breakfasts", "breakfast_sandwiches"],
    tags: ["waffles", "belgian", "brunch", "berries", "maple"],
    crewSize: 8,
    baseServings: 8,
    prepTime: 20,
    cookTime: 30,
    totalTime: 50,
    difficulty: "medium",
    ingredients: [
      { group: "Batter", quantity: "4 cups", name: "all-purpose flour" },
      { group: "Batter", quantity: "2 tbsp", name: "granulated sugar" },
      { group: "Batter", quantity: "2 tsp", name: "instant yeast", notes: "or 1 packet active dry" },
      { group: "Batter", quantity: "3 cups", name: "whole milk", notes: "warm" },
      { group: "Batter", quantity: "4", name: "large eggs", notes: "separated, yolks in batter, whites whipped" },
      { group: "Batter", quantity: "1/2 cup", name: "unsalted butter", notes: "melted and cooled" },
      { group: "Serve", quantity: "2 cups", name: "maple syrup", notes: "warmed" },
      { group: "Serve", quantity: "3 cups", name: "mixed berries", notes: "plus whipped butter" },
    ],
    steps: [
      { stepNumber: 1, title: "Mix the batter", minutes: 10, instruction: "Whisk flour, sugar, yeast, and salt. Stir in warm milk, egg yolks, and melted butter until smooth. Let rest 15 minutes so yeast activates and batter thickens slightly." },
      { stepNumber: 2, title: "Fold in whipped whites", minutes: 5, instruction: "Beat egg whites to stiff peaks. Fold one-third into the batter to lighten, then fold in the rest gently so volume stays airy—do not deflate with heavy stirring." },
      { stepNumber: 3, title: "Preheat irons", tempF: 375, minutes: 5, instruction: "Heat Belgian waffle irons to medium-high (most units reach roughly 375°F surface temp). Lightly oil plates if your iron requires it. Keep a rack and sheet pan ready in a 200°F oven." },
      { stepNumber: 4, title: "Bake the waffles", minutes: 20, instruction: "Pour batter to cover the grid without overflowing. Close iron and bake 4–5 minutes per waffle until deep golden and crisp at the edges. Transfer to the rack in the warm oven—never stack." },
      { stepNumber: 5, title: "Platter and serve", minutes: 5, instruction: "Arrange waffles on a large warm platter with bowls of whipped butter, warmed maple syrup, and berries. Serve immediately and bake remaining batches while the crew eats." },
    ],
    stationWorkflow: [
      "Run two irons in parallel if available so eight waffles finish within 15 minutes.",
      "Hold waffles on a rack in a 200°F oven—stacking steams away the crisp crust.",
      "Warm syrup in a small pot on low with a ladle at the line for fast self-serve.",
    ],
    cleanupNotes: [
      "Wipe waffle iron plates while warm with a damp cloth—never submerge electric units.",
      "Rinse mixing bowls before batter dries and hardens on the whisk.",
    ],
    leftovers: [
      "Toast leftover waffles at 350°F for 6 minutes directly on the rack to re-crisp.",
      "Use stale waffles as bread in a Monte Cristo-style sandwich bake with ham and cheese.",
    ],
    heroImage: hero("belgian-waffle-platter"),
    thumbImage: thumb("belgian-waffle-platter"),
    imageAlt: "Belgian waffle platter with maple syrup, whipped butter, and fresh berries",
    publishedAt: now,
    updatedAt: now,
    readMinutes: 7,
    seoTitle: "Belgian Waffle Platter | Firehall Breakfast",
  },
  {
    slug: "farmers-breakfast-casserole",
    title: "Farmer's Breakfast Casserole",
    subtitle: "Hash browns, sausage, eggs, and cheese baked in one deep dish.",
    description:
      "Adapted from classic Midwest farm-kitchen breakfast bake tradition for firehall oven service: shredded hash browns layered with browned breakfast sausage, eggs, milk, and cheddar baked until puffed and golden for ten portions.",
    filters: ["feed_a_crew", "high_protein", "skillets"],
    tags: ["casserole", "sausage", "hash-browns", "bake", "eggs"],
    crewSize: 10,
    baseServings: 10,
    prepTime: 20,
    cookTime: 45,
    totalTime: 65,
    difficulty: "easy",
    ingredients: [
      { group: "Base", quantity: "2 lb", name: "frozen hash browns", notes: "thawed and squeezed dry" },
      { group: "Base", quantity: "2 lb", name: "breakfast sausage", notes: "browned and crumbled" },
      { group: "Egg mix", quantity: "12", name: "large eggs" },
      { group: "Egg mix", quantity: "2 cups", name: "whole milk", notes: "or half-and-half" },
      { group: "Egg mix", quantity: "1 tsp", name: "dry mustard", notes: "helps emulsify" },
      { group: "Cheese", quantity: "3 cups", name: "shredded sharp cheddar", notes: "divided" },
      { group: "Seasoning", quantity: "1 tsp", name: "black pepper", notes: "plus salt to taste" },
      { group: "Finish", quantity: "1/2 cup", name: "sliced green onions", notes: "plus hot sauce at the line" },
    ],
    steps: [
      { stepNumber: 1, title: "Heat the oven", tempF: 375, minutes: 0, instruction: "Heat oven to 375°F. Grease a deep 9x13 pan or hotel half-pan. Thaw hash browns completely and squeeze out excess water in a clean towel—wet potatoes make a soggy casserole." },
      { stepNumber: 2, title: "Brown the sausage", minutes: 10, instruction: "Cook breakfast sausage in a skillet over medium-high, breaking into small crumbles until no pink remains and internal temperature reaches 160°F. Drain on paper towels." },
      { stepNumber: 3, title: "Layer the base", minutes: 8, instruction: "Spread hash browns evenly in the pan. Top with sausage and half the cheddar. Whisk eggs, milk, mustard, salt, and pepper until uniform and pour evenly over the layers." },
      { stepNumber: 4, title: "Bake until set", tempF: 375, minutes: 40, instruction: "Cover with foil and bake 25 minutes. Uncover, top with remaining cheddar, and bake 15 more until center reaches 165°F on a thermometer and top is golden." },
      { stepNumber: 5, title: "Rest and portion", minutes: 10, instruction: "Rest casserole 10 minutes before cutting so slices hold clean squares. Garnish with green onions and serve with hot sauce at the line." },
    ],
    stationWorkflow: [
      "Squeeze hash browns dry—this is the single biggest factor in a crisp versus soggy base.",
      "Cover for the first half of baking so top cheese does not over-brown before center sets.",
      "Cut with a sharp bench scraper in the pan for even ten-portion squares.",
    ],
    cleanupNotes: [
      "Soak the 9x13 with hot water while still warm before baked egg residue sets.",
      "Drain sausage grease into a heat-safe container, never down the sink.",
    ],
    leftovers: [
      "Reheat portions covered at 325°F for 12 minutes until steaming in the center.",
      "Cube leftovers into breakfast burrito filling with salsa and extra cheese.",
    ],
    heroImage: hero("farmers-breakfast-casserole"),
    thumbImage: thumb("farmers-breakfast-casserole"),
    imageAlt: "Farmer's breakfast casserole with hash browns, sausage, eggs, and cheddar",
    publishedAt: now,
    updatedAt: now,
    readMinutes: 8,
    seoTitle: "Farmer's Breakfast Casserole | Firehall Breakfast",
  },
  {
    slug: "tater-tot-breakfast-casserole",
    title: "Tater Tot Breakfast Casserole",
    subtitle: "Crispy tater tots baked with eggs, bacon, and melty cheese.",
    description:
      "Adapted from classic Midwest tater tot hotdish tradition for firehall breakfast: frozen tater tots layered with crispy bacon, scrambled eggs, and cheddar baked until the top is shatter-crisp and the center hits 165°F.",
    filters: ["feed_a_crew", "high_protein", "quick_breakfasts"],
    tags: ["tater-tots", "casserole", "bacon", "bake", "midwest"],
    crewSize: 10,
    baseServings: 10,
    prepTime: 15,
    cookTime: 40,
    totalTime: 55,
    difficulty: "easy",
    ingredients: [
      { group: "Base", quantity: "3 lb", name: "frozen tater tots", notes: "straight from freezer" },
      { group: "Protein", quantity: "1 1/2 lb", name: "bacon", notes: "cooked crisp and crumbled" },
      { group: "Egg mix", quantity: "12", name: "large eggs", notes: "lightly beaten" },
      { group: "Egg mix", quantity: "1 1/2 cups", name: "whole milk" },
      { group: "Cheese", quantity: "3 cups", name: "shredded cheddar", notes: "divided" },
      { group: "Seasoning", quantity: "1 tsp", name: "garlic powder", notes: "plus salt and pepper" },
      { group: "Finish", quantity: "1/2 cup", name: "sliced green onions", notes: "plus ranch or hot sauce" },
      { group: "Optional", quantity: "1 cup", name: "diced bell pepper", notes: "sautéed soft, optional layer" },
    ],
    steps: [
      { stepNumber: 1, title: "Heat the oven", tempF: 400, minutes: 0, instruction: "Heat oven to 400°F. Grease a deep 9x13 pan. Cook bacon until crisp, drain, and crumble. Keep bacon fat if sautéing optional peppers." },
      { stepNumber: 2, title: "Layer tots and bacon", minutes: 8, instruction: "Spread half the tater tots in an even layer on the pan bottom. Scatter bacon and half the cheddar over the tots. Add optional sautéed peppers if using." },
      { stepNumber: 3, title: "Add egg mixture", minutes: 5, instruction: "Whisk eggs, milk, garlic powder, salt, and pepper until smooth. Pour evenly over the layered tots and bacon so liquid reaches the bottom." },
      { stepNumber: 4, title: "Top and bake", tempF: 400, minutes: 35, instruction: "Arrange remaining tots on top in a single layer and sprinkle with remaining cheddar. Bake 35–40 minutes until tots are deep golden and center reaches 165°F on a thermometer." },
      { stepNumber: 5, title: "Rest and serve", minutes: 8, instruction: "Rest 8 minutes so the egg custard sets for clean scoops. Garnish with green onions and serve with ranch or hot sauce at the line." },
    ],
    stationWorkflow: [
      "Keep tots frozen until they hit the pan—thawed tots turn mushy in the egg layer.",
      "Use a deep pan so the egg mixture does not overflow during baking.",
      "Check center temp with a probe before pulling—golden tots can hide under-set eggs.",
    ],
    cleanupNotes: [
      "Line the pan with parchment for easier release and faster cleanup after cheese bakes on.",
      "Wipe bacon grease splatter from the oven door while still warm.",
    ],
    leftovers: [
      "Reheat squares on a sheet pan at 375°F for 10 minutes to re-crisp the tot topping.",
      "Crumble leftovers into a breakfast burrito with extra cheese and hot sauce.",
    ],
    heroImage: hero("tater-tot-breakfast-casserole"),
    thumbImage: thumb("tater-tot-breakfast-casserole"),
    imageAlt: "Tater tot breakfast casserole with bacon, eggs, and melted cheddar",
    publishedAt: now,
    updatedAt: now,
    readMinutes: 7,
    seoTitle: "Tater Tot Breakfast Casserole | Firehall Breakfast",
  },
  {
    slug: "smoked-salmon-benedit",
    title: "Smoked Salmon Benedict",
    subtitle: "Poached eggs and hollandaise over smoked salmon and rye toast.",
    description:
      "Adapted from classic Scandinavian-Jewish deli brunch tradition for firehall service: toasted rye bread topped with smoked salmon, capers, poached eggs, and a lighter lemon-dill hollandaise for eight elegant portions.",
    filters: ["feed_a_crew", "high_protein", "breakfast_sandwiches"],
    tags: ["smoked-salmon", "eggs-benedict", "hollandaise", "rye", "brunch"],
    crewSize: 8,
    baseServings: 8,
    prepTime: 25,
    cookTime: 20,
    totalTime: 45,
    difficulty: "hard",
    ingredients: [
      { group: "Hollandaise", quantity: "6", name: "large egg yolks" },
      { group: "Hollandaise", quantity: "3/4 lb", name: "unsalted butter", notes: "melted hot" },
      { group: "Hollandaise", quantity: "2 tbsp", name: "lemon juice", notes: "plus 2 tbsp chopped dill" },
      { group: "Build", quantity: "8 slices", name: "rye bread", notes: "thick-cut, toasted" },
      { group: "Build", quantity: "1 1/2 lb", name: "smoked salmon", notes: "sliced thin" },
      { group: "Build", quantity: "3 tbsp", name: "capers", notes: "drained" },
      { group: "Protein", quantity: "8", name: "large eggs", notes: "poached" },
      { group: "Finish", quantity: "1", name: "red onion", notes: " shaved thin, plus lemon wedges" },
    ],
    steps: [
      { stepNumber: 1, title: "Make dill hollandaise", minutes: 10, instruction: "Blend yolks, lemon juice, and a pinch of salt 30 seconds. With blender running, slowly stream hot melted butter until thick. Stir in dill and hold warm in a thermos—not direct heat." },
      { stepNumber: 2, title: "Toast rye and prep salmon", minutes: 8, instruction: "Toast rye slices until crisp at the edges. Arrange smoked salmon on a cold platter with capers and shaved red onion ready for fast assembly." },
      { stepNumber: 3, title: "Poach the eggs", minutes: 12, instruction: "Simmer two wide pots of water with a splash of vinegar. Slide eggs in gently and poach 3–4 minutes until whites are set (165°F) and yolks remain runny. Drain on towels." },
      { stepNumber: 4, title: "Assemble the base", minutes: 5, instruction: "Place toasted rye on warm plates. Layer salmon generously, scatter capers and a few onion slices over each portion." },
      { stepNumber: 5, title: "Top and sauce", minutes: 3, instruction: "Crown each with a poached egg, spoon dill hollandaise over the top, and finish with extra dill and lemon wedges. Serve within 2 minutes while yolks stay runny." },
    ],
    stationWorkflow: [
      "Keep salmon cold until assembly—warm plates only, not warm fish.",
      "Poach eggs in two pots simultaneously to finish eight within the same window.",
      "Hold hollandaise in a thermos at the line; never reheat over direct flame.",
    ],
    cleanupNotes: [
      "Rinse caper brine from prep surfaces promptly—it stains counters if left to dry.",
      "Wash poaching pots with cold rinse first, then hot soapy water to lift egg whites.",
    ],
    leftovers: [
      "Smoked salmon benedict does not reheat well; cook to actual crew count.",
      "Use leftover salmon and rye in a scrambled egg hash with capers and dill.",
    ],
    heroImage: hero("smoked-salmon-benedit"),
    thumbImage: thumb("smoked-salmon-benedit"),
    imageAlt: "Smoked salmon Benedict with poached eggs and dill hollandaise on rye toast",
    publishedAt: now,
    updatedAt: now,
    readMinutes: 9,
    seoTitle: "Smoked Salmon Benedict | Firehall Breakfast",
  },
  {
    slug: "bagel-lox-breakfast-board",
    title: "Bagel and Lox Breakfast Board",
    subtitle: "Toasted bagels with lox, cream cheese, capers, and fixings for ten.",
    description:
      "Adapted from classic New York deli appetizing tradition for firehall self-serve breakfast: assorted bagels toasted crisp with platters of lox, cream cheese, capers, red onion, tomato, and cucumber for ten firefighters.",
    filters: ["feed_a_crew", "quick_breakfasts", "breakfast_sandwiches"],
    tags: ["bagel", "lox", "smoked-salmon", "deli", "board"],
    crewSize: 10,
    baseServings: 10,
    prepTime: 25,
    cookTime: 10,
    totalTime: 35,
    difficulty: "easy",
    ingredients: [
      { group: "Base", quantity: "10", name: "bagels", notes: "assorted flavors, split" },
      { group: "Fish", quantity: "2 lb", name: "smoked salmon lox", notes: "sliced thin" },
      { group: "Spread", quantity: "2 cups", name: "cream cheese", notes: "plain and scallion whipped" },
      { group: "Spread", quantity: "1/2 cup", name: "whipped butter", notes: "optional for plain bagels" },
      { group: "Fixings", quantity: "1/2 cup", name: "capers", notes: "drained" },
      { group: "Fixings", quantity: "2", name: "red onions", notes: "thinly sliced" },
      { group: "Fixings", quantity: "4", name: "Roma tomatoes", notes: "sliced" },
      { group: "Fixings", quantity: "2", name: "English cucumbers", notes: "sliced thin, plus lemon wedges" },
    ],
    steps: [
      { stepNumber: 1, title: "Prep all fixings", minutes: 15, instruction: "Slice onion, tomato, and cucumber and arrange in separate bowls on ice or cold trays. Drain capers and portion cream cheese into ramekins. Keep lox refrigerated until the board goes out." },
      { stepNumber: 2, title: "Toast the bagels", tempF: 350, minutes: 8, instruction: "Split bagels and toast on sheet pans at 350°F until edges are crisp, about 6 minutes. Hold in a warm oven uncovered at 200°F—do not stack or they steam soft." },
      { stepNumber: 3, title: "Arrange the board", minutes: 8, instruction: "Center lox on a large chilled platter folded in overlapping layers. Surround with ramekins of cream cheese, capers, onion, tomato, cucumber, and lemon wedges." },
      { stepNumber: 4, title: "Set the line", minutes: 5, instruction: "Place toasted bagels in a warm basket at the line with tongs. Post a simple build order: schmear, lox, capers, onion, tomato." },
      { stepNumber: 5, title: "Serve and refresh", minutes: 5, instruction: "Serve immediately as a self-serve board. Refresh lox and cold fixings on ice if service runs longer than 30 minutes to keep fish food-safe." },
    ],
    stationWorkflow: [
      "Keep lox on ice until the moment the board hits the table—room temp fish is a food-safety issue.",
      "Toast bagels in two sheet pan batches so all ten finish crisp at the same time.",
      "Assign one crew member to restock fixings while another manages bagel refills.",
    ],
    cleanupNotes: [
      "Discard any lox held above 40°F for more than 2 hours—do not save for later shifts.",
      "Wash onion and caper boards separately from bagel crumbs to avoid cross-smells.",
    ],
    leftovers: [
      "Unused cream cheese and capers keep; repurpose lox in scrambled eggs within 24 hours if chilled.",
      "Day-old bagels make excellent French toast sticks with cinnamon sugar.",
    ],
    heroImage: hero("bagel-lox-breakfast-board"),
    thumbImage: thumb("bagel-lox-breakfast-board"),
    imageAlt: "Bagel and lox breakfast board with cream cheese, capers, and fresh fixings",
    publishedAt: now,
    updatedAt: now,
    readMinutes: 6,
    seoTitle: "Bagel and Lox Breakfast Board | Firehall Breakfast",
  },
  {
    slug: "irish-breakfast-fry-up",
    title: "Irish Breakfast Fry-Up",
    subtitle: "Bacon, sausage, black pudding, eggs, and soda bread on one plate.",
    description:
      "Adapted from classic full Irish breakfast tradition for firehall griddle service: back bacon, pork sausages, black pudding, grilled tomato, sautéed mushrooms, fried eggs, and soda bread fried in butter for eight hearty plates.",
    filters: ["feed_a_crew", "high_protein", "skillets"],
    tags: ["irish-breakfast", "fry-up", "bacon", "sausage", "eggs"],
    crewSize: 8,
    baseServings: 8,
    prepTime: 20,
    cookTime: 35,
    totalTime: 55,
    difficulty: "medium",
    ingredients: [
      { group: "Meats", quantity: "2 lb", name: "Irish back bacon", notes: "or thick-cut Canadian bacon" },
      { group: "Meats", quantity: "2 lb", name: "pork breakfast sausages", notes: "8 large links" },
      { group: "Meats", quantity: "1 lb", name: "black pudding", notes: "sliced 1/2-inch thick" },
      { group: "Veg", quantity: "1 lb", name: "white mushrooms", notes: "halved" },
      { group: "Veg", quantity: "4", name: "Roma tomatoes", notes: "halved" },
      { group: "Protein", quantity: "8", name: "large eggs" },
      { group: "Bread", quantity: "8 slices", name: "Irish soda bread", notes: "thick-cut" },
      { group: "Fat", quantity: "4 tbsp", name: "unsalted butter", notes: "plus oil for frying" },
    ],
    steps: [
      { stepNumber: 1, title: "Cook sausages and pudding", minutes: 15, instruction: "Brown sausages in a large skillet over medium heat, turning until internal temperature reaches 160°F, about 12 minutes. Add black pudding slices last 4 minutes— they fall apart if overcooked." },
      { stepNumber: 2, title: "Fry bacon and tomatoes", minutes: 10, instruction: "In a second pan, fry back bacon until edges curl and fat renders. Add tomato halves cut-side down and cook until charred. Hold meats warm on a tray covered loosely with foil." },
      { stepNumber: 3, title: "Sauté mushrooms", minutes: 8, instruction: "Sauté mushrooms in butter over high heat without crowding until deeply browned and moisture evaporates. Season with salt and pepper; hold warm." },
      { stepNumber: 4, title: "Toast soda bread", minutes: 6, instruction: "Fry soda bread slices in butter until golden on both sides, about 2 minutes per side. Keep crisp on a rack in a 200°F oven." },
      { stepNumber: 5, title: "Fry eggs and plate", minutes: 8, instruction: "Fry eggs in clean butter over medium until whites are set (165°F) and yolks are runny. Build each plate with sausage, pudding, bacon, tomato, mushrooms, bread, and an egg. Serve immediately." },
    ],
    stationWorkflow: [
      "Run two skillets in parallel—one for meats, one for veg and eggs—to hit eight plates together.",
      "Add black pudding last; it crumbles if it sits on high heat too long.",
      "Plate assembly is fastest if all components are lined on a warm tray before eggs fry.",
    ],
    cleanupNotes: [
      "Deglaze sausage pans with hot water while warm—pork fat sets hard once cooled.",
      "Wipe black pudding residue immediately; blood sausage stains boards if left to dry.",
    ],
    leftovers: [
      "Reheat meats on a sheet pan at 350°F for 8 minutes; fry fresh eggs to order.",
      "Chop leftovers into a bubble-and-squeak-style potato hash for the next breakfast.",
    ],
    heroImage: hero("irish-breakfast-fry-up"),
    thumbImage: thumb("irish-breakfast-fry-up"),
    imageAlt: "Full Irish breakfast fry-up with bacon, sausage, black pudding, and fried eggs",
    publishedAt: now,
    updatedAt: now,
    readMinutes: 9,
    seoTitle: "Irish Breakfast Fry-Up | Firehall Breakfast",
  },
  {
    slug: "sheet-pan-full-english",
    title: "Sheet Pan Full English",
    subtitle: "English breakfast components roasted and finished on one pan.",
    description:
      "Adapted from classic full English breakfast tradition for firehall batch service: bacon, sausages, baked beans, roasted tomato, and mushrooms on sheet pans, finished with fried eggs for ten crew portions.",
    filters: ["feed_a_crew", "high_protein", "quick_breakfasts"],
    tags: ["full-english", "sheet-pan", "bacon", "sausage", "beans"],
    crewSize: 10,
    baseServings: 10,
    prepTime: 15,
    cookTime: 35,
    totalTime: 50,
    difficulty: "medium",
    ingredients: [
      { group: "Meats", quantity: "2 lb", name: "thick-cut bacon", notes: "lay flat" },
      { group: "Meats", quantity: "2 lb", name: "pork sausages", notes: "10 links" },
      { group: "Veg", quantity: "5", name: "Roma tomatoes", notes: "halved" },
      { group: "Veg", quantity: "1 lb", name: "cremini mushrooms", notes: "whole or halved" },
      { group: "Beans", quantity: "2 cans", name: "baked beans", notes: "15 oz, warmed separately" },
      { group: "Protein", quantity: "10", name: "large eggs" },
      { group: "Bread", quantity: "10 slices", name: "white bread", notes: "for toast" },
      { group: "Fat", quantity: "3 tbsp", name: "olive oil", notes: "plus butter for eggs" },
    ],
    steps: [
      { stepNumber: 1, title: "Heat the oven", tempF: 400, minutes: 0, instruction: "Heat oven to 400°F. Line two sheet pans with foil and lightly oil. Arrange sausages on one pan and bacon on the other with space between pieces for even rendering." },
      { stepNumber: 2, title: "Roast meats", tempF: 400, minutes: 20, instruction: "Roast sausages 15 minutes, turning once, until internal temperature reaches 160°F. Roast bacon 12–15 minutes until crisp. Hold warm tented with foil." },
      { stepNumber: 3, title: "Roast veg", tempF: 425, minutes: 12, instruction: "Toss tomatoes and mushrooms with oil, salt, and pepper on a clean sheet pan. Roast at 425°F until tomatoes collapse and mushrooms brown, about 12 minutes." },
      { stepNumber: 4, title: "Warm beans and toast", minutes: 8, instruction: "Simmer baked beans in a pot over low heat, stirring occasionally. Toast bread until golden. Keep beans and toast warm on the line." },
      { stepNumber: 5, title: "Fry eggs and assemble", minutes: 10, instruction: "Fry eggs in butter over medium until whites are set (165°F) and yolks are runny. Plate each serving with sausage, bacon, beans, roasted veg, toast, and a fried egg." },
    ],
    stationWorkflow: [
      "Separate bacon and sausages on different pans so bacon fat does not steam the links.",
      "Warm beans on the back burner while the oven handles veg—timing is everything.",
      "Fry eggs in two skillets in parallel so ten plates finish within the same 5-minute window.",
    ],
    cleanupNotes: [
      "Drain bacon fat from foil into a container once cooled—never pour grease down the drain.",
      "Discard foil liners with rendered fat to cut scrub time on sheet pans.",
    ],
    leftovers: [
      "Reheat roasted components on a sheet pan at 350°F; fry fresh eggs separately.",
      "Mash leftover beans and sausage into a toast topping with cheddar for quick rarebit-style bites.",
    ],
    heroImage: hero("sheet-pan-full-english"),
    thumbImage: thumb("sheet-pan-full-english"),
    imageAlt: "Sheet pan full English breakfast with bacon, sausage, beans, and fried eggs",
    publishedAt: now,
    updatedAt: now,
    readMinutes: 8,
    seoTitle: "Sheet Pan Full English | Firehall Breakfast",
  },
  {
    slug: "german-potato-breakfast-skillet",
    title: "German Potato Breakfast Skillet",
    subtitle: "Pan-fried potatoes with bratwurst, sauerkraut, and fried eggs.",
    description:
      "Adapted from classic German farmer's breakfast tradition for firehall cast-iron service: Yukon gold potatoes fried with onion until crisp, served with seared bratwurst, warmed sauerkraut, and eggs fried in the same pan.",
    filters: ["skillets", "feed_a_crew", "high_protein"],
    tags: ["german", "potatoes", "bratwurst", "sauerkraut", "skillet"],
    crewSize: 8,
    baseServings: 8,
    prepTime: 15,
    cookTime: 35,
    totalTime: 50,
    difficulty: "medium",
    ingredients: [
      { group: "Potatoes", quantity: "4 lb", name: "Yukon gold potatoes", notes: "diced 1/2-inch" },
      { group: "Potatoes", quantity: "2", name: "yellow onions", notes: "sliced thin" },
      { group: "Sausage", quantity: "2 lb", name: "bratwurst", notes: "8 links, pierced" },
      { group: "Sauerkraut", quantity: "3 cups", name: "sauerkraut", notes: "drained, warmed with caraway" },
      { group: "Protein", quantity: "8", name: "large eggs" },
      { group: "Fat", quantity: "1/4 cup", name: "vegetable oil", notes: "plus butter" },
      { group: "Seasoning", quantity: "1 tsp", name: "caraway seeds", notes: "plus salt and pepper" },
      { group: "Finish", quantity: "1/4 cup", name: "fresh parsley", notes: "chopped, plus mustard at the line" },
    ],
    steps: [
      { stepNumber: 1, title: "Par-cook potatoes", minutes: 10, instruction: "Microwave diced potatoes with a splash of water until just tender, about 8 minutes. Drain and pat completely dry—wet potatoes will not crisp in the skillet." },
      { stepNumber: 2, title: "Brown bratwurst", minutes: 12, instruction: "Sear bratwurst in a lightly oiled skillet over medium until browned on all sides and internal temperature reaches 160°F, about 10 minutes. Hold warm sliced on a tray." },
      { stepNumber: 3, title: "Crisp potatoes and onion", minutes: 15, instruction: "Add oil to a large cast iron over medium-high. Fry potatoes in a single layer 4 minutes before stirring. Add onion and cook until potatoes are golden and onion is soft with crisp edges." },
      { stepNumber: 4, title: "Warm sauerkraut", minutes: 5, instruction: "Heat sauerkraut with caraway in a small pot over low, stirring occasionally. Taste and adjust salt—sauerkraut should be warm but not boiling." },
      { stepNumber: 5, title: "Fry eggs and serve", minutes: 8, instruction: "Make wells in the potato mixture and crack in eggs. Cover over medium-low until whites are set (165°F) and yolks are runny. Top with sliced bratwurst, sauerkraut, and parsley. Serve from the skillet." },
    ],
    stationWorkflow: [
      "Dry potatoes aggressively after par-cooking—this is the key to a crisp German-style pan.",
      "Pierce bratwurst before searing so they do not burst and spray grease.",
      "Warm sauerkraut on the back burner while eggs finish so all components hit the line hot.",
    ],
    cleanupNotes: [
      "Deglaze cast iron with hot water while warm; avoid soap on seasoned pans if your hall uses them.",
      "Rinse sauerkraut pot promptly—acid and salt corrode aluminum if left overnight.",
    ],
    leftovers: [
      "Reheat potato base covered at 325°F; fry fresh eggs and slice fresh bratwurst to order.",
      "Press cold potatoes into patties and griddle until crisp for handheld breakfast sandwiches.",
    ],
    heroImage: hero("german-potato-breakfast-skillet"),
    thumbImage: thumb("german-potato-breakfast-skillet"),
    imageAlt: "German potato breakfast skillet with bratwurst, sauerkraut, and fried eggs",
    publishedAt: now,
    updatedAt: now,
    readMinutes: 8,
    seoTitle: "German Potato Breakfast Skillet | Firehall Breakfast",
  },
  {
    slug: "breakfast-stromboli-roll",
    title: "Breakfast Stromboli Roll",
    subtitle: "Pizza dough rolled with scrambled eggs, ham, and cheese, baked golden.",
    description:
      "Adapted from classic Italian-American stromboli tradition for firehall oven service: pizza dough stretched thin, filled with scrambled eggs, ham, peppers, and mozzarella, rolled tight and baked until golden for eight thick slices.",
    filters: ["feed_a_crew", "high_protein", "breakfast_sandwiches"],
    tags: ["stromboli", "ham", "eggs", "cheese", "baked"],
    crewSize: 8,
    baseServings: 8,
    prepTime: 25,
    cookTime: 25,
    totalTime: 50,
    difficulty: "medium",
    ingredients: [
      { group: "Dough", quantity: "2 lb", name: "pizza dough", notes: "room temperature" },
      { group: "Filling", quantity: "12", name: "large eggs", notes: "soft-scrambled and cooled slightly" },
      { group: "Filling", quantity: "1 1/2 lb", name: "deli ham", notes: "thin slices" },
      { group: "Filling", quantity: "2 cups", name: "shredded mozzarella", notes: "low moisture" },
      { group: "Filling", quantity: "1", name: "roasted red pepper", notes: "sliced, or sautéed bell pepper" },
      { group: "Finish", quantity: "2 tbsp", name: "olive oil", notes: "for brushing" },
      { group: "Finish", quantity: "1/2 cup", name: "grated Parmesan", notes: "plus flaky salt" },
      { group: "Serve", quantity: "1 cup", name: "marinara sauce", notes: "warmed for dipping" },
    ],
    steps: [
      { stepNumber: 1, title: "Heat the oven", tempF: 425, minutes: 0, instruction: "Heat oven to 425°F. Line a sheet pan with parchment. Stretch each dough ball into a 10x14-inch rectangle on a lightly floured surface, keeping edges slightly thicker." },
      { stepNumber: 2, title: "Prep the filling", minutes: 12, instruction: "Soft-scramble eggs over low heat until just set but still glossy. Spread on a tray to cool 5 minutes—hot eggs will melt cheese prematurely and tear dough." },
      { stepNumber: 3, title: "Fill and roll", minutes: 10, instruction: "Layer ham, scrambled eggs, peppers, and mozzarella on the lower third of each dough rectangle, leaving a 1-inch border. Roll tightly from the bottom, pinch seams closed, and place seam-side down on the pan." },
      { stepNumber: 4, title: "Bake until golden", tempF: 425, minutes: 22, instruction: "Brush rolls with olive oil and sprinkle Parmesan. Cut small vents on top. Bake 20–22 minutes until deep golden and internal egg filling reaches 165°F in the center." },
      { stepNumber: 5, title: "Rest and slice", minutes: 8, instruction: "Rest stromboli 8 minutes before slicing into thick portions with a serrated knife. Serve with warm marinara for dipping at the line." },
    ],
    stationWorkflow: [
      "Cool scrambled eggs slightly before filling—hot filling blows out seams during baking.",
      "Vent the top of each roll so steam escapes and crust stays crisp.",
      "Slice with a serrated knife in one motion to avoid squashing the roll.",
    ],
    cleanupNotes: [
      "Use parchment on sheet pans so melted cheese releases without scraping.",
      "Wipe flour from prep surfaces before it mixes with oil and forms paste.",
    ],
    leftovers: [
      "Reheat slices on a sheet pan at 375°F for 8 minutes; microwave makes crust rubbery.",
      "Dice leftovers into a breakfast strata with extra eggs and milk for tomorrow's bake.",
    ],
    heroImage: hero("breakfast-stromboli-roll"),
    thumbImage: thumb("breakfast-stromboli-roll"),
    imageAlt: "Golden breakfast stromboli sliced with ham, eggs, and melted cheese",
    publishedAt: now,
    updatedAt: now,
    readMinutes: 8,
    seoTitle: "Breakfast Stromboli Roll | Firehall Breakfast",
  },
  {
    slug: "scrapple-and-eggs-skillet",
    title: "Scrapple and Eggs Skillet",
    subtitle: "Crisp Pennsylvania scrapple slices with fried eggs and toast points.",
    description:
      "Adapted from classic Pennsylvania Dutch scrapple tradition for firehall skillet breakfast: cornmeal-and-pork scrapple sliced and fried until shatter-crisp outside and creamy inside, served with fried eggs and buttered toast points.",
    filters: ["skillets", "feed_a_crew", "high_protein"],
    tags: ["scrapple", "pennsylvania", "eggs", "cast-iron", "pork"],
    crewSize: 8,
    baseServings: 8,
    prepTime: 10,
    cookTime: 25,
    totalTime: 35,
    difficulty: "easy",
    ingredients: [
      { group: "Scrapple", quantity: "2 lb", name: "scrapple loaf", notes: "cut into 1/2-inch slices" },
      { group: "Protein", quantity: "8", name: "large eggs" },
      { group: "Toast", quantity: "8 slices", name: "white bread", notes: "cut into triangles" },
      { group: "Fat", quantity: "3 tbsp", name: "vegetable oil", notes: "for scrapple, plus butter" },
      { group: "Seasoning", quantity: "1/2 tsp", name: "black pepper", notes: "scrapple is seasoned—taste before salting" },
      { group: "Finish", quantity: "4 tbsp", name: "unsalted butter", notes: "for toast and eggs" },
      { group: "Optional", quantity: "1/2 cup", name: "apple butter", notes: "for serving" },
      { group: "Optional", quantity: "1/4 cup", name: "maple syrup", notes: "Pennsylvania sweet-savory tradition" },
    ],
    steps: [
      { stepNumber: 1, title: "Slice scrapple cold", minutes: 5, instruction: "Cut scrapple into 1/2-inch slices while still cold from the fridge—warm scrapple crumbles when sliced. Pat slices dry with paper towels to reduce splatter." },
      { stepNumber: 2, title: "Fry scrapple crisp", minutes: 12, instruction: "Heat oil in a large cast iron over medium. Fry scrapple slices without crowding 4 minutes per side until a deep brown crust forms and centers are creamy. Hold warm on a rack." },
      { stepNumber: 3, title: "Toast the bread", minutes: 6, instruction: "Butter toast triangles and griddle until golden on both sides, about 2 minutes per side. Keep crisp on a warm tray." },
      { stepNumber: 4, title: "Fry the eggs", minutes: 8, instruction: "Wipe excess scrapple oil from the pan if needed. Fry eggs in butter over medium until whites are fully set (165°F) and yolks are runny or jammy to preference." },
      { stepNumber: 5, title: "Plate and serve", minutes: 3, instruction: "Serve two scrapple slices per plate with a fried egg on top and toast points on the side. Offer apple butter or maple syrup for crew who like the sweet-savory combo." },
    ],
    stationWorkflow: [
      "Chill scrapple until slicing—warm loaves fall apart on the cutting board.",
      "Fry in batches so slices crisp instead of steaming in overcrowded pans.",
      "Hold scrapple on a rack, not paper towels, so the crust stays audible.",
    ],
    cleanupNotes: [
      "Scrapple spatters aggressively—wipe stovetop immediately after frying.",
      "Soak cast iron with hot water while warm; scrapple crumbs glue fast once cooled.",
    ],
    leftovers: [
      "Reheat scrapple on a griddle over medium until crust re-crisp; do not microwave.",
      "Crumble leftover scrapple into a hash with diced potatoes and onions.",
    ],
    heroImage: hero("scrapple-and-eggs-skillet"),
    thumbImage: thumb("scrapple-and-eggs-skillet"),
    imageAlt: "Crisp scrapple slices with fried eggs and buttered toast points",
    publishedAt: now,
    updatedAt: now,
    readMinutes: 7,
    seoTitle: "Scrapple and Eggs Skillet | Firehall Breakfast",
  },
  {
    slug: "club-sandwich-breakfast-bake",
    title: "Club Sandwich Breakfast Bake",
    subtitle: "Layered bread, turkey, bacon, tomato, and eggs baked like a strata.",
    description:
      "Adapted from classic American club sandwich tradition for firehall breakfast bake: layers of toasted bread, turkey, bacon, tomato, and cheddar soaked in an egg-milk custard and baked until puffed and golden for ten portions.",
    filters: ["feed_a_crew", "high_protein", "breakfast_sandwiches"],
    tags: ["club-sandwich", "strata", "turkey", "bacon", "bake"],
    crewSize: 10,
    baseServings: 10,
    prepTime: 25,
    cookTime: 45,
    totalTime: 70,
    difficulty: "medium",
    ingredients: [
      { group: "Bread", quantity: "16 slices", name: "sandwich bread", notes: "toasted until crisp" },
      { group: "Protein", quantity: "1 1/2 lb", name: "deli turkey", notes: "sliced thick" },
      { group: "Protein", quantity: "1 lb", name: "bacon", notes: "cooked crisp and crumbled" },
      { group: "Veg", quantity: "3", name: "Roma tomatoes", notes: "sliced, seeds drained" },
      { group: "Egg mix", quantity: "12", name: "large eggs" },
      { group: "Egg mix", quantity: "2 1/2 cups", name: "whole milk" },
      { group: "Cheese", quantity: "3 cups", name: "shredded Swiss", notes: "divided" },
      { group: "Finish", quantity: "1/2 cup", name: "mayonnaise", notes: "light spread on bread, plus lettuce after bake" },
    ],
    steps: [
      { stepNumber: 1, title: "Heat the oven", tempF: 375, minutes: 0, instruction: "Heat oven to 375°F. Grease a deep 9x13 pan. Toast bread until crisp and lightly spread one side of each slice with a thin layer of mayonnaise—this keeps layers distinct after baking." },
      { stepNumber: 2, title: "Cook bacon and prep layers", minutes: 15, instruction: "Cook bacon until crisp, drain, and crumble. Layer half the bread in the pan, top with half the turkey, bacon, tomato, and Swiss. Repeat layers, finishing with bread on top." },
      { stepNumber: 3, title: "Pour the custard", minutes: 5, instruction: "Whisk eggs, milk, salt, and pepper until smooth. Pour slowly over the layered bread, pressing gently so custard reaches the bottom. Rest 10 minutes so bread absorbs liquid." },
      { stepNumber: 4, title: "Bake until set", tempF: 375, minutes: 40, instruction: "Cover with foil and bake 25 minutes. Uncover, top with remaining Swiss, and bake 15 more until center reaches 165°F and top is golden brown." },
      { stepNumber: 5, title: "Rest and garnish", minutes: 10, instruction: "Rest 10 minutes before cutting into squares. Top each portion with shredded lettuce and an extra pinch of bacon if desired. Serve with pickle spears at the line." },
    ],
    stationWorkflow: [
      "Toast bread fully crisp—soft bread turns mushy in the custard.",
      "Drain tomato seeds so excess moisture does not pool in the bake.",
      "Cover for the first half of baking so top cheese does not over-brown before center sets.",
    ],
    cleanupNotes: [
      "Soak the 9x13 with hot water while warm before egg custard dries on.",
      "Wipe mayo smears from prep boards before they mix with bacon grease.",
    ],
    leftovers: [
      "Reheat portions covered at 325°F for 12 minutes; add fresh lettuce after reheating.",
      "Cut leftovers into cubes and pan-fry in butter for crispy breakfast croutons in soup.",
    ],
    heroImage: hero("club-sandwich-breakfast-bake"),
    thumbImage: thumb("club-sandwich-breakfast-bake"),
    imageAlt: "Club sandwich breakfast bake with turkey, bacon, tomato, and melted Swiss",
    publishedAt: now,
    updatedAt: now,
    readMinutes: 8,
    seoTitle: "Club Sandwich Breakfast Bake | Firehall Breakfast",
  },
  {
    slug: "johnnycakes-with-syrup",
    title: "Johnnycakes with Maple Syrup",
    subtitle: "Rhode Island cornmeal griddle cakes with butter and warm syrup.",
    description:
      "Adapted from classic New England johnnycake tradition for firehall griddle service: stone-ground cornmeal batter cooked on a hot griddle until lacy-edged and golden, served with whipped butter and warm maple syrup for eight.",
    filters: ["feed_a_crew", "quick_breakfasts", "breakfast_sandwiches"],
    tags: ["johnnycakes", "cornmeal", "new-england", "griddle", "maple"],
    crewSize: 8,
    baseServings: 8,
    prepTime: 15,
    cookTime: 25,
    totalTime: 40,
    difficulty: "easy",
    ingredients: [
      { group: "Batter", quantity: "2 cups", name: "fine stone-ground cornmeal", notes: "white or yellow" },
      { group: "Batter", quantity: "2 cups", name: "boiling water", notes: "to scald cornmeal" },
      { group: "Batter", quantity: "1 cup", name: "whole milk", notes: "room temperature" },
      { group: "Batter", quantity: "2", name: "large eggs", notes: "beaten" },
      { group: "Batter", quantity: "3 tbsp", name: "unsalted butter", notes: "melted, plus more for griddle" },
      { group: "Batter", quantity: "2 tbsp", name: "granulated sugar", notes: "plus 1 tsp salt" },
      { group: "Serve", quantity: "2 cups", name: "maple syrup", notes: "warmed" },
      { group: "Serve", quantity: "1/2 cup", name: "whipped butter", notes: "plus optional bacon on the side" },
    ],
    steps: [
      { stepNumber: 1, title: "Scald the cornmeal", minutes: 10, instruction: "Pour boiling water over cornmeal in a large bowl, whisking until smooth. Cover and rest 10 minutes so cornmeal fully hydrates and the batter thickens to porridge consistency." },
      { stepNumber: 2, title: "Finish the batter", minutes: 5, instruction: "Whisk in milk, eggs, melted butter, sugar, and salt until uniform. Batter should pour like thick cream—thin with a tablespoon of milk if it stands in a mound." },
      { stepNumber: 3, title: "Heat the griddle", minutes: 5, instruction: "Heat a griddle or cast iron over medium until a drop of water dances and evaporates in 2 seconds (roughly 375°F surface). Brush lightly with butter." },
      { stepNumber: 4, title: "Griddle the cakes", minutes: 15, instruction: "Pour 1/4 cup batter per cake, spreading slightly if needed. Cook 3–4 minutes until edges look dry and bottoms are deep golden, then flip and cook 2–3 minutes more. Hold warm on a rack." },
      { stepNumber: 5, title: "Serve with syrup", minutes: 3, instruction: "Stack three cakes per plate with whipped butter and warm maple syrup on the side. Serve immediately while edges stay lacy and centers are tender." },
    ],
    stationWorkflow: [
      "Scald cornmeal properly—under-hydrated batter tastes gritty and cracks on the griddle.",
      "Cook in batches of six so the griddle stays at temp between pours.",
      "Hold finished cakes on a rack in a 200°F oven, never stacked, to preserve crisp edges.",
    ],
    cleanupNotes: [
      "Wipe the griddle while still warm with a damp cloth before cornmeal hardens.",
      "Soak mixing bowls immediately—cornmeal batter dries into cement quickly.",
    ],
    leftovers: [
      "Reheat cakes on a dry griddle over medium until edges re-crisp, about 2 minutes per side.",
      "Crumble stale johnnycakes into cornbread stuffing for a dinner side later in the week.",
    ],
    heroImage: hero("johnnycakes-with-syrup"),
    thumbImage: thumb("johnnycakes-with-syrup"),
    imageAlt: "Golden johnnycakes with whipped butter and warm maple syrup",
    publishedAt: now,
    updatedAt: now,
    readMinutes: 6,
    seoTitle: "Johnnycakes with Maple Syrup | Firehall Breakfast",
  },
  {
    slug: "overnight-sausage-strata",
    title: "Overnight Sausage Strata",
    subtitle: "Make-ahead bread, sausage, and egg bake rested overnight and baked hot.",
    description:
      "Adapted from classic French strata tradition for firehall make-ahead breakfast: cubed bread layered with browned sausage and cheddar, soaked overnight in an egg-milk custard, then baked golden for ten crew portions.",
    filters: ["feed_a_crew", "high_protein", "quick_breakfasts"],
    tags: ["strata", "overnight", "sausage", "make-ahead", "bake"],
    crewSize: 10,
    baseServings: 10,
    prepTime: 25,
    cookTime: 50,
    totalTime: 75,
    difficulty: "easy",
    ingredients: [
      { group: "Base", quantity: "1 lb", name: "day-old bread", notes: "cubed into 1-inch pieces" },
      { group: "Protein", quantity: "2 lb", name: "breakfast sausage", notes: "browned and crumbled" },
      { group: "Cheese", quantity: "3 cups", name: "shredded sharp cheddar", notes: "divided" },
      { group: "Egg mix", quantity: "12", name: "large eggs" },
      { group: "Egg mix", quantity: "3 cups", name: "whole milk", notes: "or half-and-half" },
      { group: "Seasoning", quantity: "1 tsp", name: "dry mustard", notes: "plus salt, pepper, and pinch nutmeg" },
      { group: "Optional", quantity: "1 cup", name: "sautéed onion", notes: "optional layer" },
      { group: "Finish", quantity: "1/2 cup", name: "sliced green onions", notes: "plus hot sauce at the line" },
    ],
    steps: [
      { stepNumber: 1, title: "Brown sausage and build layers", minutes: 20, instruction: "Cook sausage until no pink remains and internal temperature reaches 160°F; drain. Grease a deep 9x13 pan. Layer half the bread cubes, sausage, optional onion, and half the cheddar. Repeat layers." },
      { stepNumber: 2, title: "Mix and pour custard", minutes: 5, instruction: "Whisk eggs, milk, mustard, salt, pepper, and nutmeg until smooth. Pour evenly over the bread layers, pressing gently so all cubes contact liquid." },
      { stepNumber: 3, title: "Refrigerate overnight", instruction: "Cover tightly and refrigerate at least 8 hours or overnight so bread fully absorbs custard. Remove from fridge 30 minutes before baking to take the chill off the pan." },
      { stepNumber: 4, title: "Bake until puffed", tempF: 375, minutes: 45, instruction: "Heat oven to 375°F. Top with remaining cheddar. Bake uncovered 45–50 minutes until center reaches 165°F, top is golden, and a knife inserted in the middle comes out clean." },
      { stepNumber: 5, title: "Rest and portion", minutes: 10, instruction: "Rest 10 minutes before cutting into squares so custard sets for clean portions. Garnish with green onions and serve with hot sauce at the line." },
    ],
    stationWorkflow: [
      "Assemble the night before so morning service is mostly oven time.",
      "Use stale bread—fresh bread turns to mush after an overnight soak.",
      "Check center temp with a probe; golden top can hide under-set custard in the middle.",
    ],
    cleanupNotes: [
      "Wash the assembly pan the morning of service while the strata bakes in the oven.",
      "Discard any custard that spilled and baked onto the oven floor once cooled.",
    ],
    leftovers: [
      "Reheat portions covered at 325°F for 12 minutes until steaming in the center.",
      "Cube leftovers and pan-fry in butter for crispy strata hash with a fried egg on top.",
    ],
    heroImage: hero("overnight-sausage-strata"),
    thumbImage: thumb("overnight-sausage-strata"),
    imageAlt: "Overnight sausage strata baked golden with melted cheddar",
    publishedAt: now,
    updatedAt: now,
    readMinutes: 8,
    seoTitle: "Overnight Sausage Strata | Firehall Breakfast",
  },
  {
    slug: "biscuit-french-toast-sliders",
    title: "Biscuit French Toast Sliders",
    subtitle: "Buttermilk biscuits dipped in custard, griddled, and glazed with syrup butter.",
    description:
      "Adapted from classic French toast tradition using Southern buttermilk biscuits for firehall slider service: split biscuits dipped in cinnamon custard, griddled until golden, brushed with maple butter, and served warm for eight.",
    filters: ["feed_a_crew", "breakfast_sandwiches", "quick_breakfasts"],
    tags: ["french-toast", "biscuits", "sliders", "griddle", "maple"],
    crewSize: 8,
    baseServings: 8,
    prepTime: 15,
    cookTime: 20,
    totalTime: 35,
    difficulty: "easy",
    ingredients: [
      { group: "Biscuits", quantity: "8", name: "large buttermilk biscuits", notes: "bakery or homemade, split" },
      { group: "Custard", quantity: "6", name: "large eggs" },
      { group: "Custard", quantity: "1 1/2 cups", name: "whole milk" },
      { group: "Custard", quantity: "2 tsp", name: "vanilla extract" },
      { group: "Custard", quantity: "1 tsp", name: "ground cinnamon", notes: "plus pinch nutmeg" },
      { group: "Cook", quantity: "3 tbsp", name: "unsalted butter", notes: "for griddle" },
      { group: "Glaze", quantity: "1/4 cup", name: "maple syrup", notes: "mixed with 2 tbsp melted butter" },
      { group: "Serve", quantity: "1 cup", name: "powdered sugar", notes: "optional dust, plus berries" },
    ],
    steps: [
      { stepNumber: 1, title: "Mix the custard", minutes: 5, instruction: "Whisk eggs, milk, vanilla, cinnamon, nutmeg, and a pinch of salt until smooth. Pour into a shallow dish wide enough to dip biscuit halves." },
      { stepNumber: 2, title: "Split and dip biscuits", minutes: 8, instruction: "Split biscuits horizontally. Dip cut sides in custard 3 seconds per side—do not soak or they fall apart. Let excess drip off before hitting the griddle." },
      { stepNumber: 3, title: "Griddle until golden", minutes: 12, instruction: "Heat a griddle over medium and melt butter until foaming. Cook dipped biscuit halves cut-side down 3–4 minutes until deep golden, flip, and cook 2–3 minutes more until centers reach 165°F." },
      { stepNumber: 4, title: "Glaze and assemble", minutes: 5, instruction: "Brush warm maple butter on the griddle side of each half. Sandwich halves back together so glaze faces out. Hold briefly on the griddle to set the glaze." },
      { stepNumber: 5, title: "Serve warm", minutes: 3, instruction: "Serve two sliders per plate with optional powdered sugar and berries. Serve immediately while biscuit edges stay crisp and centers are custard-soft." },
    ],
    stationWorkflow: [
      "Dip and griddle in small batches—soaked biscuits tear if stacked on a holding tray.",
      "Keep maple butter warm in a squeeze bottle for fast glazing at the griddle.",
      "Split biscuits evenly so sliders sandwich back together without overhang.",
    ],
    cleanupNotes: [
      "Wipe griddle between batches before custard caramelizes and burns.",
      "Rinse custard dish immediately—dried egg is stubborn on shallow pans.",
    ],
    leftovers: [
      "Reheat sliders on a dry griddle over medium 2 minutes per side to restore crisp edges.",
      "Cube leftovers into a bread pudding bake with extra custard and raisins.",
    ],
    heroImage: hero("biscuit-french-toast-sliders"),
    thumbImage: thumb("biscuit-french-toast-sliders"),
    imageAlt: "Biscuit French toast sliders glazed with maple butter on a griddle",
    publishedAt: now,
    updatedAt: now,
    readMinutes: 6,
    seoTitle: "Biscuit French Toast Sliders | Firehall Breakfast",
  },
  {
    slug: "lumberjack-breakfast-platter",
    title: "Lumberjack Breakfast Platter",
    subtitle: "Pancakes, eggs, bacon, sausage, and hash browns for a hungry crew.",
    description:
      "Adapted from classic North American logging-camp breakfast tradition for firehall platter service: stacks of pancakes, crispy bacon, browned sausage links, shredded hash browns, and eggs cooked to order for eight hungry firefighters.",
    filters: ["feed_a_crew", "high_protein", "skillets"],
    tags: ["lumberjack", "pancakes", "bacon", "sausage", "hash-browns"],
    crewSize: 8,
    baseServings: 8,
    prepTime: 20,
    cookTime: 40,
    totalTime: 60,
    difficulty: "medium",
    ingredients: [
      { group: "Pancakes", quantity: "4 cups", name: "pancake mix", notes: "prepared per package for 24 silver-dollar cakes" },
      { group: "Pancakes", quantity: "3 cups", name: "whole milk", notes: "for batter" },
      { group: "Meats", quantity: "2 lb", name: "thick-cut bacon", notes: "16 slices" },
      { group: "Meats", quantity: "2 lb", name: "pork sausage links", notes: "16 links" },
      { group: "Hash", quantity: "2 lb", name: "frozen hash browns", notes: "shredded, crisped on griddle" },
      { group: "Protein", quantity: "8", name: "large eggs", notes: "fried or scrambled to order" },
      { group: "Serve", quantity: "2 cups", name: "maple syrup", notes: "warmed" },
      { group: "Serve", quantity: "1/2 cup", name: "unsalted butter", notes: "for pancakes and griddle" },
    ],
    steps: [
      { stepNumber: 1, title: "Cook bacon and sausage", tempF: 400, minutes: 18, instruction: "Lay bacon on sheet pans and roast at 400°F until crisp, about 15 minutes. Sear sausage links in a skillet over medium until browned and internal temperature reaches 160°F, about 12 minutes. Hold warm tented with foil." },
      { stepNumber: 2, title: "Crisp hash browns", minutes: 12, instruction: "Spread hash browns on a lightly oiled griddle in a thin layer. Cook undisturbed 4 minutes for crust, then flip sections and cook until golden. Season with salt and pepper; hold warm." },
      { stepNumber: 3, title: "Mix and griddle pancakes", minutes: 15, instruction: "Prepare pancake batter per package using milk and melted butter. Griddle silver-dollar pancakes over medium until bubbles form and edges set, flip, and cook until centers reach 190°F and bottoms are golden." },
      { stepNumber: 4, title: "Cook eggs to order", minutes: 10, instruction: "Fry or scramble eggs in butter over medium heat until whites are fully set (165°F) for fried, or until scrambled curds are moist but not wet. Season each batch with salt and pepper." },
      { stepNumber: 5, title: "Platter and serve", minutes: 5, instruction: "Arrange pancakes, bacon, sausage, hash browns, and eggs on warm platters with syrup and butter at the line. Serve family-style so the crew builds their own lumberjack plate." },
    ],
    stationWorkflow: [
      "Run oven bacon and griddle hash in parallel while one cook manages pancake batter.",
      "Hold meats tented with foil on a warm tray—never cover bacon tightly or it steams soft.",
      "Cook eggs last to order so yolks stay runny for crew who want dippers for hash.",
    ],
    cleanupNotes: [
      "Drain bacon fat from sheet pans into a heat-safe container once cooled.",
      "Scrape griddle while still warm with a bench scraper before pancake batter dries on.",
    ],
    leftovers: [
      "Reheat pancakes on a griddle 2 minutes per side; microwave makes them rubbery.",
      "Chop leftover meats and potatoes into a next-day breakfast burrito filling with eggs.",
    ],
    heroImage: hero("lumberjack-breakfast-platter"),
    thumbImage: thumb("lumberjack-breakfast-platter"),
    imageAlt: "Lumberjack breakfast platter with pancakes, bacon, sausage, hash browns, and eggs",
    publishedAt: now,
    updatedAt: now,
    readMinutes: 9,
    seoTitle: "Lumberjack Breakfast Platter | Firehall Breakfast",
  },
];
