import type { BreakfastRecipePage } from "../breakfast-schema.js";

export type BreakfastRecipePageDraft = Omit<BreakfastRecipePage, "nutrition">;

const now = new Date().toISOString();
const hero = (slug: string) => `/images/breakfast/${slug}.jpg`;
const thumb = (slug: string) => `/images/thumbs/breakfast/${slug}.jpg`;

export const NEW_BREAKFAST_PAGES: BreakfastRecipePageDraft[] = [
  {
    slug: "red-lead-skillet",
    title: "Red Lead Skillet",
    subtitle: "Senior cook specialty—steak, peppers, and eggs in one cast-iron pan.",
    description:
      "The red lead's signature skillet: seared steak strips, blistered peppers, and eggs cracked over the top. Built for a hungry crew after a long night shift with real heat cues and a workflow that keeps everything hot between calls.",
    filters: ["skillets", "high_protein", "feed_a_crew"],
    tags: ["steak", "cast-iron", "peppers", "eggs", "senior-cook"],
    crewSize: 8,
    baseServings: 8,
    prepTime: 15,
    cookTime: 25,
    totalTime: 40,
    difficulty: "medium",
    ingredients: [
      { group: "Protein", quantity: "2 lb", name: "sirloin or flank steak", notes: "sliced thin against the grain" },
      { group: "Protein", quantity: "14", name: "large eggs" },
      { group: "Veg", quantity: "3", name: "bell peppers", notes: "mixed colors, sliced" },
      { group: "Veg", quantity: "1", name: "red onion", notes: "sliced thin" },
      { group: "Veg", quantity: "3.5 lb", name: "Yukon gold potatoes", notes: "diced 1/2-inch" },
      { group: "Seasoning", quantity: "3 tbsp", name: "steak seasoning", notes: "or equal parts salt, pepper, garlic powder" },
      { group: "Fat", quantity: "3 tbsp", name: "vegetable oil", notes: "plus butter for finishing" },
      { group: "Finish", quantity: "1 1/2 cups", name: "shredded pepper jack", notes: "optional melt on top" },
    ],
    steps: [
      { stepNumber: 1, title: "Par-cook the potatoes", minutes: 8, instruction: "Microwave diced potatoes with a splash of water in a covered bowl until just tender. Drain well and pat dry so the skillet gets crust instead of steam." },
      { stepNumber: 2, title: "Sear steak strips", minutes: 8, instruction: "Heat cast iron over high with oil until shimmering (about 400°F surface). Sear steak in batches without crowding, 2–3 minutes per side, until deeply browned and internal temperature reaches 130°F for medium-rare strips. Rest on a warm tray while you build the base." },
      { stepNumber: 3, title: "Crisp potatoes and peppers", minutes: 10, instruction: "Add more oil to the pan, then potatoes in a single layer. Let them sit 3 minutes for color, toss, then add onion and peppers. Cook over medium-high until charred at the edges." },
      { stepNumber: 4, title: "Combine and make wells", minutes: 3, instruction: "Fold steak back into the skillet. Make shallow wells across the surface and crack an egg into each well. Season with salt and pepper." },
      { stepNumber: 5, title: "Cover and finish", minutes: 6, instruction: "Cover with a lid or inverted sheet pan over medium-low heat until egg whites are fully set (165°F) and yolks are runny or jammy to your crew's preference. Scatter cheese, cover 60 seconds to melt, and serve straight from the pan." },
    ],
    stationWorkflow: [
      "Assign one cook to the cast iron and one to toast or warm plates so service doesn't stall when eggs finish.",
      "Sear steak in batches before the crew lines up—hold sliced on a warm tray covered loosely with foil.",
      "Serve family-style from the skillet or portion onto warm plates immediately; eggs wait for no one.",
    ],
    cleanupNotes: [
      "Deglaze the cast iron with hot water while still warm, then scrape with a chain-mail scrubber once cooled enough to handle safely.",
      "Wipe cutting boards and knives immediately after raw steak prep to avoid cross-contamination during egg service.",
    ],
    leftovers: [
      "Reheat potato-steak base covered at 325°F for 10 minutes; fry fresh eggs to order rather than reheating set yolks.",
      "Chop leftovers into breakfast burrito filling with hot sauce and shredded cheese for the next shift.",
    ],
    heroImage: hero("red-lead-skillet"),
    thumbImage: thumb("red-lead-skillet"),
    imageAlt: "Cast-iron skillet with seared steak, peppers, and sunny-side eggs for the crew",
    publishedAt: now,
    updatedAt: now,
    readMinutes: 7,
    seoTitle: "Red Lead Skillet | Firehall Breakfast",
  },
  {
    slug: "firehall-breakfast-pizza",
    title: "Firehall Breakfast Pizza",
    subtitle: "Sheet-pan pizza loaded with scrambled eggs, sausage, and melty cheese.",
    description:
      "Two large sheet-pan pizzas feed a full hall without a delivery driver. Pre-baked crusts get a layer of gravy-spiked white sauce, scrambled eggs, browned sausage, and cheddar—cut into squares for fast line service.",
    filters: ["feed_a_crew", "high_protein", "breakfast_sandwiches"],
    tags: ["pizza", "sheet-pan", "sausage", "eggs", "cheddar"],
    crewSize: 12,
    baseServings: 12,
    prepTime: 20,
    cookTime: 28,
    totalTime: 48,
    difficulty: "medium",
    ingredients: [
      { group: "Base", quantity: "2", name: "store-bought pizza dough balls", notes: "or 2 lb homemade dough" },
      { group: "Base", quantity: "2 tbsp", name: "olive oil", notes: "for stretching and pan" },
      { group: "Sauce", quantity: "1 cup", name: "country gravy", notes: "jarred or leftover, warmed" },
      { group: "Sauce", quantity: "1/2 cup", name: "shredded mozzarella", notes: "mixed into gravy for white sauce" },
      { group: "Toppings", quantity: "18", name: "large eggs", notes: "soft-scrambled off heat" },
      { group: "Toppings", quantity: "2 lb", name: "breakfast sausage", notes: "browned and crumbled, drained" },
      { group: "Toppings", quantity: "3 cups", name: "shredded cheddar", notes: "sharp or medium" },
      { group: "Finish", quantity: "1/2 cup", name: "sliced green onions", notes: "and hot sauce at the line" },
    ],
    steps: [
      { stepNumber: 1, title: "Heat the ovens", tempF: 425, minutes: 0, instruction: "Heat oven to 425°F. Oil two half-sheet pans or large rimmed baking sheets. Stretch dough to fit each pan with a slight rim for toppings." },
      { stepNumber: 2, title: "Par-bake the crusts", tempF: 425, minutes: 8, instruction: "Dock dough with a fork, then par-bake 6–8 minutes until the surface sets but is not fully browned. This prevents a soggy middle once eggs and gravy go on." },
      { stepNumber: 3, title: "Prep toppings", minutes: 12, instruction: "Whisk gravy with mozzarella until smooth. Soft-scramble eggs over low heat—they should still look glossy. Brown sausage and drain on paper towels so the pizza doesn't weep grease." },
      { stepNumber: 4, title: "Build and bake", tempF: 425, minutes: 14, instruction: "Spread white gravy on par-baked crusts, dot with scrambled eggs and sausage, then blanket with cheddar. Bake until cheese bubbles and crust edges are deep golden." },
      { stepNumber: 5, title: "Rest and square-cut", minutes: 5, instruction: "Rest pizzas 5 minutes on the pan so cheese sets. Cut into squares with a sharp pizza wheel or bench scraper. Hold warm at 200°F uncovered for crisp edges." },
    ],
    stationWorkflow: [
      "One cook runs the oven rotation while another scrambles eggs and browns sausage in parallel.",
      "Par-bake both crusts together, then build one pizza at a time so the second crust doesn't over-proof on the counter.",
      "Cut on the sheet pan at the line and slide squares onto a warm baking dish for self-serve portions.",
    ],
    cleanupNotes: [
      "Line sheet pans with parchment for easier release and faster scrub-down after cheese bakes on.",
      "Soak pizza cutters and bench scrapers immediately—egg and cheese glue sets hard once cooled.",
    ],
    leftovers: [
      "Reheat squares on a sheet pan at 350°F for 8 minutes; avoid the microwave so crust stays crisp.",
      "Dice cold squares into a breakfast strata base with extra eggs and milk for tomorrow's bake.",
    ],
    heroImage: hero("firehall-breakfast-pizza"),
    thumbImage: thumb("firehall-breakfast-pizza"),
    imageAlt: "Sheet-pan breakfast pizza topped with scrambled eggs, sausage, and melted cheddar",
    publishedAt: now,
    updatedAt: now,
    readMinutes: 8,
    seoTitle: "Firehall Breakfast Pizza | Firehall Breakfast",
  },
  {
    slug: "breakfast-enchiladas",
    title: "Breakfast Enchiladas for the Crew",
    subtitle: "Rolled tortillas stuffed with eggs and chorizo under green chili sauce.",
    description:
      "A hotel-pan bake of flour tortillas rolled tight with scrambled eggs, chorizo, and cheese, then smothered in verde sauce and baked until bubbling. Cuts into clean portions for a crew that wants something bolder than a standard egg bake.",
    filters: ["feed_a_crew", "high_protein"],
    tags: ["enchiladas", "chorizo", "verde", "bake", "9x13"],
    crewSize: 10,
    baseServings: 10,
    prepTime: 25,
    cookTime: 35,
    totalTime: 60,
    difficulty: "medium",
    ingredients: [
      { group: "Filling", quantity: "16", name: "large eggs", notes: "soft-scrambled with salt and pepper" },
      { group: "Filling", quantity: "1 1/2 lb", name: "Mexican chorizo", notes: "cooked and crumbled, fat drained" },
      { group: "Filling", quantity: "2 cups", name: "shredded Monterey Jack", notes: "divided for filling and top" },
      { group: "Build", quantity: "14", name: "8-inch flour tortillas", notes: "warmed briefly to stay pliable" },
      { group: "Sauce", quantity: "3 cups", name: "green enchilada sauce", notes: "jarred or homemade" },
      { group: "Sauce", quantity: "1/2 cup", name: "sour cream", notes: "whisked into half the sauce for creaminess" },
      { group: "Finish", quantity: "1 cup", name: "cotija or feta", notes: "crumbled" },
      { group: "Finish", quantity: "1/2 cup", name: "cilantro", notes: "chopped, plus lime wedges" },
    ],
    steps: [
      { stepNumber: 1, title: "Heat the oven", tempF: 375, minutes: 0, instruction: "Heat oven to 375°F. Grease a deep 9x13 baking dish, or two smaller baking dishes. Warm tortillas in a dry skillet or wrapped in foil so they roll without tearing." },
      { stepNumber: 2, title: "Cook the filling", minutes: 15, instruction: "Brown chorizo in a large skillet, drain fat, then add soft-scrambled eggs and half the Jack cheese. Mix gently—the eggs should stay fluffy, not mashed." },
      { stepNumber: 3, title: "Roll the enchiladas", minutes: 12, instruction: "Spread a thin layer of sauce in the pan. Fill each tortilla with a generous scoop of filling, roll tight, and place seam-side down in a snug single layer." },
      { stepNumber: 4, title: "Sauce and cheese", minutes: 5, instruction: "Pour remaining sauce evenly over the rolls. Top with remaining Jack and cotija. Cover with foil for the first half of baking to keep tortillas soft." },
      { stepNumber: 5, title: "Bake and rest", tempF: 375, minutes: 25, instruction: "Bake covered 20 minutes, uncover, and bake 10 more until sauce bubbles at the edges. Rest 10 minutes before cutting into portions so slices hold on the plate." },
    ],
    stationWorkflow: [
      "Set up a rolling station with warm tortillas, filling bowl, and sauced pan ready before scrambling eggs.",
      "One cook rolls while another manages sauce and oven timing—don't let rolled enchiladas sit dry on the counter.",
      "Garnish with cilantro and lime at the line; hold extra sauce warm for second passes.",
    ],
    cleanupNotes: [
      "Soak the chorizo skillet immediately with hot water and a drop of dish soap to cut grease before it sets.",
      "Scrape baked-on cheese from the 9x13 while still warm using a plastic scraper, not a metal blade on glass.",
    ],
    leftovers: [
      "Portion enchiladas into containers with extra sauce on top; reheat covered at 325°F until steaming in the center.",
      "Chop leftovers into a breakfast burrito filling with scrambled eggs and hot sauce for handheld service.",
    ],
    heroImage: hero("breakfast-enchiladas"),
    thumbImage: thumb("breakfast-enchiladas"),
    imageAlt: "Crew-sized breakfast enchiladas in a 9x13 casserole — green chile sauce, melted cheese, and egg-chorizo filling in rolled tortillas",
    publishedAt: now,
    updatedAt: now,
    readMinutes: 9,
    seoTitle: "Breakfast Enchiladas for the Crew | Firehall Breakfast",
  },
  {
    slug: "breakfast-crunchwraps",
    title: "Breakfast Crunchwraps",
    subtitle: "Griddled tortilla bundles with eggs, hash, and a crunchy tostada center.",
    description:
      "Inspired by the drive-through classic but built for ten hungry firefighters. Each crunchwrap stacks eggs, sausage, cheese, and a crisp tostada inside a large flour tortilla, folded hex-style and griddled until golden and structurally sound.",
    filters: ["breakfast_sandwiches", "high_protein", "quick_breakfasts"],
    tags: ["crunchwrap", "handheld", "griddle", "sausage", "eggs"],
    crewSize: 10,
    baseServings: 10,
    prepTime: 20,
    cookTime: 25,
    totalTime: 45,
    difficulty: "medium",
    ingredients: [
      { group: "Fillings", quantity: "14", name: "large eggs", notes: "scrambled soft" },
      { group: "Fillings", quantity: "1 1/2 lb", name: "breakfast sausage", notes: "browned and crumbled" },
      { group: "Fillings", quantity: "3 cups", name: "frozen hash browns", notes: "crisped on the griddle" },
      { group: "Fillings", quantity: "2 cups", name: "shredded cheddar", notes: "plus slices for sealing" },
      { group: "Build", quantity: "10", name: "12-inch flour tortillas", notes: "burrito size" },
      { group: "Build", quantity: "10", name: "6-inch tostada shells", notes: "or crisp fried corn tortillas" },
      { group: "Build", quantity: "1 cup", name: "nacho cheese sauce", notes: "warm, not boiling" },
      { group: "Finish", quantity: "1/2 cup", name: "sour cream", notes: "and salsa for the line" },
    ],
    steps: [
      { stepNumber: 1, title: "Prep all fillings", minutes: 15, instruction: "Crisp hash browns on a lightly oiled griddle in a thin layer, season with salt, and hold warm. Brown sausage and drain. Soft-scramble eggs last so they stay tender." },
      { stepNumber: 2, title: "Set the build station", minutes: 5, instruction: "Lay out tortillas, tostadas, cheese sauce, and a small bowl of cheese slices cut to seal the bottom fold. Warm nacho cheese so it spreads without tearing tortillas." },
      { stepNumber: 3, title: "Stack and fold", minutes: 12, instruction: "Center tostada on tortilla, layer hash, sausage, eggs, cheddar, and a drizzle of nacho cheese. Fold edges to center in a hex pattern; place a cheese slice on the bottom seam to glue it shut." },
      { stepNumber: 4, title: "Griddle both sides", minutes: 10, instruction: "Cook seam-side down on a medium griddle with a light press until golden and sealed, 3–4 minutes. Flip carefully and griddle the top until crisp and cheese melts through." },
      { stepNumber: 5, title: "Serve immediately", minutes: 0, instruction: "Cut in half on a bias for the line or serve whole in parchment wraps. Hold finished wraps in a 200°F oven seam-side down—don't stack or you'll lose the crunch." },
    ],
    stationWorkflow: [
      "One cook runs the griddle press while another builds—pre-cut all seal cheese slices before the rush.",
      "Keep tostadas in a warm dry pan so they stay shatter-crisp until the moment of assembly.",
      "Build in batches of four; griddle while the next batch stacks so nothing sits and steams.",
    ],
    cleanupNotes: [
      "Scrape the griddle between batches with a bench scraper while still warm to prevent cheese carbon buildup.",
      "Wipe the press or second skillet with a damp towel held by tongs—never submerge hot cast iron.",
    ],
    leftovers: [
      "Crunchwraps do not hold well; plan portions tightly and turn extras into deconstructed bowls with salsa.",
      "If you must reheat, use a dry skillet over low heat with a lid—microwave destroys the tostada crunch.",
    ],
    heroImage: hero("breakfast-crunchwraps"),
    thumbImage: thumb("breakfast-crunchwraps"),
    imageAlt: "Golden griddled breakfast crunchwraps cut in half showing layers of egg and hash",
    publishedAt: now,
    updatedAt: now,
    readMinutes: 8,
    seoTitle: "Breakfast Crunchwraps | Firehall Breakfast",
  },
  {
    slug: "denver-breakfast-casserole",
    title: "Denver Breakfast Casserole",
    subtitle: "Ham, bell peppers, and onion baked into a make-ahead egg strata.",
    description:
      "Classic Denver omelette flavors in a 9x13 bake: diced ham, peppers, and onion folded through cubed bread and an egg-milk custard. Assembles the night before for an easy oven push on busy mornings.",
    filters: ["feed_a_crew", "high_protein"],
    tags: ["casserole", "ham", "peppers", "make-ahead", "strata"],
    crewSize: 12,
    baseServings: 12,
    prepTime: 25,
    cookTime: 45,
    totalTime: 70,
    difficulty: "easy",
    ingredients: [
      { group: "Base", quantity: "18", name: "large eggs" },
      { group: "Base", quantity: "3 cups", name: "whole milk", notes: "or half-and-half for richer custard" },
      { group: "Base", quantity: "1 loaf", name: "day-old bread", notes: "cubed and lightly toasted" },
      { group: "Fillings", quantity: "2 lb", name: "diced ham", notes: "deli or leftover spiral ham" },
      { group: "Fillings", quantity: "2", name: "bell peppers", notes: "diced, any color" },
      { group: "Fillings", quantity: "1", name: "large onion", notes: "diced and lightly sautéed" },
      { group: "Fillings", quantity: "3 cups", name: "shredded cheddar", notes: "divided" },
      { group: "Seasoning", quantity: "1 1/2 tsp", name: "dry mustard", notes: "plus salt, pepper, and paprika" },
    ],
    steps: [
      { stepNumber: 1, title: "Toast the bread cubes", tempF: 350, minutes: 8, instruction: "Heat oven to 350°F. Spread bread cubes on a sheet pan and toast 6–8 minutes until dry at the edges. Cool slightly so they don't turn the custard soggy." },
      { stepNumber: 2, title: "Build the pan", minutes: 12, instruction: "Butter a deep 9x13 dish. Layer half the bread, ham, peppers, onion, and half the cheese. Repeat layers, finishing with cheese on top." },
      { stepNumber: 3, title: "Whisk the custard", minutes: 5, instruction: "Whisk eggs with milk, dry mustard, salt, pepper, and a pinch of paprika until smooth. Pour evenly over the bread—press gently so cubes soak without compacting." },
      { stepNumber: 4, title: "Rest or refrigerate", minutes: 30, instruction: "Rest 30 minutes at room temperature, or cover and refrigerate overnight for a true make-ahead. Bring closer to room temp before baking if chilled." },
      { stepNumber: 5, title: "Bake until set", tempF: 375, minutes: 40, instruction: "Bake at 375°F until puffed, golden at the edges, and a knife inserted in the center comes out clean. Rest 10 minutes before cutting into squares for the line." },
    ],
    stationWorkflow: [
      "Prep and refrigerate the casserole the night before a busy shift; pull it 30 minutes before baking.",
      "Assign one cook to oven checks while another sets up a warm holding pan with foil for staggered eaters.",
      "Cut with a sharp serrated knife in the pan, then lift squares with a offset spatula to keep layers intact.",
    ],
    cleanupNotes: [
      "Soak the 9x13 in warm soapy water immediately after serving—egg custard bonds to metal if left to dry.",
      "Line the sheet pan with parchment when toasting bread cubes for a one-wipe cleanup.",
    ],
    leftovers: [
      "Wrap individual squares in foil and reheat at 325°F for 12 minutes until steaming in the center.",
      "Dice cold casserole into a breakfast fried rice with soy, green onion, and a fried egg on top.",
    ],
    heroImage: hero("denver-breakfast-casserole"),
    thumbImage: thumb("denver-breakfast-casserole"),
    imageAlt: "Golden Denver breakfast casserole squares with ham and bell peppers",
    publishedAt: now,
    updatedAt: now,
    readMinutes: 8,
    seoTitle: "Denver Breakfast Casserole | Firehall Breakfast",
  },
  {
    slug: "breakfast-sliders",
    title: "Breakfast Sliders",
    subtitle: "Mini sandwiches with sausage, egg, and maple glaze baked on one tray.",
    description:
      "A full sheet pan of sweet Hawaiian rolls stuffed with sausage patties, folded eggs, and cheddar, brushed with maple-butter and baked until the tops turn glossy. Pull-apart portions feed a crew fast without a griddle bottleneck.",
    filters: ["breakfast_sandwiches", "feed_a_crew", "quick_breakfasts"],
    tags: ["sliders", "sheet-pan", "sausage", "maple", "handheld"],
    crewSize: 10,
    baseServings: 10,
    prepTime: 18,
    cookTime: 22,
    totalTime: 40,
    difficulty: "easy",
    ingredients: [
      { group: "Build", quantity: "2", name: "packages Hawaiian sweet rolls", notes: "24 rolls total, connected" },
      { group: "Protein", quantity: "12", name: "breakfast sausage patties", notes: "pre-cooked or thin frozen" },
      { group: "Protein", quantity: "12", name: "large eggs", notes: "folded into thin sheets on the griddle" },
      { group: "Protein", quantity: "12 slices", name: "cheddar cheese", notes: "cut to fit rolls" },
      { group: "Glaze", quantity: "1/2 cup", name: "butter", notes: "melted" },
      { group: "Glaze", quantity: "3 tbsp", name: "maple syrup", notes: "plus extra for drizzling" },
      { group: "Glaze", quantity: "1 tsp", name: "Dijon mustard", notes: "whisked into glaze" },
      { group: "Finish", quantity: "1 tbsp", name: "everything bagel seasoning", notes: "optional crunch on top" },
    ],
    steps: [
      { stepNumber: 1, title: "Heat the oven", tempF: 350, minutes: 0, instruction: "Heat oven to 350°F. Line a rimmed sheet pan with parchment. Cook sausage patties until done and fold eggs into thin rectangles roughly the size of each roll." },
      { stepNumber: 2, title: "Slice the roll block", minutes: 5, instruction: "Without separating individual rolls, slice the connected block horizontally into tops and bottoms. Keep the shape intact so assembly stays fast." },
      { stepNumber: 3, title: "Layer the sliders", minutes: 10, instruction: "Place bottom halves on the pan. Add sausage, egg, and cheese to each roll. Cap with tops and press gently so stacks stay level." },
      { stepNumber: 4, title: "Glaze and bake", tempF: 350, minutes: 18, instruction: "Whisk melted butter, maple syrup, and Dijon. Brush generously over roll tops. Bake until cheese melts and tops turn golden and sticky." },
      { stepNumber: 5, title: "Rest and pull apart", minutes: 5, instruction: "Rest 5 minutes, then cut along roll seams with a sharp knife or bench scraper. Serve warm from the pan or transfer to a baking dish for the line." },
    ],
    stationWorkflow: [
      "Cook all sausage and egg sheets before touching the rolls—cold protein slows the bake and steams the bread.",
      "Brush glaze right before the oven; a second light brush at the 10-minute mark adds shine without sogginess.",
      "Cut and serve from the sheet pan at the line so the crew pulls their own portion without a bottleneck.",
    ],
    cleanupNotes: [
      "Discard parchment with stuck glaze rather than scraping—it saves time on a busy morning cleanup.",
      "Soak the griddle used for egg sheets immediately; folded egg residue hardens fast once cooled.",
    ],
    leftovers: [
      "Wrap sliders individually in foil and reheat at 325°F for 10 minutes; add a fresh glaze drizzle after warming.",
      "Split leftover sliders and griddle cut-side down for a crisp second-day breakfast with extra maple on top.",
    ],
    heroImage: hero("breakfast-sliders"),
    thumbImage: thumb("breakfast-sliders"),
    imageAlt: "Sheet pan of maple-glazed breakfast sliders with sausage, egg, and cheese",
    publishedAt: now,
    updatedAt: now,
    readMinutes: 7,
    seoTitle: "Breakfast Sliders | Firehall Breakfast",
  },
  {
    slug: "breakfast-quesadillas",
    title: "Breakfast Quesadillas",
    subtitle: "Crisp flour tortillas packed with eggs, bacon, and pepper jack.",
    description:
      "Griddled quesadillas cut into wedges feed eight fast without plates full of crumbs. Scrambled eggs, crisp bacon, and pepper jack get pressed between flour tortillas until shatter-crisp outside and molten inside.",
    filters: ["quick_breakfasts", "high_protein", "breakfast_sandwiches"],
    tags: ["quesadillas", "bacon", "pepper-jack", "griddle", "handheld"],
    crewSize: 8,
    baseServings: 8,
    prepTime: 15,
    cookTime: 20,
    totalTime: 35,
    difficulty: "easy",
    ingredients: [
      { group: "Fillings", quantity: "12", name: "large eggs", notes: "soft-scrambled" },
      { group: "Fillings", quantity: "1 lb", name: "bacon", notes: "cooked crisp and crumbled" },
      { group: "Fillings", quantity: "2 cups", name: "shredded pepper jack", notes: "plus extra for sealing edges" },
      { group: "Fillings", quantity: "1/2 cup", name: "pico de gallo", notes: "drained well" },
      { group: "Build", quantity: "8", name: "10-inch flour tortillas", notes: "burrito size" },
      { group: "Build", quantity: "2 tbsp", name: "butter", notes: "or oil for griddling" },
      { group: "Serve", quantity: "1 cup", name: "sour cream", notes: "and salsa verde at the line" },
      { group: "Serve", quantity: "1/4 cup", name: "fresh cilantro", notes: "chopped, optional" },
    ],
    steps: [
      { stepNumber: 1, title: "Prep the fillings", minutes: 12, instruction: "Cook bacon until crisp, drain, and crumble. Soft-scramble eggs over medium-low heat—they should still look glossy. Drain pico well so quesadillas don't steam and split." },
      { stepNumber: 2, title: "Build on half the tortilla", minutes: 8, instruction: "On one half of each tortilla, layer cheese, eggs, bacon, a spoon of pico, and more cheese. Fold over and press gently to compact without tearing." },
      { stepNumber: 3, title: "Griddle until golden", minutes: 10, instruction: "Heat a large griddle or skillet over medium with butter. Cook quesadillas 3–4 minutes per side with a spatula press until deeply golden and cheese melts through." },
      { stepNumber: 4, title: "Hold and cut", minutes: 5, instruction: "Transfer to a cutting board and rest 2 minutes so cheese sets. Cut each into 3 wedges with a sharp knife or pizza wheel. Hold warm on a sheet pan at 200°F." },
      { stepNumber: 5, title: "Serve with dips", minutes: 0, instruction: "Serve wedges with sour cream and salsa verde at the line. Keep crispy wedges uncovered; cover only if holding longer than 15 minutes." },
    ],
    stationWorkflow: [
      "Griddle two quesadillas at a time while a second cook builds the next pair—never stack uncooked folds.",
      "Use a flat press or second spatula to maximize crust contact; pale quesadillas mean cold centers.",
      "Cut on a dedicated board and slide wedges directly into a warm baking dish for self-serve.",
    ],
    cleanupNotes: [
      "Wipe the griddle between batches with a damp towel and tongs to prevent burnt cheese buildup.",
      "Drain pico through a fine mesh strainer over a bowl—wet salsa is the number-one cause of soggy quesadillas.",
    ],
    leftovers: [
      "Reheat wedges in a dry skillet over medium-low with a lid until cheese remelts—microwave makes them rubbery.",
      "Chop leftover wedges into a breakfast nacho topping with extra cheese and pickled jalapeños.",
    ],
    heroImage: hero("breakfast-quesadillas"),
    thumbImage: thumb("breakfast-quesadillas"),
    imageAlt: "Crisp breakfast quesadilla wedges with bacon, eggs, and melted pepper jack",
    publishedAt: now,
    updatedAt: now,
    readMinutes: 7,
    seoTitle: "Breakfast Quesadillas | Firehall Breakfast",
  },
  {
    slug: "protein-french-toast",
    title: "Protein French Toast",
    subtitle: "Cottage cheese and egg batter for a high-protein griddle classic.",
    description:
      "Blended cottage cheese in the custard adds protein without chalky protein powder. Thick-cut bread soaks briefly, griddles to a crisp shell, and serves with berries and maple for a crew that wants comfort food with staying power.",
    filters: ["high_protein", "healthy_breakfasts", "feed_a_crew"],
    tags: ["french-toast", "cottage-cheese", "griddle", "berries", "maple"],
    crewSize: 8,
    baseServings: 8,
    prepTime: 15,
    cookTime: 20,
    totalTime: 35,
    difficulty: "easy",
    ingredients: [
      { group: "Batter", quantity: "12", name: "large eggs" },
      { group: "Batter", quantity: "2 cups", name: "cottage cheese", notes: "blended smooth" },
      { group: "Batter", quantity: "1 cup", name: "whole milk", notes: "plus 1 tsp vanilla and pinch of cinnamon" },
      { group: "Batter", quantity: "2 tbsp", name: "maple syrup", notes: "in batter, more for serving" },
      { group: "Bread", quantity: "16", name: "thick-cut bread slices", notes: "brioche or Texas toast" },
      { group: "Cook", quantity: "3 tbsp", name: "butter", notes: "for griddling in batches" },
      { group: "Serve", quantity: "2 cups", name: "mixed berries", notes: "fresh or thawed and drained" },
      { group: "Serve", quantity: "1/2 cup", name: "Greek yogurt", notes: "optional dollop at the line" },
    ],
    steps: [
      { stepNumber: 1, title: "Blend the batter", minutes: 5, instruction: "Blend cottage cheese, eggs, milk, vanilla, cinnamon, and maple until completely smooth—no curds. Pour into a shallow baking dish for fast dipping." },
      { stepNumber: 2, title: "Heat the griddle", minutes: 3, instruction: "Heat a large griddle or cast iron over medium. Add butter until foaming but not brown. Work in batches so slices aren't crowded." },
      { stepNumber: 3, title: "Soak and griddle", minutes: 15, instruction: "Dip bread 3–4 seconds per side—don't oversaturate or centers stay raw. Griddle 3 minutes per side until deep golden and custard sets; adjust heat if browning too fast." },
      { stepNumber: 4, title: "Hold warm", minutes: 0, instruction: "Transfer finished slices to a wire rack on a sheet pan in a 200°F oven. Uncovered keeps the crust; cover only if holding longer than 20 minutes." },
      { stepNumber: 5, title: "Plate and serve", minutes: 5, instruction: "Stack two slices per plate, top with berries and a drizzle of maple. Offer Greek yogurt for extra protein without slowing the line." },
    ],
    stationWorkflow: [
      "Blend batter first and keep the dip pan shallow so slices don't over-soak during rush assembly.",
      "One cook griddles while another plates berries and maple—sync batches to two slices per firefighter.",
      "Use a wire rack for holding; stacking hot French toast steams the crust soft before service.",
    ],
    cleanupNotes: [
      "Rinse the blender immediately with warm water before cottage cheese dries on the blade assembly.",
      "Scrape the griddle while warm with a bench scraper, then wipe with a butter-damp towel.",
    ],
    leftovers: [
      "Reheat slices on a sheet pan at 325°F for 8 minutes directly on the rack for a crisp re-crisp.",
      "Chop cold slices into a bread pudding base with extra eggs, milk, and raisins for tomorrow's bake.",
    ],
    heroImage: hero("protein-french-toast"),
    thumbImage: thumb("protein-french-toast"),
    imageAlt: "Golden protein French toast stacks with fresh berries and maple drizzle",
    publishedAt: now,
    updatedAt: now,
    readMinutes: 7,
    seoTitle: "Protein French Toast | Firehall Breakfast",
  },
  {
    slug: "breakfast-poutine",
    title: "Breakfast Poutine",
    subtitle: "Crispy fries under peppery gravy, cheese curds, and fried eggs.",
    description:
      "Canadian comfort meets the firehall: oven-roasted fries or frozen fries crisped hard, topped with peppery sausage gravy, squeaky cheese curds, and sunny-side eggs. Built on sheet pans for fast assembly when the crew wants indulgent recovery food.",
    filters: ["feed_a_crew", "high_protein", "skillets"],
    tags: ["poutine", "fries", "gravy", "eggs", "indulgent"],
    crewSize: 10,
    baseServings: 10,
    prepTime: 15,
    cookTime: 30,
    totalTime: 45,
    difficulty: "medium",
    ingredients: [
      { group: "Base", quantity: "4 lb", name: "frozen straight-cut fries", notes: "or hand-cut russets" },
      { group: "Base", quantity: "2 tbsp", name: "vegetable oil", notes: "for roasting" },
      { group: "Gravy", quantity: "1 lb", name: "breakfast sausage", notes: "browned for gravy" },
      { group: "Gravy", quantity: "1/4 cup", name: "all-purpose flour", notes: "whisked into sausage fat" },
      { group: "Gravy", quantity: "3 cups", name: "whole milk", notes: "plus salt and black pepper" },
      { group: "Toppings", quantity: "12", name: "large eggs", notes: "fried sunny-side up" },
      { group: "Toppings", quantity: "1 1/2 lb", name: "cheese curds", notes: "or cubed mozzarella if curds unavailable" },
      { group: "Finish", quantity: "1/4 cup", name: "green onions", notes: "sliced, and hot sauce at the line" },
    ],
    steps: [
      { stepNumber: 1, title: "Crisp the fries", tempF: 425, minutes: 25, instruction: "Heat oven to 425°F. Spread fries on sheet pans in a single layer with oil and salt. Roast until deeply golden and crisp—soft fries kill poutine." },
      { stepNumber: 2, title: "Make sausage gravy", minutes: 10, instruction: "Brown sausage, sprinkle flour over the fat, and cook 1 minute. Whisk in milk gradually, simmer until thick enough to coat a spoon. Season aggressively with black pepper." },
      { stepNumber: 3, title: "Fry the eggs", minutes: 8, instruction: "Fry eggs sunny-side up in batches with crisp edges on the whites. Hold on a warm tray—yolks should stay runny for the full poutine experience." },
      { stepNumber: 4, title: "Assemble on trays", minutes: 5, instruction: "Pile hot fries on baking dishes or plates. Scatter cheese curds, ladle hot gravy to partially melt them, then crown each portion with a fried egg." },
      { stepNumber: 5, title: "Serve immediately", minutes: 0, instruction: "Finish with green onion and hot sauce at the line. Poutine waits for no one—serve the moment eggs hit the fries." },
    ],
    stationWorkflow: [
      "Roast fries first and hold in a warm oven uncovered so they stay crisp until gravy hits.",
      "Make gravy in a wide skillet so it stays hot and pourable—reheat with a splash of milk if it tightens.",
      "Fry eggs last in sync with gravy ladle—one cook assembles while another keeps the egg pan moving.",
    ],
    cleanupNotes: [
      "Degrease sheet pans with hot water and a splash of vinegar before scrubbing starch and oil residue.",
      "Scrape the gravy skillet while warm; flour-milk paste sets like concrete once cooled.",
    ],
    leftovers: [
      "Poutine does not reheat well; plan portions tightly and repurpose extra fries into a breakfast hash.",
      "Leftover gravy reheats smoothly with milk over low heat—serve over biscuits the next morning.",
    ],
    heroImage: hero("breakfast-poutine"),
    thumbImage: thumb("breakfast-poutine"),
    imageAlt: "Breakfast poutine with crispy fries, sausage gravy, cheese curds, and fried egg",
    publishedAt: now,
    updatedAt: now,
    readMinutes: 8,
    seoTitle: "Breakfast Poutine | Firehall Breakfast",
  },
  {
    slug: "monte-cristo-sandwiches",
    title: "Monte Cristo Sandwiches",
    subtitle: "Ham and turkey dipped in egg batter, griddled, and dusted with powdered sugar.",
    description:
      "Sweet-savory club sandwiches dipped in custard and griddled until golden, then finished with powdered sugar and jam. A special-occasion breakfast that feels like diner food but scales to ten with an assembly-line griddle setup.",
    filters: ["breakfast_sandwiches", "feed_a_crew"],
    tags: ["monte-cristo", "ham", "turkey", "griddle", "diner"],
    crewSize: 10,
    baseServings: 10,
    prepTime: 20,
    cookTime: 25,
    totalTime: 45,
    difficulty: "medium",
    ingredients: [
      { group: "Sandwich", quantity: "20", name: "thick white bread slices", notes: "crusts trimmed optional" },
      { group: "Sandwich", quantity: "1 lb", name: "sliced deli ham" },
      { group: "Sandwich", quantity: "1 lb", name: "sliced deli turkey" },
      { group: "Sandwich", quantity: "10 slices", name: "Swiss cheese" },
      { group: "Sandwich", quantity: "3 tbsp", name: "Dijon mustard", notes: "spread thin on half the slices" },
      { group: "Batter", quantity: "6", name: "large eggs", notes: "whisked with 1 cup milk and pinch of salt" },
      { group: "Cook", quantity: "4 tbsp", name: "butter", notes: "for griddling in batches" },
      { group: "Finish", quantity: "1/4 cup", name: "powdered sugar", notes: "plus raspberry jam for dipping" },
    ],
    steps: [
      { stepNumber: 1, title: "Build the sandwiches", minutes: 12, instruction: "Layer ham, turkey, and Swiss between bread slices with a thin smear of Dijon. Press gently and set aside while the griddle heats." },
      { stepNumber: 2, title: "Set the dip station", minutes: 3, instruction: "Whisk eggs and milk in a shallow pan wide enough to fit a sandwich. Heat a large griddle over medium and melt butter until foaming." },
      { stepNumber: 3, title: "Dip and griddle", minutes: 18, instruction: "Dip each sandwich briefly in egg batter—don't soak or bread falls apart. Griddle 3–4 minutes per side until deep golden and cheese melts." },
      { stepNumber: 4, title: "Hold and slice", minutes: 5, instruction: "Transfer to a wire rack in a 200°F oven between batches. Slice diagonally before serving so jam dipping is easier." },
      { stepNumber: 5, title: "Dust and serve", minutes: 3, instruction: "Dust lightly with powdered sugar through a fine sieve—go easy so it doesn't clump. Serve with warm raspberry jam for dipping at the line." },
    ],
    stationWorkflow: [
      "Build all sandwiches before dipping so the griddle never waits for assembly mid-batch.",
      "Keep batter shallow and replace when it gets thick with bread crumbs for clean dips.",
      "Dust sugar at the line, not in the oven—steam makes powdered sugar disappear on held sandwiches.",
    ],
    cleanupNotes: [
      "Wipe the griddle between batches to prevent burnt egg batter from scorching the next sandwich.",
      "Wash the dip pan immediately; egg-milk residue glues to stainless once it dries.",
    ],
    leftovers: [
      "Reheat sliced halves on a dry griddle over medium-low until cheese remelts and crust re-crisp.",
      "Turn leftover halves into a savory bread pudding by cubing, adding custard, and baking at 350°F.",
    ],
    heroImage: hero("monte-cristo-sandwiches"),
    thumbImage: thumb("monte-cristo-sandwiches"),
    imageAlt: "Golden Monte Cristo sandwiches dusted with powdered sugar and served with jam",
    publishedAt: now,
    updatedAt: now,
    readMinutes: 8,
    seoTitle: "Monte Cristo Sandwiches | Firehall Breakfast",
  },
  {
    slug: "apple-cinnamon-baked-oatmeal",
    title: "Apple Cinnamon Baked Oatmeal",
    subtitle: "Warm spiced oat squares with tender apple chunks for easy portioning.",
    description:
      "Steel-cut and rolled oats bake with diced apples, cinnamon, and brown sugar into sliceable squares—more satisfying than instant packets and easier to serve than stovetop porridge for ten. Holds warm in the oven between waves of eaters.",
    filters: ["healthy_breakfasts", "feed_a_crew"],
    tags: ["oatmeal", "apple", "cinnamon", "bake", "make-ahead"],
    crewSize: 10,
    baseServings: 10,
    prepTime: 15,
    cookTime: 40,
    totalTime: 55,
    difficulty: "easy",
    ingredients: [
      { group: "Base", quantity: "3 cups", name: "rolled oats", notes: "old-fashioned, not instant" },
      { group: "Base", quantity: "1 cup", name: "steel-cut oats", notes: "adds texture; optional" },
      { group: "Base", quantity: "4 cups", name: "whole milk", notes: "or oat milk for dairy-free" },
      { group: "Base", quantity: "2", name: "large eggs", notes: "whisked in for structure" },
      { group: "Fruit", quantity: "3", name: "large apples", notes: "peeled, cored, diced" },
      { group: "Spice", quantity: "2 tsp", name: "ground cinnamon", notes: "plus 1/2 tsp nutmeg" },
      { group: "Sweet", quantity: "1/2 cup", name: "brown sugar", notes: "plus maple for serving" },
      { group: "Finish", quantity: "1/2 cup", name: "chopped walnuts", notes: "and butter pats at the line" },
    ],
    steps: [
      { stepNumber: 1, title: "Heat the oven", tempF: 375, minutes: 0, instruction: "Heat oven to 375°F. Grease a 9x13 baking dish. Toss diced apples with half the cinnamon and spread in the bottom of the dish." },
      { stepNumber: 2, title: "Mix the oat base", minutes: 8, instruction: "Whisk oats, milk, eggs, brown sugar, remaining cinnamon, nutmeg, and a pinch of salt until combined. The mixture should look like thick pourable batter." },
      { stepNumber: 3, title: "Pour and top", minutes: 3, instruction: "Pour oat mixture over apples and scatter walnuts on top. Tap the dish to settle the batter evenly for uniform slices." },
      { stepNumber: 4, title: "Bake until set", tempF: 375, minutes: 38, instruction: "Bake until the center is set, edges are golden, and a knife inserted in the middle comes out clean. The top should spring back lightly when pressed." },
      { stepNumber: 5, title: "Rest and portion", minutes: 10, instruction: "Rest 10 minutes before cutting into squares. Serve warm with maple syrup and optional butter pats. Hold uncovered at 200°F for up to 30 minutes." },
    ],
    stationWorkflow: [
      "Dice apples and mix batter while the oven preheats—this bake is forgiving on timing.",
      "Cut squares in the pan with a sharp knife wiped between cuts for clean portions.",
      "Set maple and walnuts at the line so customization doesn't bottleneck the hot squares.",
    ],
    cleanupNotes: [
      "Soak the 9x13 in warm water immediately—baked oatmeal cement is easier to release when warm.",
      "Line the prep bowl with a thin film of oil before mixing sticky oat batter for faster cleanup.",
    ],
    leftovers: [
      "Wrap squares individually and reheat at 325°F for 10 minutes with a splash of milk on top.",
      "Crumble cold squares into a skillet with butter and pan-fry until crisp for oatmeal hash browns.",
    ],
    heroImage: hero("apple-cinnamon-baked-oatmeal"),
    thumbImage: thumb("apple-cinnamon-baked-oatmeal"),
    imageAlt: "Baked apple cinnamon oatmeal squares with walnuts and maple drizzle",
    publishedAt: now,
    updatedAt: now,
    readMinutes: 7,
    seoTitle: "Apple Cinnamon Baked Oatmeal | Firehall Breakfast",
  },
  {
    slug: "cowboy-breakfast-skillet",
    title: "Cowboy Breakfast Skillet",
    subtitle: "Smoky beans, crispy potatoes, and eggs in one cast-iron pan.",
    description:
      "A hearty Southwest-style skillet with ranch beans, chorizo-spiked potatoes, and eggs cracked over the top. One pan feeds eight with big flavor and minimal dishware—perfect when the crew wants something stick-to-your-ribs after outdoor training.",
    filters: ["skillets", "bbq_breakfast", "feed_a_crew"],
    tags: ["cowboy", "beans", "chorizo", "cast-iron", "southwest"],
    crewSize: 8,
    baseServings: 8,
    prepTime: 15,
    cookTime: 28,
    totalTime: 43,
    difficulty: "easy",
    ingredients: [
      { group: "Base", quantity: "3.5 lb", name: "Yukon gold potatoes", notes: "diced and par-cooked" },
      { group: "Protein", quantity: "1 lb", name: "Mexican chorizo", notes: "casings removed" },
      { group: "Protein", quantity: "14", name: "large eggs" },
      { group: "Beans", quantity: "2", name: "15-oz cans ranch-style beans", notes: "drained slightly, not rinsed" },
      { group: "Veg", quantity: "1", name: "large onion", notes: "diced" },
      { group: "Veg", quantity: "2", name: "jalapeños", notes: "sliced, seeds optional" },
      { group: "Seasoning", quantity: "2 tsp", name: "chili powder", notes: "plus salt, pepper, and cumin" },
      { group: "Finish", quantity: "1 1/2 cups", name: "shredded cheddar", notes: "and chopped cilantro" },
    ],
    steps: [
      { stepNumber: 1, title: "Par-cook potatoes", minutes: 8, instruction: "Microwave diced potatoes with water until just tender, drain, and pat dry. This shortens cast-iron time and guarantees creamy centers with crisp edges." },
      { stepNumber: 2, title: "Brown chorizo and veg", minutes: 10, instruction: "In a large cast iron over medium-high, cook chorizo until rendered. Add onion and jalapeño; cook until softened. Fold in potatoes and chili powder until edges crisp." },
      { stepNumber: 3, title: "Add beans", minutes: 5, instruction: "Stir in ranch beans with a splash of their liquid for saucy consistency. Simmer 3 minutes until the bottom of the skillet looks lightly glazed, not soupy." },
      { stepNumber: 4, title: "Eggs and cheese", minutes: 8, instruction: "Make wells in the mixture and crack eggs into each. Cover over medium-low heat until egg whites are fully set (165°F) and yolks are jammy. Scatter cheddar over the top and cover 60 seconds to melt." },
      { stepNumber: 5, title: "Serve from the pan", minutes: 0, instruction: "Garnish with cilantro and serve straight from the skillet family-style, or scoop portions onto warm plates. Keep extra hot sauce at the line." },
    ],
    stationWorkflow: [
      "Use two cast-iron skillets if feeding more than eight—split potatoes and chorizo evenly between pans.",
      "Cover with a sheet pan lid if your skillet lacks a cover—steam sets egg whites faster on a loud morning.",
      "Serve beans-on-the-bottom portions first; the top stays crisp longest for second-pass eaters.",
    ],
    cleanupNotes: [
      "Deglaze cast iron with hot water while warm, then scrape—bean sugars stick if left overnight.",
      "Wipe jalapeño boards and knives immediately and wash hands before touching faces or eyes.",
    ],
    leftovers: [
      "Reheat in cast iron over medium with a lid, adding a splash of water to loosen beans before eggs re-crisp.",
      "Mash leftovers into breakfast burrito filling with extra cheese and hot sauce for handheld service.",
    ],
    heroImage: hero("cowboy-breakfast-skillet"),
    thumbImage: thumb("cowboy-breakfast-skillet"),
    imageAlt: "Cowboy breakfast skillet with chorizo, ranch beans, potatoes, and baked eggs",
    publishedAt: now,
    updatedAt: now,
    readMinutes: 7,
    seoTitle: "Cowboy Breakfast Skillet | Firehall Breakfast",
  },
  {
    slug: "hall-breakfast-wraps",
    title: "Hall Breakfast Wraps",
    subtitle: "Soft flour wraps rolled with eggs, turkey sausage, and spinach.",
    description:
      "A lighter handheld option that still feeds ten: whole-wheat wraps stuffed with scrambled eggs, lean turkey sausage, sautéed spinach, and feta. Rolls tight, cuts in half on the bias, and holds in foil for eaters heading out on early rigs.",
    filters: ["healthy_breakfasts", "quick_breakfasts", "high_protein"],
    tags: ["wraps", "turkey", "spinach", "handheld", "make-ahead"],
    crewSize: 10,
    baseServings: 10,
    prepTime: 18,
    cookTime: 15,
    totalTime: 33,
    difficulty: "easy",
    ingredients: [
      { group: "Fillings", quantity: "16", name: "large eggs", notes: "soft-scrambled" },
      { group: "Fillings", quantity: "1 1/2 lb", name: "lean turkey breakfast sausage", notes: "browned and crumbled" },
      { group: "Fillings", quantity: "10 oz", name: "baby spinach", notes: "wilted and squeezed dry" },
      { group: "Fillings", quantity: "1 cup", name: "crumbled feta", notes: "or goat cheese" },
      { group: "Build", quantity: "10", name: "10-inch whole-wheat tortillas", notes: "warmed" },
      { group: "Build", quantity: "1/2 cup", name: "salsa verde", notes: "drained, spread thin" },
      { group: "Build", quantity: "1", name: "avocado", notes: "sliced, optional" },
      { group: "Hold", quantity: "10 sheets", name: "foil", notes: "for wrapping to-go portions" },
    ],
    steps: [
      { stepNumber: 1, title: "Cook the components", minutes: 12, instruction: "Brown turkey sausage and drain. Wilt spinach in the same pan, squeeze dry in a towel. Soft-scramble eggs over low heat—they should still look glossy when done." },
      { stepNumber: 2, title: "Warm tortillas", minutes: 3, instruction: "Heat tortillas in a dry skillet or wrapped in foil at 300°F until pliable. Stiff tortillas tear when rolled tight." },
      { stepNumber: 3, title: "Build each wrap", minutes: 10, instruction: "Spread a thin line of salsa verde on each tortilla. Layer eggs, sausage, spinach, feta, and optional avocado off-center. Roll tight, tucking sides as you go." },
      { stepNumber: 4, title: "Cut and wrap", minutes: 5, instruction: "Cut each wrap in half on the bias with a sharp knife. Wrap halves in foil for grab-and-go or arrange cut-side up on a tray for dine-in." },
      { stepNumber: 5, title: "Hold and serve", minutes: 0, instruction: "Hold wrapped portions in a 200°F oven up to 20 minutes. Serve with extra salsa and hot sauce at the line for self-serve heat." },
    ],
    stationWorkflow: [
      "Squeeze spinach thoroughly—wet greens turn wraps soggy within minutes on the holding rack.",
      "Roll on a flat cutting board with tortillas oriented like a burrito, not a fajita fold.",
      "Cut with a serrated knife using a gentle saw motion so fillings don't get pushed out the ends.",
    ],
    cleanupNotes: [
      "Rinse the spinach skillet while warm to prevent green film from baking onto stainless.",
      "Collect foil wrappers in a dedicated bin during service so cleanup doesn't scatter across the hall.",
    ],
    leftovers: [
      "Reheat foil-wrapped halves at 325°F for 12 minutes—open foil last 3 minutes to refresh the tortilla.",
      "Chop leftover wraps into a scramble with extra eggs and hot sauce for a second-pass skillet.",
    ],
    heroImage: hero("hall-breakfast-wraps"),
    thumbImage: thumb("hall-breakfast-wraps"),
    imageAlt: "Hall breakfast wraps cut in half showing eggs, turkey sausage, and spinach",
    publishedAt: now,
    updatedAt: now,
    readMinutes: 7,
    seoTitle: "Hall Breakfast Wraps | Firehall Breakfast",
  },
  {
    slug: "sheet-pan-breakfast-sandwiches",
    title: "Sheet Pan Breakfast Sandwiches",
    subtitle: "A dozen eggs and cheese baked between two layers of slider rolls.",
    description:
      "One sheet-pan hack produces twelve breakfast sandwiches at once: eggs baked in a parchment frame, layered with cheese and sausage on slider rolls, then topped and baked again. Cut along seams and serve—no griddle bottleneck on busy mornings.",
    filters: ["breakfast_sandwiches", "feed_a_crew", "quick_breakfasts"],
    tags: ["sheet-pan", "sliders", "eggs", "sausage", "batch-cook"],
    crewSize: 12,
    baseServings: 12,
    prepTime: 15,
    cookTime: 22,
    totalTime: 37,
    difficulty: "easy",
    ingredients: [
      { group: "Build", quantity: "1", name: "24-count slider roll package", notes: "connected, not separated" },
      { group: "Egg layer", quantity: "14", name: "large eggs", notes: "whisked with 2 tbsp milk" },
      { group: "Egg layer", quantity: "1/2 tsp", name: "kosher salt", notes: "and black pepper" },
      { group: "Protein", quantity: "12", name: "pre-cooked sausage patties", notes: "thin, fit slider size" },
      { group: "Protein", quantity: "12 slices", name: "American or cheddar cheese" },
      { group: "Finish", quantity: "3 tbsp", name: "butter", notes: "melted for brushing tops" },
      { group: "Finish", quantity: "1 tsp", name: "everything bagel seasoning", notes: "optional" },
      { group: "Serve", quantity: "1/2 cup", name: "hot sauce or ketchup", notes: "at the line" },
    ],
    steps: [
      { stepNumber: 1, title: "Heat the oven", tempF: 350, minutes: 0, instruction: "Heat oven to 350°F. Slice the connected roll block horizontally into tops and bottoms without separating individual rolls." },
      { stepNumber: 2, title: "Bake the egg sheet", tempF: 350, minutes: 12, instruction: "Whisk eggs with milk, salt, and pepper. Pour into a parchment-lined quarter sheet pan to roughly slider dimensions. Bake until just set—don't overbake or eggs turn rubbery." },
      { stepNumber: 3, title: "Trim and assemble", minutes: 8, instruction: "Trim egg sheet to fit the roll block. Place bottom halves on a lined sheet pan, add sausage, egg sheet, cheese, and top halves. Press gently to align seams." },
      { stepNumber: 4, title: "Final bake", tempF: 350, minutes: 10, instruction: "Brush tops with melted butter and optional everything seasoning. Bake until cheese melts and tops turn lightly golden." },
      { stepNumber: 5, title: "Cut and serve", minutes: 5, instruction: "Rest 5 minutes, then cut along roll seams with a sharp knife. Serve warm from the pan or transfer to a baking dish for the line." },
    ],
    stationWorkflow: [
      "Measure the roll block before baking the egg sheet—trim once, not twice, for clean sandwich edges.",
      "Use parchment to lift the egg sheet out of the quarter pan for easier trimming and placement.",
      "Cut seams with a long serrated knife in one pass per row to avoid squashing the stacks.",
    ],
    cleanupNotes: [
      "Discard parchment with baked-on egg residue instead of scraping—saves time on busy mornings.",
      "Wipe the sheet pan while warm with a damp towel before butter glaze hardens on the rim.",
    ],
    leftovers: [
      "Wrap sandwiches individually in foil and reheat at 325°F for 10 minutes until cheese remelts.",
      "Split leftovers and griddle cut-side down for a crisp second-day version with fresh hot sauce.",
    ],
    heroImage: hero("sheet-pan-breakfast-sandwiches"),
    thumbImage: thumb("sheet-pan-breakfast-sandwiches"),
    imageAlt: "Sheet pan of pull-apart breakfast slider sandwiches with egg and sausage",
    publishedAt: now,
    updatedAt: now,
    readMinutes: 7,
    seoTitle: "Sheet Pan Breakfast Sandwiches | Firehall Breakfast",
  },
  {
    slug: "chorizo-breakfast-hash",
    title: "Chorizo Breakfast Hash",
    subtitle: "Spicy crumbled chorizo with crispy potatoes and jammy eggs.",
    description:
      "Bold Mexican chorizo drives this one-pan hash: potatoes crisped in rendered chorizo fat, onions and peppers charred at the edges, and eggs finished on top. Faster than a full skillet bake but with enough heat to wake up a crew coming off a night call.",
    filters: ["skillets", "high_protein", "quick_breakfasts"],
    tags: ["chorizo", "hash", "potatoes", "spicy", "one-pan"],
    crewSize: 8,
    baseServings: 8,
    prepTime: 12,
    cookTime: 25,
    totalTime: 37,
    difficulty: "easy",
    ingredients: [
      { group: "Base", quantity: "3.5 lb", name: "russet potatoes", notes: "diced 1/2-inch, par-cooked" },
      { group: "Protein", quantity: "1 1/2 lb", name: "Mexican chorizo", notes: "casings removed" },
      { group: "Protein", quantity: "12", name: "large eggs" },
      { group: "Veg", quantity: "1", name: "large onion", notes: "diced" },
      { group: "Veg", quantity: "2", name: "bell peppers", notes: "diced, any color" },
      { group: "Seasoning", quantity: "1 tsp", name: "smoked paprika", notes: "plus salt if needed" },
      { group: "Finish", quantity: "1 cup", name: "crumbled cotija", notes: "or queso fresco" },
      { group: "Finish", quantity: "1/2 cup", name: "cilantro", notes: "chopped, plus lime wedges" },
    ],
    steps: [
      { stepNumber: 1, title: "Par-cook potatoes", minutes: 8, instruction: "Microwave diced potatoes with a splash of water until just tender, then drain and pat completely dry. Wet potatoes steam instead of crisp in the chorizo fat." },
      { stepNumber: 2, title: "Render chorizo", minutes: 8, instruction: "Cook chorizo in a large skillet over medium-high, breaking it up until browned and fat renders. Push chorizo to one side and add potatoes to the hot fat in a single layer." },
      { stepNumber: 3, title: "Crisp and combine", minutes: 10, instruction: "Let potatoes sit undisturbed 3 minutes for crust, then toss with chorizo, onion, and peppers. Cook until edges are deeply golden and vegetables soften." },
      { stepNumber: 4, title: "Eggs on top", minutes: 7, instruction: "Make wells in the hash and crack eggs into each. Cover over medium-low heat until egg whites are fully set (165°F) and yolks are jammy. Season with paprika and salt only if the chorizo is not already salty enough." },
      { stepNumber: 5, title: "Top and serve", minutes: 2, instruction: "Scatter cotija and cilantro over the top. Serve with lime wedges and hot sauce at the line straight from the skillet or scooped onto warm plates." },
    ],
    stationWorkflow: [
      "Use the widest skillet you have—crowded potatoes steam and never develop the hash crust.",
      "Hold rendered chorizo fat in the pan; if lean, add a tablespoon of oil before potatoes hit.",
      "Cover with a sheet pan lid to set eggs fast while the crew lines up at the counter.",
    ],
    cleanupNotes: [
      "Deglaze the skillet with hot water immediately after service—chorizo fat polymerizes if left to cool.",
      "Wash pepper and onion boards before switching to egg cracking to keep raw prep zones separate.",
    ],
    leftovers: [
      "Reheat hash base covered at 325°F, then top with freshly fried eggs rather than reheating set yolks.",
      "Stuff leftovers into warm tortillas with extra cheese and salsa for quick breakfast tacos.",
    ],
    heroImage: hero("chorizo-breakfast-hash"),
    thumbImage: thumb("chorizo-breakfast-hash"),
    imageAlt: "Chorizo breakfast hash with crispy potatoes, peppers, and jammy eggs",
    publishedAt: now,
    updatedAt: now,
    readMinutes: 7,
    seoTitle: "Chorizo Breakfast Hash | Firehall Breakfast",
  },
  {
    slug: "hall-sausage-biscuits-gravy",
    title: "Hall Sausage Biscuits & Gravy",
    subtitle: "Flaky biscuits split and smothered in peppery sausage gravy for twelve.",
    description:
      "Classic hall comfort: bulk breakfast sausage gravy thick enough to coat a spoon, ladled over split baking-powder biscuits. Uses shortcut biscuits from the oven so the cook focuses on gravy that stays smooth and seasoned while feeding a full shift.",
    filters: ["feed_a_crew", "breakfast_sandwiches", "high_protein"],
    tags: ["biscuits", "gravy", "sausage", "classic", "comfort"],
    crewSize: 12,
    baseServings: 12,
    prepTime: 10,
    cookTime: 25,
    totalTime: 35,
    difficulty: "easy",
    ingredients: [
      { group: "Biscuits", quantity: "12", name: "large refrigerated biscuits", notes: "or scratch-baked equivalents" },
      { group: "Biscuits", quantity: "2 tbsp", name: "butter", notes: "melted for brushing tops" },
      { group: "Gravy", quantity: "2 lb", name: "breakfast sausage", notes: "bulk or casings removed" },
      { group: "Gravy", quantity: "1/2 cup", name: "all-purpose flour", notes: "whisked into rendered fat" },
      { group: "Gravy", quantity: "5 cups", name: "whole milk", notes: "warmed slightly for smoother whisking" },
      { group: "Seasoning", quantity: "2 tsp", name: "black pepper", notes: "freshly ground, plus salt to taste" },
      { group: "Seasoning", quantity: "1/2 tsp", name: "poultry seasoning", notes: "optional depth" },
      { group: "Serve", quantity: "1/4 cup", name: "chopped parsley", notes: "and hot sauce at the line" },
    ],
    steps: [
      { stepNumber: 1, title: "Bake the biscuits", tempF: 375, minutes: 15, instruction: "Heat oven to 375°F. Arrange biscuits on a sheet pan and brush tops with melted butter. Bake until golden and cooked through—split one to check the center isn't doughy." },
      { stepNumber: 2, title: "Brown the sausage", minutes: 8, instruction: "In a large Dutch oven or deep skillet, brown sausage over medium-high, breaking it into fine crumbles. Don't drain all the fat—you need it for the roux." },
      { stepNumber: 3, title: "Build the roux", minutes: 3, instruction: "Sprinkle flour over the sausage and fat, stirring constantly for 1–2 minutes until the raw flour smell cooks off and the mixture looks sandy." },
      { stepNumber: 4, title: "Whisk in milk", minutes: 10, instruction: "Add warm milk gradually, whisking to prevent lumps. Simmer until gravy thickens enough to coat a spoon. Season aggressively with black pepper and salt." },
      { stepNumber: 5, title: "Split and ladle", minutes: 5, instruction: "Split warm biscuits and place two halves per bowl or plate. Ladle hot gravy over the top until generously covered. Garnish with parsley and serve immediately." },
    ],
    stationWorkflow: [
      "Warm milk in a microwave or small pot before whisking—cold milk shocks the roux and causes lumps.",
      "Hold biscuits uncovered at 200°F while gravy finishes; covered biscuits steam soft tops.",
      "Keep gravy on the lowest simmer with a ladle in the pot at the line for second portions.",
    ],
    cleanupNotes: [
      "Fill the gravy pot with hot soapy water immediately—flour-milk paste sets hard within minutes.",
      "Discard any biscuit crumbs on the sheet pan before they bake onto the metal during cleanup.",
    ],
    leftovers: [
      "Gravy reheats smoothly with extra milk over low heat; thin until pourable before ladling.",
      "Split leftover biscuits and griddle cut-side down, then top with reheated gravy and a fried egg.",
    ],
    heroImage: hero("hall-sausage-biscuits-gravy"),
    thumbImage: thumb("hall-sausage-biscuits-gravy"),
    imageAlt: "Split biscuits smothered in peppery sausage gravy on a firehall breakfast plate",
    publishedAt: now,
    updatedAt: now,
    readMinutes: 7,
    seoTitle: "Hall Sausage Biscuits & Gravy | Firehall Breakfast",
  },
  {
    slug: "overnight-french-toast-bake",
    title: "Overnight French Toast Bake",
    subtitle: "Prep tonight, bake tomorrow—a custard-soaked tray for the whole crew.",
    description:
      "Cubed brioche soaks overnight in a cinnamon-vanilla custard, then bakes into a puffed golden casserole that feeds twelve without standing at the griddle. Ideal before early training days when the cook needs hands-free oven time.",
    filters: ["feed_a_crew", "healthy_breakfasts"],
    tags: ["french-toast", "overnight", "make-ahead", "casserole", "brioche"],
    crewSize: 12,
    baseServings: 12,
    prepTime: 20,
    cookTime: 45,
    totalTime: 65,
    difficulty: "easy",
    ingredients: [
      { group: "Base", quantity: "2 loaves", name: "brioche or challah", notes: "cubed into 1-inch pieces" },
      { group: "Custard", quantity: "12", name: "large eggs" },
      { group: "Custard", quantity: "4 cups", name: "whole milk", notes: "or half-and-half" },
      { group: "Custard", quantity: "1/2 cup", name: "maple syrup", notes: "plus extra for serving" },
      { group: "Custard", quantity: "2 tsp", name: "vanilla extract", notes: "and 1 tbsp cinnamon" },
      { group: "Topping", quantity: "1/2 cup", name: "brown sugar", notes: "sprinkled before baking" },
      { group: "Topping", quantity: "1/2 cup", name: "chopped pecans", notes: "optional crunch" },
      { group: "Finish", quantity: "1/4 cup", name: "powdered sugar", notes: "and fresh berries at the line" },
    ],
    steps: [
      { stepNumber: 1, title: "Prep the bread", minutes: 8, instruction: "Cube brioche and spread on sheet pans to dry slightly for 30 minutes, or toast lightly at 300°F for 6 minutes. Day-old bread absorbs custard without turning mushy." },
      { stepNumber: 2, title: "Whisk the custard", minutes: 5, instruction: "Whisk eggs, milk, maple syrup, vanilla, cinnamon, and a pinch of salt until smooth. The mixture should look like thin pancake batter." },
      { stepNumber: 3, title: "Assemble and refrigerate", minutes: 10, instruction: "Layer bread cubes in a buttered 9x13 dish. Pour custard evenly, pressing gently so all cubes soak. Cover and refrigerate 8–12 hours." },
      { stepNumber: 4, title: "Bake until puffed", tempF: 375, minutes: 42, instruction: "Remove from fridge 30 minutes before baking. Heat oven to 375°F, sprinkle brown sugar and pecans on top, and bake until puffed, golden, and set in the center." },
      { stepNumber: 5, title: "Rest and serve", minutes: 10, instruction: "Rest 10 minutes before cutting into squares. Dust with powdered sugar and serve with maple syrup and berries at the line." },
    ],
    stationWorkflow: [
      "Label the covered dish with bake time and oven temp so the morning cook doesn't guess.",
      "Pull the dish while the oven preheats so the glass or metal pan doesn't crack from cold shock.",
      "Cut in the pan with a serrated knife wiped between rows for clean squares on the line.",
    ],
    cleanupNotes: [
      "Soak the 9x13 while still warm—custard and sugar caramelize on the edges once cooled.",
      "Line sheet pans with parchment when drying bread cubes for one-wipe cleanup.",
    ],
    leftovers: [
      "Wrap squares in foil and reheat at 325°F for 12 minutes until steaming in the center.",
      "Cube cold leftovers into a skillet with butter and pan-fry until crisp edges form for French toast hash.",
    ],
    heroImage: hero("overnight-french-toast-bake"),
    thumbImage: thumb("overnight-french-toast-bake"),
    imageAlt: "Golden overnight French toast bake cut into squares with berries and maple",
    publishedAt: now,
    updatedAt: now,
    readMinutes: 8,
    seoTitle: "Overnight French Toast Bake | Firehall Breakfast",
  },
  {
    slug: "fire-captain-omelette-bar",
    title: "Fire Captain Omelette Bar",
    subtitle: "Made-to-order omelettes with a prep line of fillings for ten.",
    description:
      "A station-style omelette bar keeps the captain happy and the line moving: prepped fillings, beaten eggs in pitchers, and two pans running staggered. Everyone builds their own combo while the cook focuses on fold technique and heat control.",
    filters: ["feed_a_crew", "high_protein", "quick_breakfasts"],
    tags: ["omelette", "bar", "custom", "eggs", "station"],
    crewSize: 10,
    baseServings: 10,
    prepTime: 25,
    cookTime: 20,
    totalTime: 45,
    difficulty: "medium",
    ingredients: [
      { group: "Eggs", quantity: "24", name: "large eggs", notes: "beaten in batches of 3 per omelette" },
      { group: "Eggs", quantity: "1/2 cup", name: "whole milk", notes: "whisked into beaten eggs" },
      { group: "Fillings", quantity: "2 cups", name: "shredded cheddar", notes: "and 2 cups shredded mozzarella" },
      { group: "Fillings", quantity: "2 cups", name: "diced ham", notes: "and 1 lb cooked crumbled bacon" },
      { group: "Fillings", quantity: "2 cups", name: "sautéed mushrooms", notes: "and 1 cup diced bell peppers" },
      { group: "Fillings", quantity: "1 cup", name: "diced tomatoes", notes: "drained, plus 1 cup spinach" },
      { group: "Fat", quantity: "4 tbsp", name: "butter", notes: "for pans, plus oil as needed" },
      { group: "Serve", quantity: "1/2 cup", name: "salsa and hot sauce", notes: "at the line" },
    ],
    steps: [
      { stepNumber: 1, title: "Prep the filling line", minutes: 20, instruction: "Set all fillings in labeled baking dishes with spoons. Sauté mushrooms and peppers ahead; drain tomatoes well. Beat eggs with milk in a pitcher for fast pours." },
      { stepNumber: 2, title: "Heat two pans", minutes: 3, instruction: "Heat two nonstick skillets over medium. Add a knob of butter until foaming but not brown. Work one omelette per pan for steady throughput." },
      { stepNumber: 3, title: "Cook and fill", minutes: 12, instruction: "Pour 3-egg portion into each pan, swirl to coat, and let set briefly. Add chosen fillings to one half when the top looks mostly set but still glossy." },
      { stepNumber: 4, title: "Fold and plate", minutes: 8, instruction: "Fold omelettes in half with a spatula and slide onto warm plates. Wipe pans quickly between batches if residue builds." },
      { stepNumber: 5, title: "Keep the line moving", minutes: 0, instruction: "Call orders two at a time, not ten at once. Hold finished omelettes in a 200°F oven uncovered for no more than 5 minutes before quality drops." },
    ],
    stationWorkflow: [
      "Post a simple order card at the line: pick three fillings max so the cook doesn't get buried.",
      "Run two pans staggered—pour pan B while folding pan A to maintain a steady rhythm.",
      "Keep a damp towel and oil brush at the station for quick pan resets between omelettes.",
    ],
    cleanupNotes: [
      "Wipe nonstick pans with warm soapy water only after cooling—thermal shock warps lightweight pans.",
      "Consolidate leftover fillings into labeled containers for omelette scrambles the next morning.",
    ],
    leftovers: [
      "Chop leftover omelettes into a breakfast fried rice with soy, green onion, and sesame oil.",
      "Combine extra fillings with beaten eggs and bake as a frittata at 375°F for 25 minutes.",
    ],
    heroImage: hero("fire-captain-omelette-bar"),
    thumbImage: thumb("fire-captain-omelette-bar"),
    imageAlt: "Fire captain omelette bar with fillings and folded omelettes on warm plates",
    publishedAt: now,
    updatedAt: now,
    readMinutes: 9,
    seoTitle: "Fire Captain Omelette Bar | Firehall Breakfast",
  },
  {
    slug: "breakfast-nachos-supreme",
    title: "Breakfast Nachos Supreme",
    subtitle: "Tortilla chips loaded with eggs, bacon, cheese, and salsa on sheet pans.",
    description:
      "Two sheet pans of loaded breakfast nachos feed ten fast: chips layered with queso, scrambled eggs, crisp bacon, pico, and avocado. Built in waves so the bottom layer stays crisp while the top gets melty and golden under the broiler.",
    filters: ["feed_a_crew", "quick_breakfasts", "high_protein"],
    tags: ["nachos", "bacon", "eggs", "sheet-pan", "shareable"],
    crewSize: 10,
    baseServings: 10,
    prepTime: 15,
    cookTime: 15,
    totalTime: 30,
    difficulty: "easy",
    ingredients: [
      { group: "Base", quantity: "2", name: "large bags tortilla chips", notes: "thick restaurant-style" },
      { group: "Protein", quantity: "14", name: "large eggs", notes: "soft-scrambled" },
      { group: "Protein", quantity: "1 lb", name: "bacon", notes: "cooked crisp and crumbled" },
      { group: "Cheese", quantity: "3 cups", name: "shredded cheddar", notes: "and 2 cups shredded Monterey Jack" },
      { group: "Cheese", quantity: "1 1/2 cups", name: "nacho cheese sauce", notes: "warmed" },
      { group: "Toppings", quantity: "1 1/2 cups", name: "pico de gallo", notes: "drained well" },
      { group: "Toppings", quantity: "2", name: "avocados", notes: "diced, added after broil" },
      { group: "Finish", quantity: "1/2 cup", name: "sour cream", notes: "crema, and sliced jalapeños" },
    ],
    steps: [
      { stepNumber: 1, title: "Prep components", minutes: 12, instruction: "Cook bacon until crisp and crumble. Soft-scramble eggs—they should still look glossy. Warm nacho cheese. Drain pico thoroughly so chips don't sog out." },
      { stepNumber: 2, title: "Layer the chips", minutes: 3, instruction: "Spread chips on two rimmed sheet pans in a single thick layer. Drizzle half the nacho cheese, then scatter half the shredded cheeses over each pan." },
      { stepNumber: 3, title: "First melt", tempF: 400, minutes: 5, instruction: "Bake at 400°F until cheese melts and chips at the edges toast lightly. Remove and distribute scrambled eggs and bacon evenly across both pans." },
      { stepNumber: 4, title: "Broil to finish", tempF: 500, minutes: 3, instruction: "Add remaining cheese and broil on high 2–3 minutes until bubbling and spotty golden. Watch constantly—chips burn fast under the broiler." },
      { stepNumber: 5, title: "Top and serve", minutes: 2, instruction: "Add pico, avocado, sour cream, and jalapeños immediately. Serve straight from the sheet pans at the line with extra hot sauce on the side." },
    ],
    stationWorkflow: [
      "Build on two pans so the crew can attack from both ends of the table without a traffic jam.",
      "Hold avocado and sour cream cold until the nachos leave the broiler—hot chips wilt them fast.",
      "Serve within 5 minutes of broiling; nachos don't hold, so call the crew as soon as pans hit the counter.",
    ],
    cleanupNotes: [
      "Line sheet pans with foil for easier cleanup after melted cheese and queso bond to the metal.",
      "Discard soggy bottom chips rather than scraping—foil lift-and-toss is faster on busy mornings.",
    ],
    leftovers: [
      "Nachos don't reheat well; repurpose leftover toppings into breakfast burritos with fresh tortillas.",
      "Use extra scrambled eggs and bacon in a hash with diced potatoes for the next shift.",
    ],
    heroImage: hero("breakfast-nachos-supreme"),
    thumbImage: thumb("breakfast-nachos-supreme"),
    imageAlt: "Breakfast nachos supreme loaded with eggs, bacon, melted cheese, and pico",
    publishedAt: now,
    updatedAt: now,
    readMinutes: 7,
    seoTitle: "Breakfast Nachos Supreme | Firehall Breakfast",
  },
  {
    slug: "maple-sausage-pinwheels",
    title: "Maple Sausage Pinwheels",
    subtitle: "Crescent dough spirals with sausage and maple glaze baked golden.",
    description:
      "Refrigerated crescent dough rolled with seasoned sausage and a touch of maple, sliced into pinwheels and baked until puffed and sticky-sweet. A handheld crowd-pleaser that scales to ten with two sheet pans and minimal active cooking time.",
    filters: ["feed_a_crew", "quick_breakfasts", "breakfast_sandwiches"],
    tags: ["pinwheels", "sausage", "maple", "crescent", "handheld"],
    crewSize: 10,
    baseServings: 10,
    prepTime: 15,
    cookTime: 22,
    totalTime: 37,
    difficulty: "easy",
    ingredients: [
      { group: "Filling", quantity: "1 1/2 lb", name: "breakfast sausage", notes: "browned and crumbled fine" },
      { group: "Filling", quantity: "1 1/2 cups", name: "shredded cheddar", notes: "mixed into warm sausage" },
      { group: "Filling", quantity: "3 tbsp", name: "maple syrup", notes: "stirred into sausage off heat" },
      { group: "Dough", quantity: "2", name: "8-count crescent roll tubes", notes: "or seamless dough sheets" },
      { group: "Glaze", quantity: "1/4 cup", name: "butter", notes: "melted" },
      { group: "Glaze", quantity: "2 tbsp", name: "maple syrup", notes: "for brushing before bake" },
      { group: "Seasoning", quantity: "1/2 tsp", name: "black pepper", notes: "in sausage mix" },
      { group: "Finish", quantity: "1 tbsp", name: "everything bagel seasoning", notes: "optional on top" },
    ],
    steps: [
      { stepNumber: 1, title: "Make the filling", minutes: 10, instruction: "Brown sausage, drain well, and mix with cheddar, maple syrup, and black pepper while warm so cheese starts to melt and bind the filling." },
      { stepNumber: 2, title: "Roll the dough", minutes: 8, instruction: "Press crescent dough into two rectangles, sealing seams. Spread sausage filling evenly, roll tight into logs, and pinch seams closed." },
      { stepNumber: 3, title: "Slice pinwheels", minutes: 5, instruction: "Cut each log into 8–10 pinwheels with a sharp serrated knife. Place cut-side up on parchment-lined sheet pans with space between each spiral." },
      { stepNumber: 4, title: "Glaze and bake", tempF: 375, minutes: 18, instruction: "Brush tops with melted butter and maple syrup. Bake at 375°F until golden, puffed, and sausage reaches 165°F in the center." },
      { stepNumber: 5, title: "Cool slightly and serve", minutes: 5, instruction: "Rest 5 minutes so filling sets—hot maple cheese burns tongues. Serve from sheet pans or stack in a warm baking dish for grab-and-go." },
    ],
    stationWorkflow: [
      "Chill rolled logs 10 minutes before slicing if dough gets soft—clean spirals need a firm log.",
      "Bake both sheet pans on middle and upper racks, swapping halfway for even browning.",
      "Serve with napkins stacked high—these are sticky, handheld, and popular on the way to rigs.",
    ],
    cleanupNotes: [
      "Use parchment on sheet pans so maple glaze doesn't weld to the metal during baking.",
      "Soak the sausage mixing bowl immediately—maple and cheese set into a glue once cooled.",
    ],
    leftovers: [
      "Reheat pinwheels on a sheet pan at 325°F for 8 minutes until warmed through and crust re-crisp.",
      "Split cold pinwheels and griddle cut-side down with extra maple for a caramelized second-day treat.",
    ],
    heroImage: hero("maple-sausage-pinwheels"),
    thumbImage: thumb("maple-sausage-pinwheels"),
    imageAlt: "Golden maple sausage pinwheels on a sheet pan fresh from the oven",
    publishedAt: now,
    updatedAt: now,
    readMinutes: 7,
    seoTitle: "Maple Sausage Pinwheels | Firehall Breakfast",
  },
];
