import type { ExpansionRecipeDef } from "../types.js";
import { def, ing, step } from "../recipe-build.js";
import {
  CALL_INTERRUPTION_STEP,
  LEFTOVERS_PACK_DOWN_STEP,
  buildStructuredTonightSpread,
  standardLeftovers,
} from "../../golden-100/recipe-quality/classics-wheel-editorial.js";

/**
 * High-Protein / Healthy Expansion, Batch 2 — closing the vegetarian
 * high-protein gap with tempeh, paneer, and cottage-cheese-forward dinners.
 * All nutrition below is a starting estimate; the production build
 * regenerates real per-serving macros from these ingredient lists via
 * shared/nutrition/calculate.ts (npm run audit:recipe-nutrition:fix) before
 * publish.
 */
export const BATCH_HIGH_PROTEIN_EXPANSION_2_RECIPES: ExpansionRecipeDef[] = [
  def({
    slug: "tempeh-peanut-buddha-bowls",
    title: "Tempeh Peanut Buddha Bowls",
    subtitle: "Pan-crisped tempeh and edamame over rice with a peanut-lime sauce",
    category: "crew_feeders",
    protein: "vegetarian",
    cuisine: "asian",
    mealFormat: "bowl",
    explorePools: ["bowl", "vegetarian", "healthy", "meal_prep", "hall_expansion"],
    hookLine: "A fully vegetarian bowl that gets real protein from tempeh and edamame, not just rice.",
    description:
      "Crumbled tempeh pan-crisps until deeply browned, then joins edamame, shredded carrot, and cabbage over rice with a peanut-lime sauce. It is a vegetarian bowl built to actually hold up as a full dinner.",
    whyCrewsLikeIt:
      "Tempeh browns up hearty and savory instead of tasting like a meat substitute, and the peanut sauce means nobody treats this as a side dish.",
    mealPrepNotes:
      "Make-ahead: cook tempeh and rice up to two days ahead. Storage: keep tempeh, rice, and slaw vegetables in separate containers up to 4 days; store sauce separately. Reheating: warm tempeh and rice together, then add cold slaw and sauce.",
    stationWorkflow: [
      "Crumble tempeh by hand before it hits the pan so it crisps in small, browned pieces instead of one dense block.",
      "Keep the peanut sauce in a squeeze bottle at the pass so portions stay consistent.",
      "Shred carrot and cabbage ahead and hold cold until bowls are built.",
    ],
    prepMinutes: 20,
    cookMinutes: 25,
    difficulty: "easy",
    crewSizeDefault: 8,
    ingredients: [
      ing("tempeh", "3", { unit: "block", notes: "crumbled", group: "Protein" }),
      ing("olive oil", "3", { unit: "tbsp", group: "Protein" }),
      ing("soy sauce", "2", { unit: "tbsp", group: "Protein" }),
      ing("brown rice", "2.5", { unit: "cups", notes: "dry", group: "Base" }),
      ing("edamame", "2", { unit: "cups", notes: "shelled, thawed", group: "Vegetables" }),
      ing("carrots", "1", { unit: "lb", notes: "shredded", group: "Vegetables" }),
      ing("red cabbage", "4", { unit: "cups", notes: "shredded", group: "Vegetables" }),
      ing("green onions", "0.5", { unit: "cup", notes: "sliced", group: "Vegetables" }),
      ing("peanut butter", "0.5", { unit: "cup", group: "Sauce" }),
      ing("soy sauce", "3", { unit: "tbsp", group: "Sauce" }),
      ing("rice vinegar", "2", { unit: "tbsp", group: "Sauce" }),
      ing("lime juice", "2", { unit: "tbsp", group: "Sauce" }),
      ing("honey", "2", { unit: "tbsp", group: "Sauce" }),
      ing("fresh ginger", "1", { unit: "tbsp", notes: "grated", group: "Sauce" }),
      ing("garlic", "2", { unit: "cloves", notes: "minced", group: "Sauce" }),
      ing("sesame seeds", "2", { unit: "tbsp", notes: "toasted", optional: true, group: "Finish" }),
    ],
    steps: [
      step(1, "Cook the rice", "Rinse brown rice and cook according to package directions. Fluff with a fork and hold covered.", { minutes: 35 }),
      step(2, "Crisp the tempeh", "Heat olive oil in a large skillet over medium-high. Add crumbled tempeh and cook 8–10 minutes, stirring occasionally, until deeply browned and crisp at the edges. Stir in 2 tablespoons soy sauce in the last minute.", { minutes: 10, heatLevel: "medium-high" }),
      step(3, "Build the peanut-lime sauce", "Whisk peanut butter, remaining soy sauce, rice vinegar, lime juice, honey, ginger, and garlic in a bowl until smooth, adding a splash of warm water to loosen it to a pourable consistency.", { minutes: 6 }),
      step(4, "Warm the edamame", "Steam or microwave edamame with a splash of water 3–4 minutes until hot. Toss with a pinch of salt.", { minutes: 4 }),
      step(5, "Hold everything separately", "Keep tempeh and rice covered and warm; keep shredded carrot, cabbage, and green onions cold and separate so the slaw stays crisp.", { minutes: 5 }),
      step(6, "Build the bowls", "Layer rice, crisped tempeh, edamame, carrot, and cabbage in each bowl. Drizzle with peanut-lime sauce and finish with green onions and sesame seeds if using.", { minutes: 8 }),
      CALL_INTERRUPTION_STEP(7, "crisped tempeh and peanut-lime sauce"),
      LEFTOVERS_PACK_DOWN_STEP(8, "tempeh peanut buddha bowls"),
    ],
    proTips: [
      "Prep tip: Freeze tempeh for 10 minutes before crumbling — it holds together better under a knife when firm.",
      "Rookie tip: Don't skip the browning step; pale tempeh tastes bitter, well-browned tempeh tastes nutty and savory.",
      "Add sriracha or chili crisp to the sauce for crews who want heat.",
    ],
    tonightSpread: buildStructuredTonightSpread(
      "Tempeh peanut buddha bowls",
      ["Cucumber salad", "extra lime wedges"],
      ["Sriracha", "extra peanut sauce"],
    ),
    leftovers: standardLeftovers("tempeh peanut buddha bowls", [
      "Sauce keeps separately up to a week — thin with water before reusing.",
    ]),
    equipment: ["Rice cooker or pot", "Large skillet", "Mixing bowls"],
    nutrition: { calories: 622, protein: 33, carbs: 71, fats: 27, fiber: 9 },
    spiceLevel: "mild",
    cleanupDifficulty: "easy",
    searchTerms: [
      "tempeh bowl",
      "vegetarian protein bowl",
      "peanut tempeh bowl",
      "vegetarian meal prep bowl",
      "firehouse vegetarian dinner",
    ],
    substitutions: [
      "Use extra-firm tofu instead of tempeh.",
      "Use almond butter instead of peanut butter for a nut allergy swap (still contains tree nuts).",
      "Use quinoa instead of rice for extra protein.",
    ],
  }),

  def({
    slug: "paneer-tikka-masala-bowls",
    title: "Paneer Tikka Masala Bowls",
    subtitle: "Seared paneer in a creamy tomato masala sauce over basmati rice",
    category: "crew_feeders",
    protein: "vegetarian",
    cuisine: "indian",
    mealFormat: "bowl",
    explorePools: ["bowl", "vegetarian", "healthy", "hall_expansion"],
    hookLine: "A vegetarian curry night with paneer standing in for chicken and holding its own on protein.",
    description:
      "Cubes of paneer sear until golden, then simmer in a spiced tomato-yogurt masala sauce over basmati rice. It is a genuine curry-night option for vegetarian crew members that still lands a real per-serving protein count.",
    whyCrewsLikeIt:
      "It gives vegetarian crew members an actual curry-night entrée instead of a side dish, and the sauce is rich enough that nobody misses the chicken.",
    mealPrepNotes:
      "Make-ahead: the masala sauce improves overnight in the fridge. Storage: keep paneer-in-sauce and rice in separate containers up to 4 days. Reheating: reheat sauce gently over medium-low so the paneer doesn't turn rubbery from a hard boil.",
    stationWorkflow: [
      "Sear paneer in batches so pieces brown instead of steam in a crowded pan.",
      "Build the sauce base while the rice cooks so both finish close together.",
      "Stir yogurt in off heat to keep the sauce from breaking.",
    ],
    prepMinutes: 20,
    cookMinutes: 35,
    difficulty: "medium",
    crewSizeDefault: 8,
    ingredients: [
      ing("paneer", "2.25", { unit: "lb", notes: "cubed", group: "Protein" }),
      ing("olive oil", "3", { unit: "tbsp", group: "Protein" }),
      ing("basmati rice", "2.5", { unit: "cups", notes: "dry", group: "Base" }),
      ing("yellow onion", "2", { unit: "each", notes: "diced", group: "Sauce" }),
      ing("garlic", "4", { unit: "cloves", notes: "minced", group: "Sauce" }),
      ing("fresh ginger", "1", { unit: "tbsp", notes: "grated", group: "Sauce" }),
      ing("crushed tomato", "2", { unit: "cans", group: "Sauce" }),
      ing("greek yogurt", "1", { unit: "cup", notes: "plain", group: "Sauce" }),
      ing("heavy cream", "0.33", { unit: "cup", group: "Sauce" }),
      ing("garam masala", "2", { unit: "tbsp", group: "Seasoning" }),
      ing("cumin", "1", { unit: "tbsp", group: "Seasoning" }),
      ing("turmeric", "1", { unit: "tsp", group: "Seasoning" }),
      ing("fresh cilantro", "0.25", { unit: "cup", notes: "chopped", optional: true, group: "Finish" }),
    ],
    steps: [
      step(1, "Cook the rice", "Rinse basmati rice and cook according to package directions. Fluff and hold covered.", { minutes: 20 }),
      step(2, "Sear the paneer", "Heat olive oil in a large skillet over medium-high. Sear paneer cubes in batches, 2–3 minutes per side, until golden. Remove and set aside — do not crowd the pan.", { minutes: 12, heatLevel: "medium-high" }),
      step(3, "Build the masala base", "In the same pan, cook onion 5–6 minutes until soft, then add garlic and ginger and cook 1 minute more. Stir in garam masala, cumin, and turmeric and toast 30 seconds.", { minutes: 8, heatLevel: "medium" }),
      step(4, "Simmer the sauce", "Add crushed tomato and simmer 12–15 minutes, stirring occasionally, until thickened and deep red.", { minutes: 15, heatLevel: "low" }),
      step(5, "Finish off heat", "Remove the pan from heat, then stir in greek yogurt and heavy cream until smooth — adding dairy off heat keeps the sauce from breaking.", { minutes: 4 }),
      step(6, "Return the paneer", "Fold seared paneer back into the sauce and warm gently over low heat 3–4 minutes, just until heated through.", { minutes: 4, heatLevel: "low" }),
      step(7, "Serve over rice", "Spoon paneer tikka masala over basmati rice and finish with fresh cilantro if using.", { minutes: 6 }),
      CALL_INTERRUPTION_STEP(8, "paneer tikka masala"),
      LEFTOVERS_PACK_DOWN_STEP(9, "paneer tikka masala"),
    ],
    proTips: [
      "Prep tip: Pat paneer dry before searing so it browns instead of steaming.",
      "Rookie tip: Stir dairy in off heat and over low, gentle warming only — a hard boil after adding yogurt can curdle the sauce.",
      "Add frozen peas in the last few minutes for extra color and volume.",
    ],
    tonightSpread: buildStructuredTonightSpread(
      "Paneer tikka masala bowls",
      ["Cucumber raita", "simple green salad"],
      ["Naan", "extra cilantro"],
    ),
    leftovers: standardLeftovers("paneer tikka masala", [
      "Reheat gently over low heat with a splash of water so the sauce doesn't break.",
    ]),
    equipment: ["Large skillet", "Rice cooker or pot", "Mixing bowls"],
    nutrition: { calories: 714, protein: 32, carbs: 65, fats: 37, fiber: 5 },
    spiceLevel: "medium",
    cleanupDifficulty: "easy",
    searchTerms: [
      "paneer tikka masala",
      "vegetarian curry bowl",
      "paneer bowl",
      "vegetarian indian dinner",
      "protein-rich vegetarian curry",
    ],
    substitutions: [
      "Use extra-firm tofu instead of paneer for a dairy-free-adaptable version (still contains dairy in the sauce unless yogurt/cream are swapped).",
      "Use coconut milk instead of heavy cream and yogurt for a dairy-free sauce.",
      "Use brown rice instead of basmati for more fiber.",
    ],
  }),

  def({
    slug: "black-bean-cottage-cheese-enchilada-bake",
    title: "Black Bean & Cottage Cheese Enchilada Bake",
    subtitle: "Corn tortillas layered with black beans, cottage cheese, and enchilada sauce",
    category: "crew_feeders",
    protein: "vegetarian",
    cuisine: "mexican",
    mealFormat: "bake",
    explorePools: ["bake", "vegetarian", "healthy", "high_protein", "hall_expansion"],
    hookLine: "A vegetarian enchilada bake that leans on cottage cheese instead of extra oil for its protein.",
    description:
      "Corn tortillas layer with black beans, corn, and a cottage cheese filling under melted cheese and a chili-spiced tomato sauce, then bake into sliceable squares. It is a stacked casserole, not rolled enchiladas, so it serves a crew fast.",
    whyCrewsLikeIt:
      "It is a hands-off oven bake that happens to be vegetarian and protein-dense, and it holds and reheats in squares just like the crew's usual casserole nights.",
    mealPrepNotes:
      "Make-ahead: assemble up to a day ahead and refrigerate unbaked. Storage: refrigerate baked squares up to 4 days. Reheating: cover and reheat at 350°F until warmed through, about 15 minutes.",
    stationWorkflow: [
      "Layer in a 9x13 pan like lasagna — tortillas, filling, sauce, repeat.",
      "Rest the bake 10 minutes before cutting so squares hold together.",
      "Keep toppings (green onion, avocado) separate until serving.",
    ],
    prepMinutes: 20,
    cookMinutes: 40,
    difficulty: "easy",
    crewSizeDefault: 8,
    ingredients: [
      ing("black beans", "3", { unit: "cans", notes: "drained, rinsed", group: "Filling" }),
      ing("cottage cheese", "3.5", { unit: "cups", group: "Filling" }),
      ing("corn kernels", "2", { unit: "cups", notes: "frozen or canned", group: "Filling" }),
      ing("yellow onion", "1", { unit: "each", notes: "diced", group: "Filling" }),
      ing("garlic", "3", { unit: "cloves", notes: "minced", group: "Filling" }),
      ing("chili powder", "2", { unit: "tbsp", group: "Seasoning" }),
      ing("cumin", "1", { unit: "tbsp", group: "Seasoning" }),
      ing("olive oil", "2", { unit: "tbsp", group: "Filling" }),
      ing("corn tortilla", "16", { unit: "count", group: "Base" }),
      ing("tomato sauce", "4", { unit: "cups", notes: "or canned red enchilada sauce", group: "Sauce" }),
      ing("shredded cheese", "3", { unit: "cups", notes: "cheddar or Monterey Jack blend", group: "Topping" }),
      ing("green onions", "0.5", { unit: "cup", notes: "sliced", optional: true, group: "Finish" }),
    ],
    steps: [
      step(1, "Heat the oven and build the filling", "Heat oven to 375°F. Warm olive oil in a skillet over medium, cook onion 5 minutes until soft, then add garlic, chili powder, and cumin and cook 1 minute more.", { minutes: 8, heatLevel: "medium", tempF: 375 }),
      step(2, "Combine the filling", "In a large bowl, combine the onion mixture, black beans, cottage cheese, and corn kernels. Stir until evenly mixed.", { minutes: 6 }),
      step(3, "Layer the bake", "Spread a thin layer of sauce in a greased 9x13 pan. Layer tortillas, a portion of filling, more sauce, and a scatter of cheese. Repeat to build 3 layers, finishing with sauce and the remaining cheese on top.", { minutes: 15 }),
      step(4, "Bake until bubbling", "Bake 35–40 minutes until the cheese is melted and golden and the center is hot throughout.", { minutes: 40, tempF: 375 }),
      step(5, "Rest before slicing", "Rest 10 minutes before cutting into squares so the layers hold together instead of sliding apart.", { minutes: 10 }),
      step(6, "Top and serve", "Top with green onions if using and serve with extra salsa or hot sauce on the side.", { minutes: 5 }),
      CALL_INTERRUPTION_STEP(7, "black bean and cottage cheese enchilada bake"),
      LEFTOVERS_PACK_DOWN_STEP(8, "enchilada bake"),
    ],
    proTips: [
      "Prep tip: Squeeze excess liquid from thawed corn if using frozen so the bake doesn't turn watery.",
      "Rookie tip: Rest the full 10 minutes — cutting immediately out of the oven makes the layers collapse.",
      "Add diced jalapeño to the filling for a spicier version.",
    ],
    tonightSpread: buildStructuredTonightSpread(
      "Black bean and cottage cheese enchilada bake",
      ["Simple green salad", "Mexican street corn"],
      ["Salsa", "hot sauce", "sliced avocado"],
    ),
    leftovers: standardLeftovers("enchilada bake", [
      "Reheat squares covered at 350°F until warmed through rather than microwaving dry.",
    ]),
    equipment: ["9x13 baking dish", "Large skillet", "Mixing bowl"],
    nutrition: { calories: 639, protein: 36, carbs: 72, fats: 25, fiber: 11 },
    spiceLevel: "mild",
    cleanupDifficulty: "easy",
    searchTerms: [
      "vegetarian enchilada bake",
      "black bean enchilada casserole",
      "cottage cheese enchiladas",
      "high protein vegetarian mexican",
      "meal prep enchilada bake",
    ],
    substitutions: [
      "Use pinto beans instead of black beans.",
      "Use flour tortillas if corn tortillas aren't on hand.",
      "Use Greek yogurt instead of cottage cheese if texture is a concern — blend it smooth first.",
    ],
  }),

  def({
    slug: "red-lentil-paneer-dal",
    title: "Red Lentil & Paneer Dal",
    subtitle: "A creamy red lentil dal finished with seared paneer over basmati rice",
    category: "crew_feeders",
    protein: "vegetarian",
    cuisine: "indian",
    mealFormat: "soup_chili",
    explorePools: ["soup_chili", "vegetarian", "healthy", "high_protein", "meal_prep", "hall_expansion"],
    hookLine: "A one-pot lentil dal that gets its real protein backbone from seared paneer, not just lentils.",
    description:
      "Red lentils simmer down into a creamy dal with tomato, garlic, and warm spices, then get topped with seared paneer and a dollop of yogurt. It is a genuine vegetarian main, not a side dish, served over basmati rice.",
    whyCrewsLikeIt:
      "It is a one-pot, low-cleanup dinner that happens to be vegetarian, and the seared paneer on top makes it feel like a full entrée instead of a bowl of soup.",
    mealPrepNotes:
      "Make-ahead: the dal base holds and improves for up to 3 days. Storage: keep dal, paneer, and rice in separate containers up to 4 days. Reheating: reheat dal on the stove with a splash of water; sear paneer fresh or reheat gently so it doesn't turn rubbery.",
    stationWorkflow: [
      "Simmer the dal low and slow — a hard boil scorches lentils on the bottom of the pot.",
      "Sear paneer in a separate pan close to service so it stays crisp on top of the dal.",
      "Cook rice while the dal simmers so both finish together.",
    ],
    prepMinutes: 15,
    cookMinutes: 40,
    difficulty: "easy",
    crewSizeDefault: 8,
    ingredients: [
      ing("red lentils", "2.5", { unit: "cups", notes: "dried, rinsed", group: "Base" }),
      ing("paneer", "2.25", { unit: "lb", notes: "cubed", group: "Protein" }),
      ing("olive oil", "3", { unit: "tbsp", group: "Protein" }),
      ing("basmati rice", "2", { unit: "cups", notes: "dry", group: "Base" }),
      ing("yellow onion", "2", { unit: "each", notes: "diced", group: "Base" }),
      ing("garlic", "4", { unit: "cloves", notes: "minced", group: "Base" }),
      ing("fresh ginger", "1", { unit: "tbsp", notes: "grated", group: "Base" }),
      ing("crushed tomato", "1", { unit: "can", group: "Base" }),
      ing("vegetable broth", "6", { unit: "cups", group: "Base" }),
      ing("garam masala", "2", { unit: "tbsp", group: "Seasoning" }),
      ing("turmeric", "1", { unit: "tsp", group: "Seasoning" }),
      ing("cumin", "1", { unit: "tbsp", group: "Seasoning" }),
      ing("greek yogurt", "1", { unit: "cup", notes: "for serving", group: "Finish" }),
      ing("fresh cilantro", "0.25", { unit: "cup", notes: "chopped", optional: true, group: "Finish" }),
    ],
    steps: [
      step(1, "Cook the rice", "Rinse basmati rice and cook according to package directions. Fluff and hold covered.", { minutes: 20 }),
      step(2, "Build the dal base", "Heat 1 tablespoon olive oil in a large pot over medium. Cook onion 5–6 minutes until soft, then add garlic and ginger and cook 1 minute more. Stir in garam masala, turmeric, and cumin and toast 30 seconds.", { minutes: 8, heatLevel: "medium" }),
      step(3, "Simmer the lentils", "Add rinsed red lentils, crushed tomato, and vegetable broth. Bring to a gentle boil, then reduce to a low simmer. Cook 25–30 minutes, stirring occasionally, until the lentils break down into a thick, creamy dal.", { minutes: 30, heatLevel: "low" }),
      step(4, "Sear the paneer", "While the dal simmers, heat remaining oil in a skillet over medium-high. Sear paneer cubes 2–3 minutes per side until golden. Set aside.", { minutes: 8, heatLevel: "medium-high" }),
      step(5, "Adjust seasoning and thickness", "Taste the dal and add salt or a splash of broth if it's too thick. It should be thick enough to hold on a spoon but still pourable.", { minutes: 5 }),
      step(6, "Serve", "Ladle dal over basmati rice, top with seared paneer, a dollop of yogurt, and cilantro if using.", { minutes: 6 }),
      CALL_INTERRUPTION_STEP(7, "red lentil dal base"),
      LEFTOVERS_PACK_DOWN_STEP(8, "red lentil and paneer dal"),
    ],
    proTips: [
      "Prep tip: Rinse red lentils until the water runs mostly clear for the smoothest dal.",
      "Rookie tip: Sear paneer close to service so it stays crisp instead of softening in the hot dal.",
      "A spoon of ghee stirred in at the end (a classic tadka) adds real depth if the hall has it on hand.",
    ],
    tonightSpread: buildStructuredTonightSpread(
      "Red lentil and paneer dal",
      ["Cucumber raita", "simple green salad"],
      ["Naan", "extra yogurt"],
    ),
    leftovers: standardLeftovers("red lentil and paneer dal", [
      "Dal thickens in the fridge — loosen with a splash of water or broth when reheating.",
    ]),
    equipment: ["Large soup pot", "Skillet", "Rice cooker or pot"],
    nutrition: { calories: 723, protein: 38, carbs: 66, fats: 34, fiber: 12 },
    spiceLevel: "medium",
    cleanupDifficulty: "easy",
    searchTerms: [
      "red lentil dal",
      "paneer dal",
      "vegetarian high protein dal",
      "indian lentil dinner",
      "high protein vegetarian dinner",
    ],
    substitutions: [
      "Use extra-firm tofu instead of paneer for a dairy-free-adaptable version.",
      "Use canned lentils in a pinch, added in the last 10 minutes instead of simmering from dry.",
      "Use brown rice instead of basmati for more fiber.",
    ],
  }),

  def({
    slug: "greek-yogurt-white-bean-power-bowls",
    title: "Greek Yogurt & White Bean Power Bowls",
    subtitle: "Warm white beans and quinoa with a lemon Greek yogurt sauce, feta, and vegetables",
    category: "crew_feeders",
    protein: "vegetarian",
    cuisine: "mediterranean",
    mealFormat: "bowl",
    explorePools: ["bowl", "vegetarian", "healthy", "high_protein", "meal_prep", "hall_expansion"],
    hookLine: "A warm vegetarian grain bowl where the Greek yogurt sauce is doing real protein work, not just flavor.",
    description:
      "Warm white beans and quinoa are topped with cucumber, tomato, and feta, then finished with a generous lemon Greek yogurt sauce instead of a thin vinaigrette. It is a balanced, fully vegetarian bowl built to hold its own at dinner.",
    whyCrewsLikeIt:
      "It eats like a Mediterranean plate the crew already likes, but the yogurt-and-bean combination pushes the protein well past a typical vegetable bowl.",
    mealPrepNotes:
      "Make-ahead: cook quinoa and beans up to two days ahead. Storage: keep grains, beans, cold vegetables, and yogurt sauce in separate containers up to 4 days. Reheating: warm quinoa and beans together; add cold vegetables and sauce at serving time.",
    stationWorkflow: [
      "Cook quinoa and warm the beans in parallel so both finish together.",
      "Keep the yogurt sauce cold and separate until bowls are built.",
      "Dice vegetables just before service so they stay crisp.",
    ],
    prepMinutes: 20,
    cookMinutes: 20,
    difficulty: "easy",
    crewSizeDefault: 8,
    ingredients: [
      ing("white beans", "4", { unit: "cans", notes: "drained, rinsed", group: "Base" }),
      ing("quinoa", "3", { unit: "cups", notes: "dry", group: "Base" }),
      ing("olive oil", "2", { unit: "tbsp", group: "Base" }),
      ing("garlic", "2", { unit: "cloves", notes: "minced", group: "Base" }),
      ing("greek yogurt", "4", { unit: "cups", notes: "plain", group: "Sauce" }),
      ing("lemon juice", "0.33", { unit: "cup", group: "Sauce" }),
      ing("olive oil", "0.25", { unit: "cup", group: "Sauce" }),
      ing("fresh dill", "2", { unit: "tbsp", notes: "chopped", optional: true, group: "Sauce" }),
      ing("feta cheese", "2", { unit: "cups", notes: "crumbled", group: "Toppings" }),
      ing("cucumber", "3", { unit: "each", notes: "diced", group: "Toppings" }),
      ing("cherry tomatoes", "3", { unit: "cups", notes: "halved", group: "Toppings" }),
      ing("red onion", "0.5", { unit: "each", notes: "thinly sliced", group: "Toppings" }),
    ],
    steps: [
      step(1, "Cook the quinoa", "Rinse quinoa and cook according to package directions. Fluff with a fork and hold covered.", { minutes: 18 }),
      step(2, "Warm the beans", "Heat olive oil in a skillet over medium. Add garlic and cook 30 seconds, then stir in white beans and warm through, 5–6 minutes, seasoning with salt and pepper.", { minutes: 6, heatLevel: "medium" }),
      step(3, "Build the yogurt sauce", "Whisk Greek yogurt, lemon juice, olive oil, and dill if using in a bowl with a pinch of salt until smooth.", { minutes: 5 }),
      step(4, "Hold everything at the right temperature", "Keep quinoa and beans covered and warm. Keep the yogurt sauce, feta, cucumber, tomatoes, and red onion cold and separate until serving.", { minutes: 5, heatLevel: "low" }),
      step(5, "Build the bowls", "Layer quinoa and white beans in each bowl, then top with cucumber, cherry tomatoes, red onion, and feta.", { minutes: 8 }),
      step(6, "Finish with the sauce", "Spoon a generous amount of lemon Greek yogurt sauce over each bowl just before serving.", { minutes: 4 }),
      CALL_INTERRUPTION_STEP(7, "white beans and quinoa"),
      LEFTOVERS_PACK_DOWN_STEP(8, "greek yogurt white bean power bowls"),
    ],
    proTips: [
      "Prep tip: Salt the yogurt sauce a little more than tastes right when raw — cold quinoa and beans mute seasoning.",
      "Rookie tip: Keep the sauce separate until serving so the bowl doesn't turn soupy sitting on the line.",
      "Add kalamata olives for crews who want a saltier, more traditional Greek profile.",
    ],
    tonightSpread: buildStructuredTonightSpread(
      "Greek yogurt and white bean power bowls",
      ["Warm pita", "simple side salad"],
      ["Extra lemon wedges", "kalamata olives"],
    ),
    leftovers: standardLeftovers("greek yogurt white bean power bowls", [
      "Keep the yogurt sauce separate from the grains so leftovers don't turn watery.",
    ]),
    equipment: ["Pot for quinoa", "Skillet", "Mixing bowls"],
    nutrition: { calories: 752, protein: 39, carbs: 87, fats: 29, fiber: 14 },
    spiceLevel: "mild",
    cleanupDifficulty: "easy",
    searchTerms: [
      "greek yogurt bowl",
      "white bean quinoa bowl",
      "vegetarian high protein bowl",
      "mediterranean protein bowl",
      "high protein meal prep bowl",
    ],
    substitutions: [
      "Use chickpeas instead of white beans.",
      "Use farro or brown rice instead of quinoa.",
      "Use dairy-free yogurt for a lighter-dairy version (protein count will drop).",
    ],
  }),

  def({
    slug: "cottage-cheese-spinach-stuffed-shells",
    title: "Cottage Cheese & Spinach Stuffed Shells",
    subtitle: "Jumbo pasta shells stuffed with cottage cheese, mozzarella, and spinach in marinara",
    category: "crew_feeders",
    protein: "vegetarian",
    cuisine: "italian",
    mealFormat: "pasta",
    explorePools: ["pasta", "vegetarian", "healthy", "high_protein", "hall_expansion"],
    hookLine: "A vegetarian pasta bake that swaps most of the ricotta for cottage cheese and quietly doubles the protein.",
    description:
      "Jumbo pasta shells are stuffed with a cottage cheese, mozzarella, and spinach filling, then baked under marinara until bubbling. It looks and eats like a normal stuffed shells dinner with a genuinely higher protein count per serving.",
    whyCrewsLikeIt:
      "It keeps the comfort of a baked pasta night while quietly packing more protein than a standard ricotta filling, and it is fully vegetarian without anyone needing to be told.",
    mealPrepNotes:
      "Make-ahead: assemble the full pan up to a day ahead and refrigerate unbaked. Storage: refrigerate baked shells up to 4 days. Reheating: cover and reheat at 350°F until warmed through, about 15–20 minutes.",
    stationWorkflow: [
      "Slightly undercook the shells before stuffing — they finish cooking in the oven.",
      "Squeeze spinach very dry so the filling doesn't turn watery.",
      "Cover with foil for the first half of baking so the shells don't dry out on top.",
    ],
    prepMinutes: 25,
    cookMinutes: 40,
    difficulty: "medium",
    crewSizeDefault: 8,
    ingredients: [
      ing("jumbo pasta shells", "1.5", { unit: "lb", notes: "dry", group: "Base" }),
      ing("cottage cheese", "4.5", { unit: "cups", group: "Filling" }),
      ing("shredded mozzarella", "3.5", { unit: "cups", notes: "divided", group: "Filling" }),
      ing("parmesan cheese", "1", { unit: "cup", notes: "grated", group: "Filling" }),
      ing("large eggs", "3", { unit: "each", group: "Filling" }),
      ing("frozen spinach", "20", { unit: "oz", notes: "thawed and squeezed very dry", group: "Filling" }),
      ing("garlic", "2", { unit: "cloves", notes: "minced", group: "Filling" }),
      ing("italian seasoning", "1", { unit: "tbsp", group: "Filling" }),
      ing("marinara sauce", "5", { unit: "cups", group: "Sauce" }),
    ],
    steps: [
      step(1, "Heat the oven and cook the shells", "Heat oven to 375°F. Cook jumbo shells in salted boiling water 2 minutes under the package time so they stay firm enough to stuff. Drain and cool slightly.", { minutes: 12, tempF: 375 }),
      step(2, "Build the filling", "In a large bowl, combine cottage cheese, 2 cups mozzarella, parmesan, eggs, squeezed spinach, garlic, and Italian seasoning until evenly mixed.", { minutes: 8 }),
      step(3, "Stuff the shells", "Spread 1 cup marinara in the bottom of a 9x13 pan. Stuff each shell with a generous spoonful of filling and arrange seam-side up in the pan.", { minutes: 15 }),
      step(4, "Sauce and top", "Pour remaining marinara over the stuffed shells and scatter the remaining mozzarella on top.", { minutes: 5 }),
      step(5, "Bake covered, then uncovered", "Cover with foil and bake 25 minutes, then uncover and bake 10–15 more minutes until bubbling and the cheese on top is golden.", { minutes: 40, tempF: 375 }),
      step(6, "Rest and serve", "Rest 8–10 minutes before serving so the filling sets and shells hold together on the plate.", { minutes: 10 }),
      CALL_INTERRUPTION_STEP(7, "cottage cheese and spinach stuffed shells"),
      LEFTOVERS_PACK_DOWN_STEP(8, "stuffed shells"),
    ],
    proTips: [
      "Prep tip: Squeeze spinach in a clean towel, not just a colander — excess water is the main cause of a soupy bake.",
      "Rookie tip: Slightly undercooking the shells before stuffing keeps them from turning mushy after baking.",
      "A piping bag (or a zip-top bag with the corner cut off) makes stuffing the shells much faster for a big batch.",
    ],
    tonightSpread: buildStructuredTonightSpread(
      "Cottage cheese and spinach stuffed shells",
      ["Garlic bread", "simple green salad"],
      ["Extra parmesan", "red pepper flakes"],
    ),
    leftovers: standardLeftovers("cottage cheese and spinach stuffed shells", [
      "Reheat covered at 350°F rather than microwaving so the shells don't turn rubbery.",
    ]),
    equipment: ["9x13 baking dish", "Large pot", "Mixing bowl", "Colander"],
    nutrition: { calories: 791, protein: 48, carbs: 83, fats: 30, fiber: 6 },
    spiceLevel: "mild",
    cleanupDifficulty: "medium",
    searchTerms: [
      "cottage cheese stuffed shells",
      "vegetarian stuffed shells",
      "high protein pasta bake",
      "spinach stuffed shells",
      "high protein vegetarian dinner",
    ],
    substitutions: [
      "Use part-skim ricotta blended half-and-half with cottage cheese for a more traditional texture.",
      "Use frozen chopped kale instead of spinach.",
      "Use a jarred vodka sauce instead of marinara for a richer bake.",
    ],
  }),
];
