/**
 * Handheld expansion — wraps, pitas, gyros (Firehall-original instructions).
 */
import type { ExpansionRecipeDef } from "../types.js";
import { def, ing, step } from "../recipe-build.js";

export const BATCH_HANDHELD_SOURCE_URLS: Record<string, string> = {
  "chicken-caesar-wraps": "https://www.americastestkitchen.com/recipes/7850-grilled-chicken-caesar-salad",
  "buffalo-chicken-wraps": "https://www.seriouseats.com/buffalo-chicken-wing-recipe",
  "greek-chicken-pitas": "https://www.seriouseats.com/chicken-souvlaki-recipe",
  "beef-gyros-for-the-hall": "https://www.seriouseats.com/gyros-recipe",
  "chicken-shawarma-pitas": "https://www.seriouseats.com/shawarma-recipe",
  "sausage-peppers-on-buns": "https://www.americastestkitchen.com/recipes/6831-sausage-peppers-and-onions",
};

export const BATCH_HANDHELD_WRAP_RECIPES: ExpansionRecipeDef[] = [
  def({
    slug: "chicken-caesar-wraps",
    title: "Chicken Caesar Wraps",
    subtitle: "Grilled chicken, romaine, and Parmesan in flour tortillas",
    category: "crew_feeders",
    protein: "chicken",
    cuisine: "american",
    mealFormat: "handheld",
    explorePools: ["handheld", "chicken", "healthy", "hall_expansion"],
    hookLine: "Caesar salad flavours in a wrap the crew can eat one-handed between calls",
    description:
      "Chicken breasts are seasoned and grilled, then sliced and rolled with chopped romaine, Caesar dressing, and Parmesan in large flour tortillas. Cut on a bias so cross-sections show chicken, greens, and dressing — not a mystery burrito.",
    whyCrewsLikeIt:
      "Caesar is familiar; wraps travel better than salad bowls in the truck. Grilled chicken reads as a real meal, not deli meat, and the line can hold wrapped bundles in foil at 200°F.",
    mealPrepNotes:
      "Marinate chicken up to 4 hours. Wash and dry romaine early — wet greens sog out tortillas. Roll tight, tuck ends, and wrap each in foil. Hold up to 20 minutes in a warm oven; slice just before serving for best cross-section photos and eating.",
    stationWorkflow: [
      "Slice chicken across the grain so strips stay tender in the wrap.",
      "Keep dressing separate until roll time if holding more than 15 minutes.",
      "Lay out a row of tortillas, fill, roll, and foil — assembly-line for 14.",
    ],
    prepMinutes: 20,
    cookMinutes: 20,
    difficulty: "easy",
    crewSizeDefault: 8,
    ingredients: [
      ing("boneless, skinless chicken breasts", "3", { unit: "lb", group: "Chicken" }),
      ing("large flour tortillas", "10", { unit: "count", notes: "10-inch burrito size", group: "Wrap" }),
      ing("romaine hearts", "4", { unit: "count", notes: "chopped", group: "Salad" }),
      ing("Caesar dressing", "1.5", { unit: "cups", group: "Salad" }),
      ing("Parmesan cheese", "1", { unit: "cup", notes: "grated", group: "Salad" }),
      ing("garlic cloves", "3", { unit: "count", notes: "minced", group: "Marinade" }),
      ing("olive oil", "0.25", { unit: "cup", group: "Marinade" }),
      ing("lemon juice", "3", { unit: "tbsp", group: "Marinade" }),
      ing("kosher salt and black pepper", "1", { unit: "batch", group: "Seasoning" }),
    ],
    steps: [
      step(
        1,
        "Marinate chicken and prep the wrap line",
        "Pound chicken to even thickness. Toss with olive oil, garlic, lemon juice, salt, and pepper. Chop romaine and grate Parmesan. Set dressing and tortillas on the line — for 14 firefighters, plan 12–14 wraps across two trays.",
        { minutes: 15 },
      ),
      step(
        2,
        "Grill the chicken",
        "Heat grill or grill pan over medium-high. Grill chicken 5–7 minutes per side until 160°F, then rest 5 minutes and slice into strips. Chicken should show grill marks — that is what sells this as Caesar wraps, not cold deli meat.",
        { minutes: 15, heatLevel: "medium-high" },
      ),
      step(
        3,
        "Build the filling",
        "Toss romaine with enough dressing to coat lightly — not swimming. Fold in half the Parmesan. Taste for salt and acid; Caesar should be bold before it goes in the tortilla.",
        { minutes: 5 },
      ),
      step(
        4,
        "Roll the wraps",
        "Warm tortillas 20 seconds per side on the grill or in a dry skillet. Layer chicken, dressed romaine, and remaining Parmesan across the centre. Fold sides in and roll tight. Cut on a bias for service so grilled chicken, romaine, and dressing show in cross-section.",
        { minutes: 12 },
      ),
      step(
        5,
        "Hold and serve",
        "Wrap each in foil and hold at 200°F up to 20 minutes if calls interrupt. Serve with lemon wedges and extra Parmesan at the line. Do not stack unwrapped wraps — they steam and tear.",
        { minutes: 5 },
      ),
    ],
    proTips: [
      "A light smear of dressing on the tortilla before filling helps every bite taste like Caesar.",
      "If romaine wilts, use hearts only and keep chilled until the last minute.",
      "Substitute grilled chicken thighs if breasts dry out on your grill — pull at 175°F.",
    ],
    tonightSpread: ["Caesar wraps with kettle chips", "Simple tomato soup cups for dunking if you have kettle on"],
    leftovers: ["Chop wraps into a chopped salad for next-day lunch", "Slice chicken for a green salad"],
    equipment: ["Grill or grill pan", "Instant-read thermometer", "Cutting board", "Foil"],
    nutrition: { calories: 520, protein: 42, carbs: 38, fats: 22, fiber: 3 },
    spiceLevel: "mild",
    cleanupDifficulty: "easy",
    searchTerms: ["chicken caesar wrap firehall", "grilled chicken caesar wrap crew"],
    sourceUrl: BATCH_HANDHELD_SOURCE_URLS["chicken-caesar-wraps"],
  }),

  def({
    slug: "buffalo-chicken-wraps",
    title: "Buffalo Chicken Wraps",
    subtitle: "Shredded buffalo chicken with lettuce and ranch in flour tortillas",
    category: "crew_feeders",
    protein: "chicken",
    cuisine: "american",
    mealFormat: "handheld",
    explorePools: ["handheld", "chicken", "game_day", "hall_expansion"],
    hookLine: "Wing-night flavour in a wrap — blue cheese or ranch at the line",
    description:
      "Chicken thighs are simmered, shredded, and tossed in buttery buffalo sauce, then rolled with crisp lettuce and ranch or blue cheese in flour tortillas. Halved wraps show orange buffalo chicken and green lettuce — not a generic chicken wrap.",
    whyCrewsLikeIt:
      "Buffalo dip is already on the game-day roster; wraps give the same flavour without chips-only vibes. Thighs stay juicy when held, and the crew picks ranch or blue cheese like they would at wing night.",
    mealPrepNotes:
      "Shred chicken while warm for clean pulls. Keep buffalo sauce warm in a small pot. Roll just before the line or cut in half and wrap cut ends in foil. Hold halved wraps cut-side up on sheet pans at 200°F up to 15 minutes.",
    stationWorkflow: [
      "Taste buffalo sauce before tossing — it should be spicy, tangy, and lightly buttery, not greasy.",
      "Use iceberg or romaine for crunch that survives 10 minutes in foil.",
      "For 14, split into mild and extra-hot sauce pots if your crew runs both ways.",
    ],
    prepMinutes: 15,
    cookMinutes: 35,
    difficulty: "easy",
    crewSizeDefault: 8,
    ingredients: [
      ing("boneless, skinless chicken thighs", "3", { unit: "lb", group: "Chicken" }),
      ing("low-sodium chicken broth", "2", { unit: "cups", group: "Poach" }),
      ing("hot sauce", "0.75", { unit: "cup", notes: "Frank's-style", group: "Buffalo" }),
      ing("unsalted butter", "4", { unit: "tbsp", group: "Buffalo" }),
      ing("large flour tortillas", "10", { unit: "count", group: "Wrap" }),
      ing("iceberg or romaine lettuce", "1", { unit: "head", notes: "shredded", group: "Fill" }),
      ing("ranch dressing", "1", { unit: "cup", group: "Line", notes: "or blue cheese dressing" }),
      ing("crumbled blue cheese", "0.5", { unit: "cup", group: "Line", notes: "optional" }),
      ing("celery stalks", "6", { unit: "count", notes: "sticks for the line", group: "Sides" }),
    ],
    steps: [
      step(
        1,
        "Poach and shred chicken",
        "Simmer thighs in broth until 165°F, about 18–20 minutes. Transfer to a board, shred with forks while warm, and discard poaching liquid. Shredded meat absorbs buffalo sauce better than cubed breast. Scale poaching batches for 4, 6, 8, 10, or 14 firefighters using the crew scaler.",
        { minutes: 25, heatLevel: "medium" },
      ),
      step(
        2,
        "Make buffalo sauce",
        "Melt butter in a saucepan, whisk in hot sauce, and simmer 2 minutes. Toss shredded chicken with enough sauce to coat well — there should be visible orange coating on every strand.",
        { minutes: 8 },
      ),
      step(
        3,
        "Prep lettuce and warm tortillas",
        "Shred lettuce and chill until rolling. Warm tortillas briefly so they flex without tearing when you pack buffalo chicken and lettuce.",
        { minutes: 8 },
      ),
      step(
        4,
        "Roll and halve",
        "Layer buffalo chicken and lettuce on each tortilla. Drizzle ranch inside or serve on the side. Roll tight, slice in half on a bias, and expose the cut face up on the tray so buffalo chicken and lettuce are obvious.",
        { minutes: 12 },
      ),
      step(
        5,
        "Serve with dressing and celery",
        "Pass ranch or blue cheese and celery at the line. Hold foiled halves at 200°F up to 15 minutes — refresh cut face with a spoon of sauce if a call delays service.",
        { minutes: 5 },
      ),
    ],
    proTips: [
      "A teaspoon of honey in the sauce rounds heat without killing spice.",
      "Do not confuse this with buffalo dip — wraps need less sauce per bite or they leak.",
      "Gloves help when tossing hot buffalo chicken at volume.",
    ],
    tonightSpread: ["Buffalo wraps with celery sticks", "Extra hot sauce for heat seekers"],
    leftovers: ["Buffalo chicken on a salad", "Buffalo chicken on pizza night flatbreads"],
    equipment: ["Large saucepan", "Tongs", "Sheet pans", "Foil"],
    nutrition: { calories: 540, protein: 36, carbs: 42, fats: 24, fiber: 2 },
    spiceLevel: "medium",
    cleanupDifficulty: "easy",
    searchTerms: ["buffalo chicken wrap", "buffalo wrap fire station"],
    sourceUrl: BATCH_HANDHELD_SOURCE_URLS["buffalo-chicken-wraps"],
  }),

  def({
    slug: "greek-chicken-pitas",
    title: "Greek Chicken Pitas",
    subtitle: "Lemon-oregano chicken with cucumber, tomato, and tzatziki in pita",
    category: "crew_feeders",
    protein: "chicken",
    cuisine: "greek",
    mealFormat: "handheld",
    explorePools: ["handheld", "chicken", "healthy", "hall_expansion"],
    hookLine: "Mediterranean pitas with bright lemon-oregano chicken — not shawarma spice",
    description:
      "Chicken is marinated in yogurt, lemon, and oregano, grilled, and tucked into warm pita with cucumber, tomato, red onion, and tzatziki. Open-faced on the line so chicken, pita, and tzatziki are visible before folding.",
    whyCrewsLikeIt:
      "Lighter than a burger run but still filling. Greek bowls exist in the catalog; pitas are the handheld version crews can eat walking to the rig. Feta at the line is optional but popular.",
    mealPrepNotes:
      "Marinate chicken at least 2 hours or overnight. Make tzatziki the day before. Warm pita in foil packets. Assemble open on sheet pans for speed, then fold for eating.",
    stationWorkflow: [
      "Keep cucumber and tomato drained — watery veg breaks pita.",
      "This is lemon-oregano profile; do not use shawarma spice blend on this recipe.",
      "For 14, grill chicken in two waves on two grill pans.",
    ],
    prepMinutes: 25,
    cookMinutes: 20,
    difficulty: "medium",
    crewSizeDefault: 8,
    ingredients: [
      ing("boneless, skinless chicken breasts", "3", { unit: "lb", group: "Chicken" }),
      ing("plain Greek yogurt", "1", { unit: "cup", notes: "marinade", group: "Marinade" }),
      ing("lemon juice", "0.25", { unit: "cup", group: "Marinade" }),
      ing("dried oregano", "2", { unit: "tsp", group: "Marinade" }),
      ing("garlic cloves", "4", { unit: "count", notes: "minced", group: "Marinade" }),
      ing("pita breads", "10", { unit: "count", notes: "pocket or flat", group: "Pita" }),
      ing("English cucumber", "1", { unit: "count", notes: "diced", group: "Veg" }),
      ing("tomatoes", "3", { unit: "large", notes: "diced", group: "Veg" }),
      ing("red onion", "0.5", { unit: "cup", notes: "thinly sliced", group: "Veg" }),
      ing("tzatziki", "2", { unit: "cups", group: "Sauce" }),
      ing("crumbled feta", "1", { unit: "cup", group: "Line", notes: "optional" }),
    ],
    steps: [
      step(
        1,
        "Marinate chicken",
        "Combine yogurt, lemon juice, oregano, garlic, salt, and pepper. Coat chicken and refrigerate at least 2 hours. Remove 30 minutes before grilling if time allows.",
        { minutes: 10 },
      ),
      step(
        2,
        "Grill chicken",
        "Grill over medium-high until 160°F, 5–7 minutes per side. Rest 5 minutes and slice into strips. Chicken should taste lemon-herb bright, not warm-spice shawarma.",
        { minutes: 18, heatLevel: "medium-high" },
      ),
      step(
        3,
        "Prep vegetables and warm pita",
        "Dice cucumber and tomato; salt lightly and drain on paper towels. Warm pita wrapped in foil in a 300°F oven 8 minutes.",
        { minutes: 10, tempF: 300 },
      ),
      step(
        4,
        "Fill pitas for the line",
        "Spread tzatziki inside each pita. Add chicken, cucumber, tomato, and onion. Crumble feta if using. Leave pitas open on trays so the crew sees Greek build before folding.",
        { minutes: 10 },
      ),
      step(
        5,
        "Fold and hold",
        "Fold pitas and wrap in foil. Hold at 200°F up to 20 minutes. Suggested sides: Greek salad or lemon potatoes if you have oven space.",
        { minutes: 5 },
      ),
    ],
    proTips: [
      "English cucumber has fewer seeds and keeps pitas from going soggy.",
      "If pita tears, serve as a chicken-tzatziki plate with pita on the side.",
      "Do not swap in shawarma marinade — crews should taste the difference from shawarma pitas on the same menu cycle.",
    ],
    tonightSpread: ["Greek pitas with simple orzo or rice", "Lemon wedges at the line"],
    leftovers: ["Chicken on a salad with remaining tzatziki", "Pita chips from extra bread"],
    equipment: ["Grill or grill pan", "Mixing bowls", "Foil", "Thermometer"],
    nutrition: { calories: 480, protein: 40, carbs: 44, fats: 14, fiber: 3 },
    spiceLevel: "mild",
    cleanupDifficulty: "easy",
    searchTerms: ["greek chicken pita", "chicken souvlaki pita firehall"],
    sourceUrl: BATCH_HANDHELD_SOURCE_URLS["greek-chicken-pitas"],
  }),

  def({
    slug: "beef-gyros-for-the-hall",
    title: "Beef Gyros",
    subtitle: "Thin-sliced seasoned beef with tzatziki and onion in warm pita",
    category: "crew_feeders",
    protein: "beef",
    cuisine: "greek",
    mealFormat: "handheld",
    explorePools: ["handheld", "beef", "hall_expansion"],
    hookLine: "Sliced beef with gyro spices, tzatziki, and red onion in pita — hall feed style",
    description:
      "Skirt or sirloin is seasoned with gyro-style spices, seared and sliced thin, then served in warm pita with tzatziki, tomato, and red onion. The plate should read beef gyro immediately: sliced meat, white sauce, and pita — not a steak sandwich.",
    whyCrewsLikeIt:
      "Beef breaks the chicken-heavy handheld cycle. Slicing thin after a hard sear mimics vertical-spit texture without a spit in the hall. Crews build their own if you run it open on the line.",
    mealPrepNotes:
      "Freeze beef 20 minutes for easier thin slicing if needed. Seasoning can be mixed ahead. Warm pita in stacks in foil. Hold sliced beef covered with a splash of broth at 140°F.",
    stationWorkflow: [
      "Slice beef as thin as you can after rest — thick slices feel like steak sandwich, not gyro.",
      "Keep tzatziki cold until the last minute.",
      "Red onion can be quick-pickled 30 minutes ahead for authentic bite.",
    ],
    prepMinutes: 20,
    cookMinutes: 25,
    difficulty: "medium",
    crewSizeDefault: 8,
    ingredients: [
      ing("beef skirt or sirloin steak", "3", { unit: "lb", group: "Beef" }),
      ing("olive oil", "3", { unit: "tbsp", group: "Beef" }),
      ing("dried oregano", "2", { unit: "tsp", group: "Spice" }),
      ing("garlic powder", "1", { unit: "tsp", group: "Spice" }),
      ing("ground cumin", "1", { unit: "tsp", group: "Spice" }),
      ing("paprika", "1", { unit: "tsp", group: "Spice" }),
      ing("kosher salt and black pepper", "1", { unit: "batch", group: "Spice" }),
      ing("pita breads", "10", { unit: "count", group: "Pita" }),
      ing("tzatziki", "2", { unit: "cups", group: "Sauce" }),
      ing("tomatoes", "3", { unit: "large", notes: "diced", group: "Veg" }),
      ing("red onion", "1", { unit: "count", notes: "thinly sliced", group: "Veg" }),
    ],
    steps: [
      step(
        1,
        "Season the beef",
        "Pat beef dry. Rub with olive oil, oregano, garlic powder, cumin, paprika, salt, and pepper. Let sit 15 minutes while the grill or cast iron heats.",
        { minutes: 10 },
      ),
      step(
        2,
        "Sear in batches",
        "Sear over high heat 3–4 minutes per side for medium-rare to medium. Rest 8 minutes — carryover finishes cook. Slice as thin as possible against the grain.",
        { minutes: 15, heatLevel: "high" },
      ),
      step(
        3,
        "Warm pita and prep veg",
        "Wrap pita in foil and warm at 300°F. Dice tomato and slice onion. Optional: quick-pickle onion in vinegar 30 minutes ahead.",
        { minutes: 10, tempF: 300 },
      ),
      step(
        4,
        "Build gyros",
        "Spread tzatziki in pita. Layer sliced beef, tomato, and onion. For photos and the line, show one open pita with meat fanned and sauce visible before wrapping the rest.",
        { minutes: 10 },
      ),
      step(
        5,
        "Serve hot",
        "Wrap and foil. Hold beef and pita separately if service delays past 15 minutes — reassemble quick. Fries or simple salad are classic sides at Canadian groceries.",
        { minutes: 5 },
      ),
    ],
    proTips: [
      "A touch of ground cinnamon in the rub is traditional gyro flavour — ¼ teaspoon is enough.",
      "Do not confuse with shawarma pitas — beef gyro is oregano-cumin, not turmeric-heavy.",
      "Sirloin is easier to slice; skirt has more flavour if you can slice thin.",
    ],
    tonightSpread: ["Beef gyros with fries", "Pickled onion jar at the line"],
    leftovers: ["Beef on a salad", "Beef with eggs for breakfast wrap"],
    equipment: ["Cast iron or grill", "Sharp knife", "Foil"],
    nutrition: { calories: 560, protein: 38, carbs: 40, fats: 26, fiber: 2 },
    spiceLevel: "mild",
    cleanupDifficulty: "medium",
    searchTerms: ["beef gyro firehall", "gyro pita crew"],
    sourceUrl: BATCH_HANDHELD_SOURCE_URLS["beef-gyros-for-the-hall"],
  }),

  def({
    slug: "chicken-shawarma-pitas",
    title: "Chicken Shawarma Pitas",
    subtitle: "Warm-spiced chicken with pickles and garlic sauce in pita",
    category: "crew_feeders",
    protein: "chicken",
    cuisine: "middle eastern",
    mealFormat: "handheld",
    explorePools: ["handheld", "chicken", "global", "hall_expansion"],
    hookLine: "Shawarma spice, pickled veg, and garlic-tahini — distinct from Greek lemon pitas",
    description:
      "Chicken thighs marinate in yogurt and a warm shawarma spice blend, roast or grill, and slice into pita with pickled vegetables, tomato, and garlic-tahini sauce. Spice profile and pickles make this read shawarma, not Greek souvlaki.",
    whyCrewsLikeIt:
      "Different from Greek pitas on the same cycle — crews notice turmeric-cumin colour and pickles. Bar-night shawarma exists; this is the handheld pita version with clear pickle garnish.",
    mealPrepNotes:
      "Pickles can be store-bought shawarma-style or quick red onion pickles. Marinate thighs overnight if possible. Slice chicken and hold with pan juices. Assemble open for the line.",
    stationWorkflow: [
      "Shawarma spice should colour the marinade visibly yellow-orange.",
      "Pickled turnip or cabbage from Middle Eastern aisle reads authentic on the line.",
      "Never use lemon-oregano Greek marinade on this recipe — keep pitas distinct.",
    ],
    prepMinutes: 25,
    cookMinutes: 35,
    difficulty: "medium",
    crewSizeDefault: 8,
    ingredients: [
      ing("boneless, skinless chicken thighs", "3", { unit: "lb", group: "Chicken" }),
      ing("plain yogurt", "1", { unit: "cup", group: "Marinade" }),
      ing("lemon juice", "3", { unit: "tbsp", group: "Marinade" }),
      ing("ground cumin", "2", { unit: "tsp", group: "Shawarma spice" }),
      ing("ground coriander", "2", { unit: "tsp", group: "Shawarma spice" }),
      ing("turmeric", "1", { unit: "tsp", group: "Shawarma spice" }),
      ing("paprika", "1", { unit: "tsp", group: "Shawarma spice" }),
      ing("garlic cloves", "6", { unit: "count", notes: "minced", group: "Marinade" }),
      ing("pita breads", "10", { unit: "count", group: "Pita" }),
      ing("pickled vegetables", "2", { unit: "cups", notes: "turnip, cabbage, or pickled onion", group: "Pickles" }),
      ing("tomatoes", "2", { unit: "large", notes: "diced", group: "Veg" }),
      ing("tahini", "0.5", { unit: "cup", group: "Garlic sauce" }),
      ing("garlic cloves", "2", { unit: "count", notes: "for sauce", group: "Garlic sauce" }),
      ing("lemon juice", "2", { unit: "tbsp", notes: "for sauce", group: "Garlic sauce" }),
    ],
    steps: [
      step(
        1,
        "Marinate with shawarma spices",
        "Mix yogurt, lemon, cumin, coriander, turmeric, paprika, and garlic. Coat thighs and marinate at least 4 hours. The marinade should look golden from turmeric — that is the visual cue crews expect.",
        { minutes: 15 },
      ),
      step(
        2,
        "Roast or grill chicken",
        "Roast at 425°F on sheet pans 25–30 minutes or grill until 175°F. Rest and slice thin. Charred edges are good — they sell shawarma flavour.",
        { minutes: 30, tempF: 425, heatLevel: "high" },
      ),
      step(
        3,
        "Make garlic-tahini sauce",
        "Blend tahini, garlic, lemon, and cold water until pourable and seasoned. It should be garlicky and nutty — thinner than tzatziki.",
        { minutes: 8 },
      ),
      step(
        4,
        "Assemble shawarma pitas",
        "Warm pita. Spread garlic sauce, add chicken, pickles (pickled turnip, cabbage, or onion), and tomato. Fan one pita open for the line so pickles and spiced chicken are visible.",
        { minutes: 12 },
      ),
      step(
        5,
        "Wrap and hold",
        "Fold, foil, and hold at 200°F up to 20 minutes. Pickles stay separate if holding longer than 30 minutes to keep crunch.",
        { minutes: 5 },
      ),
    ],
    proTips: [
      "A pinch of cinnamon and cardamom in the spice mix adds depth without tasting sweet.",
      "Store-bought pickled turnip from a Middle Eastern grocer is worth it for authenticity.",
      "Side-by-side with Greek pitas, label trays — rookies confuse them if unlabeled.",
    ],
    tonightSpread: ["Shawarma pitas with fries", "Extra pickles and hot sauce"],
    leftovers: ["Chicken on rice bowl", "Garlic sauce as dip for pita chips"],
    equipment: ["Sheet pans", "Blender or whisk", "Foil"],
    nutrition: { calories: 510, protein: 38, carbs: 46, fats: 18, fiber: 3 },
    spiceLevel: "mild",
    cleanupDifficulty: "easy",
    searchTerms: ["chicken shawarma pita", "shawarma wrap firehall"],
    sourceUrl: BATCH_HANDHELD_SOURCE_URLS["chicken-shawarma-pitas"],
  }),

  def({
    slug: "sausage-peppers-on-buns",
    title: "Sausage & Peppers on Buns",
    subtitle: "Italian sausage and peppers on hoagie rolls for the crew",
    category: "crew_feeders",
    protein: "pork",
    cuisine: "italian",
    mealFormat: "handheld",
    explorePools: ["handheld", "comfort", "hall_expansion"],
    hookLine: "Sheet-pan sausage and peppers piled on hoagie buns — not a plated skillet meal",
    description:
      "Italian sausage links are roasted with bell peppers and onions, split onto hoagie buns, and finished with optional melted provolone. The tray should show sausage, coloured peppers, and long buns — distinct from sausage-peppers-onions skillet dinner.",
    whyCrewsLikeIt:
      "Hoagie feed is fast to eat and scales to fourteen easily. Skillet sausage and peppers already exist in the catalog as a plated dinner; this is the sandwich version crews grab with one hand.",
    mealPrepNotes:
      "Poke sausages before roasting so they do not burst. Hoagies can be split and toasted 5 minutes in the oven. Hold sausage and pepper mix in a hotel pan at 165°F; assemble buns to order if calls interrupt.",
    stationWorkflow: [
      "Use red, yellow, and orange peppers for visual pop in photos.",
      "Split buns and toast cut-side up for structure when piled with sausage.",
      "For 14, use two full sheet pans of sausage and peppers.",
    ],
    prepMinutes: 15,
    cookMinutes: 35,
    difficulty: "easy",
    crewSizeDefault: 8,
    ingredients: [
      ing("Italian sausage links", "4", { unit: "lb", notes: "sweet or hot", group: "Main" }),
      ing("bell peppers", "4", { unit: "count", notes: "sliced", group: "Veg" }),
      ing("yellow onions", "2", { unit: "large", notes: "sliced", group: "Veg" }),
      ing("hoagie or sub rolls", "10", { unit: "count", group: "Buns" }),
      ing("provolone cheese", "12", { unit: "slices", group: "Cheese", notes: "optional" }),
      ing("olive oil", "3", { unit: "tbsp", group: "Roast" }),
      ing("dried oregano", "1", { unit: "tsp", group: "Seasoning" }),
      ing("red wine vinegar", "2", { unit: "tbsp", group: "Finish" }),
    ],
    steps: [
      step(
        1,
        "Prep sausage and vegetables",
        "Slice peppers and onions. Toss with olive oil, oregano, salt, and pepper on rimmed sheet pans. Nestle whole sausage links among vegetables.",
        { minutes: 12 },
      ),
      step(
        2,
        "Roast until browned",
        "Roast at 425°F, turning sausage once, until sausages hit 160°F and peppers are tender with browned edges, 28–32 minutes. Cut sausages on a bias into chunks.",
        { minutes: 32, tempF: 425 },
      ),
      step(
        3,
        "Toast hoagie buns",
        "Split buns and toast cut sides on a sheet pan at 425°F for 4–5 minutes until lightly crisp.",
        { minutes: 8, tempF: 425 },
      ),
      step(
        4,
        "Assemble sandwiches",
        "Pile sausage and peppers into each bun. Add provolone if using and melt under broiler 2 minutes. Splash vinegar over the pan for brightness.",
        { minutes: 10 },
      ),
      step(
        5,
        "Hold and serve",
        "Wrap sandwiches in foil and hold at 200°F up to 25 minutes. Leave one sandwich open on the tray for identification — sausage, peppers, and hoagie bun clearly visible.",
        { minutes: 5 },
      ),
    ],
    proTips: [
      "Sweet and hot sausage mix adds variety without two recipes.",
      "A foil-lined pan saves cleanup when sausage fat renders.",
      "Mustard and hot peppers at the line turn this into a full sub shop spread.",
    ],
    tonightSpread: ["Sausage and pepper hoagies with chips", "Simple green salad"],
    leftovers: ["Chop into pasta with marinara", "Breakfast hash with leftover peppers"],
    equipment: ["Sheet pans", "Instant-read thermometer", "Foil"],
    nutrition: { calories: 620, protein: 28, carbs: 48, fats: 34, fiber: 4 },
    spiceLevel: "mild",
    cleanupDifficulty: "easy",
    searchTerms: ["sausage and peppers sandwich", "italian sausage hoagie firehall"],
    sourceUrl: BATCH_HANDHELD_SOURCE_URLS["sausage-peppers-on-buns"],
  }),
];
