import type { ExpansionRecipeDef } from "../types.js";
import { def, ing, step } from "../recipe-build.js";
import {
  CALL_INTERRUPTION_STEP,
  LEFTOVERS_PACK_DOWN_STEP,
  buildStructuredTonightSpread,
  standardLeftovers,
} from "../../golden-100/recipe-quality/classics-wheel-editorial.js";

/** Wave 1 expansion — bowls, slow cooker, BBQ, budget, one-pot. */
export const BATCH_WAVE1_EXPANSION_RECIPES: ExpansionRecipeDef[] = [
  def({
    slug: "turkey-taco-bowls",
    title: "Turkey Taco Bowls",
    subtitle: "Lean seasoned turkey, cilantro-lime rice, and a full taco topping bar",
    category: "crew_feeders",
    protein: "turkey",
    cuisine: "mexican",
    mealFormat: "bowl",
    explorePools: ["bowl","turkey","healthy","budget","hall_expansion"],
    hookLine: "Taco-night energy with lean turkey that still browns hard and feeds ten.",
    description: "Seasoned ground turkey over cilantro-lime rice with black beans, corn, lettuce, pico, cheddar, sour cream, and crunchy tortilla strips.",
    whyCrewsLikeIt: "Turkey keeps the grocery bill and grease down without tasting like diet food when you brown it hot and season it properly.",
    mealPrepNotes: "Make-ahead: brown turkey and cook rice up to one day early. Storage: cool turkey, rice, beans, and cold toppings separately for 3 days. Reheating: cover turkey and rice with a splash of water or stock and heat to 165°F, then rebuild with cold toppings.",
    stationWorkflow: ["Start rice before browning turkey.","Hold turkey, beans, and corn covered at 140°F or above.","Keep dairy cold until the final pass."],
    prepMinutes: 15,
    cookMinutes: 25,
    difficulty: "easy",
    crewSizeDefault: 10,
    ingredients: [
      ing("ground turkey", "3.5", { unit: "lb", group: "Protein" }),
      ing("taco seasoning", "4", { unit: "tbsp", group: "Seasoning" }),
      ing("long-grain rice", "3", { unit: "cups", notes: "uncooked", group: "Base" }),
      ing("lime juice", "0.25", { unit: "cup", group: "Base" }),
      ing("cilantro", "0.5", { unit: "cup", notes: "chopped", group: "Base" }),
      ing("black beans", "2", { unit: "cans", group: "Hot bar" }),
      ing("corn", "3", { unit: "cups", group: "Hot bar" }),
      ing("shredded lettuce", "6", { unit: "cups", group: "Cold bar" }),
      ing("pico de gallo", "3", { unit: "cups", group: "Cold bar" }),
      ing("cheddar cheese", "3", { unit: "cups", group: "Cold bar" }),
      ing("sour cream", "2", { unit: "cups", group: "Cold bar" }),
      ing("tortilla strips", "3", { unit: "cups", group: "Finish" }),
    ],
    steps: [
      step(1, "Stage the turkey taco mise", "Drain beans, chop cilantro, and set lettuce, cheese, sour cream, pico, and strips in separate pans. Keep dairy over ice. Measure taco seasoning and lime now so you are not hunting for them while turkey is browning.", { minutes: 15 }),
      step(2, "Steam cilantro-lime rice", "Rinse rice until the water runs mostly clear. Boil with 5 1/2 cups salted water, cover, and cook on low 18 minutes without lifting the lid. Rest 10 minutes, fluff, then fold in lime and cilantro. Peeking mid-cook leaves crunchy cores.", { minutes: 28, heatLevel: "low" }),
      step(3, "Heat the skillet for turkey", "Break turkey into loose pieces and keep 1/2 cup water ready beside the seasoning. Heat a 14-inch skillet over medium-high until oil shimmers. Starting turkey in a cool pan leaves it gray and watery.", { minutes: 5, heatLevel: "medium-high" }),
      step(4, "Brown the turkey hard", "Add turkey, leave it untouched 90 seconds, then crumble and cook 8–10 minutes until browned with no pink. Drain pooled liquid, stir in seasoning and water, and simmer 3 minutes until coated. Confirm 165°F.", { minutes: 12, heatLevel: "medium-high" }),
      step(5, "Warm beans and toast corn", "Warm drained beans with a splash of water over medium-low. Toast corn in a dry skillet 4–5 minutes until a few kernels brown. Keep them separate so bean liquid does not steam the corn soft.", { minutes: 8, heatLevel: "medium" }),
      step(6, "Set cold taco sauces", "Loosen sour cream with a squeeze of lime. Hold pico drained so it does not flood the rice. Keep strips in a dry container until the last second.", { minutes: 5 }),
      step(7, "Hold hot turkey components", "Move rice, turkey, beans, and corn into covered hotel pans above 140°F in a 200°F oven. Taste turkey with rice and adjust salt or lime before service.", { minutes: 5, heatLevel: "low", tempF: 200 }),
      step(8, "Scoop turkey taco bowls", "Scoop rice first, then turkey, beans, and corn. Add lettuce on the cool side of the bowl so heat does not wilt it into slime.", { minutes: 8 }),
      step(9, "Finish with crunch and dairy", "Add pico, cheddar, sour cream, and tortilla strips last. Put hot sauce at the end of the line for heat seekers.", { minutes: 5 }),
      step(10, "Send the turkey taco line", "Pass bowls with lime wedges and keep covered turkey and rice for late returns. Refill pico in small amounts so water does not pool on the table.", { minutes: 5 }),
      CALL_INTERRUPTION_STEP(11, "seasoned ground turkey"),
      LEFTOVERS_PACK_DOWN_STEP(12, "seasoned ground turkey"),
    ],
    proTips: ["Prep tip: Turkey releases more water than beef — drain before seasoning.","Rookie tip: Do not crowd the skillet or the turkey steams gray.","Use a #8 scoop for rice so portions stay even."],
    tonightSpread: buildStructuredTonightSpread("Turkey taco bowls", ["Tortilla chips","lime wedges"], ["Sour cream","hot sauce"]),
    leftovers: standardLeftovers("seasoned ground turkey", ["Turn leftover turkey into next-shift quesadillas or nachos."]),
    equipment: ["Large skillet","Rice pot","Hotel pans","Instant-read thermometer"],
    nutrition: {"calories":580,"protein":42,"carbs":60,"fats":18,"fiber":11},
    spiceLevel: "mild",
    cleanupDifficulty: "easy",
    searchTerms: ["turkey taco bowls","ground turkey firehall dinner","healthy taco bowls","crew turkey dinner"],
    substitutions: ["Use ground chicken for turkey.","Use cauliflower rice.","Swap pinto beans for black beans."],
  }),
  def({
    slug: "peanut-chicken-rice-bowls",
    title: "Peanut Chicken Rice Bowls",
    subtitle: "Saucy chicken, crunchy vegetables, and rice for ten",
    category: "crew_feeders",
    protein: "chicken",
    cuisine: "Thai-inspired",
    mealFormat: "bowls",
    explorePools: ["bowls","weeknight"],
    hookLine: "A creamy peanut sauce makes inexpensive chicken and vegetables feel like a hall favourite.",
    description: "Tender chicken, jasmine rice, cabbage, carrots, and peanut sauce make a filling build-your-own bowl.",
    whyCrewsLikeIt: "The sauce can be made ahead and the toppings hold well for staggered dinner breaks.",
    mealPrepNotes: "Make-ahead: cook rice and sauce up to 2 days ahead. Storage: refrigerate components separately for 3 days. Reheating: heat chicken to 165°F before serving.",
    stationWorkflow: ["Start rice and sauce","Cook chicken and vegetables","Build bowls with toppings"],
    prepMinutes: 25,
    cookMinutes: 25,
    difficulty: "easy",
    crewSizeDefault: 10,
    ingredients: [
      ing("boneless chicken thighs", "5", { unit: "lb" }),
      ing("jasmine rice", "5", { unit: "cups" }),
      ing("peanut butter", "1.5", { unit: "cups" }),
      ing("shredded cabbage", "2", { unit: "heads" }),
      ing("carrots", "2", { unit: "lb" }),
      ing("lime", "4", { unit: "each" }),
    ],
    steps: [
      step(1, "Rinse rice", "Rinse rice until the water is less cloudy, then cook with water in a covered pot."),
      step(2, "Whisk sauce", "Whisk peanut butter, soy sauce, lime juice, warm water, and chili sauce until pourable."),
      step(3, "Cut chicken", "Cut thighs into bite-size pieces so they cook evenly; wash hands and board afterward."),
      step(4, "Heat pan", "Heat a wide skillet over medium-high until a drop of water sizzles, then add oil."),
      step(5, "Brown chicken", "Cook chicken in batches without crowding, turning until browned and 165°F in the thickest piece."),
      step(6, "Cook vegetables", "Stir cabbage and carrots in the hot pan for 3 minutes so they soften but remain crisp."),
      step(7, "Sauce chicken", "Return chicken to the skillet and toss with half the peanut sauce; loosen with water if it clumps."),
      step(8, "Fluff rice", "Rest cooked rice covered for 5 minutes, then fluff gently with a fork."),
      step(9, "Check heat", "Hold chicken above 140°F and keep cold toppings below 40°F until the meal break."),
      step(10, "Build bowls", "Spoon rice into bowls, add sauced chicken and vegetables, then drizzle remaining sauce."),
      CALL_INTERRUPTION_STEP(11, "Chicken thighs"),
      LEFTOVERS_PACK_DOWN_STEP(12, "Chicken thighs"),
    ],
    proTips: ["Thin peanut sauce with hot water, not oil.","Keep lime wedges separate for bright flavour.","Use sunflower butter for a peanut-free crew."],
    tonightSpread: buildStructuredTonightSpread("Peanut chicken bowls", ["cucumber salad","orange wedges"], ["lime wedges","chili crisp","crushed peanuts"]),
    leftovers: standardLeftovers("Chicken thighs", ["Turn leftovers into cold noodle salad."]),
    equipment: ["rice cooker or stockpot","wide skillet","instant-read thermometer"],
    nutrition: {"calories":690,"protein":42,"carbs":72,"fats":27,"fiber":7},
    spiceLevel: "medium",
    cleanupDifficulty: "medium",
    searchTerms: ["peanut chicken rice bowls","firehall chicken bowls","Thai chicken crew dinner","peanut sauce meal prep"],
    substitutions: ["Use tofu or chickpeas for chicken.","Use brown rice or cauliflower rice."],
  }),
  def({
    slug: "firehall-gyro-bowls",
    title: "Firehall Gyro Bowls",
    subtitle: "Greek-spiced beef, rice, vegetables, and tzatziki",
    category: "crew_feeders",
    protein: "beef",
    cuisine: "Greek",
    mealFormat: "bowls",
    explorePools: ["bowls","crew_feeders"],
    hookLine: "All the gyro flavours without a late-night pita assembly line.",
    description: "Seasoned ground beef is served over lemon rice with cucumber, tomato, onion, and cool tzatziki.",
    whyCrewsLikeIt: "Crew members can control sauces and fresh toppings while the hot base stays in one pan.",
    mealPrepNotes: "Make-ahead: chop vegetables and mix tzatziki 1 day ahead. Storage: refrigerate beef and rice for 3 days. Reheating: reheat beef to 165°F.",
    stationWorkflow: ["Cook lemon rice","Brown seasoned beef","Set up cold toppings"],
    prepMinutes: 25,
    cookMinutes: 25,
    difficulty: "easy",
    crewSizeDefault: 10,
    ingredients: [
      ing("lean ground beef", "5", { unit: "lb" }),
      ing("long-grain rice", "5", { unit: "cups" }),
      ing("cucumber", "4", { unit: "each" }),
      ing("tomatoes", "3", { unit: "lb" }),
      ing("tzatziki", "5", { unit: "cups" }),
      ing("red onion", "2", { unit: "each" }),
    ],
    steps: [
      step(1, "Cook rice", "Cook rinsed rice in salted water, keeping the lid closed so steam finishes the grains."),
      step(2, "Season beef", "Mix beef with oregano, garlic, cumin, salt, and pepper before it reaches the hot pan."),
      step(3, "Dice vegetables", "Dice cucumber and tomatoes into small pieces; keep them chilled in separate pans."),
      step(4, "Brown beef", "Cook beef in a wide skillet, breaking up large pieces with a sturdy spoon."),
      step(5, "Drain fat", "Pour off excess fat carefully, leaving a thin coating so the spices do not scorch."),
      step(6, "Finish beef", "Add a splash of water and cook until no pink remains and the beef reaches 165°F."),
      step(7, "Season rice", "Fold lemon zest, lemon juice, and parsley into the hot rice without mashing it."),
      step(8, "Taste tzatziki", "Stir tzatziki and adjust with lemon; keep it cold rather than warming it."),
      step(9, "Hold safely", "Keep beef and rice covered above 140°F while toppings stay refrigerated."),
      step(10, "Assemble bowls", "Layer lemon rice, beef, vegetables, onion, and a spoonful of tzatziki in each bowl."),
      CALL_INTERRUPTION_STEP(11, "Lean ground beef"),
      LEFTOVERS_PACK_DOWN_STEP(12, "Lean ground beef"),
    ],
    proTips: ["Drain watery tomatoes before setting them out.","Offer feta separately for salt control.","Warm pitas are optional alongside bowls."],
    tonightSpread: buildStructuredTonightSpread("Greek beef gyro bowls", ["warm pita","Greek salad"], ["tzatziki","feta","hot sauce"]),
    leftovers: standardLeftovers("Lean ground beef", ["Stuff leftover beef into breakfast wraps."]),
    equipment: ["stockpot","wide skillet","hotel pans"],
    nutrition: {"calories":640,"protein":39,"carbs":68,"fats":23,"fiber":5},
    spiceLevel: "mild",
    cleanupDifficulty: "medium",
    searchTerms: ["gyro bowls for a crowd","Greek beef rice bowls","firehall gyro dinner","ground beef meal for ten"],
    substitutions: ["Use ground lamb or turkey.","Use quinoa instead of rice."],
  }),
  def({
    slug: "egg-roll-in-a-bowl-crew",
    title: "Egg Roll in a Bowl for the Crew",
    subtitle: "Fast pork and cabbage skillet with takeout flavour",
    category: "crew_feeders",
    protein: "pork",
    cuisine: "Chinese-American",
    mealFormat: "skillet",
    explorePools: ["bowls","one_pot","budget"],
    hookLine: "The best part of an egg roll becomes a fast, lower-mess crew skillet.",
    description: "Ground pork, cabbage, carrots, ginger, and sesame are stir-fried and served over rice.",
    whyCrewsLikeIt: "It uses one large pan and forgiving ingredients that can wait for a call.",
    mealPrepNotes: "Make-ahead: shred vegetables and mix sauce 2 days ahead. Storage: refrigerate for 3 days. Reheating: heat pork mixture to 165°F.",
    stationWorkflow: ["Cook rice","Brown pork","Stir-fry cabbage and sauce"],
    prepMinutes: 20,
    cookMinutes: 20,
    difficulty: "easy",
    crewSizeDefault: 10,
    ingredients: [
      ing("ground pork", "5", { unit: "lb" }),
      ing("coleslaw mix", "5", { unit: "lb" }),
      ing("rice", "5", { unit: "cups" }),
      ing("soy sauce", "1", { unit: "cup" }),
      ing("fresh ginger", "0.5", { unit: "cup" }),
      ing("green onions", "3", { unit: "bunches" }),
    ],
    steps: [
      step(1, "Start rice", "Start rice first because it needs covered steaming time while the skillet cooks."),
      step(2, "Mix sauce", "Stir soy sauce, ginger, garlic, sesame oil, and a little brown sugar in a bowl."),
      step(3, "Heat skillet", "Heat a large skillet or griddle over medium-high and add a thin layer of oil."),
      step(4, "Brown pork", "Break pork into small crumbles and cook until browned with no pink showing."),
      step(5, "Confirm temperature", "Check several pork crumbles; they must reach 165°F before holding."),
      step(6, "Add cabbage", "Add coleslaw mix in handfuls, stirring after each addition so it contacts the heat."),
      step(7, "Pour sauce", "Pour sauce around the pan edge and toss for 2 minutes; avoid soaking the cabbage."),
      step(8, "Finish texture", "Stop cooking when cabbage is wilted but still has crunch, not limp and wet."),
      step(9, "Hold components", "Keep pork mixture above 140°F and fluff rice just before the break."),
      step(10, "Top bowls", "Spoon rice and pork mixture into bowls, then scatter green onions and sesame seeds."),
      CALL_INTERRUPTION_STEP(11, "Ground pork"),
      LEFTOVERS_PACK_DOWN_STEP(12, "Ground pork"),
    ],
    proTips: ["Use a griddle for the fastest cabbage cook.","Add chili oil at the table.","Do not salt early; soy sauce is salty."],
    tonightSpread: buildStructuredTonightSpread("Pork egg roll skillet bowls", ["mandarin oranges","edamame"], ["chili oil","sesame seeds","soy sauce"]),
    leftovers: standardLeftovers("Ground pork", ["Fold into lettuce wraps the next day."]),
    equipment: ["large skillet or griddle","rice cooker","thermometer"],
    nutrition: {"calories":580,"protein":35,"carbs":56,"fats":24,"fiber":6},
    spiceLevel: "mild",
    cleanupDifficulty: "easy",
    searchTerms: ["egg roll in a bowl crowd","ground pork cabbage crew meal","one pan firehall dinner","budget bowl recipe"],
    substitutions: ["Use ground turkey for pork.","Use cauliflower rice for lower carbs."],
  }),
  def({
    slug: "salmon-rice-bowls-crew",
    title: "Salmon Rice Bowls for the Crew",
    subtitle: "Roasted salmon with rice, cucumbers, and sesame dressing",
    category: "crew_feeders",
    protein: "salmon",
    cuisine: "Japanese-inspired",
    mealFormat: "bowls",
    explorePools: ["bowls","healthy"],
    hookLine: "Sheet-pan salmon keeps a seafood dinner practical for a ten-person shift.",
    description: "Soy-glazed salmon, rice, cucumbers, avocado, and a sesame drizzle make a bright crew meal.",
    whyCrewsLikeIt: "The salmon roasts hands-off while rice and cold toppings are organized.",
    mealPrepNotes: "Make-ahead: mix dressing and slice vegetables 1 day ahead. Storage: refrigerate salmon 2 days. Reheating: reheat salmon to 165°F if serving hot leftovers.",
    stationWorkflow: ["Cook rice","Roast glazed salmon","Build chilled toppings"],
    prepMinutes: 25,
    cookMinutes: 20,
    difficulty: "medium",
    crewSizeDefault: 10,
    ingredients: [
      ing("salmon fillets", "5", { unit: "lb" }),
      ing("sushi rice", "5", { unit: "cups" }),
      ing("cucumbers", "4", { unit: "each" }),
      ing("avocados", "6", { unit: "each" }),
      ing("soy sauce", "0.75", { unit: "cup" }),
      ing("sesame dressing", "2", { unit: "cups" }),
    ],
    steps: [
      step(1, "Heat oven", "Heat oven to 400°F and line sheet pans so the salmon does not stick."),
      step(2, "Cook rice", "Rinse sushi rice and cook it covered; do not lift the lid during the steaming time."),
      step(3, "Portion salmon", "Check fillets for pin bones and arrange them skin-side down with space between pieces."),
      step(4, "Glaze fish", "Brush salmon with soy, honey, and ginger glaze, saving clean glaze for the end."),
      step(5, "Roast salmon", "Roast until the thickest fillet flakes and reaches 145°F; avoid drying thin tail pieces."),
      step(6, "Slice cucumbers", "Slice cucumbers thinly and toss with rice vinegar and a pinch of salt."),
      step(7, "Prepare avocado", "Cut avocado just before service and cover tightly so it does not brown."),
      step(8, "Finish glaze", "Simmer reserved untouched glaze for 1 minute, then brush a light coat over cooked salmon."),
      step(9, "Hold safely", "Keep cooked salmon covered above 140°F; never leave fish at room temperature."),
      step(10, "Build bowls", "Portion rice, salmon, cucumber, avocado, and sesame dressing into each bowl."),
      CALL_INTERRUPTION_STEP(11, "Salmon fillets"),
      LEFTOVERS_PACK_DOWN_STEP(12, "Salmon fillets"),
    ],
    proTips: ["Use frozen salmon thawed under refrigeration.","Keep skin on during roasting for easier handling.","Offer nori strips separately."],
    tonightSpread: buildStructuredTonightSpread("Sesame salmon rice bowls", ["miso soup","seaweed salad"], ["sriracha mayo","nori strips","pickled ginger"]),
    leftovers: standardLeftovers("Salmon fillets", ["Flake leftover salmon into fried rice."]),
    equipment: ["sheet pans","rice cooker","fish spatula","thermometer"],
    nutrition: {"calories":720,"protein":43,"carbs":70,"fats":29,"fiber":6},
    spiceLevel: "mild",
    cleanupDifficulty: "medium",
    searchTerms: ["salmon rice bowls for a crowd","sheet pan salmon crew dinner","healthy firehall seafood","sesame salmon bowls"],
    substitutions: ["Use steelhead trout for salmon.","Use edamame instead of avocado."],
  }),
  def({
    slug: "korean-turkey-rice-bowls",
    title: "Korean Turkey Rice Bowls",
    subtitle: "Sweet-spicy turkey with rice and quick pickles",
    category: "crew_feeders",
    protein: "turkey",
    cuisine: "Korean-inspired",
    mealFormat: "bowls",
    explorePools: ["bowls","budget"],
    hookLine: "Ground turkey gets a bold gochujang glaze that disappears fast.",
    description: "Turkey is simmered in a garlicky Korean-style sauce with rice, cucumber, and carrots.",
    whyCrewsLikeIt: "Fast-cooking ground meat makes this easy to pause and restart around calls.",
    mealPrepNotes: "Make-ahead: mix sauce and pickle cucumbers 2 days ahead. Storage: refrigerate for 3 days. Reheating: heat turkey to 165°F.",
    stationWorkflow: ["Start rice","Cook glazed turkey","Add crisp toppings"],
    prepMinutes: 20,
    cookMinutes: 20,
    difficulty: "easy",
    crewSizeDefault: 10,
    ingredients: [
      ing("ground turkey", "5", { unit: "lb" }),
      ing("rice", "5", { unit: "cups" }),
      ing("gochujang", "0.75", { unit: "cup" }),
      ing("cucumbers", "4", { unit: "each" }),
      ing("carrots", "2", { unit: "lb" }),
      ing("green onions", "3", { unit: "bunches" }),
    ],
    steps: [
      step(1, "Cook rice", "Cook rice in lightly salted water and keep it covered after the heat is off."),
      step(2, "Mix glaze", "Whisk gochujang, soy sauce, brown sugar, garlic, and water until smooth."),
      step(3, "Quick-pickle cucumber", "Toss sliced cucumber with vinegar, sugar, and salt, then chill while turkey cooks."),
      step(4, "Heat skillet", "Heat a wide skillet over medium-high and add oil before the turkey."),
      step(5, "Brown turkey", "Break turkey into fine pieces and cook until all pink colour is gone."),
      step(6, "Verify turkey", "Check the centre of several pieces; ground turkey must reach 165°F."),
      step(7, "Glaze meat", "Pour in glaze and simmer until it coats the turkey instead of pooling in the pan."),
      step(8, "Prep carrots", "Julienne carrots or use matchsticks, keeping them raw for crunch."),
      step(9, "Hold hot base", "Cover turkey and rice and keep both above 140°F during a delayed meal break."),
      step(10, "Serve bowls", "Layer rice, turkey, cucumber pickles, carrots, and green onions in each bowl."),
      CALL_INTERRUPTION_STEP(11, "Ground turkey"),
      LEFTOVERS_PACK_DOWN_STEP(12, "Ground turkey"),
    ],
    proTips: ["Use mild gochujang for a mixed crew.","Add water if glaze becomes sticky.","Fried eggs make a hearty add-on."],
    tonightSpread: buildStructuredTonightSpread("Korean turkey rice bowls", ["kimchi","steamed edamame"], ["gochujang","sesame seeds","sriracha"]),
    leftovers: standardLeftovers("Ground turkey", ["Use cold leftovers in lunch lettuce cups."]),
    equipment: ["rice cooker","wide skillet","thermometer"],
    nutrition: {"calories":610,"protein":38,"carbs":76,"fats":17,"fiber":5},
    spiceLevel: "medium",
    cleanupDifficulty: "easy",
    searchTerms: ["Korean turkey rice bowls","ground turkey firehall dinner","gochujang meal for ten","budget Korean bowls"],
    substitutions: ["Use ground chicken for turkey.","Use sambal for gochujang."],
  }),
  def({
    slug: "leftover-roast-beef-bowls",
    title: "Leftover Roast Beef Bowls",
    subtitle: "Smart roast-beef remix with gravy and vegetables",
    category: "crew_feeders",
    protein: "beef",
    cuisine: "Canadian",
    mealFormat: "bowls",
    explorePools: ["bowls","leftovers","budget"],
    hookLine: "Turn yesterday's roast into a complete dinner instead of a repeat plate.",
    description: "Thin roast beef is warmed gently with gravy over mashed potatoes, peas, and carrots.",
    whyCrewsLikeIt: "It protects expensive leftover beef from overcooking and feeds a crew quickly.",
    mealPrepNotes: "Make-ahead: dice vegetables and make gravy 2 days ahead. Storage: refrigerate for 3 days. Reheating: heat beef and gravy to 165°F before serving.",
    stationWorkflow: ["Mash potatoes","Warm gravy and beef","Steam vegetables"],
    prepMinutes: 20,
    cookMinutes: 30,
    difficulty: "easy",
    crewSizeDefault: 10,
    ingredients: [
      ing("cooked roast beef", "5", { unit: "lb" }),
      ing("potatoes", "10", { unit: "lb" }),
      ing("beef gravy", "8", { unit: "cups" }),
      ing("frozen peas", "3", { unit: "lb" }),
      ing("carrots", "3", { unit: "lb" }),
      ing("butter", "0.5", { unit: "lb" }),
    ],
    steps: [
      step(1, "Boil potatoes", "Cover cubed potatoes with cold salted water and simmer until a fork slides in easily."),
      step(2, "Warm gravy", "Heat gravy in a wide pot, whisking the bottom so it does not scorch."),
      step(3, "Slice beef", "Slice cold roast beef thinly across the grain for tender bites."),
      step(4, "Steam carrots", "Steam carrots until just tender, checking that they are not turning mushy."),
      step(5, "Mash potatoes", "Drain potatoes well, then mash with warm milk and butter so they stay fluffy."),
      step(6, "Add peas", "Stir frozen peas into the carrots for the final 3 minutes of steaming."),
      step(7, "Warm beef gently", "Submerge beef slices in simmering gravy; boiling hard will make leftovers dry."),
      step(8, "Check temperature", "Heat the beef and gravy through to 165°F before holding."),
      step(9, "Hold stations", "Cover mashed potatoes and vegetables and keep hot foods above 140°F."),
      step(10, "Build bowls", "Spoon potatoes, vegetables, beef, and gravy into deep bowls for a tidy serving."),
      CALL_INTERRUPTION_STEP(11, "Cooked roast beef"),
      LEFTOVERS_PACK_DOWN_STEP(12, "Cooked roast beef"),
    ],
    proTips: ["Add horseradish to gravy for adults who want heat.","Use leftover prime rib only at a gentle simmer.","Save vegetable scraps for stock."],
    tonightSpread: buildStructuredTonightSpread("Roast beef and gravy bowls", ["dinner rolls","green salad"], ["horseradish","black pepper","ketchup"]),
    leftovers: standardLeftovers("Cooked roast beef", ["Use any remaining beef in hash tomorrow."]),
    equipment: ["stockpot","steamer basket","potato masher","thermometer"],
    nutrition: {"calories":650,"protein":42,"carbs":62,"fats":25,"fiber":8},
    spiceLevel: "mild",
    cleanupDifficulty: "medium",
    searchTerms: ["leftover roast beef bowls","roast beef crew dinner","firehall leftover meal","beef gravy potato bowls"],
    substitutions: ["Use turkey and poultry gravy.","Use instant mashed potatoes when rushed."],
  }),
  def({
    slug: "mississippi-pot-roast-crew",
    title: "Mississippi Pot Roast for the Crew",
    subtitle: "Tangy pepperoncini roast made for a busy shift",
    category: "crew_feeders",
    protein: "beef",
    cuisine: "American",
    mealFormat: "slow_cooker",
    explorePools: ["slow_cooker","crew_feeders"],
    hookLine: "Start this rich, tangy roast before breakfast and dinner is waiting.",
    description: "Chuck roast cooks low and slow with pepperoncini, ranch seasoning, and beef gravy.",
    whyCrewsLikeIt: "The slow cooker tolerates interrupted schedules and holds shredded beef well.",
    mealPrepNotes: "Make-ahead: season roast overnight. Storage: refrigerate for 3 days. Reheating: reheat shredded beef and juices to 165°F.",
    stationWorkflow: ["Start cooker in morning","Shred roast at dinner","Hold with juices"],
    prepMinutes: 15,
    cookMinutes: 480,
    difficulty: "easy",
    crewSizeDefault: 10,
    ingredients: [
      ing("chuck roast", "10", { unit: "lb" }),
      ing("pepperoncini", "2", { unit: "jars" }),
      ing("beef broth", "4", { unit: "cups" }),
      ing("ranch seasoning", "2", { unit: "packets" }),
      ing("potatoes", "10", { unit: "lb" }),
      ing("carrots", "3", { unit: "lb" }),
    ],
    steps: [
      step(1, "Morning start", "At breakfast, place roast in a 6-to-8-quart slow cooker and wash hands after handling raw beef."),
      step(2, "Season roast", "Sprinkle ranch seasoning over the roast and add broth and pepperoncini with some brine."),
      step(3, "Set cooker", "Cover and cook on low for 8 hours; do not repeatedly lift the lid because heat escapes."),
      step(4, "Check liquid", "At mid-shift, confirm there is liquid around the roast and add broth if the pot looks dry."),
      step(5, "Cook potatoes", "Near dinner, boil potatoes until fork-tender and steam carrots until tender-crisp."),
      step(6, "Test tenderness", "Slide a fork into the roast; it should twist easily without forcing."),
      step(7, "Shred beef", "Move roast to a tray and shred with two forks, discarding large pieces of fat."),
      step(8, "Finish juices", "Skim excess fat from the cooker juices, then return shredded beef and stir."),
      step(9, "Hold safely", "Set slow cooker to warm only after the beef is above 165°F; keep it above 140°F."),
      step(10, "Serve dinner", "Spoon juicy beef over mashed potatoes with carrots and pepperoncini on the side."),
      CALL_INTERRUPTION_STEP(11, "Chuck roast"),
      LEFTOVERS_PACK_DOWN_STEP(12, "Chuck roast"),
    ],
    proTips: ["Use two slow cookers if yours cannot safely hold the volume.","Pepperoncini add tang, not overwhelming heat.","Keep beef covered with liquid on warm."],
    tonightSpread: buildStructuredTonightSpread("Mississippi pot roast", ["mashed potatoes","buttered carrots"], ["pepperoncini","horseradish","gravy"]),
    leftovers: standardLeftovers("Chuck roast", ["Make roast-beef grilled cheese sandwiches."]),
    equipment: ["two slow cookers","potato pot","thermometer"],
    nutrition: {"calories":730,"protein":48,"carbs":58,"fats":32,"fiber":7},
    spiceLevel: "mild",
    cleanupDifficulty: "medium",
    searchTerms: ["Mississippi pot roast for a crowd","slow cooker firehall roast","pepperoncini chuck roast","crock pot meal for ten"],
    substitutions: ["Use beef stew meat for chuck roast.","Use Italian seasoning for ranch mix."],
  }),
  def({
    slug: "white-chicken-chili-crock",
    title: "White Chicken Chili Crock",
    subtitle: "Creamy bean-and-chicken chili for ten",
    category: "crew_feeders",
    protein: "chicken",
    cuisine: "Southwestern",
    mealFormat: "slow_cooker",
    explorePools: ["slow_cooker","budget"],
    hookLine: "A mild, creamy slow-cooker chili that the crew can top their own way.",
    description: "Chicken, white beans, green chiles, corn, and a creamy broth cook into a filling chili.",
    whyCrewsLikeIt: "It is economical, holds well, and toppings make it work for different appetites.",
    mealPrepNotes: "Make-ahead: measure spices and drain beans the night before. Storage: refrigerate 3 days. Reheating: bring chili and chicken to 165°F.",
    stationWorkflow: ["Load cooker in morning","Shred chicken","Set out toppings"],
    prepMinutes: 20,
    cookMinutes: 420,
    difficulty: "easy",
    crewSizeDefault: 10,
    ingredients: [
      ing("chicken breasts", "5", { unit: "lb" }),
      ing("white beans", "8", { unit: "cans" }),
      ing("green chiles", "4", { unit: "cans" }),
      ing("chicken broth", "12", { unit: "cups" }),
      ing("corn", "3", { unit: "lb" }),
      ing("cream cheese", "2", { unit: "lb" }),
    ],
    steps: [
      step(1, "Morning start", "Place chicken in the slow cooker with beans, green chiles, broth, cumin, and onion."),
      step(2, "Set heat", "Cover and cook on low for 7 hours; keep the cooker plugged into a stable outlet."),
      step(3, "Check chicken", "At dinner time, check the thickest breast has reached at least 165°F before shredding."),
      step(4, "Shred chicken", "Lift chicken to a clean tray, shred it with forks, and return it to the hot chili."),
      step(5, "Add corn", "Stir in frozen corn so it heats through without becoming dull and soft."),
      step(6, "Melt cream cheese", "Add cubed cream cheese and stir every few minutes until no white lumps remain."),
      step(7, "Adjust thickness", "Mash one cup of beans against the pot wall if the chili needs more body."),
      step(8, "Taste carefully", "Taste only with a clean spoon, then add salt or lime without over-salting canned beans."),
      step(9, "Hold chili", "Switch to warm after it is steaming hot; verify it stays above 140°F."),
      step(10, "Serve bowls", "Ladle chili into bowls and let crew add cheese, cilantro, chips, and lime."),
      CALL_INTERRUPTION_STEP(11, "Chicken breasts"),
      LEFTOVERS_PACK_DOWN_STEP(12, "Chicken breasts"),
    ],
    proTips: ["Keep dairy out until the final hour.","Use two ladles so toppings stay separate.","Thin with hot broth, not cold water."],
    tonightSpread: buildStructuredTonightSpread("White chicken chili", ["tortilla chips","cornbread"], ["shredded cheese","cilantro","lime wedges"]),
    leftovers: standardLeftovers("Chicken breasts", ["Use leftovers as enchilada filling."]),
    equipment: ["slow cooker","ladle","thermometer"],
    nutrition: {"calories":590,"protein":43,"carbs":52,"fats":21,"fiber":11},
    spiceLevel: "mild",
    cleanupDifficulty: "easy",
    searchTerms: ["white chicken chili slow cooker crowd","crockpot chicken chili firehall","slow cooker dinner for ten","creamy white bean chili"],
    substitutions: ["Use turkey breast for chicken.","Use coconut milk for cream cheese."],
  }),
  def({
    slug: "italian-beef-slow-cooker",
    title: "Italian Beef Slow Cooker Sandwiches",
    subtitle: "Juicy shredded beef with peppers on sturdy rolls",
    category: "crew_feeders",
    protein: "beef",
    cuisine: "Italian-American",
    mealFormat: "slow_cooker",
    explorePools: ["slow_cooker","game_day"],
    hookLine: "A Chicago-style sandwich bar that can stay ready through a long call.",
    description: "Chuck roast cooks in peppery Italian jus, then gets piled onto rolls with sweet or hot peppers.",
    whyCrewsLikeIt: "The beef improves on warm and guests can build sandwiches without slowing the kitchen.",
    mealPrepNotes: "Make-ahead: start beef the day before if needed. Storage: refrigerate beef in jus for 3 days. Reheating: heat beef to 165°F.",
    stationWorkflow: ["Start beef in morning","Shred into jus","Build sandwich bar"],
    prepMinutes: 15,
    cookMinutes: 480,
    difficulty: "easy",
    crewSizeDefault: 10,
    ingredients: [
      ing("chuck roast", "10", { unit: "lb" }),
      ing("beef broth", "10", { unit: "cups" }),
      ing("Italian seasoning", "0.5", { unit: "cup" }),
      ing("giardiniera", "2", { unit: "jars" }),
      ing("hoagie rolls", "12", { unit: "each" }),
      ing("provolone", "2", { unit: "lb" }),
    ],
    steps: [
      step(1, "Morning start", "Place chuck roast in the slow cooker with broth, Italian seasoning, garlic, and pepper."),
      step(2, "Cook covered", "Cook on low for 8 hours, leaving the lid closed to maintain a steady braise."),
      step(3, "Slice peppers", "Slice bell peppers and onions for a sweet topping, keeping them refrigerated until cooking."),
      step(4, "Sauté peppers", "Sauté peppers and onions until soft and lightly browned, not blackened."),
      step(5, "Test roast", "Test with forks; the roast should pull apart easily after the long cook."),
      step(6, "Shred beef", "Shred beef on a rimmed tray, then return it to the hot jus to stay moist."),
      step(7, "Heat to safe temp", "Stir and verify the shredded beef reaches 165°F before changing the cooker to warm."),
      step(8, "Toast rolls", "Toast split rolls at 200°F just until dry on the cut side so they resist the jus."),
      step(9, "Hold for calls", "Keep beef submerged in jus above 140°F and hold cheese cold until serving."),
      step(10, "Build sandwiches", "Pile beef on rolls, add peppers or giardiniera, and top with provolone."),
      CALL_INTERRUPTION_STEP(11, "Chuck roast"),
      LEFTOVERS_PACK_DOWN_STEP(12, "Chuck roast"),
    ],
    proTips: ["Use a slotted spoon so rolls do not collapse.","Offer jus in cups for dipping.","Keep hot giardiniera clearly labelled."],
    tonightSpread: buildStructuredTonightSpread("Italian beef sandwiches", ["potato wedges","Italian salad"], ["giardiniera","banana peppers","extra jus"]),
    leftovers: standardLeftovers("Chuck roast", ["Use beef and jus for loaded fries."]),
    equipment: ["slow cooker","skillet","sheet pans","thermometer"],
    nutrition: {"calories":760,"protein":49,"carbs":61,"fats":34,"fiber":5},
    spiceLevel: "medium",
    cleanupDifficulty: "medium",
    searchTerms: ["Italian beef slow cooker crowd","slow cooker beef sandwiches","firehall sandwich dinner","Chicago beef recipe ten people"],
    substitutions: ["Use brisket for chuck roast.","Use mozzarella for provolone."],
  }),
  def({
    slug: "salsa-verde-chicken-crock",
    title: "Salsa Verde Chicken Crock",
    subtitle: "Tender green-chile chicken for tacos and bowls",
    category: "crew_feeders",
    protein: "chicken",
    cuisine: "Mexican-inspired",
    mealFormat: "slow_cooker",
    explorePools: ["slow_cooker","taco_night"],
    hookLine: "Three pantry staples become a reliable taco-night main by dinner.",
    description: "Chicken cooks gently in salsa verde with beans and corn, then shreds for tacos or rice bowls.",
    whyCrewsLikeIt: "It has a hands-off morning start and adapts to whatever tortillas or rice are on hand.",
    mealPrepNotes: "Make-ahead: portion toppings one day ahead. Storage: refrigerate chicken 3 days. Reheating: heat chicken to 165°F.",
    stationWorkflow: ["Load cooker early","Shred salsa chicken","Open taco bar"],
    prepMinutes: 15,
    cookMinutes: 390,
    difficulty: "easy",
    crewSizeDefault: 10,
    ingredients: [
      ing("chicken thighs", "6", { unit: "lb" }),
      ing("salsa verde", "6", { unit: "cups" }),
      ing("black beans", "6", { unit: "cans" }),
      ing("corn", "3", { unit: "lb" }),
      ing("tortillas", "30", { unit: "each" }),
      ing("limes", "6", { unit: "each" }),
    ],
    steps: [
      step(1, "Morning start", "Add chicken thighs and salsa verde to the slow cooker, keeping raw chicken away from toppings."),
      step(2, "Cook low", "Cover and cook on low for 6 to 7 hours without opening the lid repeatedly."),
      step(3, "Warm beans", "Rinse beans and stir them in for the final hour so they do not break apart."),
      step(4, "Check temperature", "Check the thickest thigh reaches 165°F before removing it to shred."),
      step(5, "Shred chicken", "Shred chicken with two forks and return it to the salsa so each piece stays juicy."),
      step(6, "Add corn", "Stir in corn and cook until it is hot throughout, about 10 minutes."),
      step(7, "Taste salsa", "Taste the sauce and add lime juice; add salt only after tasting the salsa verde."),
      step(8, "Warm tortillas", "Wrap tortillas in foil and warm at 200°F until flexible, not crisp."),
      step(9, "Hold safely", "Keep chicken on warm above 140°F and keep cheese and sour cream cold."),
      step(10, "Serve bar", "Offer chicken in tortillas or bowls with beans, corn, lime, and toppings."),
      CALL_INTERRUPTION_STEP(11, "Chicken thighs"),
      LEFTOVERS_PACK_DOWN_STEP(12, "Chicken thighs"),
    ],
    proTips: ["Use thighs because they stay tender on warm.","Keep mild and hot salsa separate.","Drain excess sauce for less messy tacos."],
    tonightSpread: buildStructuredTonightSpread("Salsa verde shredded chicken", ["cilantro rice","tortilla chips"], ["sour cream","jalapeños","cotija"]),
    leftovers: standardLeftovers("Chicken thighs", ["Bake leftovers into green enchiladas."]),
    equipment: ["slow cooker","foil","thermometer"],
    nutrition: {"calories":620,"protein":44,"carbs":62,"fats":19,"fiber":10},
    spiceLevel: "medium",
    cleanupDifficulty: "easy",
    searchTerms: ["salsa verde chicken slow cooker crowd","crockpot taco night firehall","slow cooker chicken tacos ten","green chile chicken bowls"],
    substitutions: ["Use chicken breasts for thighs.","Use pinto beans for black beans."],
  }),
  def({
    slug: "loaded-baked-potato-soup-crock",
    title: "Loaded Baked Potato Soup Crock",
    subtitle: "Creamy potato soup with bacon and cheese toppings",
    category: "crew_feeders",
    protein: "bacon",
    cuisine: "American",
    mealFormat: "slow_cooker",
    explorePools: ["slow_cooker","budget"],
    hookLine: "A winter-proof soup bar that lets every firefighter choose the loaded finish.",
    description: "Potatoes, broth, bacon, cheese, and sour cream become thick, comforting soup in the slow cooker.",
    whyCrewsLikeIt: "It is inexpensive, familiar, and easy to keep hot for a delayed dinner.",
    mealPrepNotes: "Make-ahead: cook bacon and chop potatoes 1 day ahead. Storage: refrigerate 3 days. Reheating: bring soup to 165°F while stirring.",
    stationWorkflow: ["Start potatoes in morning","Mash and enrich soup","Offer loaded toppings"],
    prepMinutes: 25,
    cookMinutes: 420,
    difficulty: "easy",
    crewSizeDefault: 10,
    ingredients: [
      ing("russet potatoes", "12", { unit: "lb" }),
      ing("chicken broth", "14", { unit: "cups" }),
      ing("bacon", "3", { unit: "lb" }),
      ing("cheddar cheese", "3", { unit: "lb" }),
      ing("sour cream", "4", { unit: "cups" }),
      ing("green onions", "3", { unit: "bunches" }),
    ],
    steps: [
      step(1, "Morning start", "Add peeled potato cubes, broth, onion, and seasonings to the slow cooker."),
      step(2, "Cook covered", "Cook on low for 7 hours until potatoes crush easily against the side with a spoon."),
      step(3, "Cook bacon", "Bake bacon on lined pans until crisp, then drain it well and crumble after cooling."),
      step(4, "Mash potatoes", "Mash about half the potatoes in the cooker; leave some chunks for baked-potato texture."),
      step(5, "Make slurry", "Whisk cornstarch with cold water until smooth so it will not form lumps in soup."),
      step(6, "Thicken soup", "Stir slurry into simmering soup and cook until it lightly coats a spoon."),
      step(7, "Add dairy", "Lower heat, then stir in sour cream and cheese gradually so the soup does not split."),
      step(8, "Check heat", "Warm soup back to 165°F while stirring the bottom to prevent scorching."),
      step(9, "Hold safely", "Keep the cooker on warm and confirm soup stays above 140°F during service."),
      step(10, "Load bowls", "Ladle soup and top with bacon, cheddar, green onions, and extra sour cream."),
      CALL_INTERRUPTION_STEP(11, "Bacon"),
      LEFTOVERS_PACK_DOWN_STEP(12, "Bacon"),
    ],
    proTips: ["Add dairy after potatoes are tender.","Use an immersion blender only for a smoother soup.","Serve toppings with separate spoons."],
    tonightSpread: buildStructuredTonightSpread("Loaded baked potato soup", ["crusty bread","green salad"], ["bacon","cheddar","chives"]),
    leftovers: standardLeftovers("Bacon", ["Use leftovers as a casserole sauce."]),
    equipment: ["slow cooker","sheet pans","potato masher","ladle"],
    nutrition: {"calories":680,"protein":26,"carbs":64,"fats":36,"fiber":7},
    spiceLevel: "mild",
    cleanupDifficulty: "medium",
    searchTerms: ["loaded baked potato soup crockpot crowd","slow cooker potato soup firehall","crockpot soup for ten","bacon cheddar potato soup"],
    substitutions: ["Use turkey bacon for bacon.","Use Greek yogurt for sour cream."],
  }),
  def({
    slug: "thai-peanut-chicken-crock",
    title: "Thai Peanut Chicken Crock",
    subtitle: "Slow-cooked peanut chicken with rice and bright vegetables",
    category: "crew_feeders",
    protein: "chicken",
    cuisine: "Thai-inspired",
    mealFormat: "slow_cooker",
    explorePools: ["slow_cooker","bowls"],
    hookLine: "A slow cooker turns a scratch peanut sauce into an easy bowl-night main.",
    description: "Chicken thighs simmer in coconut-peanut sauce and are served with rice, lime, and crunchy vegetables.",
    whyCrewsLikeIt: "The flavour develops while the crew works, while the vegetables remain fresh until dinner.",
    mealPrepNotes: "Make-ahead: whisk sauce and shred vegetables 2 days ahead. Storage: refrigerate 3 days. Reheating: heat chicken to 165°F.",
    stationWorkflow: ["Start peanut chicken early","Cook rice near dinner","Finish with lime and crunch"],
    prepMinutes: 20,
    cookMinutes: 390,
    difficulty: "easy",
    crewSizeDefault: 10,
    ingredients: [
      ing("chicken thighs", "6", { unit: "lb" }),
      ing("peanut butter", "1.5", { unit: "cups" }),
      ing("coconut milk", "4", { unit: "cans" }),
      ing("rice", "5", { unit: "cups" }),
      ing("red cabbage", "2", { unit: "heads" }),
      ing("lime", "6", { unit: "each" }),
    ],
    steps: [
      step(1, "Morning start", "Place chicken thighs in the slow cooker, keeping the raw-chicken package away from ready-to-eat vegetables."),
      step(2, "Whisk sauce", "Whisk peanut butter, coconut milk, curry paste, soy sauce, and lime juice until smooth."),
      step(3, "Cook low", "Pour sauce over chicken, cover, and cook on low for 6 to 7 hours."),
      step(4, "Start rice", "Near dinner, cook rinsed rice covered so it is fresh when chicken is ready."),
      step(5, "Check chicken", "Check a thick thigh has reached 165°F before shredding or chopping it."),
      step(6, "Shred chicken", "Shred chicken in the sauce with two forks; do not remove all the cooking liquid."),
      step(7, "Adjust sauce", "Stir in hot water a little at a time if the peanut sauce is thicker than gravy."),
      step(8, "Prep cabbage", "Thinly shred cabbage and toss with lime and a pinch of salt just before serving."),
      step(9, "Hold hot", "Keep chicken on warm above 140°F and keep cabbage chilled until bowls are built."),
      step(10, "Serve bowls", "Portion rice, peanut chicken, cabbage, and lime wedges into each bowl."),
      CALL_INTERRUPTION_STEP(11, "Chicken thighs"),
      LEFTOVERS_PACK_DOWN_STEP(12, "Chicken thighs"),
    ],
    proTips: ["Use sunflower butter when peanut allergies require it.","Keep curry paste modest and offer heat separately.","Coconut milk may look separated; stir it smooth."],
    tonightSpread: buildStructuredTonightSpread("Thai peanut chicken bowls", ["cucumber salad","mango slices"], ["lime wedges","chili crisp","crushed peanuts"]),
    leftovers: standardLeftovers("Chicken thighs", ["Use leftover sauce on noodles."]),
    equipment: ["slow cooker","rice cooker","thermometer"],
    nutrition: {"calories":740,"protein":43,"carbs":67,"fats":35,"fiber":6},
    spiceLevel: "medium",
    cleanupDifficulty: "medium",
    searchTerms: ["Thai peanut chicken slow cooker crowd","crockpot peanut chicken bowls","firehall slow cooker bowls","Thai chicken meal for ten"],
    substitutions: ["Use chickpeas for chicken.","Use almond butter for peanut butter."],
  }),
  def({
    slug: "burnt-ends-chili-crew",
    title: "Burnt Ends Chili for the Crew",
    subtitle: "Smoky brisket ends folded into hearty bean chili",
    category: "smoker_recipes",
    protein: "beef",
    cuisine: "BBQ",
    mealFormat: "smoker",
    explorePools: ["bbq","game_day"],
    hookLine: "Give leftover burnt ends a second life in a smoky, high-reward chili.",
    description: "Chopped burnt ends enrich a tomato-bean chili that simmers in a Dutch oven on the smoker.",
    whyCrewsLikeIt: "It turns barbecue leftovers into a complete meal and improves while held hot.",
    mealPrepNotes: "Make-ahead: chop burnt ends and chili vegetables 1 day ahead. Storage: refrigerate 3 days. Reheating: bring chili to 165°F.",
    stationWorkflow: ["Smoke chili base","Add chopped burnt ends","Hold for toppings"],
    prepMinutes: 25,
    cookMinutes: 150,
    difficulty: "medium",
    crewSizeDefault: 10,
    ingredients: [
      ing("burnt ends", "5", { unit: "lb" }),
      ing("kidney beans", "6", { unit: "cans" }),
      ing("crushed tomatoes", "6", { unit: "cans" }),
      ing("onions", "3", { unit: "each" }),
      ing("beef broth", "6", { unit: "cups" }),
      ing("chili powder", "0.5", { unit: "cup" }),
    ],
    steps: [
      step(1, "Heat smoker", "Preheat smoker to 275°F and make sure its water pan and fuel are ready for a long cook."),
      step(2, "Dice burnt ends", "Cut burnt ends into spoon-size pieces, trimming only hard fat that will not melt."),
      step(3, "Sauté aromatics", "Sauté onion and peppers in a Dutch oven until softened, scraping up any browned bits."),
      step(4, "Bloom spices", "Stir chili powder and cumin for 30 seconds so the spices smell fragrant but do not burn."),
      step(5, "Build chili", "Add tomatoes, beans, broth, and burnt ends, stirring until the pot is evenly mixed."),
      step(6, "Smoke uncovered", "Place the Dutch oven in the smoker uncovered for 45 minutes to pick up smoke."),
      step(7, "Simmer covered", "Cover and smoke another hour, stirring once so the bottom does not catch."),
      step(8, "Check heat", "Bring the chili to 165°F, especially if the burnt ends were refrigerated."),
      step(9, "Hold chili", "Keep the covered pot above 140°F; add hot broth if it thickens too much."),
      step(10, "Ladle bowls", "Serve thick chili with cheese, onions, and cornbread rather than thinning it at the table."),
      CALL_INTERRUPTION_STEP(11, "Burnt ends"),
      LEFTOVERS_PACK_DOWN_STEP(12, "Burnt ends"),
    ],
    proTips: ["Use any smoked brisket if burnt ends are unavailable.","Smoke can become bitter if the pot stays uncovered too long.","Offer hot sauce separately."],
    tonightSpread: buildStructuredTonightSpread("Smoked burnt ends chili", ["cornbread","slaw"], ["cheddar","green onions","hot sauce"]),
    leftovers: standardLeftovers("Burnt ends", ["Spoon leftovers over baked potatoes."]),
    equipment: ["smoker","Dutch oven","ladle","thermometer"],
    nutrition: {"calories":710,"protein":45,"carbs":55,"fats":33,"fiber":12},
    spiceLevel: "medium",
    cleanupDifficulty: "medium",
    searchTerms: ["burnt ends chili recipe","smoker chili for a crowd","BBQ firehall chili","brisket chili ten people"],
    substitutions: ["Use smoked chuck roast for burnt ends.","Use black beans for kidney beans."],
  }),
  def({
    slug: "smoker-nachos-crew",
    title: "Smoker Nachos for the Crew",
    subtitle: "Layered chips, pulled pork, beans, and melted cheese",
    category: "smoker_recipes",
    protein: "pork",
    cuisine: "BBQ",
    mealFormat: "smoker",
    explorePools: ["bbq","game_day"],
    hookLine: "A smoker adds real barbecue flavour to a fast, shareable dinner tray.",
    description: "Sturdy tortilla chips are layered with pulled pork, beans, cheese, and toppings on smoker-safe pans.",
    whyCrewsLikeIt: "It is a crowd-pleasing use for leftover pork, with trays that can be refreshed in batches.",
    mealPrepNotes: "Make-ahead: shred pork and portion toppings 1 day ahead. Storage: refrigerate toppings separately for 3 days. Reheating: heat pork to 165°F before layering.",
    stationWorkflow: ["Preheat smoker","Build layered trays","Melt and top quickly"],
    prepMinutes: 25,
    cookMinutes: 30,
    difficulty: "easy",
    crewSizeDefault: 10,
    ingredients: [
      ing("pulled pork", "5", { unit: "lb" }),
      ing("tortilla chips", "5", { unit: "lb" }),
      ing("shredded cheese", "5", { unit: "lb" }),
      ing("black beans", "6", { unit: "cans" }),
      ing("salsa", "4", { unit: "cups" }),
      ing("jalapeños", "1", { unit: "jar" }),
    ],
    steps: [
      step(1, "Heat smoker", "Preheat smoker to 350°F so cheese melts quickly instead of drying out the chips."),
      step(2, "Warm pork", "Heat pulled pork with a little barbecue sauce until it reaches 165°F before it goes on chips."),
      step(3, "Drain beans", "Rinse and drain beans well; wet beans make nachos soggy."),
      step(4, "Line pans", "Line rimmed sheet pans with foil for easy removal and to keep chips from sticking."),
      step(5, "Make first layer", "Spread chips in one even layer, leaving no deep piles that block the heat."),
      step(6, "Add fillings", "Scatter pork, beans, and cheese across every chip instead of concentrating toppings in the centre."),
      step(7, "Smoke trays", "Smoke trays until cheese is fully melted, checking after 8 minutes so chip edges do not burn."),
      step(8, "Add cold toppings", "Add salsa, jalapeños, onion, and cilantro only after trays leave the smoker."),
      step(9, "Hold wisely", "Serve immediately; if delayed, keep pork above 140°F separately and build fresh trays."),
      step(10, "Serve portions", "Cut or scoop nachos from the tray with a wide spatula, including toppings in each portion."),
      CALL_INTERRUPTION_STEP(11, "Pulled pork"),
      LEFTOVERS_PACK_DOWN_STEP(12, "Pulled pork"),
    ],
    proTips: ["Build two shallow layers rather than one overloaded tray.","Use pickled jalapeños for even heat.","Keep sour cream cold until serving."],
    tonightSpread: buildStructuredTonightSpread("Smoked pulled-pork nachos", ["corn salad","guacamole"], ["sour cream","salsa","barbecue sauce"]),
    leftovers: standardLeftovers("Pulled pork", ["Turn leftover pork and beans into quesadillas."]),
    equipment: ["smoker","sheet pans","wide spatula","thermometer"],
    nutrition: {"calories":830,"protein":41,"carbs":72,"fats":43,"fiber":9},
    spiceLevel: "medium",
    cleanupDifficulty: "heavy",
    searchTerms: ["smoker nachos for a crowd","pulled pork nachos smoker","BBQ game day firehall","smoked nacho trays"],
    substitutions: ["Use shredded chicken for pork.","Use tortilla strips for chips."],
  }),
  def({
    slug: "weeknight-bbq-ribs-crew",
    title: "Weeknight BBQ Ribs for the Crew",
    subtitle: "Fast-finished ribs with a smoker shortcut",
    category: "smoker_recipes",
    protein: "pork",
    cuisine: "BBQ",
    mealFormat: "smoker",
    explorePools: ["bbq","weeknight"],
    hookLine: "Smoke first, wrap smart, and get tender ribs on the table in one shift.",
    description: "St. Louis ribs get a dry rub, smoke, and a covered finish before barbecue sauce is set.",
    whyCrewsLikeIt: "The wrap phase protects tenderness and makes timing more reliable than an all-day rib cook.",
    mealPrepNotes: "Make-ahead: remove membranes and season ribs overnight. Storage: refrigerate cooked ribs for 3 days. Reheating: heat ribs to 165°F.",
    stationWorkflow: ["Season ribs","Smoke and wrap","Glaze before serving"],
    prepMinutes: 20,
    cookMinutes: 210,
    difficulty: "medium",
    crewSizeDefault: 10,
    ingredients: [
      ing("St. Louis ribs", "10", { unit: "racks" }),
      ing("barbecue rub", "1.5", { unit: "cups" }),
      ing("barbecue sauce", "4", { unit: "cups" }),
      ing("apple juice", "2", { unit: "cups" }),
      ing("corn", "10", { unit: "ears" }),
      ing("potatoes", "10", { unit: "lb" }),
    ],
    steps: [
      step(1, "Heat smoker", "Preheat smoker to 275°F and stabilize the temperature before ribs go on."),
      step(2, "Remove membranes", "Pull the membrane from the bone side with a paper towel so rub can season both sides."),
      step(3, "Apply rub", "Coat ribs evenly with barbecue rub, pressing it on without making a thick paste."),
      step(4, "Smoke ribs", "Place racks bone-side down and smoke for 90 minutes, keeping the lid closed."),
      step(5, "Wrap racks", "Wrap each rack tightly with a splash of apple juice; loose foil leaks steam and dries ribs."),
      step(6, "Finish tender", "Return wrapped ribs to smoker until a toothpick slides between bones with little resistance."),
      step(7, "Check food safety", "Ribs are safe above 145°F, but tenderness usually arrives near 195°F; verify with a probe."),
      step(8, "Glaze ribs", "Unwrap carefully, brush with sauce, and smoke uncovered 10 minutes to set the glaze."),
      step(9, "Hold warm", "Cover ribs loosely and hold above 140°F; do not stack them tightly or the glaze smears."),
      step(10, "Cut and serve", "Slice between bones with a sharp knife and serve with potatoes and corn."),
      CALL_INTERRUPTION_STEP(11, "Pork ribs"),
      LEFTOVERS_PACK_DOWN_STEP(12, "Pork ribs"),
    ],
    proTips: ["Choose similarly sized racks for even timing.","Do not rely on time alone; use the toothpick test.","Keep sauce warm for a smoother glaze."],
    tonightSpread: buildStructuredTonightSpread("Weeknight smoked BBQ ribs", ["smoked corn","potato salad"], ["barbecue sauce","pickles","hot sauce"]),
    leftovers: standardLeftovers("Pork ribs", ["Pull remaining rib meat for fried rice."]),
    equipment: ["smoker","foil","probe thermometer","sharp knife"],
    nutrition: {"calories":860,"protein":46,"carbs":61,"fats":49,"fiber":6},
    spiceLevel: "mild",
    cleanupDifficulty: "heavy",
    searchTerms: ["weeknight BBQ ribs smoker","ribs for ten people","firehall smoker dinner","fast smoked St Louis ribs"],
    substitutions: ["Use baby back ribs for St. Louis ribs.","Use cola for apple juice."],
  }),
  def({
    slug: "grilled-flank-fajita-bar",
    title: "Grilled Flank Fajita Bar",
    subtitle: "Charred steak, peppers, tortillas, and fresh toppings",
    category: "smoker_recipes",
    protein: "beef",
    cuisine: "Mexican-inspired",
    mealFormat: "grill",
    explorePools: ["bbq","taco_night"],
    hookLine: "High-heat grilled flank steak delivers a full fajita bar with minimal indoor cleanup.",
    description: "Marinated flank steak is grilled, rested, sliced thin, and paired with peppers, onions, and tortillas.",
    whyCrewsLikeIt: "The grill handles the main cooking while a simple topping bar feeds people at different times.",
    mealPrepNotes: "Make-ahead: marinate steak up to 24 hours and slice vegetables 1 day ahead. Storage: refrigerate for 3 days. Reheating: heat steak to 165°F if reheating leftovers.",
    stationWorkflow: ["Marinate steak","Grill steak and vegetables","Slice across grain"],
    prepMinutes: 30,
    cookMinutes: 25,
    difficulty: "medium",
    crewSizeDefault: 10,
    ingredients: [
      ing("flank steak", "8", { unit: "lb" }),
      ing("bell peppers", "12", { unit: "each" }),
      ing("onions", "6", { unit: "each" }),
      ing("flour tortillas", "30", { unit: "each" }),
      ing("lime", "8", { unit: "each" }),
      ing("fajita seasoning", "1", { unit: "cup" }),
    ],
    steps: [
      step(1, "Marinate steak", "Rub flank steak with oil, lime, and fajita seasoning, then refrigerate it covered overnight."),
      step(2, "Preheat grill", "Heat a clean grill to high and oil the grates with a folded paper towel held by tongs."),
      step(3, "Slice vegetables", "Cut peppers and onions into wide strips so they do not fall through the grates."),
      step(4, "Grill vegetables", "Cook vegetables in a grill basket, stirring until softened with charred edges."),
      step(5, "Grill steak", "Grill steak over high heat, turning once, until it reaches your safe target of at least 145°F."),
      step(6, "Rest steak", "Place steak on a board for 8 minutes so juices redistribute before slicing."),
      step(7, "Slice correctly", "Find the grain and slice thinly across it; slicing with the grain makes flank steak chewy."),
      step(8, "Warm tortillas", "Wrap tortillas in foil and warm at 200°F or on an indirect grill zone."),
      step(9, "Hold safely", "Keep steak and vegetables above 140°F, covering loosely so they do not steam soggy."),
      step(10, "Open fajita bar", "Serve sliced steak, vegetables, tortillas, lime, and chilled toppings in separate pans."),
      CALL_INTERRUPTION_STEP(11, "Flank steak"),
      LEFTOVERS_PACK_DOWN_STEP(12, "Flank steak"),
    ],
    proTips: ["Do not pierce steak while grilling.","Use skirt steak if flank is unavailable.","Label raw and cooked steak trays clearly."],
    tonightSpread: buildStructuredTonightSpread("Grilled flank steak fajitas", ["black beans","Mexican rice"], ["salsa","sour cream","guacamole"]),
    leftovers: standardLeftovers("Flank steak", ["Make steak-and-egg breakfast burritos."]),
    equipment: ["grill","grill basket","tongs","thermometer"],
    nutrition: {"calories":690,"protein":46,"carbs":60,"fats":28,"fiber":8},
    spiceLevel: "medium",
    cleanupDifficulty: "medium",
    searchTerms: ["grilled flank steak fajitas crowd","fajita bar for ten","firehall grill dinner","BBQ steak taco bar"],
    substitutions: ["Use skirt steak for flank steak.","Use corn tortillas for flour tortillas."],
  }),
  def({
    slug: "costco-rotisserie-remix",
    title: "Costco Rotisserie Chicken Remix",
    subtitle: "Creamy chicken-and-rice bake from store-bought birds",
    category: "crew_feeders",
    protein: "chicken",
    cuisine: "American",
    mealFormat: "casserole",
    explorePools: ["budget", "chicken", "casserole", "hall_expansion"],
    hookLine: "Store-bought rotisserie chicken becomes a low-cost, no-stress hall dinner.",
    description: "Shredded chicken, rice, broccoli, and a creamy sauce bake under a crisp cheese topping.",
    whyCrewsLikeIt: "Using cooked chicken cuts prep time sharply and stretches a grocery run into ten dinners.",
    mealPrepNotes: "Make-ahead: assemble casserole 1 day ahead. Storage: refrigerate 3 days. Reheating: bake to 165°F in the centre.",
    stationWorkflow: ["Shred chicken","Mix rice filling","Bake covered then brown"],
    prepMinutes: 25,
    cookMinutes: 40,
    difficulty: "easy",
    crewSizeDefault: 10,
    ingredients: [
      ing("rotisserie chickens", "4", { unit: "each" }),
      ing("cooked rice", "12", { unit: "cups" }),
      ing("broccoli", "4", { unit: "lb" }),
      ing("cream of chicken soup", "6", { unit: "cans" }),
      ing("cheddar cheese", "3", { unit: "lb" }),
      ing("milk", "4", { unit: "cups" }),
    ],
    steps: [
      step(1, "Heat oven and stage pans", "Heat the oven to 375°F and grease two deep hotel pans or casserole dishes so the rice bake releases cleanly after service. Set shredded chicken, rice, and broccoli within arm reach before mixing — hunting for pans mid-fold is how portions go uneven.", { minutes: 5, tempF: 375 }),
      step(2, "Pull chicken", "Remove meat from rotisserie chickens, discarding bones and checking for small cartilage pieces that can hide in dark meat. Shred into bite-size strips so every scoop gets chicken, not just rice.", { minutes: 15 }),
      step(3, "Steam broccoli", "Steam broccoli only until bright green and still crisp; it will finish in the oven. Soft olive broccoli sat too long and turns mushy in the bake.", { minutes: 8 }),
      step(4, "Mix sauce", "Whisk soup and milk until completely smooth so no concentrated salty pockets remain in the bake. Taste and add black pepper — rotisserie chicken already brings salt.", { minutes: 5 }),
      step(5, "Combine filling", "Fold rice, chicken, broccoli, and sauce together gently so the rice stays distinct instead of turning to porridge. Divide evenly between pans and level the surface.", { minutes: 8 }),
      step(6, "Cover and bake", "Cover with foil and bake until the centre of each pan reaches 165°F on an instant-read thermometer, about 25–30 minutes. Cold spots in the middle mean the pans were overfilled or the oven was crowded.", { minutes: 30, tempF: 375 }),
      step(7, "Add cheese", "Remove foil, blanket with cheddar, and bake uncovered 8–10 minutes until melted and lightly golden at the edges. Cheese burned black sat under the broiler too long.", { minutes: 10, tempF: 375 }),
      step(8, "Let the bake set", "Cover and wait 5 minutes so the sauce thickens enough to scoop clean portions without flooding the plate.", { minutes: 5 }),
      step(9, "Hold safely", "Cover loosely and hold above 140°F in a 200°F oven if the crew is delayed. Stir once before service if the edges look dry.", { minutes: 5, tempF: 200 }),
      step(10, "Scoop servings", "Use a large spoon to serve complete portions with chicken, rice, and broccoli in every scoop. Keep hot sauce and cracked pepper at the pass.", { minutes: 5 }),
      CALL_INTERRUPTION_STEP(11, "rotisserie chicken bake"),
      LEFTOVERS_PACK_DOWN_STEP(12, "rotisserie chicken bake"),
    ],
    proTips: ["Save carcasses for stock.","Use low-sodium soup because rotisserie chicken is seasoned.","Add crushed crackers only for the last bake."],
    tonightSpread: buildStructuredTonightSpread("Rotisserie chicken rice bake", ["green salad","dinner rolls"], ["hot sauce","black pepper","crushed crackers"]),
    leftovers: standardLeftovers("Rotisserie chicken", ["Roll leftovers into burritos."]),
    equipment: ["casserole pans","mixing bowl","thermometer"],
    nutrition: {"calories":640,"protein":40,"carbs":58,"fats":27,"fiber":5},
    spiceLevel: "mild",
    cleanupDifficulty: "medium",
    searchTerms: ["rotisserie chicken dinner for ten","Costco chicken crew meal","budget chicken rice bake","firehall casserole"],
    substitutions: ["Use cooked turkey for chicken.","Use frozen mixed vegetables for broccoli."],
  }),
  def({
    slug: "chicken-thigh-stretch-dinner",
    title: "Chicken Thigh Stretch Dinner",
    subtitle: "Roasted thighs, beans, and vegetables that go farther",
    category: "crew_feeders",
    protein: "chicken",
    cuisine: "American",
    mealFormat: "sheet_pan",
    explorePools: ["budget","crew_feeders"],
    hookLine: "Bone-in thighs, beans, and vegetables make a generous meal without premium meat prices.",
    description: "Spiced chicken thighs roast over potatoes, peppers, and beans for a complete economical pan dinner.",
    whyCrewsLikeIt: "Dark meat stays juicy and the vegetables cook in the flavourful pan drippings.",
    mealPrepNotes: "Make-ahead: season chicken overnight and cut vegetables 1 day ahead. Storage: refrigerate 3 days. Reheating: heat chicken to 165°F.",
    stationWorkflow: ["Season chicken","Roast pans together","Rest and portion"],
    prepMinutes: 25,
    cookMinutes: 50,
    difficulty: "easy",
    crewSizeDefault: 10,
    ingredients: [
      ing("bone-in chicken thighs", "10", { unit: "lb" }),
      ing("potatoes", "10", { unit: "lb" }),
      ing("canned chickpeas", "6", { unit: "cans" }),
      ing("bell peppers", "8", { unit: "each" }),
      ing("onions", "4", { unit: "each" }),
      ing("paprika", "0.25", { unit: "cup" }),
    ],
    steps: [
      step(1, "Heat oven", "Heat oven to 425°F and line sheet pans with parchment or foil."),
      step(2, "Season chicken", "Rub thighs with oil, paprika, garlic, salt, and pepper, then wash hands thoroughly."),
      step(3, "Cut potatoes", "Cut potatoes into equal 1-inch pieces so they finish at the same time."),
      step(4, "Dry chickpeas", "Drain and pat chickpeas dry; wet chickpeas steam instead of browning."),
      step(5, "Arrange pans", "Spread potatoes, peppers, onion, and chickpeas in single layers, leaving space between pieces."),
      step(6, "Add chicken", "Place thighs skin-side up among the vegetables without crowding or overlapping them."),
      step(7, "Roast", "Roast, rotating pans halfway, until vegetables brown and the thickest thigh reaches 165°F."),
      step(8, "Crisp skin", "Broil for 2 minutes only if skin needs crisping; watch closely because paprika can burn."),
      step(9, "Hold safely", "Cover loosely and keep chicken above 140°F while portions are arranged."),
      step(10, "Serve pans", "Give each person a thigh with roasted potatoes, chickpeas, peppers, and pan juices."),
      CALL_INTERRUPTION_STEP(11, "Chicken thighs"),
      LEFTOVERS_PACK_DOWN_STEP(12, "Chicken thighs"),
    ],
    proTips: ["Use two ovens or staggered pans if space is limited.","Do not crowd pans or vegetables will steam.","Thighs are forgiving but still need a temperature check."],
    tonightSpread: buildStructuredTonightSpread("Roasted chicken thigh dinner", ["simple salad","warm bread"], ["hot sauce","lemon wedges","ranch"]),
    leftovers: standardLeftovers("Chicken thighs", ["Pull leftover meat for chicken salad."]),
    equipment: ["sheet pans","tongs","thermometer"],
    nutrition: {"calories":670,"protein":41,"carbs":57,"fats":29,"fiber":10},
    spiceLevel: "mild",
    cleanupDifficulty: "easy",
    searchTerms: ["budget chicken thigh dinner crowd","sheet pan chicken firehall","chicken thighs meal for ten","cheap crew dinner"],
    substitutions: ["Use drumsticks for thighs.","Use white beans for chickpeas."],
  }),
  def({
    slug: "pasta-e-fagioli-hall",
    title: "Pasta e Fagioli for the Hall",
    subtitle: "Big-pot Italian bean, beef, and pasta soup",
    category: "crew_feeders",
    protein: "beef",
    cuisine: "Italian",
    mealFormat: "one_pot",
    explorePools: ["budget","one_pot"],
    hookLine: "A hearty Italian soup that uses pantry beans and pasta to feed ten warmly.",
    description: "Ground beef, beans, vegetables, tomatoes, and small pasta simmer into a satisfying one-pot dinner.",
    whyCrewsLikeIt: "It is inexpensive, freezer-friendly, and forgiving if the meal is interrupted.",
    mealPrepNotes: "Make-ahead: make soup base 2 days ahead; cook pasta fresh. Storage: refrigerate 3 days. Reheating: heat soup to 165°F.",
    stationWorkflow: ["Brown beef and vegetables","Simmer bean base","Cook pasta before service"],
    prepMinutes: 20,
    cookMinutes: 45,
    difficulty: "easy",
    crewSizeDefault: 10,
    ingredients: [
      ing("ground beef", "4", { unit: "lb" }),
      ing("small pasta", "3", { unit: "lb" }),
      ing("cannellini beans", "6", { unit: "cans" }),
      ing("crushed tomatoes", "4", { unit: "cans" }),
      ing("beef broth", "14", { unit: "cups" }),
      ing("carrots", "2", { unit: "lb" }),
    ],
    steps: [
      step(1, "Heat pot", "Heat a large heavy pot over medium-high and add a small amount of oil."),
      step(2, "Brown beef", "Cook ground beef in batches, breaking it up and draining excess fat when browned."),
      step(3, "Check beef", "Verify the beef reaches 165°F before adding ready-to-eat ingredients."),
      step(4, "Soften vegetables", "Cook onion, carrots, and celery in the same pot until they soften and smell sweet."),
      step(5, "Build broth", "Add tomatoes, beans, broth, Italian seasoning, and browned beef, scraping the pot bottom."),
      step(6, "Simmer base", "Simmer gently for 20 minutes; a hard boil can break beans and reduce liquid too fast."),
      step(7, "Cook pasta", "Stir in pasta and cook at a gentle simmer, stirring often so it does not stick."),
      step(8, "Adjust texture", "Add hot broth if pasta absorbs too much liquid before it is tender."),
      step(9, "Hold safely", "Keep soup above 140°F, adding broth before holding because pasta continues to swell."),
      step(10, "Serve soup", "Ladle soup into bowls and top with parmesan and parsley just before eating."),
      CALL_INTERRUPTION_STEP(11, "Ground beef"),
      LEFTOVERS_PACK_DOWN_STEP(12, "Ground beef"),
    ],
    proTips: ["Cook pasta separately if holding longer than 30 minutes.","Use low-sodium broth to control salt.","Add spinach at the end if available."],
    tonightSpread: buildStructuredTonightSpread("Pasta e fagioli", ["garlic bread","Caesar salad"], ["parmesan","red pepper flakes","olive oil"]),
    leftovers: standardLeftovers("Ground beef", ["Freeze without pasta for best texture."]),
    equipment: ["large stockpot","ladle","thermometer"],
    nutrition: {"calories":610,"protein":35,"carbs":70,"fats":19,"fiber":13},
    spiceLevel: "mild",
    cleanupDifficulty: "medium",
    searchTerms: ["pasta e fagioli crowd","Italian bean soup for ten","budget firehall soup","one pot beef pasta soup"],
    substitutions: ["Use ground turkey for beef.","Use ditalini or elbow pasta."],
  }),
  def({
    slug: "dirty-rice-crew-skillet",
    title: "Dirty Rice Crew Skillet",
    subtitle: "Cajun sausage, beef, rice, and vegetables in one pan",
    category: "crew_feeders",
    protein: "sausage and beef",
    cuisine: "Cajun",
    mealFormat: "skillet",
    explorePools: ["one_pot","budget"],
    hookLine: "One skillet delivers bold Cajun comfort with enough rice for a hungry crew.",
    description: "Sausage, ground beef, vegetables, and seasoned rice cook together until fluffy and savoury.",
    whyCrewsLikeIt: "It uses economical proteins and one pan, with heat easily adjusted at the table.",
    mealPrepNotes: "Make-ahead: chop vegetables and mix seasoning 2 days ahead. Storage: refrigerate 3 days. Reheating: heat mixture to 165°F.",
    stationWorkflow: ["Brown meats","Toast rice and vegetables","Simmer until fluffy"],
    prepMinutes: 20,
    cookMinutes: 35,
    difficulty: "easy",
    crewSizeDefault: 10,
    ingredients: [
      ing("andouille sausage", "3", { unit: "lb" }),
      ing("ground beef", "3", { unit: "lb" }),
      ing("long-grain rice", "5", { unit: "cups" }),
      ing("chicken broth", "12", { unit: "cups" }),
      ing("bell peppers", "4", { unit: "each" }),
      ing("celery", "2", { unit: "bunches" }),
    ],
    steps: [
      step(1, "Slice sausage", "Slice sausage into coins of equal thickness so each piece browns evenly."),
      step(2, "Brown sausage", "Cook sausage in a wide deep skillet until its edges colour, then transfer it to a tray."),
      step(3, "Cook beef", "Brown ground beef in the rendered fat, breaking it into small crumbles and draining if greasy."),
      step(4, "Verify meat", "Check beef reaches 165°F before it is mixed with the rice."),
      step(5, "Soften vegetables", "Cook onion, pepper, and celery until soft, scraping browned flavour from the pan."),
      step(6, "Toast rice", "Stir dry rice for 2 minutes until lightly translucent; do not let it burn on the bottom."),
      step(7, "Add broth", "Return meats, pour in hot broth and seasoning, then stir once to distribute rice."),
      step(8, "Simmer covered", "Cover and simmer on low until rice is tender; avoid lifting the lid often."),
      step(9, "Fluff and hold", "Fluff with a fork and hold covered above 140°F if a call delays dinner."),
      step(10, "Serve skillet", "Spoon dirty rice into bowls and offer hot sauce rather than over-spicing the whole batch."),
      CALL_INTERRUPTION_STEP(11, "Sausage and beef"),
      LEFTOVERS_PACK_DOWN_STEP(12, "Sausage and beef"),
    ],
    proTips: ["Use mild sausage for mixed heat preferences.","Keep the lid tight while rice steams.","Add broth, not water, if rice is underdone."],
    tonightSpread: buildStructuredTonightSpread("Cajun dirty rice skillet", ["green beans","cornbread"], ["hot sauce","green onions","pickles"]),
    leftovers: standardLeftovers("Sausage and beef", ["Stuff leftovers into peppers."]),
    equipment: ["deep skillet","lid","thermometer"],
    nutrition: {"calories":690,"protein":37,"carbs":68,"fats":30,"fiber":5},
    spiceLevel: "medium",
    cleanupDifficulty: "medium",
    searchTerms: ["dirty rice skillet crowd","Cajun rice crew dinner","one pot sausage rice ten","budget firehall skillet"],
    substitutions: ["Use turkey sausage for andouille.","Use ground turkey for beef."],
  }),
  def({
    slug: "sausage-gnocchi-skillet",
    title: "Sausage Gnocchi Skillet",
    subtitle: "Creamy tomato gnocchi with sausage and spinach",
    category: "crew_feeders",
    protein: "sausage",
    cuisine: "Italian-American",
    mealFormat: "skillet",
    explorePools: ["one_pot","weeknight"],
    hookLine: "Shelf-stable gnocchi and sausage create a restaurant-style skillet in under an hour.",
    description: "Italian sausage, pillowy gnocchi, tomato sauce, spinach, and mozzarella cook into a quick crew dinner.",
    whyCrewsLikeIt: "It is fast enough for a weeknight and needs only one skillet plus a side salad.",
    mealPrepNotes: "Make-ahead: slice sausage and grate cheese 1 day ahead. Storage: refrigerate 3 days. Reheating: heat sausage and sauce to 165°F.",
    stationWorkflow: ["Brown sausage","Simmer gnocchi in sauce","Melt cheese and serve"],
    prepMinutes: 15,
    cookMinutes: 30,
    difficulty: "easy",
    crewSizeDefault: 10,
    ingredients: [
      ing("Italian sausage", "5", { unit: "lb" }),
      ing("shelf-stable gnocchi", "6", { unit: "lb" }),
      ing("marinara sauce", "12", { unit: "cups" }),
      ing("spinach", "2", { unit: "lb" }),
      ing("mozzarella", "3", { unit: "lb" }),
      ing("onions", "2", { unit: "each" }),
    ],
    steps: [
      step(1, "Heat skillet", "Heat a deep skillet over medium-high so sausage browns before the sauce is added."),
      step(2, "Brown sausage", "Cook sausage, breaking it into bite-size pieces until browned and no pink remains."),
      step(3, "Check sausage", "Confirm sausage reaches 165°F with a thermometer before continuing."),
      step(4, "Soften onion", "Add onion and cook until translucent, scraping any browned sausage bits into the pan."),
      step(5, "Add sauce", "Pour in marinara and a little water, then bring it to a gentle simmer."),
      step(6, "Cook gnocchi", "Stir gnocchi into sauce and simmer until tender; stir often so it does not stick."),
      step(7, "Wilt spinach", "Add spinach in handfuls and fold until it wilts into the hot sauce."),
      step(8, "Melt cheese", "Scatter mozzarella over the top, cover, and let residual steam melt it without scorching."),
      step(9, "Hold safely", "Keep the skillet covered above 140°F; loosen with hot water if gnocchi thickens."),
      step(10, "Spoon servings", "Serve immediately with a wide spoon so each portion includes sausage, gnocchi, and sauce."),
      CALL_INTERRUPTION_STEP(11, "Italian sausage"),
      LEFTOVERS_PACK_DOWN_STEP(12, "Italian sausage"),
    ],
    proTips: ["Use two skillets for faster service.","Do not boil gnocchi aggressively or it can break.","Add red pepper flakes individually."],
    tonightSpread: buildStructuredTonightSpread("Creamy sausage gnocchi skillet", ["garlic bread","Italian salad"], ["parmesan","red pepper flakes","basil"]),
    leftovers: standardLeftovers("Italian sausage", ["Bake leftovers with extra mozzarella."]),
    equipment: ["deep skillet with lid","thermometer","wide spoon"],
    nutrition: {"calories":760,"protein":35,"carbs":75,"fats":35,"fiber":6},
    spiceLevel: "mild",
    cleanupDifficulty: "easy",
    searchTerms: ["sausage gnocchi skillet crowd","one pot gnocchi dinner ten","Italian sausage firehall meal","weeknight crew skillet"],
    substitutions: ["Use turkey sausage for pork sausage.","Use kale for spinach."],
  }),
  def({
    slug: "spanish-rice-chicken-one-pot",
    title: "Spanish Rice Chicken One Pot",
    subtitle: "Saffron-style chicken, peppers, peas, and rice",
    category: "crew_feeders",
    protein: "chicken",
    cuisine: "Spanish-inspired",
    mealFormat: "one_pot",
    explorePools: ["one_pot","budget"],
    hookLine: "A colourful one-pot chicken and rice dinner that holds together on a busy shift.",
    description: "Chicken thighs, tomatoes, peppers, peas, and seasoned rice simmer in one broad pot until tender.",
    whyCrewsLikeIt: "It turns basic pantry staples into a complete meal with only one main pan to clean.",
    mealPrepNotes: "Make-ahead: season chicken and chop vegetables 1 day ahead. Storage: refrigerate 3 days. Reheating: heat chicken and rice to 165°F.",
    stationWorkflow: ["Brown chicken","Build seasoned rice","Steam covered until tender"],
    prepMinutes: 25,
    cookMinutes: 45,
    difficulty: "medium",
    crewSizeDefault: 10,
    ingredients: [
      ing("boneless chicken thighs", "6", { unit: "lb" }),
      ing("long-grain rice", "5", { unit: "cups" }),
      ing("chicken broth", "12", { unit: "cups" }),
      ing("diced tomatoes", "4", { unit: "cans" }),
      ing("bell peppers", "6", { unit: "each" }),
      ing("frozen peas", "3", { unit: "lb" }),
    ],
    steps: [
      step(1, "Season chicken", "Season chicken pieces with smoked paprika, garlic, salt, and pepper on a clean tray."),
      step(2, "Brown chicken", "Brown chicken in a wide heavy pot in batches; crowding will make it pale and watery."),
      step(3, "Check chicken", "The chicken will finish later, but keep raw utensils away from cooked vegetables and rice."),
      step(4, "Cook vegetables", "Sauté onion and peppers in the same pot until softened and lightly golden."),
      step(5, "Toast rice", "Stir rice for 2 minutes in the pan fat until the grains look glossy and separate."),
      step(6, "Add liquid", "Stir in tomatoes, hot broth, and seasoning, scraping the bottom so nothing sticks."),
      step(7, "Return chicken", "Nestle chicken into the rice in one layer, leaving some pieces visible for even cooking."),
      step(8, "Simmer covered", "Cover and cook on low until rice is tender and chicken reaches 165°F in the thickest piece."),
      step(9, "Add peas and hold", "Fold in peas, cover 5 minutes, then keep the pot above 140°F if needed."),
      step(10, "Serve one pot", "Fluff rice gently and serve chicken with the vegetables and tomato-rich rice."),
      CALL_INTERRUPTION_STEP(11, "Chicken thighs"),
      LEFTOVERS_PACK_DOWN_STEP(12, "Chicken thighs"),
    ],
    proTips: ["Use a wide pot so rice cooks evenly.","If rice is firm, add hot broth and cover again.","Do not stir repeatedly once the pot is covered."],
    tonightSpread: buildStructuredTonightSpread("Spanish chicken and rice", ["green salad","crusty bread"], ["lemon wedges","hot sauce","parsley"]),
    leftovers: standardLeftovers("Chicken thighs", ["Turn leftovers into stuffed peppers."]),
    equipment: ["wide Dutch oven with lid","tongs","thermometer"],
    nutrition: {"calories":650,"protein":42,"carbs":72,"fats":20,"fiber":7},
    spiceLevel: "mild",
    cleanupDifficulty: "medium",
    searchTerms: ["Spanish chicken rice one pot crowd","one pot chicken rice for ten","budget firehall chicken dinner","skillet chicken and rice"],
    substitutions: ["Use chicken breasts for thighs.","Use brown rice with extra broth and time."],
  })
];

export const BATCH_WAVE1_EXPANSION_COUNT = BATCH_WAVE1_EXPANSION_RECIPES.length;
