import { def, ing, step } from "../recipe-build.js";
import type { ExpansionRecipeDef } from "../types.js";

export const PHASE5_DISTINCT_RECIPES: ExpansionRecipeDef[] = [
  def({
    slug: "montreal-smoked-meat-platter",
    title: "Montreal Smoked Meat Platter",
    subtitle: "Steamed brisket-style beef piled high with mustard and rye for ten",
    category: "crew_feeders",
    protein: "beef",
    cuisine: "canadian",
    mealFormat: "platter",
    explorePools: ["hall_expansion", "crew_feeders", "canadian", "beef"],
    hookLine: "Deli-counter smoked meat energy without leaving the hall kitchen",
    description:
      "Beef brisket gets a Montreal-style coriander-and-pepper cure, slow-roasts until fork-tender, then steams and slices paper-thin for a classic smoked meat platter. Serve stacked on rye with yellow mustard, dill pickles, and coleslaw.",
    whyCrewsLikeIt:
      "Smoked meat night feels like a hall field trip to the old neighborhood. Sliced thin and piled high, it feeds fast between tones and satisfies the crew that wants real sandwich meat, not deli turkey from a plastic sleeve.",
    mealPrepNotes:
      "Cure brisket up to 48 hours ahead for deeper flavor. Steam sliced meat in hotel pans with a splash of broth so it stays moist on the hold line. Slice against the grain as thin as your knife skills allow.",
    stationWorkflow: [
      "Weigh brisket before curing so salt ratios stay consistent across batches.",
      "Rest roasted brisket wrapped in foil at least 30 minutes before slicing—rushing this step costs you juice.",
      "Keep mustard, pickles, and rye bread in separate labeled bins so the line moves without a bottleneck.",
    ],
    prepMinutes: 45,
    cookMinutes: 300,
    difficulty: "medium",
    crewSizeDefault: 10,
    ingredients: [
      ing("beef brisket flat", "6", { unit: "lb", notes: "trimmed", group: "Main" }),
      ing("kosher salt", "0.33", { unit: "cup", group: "Cure" }),
      ing("coriander seeds", "3", { unit: "tbsp", notes: "toasted and cracked", group: "Cure" }),
      ing("black peppercorns", "2", { unit: "tbsp", notes: "cracked", group: "Cure" }),
      ing("garlic powder", "1", { unit: "tbsp", group: "Cure" }),
      ing("brown sugar", "2", { unit: "tbsp", group: "Cure" }),
      ing("beef broth", "2", { unit: "cups", notes: "for steaming", group: "Service" }),
      ing("rye bread", "20", { unit: "slices", group: "Service" }),
      ing("yellow mustard", "1", { unit: "cup", group: "Service" }),
      ing("dill pickle spears", "20", { unit: "spears", group: "Service" }),
      ing("coleslaw", "4", { unit: "cups", notes: "prepared or quick-made", group: "Service" }),
    ],
    steps: [
      step(1, "Cure the brisket", "Mix salt, cracked coriander, pepper, garlic powder, and brown sugar. Coat brisket evenly, wrap tight, and refrigerate 24–48 hours, flipping once.", { minutes: 20 }),
      step(2, "Roast low and slow", "Rinse cure lightly, pat dry, and roast uncovered at 275°F fat-side up until probe-tender at 203°F internal, about 4–5 hours.", { minutes: 270, tempF: 275 }),
      step(3, "Rest and chill slightly", "Wrap brisket in foil and rest 30 minutes. Chill 1 hour if you want cleaner slices—warm meat still works for service night.", { minutes: 30 }),
      step(4, "Slice and steam", "Slice against the grain as thin as possible. Layer in hotel pans with a splash of warm broth, cover, and steam or hold at 165°F until service.", { minutes: 20 }),
      step(5, "Build the platter line", "Fan sliced meat on platters with rye, mustard, pickles, and coleslaw. Let crew stack their own sandwiches or plate open-face for speed.", { minutes: 10 }),
    ],
    proTips: [
      "A sharp slicer knife beats a dull chef knife—dedicate one to smoked meat duty.",
      "Save trim for hash or soup base; Montreal-style beef trim is pure flavor.",
      "Offer a side of sauerkraut for crew who want that classic deli counter combo.",
    ],
    tonightSpread: [
      "Smoked meat platters with rye, mustard, pickles, and vinegar coleslaw.",
      "Hot fries dusted with Montreal steak spice for a poutine-adjacent side without duplicating poutine night.",
    ],
    leftovers: [
      "Chop and griddle with onions for smoked meat hash with fried eggs.",
      "Layer into grilled cheese with Swiss for a hall-style melt.",
    ],
    equipment: ["Roasting pan", "Instant-read thermometer", "Hotel pans", "Sharp slicer knife", "Cutting board"],
    nutrition: { calories: 520, protein: 42, carbs: 38, fats: 22, fiber: 3 },
    spiceLevel: "mild",
    cleanupDifficulty: "medium",
  }),

  def({
    slug: "tourtiere-for-the-crew",
    title: "Tourtière for the Crew",
    subtitle: "Savory pork-and-beef pie with warm spice baked for ten",
    category: "crew_feeders",
    protein: "pork",
    cuisine: "canadian",
    mealFormat: "bake",
    explorePools: ["hall_expansion", "crew_feeders", "canadian", "pork"],
    hookLine: "Quebec holiday pie scaled for a hungry hall—not a single family table",
    description:
      "Ground pork and beef simmer with onion, potato, and warm spices until rich and fragrant, then bake inside flaky double-crust pies. Cut into hearty wedges and serve with ketchup and cranberry sauce at the line.",
    whyCrewsLikeIt:
      "Tourtière is pure Canadian comfort—familiar to northern halls, new to southern crews, and universally satisfying on cold shift nights. Two big pies feed ten with leftovers for the next watch.",
    mealPrepNotes:
      "Filling can be made a day ahead and chilled. Use deep-dish pie plates or one large half-sheet tray pie for easier portioning. Vent crust well so steam escapes and bottom crust stays crisp.",
    stationWorkflow: [
      "Cook filling until almost dry—wet filling makes soggy bottom crust every time.",
      "Chill filling 30 minutes before filling shells so pastry does not melt on contact.",
      "Score pie tops with crew numbers or shift initials if you are feeling festive.",
    ],
    prepMinutes: 40,
    cookMinutes: 55,
    difficulty: "medium",
    crewSizeDefault: 10,
    ingredients: [
      ing("ground pork", "2", { unit: "lb", group: "Filling" }),
      ing("ground beef", "1", { unit: "lb", group: "Filling" }),
      ing("yellow onion", "2", { unit: "whole", notes: "finely diced", group: "Filling" }),
      ing("russet potato", "1", { unit: "large", notes: "finely diced", group: "Filling" }),
      ing("garlic cloves", "4", { unit: "cloves", notes: "minced", group: "Filling" }),
      ing("ground cinnamon", "1", { unit: "tsp", group: "Spice" }),
      ing("ground cloves", "0.5", { unit: "tsp", group: "Spice" }),
      ing("dried sage", "1", { unit: "tsp", group: "Spice" }),
      ing("pie crust", "4", { unit: "sheets", notes: "store-bought or homemade", group: "Crust" }),
      ing("beef broth", "0.5", { unit: "cup", group: "Filling" }),
      ing("egg", "1", { unit: "whole", notes: "for egg wash", group: "Finish" }),
    ],
    steps: [
      step(1, "Brown the meat", "Cook pork and beef in a large skillet over medium-high heat, breaking up clumps until browned. Drain excess fat, leaving about 2 tablespoons in the pan.", { minutes: 12 }),
      step(2, "Build the filling", "Add onion, potato, and garlic. Cook 8 minutes until softened. Stir in cinnamon, cloves, sage, salt, pepper, and broth. Simmer until moisture mostly evaporates and filling looks thick.", { minutes: 15 }),
      step(3, "Cool the filling", "Spread filling on a sheet pan and cool 30 minutes. Hot filling will destroy your pie crust on contact.", { minutes: 30 }),
      step(4, "Assemble and bake", "Line two deep pie dishes with crust, fill evenly, top with second crust, crimp edges, cut vents, and brush with egg wash. Bake at 375°F until golden and bubbling, 45–50 minutes.", { minutes: 48, tempF: 375 }),
      step(5, "Rest and portion", "Rest pies 15 minutes before cutting into wedges. Serve with ketchup and cranberry sauce at the line.", { minutes: 15 }),
    ],
    proTips: [
      "A splash of Worcestershire in the filling adds depth without changing the classic profile.",
      "If bottom crust worries you, blind-bake 8 minutes before filling.",
      "Make one pie spicy with cayenne for the crew that always asks for heat.",
    ],
    tonightSpread: [
      "Tourtière wedges with ketchup, cranberry sauce, and a simple pea salad.",
      "Pickled beets on the side for a bright counter to rich meat filling.",
    ],
    leftovers: [
      "Reheat wedges in the oven so crust re-crispes—microwave makes it sad.",
      "Crumble cold filling into scrambled eggs for a Quebec-style breakfast shift.",
    ],
    equipment: ["Large skillet", "Deep pie dishes", "Sheet pan", "Pastry brush", "Instant-read thermometer"],
    nutrition: { calories: 580, protein: 28, carbs: 42, fats: 34, fiber: 2 },
    spiceLevel: "mild",
    cleanupDifficulty: "medium",
  }),

  def({
    slug: "firehall-donair-platter",
    title: "Firehall Donair Platter",
    subtitle: "Spiced beef cones roasted and shaved with sweet sauce for ten",
    category: "crew_feeders",
    protein: "beef",
    cuisine: "canadian",
    mealFormat: "platter",
    explorePools: ["hall_expansion", "crew_feeders", "canadian", "beef"],
    hookLine: "East Coast donair night without the corner-shop rotisserie",
    description:
      "Seasoned ground beef is pressed around vertical skewers, roasted until crisp-edged, then shaved thin for donair platters. Serve with warm pita, diced tomatoes, onions, and sweet garlicky donair sauce.",
    whyCrewsLikeIt:
      "Donair is a Canadian hall legend—messy, satisfying, and impossible to eat quietly. Shaved meat platters let crews build wraps fast or plate it open-face when tones drop mid-meal.",
    mealPrepNotes:
      "Form meat cones the night before on skewers set in loaf pans for stability. Donair sauce keeps 5 days refrigerated. Hold shaved meat at 165°F with a light broth mist.",
    stationWorkflow: [
      "Press meat firmly around skewers—loose cones fall apart when you shave.",
      "Rotate pans halfway through roasting for even browning on all sides.",
      "Keep sauce in squeeze bottles so the line does not drown every wrap the same way.",
    ],
    prepMinutes: 35,
    cookMinutes: 65,
    difficulty: "medium",
    crewSizeDefault: 9,
    ingredients: [
      ing("ground beef", "5", { unit: "lb", notes: "80/20", group: "Main" }),
      ing("ground lamb", "1", { unit: "lb", notes: "optional for authenticity", group: "Main" }),
      ing("garlic powder", "2", { unit: "tbsp", group: "Seasoning" }),
      ing("onion powder", "2", { unit: "tbsp", group: "Seasoning" }),
      ing("ground oregano", "1", { unit: "tbsp", group: "Seasoning" }),
      ing("paprika", "1", { unit: "tbsp", group: "Seasoning" }),
      ing("sweetened condensed milk", "0.5", { unit: "cup", group: "Sauce" }),
      ing("white vinegar", "0.33", { unit: "cup", group: "Sauce" }),
      ing("garlic cloves", "3", { unit: "cloves", notes: "minced", group: "Sauce" }),
      ing("pita bread", "12", { unit: "rounds", notes: "warmed", group: "Service" }),
      ing("tomatoes", "3", { unit: "whole", notes: "diced", group: "Service" }),
      ing("white onion", "1", { unit: "whole", notes: "finely diced", group: "Service" }),
    ],
    steps: [
      step(1, "Season the meat", "Mix beef, lamb if using, garlic powder, onion powder, oregano, paprika, salt, and pepper until sticky and uniform.", { minutes: 10 }),
      step(2, "Form the cones", "Press seasoned meat around metal skewers or dowels set in loaf pans, packing tight into cone shapes about 6 inches tall.", { minutes: 20 }),
      step(3, "Roast until browned", "Roast at 350°F, rotating pans, until exterior is deeply browned and internal temp hits 165°F, about 50–60 minutes.", { minutes: 55, tempF: 350 }),
      step(4, "Make donair sauce", "Whisk condensed milk, vinegar, and garlic until smooth and tangy. Thin with a tablespoon of water if too thick.", { minutes: 5 }),
      step(5, "Shave and serve", "Rest cones 10 minutes, shave meat thin with a sharp knife, and pile on platters with warmed pita, tomatoes, onions, and sauce at the line.", { minutes: 15 }),
    ],
    proTips: [
      "A little baking soda in the mix helps bind—just a quarter teaspoon for the batch.",
      "Offer lettuce for crew who want crunch without turning it into a generic wrap bar.",
      "Save rendered fat from the pan to crisp pita edges on the griddle.",
    ],
    tonightSpread: [
      "Shaved donair meat with pita, tomatoes, onions, and sweet sauce.",
      "Garlic fingers or fries on the side for the full Halifax-style spread.",
    ],
    leftovers: [
      "Reheat shaved meat in a skillet with sauce for quick donair bowls over rice—not the same as a burrito bowl, just honest leftovers.",
      "Stuff into sub rolls for donair cheesesteaks on the next shift.",
    ],
    equipment: ["Loaf pans", "Metal skewers", "Roasting pans", "Sharp knife", "Mixing bowls"],
    nutrition: { calories: 540, protein: 38, carbs: 36, fats: 28, fiber: 2 },
    spiceLevel: "mild",
    cleanupDifficulty: "medium",
  }),

  def({
    slug: "maple-cured-salmon-plank",
    title: "Maple-Cured Salmon Plank",
    subtitle: "Cedar-planked salmon with maple glaze for ten on the grill",
    category: "crew_feeders",
    protein: "salmon",
    cuisine: "canadian",
    mealFormat: "grill",
    explorePools: ["hall_expansion", "crew_feeders", "canadian", "salmon"],
    hookLine: "Canadian maple meets cedar smoke without a fancy seafood restaurant budget",
    description:
      "Salmon fillets get a quick maple-brine, then grill on cedar planks until edges caramelize and centers stay moist. Flake onto platters with lemon-dill yogurt and roasted asparagus.",
    whyCrewsLikeIt:
      "Salmon night upgrades the hall menu without feeling fussy. Plank grilling keeps fish off direct flame, reduces sticking, and delivers real smoke aroma—even on a gas grill behind the station.",
    mealPrepNotes:
      "Brine fillets up to 4 hours ahead. Soak cedar planks at least 1 hour. Pat salmon dry before grilling so maple glaze caramelizes instead of steaming off.",
    stationWorkflow: [
      "Weight planks under water with a sheet pan so they soak evenly.",
      "Brush glaze only in the last 6 minutes—sugar burns fast over high heat.",
      "Use two probes on the largest fillets so you are not guessing on doneness.",
    ],
    prepMinutes: 30,
    cookMinutes: 25,
    difficulty: "medium",
    crewSizeDefault: 8,
    ingredients: [
      ing("salmon fillets", "5", { unit: "lb", notes: "skin-on, portioned", group: "Main" }),
      ing("maple syrup", "0.33", { unit: "cup", group: "Brine" }),
      ing("kosher salt", "3", { unit: "tbsp", group: "Brine" }),
      ing("brown sugar", "2", { unit: "tbsp", group: "Glaze" }),
      ing("Dijon mustard", "2", { unit: "tbsp", group: "Glaze" }),
      ing("soy sauce", "1", { unit: "tbsp", group: "Glaze" }),
      ing("cedar grilling planks", "4", { unit: "planks", notes: "soaked", group: "Grill" }),
      ing("Greek yogurt", "1", { unit: "cup", group: "Sauce" }),
      ing("fresh dill", "0.25", { unit: "cup", notes: "chopped", group: "Sauce" }),
      ing("lemon", "2", { unit: "whole", notes: "zested and juiced", group: "Sauce" }),
      ing("asparagus", "2", { unit: "lb", notes: "trimmed", group: "Side" }),
    ],
    steps: [
      step(1, "Brine the salmon", "Dissolve salt in cold water with maple syrup. Submerge salmon 30–60 minutes, then pat completely dry.", { minutes: 15 }),
      step(2, "Soak cedar planks", "Submerge planks in water at least 1 hour so they smolder instead of catching fire on the grill.", { minutes: 60 }),
      step(3, "Prep glaze and sauce", "Whisk maple syrup, brown sugar, Dijon, and soy for glaze. Mix yogurt, dill, lemon zest, and juice for sauce. Refrigerate until service.", { minutes: 10 }),
      step(4, "Grill on planks", "Heat grill to medium-high, about 400°F. Place salmon on planks, close lid, and grill 12–15 minutes until centers reach 125°F for medium or 140°F for well-done.", { minutes: 15, tempF: 400 }),
      step(5, "Glaze and platter", "Brush glaze in final 6 minutes. Rest salmon 5 minutes, flake or portion onto platters with yogurt sauce and grilled asparagus.", { minutes: 10 }),
    ],
    proTips: [
      "Keep a spray bottle near the grill—planks can flare if glaze drips.",
      "Offer capers for crew who want a bagel-and-lox vibe without the bagels.",
      "Save plank trim for smoking wood chips on the next BBQ night.",
    ],
    tonightSpread: [
      "Planked salmon with dill yogurt, grilled asparagus, and lemon wedges.",
      "Wild rice pilaf for a plate that feels complete without heavy starches.",
    ],
    leftovers: [
      "Flake cold salmon into salads with the yogurt sauce as dressing.",
      "Make salmon cakes with panko and egg for a fast lunch shift.",
    ],
    equipment: ["Grill", "Cedar planks", "Instant-read thermometer", "Sheet pan", "Basting brush"],
    nutrition: { calories: 420, protein: 40, carbs: 18, fats: 22, fiber: 2 },
    spiceLevel: "mild",
    cleanupDifficulty: "easy",
  }),

  def({
    slug: "classic-poutine-feed-crew",
    title: "Classic Poutine Feed for the Crew",
    subtitle: "Double-fried fries with beef gravy and cheese curds for ten",
    category: "crew_feeders",
    protein: "beef",
    cuisine: "canadian",
    mealFormat: "platter",
    explorePools: ["hall_expansion", "crew_feeders", "canadian", "beef"],
    hookLine: "Real Quebec poutine—not breakfast poutine, not fancy truffle fries",
    description:
      "Russet potatoes are cut thick, fried twice until shatter-crisp, then topped with hot beef gravy and squeaky cheese curds. Serve immediately on platters because poutine waits for no one—not even the captain.",
    whyCrewsLikeIt:
      "Poutine is the ultimate Canadian hall comfort food. Crisp fries, rich gravy, and melting curds hit every craving after a cold call. This is the real deal—no poached eggs, no pulled pork gimmicks.",
    mealPrepNotes:
      "Par-fry potatoes earlier in the day and finish-fry at service. Gravy must be hot enough to soften curds but not so hot it breaks them to mush. Work in batches so fries stay crisp.",
    stationWorkflow: [
      "Salt fries immediately out of the second fry so seasoning sticks.",
      "Hold gravy in a bain-marie at 180°F—too cool and curds never melt right.",
      "Assemble to order or in small hotel pans max—soggy poutine kills morale.",
    ],
    prepMinutes: 35,
    cookMinutes: 40,
    difficulty: "medium",
    crewSizeDefault: 10,
    ingredients: [
      ing("russet potatoes", "8", { unit: "lb", notes: "cut into thick fries", group: "Fries" }),
      ing("vegetable oil", "2", { unit: "gal", notes: "for frying", group: "Fries" }),
      ing("beef broth", "4", { unit: "cups", group: "Gravy" }),
      ing("beef drippings or butter", "4", { unit: "tbsp", group: "Gravy" }),
      ing("all-purpose flour", "0.25", { unit: "cup", group: "Gravy" }),
      ing("Worcestershire sauce", "1", { unit: "tbsp", group: "Gravy" }),
      ing("garlic powder", "1", { unit: "tsp", group: "Gravy" }),
      ing("cheese curds", "2", { unit: "lb", notes: "room temperature", group: "Finish" }),
      ing("kosher salt", "2", { unit: "tbsp", group: "Seasoning" }),
      ing("black pepper", "1", { unit: "tsp", group: "Seasoning" }),
    ],
    steps: [
      step(1, "Cut and soak fries", "Cut potatoes into thick fries, soak in cold water 30 minutes, then drain and dry completely on towels.", { minutes: 35 }),
      step(2, "First fry", "Blanch fries in 325°F oil 4–5 minutes until soft but not browned. Drain, cool on racks at least 20 minutes.", { minutes: 25, tempF: 325 }),
      step(3, "Build beef gravy", "Melt drippings, whisk in flour, cook 2 minutes, then whisk in broth, Worcestershire, and garlic powder. Simmer until thick enough to coat a spoon.", { minutes: 12 }),
      step(4, "Second fry", "Fry blanched potatoes at 375°F until deep golden and crisp, 3–4 minutes. Drain, salt immediately.", { minutes: 15, tempF: 375 }),
      step(5, "Assemble and serve", "Pile hot fries on platters, scatter curds, ladle hot gravy over top, and serve at once with pepper mills on the table.", { minutes: 5 }),
    ],
    proTips: [
      "If curds are unavailable, use whole-milk mozzarella torn into chunks—never pre-shredded.",
      "A splash of apple cider vinegar in gravy adds Quebec-style tang.",
      "Vent the fryer area—poutine night smokes up the hall fast.",
    ],
    tonightSpread: [
      "Classic poutine platters with extra gravy on the side.",
      "Simple vinegar coleslaw to cut the richness between bites.",
    ],
    leftovers: [
      "Honestly? Leftover poutine is a lost cause—plan portions tight.",
      "Save gravy for hot beef sandwiches the next shift.",
    ],
    equipment: ["Deep fryer or heavy pot", "Candy thermometer", "Wire racks", "Sauce pot", "Sheet pans"],
    nutrition: { calories: 680, protein: 18, carbs: 72, fats: 36, fiber: 5 },
    spiceLevel: "mild",
    cleanupDifficulty: "heavy",
  }),

  def({
    slug: "cottage-pie-for-the-crew",
    title: "Cottage Pie for the Crew",
    subtitle: "Ground beef and vegetables under golden mashed potato for ten",
    category: "crew_feeders",
    protein: "beef",
    cuisine: "british",
    mealFormat: "bake",
    explorePools: ["hall_expansion", "crew_feeders", "british", "beef"],
    hookLine: "Shepherd's beef cousin—mashed potato lid, rich meat base, zero fuss",
    description:
      "Ground beef browns with onion, carrot, and peas in a savory gravy, then bakes under a thick layer of buttery mashed potatoes until the top turns golden. Portion from a large casserole for classic British pub comfort.",
    whyCrewsLikeIt:
      "Cottage pie is stick-to-your-ribs food after wet calls. One casserole feeds the hall, slices clean, and reheats well for the next watch—important when you never know who is eating when.",
    mealPrepNotes:
      "Assemble fully ahead and refrigerate—bake add 15 minutes if going straight from cold. Pipe or fork-ruffle potato top for extra crisp edges. Rest 10 minutes before cutting so slices hold shape.",
    stationWorkflow: [
      "Reduce filling until thick—runny gravy makes potato topping slide off in service.",
      "Cool filling before topping with potatoes or they melt into the meat.",
      "Brush potato peaks with melted butter for better browning in the oven.",
    ],
    prepMinutes: 35,
    cookMinutes: 45,
    difficulty: "easy",
    crewSizeDefault: 10,
    ingredients: [
      ing("ground beef", "3", { unit: "lb", group: "Filling" }),
      ing("yellow onion", "2", { unit: "whole", notes: "diced", group: "Filling" }),
      ing("carrots", "3", { unit: "whole", notes: "diced", group: "Filling" }),
      ing("frozen peas", "1.5", { unit: "cups", group: "Filling" }),
      ing("tomato paste", "2", { unit: "tbsp", group: "Filling" }),
      ing("beef broth", "2", { unit: "cups", group: "Filling" }),
      ing("Worcestershire sauce", "2", { unit: "tbsp", group: "Filling" }),
      ing("russet potatoes", "4", { unit: "lb", notes: "peeled and cubed", group: "Topping" }),
      ing("butter", "6", { unit: "tbsp", group: "Topping" }),
      ing("whole milk", "0.75", { unit: "cup", group: "Topping" }),
      ing("cheddar cheese", "1", { unit: "cup", notes: "grated", group: "Topping" }),
    ],
    steps: [
      step(1, "Brown the beef filling", "Cook ground beef with onion and carrots until beef is browned and vegetables soften, about 12 minutes. Drain excess fat.", { minutes: 12 }),
      step(2, "Simmer the gravy", "Stir in tomato paste, broth, Worcestershire, salt, and pepper. Simmer 10 minutes until thickened, then fold in peas and cool slightly.", { minutes: 12 }),
      step(3, "Mash the potatoes", "Boil potatoes until tender, drain well, then mash with butter, milk, and salt until smooth and spreadable.", { minutes: 20 }),
      step(4, "Assemble the pie", "Spread beef filling in a large buttered casserole. Top with mashed potatoes, ruffle with a fork, and scatter cheddar over peaks.", { minutes: 10 }),
      step(5, "Bake and serve", "Bake at 400°F until potato top is golden and filling bubbles at edges, 30–35 minutes. Rest 10 minutes before portioning.", { minutes: 35, tempF: 400 }),
    ],
    proTips: [
      "Add a teaspoon of Marmite to the gravy for authentic depth—start small.",
      "Individual ramekins portion faster on busy nights than one huge casserole.",
      "HP sauce on the side makes British crews instantly happier.",
    ],
    tonightSpread: [
      "Cottage pie wedges with HP sauce and steamed green beans.",
      "Crusty bread for mopping gravy from the pan.",
    ],
    leftovers: [
      "Reheat covered in oven with extra gravy spooned over dried edges.",
      "Press cold leftovers into patties and pan-fry for cottage pie cakes.",
    ],
    equipment: ["Large casserole dish", "Potato masher", "Large skillet", "Sauce pot", "Sheet pan"],
    nutrition: { calories: 520, protein: 32, carbs: 48, fats: 24, fiber: 5 },
    spiceLevel: "mild",
    cleanupDifficulty: "medium",
  }),

  def({
    slug: "chicken-paprikash-hall",
    title: "Chicken Paprikash for the Hall",
    subtitle: "Hungarian paprika stew with sour cream over egg noodles for ten",
    category: "crew_feeders",
    protein: "chicken",
    cuisine: "hungarian",
    mealFormat: "stew",
    explorePools: ["hall_expansion", "crew_feeders", "hungarian", "chicken"],
    hookLine: "Deep paprika color, real stew depth—not another generic chicken skillet",
    description:
      "Chicken thighs braise in a brick-red paprika sauce with onion and bell pepper until tender, then finish with sour cream off heat. Serve over buttered egg noodles with extra paprika at the line.",
    whyCrewsLikeIt:
      "Paprikash brings Eastern European comfort to halls that already ran out of chili ideas. The sauce is rich but not cream-pasta heavy, and thighs stay juicy on the hold line.",
    mealPrepNotes:
      "Bloom paprika in fat briefly—never burn it or the whole pot turns bitter. Stir sour cream off heat to prevent curdling. Hold noodles and sauce separately if holding over 30 minutes.",
    stationWorkflow: [
      "Use sweet Hungarian paprika if you can find it—the flavor difference is real.",
      "Brown chicken skin-side down first for fond that builds the stew base.",
      "Portion noodles first, then ladle sauce so every plate gets equal chicken.",
    ],
    prepMinutes: 25,
    cookMinutes: 50,
    difficulty: "medium",
    crewSizeDefault: 9,
    ingredients: [
      ing("bone-in chicken thighs", "5", { unit: "lb", notes: "about 16 pieces", group: "Main" }),
      ing("sweet paprika", "3", { unit: "tbsp", group: "Sauce" }),
      ing("yellow onion", "2", { unit: "whole", notes: "sliced", group: "Sauce" }),
      ing("red bell pepper", "2", { unit: "whole", notes: "sliced", group: "Sauce" }),
      ing("garlic cloves", "5", { unit: "cloves", notes: "minced", group: "Sauce" }),
      ing("tomato paste", "2", { unit: "tbsp", group: "Sauce" }),
      ing("chicken broth", "3", { unit: "cups", group: "Sauce" }),
      ing("sour cream", "1", { unit: "cup", group: "Finish" }),
      ing("egg noodles", "2", { unit: "lb", group: "Base" }),
      ing("butter", "4", { unit: "tbsp", group: "Base" }),
      ing("fresh parsley", "0.25", { unit: "cup", notes: "chopped", group: "Finish" }),
    ],
    steps: [
      step(1, "Brown the chicken", "Season thighs with salt and pepper. Sear skin-side down in a Dutch oven until golden, flip briefly, then set aside.", { minutes: 12 }),
      step(2, "Build paprika base", "Sauté onion and bell pepper in the same pot 6 minutes. Stir in paprika and garlic, cook 1 minute until fragrant, then add tomato paste.", { minutes: 8 }),
      step(3, "Braise until tender", "Add broth, nestle chicken skin-side up, cover, and simmer 35–40 minutes until chicken reaches 165°F and sauce thickens.", { minutes: 38 }),
      step(4, "Finish with sour cream", "Remove pot from heat. Stir sour cream in gradually until sauce turns silky. Taste and adjust salt.", { minutes: 5 }),
      step(5, "Boil noodles and serve", "Cook egg noodles, toss with butter, and portion into bowls. Top with chicken, sauce, and parsley.", { minutes: 12 }),
    ],
    proTips: [
      "A pinch of caraway seed in the base adds classic Hungarian aroma.",
      "Pull chicken bones at the line if your crew prefers fork-only eating.",
      "Hot paprika on the side lets spice lovers upgrade without changing the batch.",
    ],
    tonightSpread: [
      "Paprikash over noodles with cucumber salad in sour cream dressing.",
      "Crusty bread for soaking up every bit of red sauce.",
    ],
    leftovers: [
      "Shred chicken into sauce and reheat gently for next-day stew.",
      "Reduce sauce further and use as a filling for savory hand pies.",
    ],
    equipment: ["Dutch oven", "Large pot", "Instant-read thermometer", "Tongs", "Ladle"],
    nutrition: { calories: 490, protein: 36, carbs: 44, fats: 20, fiber: 3 },
    spiceLevel: "mild",
    cleanupDifficulty: "medium",
  }),

  def({
    slug: "chicken-cacciatore-crew",
    title: "Chicken Cacciatore for the Crew",
    subtitle: "Italian hunter-style chicken braised with tomatoes and peppers for ten",
    category: "crew_feeders",
    protein: "chicken",
    cuisine: "italian",
    mealFormat: "braise",
    explorePools: ["hall_expansion", "crew_feeders", "italian", "chicken"],
    hookLine: "Rustic Italian braise that tastes like Sunday dinner, not red-sauce pasta night",
    description:
      "Chicken pieces brown in olive oil, then braise with tomatoes, bell peppers, mushrooms, and herbs until the sauce is thick and meat pulls from the bone. Serve in shallow bowls with polenta or crusty bread.",
    whyCrewsLikeIt:
      "Cacciatore delivers big Italian flavor without boiling a vat of spaghetti. It is a one-pot braise that holds warm, smells incredible when crews walk in, and feels like someone actually cooked—not opened a jar.",
    mealPrepNotes:
      "Use bone-in pieces for better braise flavor. Sauce improves overnight. Polenta can be made ahead and reheated with broth whisked in.",
    stationWorkflow: [
      "Brown chicken in batches—crowding the pot steams instead of sears.",
      "Deglaze with wine to lift fond before adding tomatoes.",
      "Finish with fresh basil at service, not during the braise.",
    ],
    prepMinutes: 30,
    cookMinutes: 55,
    difficulty: "medium",
    crewSizeDefault: 10,
    ingredients: [
      ing("chicken leg quarters", "6", { unit: "lb", notes: "cut into pieces", group: "Main" }),
      ing("olive oil", "0.25", { unit: "cup", group: "Braise" }),
      ing("yellow onion", "2", { unit: "whole", notes: "sliced", group: "Braise" }),
      ing("red bell pepper", "2", { unit: "whole", notes: "sliced", group: "Braise" }),
      ing("cremini mushrooms", "1", { unit: "lb", notes: "quartered", group: "Braise" }),
      ing("garlic cloves", "6", { unit: "cloves", notes: "minced", group: "Braise" }),
      ing("crushed tomatoes", "2", { unit: "cans", notes: "28 oz each", group: "Braise" }),
      ing("dry white wine", "1", { unit: "cup", group: "Braise" }),
      ing("dried oregano", "1", { unit: "tbsp", group: "Herbs" }),
      ing("fresh basil", "0.5", { unit: "cup", notes: "torn", group: "Finish" }),
      ing("polenta", "2", { unit: "cups", notes: "dry", group: "Base" }),
    ],
    steps: [
      step(1, "Brown the chicken", "Season chicken pieces. Sear in olive oil over medium-high heat until golden on all sides, about 12 minutes total. Set aside.", { minutes: 12 }),
      step(2, "Sweat vegetables", "In the same pot, cook onion, bell pepper, and mushrooms 8 minutes until softened. Add garlic and oregano, stir 1 minute.", { minutes: 10 }),
      step(3, "Deglaze and braise", "Pour in wine, scraping up browned bits. Add crushed tomatoes and nestle chicken into sauce. Cover and simmer 40 minutes until chicken reaches 165°F.", { minutes: 40 }),
      step(4, "Cook polenta", "Whisk polenta into simmering salted water or broth, stirring 15–20 minutes until thick and creamy. Hold warm with a lid.", { minutes: 20 }),
      step(5, "Serve family-style", "Taste sauce and adjust seasoning. Spoon polenta into bowls, top with chicken and sauce, and scatter fresh basil.", { minutes: 8 }),
    ],
    proTips: [
      "Capers and olives stirred in at the end add salty punch—optional but authentic.",
      "If sauce is thin, simmer uncovered last 10 minutes to concentrate.",
      "Red pepper flakes on the side keep heat optional for mixed crews.",
    ],
    tonightSpread: [
      "Cacciatore over creamy polenta with crusty Italian bread.",
      "Simple arugula salad with lemon vinaigrette to cut the rich sauce.",
    ],
    leftovers: [
      "Shred chicken into sauce for subs on Italian rolls.",
      "Use sauce as a base for baked eggs the next breakfast shift.",
    ],
    equipment: ["Dutch oven", "Large pot", "Instant-read thermometer", "Wooden spoon", "Whisk"],
    nutrition: { calories: 460, protein: 38, carbs: 36, fats: 18, fiber: 4 },
    spiceLevel: "mild",
    cleanupDifficulty: "medium",
  }),

  def({
    slug: "coq-au-vin-batch",
    title: "Coq au Vin Batch",
    subtitle: "Red wine-braised chicken with mushrooms and lardons for ten",
    category: "crew_feeders",
    protein: "chicken",
    cuisine: "french",
    mealFormat: "braise",
    explorePools: ["hall_expansion", "crew_feeders", "french", "chicken"],
    hookLine: "Classic French braise scaled for the hall—not a fussy date-night portion",
    description:
      "Chicken legs and thighs braise in red wine with bacon, mushrooms, pearl onions, and thyme until the sauce is glossy and meat falls from the bone. Serve with boiled potatoes and parsley.",
    whyCrewsLikeIt:
      "Coq au vin sounds fancy but it is just smart one-pot cooking—wine, bacon, and time do the work while you prep the rest of the meal. Crews respect a hall that can pull off real French comfort.",
    mealPrepNotes:
      "Use drinkable wine, not cooking wine. Bacon can be rendered ahead. Braise improves next day if you have leftover capacity.",
    stationWorkflow: [
      "Pat chicken dry before searing—wet skin never browns properly.",
      "Reduce wine before adding broth so sauce tastes deep, not thin.",
      "Skim excess fat from sauce before service for cleaner plates.",
    ],
    prepMinutes: 35,
    cookMinutes: 75,
    difficulty: "medium",
    crewSizeDefault: 8,
    ingredients: [
      ing("chicken legs and thighs", "6", { unit: "lb", notes: "bone-in", group: "Main" }),
      ing("thick-cut bacon", "1", { unit: "lb", notes: "cut into lardons", group: "Braise" }),
      ing("cremini mushrooms", "1.5", { unit: "lb", notes: "quartered", group: "Braise" }),
      ing("pearl onions", "1", { unit: "lb", notes: "peeled", group: "Braise" }),
      ing("garlic cloves", "4", { unit: "cloves", notes: "smashed", group: "Braise" }),
      ing("red wine", "3", { unit: "cups", notes: "dry", group: "Braise" }),
      ing("chicken broth", "2", { unit: "cups", group: "Braise" }),
      ing("tomato paste", "2", { unit: "tbsp", group: "Braise" }),
      ing("fresh thyme", "4", { unit: "sprigs", group: "Herbs" }),
      ing("Yukon Gold potatoes", "4", { unit: "lb", notes: "halved", group: "Side" }),
      ing("fresh parsley", "0.33", { unit: "cup", notes: "chopped", group: "Finish" }),
    ],
    steps: [
      step(1, "Render bacon and brown chicken", "Cook bacon until crisp, set aside. Sear seasoned chicken in bacon fat until golden on all sides, then set aside.", { minutes: 18 }),
      step(2, "Build the braise base", "Sauté mushrooms and pearl onions in the same pot 8 minutes. Add garlic and tomato paste, cook 2 minutes.", { minutes: 10 }),
      step(3, "Add wine and simmer", "Pour in wine, scrape fond, and reduce 5 minutes. Add broth, thyme, chicken, and bacon. Cover and braise at 325°F or simmer stovetop 60–70 minutes until tender.", { minutes: 65, tempF: 325 }),
      step(4, "Boil potatoes", "Simmer halved potatoes in salted water until fork-tender, 18–20 minutes. Drain and toss with butter, salt, and parsley.", { minutes: 20 }),
      step(5, "Finish and plate", "Skim excess fat from sauce. Portion chicken and sauce over potatoes, scatter bacon and parsley.", { minutes: 10 }),
    ],
    proTips: [
      "Beef bouillon cube adds depth if wine flavor feels too sharp.",
      "A beurre manié of butter and flour thickens sauce at the end if needed.",
      "Label wine bottles in the kitchen—braising wine disappears fast in a hall.",
    ],
    tonightSpread: [
      "Coq au vin with buttered potatoes and crusty baguette.",
      "Simple green salad with Dijon vinaigrette.",
    ],
    leftovers: [
      "Pull meat for wine-braised chicken sandwiches on baguette.",
      "Reduce sauce and serve over pappardelle—different format, same braise.",
    ],
    equipment: ["Dutch oven", "Large pot", "Instant-read thermometer", "Tongs", "Slotted spoon"],
    nutrition: { calories: 510, protein: 40, carbs: 32, fats: 22, fiber: 3 },
    spiceLevel: "mild",
    cleanupDifficulty: "medium",
  }),

  def({
    slug: "hungarian-goulash-crew",
    title: "Hungarian Goulash for the Crew",
    subtitle: "Paprika beef stew with caraway and potatoes for ten",
    category: "crew_feeders",
    protein: "beef",
    cuisine: "hungarian",
    mealFormat: "stew",
    explorePools: ["hall_expansion", "crew_feeders", "hungarian", "beef"],
    hookLine: "Real goulash—beef and paprika stew, not American chili with a different name",
    description:
      "Beef chuck simmers with onions, potatoes, and a heavy hand of sweet paprika until the broth turns rust-red and meat breaks down tender. Serve in deep bowls with sour cream and rye bread.",
    whyCrewsLikeIt:
      "Goulash is cold-weather hall fuel. It is hearty without being greasy, spices are warm not blow-your-head-off, and one pot feeds everyone including the probie who always takes seconds.",
    mealPrepNotes:
      "Cut beef uniform for even cooking. Stew tastes better the next day. Hold at 165°F in hotel pans with a thin broth layer so meat does not dry.",
    stationWorkflow: [
      "Brown beef in batches—do not skip this step or stew tastes flat.",
      "Add paprika off high heat so it blooms without scorching.",
      "Simmer gently—rapid boiling toughens chuck.",
    ],
    prepMinutes: 30,
    cookMinutes: 120,
    difficulty: "easy",
    crewSizeDefault: 10,
    ingredients: [
      ing("beef chuck roast", "4", { unit: "lb", notes: "cut into 1.5-inch cubes", group: "Main" }),
      ing("yellow onions", "3", { unit: "whole", notes: "diced", group: "Stew" }),
      ing("sweet paprika", "3", { unit: "tbsp", group: "Stew" }),
      ing("caraway seeds", "1", { unit: "tsp", group: "Stew" }),
      ing("garlic cloves", "5", { unit: "cloves", notes: "minced", group: "Stew" }),
      ing("tomato paste", "2", { unit: "tbsp", group: "Stew" }),
      ing("beef broth", "6", { unit: "cups", group: "Stew" }),
      ing("russet potatoes", "2", { unit: "lb", notes: "cubed", group: "Stew" }),
      ing("red bell pepper", "1", { unit: "whole", notes: "diced", group: "Stew" }),
      ing("sour cream", "1", { unit: "cup", notes: "for serving", group: "Finish" }),
      ing("rye bread", "1", { unit: "loaf", notes: "sliced", group: "Service" }),
    ],
    steps: [
      step(1, "Brown the beef", "Season chuck cubes and brown in batches in a Dutch oven over high heat until deeply colored. Set aside.", { minutes: 15 }),
      step(2, "Cook onions and spices", "Reduce heat, add onions, and cook 8 minutes. Stir in paprika, caraway, garlic, and tomato paste, cooking 2 minutes until fragrant.", { minutes: 10 }),
      step(3, "Simmer the stew", "Return beef, add broth and bell pepper. Cover and simmer 1.5 hours until beef starts to tenderize.", { minutes: 90 }),
      step(4, "Add potatoes", "Stir in potatoes and simmer uncovered 30–40 minutes until beef and potatoes are fork-tender and broth thickens slightly.", { minutes: 35 }),
      step(5, "Serve in bowls", "Taste and adjust salt. Ladle into bowls with sour cream dolloped on top and rye bread on the side.", { minutes: 5 }),
    ],
    proTips: [
      "A bay leaf in the simmer adds subtle depth—remove before service.",
      "Csipetke noodles are traditional if you want an extra Hungarian touch.",
      "Hot paprika on the side lets crews customize heat without changing the pot.",
    ],
    tonightSpread: [
      "Goulash bowls with sour cream, rye bread, and pickled vegetables.",
      "Simple cabbage salad with vinegar dressing.",
    ],
    leftovers: [
      "Thicken with a little flour and wrap in pastry for goulash hand pies.",
      "Serve over spaetzle if you have egg noodles gone.",
    ],
    equipment: ["Dutch oven", "Wooden spoon", "Ladle", "Cutting board", "Hotel pan"],
    nutrition: { calories: 480, protein: 38, carbs: 34, fats: 20, fiber: 4 },
    spiceLevel: "mild",
    cleanupDifficulty: "easy",
  }),

  def({
    slug: "tonkotsu-ramen-crew",
    title: "Tonkotsu Ramen for the Crew",
    subtitle: "Rich pork-and-chicken broth with noodles and toppings for ten",
    category: "crew_feeders",
    protein: "pork",
    cuisine: "japanese",
    mealFormat: "bowl",
    explorePools: ["hall_expansion", "crew_feeders", "japanese", "pork"],
    hookLine: "Hall ramen bar with real broth depth—not instant packets with an egg on top",
    description:
      "Pork bones and chicken backs simmer for hours into a creamy white broth, then serve over springy ramen noodles with chashu pork, soft eggs, nori, and scallions. Set up a topping bar so crews build their own bowls.",
    whyCrewsLikeIt:
      "Ramen night feels like a reward shift. The broth does the heavy lifting overnight, and bowl service moves fast when noodles and toppings are lined up like a firehouse assembly station.",
    mealPrepNotes:
      "Start broth the day before. Blanch bones first for cleaner flavor. Soft-boil eggs 6.5 minutes, ice bath, peel ahead. Cook noodles to order or in small batches so they do not turn mushy.",
    stationWorkflow: [
      "Skim broth regularly during the long simmer—clean broth equals clean flavor.",
      "Slice chashu thin while cold for uniform portions.",
      "Keep miso and chili oil on the side so heat levels stay crew-controlled.",
    ],
    prepMinutes: 45,
    cookMinutes: 240,
    difficulty: "hard",
    crewSizeDefault: 10,
    ingredients: [
      ing("pork neck bones", "4", { unit: "lb", group: "Broth" }),
      ing("chicken backs", "2", { unit: "lb", group: "Broth" }),
      ing("ginger", "3", { unit: "inches", notes: "smashed", group: "Broth" }),
      ing("garlic cloves", "8", { unit: "cloves", notes: "smashed", group: "Broth" }),
      ing("soy sauce", "0.5", { unit: "cup", group: "Tare" }),
      ing("mirin", "0.25", { unit: "cup", group: "Tare" }),
      ing("pork belly", "2", { unit: "lb", notes: "for chashu", group: "Topping" }),
      ing("ramen noodles", "2", { unit: "lb", notes: "fresh or dried", group: "Noodles" }),
      ing("soft-boiled eggs", "10", { unit: "eggs", notes: "peeled and halved", group: "Topping" }),
      ing("nori sheets", "10", { unit: "sheets", notes: "cut in half", group: "Topping" }),
      ing("green onions", "1", { unit: "bunch", notes: "sliced", group: "Topping" }),
      ing("corn kernels", "2", { unit: "cups", notes: "steamed", group: "Topping" }),
    ],
    steps: [
      step(1, "Blanch and start broth", "Blanch pork and chicken bones 5 minutes, rinse, then cover with fresh water in a large stockpot. Add ginger and garlic. Simmer vigorously 4 hours, skimming often.", { minutes: 240 }),
      step(2, "Braise chashu pork", "Roll pork belly, tie, and braise in soy, mirin, and water 2 hours until tender. Cool and slice thin.", { minutes: 120 }),
      step(3, "Season the broth", "Strain broth if you want smoother body. Whisk soy and mirin tare into broth to taste—salty, rich, and milky white.", { minutes: 15 }),
      step(4, "Prep the bar", "Arrange chashu, eggs, nori, scallions, and corn in labeled pans. Heat broth to a rolling simmer in a large pot or tilt skillet.", { minutes: 20 }),
      step(5, "Build bowls", "Cook noodles per package, drain, and divide into bowls. Ladle hot broth over noodles, top with chashu and garnishes, and serve immediately.", { minutes: 10 }),
    ],
    proTips: [
      "A tablespoon of chicken fat whisked in at service adds extra gloss.",
      "Do not add noodles to the hold pot—they swell and ruin texture.",
      "Sesame seeds and bamboo shoots upgrade the bar without much extra work.",
    ],
    tonightSpread: [
      "Tonkotsu ramen bowls with full topping bar and chili oil.",
      "Quick cucumber pickles for crunch between rich sips.",
    ],
    leftovers: [
      "Broth freezes well for a second ramen night later in the month.",
      "Chashu slices reheat gently in broth for rice topping—not a bowl format, just smart reuse.",
    ],
    equipment: ["Large stockpot", "Second pot for chashu", "Noodle baskets", "Ladle", "Sheet pans"],
    nutrition: { calories: 580, protein: 32, carbs: 52, fats: 28, fiber: 2 },
    spiceLevel: "mild",
    cleanupDifficulty: "heavy",
  }),

  def({
    slug: "miso-ramen-bar",
    title: "Miso Ramen Bar",
    subtitle: "Chicken broth miso ramen with tofu and vegetables for ten",
    category: "crew_feeders",
    protein: "chicken",
    cuisine: "japanese",
    mealFormat: "bowl",
    explorePools: ["hall_expansion", "crew_feeders", "japanese", "chicken"],
    hookLine: "Faster ramen night with bold miso flavor and a build-your-own bar",
    description:
      "Chicken broth simmers with aromatics, then finishes with red and white miso for a savory bowl base. Serve with ramen noodles, shredded chicken, seared tofu, bean sprouts, corn, and soft eggs.",
    whyCrewsLikeIt:
      "Miso ramen comes together faster than tonkotsu but still feels special. Tofu and chicken together keep vegetarians and meat eaters happy without cooking two separate meals.",
    mealPrepNotes:
      "Never boil miso—whisk in off heat to preserve flavor. Prep all toppings before noodles go in. Chili crisp at the line is mandatory for half the hall.",
    stationWorkflow: [
      "Press tofu 20 minutes for better sear—wet tofu steams and sticks.",
      "Keep broth and noodles separate until the line opens.",
      "Label gluten-free options if using wheat noodles—rice noodles swap easy.",
    ],
    prepMinutes: 35,
    cookMinutes: 90,
    difficulty: "medium",
    crewSizeDefault: 9,
    ingredients: [
      ing("chicken thighs", "3", { unit: "lb", notes: "boneless", group: "Protein" }),
      ing("chicken broth", "8", { unit: "cups", group: "Broth" }),
      ing("white miso paste", "0.33", { unit: "cup", group: "Broth" }),
      ing("red miso paste", "2", { unit: "tbsp", group: "Broth" }),
      ing("ginger", "2", { unit: "inches", notes: "sliced", group: "Broth" }),
      ing("garlic cloves", "4", { unit: "cloves", notes: "smashed", group: "Broth" }),
      ing("firm tofu", "2", { unit: "blocks", notes: "cubed and seared", group: "Topping" }),
      ing("ramen noodles", "2", { unit: "lb", group: "Noodles" }),
      ing("bean sprouts", "3", { unit: "cups", group: "Topping" }),
      ing("corn kernels", "2", { unit: "cups", group: "Topping" }),
      ing("soft-boiled eggs", "8", { unit: "eggs", notes: "halved", group: "Topping" }),
      ing("green onions", "1", { unit: "bunch", notes: "sliced", group: "Topping" }),
    ],
    steps: [
      step(1, "Simmer chicken broth", "Poach chicken thighs in broth with ginger and garlic 25 minutes until cooked through. Remove chicken, shred, and reserve.", { minutes: 25 }),
      step(2, "Finish miso base", "Keep broth at a gentle simmer. Remove from heat, whisk white and red miso until dissolved, then return to low heat without boiling.", { minutes: 10 }),
      step(3, "Sear tofu", "Pat tofu dry, sear in oil until golden on multiple sides. Hold warm with shredded chicken.", { minutes: 12 }),
      step(4, "Set the bar", "Line up sprouts, corn, eggs, scallions, tofu, and chicken in hotel pans. Keep broth hot in a large pot.", { minutes: 15 }),
      step(5, "Assemble bowls", "Cook noodles, divide into bowls, ladle miso broth over, and let crews pick toppings.", { minutes: 10 }),
    ],
    proTips: [
      "A splash of sesame oil at the bowl station adds aroma without changing the batch.",
      "Spinach wilted in broth for 30 seconds adds green without extra pans.",
      "Keep extra miso paste slurry nearby if broth needs salt at service.",
    ],
    tonightSpread: [
      "Miso ramen bar with tofu, chicken, eggs, and chili crisp.",
      "Edamame with flaky salt for a simple side.",
    ],
    leftovers: [
      "Broth reheats gently—do not boil or miso flavor dulls.",
      "Shredded chicken becomes lettuce wraps with miso dressing.",
    ],
    equipment: ["Large pot", "Skillet", "Noodle baskets", "Hotel pans", "Whisk"],
    nutrition: { calories: 460, protein: 34, carbs: 48, fats: 14, fiber: 3 },
    spiceLevel: "mild",
    cleanupDifficulty: "medium",
  }),

  def({
    slug: "malaysian-laksa-soup",
    title: "Malaysian Laksa Soup",
    subtitle: "Coconut curry noodle soup with shrimp and chicken for ten",
    category: "crew_feeders",
    protein: "shrimp",
    cuisine: "malaysian",
    mealFormat: "soup",
    explorePools: ["hall_expansion", "crew_feeders", "malaysian", "shrimp"],
    hookLine: "Southeast Asian coconut soup—fragrant, spicy, and nothing like a generic curry bowl",
    description:
      "Aromatics and laksa paste bloom in coconut milk and broth, then simmer with chicken, shrimp, and rice noodles. Serve with lime, cilantro, bean sprouts, and sambal for a bright, spicy hall soup night.",
    whyCrewsLikeIt:
      "Laksa wakes up tired palates. Coconut broth feels indulgent, shrimp and chicken double the protein, and the soup format means one ladle per bowl—fast service when everyone is starving post-call.",
    mealPrepNotes:
      "Bloom laksa paste in oil before any liquids—raw paste tastes harsh. Shrimp go in at the very end; they need only 2–3 minutes. Cook rice noodles ahead, rinse cold, and hold separately so they do not swell in the broth pot.",
    stationWorkflow: [
      "Bloom paste in oil before liquids—raw spice taste ruins the pot.",
      "Taste broth for balance: salty, coconut-sweet, and lime-bright.",
      "Keep sambal separate—hall spice tolerance varies wildly.",
    ],
    prepMinutes: 35,
    cookMinutes: 40,
    difficulty: "medium",
    crewSizeDefault: 10,
    ingredients: [
      ing("vegetable oil", "3", { unit: "tbsp", group: "Base" }),
      ing("laksa paste", "0.5", { unit: "cup", notes: "store-bought or homemade", group: "Base" }),
      ing("coconut milk", "3", { unit: "cans", notes: "13.5 oz each", group: "Base" }),
      ing("chicken broth", "4", { unit: "cups", group: "Base" }),
      ing("chicken breast", "2", { unit: "lb", notes: "sliced thin", group: "Protein" }),
      ing("large shrimp", "2", { unit: "lb", notes: "peeled and deveined", group: "Protein" }),
      ing("rice noodles", "1.5", { unit: "lb", notes: "thick", group: "Noodles" }),
      ing("fish sauce", "2", { unit: "tbsp", group: "Seasoning" }),
      ing("lime juice", "0.25", { unit: "cup", group: "Finish" }),
      ing("bean sprouts", "3", { unit: "cups", group: "Garnish" }),
      ing("fresh cilantro", "1", { unit: "cup", notes: "chopped", group: "Garnish" }),
      ing("sambal oelek", "0.25", { unit: "cup", notes: "for serving", group: "Garnish" }),
    ],
    steps: [
      step(
        1,
        "Bloom laksa paste in oil",
        "Heat 3 tbsp vegetable oil in a large pot over medium heat until it shimmers. Add 1/2 cup laksa paste and fry 2–3 minutes, stirring constantly, until deeply fragrant and the oil turns orange-red with a thin sheen on top.",
        { minutes: 5 },
      ),
      step(
        2,
        "Simmer coconut milk and broth",
        "Pour in 3 cans coconut milk and 4 cups chicken broth. Bring to a gentle simmer over medium heat—small bubbles at the edges, not a rolling boil. Simmer uncovered 15 minutes so the paste flavor melds into the broth.",
        { minutes: 15 },
      ),
      step(
        3,
        "Season with fish sauce",
        "Stir in 2 tbsp fish sauce and taste: broth should be savory, lightly sweet from coconut, and lightly spicy from the paste. Add another small splash of fish sauce if the pot tastes flat.",
        { minutes: 5 },
      ),
      step(
        4,
        "Poach chicken breast",
        "Slide in 2 lb thin-sliced chicken breast. Return to a gentle simmer and cook 8–10 minutes until chicken is opaque white throughout and reads 165°F in the thickest piece. Transfer chicken to a hotel pan, shred or slice, and cover loosely.",
        { minutes: 10, tempF: 165 },
      ),
      step(
        5,
        "Cook and cool rice noodles",
        "Soak or boil 1.5 lb thick rice noodles per package until tender but still springy. Drain, rinse under cold water to stop cooking, toss with a few drops of oil, and portion into bowls or a labeled hotel pan for the line.",
        { minutes: 10 },
      ),
      step(
        6,
        "Poach shrimp in laksa broth",
        "Raise the laksa broth to a steady simmer. Add 2 lb peeled large shrimp and cook 2–3 minutes until shells turn pink and flesh is opaque and curled—do not let shrimp boil hard or they turn rubbery.",
        { minutes: 5 },
      ),
      step(
        7,
        "Brighten with lime and hold",
        "Remove the pot from heat. Stir in 1/4 cup lime juice and taste once more—the broth should finish bright and slightly tangy. For holding, keep broth in the pot or a hotel pan at 170°F max; do not boil while holding or coconut fat may split.",
        { minutes: 3, tempF: 170 },
      ),
      step(
        8,
        "Ladle bowls on the line",
        "Place a portion of rice noodles in each bowl. Ladle hot laksa broth over noodles, then top with chicken, shrimp, bean sprouts, and chopped cilantro. Pass sambal oelek on the side so each crew member controls the heat.",
        { minutes: 8 },
      ),
    ],
    proTips: [
      "Hard-boiled egg halves are traditional and add cheap protein.",
      "Fried shallots from a jar upgrade texture instantly.",
      "If broth splits on hold, whisk in a spoon of warm water—not more coconut milk.",
    ],
    tonightSpread: [
      "Laksa bowls with lime wedges, cilantro, sprouts, and sambal.",
      "Cucumber salad with chili and peanuts for crunch.",
    ],
    leftovers: [
      "Reheat broth and chicken gently to 165°F—never boil or coconut fat splits. Poach fresh shrimp in the reheated broth for 2–3 minutes at service.",
      "Extra laksa paste freezes in ice cube trays for quick future batches.",
    ],
    equipment: ["Large pot", "Ladle", "Tongs", "Bowls", "Hotel pans"],
    nutrition: { calories: 490, protein: 36, carbs: 46, fats: 18, fiber: 2 },
    spiceLevel: "medium",
    cleanupDifficulty: "medium",
  }),

  def({
    slug: "bun-bo-hue-noodle-soup",
    title: "Bun Bo Hue Noodle Soup",
    subtitle: "Spicy lemongrass beef and pork noodle soup for ten",
    category: "crew_feeders",
    protein: "beef",
    cuisine: "vietnamese",
    mealFormat: "bowl",
    explorePools: ["hall_expansion", "crew_feeders", "vietnamese", "beef"],
    hookLine: "Central Vietnam's spicy noodle soup—bold broth, not pho's quiet cousin",
    description:
      "Beef shank and pork hock simmer with lemongrass, chili, and shrimp paste into a fiery aromatic broth. Serve over round rice noodles with thin beef, blood cake if available, herbs, and lime.",
    whyCrewsLikeIt:
      "Bun bo hue brings real heat and depth—crews who think pho is too mild will respect this bowl. It is soup with attitude, perfect for cold nights when the hall needs something that punches back.",
    mealPrepNotes:
      "Broth takes time but mostly unattended. Skim diligently. Shrimp paste smells strong but transforms the broth—do not skip. Herbs should be washed and piled high before service.",
    stationWorkflow: [
      "Char onion and ginger before adding to broth for smoky depth.",
      "Slice beef paper-thin and drop raw into hot broth at the bowl.",
      "Keep chili oil and lime wedges on the line for final customization.",
    ],
    prepMinutes: 40,
    cookMinutes: 180,
    difficulty: "hard",
    crewSizeDefault: 8,
    ingredients: [
      ing("beef shank", "3", { unit: "lb", group: "Broth" }),
      ing("pork hock", "2", { unit: "lb", group: "Broth" }),
      ing("lemongrass stalks", "6", { unit: "stalks", notes: "smashed", group: "Broth" }),
      ing("shrimp paste", "1", { unit: "tbsp", group: "Broth" }),
      ing("chili oil", "3", { unit: "tbsp", group: "Broth" }),
      ing("beef eye round", "1.5", { unit: "lb", notes: "sliced paper-thin", group: "Protein" }),
      ing("round rice noodles", "2", { unit: "lb", group: "Noodles" }),
      ing("yellow onion", "2", { unit: "whole", notes: "halved and charred", group: "Broth" }),
      ing("fish sauce", "3", { unit: "tbsp", group: "Seasoning" }),
      ing("Thai basil", "2", { unit: "cups", notes: "leaves", group: "Herbs" }),
      ing("mint", "1", { unit: "cup", notes: "leaves", group: "Herbs" }),
      ing("lime", "4", { unit: "whole", notes: "cut into wedges", group: "Finish" }),
    ],
    steps: [
      step(1, "Start the broth", "Cover beef shank and pork hock with water. Add lemongrass, charred onion, and shrimp paste. Simmer 2.5–3 hours, skimming often.", { minutes: 165 }),
      step(2, "Season boldly", "Remove solids, strain broth if desired. Season with fish sauce and chili oil until broth is spicy, salty, and aromatic.", { minutes: 15 }),
      step(3, "Shred braised meat", "Pull tender meat from shank and hock, slice or shred, and hold warm.", { minutes: 15 }),
      step(4, "Prep noodles and herbs", "Cook rice noodles, rinse, and divide into bowls. Plate basil, mint, and limes at the line.", { minutes: 15 }),
      step(5, "Build bowls", "Top noodles with shredded braised meats and raw beef slices. Ladle boiling broth over to cook raw beef. Serve with herbs and lime.", { minutes: 10 }),
    ],
    proTips: [
      "Freeze beef eye round 30 minutes for easier thin slicing.",
      "Annatto oil adds classic red color if you have it.",
      "Warn the hall—this is spicier than most station soups.",
    ],
    tonightSpread: [
      "Bun bo hue with herb plate, lime, and extra chili oil.",
      "Vietnamese pickles for acid between spicy spoonfuls.",
    ],
    leftovers: [
      "Broth improves next day—skim fat cap before reheating.",
      "Shredded meats become banh mi filling with pickles and mayo.",
    ],
    equipment: ["Large stockpot", "Strainer", "Sharp knife", "Bowls", "Ladle"],
    nutrition: { calories: 520, protein: 40, carbs: 50, fats: 16, fiber: 2 },
    spiceLevel: "hot",
    cleanupDifficulty: "heavy",
  }),

  def({
    slug: "wonton-noodle-soup-crew",
    title: "Wonton Noodle Soup for the Crew",
    subtitle: "Pork wontons in clear broth with egg noodles for ten",
    category: "crew_feeders",
    protein: "pork",
    cuisine: "chinese",
    mealFormat: "bowl",
    explorePools: ["hall_expansion", "crew_feeders", "chinese", "pork"],
    hookLine: "Classic Cantonese wonton soup scaled for a hungry hall lineup",
    description:
      "Pork and shrimp wontons fold by the dozen, poach in rich chicken broth, and serve over springy egg noodles with bok choy and scallions. Clean, comforting, and perfect when crews want soup that feels homemade.",
    whyCrewsLikeIt:
      "Wonton soup is familiar without being boring. Folding wontons is a good team task for off-duty crew, and the clear broth lightens up a menu heavy on grills and braises.",
    mealPrepNotes:
      "Wontons freeze well on sheet pans—bag and hold for future nights. Broth can simmer while wontons are folded. Cook noodles fresh per batch.",
    stationWorkflow: [
      "Keep wonton filling cold—warm filling tears wrappers.",
      "Do not overcrowd the pot when poaching or wrappers break.",
      "Blanch bok choy separately so broth stays clear.",
    ],
    prepMinutes: 50,
    cookMinutes: 40,
    difficulty: "medium",
    crewSizeDefault: 10,
    ingredients: [
      ing("ground pork", "1.5", { unit: "lb", group: "Wonton" }),
      ing("shrimp", "0.5", { unit: "lb", notes: "finely chopped", group: "Wonton" }),
      ing("wonton wrappers", "60", { unit: "wrappers", group: "Wonton" }),
      ing("green onions", "4", { unit: "whole", notes: "minced", group: "Wonton" }),
      ing("sesame oil", "1", { unit: "tbsp", group: "Wonton" }),
      ing("soy sauce", "2", { unit: "tbsp", group: "Wonton" }),
      ing("chicken broth", "8", { unit: "cups", group: "Broth" }),
      ing("ginger", "2", { unit: "inches", notes: "sliced", group: "Broth" }),
      ing("egg noodles", "2", { unit: "lb", notes: "fresh if possible", group: "Noodles" }),
      ing("baby bok choy", "2", { unit: "lb", notes: "halved", group: "Vegetable" }),
      ing("white pepper", "1", { unit: "tsp", group: "Seasoning" }),
    ],
    steps: [
      step(1, "Make wonton filling", "Mix pork, shrimp, green onions, sesame oil, soy sauce, and white pepper until sticky.", { minutes: 15 }),
      step(2, "Fold wontons", "Place a teaspoon of filling in each wrapper, wet edges, fold into triangles or purses, and press air out. Cover with damp towels.", { minutes: 35 }),
      step(3, "Simmer broth", "Simmer chicken broth with ginger 20 minutes. Season with soy and white pepper to taste.", { minutes: 20 }),
      step(4, "Poach wontons and bok choy", "Boil wontons in salted water 4–5 minutes until they float and filling hits 165°F. Blanch bok choy 2 minutes in the same water.", { minutes: 10 }),
      step(5, "Assemble bowls", "Cook egg noodles, drain, and divide into bowls. Add bok choy, wontons, and ladle hot broth over. Finish with scallions.", { minutes: 10 }),
    ],
    proTips: [
      "A little cornstarch in filling helps bind if mixture feels loose.",
      "Chili crisp and black vinegar at the table turn good soup into great soup.",
      "Extra wontons freeze—future shift will thank you.",
    ],
    tonightSpread: [
      "Wonton noodle soup with chili crisp and black vinegar.",
      "Cucumber salad with sesame dressing.",
    ],
    leftovers: [
      "Frozen wontons go straight into boiling broth from frozen.",
      "Broth becomes egg drop soup base with whisked eggs.",
    ],
    equipment: ["Large pot", "Mixing bowl", "Sheet pans", "Spider strainer", "Ladle"],
    nutrition: { calories: 440, protein: 28, carbs: 48, fats: 14, fiber: 2 },
    spiceLevel: "mild",
    cleanupDifficulty: "medium",
  }),

  def({
    slug: "peri-peri-chicken-platter",
    title: "Peri Peri Chicken Platter",
    subtitle: "Portuguese-African chili chicken with charred lemon for ten",
    category: "crew_feeders",
    protein: "chicken",
    cuisine: "portuguese",
    mealFormat: "platter",
    explorePools: ["hall_expansion", "crew_feeders", "portuguese", "chicken"],
    hookLine: "Fiery peri peri platters—grill heat without another fajita night",
    description:
      "Chicken quarters marinate in peri peri chili sauce with lemon and garlic, then grill until charred and juicy. Serve on platters with grilled peppers, charred lemons, and extra sauce for dipping.",
    whyCrewsLikeIt:
      "Peri peri chicken brings real heat and tang—crews who live on hot sauce will line up twice. Quarters are cheap, grill fast, and look impressive piled on sheet pans.",
    mealPrepNotes:
      "Marinate up to 24 hours. Reserve half the sauce for serving—never baste with used marinade from raw chicken. Spatchcock quarters if you need faster grill time.",
    stationWorkflow: [
      "Oil grill grates well—sugar in chili sauce sticks fast.",
      "Move chicken to cooler zones if skin chars before 165°F internal.",
      "Char lemon halves cut-side down for squeezing at the table.",
    ],
    prepMinutes: 25,
    cookMinutes: 40,
    difficulty: "medium",
    crewSizeDefault: 10,
    ingredients: [
      ing("chicken leg quarters", "6", { unit: "lb", notes: "about 12 pieces", group: "Main" }),
      ing("red chilies", "6", { unit: "whole", notes: "seeded", group: "Sauce" }),
      ing("garlic cloves", "8", { unit: "cloves", group: "Sauce" }),
      ing("lemon juice", "0.33", { unit: "cup", group: "Sauce" }),
      ing("olive oil", "0.5", { unit: "cup", group: "Sauce" }),
      ing("smoked paprika", "1", { unit: "tbsp", group: "Sauce" }),
      ing("oregano", "1", { unit: "tbsp", notes: "dried", group: "Sauce" }),
      ing("red bell peppers", "4", { unit: "whole", notes: "quartered", group: "Grill" }),
      ing("yellow onion", "2", { unit: "whole", notes: "quartered", group: "Grill" }),
      ing("lemon", "4", { unit: "whole", notes: "halved", group: "Finish" }),
      ing("fresh cilantro", "0.25", { unit: "cup", notes: "chopped", group: "Finish" }),
    ],
    steps: [
      step(1, "Blend peri peri sauce", "Blend chilies, garlic, lemon juice, olive oil, paprika, oregano, and salt until smooth.", { minutes: 10 }),
      step(2, "Marinate chicken", "Coat quarters in half the sauce. Marinate at least 2 hours or overnight refrigerated.", { minutes: 10 }),
      step(3, "Preheat grill", "Heat grill to medium-high, about 400°F. Oil grates thoroughly.", { minutes: 10, tempF: 400 }),
      step(4, "Grill chicken and vegetables", "Grill chicken skin-side down 8 minutes, flip, and cook until 165°F internal, about 20 minutes total. Grill peppers, onions, and lemon halves alongside.", { minutes: 28, tempF: 400 }),
      step(5, "Platter and serve", "Rest chicken 5 minutes, then pile on platters with grilled vegetables. Drizzle reserved sauce and scatter cilantro.", { minutes: 10 }),
    ],
    proTips: [
      "Bird's eye chilies kick heat up—jalapeños keep it hall-friendly.",
      "Peri peri mayo for dipping is an easy upgrade.",
      "Portuguese rolls soak up sauce better than standard buns.",
    ],
    tonightSpread: [
      "Peri peri chicken with grilled peppers, onions, and charred lemon.",
      "Simple rice or roasted potatoes for crew who want a plate, not just chicken.",
    ],
    leftovers: [
      "Pull meat for peri peri wraps with slaw—not a burrito bowl, a straight wrap.",
      "Chop into grain salad with cucumber and feta.",
    ],
    equipment: ["Grill", "Blender", "Instant-read thermometer", "Sheet pans", "Tongs"],
    nutrition: { calories: 430, protein: 38, carbs: 12, fats: 26, fiber: 2 },
    spiceLevel: "hot",
    cleanupDifficulty: "medium",
  }),

  def({
    slug: "korean-bulgogi-grill-night",
    title: "Korean Bulgogi Grill Night",
    subtitle: "Marinated beef grilled with scallions and lettuce wraps for ten",
    category: "crew_feeders",
    protein: "beef",
    cuisine: "korean",
    mealFormat: "grill",
    explorePools: ["hall_expansion", "crew_feeders", "korean", "beef"],
    hookLine: "Bulgogi on the grill with lettuce wraps—not another rice bowl lineup",
    description:
      "Thin-sliced ribeye marinates in soy, pear, garlic, and sesame, then grills hot over charcoal or gas until caramelized at the edges. Serve with lettuce cups, scallions, kimchi, and ssamjang for wrap-your-own platters.",
    whyCrewsLikeIt:
      "Grill-night bulgogi feels interactive and special without the rice-bowl repetition. Crews build lettuce wraps, eat with their hands, and the sweet-salty beef disappears faster than you can restock the platter.",
    mealPrepNotes:
      "Freeze beef 30 minutes for easier slicing. Marinate up to 8 hours. Grill in batches over highest heat—crowding steams instead of chars.",
    stationWorkflow: [
      "Slice beef as thin as possible across the grain.",
      "Pat marinade off slightly before grilling to reduce flare-ups.",
      "Keep lettuce leaves whole and cold in a lined pan.",
    ],
    prepMinutes: 35,
    cookMinutes: 20,
    difficulty: "medium",
    crewSizeDefault: 10,
    ingredients: [
      ing("ribeye steak", "4", { unit: "lb", notes: "partially frozen, sliced thin", group: "Main" }),
      ing("soy sauce", "0.5", { unit: "cup", group: "Marinade" }),
      ing("Asian pear or apple", "1", { unit: "whole", notes: "grated", group: "Marinade" }),
      ing("brown sugar", "3", { unit: "tbsp", group: "Marinade" }),
      ing("garlic cloves", "6", { unit: "cloves", notes: "minced", group: "Marinade" }),
      ing("ginger", "1", { unit: "tbsp", notes: "grated", group: "Marinade" }),
      ing("sesame oil", "2", { unit: "tbsp", group: "Marinade" }),
      ing("green onions", "2", { unit: "bunches", notes: "cut into long lengths", group: "Grill" }),
      ing("butter lettuce", "2", { unit: "heads", notes: "leaves separated", group: "Service" }),
      ing("kimchi", "2", { unit: "cups", group: "Service" }),
      ing("ssamjang", "0.5", { unit: "cup", group: "Service" }),
    ],
    steps: [
      step(1, "Slice and marinate beef", "Slice ribeye paper-thin. Mix soy, grated pear, sugar, garlic, ginger, and sesame oil. Toss beef and marinate at least 1 hour.", { minutes: 20 }),
      step(2, "Prep wrap station", "Separate lettuce leaves, grill scallion lengths lightly, and portion kimchi and ssamjang into bowls.", { minutes: 15 }),
      step(3, "Heat the grill", "Preheat grill to high, about 450°F. Vent the kitchen—this will smoke.", { minutes: 10, tempF: 450 }),
      step(4, "Grill bulgogi in batches", "Grill beef in single layers 1–2 minutes per side until caramelized. Repeat until all beef is cooked.", { minutes: 12, tempF: 450 }),
      step(5, "Serve platters", "Pile hot beef on platters with grilled scallions. Let crews build lettuce wraps with kimchi and ssamjang.", { minutes: 5 }),
    ],
    proTips: [
      "A cast iron griddle on the grill gives better char than grates alone.",
      "Offer steamed rice on the side for crew who skip lettuce wraps.",
      "Toasted sesame seeds over finished beef add crunch and look pro.",
    ],
    tonightSpread: [
      "Bulgogi platters with lettuce cups, kimchi, and ssamjang.",
      "Quick cucumber salad with rice vinegar.",
    ],
    leftovers: [
      "Beef becomes bulgogi quesadillas—different format, still works.",
      "Chop into fried rice with kimchi for lunch shift.",
    ],
    equipment: ["Grill or cast iron griddle", "Tongs", "Mixing bowls", "Serving platters", "Small bowls"],
    nutrition: { calories: 460, protein: 36, carbs: 18, fats: 28, fiber: 2 },
    spiceLevel: "mild",
    cleanupDifficulty: "medium",
  }),

  def({
    slug: "lamb-kofta-skewer-platter",
    title: "Lamb Kofta Skewer Platter",
    subtitle: "Spiced lamb skewers with yogurt sauce and flatbread for ten",
    category: "crew_feeders",
    protein: "lamb",
    cuisine: "middle_eastern",
    mealFormat: "skewer",
    explorePools: ["hall_expansion", "crew_feeders", "middle_eastern", "lamb"],
    hookLine: "Middle Eastern kofta skewers—grill smoke, warm spices, zero platter boredom",
    description:
      "Ground lamb mixes with onion, parsley, and warm spices, then grills on skewers until charred outside and juicy inside. Serve with tzatziki-style yogurt sauce, grilled flatbread, tomatoes, and pickled onions.",
    whyCrewsLikeIt:
      "Kofta skewers are hand-held, flavorful, and feel like a cookout with purpose. Lamb brings variety to halls stuck on chicken-and-beef rotation, and skewers portion cleanly for ten hungry firefighters.",
    mealPrepNotes:
      "Chill formed kofta 30 minutes before grilling so they hold shape. Soak wooden skewers if using. Yogurt sauce improves after an hour in the fridge.",
    stationWorkflow: [
      "Do not overmix lamb or kofta turns dense—combine until just uniform.",
      "Grill over medium-high heat—lamb fat flares on max heat.",
      "Warm flatbread wrapped in foil on the grill during last 5 minutes.",
    ],
    prepMinutes: 30,
    cookMinutes: 15,
    difficulty: "medium",
    crewSizeDefault: 9,
    ingredients: [
      ing("ground lamb", "4", { unit: "lb", group: "Kofta" }),
      ing("yellow onion", "1", { unit: "whole", notes: "grated and drained", group: "Kofta" }),
      ing("fresh parsley", "0.5", { unit: "cup", notes: "finely chopped", group: "Kofta" }),
      ing("ground cumin", "2", { unit: "tsp", group: "Spice" }),
      ing("ground coriander", "2", { unit: "tsp", group: "Spice" }),
      ing("smoked paprika", "1", { unit: "tsp", group: "Spice" }),
      ing("garlic cloves", "4", { unit: "cloves", notes: "minced", group: "Kofta" }),
      ing("Greek yogurt", "2", { unit: "cups", group: "Sauce" }),
      ing("lemon juice", "3", { unit: "tbsp", group: "Sauce" }),
      ing("flatbread", "12", { unit: "pieces", notes: "pita or naan", group: "Service" }),
      ing("cherry tomatoes", "2", { unit: "cups", notes: "halved", group: "Service" }),
      ing("red onion", "1", { unit: "whole", notes: "quick-pickled", group: "Service" }),
    ],
    steps: [
      step(1, "Mix kofta", "Combine lamb, drained onion, parsley, garlic, cumin, coriander, paprika, salt, and pepper. Mix gently and chill 30 minutes.", { minutes: 15 }),
      step(2, "Form skewers", "Shape meat into logs around skewers about 6 inches long. Press firmly so meat adheres.", { minutes: 15 }),
      step(3, "Make yogurt sauce", "Whisk yogurt, lemon juice, minced garlic, salt, and chopped cucumber if available.", { minutes: 5 }),
      step(4, "Grill kofta", "Grill skewers over medium-high heat 10–12 minutes, turning often, until charred and 165°F internal.", { minutes: 12, tempF: 400 }),
      step(5, "Platter and serve", "Slide kofta off skewers onto platters or serve on skewers with warm flatbread, tomatoes, pickled onion, and yogurt sauce.", { minutes: 5 }),
    ],
    proTips: [
      "A little soaked breadcrumbs in the mix helps bind if lamb is very lean.",
      "Sumac sprinkled at service adds classic tang.",
      "Offer harissa for crews who want more heat.",
    ],
    tonightSpread: [
      "Lamb kofta with flatbread, yogurt sauce, tomatoes, and pickled onions.",
      "Simple herb salad with lemon dressing.",
    ],
    leftovers: [
      "Crumble kofta into hummus bowls with cucumbers.",
      "Reheat in pita with tzatziki for quick lunch.",
    ],
    equipment: ["Grill", "Metal or soaked wood skewers", "Mixing bowl", "Instant-read thermometer", "Platters"],
    nutrition: { calories: 520, protein: 34, carbs: 28, fats: 32, fiber: 2 },
    spiceLevel: "medium",
    cleanupDifficulty: "medium",
  }),

  def({
    slug: "moroccan-chicken-kebab-platter",
    title: "Moroccan Chicken Kebab Platter",
    subtitle: "Chermoula-marinated chicken skewers with couscous for ten",
    category: "crew_feeders",
    protein: "chicken",
    cuisine: "moroccan",
    mealFormat: "skewer",
    explorePools: ["hall_expansion", "crew_feeders", "moroccan", "chicken"],
    hookLine: "North African spice on the grill—bright herbs, cumin, and char",
    description:
      "Chicken thighs marinate in chermoula—cilantro, cumin, lemon, and garlic—then grill on skewers with onions and peppers. Serve over fluffy couscous with olives, preserved lemon, and harissa.",
    whyCrewsLikeIt:
      "Moroccan kebabs bring sun-bright flavor to northern halls. Thigh meat stays juicy on skewers, couscous cooks in minutes, and the platter looks like someone actually planned dinner—not raided the freezer.",
    mealPrepNotes:
      "Cut chicken uniform for even grilling. Chermoula can be made ahead. Fluff couscous with a fork, not a spoon, so grains stay separate.",
    stationWorkflow: [
      "Alternate chicken and vegetables on skewers for even cooking.",
      "Do not pack skewers too tight—heat needs to circulate.",
      "Keep harissa off to the side for spice-sensitive crew.",
    ],
    prepMinutes: 30,
    cookMinutes: 20,
    difficulty: "medium",
    crewSizeDefault: 10,
    ingredients: [
      ing("boneless chicken thighs", "4", { unit: "lb", notes: "cut into chunks", group: "Main" }),
      ing("fresh cilantro", "1", { unit: "cup", notes: "packed", group: "Chermoula" }),
      ing("fresh parsley", "0.5", { unit: "cup", group: "Chermoula" }),
      ing("garlic cloves", "6", { unit: "cloves", group: "Chermoula" }),
      ing("ground cumin", "2", { unit: "tsp", group: "Chermoula" }),
      ing("smoked paprika", "1", { unit: "tsp", group: "Chermoula" }),
      ing("lemon juice", "0.25", { unit: "cup", group: "Chermoula" }),
      ing("olive oil", "0.33", { unit: "cup", group: "Chermoula" }),
      ing("couscous", "3", { unit: "cups", notes: "dry", group: "Base" }),
      ing("green olives", "1", { unit: "cup", notes: "pitted", group: "Garnish" }),
      ing("preserved lemon", "2", { unit: "tbsp", notes: "minced", group: "Garnish" }),
      ing("harissa", "0.25", { unit: "cup", notes: "for serving", group: "Garnish" }),
    ],
    steps: [
      step(1, "Blend chermoula", "Blend cilantro, parsley, garlic, cumin, paprika, lemon juice, and olive oil until smooth.", { minutes: 10 }),
      step(2, "Marinate chicken", "Coat chicken chunks in chermoula. Marinate at least 2 hours or overnight.", { minutes: 10 }),
      step(3, "Prepare couscous", "Pour boiling broth or water over couscous, cover, rest 5 minutes, then fluff with a fork.", { minutes: 10 }),
      step(4, "Skewer and grill", "Thread chicken onto skewers with onion and pepper pieces. Grill over medium-high heat until charred and 165°F internal, about 12–15 minutes.", { minutes: 15, tempF: 400 }),
      step(5, "Platter and serve", "Spread couscous on platters, top with kebabs, scatter olives and preserved lemon, and serve harissa on the side.", { minutes: 5 }),
    ],
    proTips: [
      "Ras el hanout in the marinade adds authentic depth if you have it.",
      "Grill lemon halves for squeezing over finished kebabs.",
      "Almonds toasted and chopped add crunch at the line.",
    ],
    tonightSpread: [
      "Moroccan chicken kebabs over couscous with olives and harissa.",
      "Simple carrot salad with orange and cumin.",
    ],
    leftovers: [
      "Chop kebabs into couscous salad for cold lunch.",
      "Stuff into pita with yogurt for next-day wraps.",
    ],
    equipment: ["Grill", "Blender", "Skewers", "Instant-read thermometer", "Large platters"],
    nutrition: { calories: 450, protein: 36, carbs: 38, fats: 18, fiber: 3 },
    spiceLevel: "medium",
    cleanupDifficulty: "medium",
  }),

  def({
    slug: "lebanese-chicken-shish-platter",
    title: "Lebanese Chicken Shish Platter",
    subtitle: "Garlic-lemon chicken skewers with toum and tabbouleh for ten",
    category: "crew_feeders",
    protein: "chicken",
    cuisine: "lebanese",
    mealFormat: "skewer",
    explorePools: ["hall_expansion", "crew_feeders", "lebanese", "chicken"],
    hookLine: "Shish taouk platters with real garlic punch—Lebanese grill night for the hall",
    description:
      "Chicken breast chunks marinate in lemon, garlic, yogurt, and olive oil, then grill on skewers until charred at the edges. Serve with toum garlic sauce, tabbouleh, pickles, and warm pita.",
    whyCrewsLikeIt:
      "Shish taouk is Mediterranean comfort without the pasta or rice-bowl rut. Garlic-lemon chicken on skewers feels like a backyard cookout with better seasoning, and toum separates the rookies from crews who respect raw garlic.",
    mealPrepNotes:
      "Yogurt marinade tenderizes breast meat—do not skip. Make toum in a food processor ahead. Tabbouleh improves if parsley is chopped fine and salad rests 30 minutes.",
    stationWorkflow: [
      "Cut breast chunks uniform so skewers finish together.",
      "Leave small gaps on skewers for heat circulation.",
      "Warm pita in foil bundles on the grill last 5 minutes.",
    ],
    prepMinutes: 35,
    cookMinutes: 15,
    difficulty: "medium",
    crewSizeDefault: 8,
    ingredients: [
      ing("chicken breast", "4", { unit: "lb", notes: "cut into 1.5-inch cubes", group: "Main" }),
      ing("lemon juice", "0.33", { unit: "cup", group: "Marinade" }),
      ing("olive oil", "0.25", { unit: "cup", group: "Marinade" }),
      ing("Greek yogurt", "0.5", { unit: "cup", group: "Marinade" }),
      ing("garlic cloves", "8", { unit: "cloves", notes: "minced", group: "Marinade" }),
      ing("paprika", "1", { unit: "tbsp", group: "Marinade" }),
      ing("garlic cloves", "6", { unit: "cloves", notes: "for toum", group: "Sauce" }),
      ing("neutral oil", "1", { unit: "cup", notes: "for toum", group: "Sauce" }),
      ing("lemon juice", "3", { unit: "tbsp", notes: "for toum", group: "Sauce" }),
      ing("bulgur wheat", "1", { unit: "cup", notes: "fine", group: "Tabbouleh" }),
      ing("fresh parsley", "2", { unit: "cups", notes: "finely chopped", group: "Tabbouleh" }),
      ing("pita bread", "12", { unit: "rounds", notes: "warmed", group: "Service" }),
    ],
    steps: [
      step(1, "Marinate chicken", "Mix lemon juice, olive oil, yogurt, minced garlic, paprika, salt, and pepper. Coat chicken and marinate at least 2 hours.", { minutes: 15 }),
      step(2, "Make toum", "Blend garlic with lemon juice, then slowly stream in oil until thick and fluffy like mayonnaise.", { minutes: 10 }),
      step(3, "Prep tabbouleh", "Soak bulgur in hot water 20 minutes, drain, and toss with parsley, diced tomato, cucumber, mint, lemon, and olive oil.", { minutes: 25 }),
      step(4, "Grill skewers", "Thread chicken onto skewers. Grill over medium-high heat 10–12 minutes until charred and 165°F internal.", { minutes: 12, tempF: 400 }),
      step(5, "Platter and serve", "Arrange skewers on platters with tabbouleh, toum, pickles, and warm pita. Slide chicken off skewers at the line if preferred.", { minutes: 8 }),
    ],
    proTips: [
      "Sumac on finished chicken adds classic Lebanese tang.",
      "Pickled turnips from a jar are worth buying for authenticity.",
      "If toum breaks, blend in another egg white to re-emulsify.",
    ],
    tonightSpread: [
      "Shish taouk with toum, tabbouleh, pickles, and warm pita.",
      "Hummus on the side for double-dip energy.",
    ],
    leftovers: [
      "Chicken in pita with toum and pickles for lunch.",
      "Tabbouleh holds 2 days—good side for next shift.",
    ],
    equipment: ["Grill", "Food processor", "Skewers", "Instant-read thermometer", "Large platters"],
    nutrition: { calories: 420, protein: 40, carbs: 32, fats: 16, fiber: 3 },
    spiceLevel: "mild",
    cleanupDifficulty: "medium",
  }),
];
