import type { ExpansionRecipeDef } from "../types.js";
import { def, ing, step } from "../recipe-build.js";

export const BATCH_250_RECIPES: ExpansionRecipeDef[] = [
  def({
    slug: "mesquite-chuck-roast",
    title: "Mesquite Smoked Chuck Roast",
    subtitle: "Low-and-slow chuck roast sliced for sandwiches and plates for ten",
    category: "smoker_recipes",
    protein: "beef",
    cuisine: "american",
    mealFormat: "smoker",
    explorePools: ["bbq", "smoker", "beef", "hall_expansion"],
    hookLine: "Brisket-style smoke flavor without the brisket price tag or timeline",
    description:
      "Beef chuck roasts get a simple salt-and-pepper crust, then smoke until probe-tender and sliceable. Rest, slice against the grain, and serve with quick pickles and soft rolls for a true smoke-night spread.",
    whyCrewsLikeIt:
      "Chuck roast delivers rich beef smoke flavor on a station budget. It shreds or slices cleanly, holds warm in hotel pans, and feeds a full hall without babysitting a brisket all day.",
    mealPrepNotes:
      "Season roasts the night before uncovered on a rack so the rub sets. Bring to room temperature 45 minutes before smoking. Hold sliced beef at 165°F max with a splash of beef broth.",
    stationWorkflow: [
      "Use a leave-in probe in the thickest roast so you are not opening the smoker every twenty minutes.",
      "Wrap in butcher paper at 165°F internal if bark color stalls before tenderness.",
      "Slice against the grain on a dedicated board with a sharp slicer knife for even portions.",
    ],
    prepMinutes: 25,
    cookMinutes: 360,
    difficulty: "medium",
    crewSizeDefault: 10,
    ingredients: [
      ing("boneless beef chuck roast", "6", { unit: "lb", notes: "two 3 lb roasts", group: "Main" }),
      ing("kosher salt", "3", { unit: "tbsp", group: "Rub" }),
      ing("coarse black pepper", "2", { unit: "tbsp", group: "Rub" }),
      ing("garlic powder", "2", { unit: "tbsp", group: "Rub" }),
      ing("onion powder", "1", { unit: "tbsp", group: "Rub" }),
      ing("smoked paprika", "1", { unit: "tbsp", group: "Rub" }),
      ing("yellow mustard", "0.25", { unit: "cup", notes: "as binder", group: "Rub" }),
      ing("beef broth", "2", { unit: "cups", notes: "for holding", group: "Service" }),
      ing("apple cider vinegar", "0.25", { unit: "cup", group: "Service" }),
      ing("soft potato rolls", "16", { unit: "rolls", group: "Service" }),
    ],
    steps: [
      step(1, "Season the roasts", "Coat chuck roasts with mustard, then pack evenly with salt, pepper, garlic powder, onion powder, and smoked paprika. Rest on a wire rack 30 minutes while the smoker preheats.", { minutes: 35 }),
      step(2, "Smoke until tender", "Heat smoker to 250°F with mesquite or oak. Place roasts fat-side up and smoke until internal temperature reaches 165°F and a probe slides in with light resistance, about 5–6 hours.", { minutes: 180, tempF: 250 }),
      step(3, "Wrap and finish", "Wrap roasts in butcher paper and return to smoker until probe-tender at 203°F internal, about 1–1.5 hours more. Fat should render and meat should pull apart with gentle pressure.", { minutes: 75, tempF: 250 }),
      step(4, "Rest before slicing", "Rest wrapped roasts 30 minutes in a dry cooler or warm oven so juices redistribute. Unwrap and slice against the grain into quarter-inch portions.", { minutes: 30 }),
      step(5, "Hold and serve", "Toss sliced beef lightly with warm broth and vinegar. Hold covered at 165°F. Pile on rolls with pickles and extra pepper at the line.", { minutes: 15 }),
    ],
    proTips: [
      "Two smaller roasts cook more evenly than one massive roast and give you backup if one finishes early.",
      "Save pan drippings, skim fat, and whisk into warmed broth for a quick au jus.",
      "If bark gets too dark before tenderness, drop smoker temp to 225°F and stay patient.",
    ],
    tonightSpread: [
      "Sliced chuck on a hotel pan with soft rolls, dill pickles, and sliced raw onion.",
      "Quick coleslaw with vinegar dressing to cut the rich smoke and fat.",
    ],
    leftovers: [
      "Chop and simmer in BBQ sauce for fast smoked beef sandwiches the next shift.",
      "Dice into a hearty beef and barley soup with leftover broth.",
    ],
    equipment: ["Pellet or offset smoker", "Instant-read thermometer", "Butcher paper", "Wire rack", "Hotel pans"],
    nutrition: { calories: 410, protein: 42, carbs: 18, fats: 20, fiber: 1 },
    spiceLevel: "mild",
    cleanupDifficulty: "medium",
  }),

  def({
    slug: "molasses-bourbon-pork-ribs",
    title: "Molasses Bourbon Pork Ribs",
    subtitle: "St. Louis ribs with sticky molasses-bourbon glaze for ten",
    category: "smoker_recipes",
    protein: "pork",
    cuisine: "american",
    mealFormat: "smoker",
    explorePools: ["bbq", "smoker", "pork", "hall_expansion"],
    hookLine: "Sweet-smoky ribs that pass the bend test without drying out on the hold line",
    description:
      "St. Louis-cut ribs get a brown-sugar rub, smoke wrapped until tender, then finish unwrapped with a molasses-bourbon glaze until sticky and lightly charred. Cut into three-bone sections for fast service.",
    whyCrewsLikeIt:
      "Ribs are pure game-day energy—hands-on, satisfying, and impossible to eat just one. Pre-cutting racks into sections means faster plating when the tones drop mid-meal.",
    mealPrepNotes:
      "Remove silver skin the day before and keep seasoned racks on sheet pans in the fridge. Glaze can be mixed ahead. Hold finished ribs loosely tented at 170°F—tight foil steams away bark.",
    stationWorkflow: [
      "Wrap ribs in foil with a splash of apple juice at the two-hour mark to speed tenderness without boiling.",
      "Apply glaze in two thin coats during the final 20 minutes so sugar caramelizes instead of burning.",
      "Cut between bones with a sharp boning knife on a rimmed board to catch glaze drips.",
    ],
    prepMinutes: 30,
    cookMinutes: 300,
    difficulty: "medium",
    crewSizeDefault: 10,
    ingredients: [
      ing("St. Louis pork ribs", "4", { unit: "racks", notes: "about 8 lb total", group: "Main" }),
      ing("brown sugar", "0.5", { unit: "cup", group: "Rub" }),
      ing("kosher salt", "3", { unit: "tbsp", group: "Rub" }),
      ing("smoked paprika", "2", { unit: "tbsp", group: "Rub" }),
      ing("garlic powder", "2", { unit: "tbsp", group: "Rub" }),
      ing("black pepper", "1", { unit: "tbsp", group: "Rub" }),
      ing("molasses", "0.33", { unit: "cup", group: "Glaze" }),
      ing("bourbon", "0.25", { unit: "cup", group: "Glaze" }),
      ing("BBQ sauce", "1", { unit: "cup", group: "Glaze" }),
      ing("apple juice", "1", { unit: "cup", notes: "for spritz and wrap", group: "Glaze" }),
    ],
    steps: [
      step(1, "Prep and rub the racks", "Remove silver skin from the bone side of each rack. Coat both sides with brown sugar, salt, smoked paprika, garlic powder, and black pepper. Let sit 20 minutes while smoker preheats.", { minutes: 25 }),
      step(2, "Smoke the ribs", "Heat smoker to 275°F with fruit or hickory wood. Place ribs bone-side down and smoke 2 hours, spritzing with apple juice every 45 minutes.", { minutes: 120, tempF: 275 }),
      step(3, "Wrap for tenderness", "Lay each rack on foil, add 2 tablespoons apple juice, wrap tight, and return to smoker until meat pulls back from bones and internal temp hits 195°F, about 1.5–2 hours.", { minutes: 105, tempF: 275 }),
      step(4, "Glaze and finish", "Unwrap ribs, brush with molasses-bourbon glaze mixed with BBQ sauce, and smoke uncovered 20–30 minutes until sticky and lightly charred at the edges.", { minutes: 25, tempF: 275 }),
      step(5, "Rest and portion", "Rest racks 10 minutes, slice into three-bone sections, and pile on platters. Serve with extra glaze and wet wipes at the line.", { minutes: 15 }),
    ],
    proTips: [
      "If ribs finish early, hold wrapped in a cooler up to 90 minutes without losing texture.",
      "Keep bourbon away from open flame—add to glaze off heat, then brush on the smoker.",
      "Offer extra napkins. This is not a fork-and-knife meal and crews will respect you for knowing that.",
    ],
    tonightSpread: [
      "Rib sections on sheet pans with extra glaze and cornbread muffins.",
      "Cool cucumber salad with sour cream to reset between sweet, sticky bites.",
    ],
    leftovers: [
      "Pull meat from bones and fold into mac and cheese for smoky rib mac.",
      "Chop and pile on loaded fries with shredded cheese and scallions.",
    ],
    equipment: ["Smoker", "Aluminum foil", "Spray bottle", "Basting brush", "Instant-read thermometer"],
    nutrition: { calories: 580, protein: 38, carbs: 28, fats: 36, fiber: 1 },
    spiceLevel: "mild",
    cleanupDifficulty: "medium",
  }),

  def({
    slug: "applewood-pork-shoulder-steaks",
    title: "Applewood Grilled Pork Shoulder Steaks",
    subtitle: "Thick-cut shoulder steaks with apple glaze for ten on the grill",
    category: "smoker_recipes",
    protein: "pork",
    cuisine: "american",
    mealFormat: "grill",
    explorePools: ["bbq", "grill", "pork", "hall_expansion"],
    hookLine: "Pork shoulder flavor in a fast-grill steak format that still feeds the whole hall",
    description:
      "Boneless pork shoulder is sliced into thick steaks, marinated overnight, then grilled over medium-high heat until charred outside and juicy inside. A reduced apple cider glaze finishes on the grill for shine and tang.",
    whyCrewsLikeIt:
      "Shoulder steaks give you pork BBQ flavor without a twelve-hour smoke commitment. They cook in under thirty minutes on the grill and portion cleanly for a hungry line.",
    mealPrepNotes:
      "Slice steaks uniform—about 1 inch thick—so they finish together. Marinate up to 24 hours in labeled cambros. Glaze can simmer ahead and reheat on the side burner.",
    stationWorkflow: [
      "Pat steaks dry before grilling so marinade sugars caramelize instead of steaming.",
      "Move steaks to cooler zones if flare-ups threaten to char the exterior before center hits 145°F.",
      "Tent finished steaks 5 minutes before slicing across the grain for service.",
    ],
    prepMinutes: 30,
    cookMinutes: 35,
    difficulty: "easy",
    crewSizeDefault: 10,
    ingredients: [
      ing("boneless pork shoulder", "6", { unit: "lb", notes: "cut into 10 steaks", group: "Main" }),
      ing("apple cider", "2", { unit: "cups", group: "Marinade" }),
      ing("olive oil", "0.33", { unit: "cup", group: "Marinade" }),
      ing("garlic cloves", "6", { unit: "cloves", notes: "smashed", group: "Marinade" }),
      ing("fresh rosemary", "3", { unit: "tbsp", notes: "chopped", group: "Marinade" }),
      ing("kosher salt", "2", { unit: "tbsp", group: "Seasoning" }),
      ing("black pepper", "1", { unit: "tbsp", group: "Seasoning" }),
      ing("brown sugar", "0.25", { unit: "cup", group: "Glaze" }),
      ing("Dijon mustard", "2", { unit: "tbsp", group: "Glaze" }),
      ing("apple cider vinegar", "2", { unit: "tbsp", group: "Glaze" }),
    ],
    steps: [
      step(1, "Marinate the steaks", "Whisk cider, olive oil, garlic, rosemary, salt, and pepper. Coat pork steaks and refrigerate at least 4 hours or overnight so flavor penetrates the thick cut.", { minutes: 15 }),
      step(2, "Build the glaze", "Simmer 1 cup cider with brown sugar, Dijon, and vinegar until reduced to a syrupy glaze that coats the back of a spoon, about 12 minutes. Keep warm off heat.", { minutes: 12 }),
      step(3, "Preheat the grill", "Heat grill to medium-high, about 400°F on the grates. Oil grates well so sticky marinade does not tear the crust when you flip.", { minutes: 10, tempF: 400 }),
      step(4, "Grill the steaks", "Grill steaks 5–6 minutes per side until grill marks set and internal temperature reaches 145°F in the thickest part. Brush with glaze during the final 2 minutes on each side.", { minutes: 12, tempF: 400 }),
      step(5, "Rest and slice", "Tent steaks 5 minutes, then slice across the grain into half-inch strips. Fan on platters and serve with remaining glaze at the line.", { minutes: 10 }),
    ],
    proTips: [
      "Ask the butcher to slice shoulder steaks if your knife skills are still developing—uniform thickness matters.",
      "Keep a spray bottle of water near the grill to tame flare-ups from cider sugars.",
      "Pair with grilled apple halves brushed with the same glaze for a seasonal smoke-night side.",
    ],
    tonightSpread: [
      "Sliced pork steaks with extra glaze, roasted potatoes, and quick pickled red onions.",
      "Soft rolls for building apple-glazed pork sandwiches with slaw.",
    ],
    leftovers: [
      "Chop cold steak into a hash with diced potatoes and fried eggs for breakfast shift.",
      "Slice thin for Cuban-style pressed sandwiches with pickles and mustard.",
    ],
    equipment: ["Charcoal or gas grill", "Instant-read thermometer", "Basting brush", "Sheet pans", "Mixing bowls"],
    nutrition: { calories: 460, protein: 44, carbs: 14, fats: 26, fiber: 0 },
    spiceLevel: "mild",
    cleanupDifficulty: "easy",
  }),

  def({
    slug: "honey-mustard-oven-chicken-thighs",
    title: "Honey Mustard Baked Chicken Thighs",
    subtitle: "Crispy-skinned thighs with tangy honey-mustard glaze for ten",
    category: "crew_feeders",
    protein: "chicken",
    cuisine: "american",
    mealFormat: "baked",
    explorePools: ["chicken", "comfort", "hall_expansion"],
    hookLine: "Sheet-pan chicken that hits 165°F with real crisp skin and no fryer mess",
    description:
      "Bone-in chicken thighs are seasoned, roasted on a wire rack until skin crisps, then brushed with honey-mustard glaze during the final minutes. Finish under the broiler for color if needed.",
    whyCrewsLikeIt:
      "Thighs forgive timing better than breast meat and stay juicy on the hold line. One sheet pan feeds ten without standing over a grill between calls.",
    mealPrepNotes:
      "Pat thighs completely dry for crisp skin. Line sheet pans with foil for fast cleanup. Glaze can be mixed ahead in squeeze bottles.",
    stationWorkflow: [
      "Space thighs skin-side up on a wire rack so hot air circulates under the skin.",
      "Brush glaze only in the last 8 minutes so sugars do not burn before meat finishes.",
      "Hold finished thighs whole and portion at the line to keep skin intact.",
    ],
    prepMinutes: 20,
    cookMinutes: 45,
    difficulty: "easy",
    crewSizeDefault: 10,
    ingredients: [
      ing("bone-in chicken thighs", "5", { unit: "lb", notes: "about 16 pieces", group: "Main" }),
      ing("olive oil", "3", { unit: "tbsp", group: "Seasoning" }),
      ing("kosher salt", "2", { unit: "tbsp", group: "Seasoning" }),
      ing("black pepper", "1", { unit: "tbsp", group: "Seasoning" }),
      ing("smoked paprika", "1", { unit: "tbsp", group: "Seasoning" }),
      ing("garlic powder", "1", { unit: "tbsp", group: "Seasoning" }),
      ing("honey", "0.33", { unit: "cup", group: "Glaze" }),
      ing("Dijon mustard", "0.33", { unit: "cup", group: "Glaze" }),
      ing("apple cider vinegar", "2", { unit: "tbsp", group: "Glaze" }),
      ing("fresh parsley", "0.25", { unit: "cup", notes: "chopped", group: "Finish" }),
    ],
    steps: [
      step(1, "Season the thighs", "Pat chicken thighs dry. Toss with olive oil, salt, pepper, smoked paprika, and garlic powder until evenly coated.", { minutes: 10 }),
      step(2, "Roast on a rack", "Arrange thighs skin-side up on a wire rack over a foil-lined sheet pan. Roast at 425°F until skin crisps and internal temp reaches 155°F, about 30 minutes.", { minutes: 30, tempF: 425 }),
      step(3, "Build the glaze", "Whisk honey, Dijon, and vinegar until smooth. Taste and adjust tang with a splash more vinegar if too sweet.", { minutes: 3 }),
      step(4, "Glaze and finish", "Brush thighs with glaze and roast 8–10 more minutes until internal temp hits 165°F and glaze sets glossy. Broil 1–2 minutes for extra color if needed.", { minutes: 10, tempF: 425 }),
      step(5, "Rest and serve", "Rest thighs 5 minutes. Portion two per plate with pan juices spooned over and parsley scattered at the line.", { minutes: 5 }),
    ],
    proTips: [
      "Use a leave-in probe on the largest thigh so you are not guessing on doneness.",
      "Roast green beans on a second rack below the chicken to use oven space efficiently.",
      "Save rendered fat from the pan for roasting potatoes on the next shift.",
    ],
    tonightSpread: [
      "Glazed thighs with roasted baby potatoes and steamed green beans.",
      "Extra glaze in a squeeze bottle for crew who want more tang at the table.",
    ],
    leftovers: [
      "Pull meat and chop into a chicken salad with celery and light mayo.",
      "Slice and stack on toasted bread with Swiss cheese for quick melts.",
    ],
    equipment: ["Sheet pans", "Wire cooling rack", "Instant-read thermometer", "Mixing bowls", "Basting brush"],
    nutrition: { calories: 390, protein: 36, carbs: 12, fats: 22, fiber: 0 },
    spiceLevel: "mild",
    cleanupDifficulty: "easy",
  }),

  def({
    slug: "spatchcock-lemon-roast-chicken",
    title: "Spatchcock Lemon Roast Chicken",
    subtitle: "Whole birds flattened with lemon-garlic butter for ten",
    category: "crew_feeders",
    protein: "chicken",
    cuisine: "american",
    mealFormat: "roast",
    explorePools: ["chicken", "comfort", "hall_expansion"],
    hookLine: "Two spatchcocked birds that roast even and carve fast after a long shift",
    description:
      "Whole chickens are spatchcocked, seasoned under the skin with lemon-garlic butter, and roasted on sheet pans until golden. Carve into quarters and eighths for fast hall service.",
    whyCrewsLikeIt:
      "Spatchcocking cuts roast time nearly in half and gives every piece crisp skin. Whole bird night feels special without the stress of grilling twenty individual pieces.",
    mealPrepNotes:
      "Spatchcock birds the morning of and keep on sheet pans in the fridge. Soften butter mix ahead. Rest birds 15 minutes before carving or juices run everywhere.",
    stationWorkflow: [
      "Use kitchen shears to remove backbone and flatten bird—watch a quick video once and you will never go back.",
      "Slide butter under breast skin carefully so it melts into meat during roast.",
      "Carve on a rimmed board with a sharp knife: remove legs, split breast, then portion.",
    ],
    prepMinutes: 35,
    cookMinutes: 60,
    difficulty: "medium",
    crewSizeDefault: 10,
    ingredients: [
      ing("whole chickens", "2", { unit: "whole", notes: "about 5 lb each", group: "Main" }),
      ing("unsalted butter", "0.5", { unit: "cup", notes: "softened", group: "Butter" }),
      ing("lemon", "2", { unit: "whole", notes: "zested and juiced", group: "Butter" }),
      ing("garlic cloves", "8", { unit: "cloves", notes: "minced", group: "Butter" }),
      ing("fresh thyme", "2", { unit: "tbsp", group: "Butter" }),
      ing("kosher salt", "2", { unit: "tbsp", group: "Seasoning" }),
      ing("black pepper", "1", { unit: "tbsp", group: "Seasoning" }),
      ing("olive oil", "2", { unit: "tbsp", group: "Seasoning" }),
      ing("yellow onion", "2", { unit: "whole", notes: "quartered", group: "Roast" }),
      ing("carrots", "4", { unit: "whole", notes: "chunked", group: "Roast" }),
    ],
    steps: [
      step(1, "Spatchcock the birds", "Remove backbones with shears, flatten chickens breast-side up, and tuck wing tips under. Pat completely dry inside and out.", { minutes: 15 }),
      step(2, "Season under the skin", "Mix butter with lemon zest, juice, garlic, and thyme. Loosen breast skin and spread half the butter mix under skin on each bird. Season outside with salt, pepper, and olive oil.", { minutes: 15 }),
      step(3, "Roast on vegetables", "Scatter onion and carrots on two sheet pans. Place spatchcocked birds on top and roast at 425°F until thickest breast hits 165°F and skin is golden, about 50–60 minutes.", { minutes: 55, tempF: 425 }),
      step(4, "Rest before carving", "Tent birds with foil and rest 15 minutes so juices settle. Save pan juices and roasted vegetables for service.", { minutes: 15 }),
      step(5, "Carve for the line", "Carve each bird into ten portions: legs, thighs, and breast pieces. Arrange on hotel pans with pan juices spooned over.", { minutes: 10 }),
    ],
    proTips: [
      "Insert probe in the thickest part of the breast, not touching bone, for accurate reads.",
      "If skin browns too fast, tent loosely with foil and keep roasting to 165°F internal.",
      "Roasted pan vegetables make an easy side without another pot to wash.",
    ],
    tonightSpread: [
      "Carved chicken on platters with pan juices and roasted carrots and onions.",
      "Mashed potatoes or crusty bread to soak up lemon-garlic butter.",
    ],
    leftovers: [
      "Strip bones for chicken soup with the roasted vegetable base.",
      "Slice cold breast for sandwiches with mayo and crisp lettuce.",
    ],
    equipment: ["Kitchen shears", "Sheet pans", "Instant-read thermometer", "Carving knife", "Mixing bowls"],
    nutrition: { calories: 420, protein: 40, carbs: 8, fats: 26, fiber: 2 },
    spiceLevel: "mild",
    cleanupDifficulty: "medium",
  }),

  def({
    slug: "cajun-chicken-rice-skillet",
    title: "Cajun Chicken and Rice Skillet",
    subtitle: "One-skillet spiced chicken with peppers and rice for ten",
    category: "crew_feeders",
    protein: "chicken",
    cuisine: "cajun",
    mealFormat: "skillet",
    explorePools: ["chicken", "one_pot", "hall_expansion"],
    hookLine: "Dirty-rice energy in one pan with real heat control for mixed spice tolerances",
    description:
      "Chicken thighs are seared with Cajun seasoning, then simmered with trinity vegetables, rice, and broth until fluffy and fragrant. Finish with scallions and hot sauce at the line.",
    whyCrewsLikeIt:
      "One pan means fewer dishes after a busy day. Bold Cajun flavor reads as a proper meal, not a rookie rice packet, and the skillet format holds warm on the stove between calls.",
    mealPrepNotes:
      "Dice trinity uniform so it cooks evenly. Use a large cast iron or hotel pan for ten portions. Keep hot sauce off to the side for heat-sensitive crew.",
    stationWorkflow: [
      "Sear chicken in batches so skin browns instead of steaming in the pan.",
      "Toast rice in the fat 2 minutes before adding broth for nuttier flavor.",
      "Cover and simmer on low—lift lid only once to check liquid level.",
    ],
    prepMinutes: 25,
    cookMinutes: 40,
    difficulty: "easy",
    crewSizeDefault: 10,
    ingredients: [
      ing("bone-in chicken thighs", "4", { unit: "lb", notes: "about 12 pieces", group: "Main" }),
      ing("long-grain white rice", "3", { unit: "cups", group: "Main" }),
      ing("Cajun seasoning", "3", { unit: "tbsp", group: "Seasoning" }),
      ing("yellow onion", "1", { unit: "whole", notes: "diced", group: "Trinity" }),
      ing("green bell pepper", "2", { unit: "whole", notes: "diced", group: "Trinity" }),
      ing("celery stalks", "3", { unit: "stalks", notes: "diced", group: "Trinity" }),
      ing("garlic cloves", "5", { unit: "cloves", notes: "minced", group: "Trinity" }),
      ing("chicken broth", "5", { unit: "cups", group: "Liquid" }),
      ing("tomato paste", "2", { unit: "tbsp", group: "Liquid" }),
      ing("green onions", "6", { unit: "whole", notes: "sliced", group: "Finish" }),
    ],
    steps: [
      step(1, "Season and sear chicken", "Toss chicken thighs with half the Cajun seasoning. Sear skin-side down in a large skillet over medium-high heat 5 minutes per side until golden. Set aside.", { minutes: 12 }),
      step(2, "Cook the trinity", "In the same pan, sauté onion, bell pepper, celery, and garlic 6–8 minutes until softened and lightly caramelized at the edges.", { minutes: 8 }),
      step(3, "Toast rice and build", "Stir in rice and remaining Cajun seasoning, toast 2 minutes, then add tomato paste and broth. Nestle seared chicken skin-side up into the rice.", { minutes: 5 }),
      step(4, "Simmer covered", "Cover and simmer on low 25–30 minutes until rice absorbs liquid and chicken reaches 165°F internal. Avoid stirring so rice stays fluffy.", { minutes: 28 }),
      step(5, "Rest and serve", "Rest covered 5 minutes off heat. Fluff rice gently around chicken, scatter green onions, and serve straight from the skillet or transfer to a hotel pan.", { minutes: 5 }),
    ],
    proTips: [
      "If rice looks dry before chicken finishes, add broth ¼ cup at a time—not water.",
      "Andouille sausage slices stirred in at step 2 add smoke without extra pans.",
      "A tight-fitting lid or foil seal is critical—steam escapes and rice stays crunchy.",
    ],
    tonightSpread: [
      "Skillet served with cornbread muffins and extra hot sauce on the side.",
      "Simple iceberg salad with ranch for crew who want something cool.",
    ],
    leftovers: [
      "Reheat covered with splash of broth for lunch bowls the next day.",
      "Stuff into bell pepper halves and bake for a quick round-two dinner.",
    ],
    equipment: ["Large cast iron skillet or Dutch oven", "Instant-read thermometer", "Tight lid", "Wooden spoon", "Hotel pan"],
    nutrition: { calories: 480, protein: 34, carbs: 52, fats: 16, fiber: 3 },
    spiceLevel: "medium",
    cleanupDifficulty: "easy",
  }),

  def({
    slug: "paprika-roasted-chicken-quarters",
    title: "Paprika Roasted Chicken Quarters",
    subtitle: "Budget-friendly leg quarters with smoked paprika rub for ten",
    category: "crew_feeders",
    protein: "chicken",
    cuisine: "american",
    mealFormat: "baked",
    explorePools: ["chicken", "budget", "hall_expansion"],
    hookLine: "Leg quarters that roast cheap, taste big, and survive the hold pan",
    description:
      "Chicken leg quarters get a smoky paprika rub and roast on sheet pans until skin crackles and meat pulls cleanly from the bone at 165°F. Simple, filling, and built for hall budgets.",
    whyCrewsLikeIt:
      "Leg quarters are the most forgiving cut on the roster—cheap, hard to overcook, and satisfying after a hard shift. Two pans feed ten without fuss.",
    mealPrepNotes:
      "Season quarters up to 12 hours ahead for deeper flavor. Use parchment on pans for easier cleanup. Portion one leg quarter per person with extra for big eaters.",
    stationWorkflow: [
      "Arrange quarters skin-side up with space between pieces for air circulation.",
      "Rotate pans top to bottom halfway through for even browning in uneven ovens.",
      "Check largest quarter with a probe—dark meat finishes slower than it looks.",
    ],
    prepMinutes: 15,
    cookMinutes: 50,
    difficulty: "easy",
    crewSizeDefault: 10,
    ingredients: [
      ing("chicken leg quarters", "6", { unit: "lb", notes: "about 12 pieces", group: "Main" }),
      ing("smoked paprika", "2", { unit: "tbsp", group: "Rub" }),
      ing("sweet paprika", "1", { unit: "tbsp", group: "Rub" }),
      ing("kosher salt", "2", { unit: "tbsp", group: "Rub" }),
      ing("garlic powder", "1", { unit: "tbsp", group: "Rub" }),
      ing("onion powder", "1", { unit: "tbsp", group: "Rub" }),
      ing("black pepper", "1", { unit: "tsp", group: "Rub" }),
      ing("olive oil", "0.25", { unit: "cup", group: "Rub" }),
      ing("lemon wedges", "4", { unit: "whole", notes: "for serving", group: "Finish" }),
      ing("fresh parsley", "0.25", { unit: "cup", notes: "chopped", group: "Finish" }),
    ],
    steps: [
      step(1, "Mix the rub", "Combine smoked paprika, sweet paprika, salt, garlic powder, onion powder, and black pepper. Toss quarters with olive oil, then coat evenly with rub.", { minutes: 10 }),
      step(2, "Prep the pans", "Line two sheet pans with parchment. Arrange quarters skin-side up with at least an inch between pieces.", { minutes: 5 }),
      step(3, "Roast until done", "Roast at 400°F for 45–50 minutes until skin is deep golden and thickest part reaches 165°F without touching bone.", { minutes: 48, tempF: 400 }),
      step(4, "Crisp under broiler", "Optional: broil 2–3 minutes for extra crackly skin. Watch closely so paprika does not scorch.", { minutes: 3 }),
      step(5, "Serve family-style", "Rest 5 minutes, scatter parsley, and pile quarters on platters with lemon wedges for squeezing at the table.", { minutes: 5 }),
    ],
    proTips: [
      "Quarters are done when juices run clear and leg joint moves easily—probe confirms.",
      "Roast quartered potatoes on the same pans during the last 30 minutes.",
      "Hold finished quarters at 165°F max—higher dries dark meat fast.",
    ],
    tonightSpread: [
      "Paprika quarters with roasted potatoes and buttered corn.",
      "White rice with pan drippings spooned over for a simple plate.",
    ],
    leftovers: [
      "Pull meat for chicken tacos with shredded lettuce and salsa.",
      "Simmer bones into stock for next week's soup base.",
    ],
    equipment: ["Sheet pans", "Parchment paper", "Instant-read thermometer", "Mixing bowls", "Platters"],
    nutrition: { calories: 410, protein: 38, carbs: 4, fats: 28, fiber: 0 },
    spiceLevel: "mild",
    cleanupDifficulty: "easy",
  }),

  def({
    slug: "cast-iron-chicken-fajitas",
    title: "Cast Iron Chicken Fajitas",
    subtitle: "Sizzling peppers and chicken with warm tortillas for ten",
    category: "game_day_recipes",
    protein: "chicken",
    cuisine: "mexican",
    mealFormat: "skillet",
    explorePools: ["chicken", "game_day", "handheld", "hall_expansion"],
    hookLine: "That sizzle when the pan hits the table—without a trip to a restaurant",
    description:
      "Chicken strips marinate in lime and spices, sear hot in cast iron with peppers and onions, and serve sizzling with warm tortillas and classic fixings. Built for build-your-own line speed.",
    whyCrewsLikeIt:
      "Fajitas feel like an event—sizzling pans, fresh toppings, everyone building their own. Interactive meals keep morale up on long tour days.",
    mealPrepNotes:
      "Slice chicken uniform for even cooking. Marinate up to 8 hours. Warm tortillas in foil bundles so they stay soft at the line.",
    stationWorkflow: [
      "Cook chicken in batches over high heat—crowding steams instead of sears.",
      "Keep cast iron screaming hot before adding peppers so they char quickly.",
      "Serve fixings in labeled bowls: salsa, sour cream, cheese, lettuce, lime.",
    ],
    prepMinutes: 30,
    cookMinutes: 20,
    difficulty: "easy",
    crewSizeDefault: 10,
    ingredients: [
      ing("chicken breast", "4", { unit: "lb", notes: "sliced into strips", group: "Main" }),
      ing("lime juice", "0.33", { unit: "cup", group: "Marinade" }),
      ing("olive oil", "0.25", { unit: "cup", group: "Marinade" }),
      ing("chili powder", "2", { unit: "tbsp", group: "Marinade" }),
      ing("ground cumin", "1", { unit: "tbsp", group: "Marinade" }),
      ing("garlic cloves", "4", { unit: "cloves", notes: "minced", group: "Marinade" }),
      ing("red bell pepper", "3", { unit: "whole", notes: "sliced", group: "Vegetables" }),
      ing("green bell pepper", "2", { unit: "whole", notes: "sliced", group: "Vegetables" }),
      ing("yellow onion", "2", { unit: "whole", notes: "sliced", group: "Vegetables" }),
      ing("flour tortillas", "20", { unit: "whole", notes: "8-inch", group: "Service" }),
    ],
    steps: [
      step(1, "Marinate the chicken", "Toss chicken strips with lime juice, 2 tablespoons olive oil, chili powder, cumin, and garlic. Marinate at least 30 minutes in the fridge.", { minutes: 10 }),
      step(2, "Sear the chicken", "Heat cast iron over high heat until smoking lightly. Sear chicken in batches 3–4 minutes until charred edges appear and internal temp reaches 165°F. Set aside.", { minutes: 12 }),
      step(3, "Char the vegetables", "Add remaining oil to the pan. Sear peppers and onions 4–5 minutes until blistered and tender-crisp with light char.", { minutes: 5 }),
      step(4, "Combine and season", "Return chicken to pan, toss with vegetables, and season with salt to taste. Squeeze half a lime over the mix.", { minutes: 2 }),
      step(5, "Serve sizzling", "Warm tortillas wrapped in foil at 300°F for 10 minutes. Portion chicken and peppers into hot cast iron skillets or hotel pans and serve with fixings.", { minutes: 10, tempF: 300 }),
    ],
    proTips: [
      "Vent the kitchen—high-heat searing sets off alarms if you are not ready.",
      "A splash of chicken broth at the end keeps everything juicy on the hold line.",
      "Offer sliced jalapeños for heat without forcing spice on the whole hall.",
    ],
    tonightSpread: [
      "Sizzling fajita pans with tortillas, shredded cheese, salsa, and sour cream.",
      "Spanish rice on the side for crew who want a plated option instead of wraps.",
    ],
    leftovers: [
      "Chop into breakfast burritos with scrambled eggs and hot sauce.",
      "Toss cold leftovers over romaine for a quick fajita salad lunch.",
    ],
    equipment: ["Cast iron skillet", "Instant-read thermometer", "Sheet pans", "Mixing bowls", "Tongs"],
    nutrition: { calories: 380, protein: 36, carbs: 32, fats: 12, fiber: 4 },
    spiceLevel: "medium",
    cleanupDifficulty: "easy",
  }),

  def({
    slug: "mushroom-swiss-steak-pan",
    title: "Mushroom Swiss Steak Pan",
    subtitle: "Seared round steak with mushrooms and Swiss over mashed potatoes for ten",
    category: "crew_feeders",
    protein: "beef",
    cuisine: "russian",
    mealFormat: "pasta",
    explorePools: ["beef", "comfort", "pasta", "hall_expansion"],
    hookLine: "Classic stroganoff scaled for the hall without curdled sauce panic",
    description:
      "Sirloin strips sear fast, simmer with mushrooms and onions in a rich broth base, then finish off heat with sour cream for a silky sauce. Serve over wide egg noodles with parsley.",
    whyCrewsLikeIt:
      "Stroganoff is pure comfort after cold calls. The sauce feels indulgent but comes together in one pot plus a noodle boil—manageable even for newer cooks.",
    mealPrepNotes:
      "Slice beef against the grain thin for tender bites. Stir sour cream off heat so it does not break. Hold sauce and noodles separately if holding more than 30 minutes.",
    stationWorkflow: [
      "Sear beef in batches over high heat—thirty seconds per side max before it toughens.",
      "Deglaze with broth to capture fond; that is your flavor foundation.",
      "Toss noodles with a little butter before saucing so they do not clump on the line.",
    ],
    prepMinutes: 25,
    cookMinutes: 35,
    difficulty: "medium",
    crewSizeDefault: 10,
    ingredients: [
      ing("sirloin steak", "3", { unit: "lb", notes: "sliced thin", group: "Main" }),
      ing("wide egg noodles", "2", { unit: "lb", group: "Main" }),
      ing("cremini mushrooms", "1.5", { unit: "lb", notes: "sliced", group: "Vegetables" }),
      ing("yellow onion", "1", { unit: "whole", notes: "diced", group: "Vegetables" }),
      ing("garlic cloves", "4", { unit: "cloves", notes: "minced", group: "Aromatics" }),
      ing("beef broth", "3", { unit: "cups", group: "Sauce" }),
      ing("sour cream", "1.5", { unit: "cups", group: "Sauce" }),
      ing("Dijon mustard", "2", { unit: "tbsp", group: "Sauce" }),
      ing("unsalted butter", "4", { unit: "tbsp", group: "Sauce" }),
      ing("fresh parsley", "0.33", { unit: "cup", notes: "chopped", group: "Finish" }),
    ],
    steps: [
      step(1, "Sear the beef", "Pat sirloin strips dry and season with salt and pepper. Sear in butter over high heat in batches 30–45 seconds per side until browned but still pink inside. Set aside.", { minutes: 10 }),
      step(2, "Cook mushrooms and onion", "In the same pot, sauté mushrooms and onion 8 minutes until moisture evaporates and edges brown. Add garlic and cook 1 minute.", { minutes: 9 }),
      step(3, "Build the sauce", "Pour in beef broth and simmer 5 minutes, scraping fond from the bottom. Whisk Dijon into sour cream, then stir off heat into the warm broth until smooth.", { minutes: 6 }),
      step(4, "Cook the noodles", "Boil egg noodles in salted water until al dente, about 8 minutes. Drain and toss with a tablespoon of butter.", { minutes: 10 }),
      step(5, "Combine and serve", "Return beef and any juices to sauce and warm 2 minutes—do not boil. Serve noodles topped with stroganoff and parsley at the line.", { minutes: 5 }),
    ],
    proTips: [
      "Partially freeze sirloin 20 minutes for easier thin slicing.",
      "If sauce breaks, whisk in a spoonful of cold sour cream off heat to bring it back.",
      "Frozen peas stirred in at the end add color and stretch the dish cheaply.",
    ],
    tonightSpread: [
      "Stroganoff over noodles with crusty bread for sauce mopping.",
      "Simple cucumber salad with dill for a cool contrast.",
    ],
    leftovers: [
      "Reheat gently with splash of broth—microwave on medium, not full blast.",
      "Fill baked potato skins with stroganoff and melted cheese.",
    ],
    equipment: ["Large Dutch oven", "Stock pot", "Tongs", "Whisk", "Chef knife"],
    nutrition: { calories: 520, protein: 38, carbs: 48, fats: 22, fiber: 3 },
    spiceLevel: "mild",
    cleanupDifficulty: "medium",
  }),

  def({
    slug: "pepper-steak-onions",
    title: "Pepper Steak with Onions",
    subtitle: "Sliced round steak with bell peppers over rice for ten",
    category: "crew_feeders",
    protein: "beef",
    cuisine: "chinese-american",
    mealFormat: "skillet",
    explorePools: ["beef", "comfort", "hall_expansion"],
    hookLine: "Takeout-style pepper steak that hits the table faster than delivery",
    description:
      "Round steak strips marinate in soy and ginger, stir-fry with peppers and onions, and finish in a savory gravy. Serve over steamed rice for a filling hall plate.",
    whyCrewsLikeIt:
      "Pepper steak delivers big savory flavor with ingredients already in the station pantry. Rice stretches the protein and keeps everyone full through a second call.",
    mealPrepNotes:
      "Slice steak against the grain paper-thin. Mix gravy slurry before you start cooking—no time to measure mid-stir-fry. Cook rice in a separate pot or rice cooker.",
    stationWorkflow: [
      "Get the wok or large skillet smoking hot before beef hits the pan.",
      "Stir-fry in batches: beef first, set aside, then peppers, then combine.",
      "Add gravy and simmer just until glossy—overcooking turns beef chewy.",
    ],
    prepMinutes: 30,
    cookMinutes: 25,
    difficulty: "medium",
    crewSizeDefault: 10,
    ingredients: [
      ing("round steak", "3.5", { unit: "lb", notes: "sliced thin", group: "Main" }),
      ing("long-grain white rice", "3", { unit: "cups", notes: "uncooked", group: "Base" }),
      ing("green bell pepper", "3", { unit: "whole", notes: "sliced", group: "Vegetables" }),
      ing("red bell pepper", "2", { unit: "whole", notes: "sliced", group: "Vegetables" }),
      ing("yellow onion", "2", { unit: "whole", notes: "sliced", group: "Vegetables" }),
      ing("soy sauce", "0.33", { unit: "cup", group: "Marinade" }),
      ing("fresh ginger", "2", { unit: "tbsp", notes: "grated", group: "Marinade" }),
      ing("garlic cloves", "5", { unit: "cloves", notes: "minced", group: "Marinade" }),
      ing("beef broth", "2", { unit: "cups", group: "Gravy" }),
      ing("cornstarch", "3", { unit: "tbsp", group: "Gravy" }),
    ],
    steps: [
      step(1, "Marinate and prep rice", "Toss sliced steak with half the soy sauce and ginger. Start rice in a pot with 6 cups water—bring to boil, cover, simmer 18 minutes, then rest off heat.", { minutes: 5 }),
      step(2, "Sear the beef", "Heat oil in a wok over high heat. Stir-fry beef in batches 2–3 minutes until browned but still tender. Set aside.", { minutes: 8 }),
      step(3, "Stir-fry vegetables", "Add peppers and onion to the wok. Stir-fry 4–5 minutes until charred at edges and slightly softened.", { minutes: 5 }),
      step(4, "Build the gravy", "Stir remaining soy sauce, garlic, broth, and cornstarch slurry into the wok. Simmer 2 minutes until glossy and thickened.", { minutes: 3 }),
      step(5, "Combine and serve", "Return beef and juices to gravy, toss 1 minute to coat. Fluff rice and serve pepper steak over rice at the line.", { minutes: 4 }),
    ],
    proTips: [
      "A splash of rice vinegar at the end brightens heavy soy gravy.",
      "Use baking soda pinch in marinade for extra tender beef if your cut is tough.",
      "Sesame oil drizzle at service adds aroma—do not cook it on high heat.",
    ],
    tonightSpread: [
      "Pepper steak over rice with steamed broccoli on the side.",
      "Chili garlic crisp at the table for crew who want more heat.",
    ],
    leftovers: [
      "Wrap in flour tortillas with extra sauce for quick lunch wraps.",
      "Stir into fried rice the next day with scrambled eggs.",
    ],
    equipment: ["Wok or large skillet", "Stock pot", "Mixing bowls", "Rice paddle", "Chef knife"],
    nutrition: { calories: 490, protein: 40, carbs: 54, fats: 12, fiber: 3 },
    spiceLevel: "mild",
    cleanupDifficulty: "medium",
  }),

  def({
    slug: "dutch-oven-pot-roast",
    title: "Dutch Oven Pot Roast",
    subtitle: "Chuck roast with carrots and potatoes braised for ten",
    category: "crew_feeders",
    protein: "beef",
    cuisine: "american",
    mealFormat: "braise",
    explorePools: ["beef", "comfort", "hearty", "hall_expansion"],
    hookLine: "Set-it-and-forget-it braise that makes the hall smell like Sunday dinner",
    description:
      "Beef chuck sears in a Dutch oven, then braises low with broth, tomato paste, and aromatics until fork-tender. Carrots and potatoes cook in the same pot for a complete meal.",
    whyCrewsLikeIt:
      "Pot roast is the definition of hall comfort—fork-tender beef, rich gravy, and vegetables in one pot. It holds warm for late eaters and tastes better the next day.",
    mealPrepNotes:
      "Sear roast hard for deep color before braising. Cut vegetables large so they do not turn to mush. Shred or slice roast after resting 15 minutes.",
    stationWorkflow: [
      "Brown roast on all sides in batches if your Dutch oven is tight—color equals flavor.",
      "Deglaze with broth and scrape every brown bit from the bottom.",
      "Nestle vegetables around roast for the last 90 minutes of braising.",
    ],
    prepMinutes: 30,
    cookMinutes: 210,
    difficulty: "easy",
    crewSizeDefault: 10,
    ingredients: [
      ing("boneless chuck roast", "5", { unit: "lb", group: "Main" }),
      ing("Yukon Gold potatoes", "3", { unit: "lb", notes: "quartered", group: "Vegetables" }),
      ing("carrots", "1.5", { unit: "lb", notes: "chunked", group: "Vegetables" }),
      ing("yellow onion", "2", { unit: "whole", notes: "quartered", group: "Aromatics" }),
      ing("garlic cloves", "6", { unit: "cloves", notes: "smashed", group: "Aromatics" }),
      ing("beef broth", "4", { unit: "cups", group: "Braise" }),
      ing("tomato paste", "3", { unit: "tbsp", group: "Braise" }),
      ing("Worcestershire sauce", "2", { unit: "tbsp", group: "Braise" }),
      ing("fresh thyme", "4", { unit: "sprigs", group: "Braise" }),
      ing("all-purpose flour", "3", { unit: "tbsp", notes: "for gravy", group: "Finish" }),
    ],
    steps: [
      step(1, "Sear the roast", "Pat chuck dry and season generously. Sear in oil in a Dutch oven over medium-high heat 3–4 minutes per side until deeply browned. Set aside.", { minutes: 15 }),
      step(2, "Build the braise", "Sauté onion and garlic 3 minutes. Stir in tomato paste and cook 1 minute. Add broth, Worcestershire, and thyme, scraping fond from the bottom.", { minutes: 5 }),
      step(3, "Braise low and slow", "Return roast to pot, cover, and braise at 325°F until fork-tender and internal temp reaches 203°F, about 2.5–3 hours.", { minutes: 165, tempF: 325 }),
      step(4, "Add vegetables", "Nestle potatoes and carrots around roast. Cover and continue braising at 325°F until vegetables pierce easily, about 60–75 minutes.", { minutes: 70, tempF: 325 }),
      step(5, "Rest and serve", "Rest roast 15 minutes. Whisk flour slurry into simmering braising liquid for gravy. Slice or shred beef and serve with vegetables and gravy.", { minutes: 20 }),
    ],
    proTips: [
      "Do not skip the sear—gray pot roast tastes flat no matter how long it braises.",
      "If gravy is thin, simmer uncovered 10 minutes before adding slurry.",
      "Celery stalks added with carrots deepen the savory base cheaply.",
    ],
    tonightSpread: [
      "Sliced pot roast with gravy, potatoes, and carrots on platters.",
      "Crusty bread for soaking up extra gravy at the end of the line.",
    ],
    leftovers: [
      "Shred leftovers for French dip sandwiches with strained gravy.",
      "Dice into a beef and vegetable soup with leftover braising liquid.",
    ],
    equipment: ["Large Dutch oven", "Instant-read thermometer", "Wooden spoon", "Carving knife", "Ladle"],
    nutrition: { calories: 540, protein: 44, carbs: 38, fats: 24, fiber: 5 },
    spiceLevel: "mild",
    cleanupDifficulty: "medium",
  }),

  def({
    slug: "enchilada-beef-skillet",
    title: "Beef Enchilada Skillet",
    subtitle: "Ground beef, tortillas, and enchilada sauce in one pan for ten",
    category: "game_day_recipes",
    protein: "beef",
    cuisine: "mexican",
    mealFormat: "skillet",
    explorePools: ["beef", "game_day", "comfort", "hall_expansion"],
    hookLine: "All the enchilada flavor without rolling twenty tortillas on a busy night",
    description:
      "Ground beef browns with spices and onions, then simmers with torn tortillas and enchilada sauce until bubbly. Top with cheese and bake until melted for a fast Mexican comfort feed.",
    whyCrewsLikeIt:
      "Enchilada flavor without rolling dozens of tortillas. One skillet bakes in the oven while you set up the rest of the meal, and it scoops fast when the tones drop.",
    mealPrepNotes:
      "Use stale tortillas—they absorb sauce better. Brown beef hard for flavor. Assemble in an oven-safe skillet or transfer to hotel pans for baking.",
    stationWorkflow: [
      "Drain excess fat after browning beef or the skillet turns greasy.",
      "Tear tortillas into strips instead of layering whole—easier to portion.",
      "Let rest 5 minutes after baking so slices hold together on the line.",
    ],
    prepMinutes: 20,
    cookMinutes: 35,
    difficulty: "easy",
    crewSizeDefault: 10,
    ingredients: [
      ing("ground beef (85/15)", "3", { unit: "lb", group: "Main" }),
      ing("flour tortillas", "12", { unit: "whole", notes: "torn into strips", group: "Main" }),
      ing("red enchilada sauce", "4", { unit: "cups", group: "Sauce" }),
      ing("yellow onion", "1", { unit: "whole", notes: "diced", group: "Aromatics" }),
      ing("garlic cloves", "4", { unit: "cloves", notes: "minced", group: "Aromatics" }),
      ing("chili powder", "2", { unit: "tbsp", group: "Seasoning" }),
      ing("ground cumin", "1", { unit: "tbsp", group: "Seasoning" }),
      ing("shredded cheddar cheese", "3", { unit: "cups", group: "Topping" }),
      ing("sour cream", "1", { unit: "cup", notes: "for serving", group: "Topping" }),
      ing("fresh cilantro", "0.33", { unit: "cup", notes: "chopped", group: "Finish" }),
    ],
    steps: [
      step(1, "Brown the beef", "Cook ground beef with onion over medium-high heat 8–10 minutes, breaking into crumbles until browned. Drain excess fat. Stir in garlic, chili powder, and cumin 1 minute.", { minutes: 12 }),
      step(2, "Layer the skillet", "Add half the torn tortillas, half the enchilada sauce, and half the beef. Repeat layers, ending with sauce on top.", { minutes: 5 }),
      step(3, "Simmer on stove", "Cover and simmer on low 10 minutes until tortillas soften and absorb sauce.", { minutes: 10 }),
      step(4, "Bake with cheese", "Top with cheddar and bake uncovered at 375°F until cheese melts and bubbles at edges, about 15 minutes.", { minutes: 15, tempF: 375 }),
      step(5, "Garnish and serve", "Rest 5 minutes. Scoop portions with spatula and top with sour cream and cilantro at the line.", { minutes: 5 }),
    ],
    proTips: [
      "Add a can of black beans for stretch and fiber without changing the vibe.",
      "Pickled jalapeños on the side beat cooking spice into the whole batch.",
      "Two skillets bake faster than one deep hotel pan if your oven runs small.",
    ],
    tonightSpread: [
      "Skillet scoops with sour cream, cilantro, and shredded lettuce on the side.",
      "Mexican rice in a hotel pan for crew who want a bigger plate.",
    ],
    leftovers: [
      "Reheat covered at 350°F with extra sauce splashed on top.",
      "Stuff into burritos with scrambled eggs for breakfast shift.",
    ],
    equipment: ["Large oven-safe skillet", "Mixing spoon", "Sheet pan", "Chef knife", "Spatula"],
    nutrition: { calories: 510, protein: 34, carbs: 36, fats: 28, fiber: 4 },
    spiceLevel: "medium",
    cleanupDifficulty: "easy",
  }),

  def({
    slug: "mostaccioli-sausage-bake",
    title: "Baked Mostaccioli with Sausage",
    subtitle: "Cheesy mostaccioli with hot Italian sausage baked for ten",
    category: "crew_feeders",
    protein: "pork",
    cuisine: "italian",
    mealFormat: "pasta",
    explorePools: ["pasta", "comfort", "hall_expansion"],
    hookLine: "Bubbling pasta bake that feeds the hall and survives reheat on night two",
    description:
      "Hot Italian sausage browns with garlic and marinara, tosses with par-cooked ziti and ricotta, then bakes under a mozzarella cap until golden and bubbling.",
    whyCrewsLikeIt:
      "Baked ziti is crew comfort math—cheap pasta, big flavor, one pan to scrub. It slices into portions for fast service and tastes even better as leftovers.",
    mealPrepNotes:
      "Undercook ziti by 2 minutes—it finishes in the oven. Assemble in disposable pans for easy cleanup. Rest 10 minutes before cutting so layers set.",
    stationWorkflow: [
      "Brown sausage in chunks first, then crumble—better texture than raw crumble.",
      "Mix ricotta with egg and parsley so it stays creamy, not grainy.",
      "Cover with foil first half of bake, uncover for golden cheese top.",
    ],
    prepMinutes: 30,
    cookMinutes: 45,
    difficulty: "easy",
    crewSizeDefault: 10,
    ingredients: [
      ing("mostaccioli pasta", "2", { unit: "lb", group: "Main" }),
      ing("hot Italian sausage", "3", { unit: "lb", notes: "casings removed", group: "Main" }),
      ing("marinara sauce", "6", { unit: "cups", group: "Sauce" }),
      ing("whole-milk ricotta", "2", { unit: "cups", group: "Cheese" }),
      ing("shredded mozzarella", "3", { unit: "cups", group: "Cheese" }),
      ing("grated Parmesan", "1", { unit: "cup", group: "Cheese" }),
      ing("egg", "1", { unit: "whole", group: "Cheese" }),
      ing("garlic cloves", "5", { unit: "cloves", notes: "minced", group: "Aromatics" }),
      ing("fresh basil", "0.33", { unit: "cup", notes: "chopped", group: "Finish" }),
      ing("red pepper flakes", "1", { unit: "tsp", group: "Seasoning" }),
    ],
    steps: [
      step(1, "Par-cook the pasta", "Boil ziti in salted water until just shy of al dente, about 8 minutes. Drain and toss with a teaspoon of oil.", { minutes: 10 }),
      step(2, "Brown the sausage", "Cook sausage with garlic over medium-high heat 10 minutes, breaking into crumbles until browned. Stir in marinara and simmer 5 minutes.", { minutes: 15 }),
      step(3, "Mix the cheese layer", "Combine ricotta, half the mozzarella, Parmesan, egg, basil, and red pepper flakes until smooth.", { minutes: 5 }),
      step(4, "Assemble and bake", "Toss ziti with sausage sauce, dollop ricotta mix throughout, top with remaining mozzarella. Cover and bake at 375°F 25 minutes, uncover and bake 15 more until golden.", { minutes: 40, tempF: 375 }),
      step(5, "Rest and portion", "Rest 10 minutes so cheese sets. Cut into ten portions and serve with extra marinara at the line.", { minutes: 10 }),
    ],
    proTips: [
      "Sweet Italian sausage works if your hall does not love heat—swap half and half.",
      "A thin layer of sauce on the pan bottom prevents sticking on cleanup.",
      "Freeze half a pan before baking for an emergency meal on a future shift.",
    ],
    tonightSpread: [
      "Baked ziti squares with garlic bread and simple Caesar salad.",
      "Extra red pepper flakes and grated Parmesan at the table.",
    ],
    leftovers: [
      "Reheat covered at 350°F with splash of water to loosen sauce.",
      "Pan-fry cold squares in oil for crispy-edged ziti bites.",
    ],
    equipment: ["Large stock pot", "Hotel pan or baking dish", "Aluminum foil", "Mixing bowls", "Wooden spoon"],
    nutrition: { calories: 580, protein: 32, carbs: 52, fats: 28, fiber: 4 },
    spiceLevel: "medium",
    cleanupDifficulty: "medium",
  }),

  def({
    slug: "creamy-chicken-penne-alfredo",
    title: "Creamy Chicken Penne Alfredo",
    subtitle: "Grilled chicken strips in garlic-Parmesan cream sauce for ten",
    category: "crew_feeders",
    protein: "chicken",
    cuisine: "italian",
    mealFormat: "pasta",
    explorePools: ["pasta", "chicken", "comfort", "hall_expansion"],
    hookLine: "Restaurant-style alfredo that does not break or glue shut on the hold line",
    description:
      "Chicken breasts season and sear, then slice into strips. Penne tosses with a stabilized garlic-Parmesan cream sauce and finishes with parsley and cracked pepper.",
    whyCrewsLikeIt:
      "Alfredo night feels like a treat without leaving the hall. Chicken adds protein crews expect, and the sauce stays silky when held properly in a warm pan.",
    mealPrepNotes:
      "Warm cream before adding to the pan to reduce curdling risk. Reserve pasta water—it saves a broken sauce. Slice chicken after resting so juices stay in the meat.",
    stationWorkflow: [
      "Sear chicken to 165°F internal, rest, then slice—do not cube before cooking.",
      "Toss pasta with sauce off direct heat so cheese stays smooth.",
      "Hold sauced pasta in a hotel pan at 170°F max with a loose foil tent.",
    ],
    prepMinutes: 25,
    cookMinutes: 30,
    difficulty: "medium",
    crewSizeDefault: 10,
    ingredients: [
      ing("penne pasta", "2", { unit: "lb", group: "Main" }),
      ing("chicken breast", "3", { unit: "lb", group: "Main" }),
      ing("heavy cream", "4", { unit: "cups", group: "Sauce" }),
      ing("unsalted butter", "6", { unit: "tbsp", group: "Sauce" }),
      ing("garlic cloves", "6", { unit: "cloves", notes: "minced", group: "Sauce" }),
      ing("grated Parmesan", "2", { unit: "cups", group: "Sauce" }),
      ing("olive oil", "3", { unit: "tbsp", group: "Chicken" }),
      ing("kosher salt", "2", { unit: "tsp", group: "Seasoning" }),
      ing("black pepper", "1", { unit: "tsp", group: "Seasoning" }),
      ing("fresh parsley", "0.33", { unit: "cup", notes: "chopped", group: "Finish" }),
    ],
    steps: [
      step(1, "Cook the penne", "Boil penne in salted water until al dente, about 10 minutes. Reserve 2 cups pasta water before draining.", { minutes: 12 }),
      step(2, "Sear the chicken", "Season chicken with salt and pepper. Sear in olive oil over medium-high heat 6–7 minutes per side until internal temp reaches 165°F. Rest 5 minutes and slice.", { minutes: 20, tempF: 165 }),
      step(3, "Build the sauce", "Melt butter in a large pot, sauté garlic 1 minute. Pour in warmed cream and simmer gently 3 minutes—do not boil hard.", { minutes: 5 }),
      step(4, "Finish the sauce", "Whisk in Parmesan until melted and smooth. Thin with pasta water if too thick. Season with pepper.", { minutes: 3 }),
      step(5, "Toss and serve", "Add penne and sliced chicken to sauce off heat. Toss until coated. Garnish with parsley and serve immediately or hold warm.", { minutes: 5 }),
    ],
    proTips: [
      "Nutmeg pinch in cream sauce adds depth without changing the classic profile.",
      "Broccoli florets blanched and folded in at the end makes this a full plate.",
      "If sauce tightens on hold, loosen with reserved pasta water, not more cream.",
    ],
    tonightSpread: [
      "Alfredo with garlic bread and a simple mixed green salad.",
      "Extra cracked black pepper and Parmesan at the line.",
    ],
    leftovers: [
      "Reheat gently with pasta water in a covered pan on low heat.",
      "Bake leftovers in a dish topped with mozzarella for quick alfredo bake.",
    ],
    equipment: ["Stock pot", "Large sauté pan", "Instant-read thermometer", "Whisk", "Tongs"],
    nutrition: { calories: 560, protein: 42, carbs: 50, fats: 24, fiber: 3 },
    spiceLevel: "mild",
    cleanupDifficulty: "medium",
  }),

  def({
    slug: "rigatoni-meat-sauce-batch",
    title: "Rigatoni with Meat Sauce",
    subtitle: "Slow-simmered beef and pork ragù over rigatoni for ten",
    category: "crew_feeders",
    protein: "beef",
    cuisine: "italian",
    mealFormat: "pasta",
    explorePools: ["pasta", "beef", "comfort", "hall_expansion"],
    hookLine: "Sunday sauce energy on a weeknight timeline with hall-sized portions",
    description:
      "Ground beef and pork simmer with onion, garlic, and crushed tomatoes until thick and rich. Toss with rigatoni and finish with Parmesan for a proper Italian-American hall feed.",
    whyCrewsLikeIt:
      "Meat sauce is the pasta baseline everyone recognizes. It scales cheap, simmers while you handle other duties, and holds hot in a hotel pan for late eaters.",
    mealPrepNotes:
      "Simmer sauce at least 45 minutes for depth—longer is better. Salt pasta water heavily. Sauce and pasta can stay separate until service if holding.",
    stationWorkflow: [
      "Brown meats separately before combining for better texture.",
      "Simmer uncovered last 15 minutes so sauce thickens to coat pasta.",
      "Toss pasta with a ladle of sauce before plating so strands do not stick.",
    ],
    prepMinutes: 20,
    cookMinutes: 60,
    difficulty: "easy",
    crewSizeDefault: 10,
    ingredients: [
      ing("rigatoni pasta", "2", { unit: "lb", group: "Main" }),
      ing("ground beef (80/20)", "2", { unit: "lb", group: "Sauce" }),
      ing("ground pork", "1", { unit: "lb", group: "Sauce" }),
      ing("crushed tomatoes", "2", { unit: "cans", notes: "28 oz each", group: "Sauce" }),
      ing("tomato paste", "3", { unit: "tbsp", group: "Sauce" }),
      ing("yellow onion", "1", { unit: "whole", notes: "finely diced", group: "Aromatics" }),
      ing("garlic cloves", "6", { unit: "cloves", notes: "minced", group: "Aromatics" }),
      ing("dry red wine", "1", { unit: "cup", group: "Sauce" }),
      ing("dried oregano", "2", { unit: "tsp", group: "Seasoning" }),
      ing("grated Parmesan", "1", { unit: "cup", notes: "for serving", group: "Finish" }),
    ],
    steps: [
      step(1, "Brown the meats", "Cook beef and pork with onion over medium-high heat 12–15 minutes, breaking into crumbles until well browned. Drain excess fat.", { minutes: 15 }),
      step(2, "Build the sauce", "Add garlic and tomato paste, cook 2 minutes. Pour in wine and simmer until mostly reduced, about 4 minutes.", { minutes: 6 }),
      step(3, "Simmer low", "Add crushed tomatoes and oregano. Simmer uncovered 40–45 minutes, stirring occasionally, until sauce thickens and oil pools at edges.", { minutes: 42 }),
      step(4, "Cook rigatoni", "Boil rigatoni in salted water until al dente, about 11 minutes. Drain and toss with a cup of sauce.", { minutes: 12 }),
      step(5, "Serve family-style", "Portion pasta into bowls or hotel pan, top with remaining sauce and Parmesan. Serve with extra cheese at the line.", { minutes: 5 }),
    ],
    proTips: [
      "A parmesan rind simmered in the sauce adds savory depth—fish it out before serving.",
      "Red pepper flake pinch in the browning stage wakes up canned tomatoes.",
      "Double the batch and freeze half sauce for an emergency pasta night.",
    ],
    tonightSpread: [
      "Rigatoni with meat sauce, garlic bread, and simple green salad.",
      "Roasted zucchini on the side for crew who want vegetables.",
    ],
    leftovers: [
      "Bake into a pasta casserole with extra mozzarella on top.",
      "Stuff into hoagie rolls with melted provolone for meatball-less subs.",
    ],
    equipment: ["Large Dutch oven", "Stock pot", "Wooden spoon", "Ladle", "Colander"],
    nutrition: { calories: 540, protein: 36, carbs: 56, fats: 20, fiber: 5 },
    spiceLevel: "mild",
    cleanupDifficulty: "medium",
  }),

  def({
    slug: "station-cobb-salad",
    title: "Station Cobb Salad",
    subtitle: "Chopped salad with chicken, bacon, egg, and blue cheese for ten",
    category: "game_day_recipes",
    protein: "chicken",
    cuisine: "american",
    mealFormat: "salad",
    explorePools: ["salad", "game_day", "chicken", "hall_expansion"],
    hookLine: "A full dinner salad that actually fills firefighters up",
    description:
      "Grilled chicken, crisp bacon, hard-boiled eggs, avocado, and blue cheese top chopped romaine in rows for a classic Cobb spread. Crews build bowls at the line with ranch or vinaigrette.",
    whyCrewsLikeIt:
      "Salad night does not have to feel like punishment when there is bacon, egg, and grilled chicken in the mix. The row presentation looks sharp for visiting crews and photos.",
    mealPrepNotes:
      "Cook chicken and bacon ahead. Hard-boil eggs ice-bath immediately for clean peels. Keep avocado sliced just before service to prevent browning.",
    stationWorkflow: [
      "Chop romaine dry—wet lettuce kills the crunch in ten minutes.",
      "Arrange toppings in rows on a long platter for classic Cobb presentation.",
      "Offer dressing on the side so salad stays crisp on the hold table.",
    ],
    prepMinutes: 40,
    cookMinutes: 25,
    difficulty: "easy",
    crewSizeDefault: 10,
    ingredients: [
      ing("romaine lettuce hearts", "5", { unit: "heads", notes: "chopped", group: "Base" }),
      ing("chicken breast", "2.5", { unit: "lb", group: "Protein" }),
      ing("thick-cut bacon", "1", { unit: "lb", group: "Protein" }),
      ing("hard-boiled eggs", "8", { unit: "whole", notes: "quartered", group: "Protein" }),
      ing("ripe avocados", "3", { unit: "whole", notes: "sliced", group: "Vegetables" }),
      ing("cherry tomatoes", "2", { unit: "cups", notes: "halved", group: "Vegetables" }),
      ing("crumbled blue cheese", "1", { unit: "cup", group: "Cheese" }),
      ing("red wine vinegar", "0.25", { unit: "cup", group: "Dressing" }),
      ing("olive oil", "0.5", { unit: "cup", group: "Dressing" }),
      ing("Dijon mustard", "1", { unit: "tbsp", group: "Dressing" }),
    ],
    steps: [
      step(1, "Cook the chicken", "Season chicken breasts and grill or sear over medium-high heat 6–7 minutes per side until internal temp reaches 165°F. Rest and slice.", { minutes: 18, tempF: 165 }),
      step(2, "Crisp the bacon", "Bake bacon on sheet pans at 400°F until crisp, about 15 minutes. Drain on paper towels and crumble.", { minutes: 15, tempF: 400 }),
      step(3, "Prep the components", "Hard-boil eggs 10 minutes, ice bath, peel and quarter. Chop romaine and wash tomatoes. Slice avocados just before assembly.", { minutes: 20 }),
      step(4, "Make the dressing", "Whisk vinegar, Dijon, salt, and pepper, then stream in olive oil until emulsified.", { minutes: 5 }),
      step(5, "Assemble and serve", "Spread romaine on platters. Arrange chicken, bacon, eggs, avocado, tomatoes, and blue cheese in rows. Serve dressing on the side.", { minutes: 10 }),
    ],
    proTips: [
      "Rotisserie chicken works in a pinch if grill time is tight—season with extra pepper.",
      "Red onion slices add bite—soak in cold water 5 minutes if raw onion runs strong.",
      "Grilled corn kernels mixed in turn this into a summer station favorite.",
    ],
    tonightSpread: [
      "Cobb platters with dressing choice and warm dinner rolls.",
      "Fresh fruit bowl for crew who want something sweet after the meal.",
    ],
    leftovers: [
      "Pack components separately—do not dress until eating or salad turns soggy.",
      "Chop leftovers into a wrap with ranch for quick lunch.",
    ],
    equipment: ["Sheet pans", "Grill or cast iron", "Instant-read thermometer", "Large platters", "Mixing bowls"],
    nutrition: { calories: 420, protein: 38, carbs: 12, fats: 26, fiber: 6 },
    spiceLevel: "mild",
    cleanupDifficulty: "easy",
  }),

  def({
    slug: "warm-spinach-chicken-salad",
    title: "Warm Spinach Chicken Salad",
    subtitle: "Sliced chicken over wilted spinach with bacon vinaigrette for ten",
    category: "game_day_recipes",
    protein: "chicken",
    cuisine: "american",
    mealFormat: "salad",
    explorePools: ["salad", "healthy", "chicken", "hall_expansion"],
    hookLine: "Hot bacon dressing turns salad into a meal crews actually finish",
    description:
      "Chicken thighs roast and slice, then serve over lightly wilted spinach with warm bacon-mustard vinaigrette, sliced mushrooms, and hard-boiled egg. Hearty enough for a cold-night shift.",
    whyCrewsLikeIt:
      "Warm salad sounds fancy but it is just smart hall cooking—hot dressing wilts spinach slightly and makes the plate feel like dinner, not diet food.",
    mealPrepNotes:
      "Render bacon slowly for best vinaigrette fat. Dress spinach lightly at service—too much and it collapses. Mushrooms sauté just before plating.",
    stationWorkflow: [
      "Roast chicken thighs to 165°F while prep other components.",
      "Sauté mushrooms in bacon fat until golden before building salads.",
      "Pour warm dressing over spinach right before serving, not earlier.",
    ],
    prepMinutes: 25,
    cookMinutes: 35,
    difficulty: "easy",
    crewSizeDefault: 8,
    ingredients: [
      ing("boneless chicken thighs", "3", { unit: "lb", group: "Main" }),
      ing("baby spinach", "2", { unit: "lb", group: "Base" }),
      ing("thick-cut bacon", "12", { unit: "slices", group: "Dressing" }),
      ing("cremini mushrooms", "1", { unit: "lb", notes: "sliced", group: "Vegetables" }),
      ing("hard-boiled eggs", "6", { unit: "whole", notes: "quartered", group: "Protein" }),
      ing("red wine vinegar", "0.33", { unit: "cup", group: "Dressing" }),
      ing("Dijon mustard", "2", { unit: "tbsp", group: "Dressing" }),
      ing("shallot", "1", { unit: "whole", notes: "minced", group: "Dressing" }),
      ing("olive oil", "3", { unit: "tbsp", group: "Chicken" }),
      ing("kosher salt", "1", { unit: "tbsp", group: "Seasoning" }),
    ],
    steps: [
      step(1, "Roast the chicken", "Season thighs with salt and olive oil. Roast at 425°F on a sheet pan 25–30 minutes until internal temp reaches 165°F. Rest and slice.", { minutes: 30, tempF: 425 }),
      step(2, "Cook bacon and mushrooms", "Render bacon in a skillet until crisp. Remove and chop. Sauté mushrooms in bacon fat 6–8 minutes until golden. Set aside.", { minutes: 15 }),
      step(3, "Build warm vinaigrette", "Whisk vinegar, mustard, and shallot into warm bacon fat off heat. Crumble half the bacon into the dressing.", { minutes: 5 }),
      step(4, "Wilt the spinach", "Toss spinach in a large bowl with warm dressing until leaves just wilt—about 30 seconds of gentle tossing.", { minutes: 2 }),
      step(5, "Plate and serve", "Top wilted spinach with sliced chicken, mushrooms, egg quarters, and remaining bacon crumbles. Serve immediately.", { minutes: 5 }),
    ],
    proTips: [
      "Baby spinach handles warm dressing better than mature spinach leaves.",
      "Add sliced red grapes for sweet contrast if your crew likes fruit in salad.",
      "This does not hold—plate to order or assemble in small batches.",
    ],
    tonightSpread: [
      "Warm spinach salad plated with crusty rolls on the side.",
      "Roasted sweet potato wedges for crew who want more carbs.",
    ],
    leftovers: [
      "Slice cold chicken for sandwiches with leftover bacon.",
      "Use wilted spinach in a frittata the next morning.",
    ],
    equipment: ["Sheet pan", "Large skillet", "Mixing bowls", "Instant-read thermometer", "Whisk"],
    nutrition: { calories: 380, protein: 34, carbs: 8, fats: 24, fiber: 4 },
    spiceLevel: "mild",
    cleanupDifficulty: "easy",
  }),

  def({
    slug: "hall-chicken-noodle-soup",
    title: "Hall Chicken Noodle Soup",
    subtitle: "Classic chicken noodle soup with egg noodles for ten",
    category: "crew_feeders",
    protein: "chicken",
    cuisine: "american",
    mealFormat: "soup",
    explorePools: ["soup", "comfort", "chicken", "hall_expansion"],
    hookLine: "The pot you want when half the crew is coming off a cold-weather call",
    description:
      "Chicken thighs simmer with mirepoix and herbs until tender, then shred into a rich broth with egg noodles and carrots. Simple, restorative, and built for the biggest stock pot in the hall.",
    whyCrewsLikeIt:
      "Chicken noodle soup is the universal reset meal. It reheats perfectly, fills the hall with comfort smell, and nobody complains when they are tired or under the weather.",
    mealPrepNotes:
      "Poach thighs gently—boiling toughens meat. Cook noodles separately and add at service so they do not bloat in the pot. Skim fat from broth for cleaner flavor.",
    stationWorkflow: [
      "Simmer broth low—rolling boil makes cloudy, greasy soup.",
      "Shred chicken with two forks while still warm for fast prep.",
      "Hold soup at 165°F minimum on the stove or in a warmer.",
    ],
    prepMinutes: 25,
    cookMinutes: 60,
    difficulty: "easy",
    crewSizeDefault: 10,
    ingredients: [
      ing("bone-in chicken thighs", "4", { unit: "lb", group: "Main" }),
      ing("wide egg noodles", "1", { unit: "lb", group: "Main" }),
      ing("yellow onion", "1", { unit: "whole", notes: "diced", group: "Aromatics" }),
      ing("carrots", "4", { unit: "whole", notes: "sliced", group: "Vegetables" }),
      ing("celery stalks", "4", { unit: "stalks", notes: "sliced", group: "Vegetables" }),
      ing("garlic cloves", "4", { unit: "cloves", notes: "minced", group: "Aromatics" }),
      ing("chicken broth", "8", { unit: "cups", group: "Broth" }),
      ing("fresh thyme", "4", { unit: "sprigs", group: "Herbs" }),
      ing("bay leaves", "2", { unit: "whole", group: "Herbs" }),
      ing("fresh parsley", "0.33", { unit: "cup", notes: "chopped", group: "Finish" }),
    ],
    steps: [
      step(1, "Poach the chicken", "Simmer chicken thighs in broth with onion, bay leaves, and thyme 30–35 minutes until internal temp reaches 165°F and meat pulls easily from bone.", { minutes: 35, tempF: 165 }),
      step(2, "Shred and strain", "Remove chicken, shred meat, discard skin and bones. Strain broth if cloudy, return to pot, and skim excess fat.", { minutes: 15 }),
      step(3, "Build the soup base", "Add carrots, celery, and garlic to broth. Simmer 15 minutes until vegetables tender.", { minutes: 15 }),
      step(4, "Cook noodles separately", "Boil egg noodles in salted water until al dente, about 7 minutes. Drain and toss with a little oil.", { minutes: 8 }),
      step(5, "Ladle and garnish", "Return shredded chicken to soup. Season with salt and pepper. Portion noodles into bowls, ladle hot soup over, and garnish with parsley.", { minutes: 5 }),
    ],
    proTips: [
      "A splash of lemon juice at service brightens heavy broth instantly.",
      "Turmeric pinch adds golden color without changing the classic flavor.",
      "Freeze half the shredded chicken and broth base separately for fast future soup.",
    ],
    tonightSpread: [
      "Soup with saltine crackers and buttered bread on the side.",
      "Simple green salad for crew who want crunch alongside the bowl.",
    ],
    leftovers: [
      "Store noodles separate from broth or they absorb everything overnight.",
      "Reduce broth and add cream for a quick chicken pot pie filling.",
    ],
    equipment: ["Large stock pot", "Colander", "Ladle", "Tongs", "Cutting board"],
    nutrition: { calories: 340, protein: 28, carbs: 36, fats: 10, fiber: 3 },
    spiceLevel: "mild",
    cleanupDifficulty: "easy",
  }),

  def({
    slug: "green-chile-chicken-stew",
    title: "Green Chile Chicken Stew",
    subtitle: "Tomatillo and green chile stew with white beans for ten",
    category: "crew_feeders",
    protein: "chicken",
    cuisine: "southwestern",
    mealFormat: "soup",
    explorePools: ["soup", "chicken", "hearty", "hall_expansion"],
    hookLine: "Southwestern stew with real green chile heat you can dial up or down",
    description:
      "Chicken thighs braise with tomatillos, green chiles, and white beans until tender and tangy. Cumin and cilantro finish the pot for a bright, warming stew that is not standard chili.",
    whyCrewsLikeIt:
      "Green chile stew feels different from the usual tomato chili rotation. It is hearty, tangy, and the heat level is easy to control for mixed spice tolerances on the crew.",
    mealPrepNotes:
      "Roast fresh tomatillos under broiler for depth if using raw. Canned green chiles work fine for speed. Shred chicken in the pot after braising.",
    stationWorkflow: [
      "Char tomatillos and onions under broiler 5 minutes for smoky base flavor.",
      "Simmer stew uncovered last 15 minutes to thicken slightly.",
      "Offer lime wedges and hot sauce at the line, not cooked into the whole pot.",
    ],
    prepMinutes: 30,
    cookMinutes: 50,
    difficulty: "medium",
    crewSizeDefault: 10,
    ingredients: [
      ing("bone-in chicken thighs", "4", { unit: "lb", group: "Main" }),
      ing("tomatillos", "2", { unit: "lb", notes: "husked and halved", group: "Base" }),
      ing("canned green chiles", "2", { unit: "cans", notes: "4 oz each", group: "Base" }),
      ing("cannellini beans", "2", { unit: "cans", notes: "15 oz each, drained", group: "Base" }),
      ing("yellow onion", "1", { unit: "whole", notes: "diced", group: "Aromatics" }),
      ing("garlic cloves", "5", { unit: "cloves", notes: "minced", group: "Aromatics" }),
      ing("ground cumin", "2", { unit: "tsp", group: "Seasoning" }),
      ing("chicken broth", "6", { unit: "cups", group: "Liquid" }),
      ing("fresh cilantro", "0.5", { unit: "cup", notes: "chopped", group: "Finish" }),
      ing("lime", "3", { unit: "whole", notes: "wedged", group: "Finish" }),
    ],
    steps: [
      step(1, "Char the tomatillos", "Broil tomatillos and onion at 500°F 5–7 minutes until blistered. Blend with green chiles and half the garlic until smooth.", { minutes: 10, tempF: 500 }),
      step(2, "Sear the chicken", "Season chicken thighs and sear in oil 4 minutes per side until golden. Set aside.", { minutes: 10 }),
      step(3, "Simmer the stew", "Sauté remaining garlic and cumin 1 minute. Add tomatillo puree and broth. Return chicken and simmer 30 minutes until internal temp reaches 165°F.", { minutes: 30, tempF: 165 }),
      step(4, "Shred and finish", "Remove chicken, shred meat, discard bones. Return meat to pot with beans and simmer 10 minutes. Stir in half the cilantro.", { minutes: 12 }),
      step(5, "Serve with garnishes", "Ladle into bowls and top with remaining cilantro and lime wedges. Offer hot sauce at the line.", { minutes: 5 }),
    ],
    proTips: [
      "Roasted poblano peppers diced in add smoky depth beyond canned chiles.",
      "Corn kernels stirred in at the end make this feel like a complete bowl.",
      "This thickens overnight—thin reheats with broth, not water.",
    ],
    tonightSpread: [
      "Stew with warm flour tortillas for dunking.",
      "Shredded Monterey Jack and sour cream at the line.",
    ],
    leftovers: [
      "Layer over rice with fried egg for a green chile bowl breakfast.",
      "Use as enchilada filling with extra cheese and sauce.",
    ],
    equipment: ["Large Dutch oven", "Blender", "Instant-read thermometer", "Ladle", "Sheet pan"],
    nutrition: { calories: 360, protein: 32, carbs: 34, fats: 12, fiber: 8 },
    spiceLevel: "medium",
    cleanupDifficulty: "medium",
  }),

  def({
    slug: "ginger-soy-chicken-rice-bowls",
    title: "Ginger Soy Chicken Rice Bowls",
    subtitle: "Grilled chicken over rice with steamed broccoli for ten",
    category: "crew_feeders",
    protein: "chicken",
    cuisine: "asian-american",
    mealFormat: "bowl",
    explorePools: ["bowl", "healthy", "chicken", "hall_expansion"],
    hookLine: "Balanced bowls with real protein portions—not sad desk-lunch energy",
    description:
      "Chicken thighs marinate in ginger-soy, grill until charred, and serve over steamed rice with broccoli and sesame drizzle. Clean flavors, filling portions, fast assembly.",
    whyCrewsLikeIt:
      "Bowls line up fast when components are ready. This hits the healthy night brief without tiny portions or weird ingredients nobody recognizes.",
    mealPrepNotes:
      "Marinate chicken up to 12 hours. Steam broccoli just before service. Keep sauce separate until plating so rice does not get soggy.",
    stationWorkflow: [
      "Grill chicken to 165°F internal over medium-high heat for char marks.",
      "Steam broccoli until bright green and tender-crisp, not army green.",
      "Build bowls: rice, broccoli, sliced chicken, sauce, sesame seeds.",
    ],
    prepMinutes: 25,
    cookMinutes: 25,
    difficulty: "easy",
    crewSizeDefault: 10,
    ingredients: [
      ing("boneless chicken thighs", "4", { unit: "lb", group: "Main" }),
      ing("jasmine rice", "3", { unit: "cups", notes: "uncooked", group: "Base" }),
      ing("broccoli florets", "2", { unit: "lb", group: "Vegetables" }),
      ing("low-sodium soy sauce", "0.5", { unit: "cup", group: "Marinade" }),
      ing("fresh ginger", "3", { unit: "tbsp", notes: "grated", group: "Marinade" }),
      ing("garlic cloves", "4", { unit: "cloves", notes: "minced", group: "Marinade" }),
      ing("honey", "3", { unit: "tbsp", group: "Marinade" }),
      ing("rice vinegar", "2", { unit: "tbsp", group: "Sauce" }),
      ing("sesame oil", "2", { unit: "tbsp", group: "Finish" }),
      ing("sesame seeds", "3", { unit: "tbsp", group: "Finish" }),
    ],
    steps: [
      step(1, "Marinate the chicken", "Whisk soy sauce, ginger, garlic, and honey. Coat chicken thighs and marinate at least 30 minutes in the fridge.", { minutes: 10 }),
      step(2, "Cook the rice", "Rinse jasmine rice and cook with 5.5 cups water—bring to boil, cover, simmer 18 minutes, rest 5 minutes off heat.", { minutes: 25 }),
      step(3, "Grill the chicken", "Grill thighs over medium-high heat 5–6 minutes per side until charred and internal temp reaches 165°F. Rest and slice.", { minutes: 15, tempF: 165 }),
      step(4, "Steam the broccoli", "Steam broccoli 4–5 minutes until bright green and tender-crisp. Season lightly with salt.", { minutes: 5 }),
      step(5, "Assemble bowls", "Portion rice and broccoli into bowls. Top with sliced chicken, drizzle remaining marinade simmered 2 minutes, sesame oil, and sesame seeds.", { minutes: 10 }),
    ],
    proTips: [
      "Simmer used marinade 3 minutes after chicken comes out—safe glaze for bowls.",
      "Sriracha mayo on the side beats mixing spice into the whole batch.",
      "Swap half broccoli for snap peas if you want more color on the line.",
    ],
    tonightSpread: [
      "Bowls with lime wedges and extra soy on the side.",
      "Miso soup cups for crew who want something warm to start.",
    ],
    leftovers: [
      "Chop into fried rice with leftover chicken and broccoli.",
      "Wrap in lettuce cups for a lighter second-day lunch.",
    ],
    equipment: ["Grill or grill pan", "Rice cooker or pot", "Steamer basket", "Instant-read thermometer", "Mixing bowls"],
    nutrition: { calories: 420, protein: 36, carbs: 48, fats: 10, fiber: 4 },
    spiceLevel: "mild",
    cleanupDifficulty: "easy",
  }),

  def({
    slug: "mediterranean-chicken-farro-bowls",
    title: "Mediterranean Chicken Farro Bowls",
    subtitle: "Herb chicken with farro, cucumber, and hummus for ten",
    category: "crew_feeders",
    protein: "chicken",
    cuisine: "mediterranean",
    mealFormat: "bowl",
    explorePools: ["bowl", "healthy", "chicken", "hall_expansion"],
    hookLine: "Mediterranean bowls that feel fresh but still deliver serious protein",
    description:
      "Lemon-oregano chicken roasts and slices over chewy farro with cucumber, tomato, olives, and hummus. A bright, filling bowl that breaks up heavy comfort-food rotations.",
    whyCrewsLikeIt:
      "Farro is nutty, filling, and different from the usual rice line-up. Mediterranean flavors feel light but the portions are hall-sized, not spa-sized.",
    mealPrepNotes:
      "Cook farro ahead—it holds well. Dice vegetables uniform. Chicken can roast while farro simmers to save time.",
    stationWorkflow: [
      "Roast chicken at 425°F until 165°F internal for crisp exterior.",
      "Drain farro well so bowls are not watery.",
      "Set up bowl line: farro, chicken, veg, hummus, drizzle.",
    ],
    prepMinutes: 30,
    cookMinutes: 40,
    difficulty: "easy",
    crewSizeDefault: 10,
    ingredients: [
      ing("chicken breast", "3.5", { unit: "lb", group: "Main" }),
      ing("farro", "3", { unit: "cups", notes: "dry", group: "Base" }),
      ing("English cucumber", "2", { unit: "whole", notes: "diced", group: "Vegetables" }),
      ing("cherry tomatoes", "2", { unit: "cups", notes: "halved", group: "Vegetables" }),
      ing("kalamata olives", "1", { unit: "cup", notes: "pitted, halved", group: "Vegetables" }),
      ing("hummus", "2", { unit: "cups", group: "Topping" }),
      ing("lemon", "2", { unit: "whole", notes: "juiced", group: "Marinade" }),
      ing("dried oregano", "2", { unit: "tbsp", group: "Marinade" }),
      ing("olive oil", "0.33", { unit: "cup", group: "Dressing" }),
      ing("feta cheese", "1.5", { unit: "cups", notes: "crumbled", group: "Finish" }),
    ],
    steps: [
      step(1, "Cook the farro", "Simmer farro in salted water 25–30 minutes until chewy-tender. Drain and toss with 2 tablespoons olive oil.", { minutes: 30 }),
      step(2, "Roast the chicken", "Coat chicken with lemon juice, oregano, salt, pepper, and 2 tablespoons olive oil. Roast at 425°F 22–25 minutes until internal temp reaches 165°F. Slice.", { minutes: 25, tempF: 425 }),
      step(3, "Prep the vegetables", "Combine cucumber, tomatoes, and olives. Dress lightly with remaining olive oil and lemon juice.", { minutes: 10 }),
      step(4, "Build the bowl line", "Set out farro, sliced chicken, vegetable mix, hummus, and feta in labeled containers.", { minutes: 5 }),
      step(5, "Assemble and serve", "Portion farro into bowls, top with chicken, vegetables, dollop of hummus, and crumbled feta.", { minutes: 8 }),
    ],
    proTips: [
      "Pearl farro cooks faster than whole—check package time and adjust.",
      "Pickled red onions add punch without extra prep mid-service.",
      "Grilled zucchini strips use the same oven time as chicken.",
    ],
    tonightSpread: [
      "Bowls with warm pita wedges and extra lemon wedges.",
      "Simple tabbouleh on the side if you want more veg volume cheaply.",
    ],
    leftovers: [
      "Stuff into pita with extra hummus for quick lunches.",
      "Farro and veg mix makes a cold grain salad the next day.",
    ],
    equipment: ["Sheet pan", "Stock pot", "Instant-read thermometer", "Mixing bowls", "Serving containers"],
    nutrition: { calories: 450, protein: 40, carbs: 44, fats: 14, fiber: 8 },
    spiceLevel: "mild",
    cleanupDifficulty: "easy",
  }),

  def({
    slug: "kielbasa-cabbage-potato-skillet",
    title: "Kielbasa Cabbage Potato Skillet",
    subtitle: "One-pan smoked sausage with cabbage and potatoes for ten",
    category: "crew_feeders",
    protein: "pork",
    cuisine: "polish-american",
    mealFormat: "skillet",
    explorePools: ["one_pot", "comfort", "hall_expansion"],
    hookLine: "Rookie-proof one pan—brown sausage, add veg, cover, done",
    description:
      "Kielbasa slices sear with onion, then simmer with cabbage and potatoes until tender. Mustard and caraway finish the pan for a simple, filling one-pot meal.",
    whyCrewsLikeIt:
      "This is the meal you teach a probie first—hard to mess up, one pan, and everyone recognizes sausage and potatoes. Perfect when the crew is short on cooks.",
    mealPrepNotes:
      "Slice kielbasa and potatoes uniform for even cooking. Use a lid to steam cabbage—dry pan burns before veg softens. Caraway is optional but classic.",
    stationWorkflow: [
      "Brown kielbasa first for flavor, then set aside while potatoes start.",
      "Layer cabbage on top and cover—steam does the work.",
      "Taste and adjust salt after sausage goes back in—it carries salt already.",
    ],
    prepMinutes: 20,
    cookMinutes: 35,
    difficulty: "easy",
    crewSizeDefault: 10,
    ingredients: [
      ing("smoked kielbasa", "3", { unit: "lb", notes: "sliced into coins", group: "Main" }),
      ing("Yukon Gold potatoes", "3", { unit: "lb", notes: "quartered", group: "Main" }),
      ing("green cabbage", "1", { unit: "head", notes: "cut into wedges", group: "Vegetables" }),
      ing("yellow onion", "1", { unit: "whole", notes: "sliced", group: "Vegetables" }),
      ing("garlic cloves", "4", { unit: "cloves", notes: "minced", group: "Aromatics" }),
      ing("chicken broth", "1.5", { unit: "cups", group: "Liquid" }),
      ing("apple cider vinegar", "2", { unit: "tbsp", group: "Seasoning" }),
      ing("Dijon mustard", "2", { unit: "tbsp", group: "Seasoning" }),
      ing("caraway seeds", "1", { unit: "tsp", group: "Seasoning" }),
      ing("black pepper", "1", { unit: "tsp", group: "Seasoning" }),
    ],
    steps: [
      step(1, "Brown the kielbasa", "Sear kielbasa slices in a large skillet over medium-high heat 4–5 minutes until edges caramelize. Set aside.", { minutes: 6 }),
      step(2, "Start the potatoes", "Add onion and potatoes to the pan with a splash of broth. Cover and cook 12 minutes, stirring once, until potatoes begin to soften.", { minutes: 12 }),
      step(3, "Add cabbage and steam", "Nestle cabbage wedges into the pan, add remaining broth, cover, and cook 15 minutes until cabbage wilts and potatoes pierce easily.", { minutes: 15 }),
      step(4, "Combine and season", "Return kielbasa, stir in garlic, mustard, vinegar, caraway, and pepper. Cook uncovered 5 minutes until liquid mostly reduces.", { minutes: 5 }),
      step(5, "Serve from the skillet", "Taste for salt. Serve straight from the skillet or transfer to a hotel pan for buffet line.", { minutes: 3 }),
    ],
    proTips: [
      "Andouille or smoked turkey sausage works if kielbasa is not in the freezer.",
      "A splash of beer instead of half the broth adds depth without complexity.",
      "This reheats well—add broth when warming so potatoes do not dry out.",
    ],
    tonightSpread: [
      "Skillet served with rye bread and whole-grain mustard.",
      "Quick vinegar slaw if you want a raw crunch side.",
    ],
    leftovers: [
      "Chop and fry into a breakfast hash with eggs.",
      "Wrap in tortillas with sauerkraut for quick kielbasa tacos.",
    ],
    equipment: ["Large skillet with lid", "Chef knife", "Wooden spoon", "Measuring cups", "Hotel pan"],
    nutrition: { calories: 480, protein: 22, carbs: 38, fats: 28, fiber: 6 },
    spiceLevel: "mild",
    cleanupDifficulty: "easy",
  }),

  def({
    slug: "cheesy-chicken-broccoli-rice",
    title: "Cheesy Chicken Broccoli Rice",
    subtitle: "One-pot cheddar chicken and rice for ten",
    category: "crew_feeders",
    protein: "chicken",
    cuisine: "american",
    mealFormat: "one_pot",
    explorePools: ["one_pot", "comfort", "chicken", "hall_expansion"],
    hookLine: "The first one-pot most halls learn—chicken, rice, broccoli, cheese, done",
    description:
      "Chicken breast cubes cook with rice and broccoli in one pot, then finish with sharp cheddar until creamy and cohesive. Simple seasoning, big portions, minimal dishes.",
    whyCrewsLikeIt:
      "Every hall has a version of this dish because it works. One pot, familiar flavors, and even rookies can follow the steps without burning the house down.",
    mealPrepNotes:
      "Cut chicken uniform so it cooks with the rice. Add broccoli in the last 8 minutes so it stays green. Stir cheese off heat for smoothest melt.",
    stationWorkflow: [
      "Sear chicken lightly before adding rice and broth for better flavor.",
      "Use exact broth ratio—too much makes mush, too little scorches.",
      "Cover tightly during simmer—lifting lid drops temperature and extends cook time.",
    ],
    prepMinutes: 15,
    cookMinutes: 35,
    difficulty: "easy",
    crewSizeDefault: 10,
    ingredients: [
      ing("boneless chicken breast", "3", { unit: "lb", notes: "cubed", group: "Main" }),
      ing("long-grain white rice", "3", { unit: "cups", group: "Main" }),
      ing("broccoli florets", "2", { unit: "lb", group: "Vegetables" }),
      ing("chicken broth", "5.5", { unit: "cups", group: "Liquid" }),
      ing("sharp cheddar cheese", "2", { unit: "cups", notes: "shredded", group: "Cheese" }),
      ing("yellow onion", "1", { unit: "whole", notes: "diced", group: "Aromatics" }),
      ing("garlic powder", "1", { unit: "tsp", group: "Seasoning" }),
      ing("onion powder", "1", { unit: "tsp", group: "Seasoning" }),
      ing("unsalted butter", "3", { unit: "tbsp", group: "Finish" }),
      ing("kosher salt", "2", { unit: "tsp", group: "Seasoning" }),
    ],
    steps: [
      step(1, "Sear the chicken", "Season cubed chicken with salt, garlic powder, and onion powder. Sear in butter 4–5 minutes until lightly golden—not fully cooked through.", { minutes: 6 }),
      step(2, "Add rice and broth", "Stir in rice and onion, toast 1 minute, then pour in broth. Bring to boil, cover, reduce to low simmer.", { minutes: 5 }),
      step(3, "Simmer covered", "Cook covered 18 minutes without lifting lid until rice absorbs liquid and chicken reaches 165°F internal.", { minutes: 18, tempF: 165 }),
      step(4, "Steam the broccoli", "Nestle broccoli on top, cover, and cook 8 more minutes until broccoli tender and rice fluffy.", { minutes: 8 }),
      step(5, "Finish with cheese", "Remove from heat, stir in cheddar and remaining butter until melted and creamy. Rest 5 minutes before serving.", { minutes: 5 }),
    ],
    proTips: [
      "Rotisserie chicken shredded in at the end skips the sear step on busy nights.",
      "A teaspoon of mustard powder in the cheese adds depth without tasting like mustard.",
      "Hot sauce on the table beats cooking spice into the whole pot.",
    ],
    tonightSpread: [
      "One-pot scoops with dinner rolls and simple mixed greens.",
      "Extra shredded cheese at the line for crew who want it cheesier.",
    ],
    leftovers: [
      "Reheat with splash of broth in a covered pan on low.",
      "Press cold leftovers into patties and pan-fry for crispy rice cakes.",
    ],
    equipment: ["Large pot with tight lid", "Instant-read thermometer", "Wooden spoon", "Chef knife", "Measuring cups"],
    nutrition: { calories: 460, protein: 38, carbs: 48, fats: 14, fiber: 4 },
    spiceLevel: "mild",
    cleanupDifficulty: "easy",
  }),

  def({
    slug: "sheet-pan-meatball-marinara",
    title: "Sheet Pan Meatball Marinara Feed",
    subtitle: "Oven-baked beef meatballs with marinara for ten",
    category: "crew_feeders",
    protein: "beef",
    cuisine: "italian",
    mealFormat: "sheet_pan",
    explorePools: ["beef", "hearty", "crew_feed", "hall_expansion"],
    hookLine: "Sixty meatballs on two sheet pans—maximum feed, minimum babysitting",
    description:
      "Beef meatballs mix fast, bake on sheet pans until browned, then simmer in marinara until saucy. Serve over spaghetti or in sub rolls for a big crew feed that scales easy.",
    whyCrewsLikeIt:
      "Meatballs feed a crowd without carving or portion guesswork. Sheet pan bake beats standing at a skillet forming batches, and subs plus pasta covers different appetites.",
    mealPrepNotes:
      "Use a scoop for uniform meatballs—they bake evenly. Bake at high heat for color, then finish in sauce. Spaghetti can boil while meatballs bake.",
    stationWorkflow: [
      "Roll meatballs golf-ball size—about 2 ounces each for ten hungry people.",
      "Bake on parchment-lined pans so cleanup is wipe-and-go.",
      "Simmer baked meatballs in marinara 15 minutes so sauce clings.",
    ],
    prepMinutes: 30,
    cookMinutes: 40,
    difficulty: "easy",
    crewSizeDefault: 10,
    ingredients: [
      ing("ground beef (80/20)", "4", { unit: "lb", group: "Main" }),
      ing("breadcrumbs", "2", { unit: "cups", group: "Main" }),
      ing("eggs", "3", { unit: "whole", group: "Main" }),
      ing("grated Parmesan", "1", { unit: "cup", group: "Main" }),
      ing("garlic cloves", "6", { unit: "cloves", notes: "minced", group: "Main" }),
      ing("marinara sauce", "8", { unit: "cups", group: "Sauce" }),
      ing("spaghetti", "2", { unit: "lb", group: "Base" }),
      ing("fresh basil", "0.33", { unit: "cup", notes: "chopped", group: "Finish" }),
      ing("sub rolls", "10", { unit: "rolls", notes: "optional for sandwiches", group: "Service" }),
      ing("shredded mozzarella", "2", { unit: "cups", notes: "optional for subs", group: "Service" }),
    ],
    steps: [
      step(1, "Mix the meatballs", "Combine beef, breadcrumbs, eggs, Parmesan, garlic, salt, and pepper until just mixed. Roll into about 60 golf-ball-size meatballs.", { minutes: 20 }),
      step(2, "Bake on sheet pans", "Arrange meatballs on two parchment-lined sheet pans. Bake at 425°F 18–20 minutes until browned and internal temp reaches 160°F.", { minutes: 20, tempF: 425 }),
      step(3, "Simmer in marinara", "Transfer meatballs to large pots, cover with marinara, and simmer 15 minutes until sauce coats meatballs and centers reach 165°F.", { minutes: 15, tempF: 165 }),
      step(4, "Boil spaghetti", "Cook spaghetti in salted water until al dente while meatballs simmer. Drain and toss with a ladle of sauce.", { minutes: 12 }),
      step(5, "Serve the spread", "Serve meatballs and sauce over spaghetti with basil. Toast sub rolls with mozzarella for meatball subs on the same line.", { minutes: 10 }),
    ],
    proTips: [
      "Bake a test meatball first if you are unsure on seasoning—adjust mix before rolling all 60.",
      "Italian seasoning tablespoon in the mix saves chopping extra herbs.",
      "Meatballs freeze raw on sheet pans—transfer to bags for emergency feeds.",
    ],
    tonightSpread: [
      "Spaghetti and meatballs with garlic bread and extra Parmesan.",
      "Meatball subs with melted mozzarella for handheld eaters.",
    ],
    leftovers: [
      "Meatball parm bake: layer in dish with mozzarella and bake 375°F.",
      "Crush into pizza topping for a quick flatbread night.",
    ],
    equipment: ["Two sheet pans", "Parchment paper", "Large stock pot", "Mixing bowls", "Instant-read thermometer"],
    nutrition: { calories: 580, protein: 42, carbs: 52, fats: 24, fiber: 4 },
    spiceLevel: "mild",
    cleanupDifficulty: "medium",
  }),

  def({
    slug: "hall-sloppy-joe-feed",
    title: "Hall Sloppy Joe Feed",
    subtitle: "Sweet-tangy beef sloppy joes with buns and chips for ten",
    category: "crew_feeders",
    protein: "beef",
    cuisine: "american",
    mealFormat: "sandwich",
    explorePools: ["beef", "hearty", "crew_feed", "handheld", "hall_expansion"],
    hookLine: "Two pounds of beef per person? No—but it feels that way when everyone goes back for seconds",
    description:
      "Ground beef browns with onion and bell pepper, then simmers in a sweet-tangy tomato sauce until thick and scoopable. Pile on toasted buns with pickles and chips for a classic hall feed.",
    whyCrewsLikeIt:
      "Sloppy joes are cheap, fast, and universally loved—especially by crews who grew up on cafeteria versions. This recipe is thicker and meatier, built for ten hungry firefighters.",
    mealPrepNotes:
      "Brown beef hard and drain fat or sandwiches get greasy. Sauce should mound on a spoon, not run off the bun. Toast buns so they survive the saucy filling.",
    stationWorkflow: [
      "Cook beef in two batches in the biggest pot you have.",
      "Simmer uncovered last 10 minutes until sauce thickens to scoop consistency.",
      "Set up line: buns, beef, pickles, onions, chips.",
    ],
    prepMinutes: 15,
    cookMinutes: 35,
    difficulty: "easy",
    crewSizeDefault: 10,
    ingredients: [
      ing("ground beef (80/20)", "5", { unit: "lb", group: "Main" }),
      ing("yellow onion", "2", { unit: "whole", notes: "diced", group: "Vegetables" }),
      ing("green bell pepper", "2", { unit: "whole", notes: "diced", group: "Vegetables" }),
      ing("ketchup", "2", { unit: "cups", group: "Sauce" }),
      ing("tomato paste", "0.25", { unit: "cup", group: "Sauce" }),
      ing("Worcestershire sauce", "3", { unit: "tbsp", group: "Sauce" }),
      ing("apple cider vinegar", "3", { unit: "tbsp", group: "Sauce" }),
      ing("brown sugar", "0.25", { unit: "cup", group: "Sauce" }),
      ing("hamburger buns", "12", { unit: "whole", notes: "toasted", group: "Service" }),
      ing("dill pickle chips", "2", { unit: "cups", group: "Service" }),
    ],
    steps: [
      step(1, "Brown the beef", "Cook ground beef with onion and bell pepper over medium-high heat 12–15 minutes, breaking into crumbles until well browned. Drain excess fat.", { minutes: 15 }),
      step(2, "Build the sauce", "Stir in ketchup, tomato paste, Worcestershire, vinegar, and brown sugar until combined.", { minutes: 3 }),
      step(3, "Simmer until thick", "Reduce heat and simmer uncovered 15–20 minutes, stirring often, until sauce mounds on a spoon and flavors meld.", { minutes: 18 }),
      step(4, "Toast the buns", "Split buns and toast cut-side down in a dry skillet or under broiler at 400°F until golden, about 3 minutes.", { minutes: 5, tempF: 400 }),
      step(5, "Serve the line", "Hold beef warm at 165°F in a hotel pan. Crews build sandwiches with pickles and extra onion if desired. Serve with chips.", { minutes: 5 }),
    ],
    proTips: [
      "A tablespoon of mustard adds tang without making it taste like mustard.",
      "Smoked paprika pinch makes canned-sauce flavors taste more homemade.",
      "Coleslaw on the sandwich is messy but worth it if you have time.",
    ],
    tonightSpread: [
      "Sloppy joes with kettle chips and dill pickles.",
      "Baked beans from a can, doctored with molasses and mustard, for a cookout vibe.",
    ],
    leftovers: [
      "Serve over baked potatoes with shredded cheese.",
      "Fold into a casserole with tater tots and cheddar for sloppy joe hot dish.",
    ],
    equipment: ["Large Dutch oven", "Wooden spoon", "Sheet pan", "Hotel pan", "Spatula"],
    nutrition: { calories: 520, protein: 36, carbs: 42, fats: 24, fiber: 3 },
    spiceLevel: "mild",
    cleanupDifficulty: "easy",
  }),

];
