import type { ExpansionRecipeDef } from "../types.js";
import { def, ing, step } from "../recipe-build.js";
import {
  CALL_INTERRUPTION_STEP,
  LEFTOVERS_PACK_DOWN_STEP,
  buildStructuredTonightSpread,
  standardLeftovers,
} from "../../golden-100/recipe-quality/classics-wheel-editorial.js";

/**
 * High-Protein / Healthy Expansion — dinners, lighter crew meals, meal-prep
 * bowls, and vegetarian high-protein recipes. All nutrition below is a
 * starting estimate; the production build regenerates real per-serving
 * macros from these ingredient lists via shared/nutrition/calculate.ts
 * (npm run audit:recipe-nutrition:fix) before publish.
 */
export const BATCH_HIGH_PROTEIN_EXPANSION_RECIPES: ExpansionRecipeDef[] = [
  def({
    slug: "firehouse-sweet-potato-beef-protein-bowls",
    title: "Firehouse Sweet Potato & Beef Protein Bowls",
    subtitle: "Seasoned ground beef, roasted sweet potato, and cottage cheese in a high-protein bowl",
    category: "crew_feeders",
    protein: "beef",
    cuisine: "american",
    mealFormat: "bowl",
    explorePools: ["bowl", "beef", "healthy", "high_protein", "meal_prep", "hall_expansion"],
    hookLine: "A ground-beef-and-sweet-potato bowl built around real per-serving protein, not a keyword.",
    description:
      "Roasted sweet potato cubes and seasoned ground beef share a bowl with cottage cheese, avocado, and a quick lime-herb drizzle. It is a straightforward, high-protein dinner that also reheats well for next-day lunches.",
    whyCrewsLikeIt:
      "It uses ingredients most halls already stock, comes together in two pans, and lands well above the crew's usual protein target without feeling like a diet plate.",
    mealPrepNotes:
      "Make-ahead: roast sweet potatoes and brown the beef up to two days ahead. Storage: keep beef, sweet potato, and cold toppings in separate containers up to 4 days; add cottage cheese and avocado at serving time. Reheating: warm beef and sweet potato together to 165°F, then top cold.",
    stationWorkflow: [
      "Get sweet potatoes in the oven first — they take longer than the beef.",
      "Brown beef in one wide skillet once the potatoes are past the halfway mark.",
      "Keep cottage cheese and avocado cold and separate until each bowl is built.",
    ],
    prepMinutes: 15,
    cookMinutes: 30,
    difficulty: "easy",
    crewSizeDefault: 8,
    ingredients: [
      ing("sweet potato", "4", { unit: "lb", notes: "peeled, 3/4-inch cubes", group: "Base" }),
      ing("olive oil", "3", { unit: "tbsp", group: "Base" }),
      ing("ground beef", "2.5", { unit: "lb", notes: "90/10", group: "Protein" }),
      ing("garlic", "4", { unit: "cloves", notes: "minced", group: "Protein" }),
      ing("smoked paprika", "1", { unit: "tbsp", group: "Protein" }),
      ing("cumin", "2", { unit: "tsp", group: "Protein" }),
      ing("cottage cheese", "2", { unit: "cups", group: "Toppings" }),
      ing("avocado", "3", { unit: "each", notes: "sliced", group: "Toppings" }),
      ing("cherry tomatoes", "2", { unit: "cups", notes: "halved", group: "Toppings" }),
      ing("green onions", "0.5", { unit: "cup", notes: "sliced", group: "Toppings" }),
      ing("lime juice", "3", { unit: "tbsp", group: "Dressing" }),
      ing("olive oil", "2", { unit: "tbsp", group: "Dressing" }),
      ing("fresh cilantro", "0.25", { unit: "cup", notes: "chopped", optional: true, group: "Dressing" }),
    ],
    steps: [
      step(1, "Roast the sweet potato base", "Heat the oven to 425°F. Toss sweet potato cubes with olive oil, salt, and pepper on two sheet pans in a single layer. Roast 25–28 minutes, turning once, until browned at the edges and fork-tender.", { minutes: 28, heatLevel: "medium-high", tempF: 425 }),
      step(2, "Season and brown the beef", "Heat a wide skillet over medium-high. Add beef and break it into crumbles, cooking 7–8 minutes until no pink remains. Drain excess fat, then stir in garlic, smoked paprika, cumin, salt, and pepper and cook 2 more minutes until fragrant.", { minutes: 12, heatLevel: "medium-high" }),
      step(3, "Build the lime-herb drizzle", "Whisk lime juice with olive oil, a pinch of salt, and cilantro if using. Keep it in a squeeze bottle at the cold end of the line so it stays bright instead of wilting the toppings early.", { minutes: 4 }),
      step(4, "Hold everything at the right temperature", "Cover beef and sweet potato in separate dishes and hold at 140°F or above until service. Keep cottage cheese, avocado, tomatoes, and green onions cold and covered until the last possible moment.", { minutes: 5, heatLevel: "low" }),
      step(5, "Layer the bowls", "Start each bowl with roasted sweet potato, then add a portion of seasoned beef beside it rather than on top, so both stay visible and neither steams the other soft.", { minutes: 6 }),
      step(6, "Add the cottage cheese and produce", "Spoon cottage cheese into its own section of the bowl, then scatter avocado, cherry tomatoes, and green onions around the hot components.", { minutes: 5 }),
      step(7, "Finish and send it out", "Drizzle the lime-herb dressing over the top and set bowls at the pass with extra lime wedges and hot sauce on the side for anyone who wants more heat.", { minutes: 4 }),
      CALL_INTERRUPTION_STEP(8, "seasoned ground beef and roasted sweet potato"),
      LEFTOVERS_PACK_DOWN_STEP(9, "seasoned ground beef and roasted sweet potato"),
    ],
    proTips: [
      "Prep tip: Cut sweet potato pieces the same size so none burn while others stay firm.",
      "Rookie tip: Add cottage cheese cold, right before serving, so it never breaks down from residual heat.",
      "Swap ground turkey for beef if the hall is trying to keep saturated fat lower without losing protein.",
      "Keep hot sauce and extra lime on the side — the base recipe is intentionally mild.",
    ],
    tonightSpread: buildStructuredTonightSpread(
      "Sweet potato and beef protein bowls",
      ["Sliced cucumber", "extra lime wedges"],
      ["Hot sauce", "extra cottage cheese"],
    ),
    leftovers: standardLeftovers("seasoned ground beef and roasted sweet potato", [
      "Fold cold leftovers into a lunch bowl with extra greens the next shift.",
    ]),
    equipment: ["Two sheet pans", "Large skillet", "Mixing bowls", "Instant-read thermometer"],
    nutrition: { calories: 789, protein: 49, carbs: 56, fats: 44, fiber: 7 },
    spiceLevel: "mild",
    cleanupDifficulty: "easy",
    searchTerms: [
      "sweet potato beef protein bowl",
      "ground beef sweet potato bowl",
      "cottage cheese beef bowl",
      "high protein dinner bowl",
      "firehouse protein bowl",
      "meal prep beef bowl",
      "crew dinner high protein",
    ],
    substitutions: [
      "Use ground turkey or ground bison for beef.",
      "Use Greek yogurt if cottage cheese is unpopular.",
      "Use roasted broccoli alongside the sweet potato for more volume.",
    ],
  }),

  def({
    slug: "firehouse-dense-bean-salad",
    title: "Firehouse Dense Bean Salad",
    subtitle: "Mixed beans, crunchy vegetables, and a lemon-herb vinaigrette in a make-ahead salad",
    category: "crew_feeders",
    protein: "vegetarian",
    cuisine: "american",
    mealFormat: "salad",
    explorePools: ["salad", "vegetarian", "healthy", "meal_prep", "hall_expansion"],
    hookLine: "A cold, make-ahead bean salad dense enough with protein to stand in as a full meal or a serious side.",
    description:
      "Chickpeas, black beans, and kidney beans are tossed with cucumber, bell pepper, red onion, and feta in a lemon-herb vinaigrette. It holds in the fridge for days and actually improves as the flavors settle.",
    whyCrewsLikeIt:
      "It needs no reheating, travels well to calls, and gives the crew a fiber- and protein-forward option next to heavier mains without anyone feeling shortchanged.",
    mealPrepNotes:
      "Make-ahead: this salad is designed to be made 1–3 days in advance. Storage: keep in a sealed container up to 4 days; dress fully or hold dressing separate for the crispest vegetables. Reheating: none — serve cold or at room temperature.",
    stationWorkflow: [
      "Drain and rinse all beans well so the dressing doesn't turn watery.",
      "Cut vegetables to a uniform, small dice so every bite has a mix.",
      "Dress the salad at least 20 minutes before serving so the beans pick up flavor.",
    ],
    prepMinutes: 20,
    cookMinutes: 5,
    difficulty: "easy",
    crewSizeDefault: 8,
    ingredients: [
      ing("chickpeas", "2", { unit: "cans", notes: "drained, rinsed", group: "Beans" }),
      ing("black beans", "2", { unit: "cans", notes: "drained, rinsed", group: "Beans" }),
      ing("kidney beans", "1", { unit: "can", notes: "drained, rinsed", group: "Beans" }),
      ing("cucumber", "2", { unit: "each", notes: "small dice", group: "Vegetables" }),
      ing("bell pepper", "2", { unit: "each", notes: "small dice", group: "Vegetables" }),
      ing("red onion", "0.5", { unit: "each", notes: "finely diced", group: "Vegetables" }),
      ing("cherry tomatoes", "2", { unit: "cups", notes: "halved", group: "Vegetables" }),
      ing("feta cheese", "1.5", { unit: "cups", notes: "crumbled", group: "Vegetables" }),
      ing("olive oil", "0.33", { unit: "cup", group: "Dressing" }),
      ing("lemon juice", "0.33", { unit: "cup", group: "Dressing" }),
      ing("dijon mustard", "1", { unit: "tbsp", group: "Dressing" }),
      ing("dried oregano", "1", { unit: "tbsp", group: "Dressing" }),
      ing("garlic", "2", { unit: "cloves", notes: "minced", group: "Dressing" }),
      ing("fresh parsley", "0.5", { unit: "cup", notes: "chopped", group: "Finish" }),
    ],
    steps: [
      step(1, "Drain and rinse the beans", "Drain chickpeas, black beans, and kidney beans, then rinse under cold water until the runoff is clear. Shake dry in a colander — excess liquid dilutes the dressing.", { minutes: 8 }),
      step(2, "Dice the vegetables small and even", "Cut cucumber, bell pepper, and red onion into a small, even dice so no single bite is all onion or all bean. Halve the cherry tomatoes.", { minutes: 15 }),
      step(3, "Whisk the lemon-herb vinaigrette", "Whisk olive oil, lemon juice, dijon, oregano, and garlic in a bowl until it looks cohesive rather than separated. Taste and adjust salt — the beans will mute seasoning as they sit.", { minutes: 5 }),
      step(4, "Combine beans and vegetables", "Fold the beans, cucumber, pepper, onion, and tomatoes together in a large bowl. Toss gently rather than stirring hard, so the softer beans stay intact.", { minutes: 5 }),
      step(5, "Dress and rest before serving", "Pour the vinaigrette over the salad and toss to coat evenly. Let it sit at least 20 minutes, or refrigerate up to 3 days, so the beans absorb the dressing.", { minutes: 20 }),
      step(6, "Finish with feta and parsley", "Fold in feta and parsley just before serving so the cheese stays in distinct pieces instead of dissolving into the dressing overnight.", { minutes: 5 }),
      step(7, "Hold and serve cold", "Keep the salad covered and cold until service — it does not need to be held warm and should not sit at room temperature longer than two hours.", { minutes: 5, heatLevel: "" }),
    ],
    proTips: [
      "Prep tip: Rinse beans until the water runs clear — skipping this leaves a starchy film on the dressing.",
      "Rookie tip: Dress the salad ahead of time; it actually tastes better after a day in the fridge.",
      "Swap feta for cottage cheese if the crew wants a milder, higher-protein finish.",
      "Add diced avocado right before serving if you want extra richness — it does not hold well pre-mixed.",
    ],
    tonightSpread: buildStructuredTonightSpread(
      "Dense bean salad",
      ["Warm pita or crusty bread", "grilled protein on the side"],
      ["Extra lemon wedges", "hot sauce"],
    ),
    leftovers: [
      "Keeps well covered and cold for up to 4 days — flavor improves on day two.",
      "Store any dressing added separately if serving over multiple days to keep vegetables crisp.",
      "Spoon leftovers over greens or into a wrap for a fast next-day lunch.",
    ],
    equipment: ["Colander", "Large mixing bowl", "Chef knife", "Whisk"],
    nutrition: { calories: 390, protein: 19, carbs: 46, fats: 16, fiber: 14 },
    spiceLevel: "mild",
    cleanupDifficulty: "easy",
    searchTerms: [
      "dense bean salad",
      "mixed bean salad",
      "make ahead bean salad",
      "meal prep bean salad",
      "vegetarian bean salad",
      "firehouse bean salad",
      "cold crew side dish",
    ],
    substitutions: [
      "Use cottage cheese instead of feta for a milder, dairy-forward protein boost.",
      "Use any combination of canned beans on hand — cannellini and pinto both work.",
      "Add canned tuna or grilled chicken to turn this into a heartier main.",
    ],
  }),

  def({
    slug: "loaded-firehouse-sweet-potatoes",
    title: "Loaded Firehouse Sweet Potatoes",
    subtitle: "Baked sweet potatoes topped with seasoned beef, Greek yogurt, and cheese, topping-bar style",
    category: "crew_feeders",
    protein: "beef",
    cuisine: "american",
    mealFormat: "bake",
    explorePools: ["bake", "beef", "healthy", "high_protein", "hall_expansion"],
    hookLine: "A loaded-potato night built on sweet potatoes and a real topping bar instead of sour cream and butter.",
    description:
      "Whole sweet potatoes are baked until tender, split, and loaded with seasoned chili-style beef, Greek yogurt, shredded cheese, and a topping bar of scallions, black beans, and salsa. Everyone builds their own.",
    whyCrewsLikeIt:
      "It turns a familiar loaded-potato format into a higher-protein, better-balanced dinner without losing the comfort-food feel, and the topping bar handles picky eaters without extra cooking.",
    mealPrepNotes:
      "Make-ahead: bake potatoes and cook the beef filling up to two days ahead. Storage: keep potatoes, beef, and cold toppings in separate containers up to 4 days. Reheating: reheat potatoes and beef separately to 165°F, then rebuild with cold toppings.",
    stationWorkflow: [
      "Bake potatoes first — they take the longest and hold well wrapped in foil.",
      "Brown and season the beef filling while potatoes finish in the oven.",
      "Set Greek yogurt, cheese, and toppings out only once potatoes are ready to split.",
    ],
    prepMinutes: 15,
    cookMinutes: 55,
    difficulty: "easy",
    crewSizeDefault: 8,
    ingredients: [
      ing("sweet potato", "8", { unit: "each", notes: "medium, scrubbed", group: "Base" }),
      ing("olive oil", "2", { unit: "tbsp", group: "Base" }),
      ing("ground beef", "2.5", { unit: "lb", notes: "90/10", group: "Filling" }),
      ing("taco seasoning", "3", { unit: "tbsp", group: "Filling" }),
      ing("black beans", "1", { unit: "can", notes: "drained, rinsed", group: "Filling" }),
      ing("plain greek yogurt", "1.5", { unit: "cups", group: "Toppings" }),
      ing("cheddar cheese", "2", { unit: "cups", notes: "shredded", group: "Toppings" }),
      ing("green onions", "0.5", { unit: "cup", notes: "sliced", group: "Toppings" }),
      ing("salsa", "1.5", { unit: "cups", group: "Toppings" }),
      ing("diced tomato", "1.5", { unit: "cups", group: "Toppings" }),
      ing("jalapeno", "2", { unit: "each", notes: "sliced", optional: true, group: "Toppings" }),
    ],
    steps: [
      step(1, "Bake the sweet potatoes", "Heat the oven to 400°F. Rub potatoes with olive oil, pierce a few times with a fork, and bake directly on a rack or sheet pan 45–55 minutes until a knife slides in with no resistance.", { minutes: 55, heatLevel: "medium-high", tempF: 400 }),
      step(2, "Brown the beef filling", "While potatoes bake, brown ground beef in a skillet over medium-high 7–8 minutes until no pink remains. Drain excess fat, stir in taco seasoning with 1/4 cup water, and simmer 3 minutes.", { minutes: 12, heatLevel: "medium-high" }),
      step(3, "Warm the black beans into the filling", "Fold drained black beans into the seasoned beef and simmer 3–4 minutes until heated through. This keeps the filling scoopable instead of two separate components on the plate.", { minutes: 5, heatLevel: "medium" }),
      step(4, "Hold potatoes and filling hot", "Wrap finished potatoes loosely in foil to hold their heat, and keep the beef-bean filling covered at 140°F or above. Do not let potatoes sit uncovered — they dry out fast.", { minutes: 5, heatLevel: "low" }),
      step(5, "Set the topping bar", "Put Greek yogurt, cheddar, green onions, salsa, diced tomato, and jalapeño in separate bowls at the end of the line, keeping the yogurt and cheese cold until service starts.", { minutes: 6 }),
      step(6, "Split and load the potatoes", "Slice each potato lengthwise and press the ends toward the middle to open it up. Spoon in the beef-bean filling first so the base of the bowl holds heat.", { minutes: 6 }),
      step(7, "Finish loading and serve", "Top with cheddar so it melts slightly into the hot filling, then add Greek yogurt, salsa, tomato, and green onions. Serve immediately so the yogurt stays cool against the hot potato.", { minutes: 5 }),
      CALL_INTERRUPTION_STEP(8, "seasoned beef and black bean filling"),
      LEFTOVERS_PACK_DOWN_STEP(9, "seasoned beef and black bean filling"),
    ],
    proTips: [
      "Prep tip: Bake a few extra potatoes — they reheat well and let latecomers build their own.",
      "Rookie tip: Use Greek yogurt in place of sour cream; it holds up better once it hits the hot filling.",
      "Swap the beef filling for seasoned black beans only to make the whole tray vegetarian.",
      "Score the potato flesh lightly with a fork before loading so toppings settle in instead of sliding off.",
    ],
    tonightSpread: buildStructuredTonightSpread(
      "Loaded sweet potatoes",
      ["Simple green salad", "tortilla chips"],
      ["Extra salsa", "hot sauce", "lime wedges"],
    ),
    leftovers: standardLeftovers("seasoned beef and black bean filling", [
      "Scoop leftover potato flesh and filling into a quick skillet hash the next shift.",
    ]),
    equipment: ["Sheet pan", "Large skillet", "Foil", "Serving bowls"],
    nutrition: { calories: 736, protein: 55, carbs: 44, fats: 40, fiber: 9 },
    spiceLevel: "mild",
    cleanupDifficulty: "easy",
    searchTerms: [
      "loaded sweet potato",
      "loaded sweet potato bar",
      "high protein loaded potato",
      "sweet potato dinner",
      "greek yogurt loaded potato",
      "firehouse loaded sweet potatoes",
      "crew dinner sweet potato",
    ],
    substitutions: [
      "Use lean ground turkey instead of beef.",
      "Use shredded rotisserie chicken tossed in taco seasoning for a lighter filling.",
      "Skip the cheese and add extra black beans for a lower-fat version.",
    ],
  }),

  def({
    slug: "firehouse-diner-burger-bowls",
    title: "Firehouse Diner Burger Bowls",
    subtitle: "Seasoned beef patties over lettuce with diner-style burger toppings and a tangy burger sauce",
    category: "crew_feeders",
    protein: "beef",
    cuisine: "american",
    mealFormat: "bowl",
    explorePools: ["bowl", "beef", "healthy", "high_protein", "hall_expansion"],
    hookLine: "A classic American diner burger, deconstructed into a bowl with real per-serving protein.",
    description:
      "Griddled beef patties are chopped over crisp lettuce with tomato, pickles, red onion, and cheddar, finished with a tangy burger sauce. It tastes like a diner cheeseburger without the bun weighing the plate down.",
    whyCrewsLikeIt:
      "It delivers the exact flavor of a diner burger night — griddled beef, melted cheddar, tangy sauce — while landing in a much better protein-to-calorie ratio than a double burger and fries.",
    mealPrepNotes:
      "Make-ahead: chop vegetables and mix the sauce up to a day ahead. Storage: keep cooked beef, chopped lettuce, and sauce in separate containers up to 3 days. Reheating: warm beef to 165°F; add cold lettuce and sauce after, never before.",
    stationWorkflow: [
      "Chop lettuce and vegetables before the griddle heats up so the beef doesn't sit.",
      "Cook patties in batches on a hot griddle or skillet rather than crowding one pan.",
      "Toss lettuce with sauce at the very end so it doesn't wilt while holding.",
    ],
    prepMinutes: 15,
    cookMinutes: 20,
    difficulty: "easy",
    crewSizeDefault: 8,
    ingredients: [
      ing("ground beef", "2.5", { unit: "lb", notes: "80/20, formed into thin patties", group: "Protein" }),
      ing("garlic powder", "1", { unit: "tbsp", group: "Protein" }),
      ing("onion powder", "1", { unit: "tbsp", group: "Protein" }),
      ing("romaine lettuce", "3", { unit: "hearts", notes: "chopped", group: "Base" }),
      ing("cheddar cheese", "1.5", { unit: "cups", notes: "shredded", group: "Toppings" }),
      ing("tomatoes", "3", { unit: "each", notes: "diced", group: "Toppings" }),
      ing("dill pickles", "1", { unit: "cup", notes: "chopped", group: "Toppings" }),
      ing("red onion", "0.5", { unit: "each", notes: "finely diced", group: "Toppings" }),
      ing("mayonnaise", "0.5", { unit: "cup", group: "Sauce" }),
      ing("ketchup", "0.25", { unit: "cup", group: "Sauce" }),
      ing("dill pickle juice", "1", { unit: "tbsp", group: "Sauce" }),
      ing("smoked paprika", "0.5", { unit: "tsp", group: "Sauce" }),
    ],
    steps: [
      step(1, "Chop the diner toppings", "Chop romaine into bite-size ribbons, dice tomato and red onion, and chop pickles. Hold all of it cold and covered — this is a rookie-friendly, low-heat prep step.", { minutes: 15 }),
      step(2, "Mix the burger sauce", "Whisk mayonnaise, ketchup, pickle juice, and smoked paprika until smooth and pink-orange. Taste and adjust with more pickle juice for tang.", { minutes: 5 }),
      step(3, "Season and form thin patties", "Mix ground beef with garlic powder, onion powder, salt, and pepper. Form into thin, wide patties so they cook fast and develop a real seared crust.", { minutes: 8 }),
      step(4, "Griddle the beef", "Cook patties on a hot griddle or skillet 3–4 minutes per side until well browned and 165°F in the center. Work in batches rather than crowding the pan, which steams instead of sears.", { minutes: 12, heatLevel: "medium-high" }),
      step(5, "Chop the beef for the bowls", "Rest patties 2 minutes, then chop into bite-size pieces on a clean board. Chopping instead of leaving whole patties makes portioning and eating with a fork much easier.", { minutes: 4 }),
      step(6, "Hold beef and lettuce separately", "Keep chopped beef covered at 140°F or above. Keep lettuce and cold toppings refrigerated and undressed until right before service so nothing wilts.", { minutes: 5, heatLevel: "low" }),
      step(7, "Build the bowls", "Fill each bowl with lettuce first, then add chopped beef, cheddar, tomato, pickles, and red onion around it. Drizzle burger sauce over the top and serve immediately.", { minutes: 8 }),
      CALL_INTERRUPTION_STEP(8, "griddled ground beef"),
      LEFTOVERS_PACK_DOWN_STEP(9, "griddled ground beef"),
    ],
    proTips: [
      "Prep tip: Thin patties cook faster and develop more seared surface per pound than thick ones.",
      "Rookie tip: Keep the burger sauce on the side for anyone who wants their bowl drier.",
      "Add crumbled turkey bacon for a smokier version without much extra fat.",
      "Skip the cheese to lower saturated fat while keeping the protein count about the same.",
    ],
    tonightSpread: buildStructuredTonightSpread(
      "Diner burger bowls",
      ["Oven fries or roasted potatoes", "extra pickles"],
      ["Extra burger sauce", "hot sauce"],
    ),
    leftovers: standardLeftovers("griddled ground beef", [
      "Fold leftover beef and toppings into a wrap or over rice for a fast next-day lunch.",
    ]),
    equipment: ["Griddle or large skillet", "Chef knife", "Mixing bowls", "Instant-read thermometer"],
    nutrition: { calories: 560, protein: 44, carbs: 5, fats: 42, fiber: 4 },
    spiceLevel: "mild",
    cleanupDifficulty: "easy",
    searchTerms: [
      "burger bowl",
      "high protein burger bowl",
      "diner burger bowl",
      "cheeseburger bowl",
      "low carb burger bowl",
      "firehouse burger bowl",
      "crew dinner burger bowl",
    ],
    substitutions: [
      "Use ground turkey or ground chicken instead of beef.",
      "Use a Greek yogurt-based sauce instead of mayonnaise for a lighter dressing.",
      "Add avocado for extra healthy fat if the crew wants more richness.",
    ],
  }),

  def({
    slug: "blackened-salmon-sweet-potato-bowls",
    title: "Blackened Salmon Sweet Potato Bowls",
    subtitle: "Cajun-blackened salmon over roasted sweet potato and greens with a cooling yogurt drizzle",
    category: "crew_feeders",
    protein: "salmon",
    cuisine: "american",
    mealFormat: "bowl",
    explorePools: ["bowl", "seafood", "healthy", "high_protein", "hall_expansion"],
    hookLine: "A lean, omega-3-forward bowl with real char and spice instead of a plain broiled fillet.",
    description:
      "Salmon fillets get a bold blackening seasoning and a hard sear, then sit over roasted sweet potato and sautéed greens with a cool lemon-yogurt drizzle to balance the heat.",
    whyCrewsLikeIt:
      "It gives crews who are tired of chicken and beef a genuinely satisfying fish option with real crust and spice, and the sweet potato base makes it filling instead of light and forgettable.",
    mealPrepNotes:
      "Make-ahead: roast sweet potato up to two days ahead; the yogurt sauce holds 3 days. Storage: keep salmon, sweet potato, and greens separate. Reheating: gently reheat salmon covered at 275°F just until warm — high heat dries it out fast.",
    stationWorkflow: [
      "Roast the sweet potato first since it takes the longest.",
      "Sear salmon last, close to service, so the crust stays crisp.",
      "Keep the yogurt sauce cold and add it only at the pass.",
    ],
    prepMinutes: 15,
    cookMinutes: 25,
    difficulty: "medium",
    crewSizeDefault: 8,
    ingredients: [
      ing("sweet potato", "3.5", { unit: "lb", notes: "3/4-inch cubes", group: "Base" }),
      ing("olive oil", "0.25", { unit: "cup", group: "Base" }),
      ing("salmon fillet", "3", { unit: "lb", notes: "cut into 8 portions", group: "Protein" }),
      ing("smoked paprika", "2", { unit: "tbsp", group: "Seasoning" }),
      ing("garlic powder", "1", { unit: "tbsp", group: "Seasoning" }),
      ing("cayenne pepper", "1", { unit: "tsp", group: "Seasoning" }),
      ing("dried thyme", "1", { unit: "tsp", group: "Seasoning" }),
      ing("baby spinach", "10", { unit: "oz", group: "Greens" }),
      ing("garlic", "3", { unit: "cloves", notes: "minced", group: "Greens" }),
      ing("plain greek yogurt", "1", { unit: "cup", group: "Sauce" }),
      ing("lemon juice", "2", { unit: "tbsp", group: "Sauce" }),
      ing("fresh dill", "2", { unit: "tbsp", notes: "chopped", optional: true, group: "Sauce" }),
    ],
    steps: [
      step(1, "Roast the sweet potato", "Heat the oven to 425°F. Toss sweet potato cubes with 2 tablespoons oil, salt, and pepper on a sheet pan and roast 22–25 minutes, turning once, until tender and browned at the edges.", { minutes: 25, heatLevel: "medium-high", tempF: 425 }),
      step(2, "Mix the blackening seasoning", "Combine smoked paprika, garlic powder, cayenne, thyme, salt, and pepper in a small bowl. Pat salmon portions dry, then coat evenly on both sides — dry fish takes seasoning and sears better than wet fish.", { minutes: 8 }),
      step(3, "Sear the salmon", "Heat remaining oil in a large skillet over medium-high until shimmering. Sear salmon skin-side up first 3–4 minutes until a dark crust forms, flip, and cook 3 more minutes to 130–135°F for medium.", { minutes: 10, heatLevel: "medium-high" }),
      step(4, "Wilt the greens", "In the same skillet, add garlic and spinach in batches, tossing 2–3 minutes just until wilted. Season lightly with salt — the salmon and sauce both carry plenty of flavor already.", { minutes: 5, heatLevel: "medium" }),
      step(5, "Mix the lemon-yogurt sauce", "Stir Greek yogurt with lemon juice, dill, and a pinch of salt until smooth. Keep it cold in a squeeze bottle so it stays thick and cooling against the spiced fish.", { minutes: 4 }),
      step(6, "Hold and build the bowls", "Keep salmon loosely covered and sweet potato warm in a 200°F oven. Layer sweet potato and spinach in each bowl, top with a portion of salmon, and finish with a drizzle of yogurt sauce.", { minutes: 8, tempF: 200 }),
      CALL_INTERRUPTION_STEP(7, "blackened salmon"),
      LEFTOVERS_PACK_DOWN_STEP(8, "blackened salmon"),
    ],
    proTips: [
      "Prep tip: Pat salmon completely dry before seasoning — moisture is the enemy of a real blackened crust.",
      "Rookie tip: Pull salmon a shade under your target temperature; it keeps cooking a bit while it rests.",
      "Use cod or tilapia if the hall doesn't have salmon on hand — the seasoning still works well.",
      "Keep cayenne on the lower end if the crew doesn't run hot on spice; the smoked paprika still carries flavor.",
    ],
    tonightSpread: buildStructuredTonightSpread(
      "Blackened salmon sweet potato bowls",
      ["Simple cucumber salad", "lemon wedges"],
      ["Extra yogurt sauce", "hot sauce"],
    ),
    leftovers: [
      "Cool salmon and sweet potato in shallow pans within two hours; reheat salmon gently, not on high heat.",
      "Store the yogurt sauce separately — it keeps well cold for up to 3 days.",
      "Flake leftover salmon over greens for a fast next-day lunch instead of reheating it whole.",
    ],
    equipment: ["Sheet pan", "Large skillet", "Instant-read thermometer", "Fish spatula"],
    nutrition: { calories: 629, protein: 45, carbs: 44, fats: 29, fiber: 5 },
    spiceLevel: "medium",
    cleanupDifficulty: "medium",
    searchTerms: [
      "blackened salmon bowl",
      "salmon sweet potato bowl",
      "high protein salmon bowl",
      "healthy salmon dinner",
      "omega 3 dinner bowl",
      "firehouse salmon bowl",
    ],
    substitutions: [
      "Use cod, tilapia, or trout in place of salmon.",
      "Use sour cream thinned with a little water if Greek yogurt isn't on hand.",
      "Swap spinach for kale or broccolini.",
    ],
  }),

  def({
    slug: "firehouse-chicken-black-bean-bowls",
    title: "Firehouse Chicken & Black Bean Bowls",
    subtitle: "Chili-lime chicken, black beans, corn, and brown rice with a cool avocado crema",
    category: "crew_feeders",
    protein: "chicken",
    cuisine: "mexican",
    mealFormat: "bowl",
    explorePools: ["bowl", "chicken", "healthy", "high_protein", "meal_prep", "hall_expansion"],
    hookLine: "A meal-prep-friendly chicken bowl built around beans and brown rice instead of a heavy sauce.",
    description:
      "Chili-lime chicken breast is sliced over brown rice, black beans, and roasted corn, then finished with an avocado crema. It is built to hold well in individual containers for several days without going soggy.",
    whyCrewsLikeIt:
      "It is genuinely different from the hall's other bowl nights, packs well into individual containers for the next shift, and gives a real fiber-and-protein combination instead of just chicken and rice.",
    mealPrepNotes:
      "Make-ahead: chicken and rice both hold well up to 4 days. Storage: pack rice, beans, corn, and chicken together; keep avocado crema in a separate small container and add at the time of eating. Reheating: heat to 165°F, then top with cold crema.",
    stationWorkflow: [
      "Start rice first — it takes the longest and holds well covered.",
      "Marinate chicken while rice cooks, then sear it close to service.",
      "Make the crema last so it stays bright green and doesn't oxidize before serving.",
    ],
    prepMinutes: 20,
    cookMinutes: 25,
    difficulty: "easy",
    crewSizeDefault: 8,
    ingredients: [
      ing("chicken breast", "3", { unit: "lb", notes: "boneless, skinless", group: "Protein" }),
      ing("lime juice", "0.25", { unit: "cup", group: "Marinade" }),
      ing("chili powder", "2", { unit: "tbsp", group: "Marinade" }),
      ing("cumin", "1", { unit: "tbsp", group: "Marinade" }),
      ing("garlic", "3", { unit: "cloves", notes: "minced", group: "Marinade" }),
      ing("brown rice", "2.5", { unit: "cups", notes: "uncooked", group: "Base" }),
      ing("black beans", "2", { unit: "cans", notes: "drained, rinsed", group: "Base" }),
      ing("corn", "3", { unit: "cups", group: "Base" }),
      ing("avocado", "2", { unit: "each", group: "Crema" }),
      ing("plain greek yogurt", "0.5", { unit: "cup", group: "Crema" }),
      ing("lime juice", "2", { unit: "tbsp", group: "Crema" }),
      ing("fresh cilantro", "0.25", { unit: "cup", group: "Crema" }),
    ],
    steps: [
      step(1, "Marinate the chicken", "Whisk lime juice, chili powder, cumin, garlic, salt, and pepper in a bowl. Add chicken and turn to coat; let it sit at least 15 minutes while the rice cooks.", { minutes: 15 }),
      step(2, "Cook the brown rice", "Rinse rice, then bring it with water to a boil in a lidded pot, cover, and simmer on low about 35 minutes until tender. Rest 5 minutes, then fluff. Do not lift the lid repeatedly during the simmer.", { minutes: 40, heatLevel: "low" }),
      step(3, "Sear the chicken", "Heat a skillet over medium-high with a splash of oil. Sear chicken 5–6 minutes per side until browned and 165°F at the thickest point. Rest 5 minutes, then slice against the grain.", { minutes: 15, heatLevel: "medium-high" }),
      step(4, "Char the corn", "In a dry, wide skillet over medium-high, toast corn 4–5 minutes, stirring only when it starts to pop, until a few kernels brown. This adds real flavor beyond just heating it through.", { minutes: 6, heatLevel: "medium-high" }),
      step(5, "Warm the black beans", "Warm drained black beans in a small saucepan with a splash of water over medium-low 4–5 minutes. Season lightly with cumin and salt.", { minutes: 6, heatLevel: "medium-low" }),
      step(6, "Blend the avocado crema", "Blend or mash avocado with Greek yogurt, lime juice, cilantro, and a pinch of salt until smooth and pourable. Add a splash of water if it is too thick to drizzle.", { minutes: 6 }),
      step(7, "Build the bowls", "Layer rice, black beans, and corn in each bowl, fan sliced chicken across the top, and finish with a drizzle of avocado crema and extra cilantro.", { minutes: 8 }),
      CALL_INTERRUPTION_STEP(8, "chili-lime chicken"),
      LEFTOVERS_PACK_DOWN_STEP(9, "chili-lime chicken"),
    ],
    proTips: [
      "Prep tip: Slice chicken against the grain for the most tender bite.",
      "Rookie tip: Keep avocado crema in its own small container for multi-day meal prep so it doesn't brown on top.",
      "Add a squeeze of lime over packed containers before sealing to help keep the avocado crema bright.",
      "Swap brown rice for quinoa for a slightly higher-protein base.",
    ],
    tonightSpread: buildStructuredTonightSpread(
      "Chicken and black bean bowls",
      ["Tortilla chips", "sliced jalapeño"],
      ["Extra lime wedges", "hot sauce"],
    ),
    leftovers: standardLeftovers("chili-lime chicken", [
      "Pack rice, beans, corn, and chicken together for grab-and-go lunches; keep crema separate.",
    ]),
    equipment: ["Rice pot", "Large skillet", "Blender or fork for mashing", "Instant-read thermometer"],
    nutrition: { calories: 714, protein: 68, carbs: 78, fats: 15, fiber: 11 },
    spiceLevel: "mild",
    cleanupDifficulty: "easy",
    searchTerms: [
      "chicken black bean bowl",
      "high protein meal prep bowl",
      "chicken burrito bowl",
      "chili lime chicken bowl",
      "meal prep chicken bowl",
      "firehouse chicken bowl",
    ],
    substitutions: [
      "Use quinoa instead of brown rice.",
      "Use shredded rotisserie chicken to save time.",
      "Use sour cream thinned with lime juice if avocado isn't available.",
    ],
  }),

  def({
    slug: "sesame-ginger-tofu-bowls",
    title: "Sesame Ginger Tofu Bowls",
    subtitle: "Crisped tofu, edamame, and vegetables over rice with a sesame-ginger sauce",
    category: "crew_feeders",
    protein: "vegetarian",
    cuisine: "asian",
    mealFormat: "bowl",
    explorePools: ["bowl", "vegetarian", "healthy", "high_protein", "meal_prep", "hall_expansion"],
    hookLine: "A crisp-edged tofu bowl with enough protein and sauce to satisfy crews who never asked for tofu.",
    description:
      "Pressed tofu is pan-crisped until golden, then served over rice with edamame, shredded carrots, and cucumber in a sesame-ginger sauce. It is the hall's first fully vegetarian high-protein bowl option.",
    whyCrewsLikeIt:
      "The sauce and crisp texture do the convincing — most crews are surprised how filling and flavorful a vegetarian night can be, and it gives anyone avoiding meat a real seat at the table.",
    mealPrepNotes:
      "Make-ahead: press and marinate tofu up to a day ahead; sauce holds 5 days. Storage: keep tofu, rice, and vegetables separate up to 4 days. Reheating: reheat tofu in a dry skillet to re-crisp rather than the microwave, which turns it soft.",
    stationWorkflow: [
      "Press tofu early — it needs at least 15 minutes under weight to crisp properly.",
      "Cook rice while tofu presses so both finish close together.",
      "Crisp tofu last, right before service, so the edges stay firm.",
    ],
    prepMinutes: 20,
    cookMinutes: 20,
    difficulty: "medium",
    crewSizeDefault: 8,
    ingredients: [
      ing("firm tofu", "3", { unit: "block", notes: "pressed, cubed", group: "Protein" }),
      ing("cornstarch", "3", { unit: "tbsp", group: "Protein" }),
      ing("vegetable oil", "3", { unit: "tbsp", group: "Protein" }),
      ing("jasmine rice", "2.5", { unit: "cups", notes: "uncooked", group: "Base" }),
      ing("edamame", "3", { unit: "cups", notes: "shelled, thawed", group: "Vegetables" }),
      ing("shredded carrots", "2", { unit: "cups", group: "Vegetables" }),
      ing("cucumber", "2", { unit: "each", notes: "sliced", group: "Vegetables" }),
      ing("soy sauce", "0.33", { unit: "cup", group: "Sauce" }),
      ing("rice vinegar", "3", { unit: "tbsp", group: "Sauce" }),
      ing("honey", "2", { unit: "tbsp", group: "Sauce" }),
      ing("fresh ginger", "2", { unit: "tbsp", notes: "grated", group: "Sauce" }),
      ing("sesame oil", "1", { unit: "tbsp", group: "Sauce" }),
      ing("sesame seeds", "2", { unit: "tbsp", optional: true, group: "Finish" }),
    ],
    steps: [
      step(1, "Press the tofu", "Wrap tofu blocks in paper towel and press under a heavy pan for at least 15 minutes to remove excess water. Dry tofu is the difference between crisp edges and a soggy pan.", { minutes: 15 }),
      step(2, "Cook the rice", "Rinse rice, bring it with water to a boil in a lidded pot, then reduce to low and simmer 18 minutes. Rest 10 minutes off heat, then fluff.", { minutes: 28, heatLevel: "low" }),
      step(3, "Cube and coat the tofu", "Cut pressed tofu into 3/4-inch cubes and toss gently with cornstarch until lightly coated. The cornstarch is what creates the crisp shell in the pan.", { minutes: 8 }),
      step(4, "Crisp the tofu", "Heat oil in a wide skillet over medium-high. Add tofu in a single layer and let it sit undisturbed 3 minutes per side, turning occasionally, until golden and crisp on most sides, about 10 minutes total.", { minutes: 10, heatLevel: "medium-high" }),
      step(5, "Mix the sesame-ginger sauce", "Whisk soy sauce, rice vinegar, honey, ginger, and sesame oil in a small bowl until the honey dissolves. Toss half of it with the warm tofu right in the pan.", { minutes: 5 }),
      step(6, "Warm the edamame", "Steam or microwave edamame with a splash of water 3–4 minutes until hot. Toss with a pinch of salt.", { minutes: 4 }),
      step(7, "Build the bowls", "Layer rice, edamame, carrots, and cucumber in each bowl, top with crisped tofu, and drizzle the remaining sauce over the top. Finish with sesame seeds if using.", { minutes: 8 }),
      step(8, "Hold for a delayed line", "If service is delayed, hold tofu uncovered on a rack over a sheet pan in a 200°F oven so the crust stays crisp instead of steaming soft under a lid.", { minutes: 5, tempF: 200 }),
    ],
    proTips: [
      "Prep tip: Do not skip pressing the tofu — wet tofu will not crisp no matter how hot the pan is.",
      "Rookie tip: Let tofu sit undisturbed in the pan; flipping it too early tears off the crust.",
      "Add sriracha or chili crisp on the side for crews who want heat.",
      "Double the sauce batch and keep extra on hand — this dish tends to run out of sauce first.",
    ],
    tonightSpread: buildStructuredTonightSpread(
      "Sesame ginger tofu bowls",
      ["Steamed broccoli", "extra cucumber"],
      ["Sriracha", "extra sesame-ginger sauce"],
    ),
    leftovers: [
      "Store tofu separately from rice and re-crisp it in a dry skillet rather than the microwave.",
      "Cool rice and vegetables in shallow containers within two hours of cooking.",
      "Leftover tofu and vegetables work well cold, tossed with extra sauce, as a next-day lunch.",
    ],
    equipment: ["Rice pot", "Large skillet", "Mixing bowls", "Whisk"],
    nutrition: { calories: 584, protein: 35, carbs: 68, fats: 22, fiber: 8 },
    spiceLevel: "mild",
    cleanupDifficulty: "medium",
    searchTerms: [
      "tofu bowl",
      "high protein vegetarian bowl",
      "sesame ginger tofu",
      "crispy tofu rice bowl",
      "vegetarian meal prep bowl",
      "firehouse tofu bowl",
    ],
    substitutions: [
      "Use tempeh instead of tofu for a firmer, nuttier bite.",
      "Use brown rice or quinoa instead of jasmine rice.",
      "Use tamari instead of soy sauce for a gluten-free version.",
    ],
  }),

  def({
    slug: "firehouse-lentil-chili",
    title: "Firehouse Lentil Chili",
    subtitle: "A thick, vegetarian chili built on lentils, beans, and fire-roasted tomatoes",
    category: "crew_feeders",
    protein: "vegetarian",
    cuisine: "american",
    mealFormat: "soup_chili",
    explorePools: ["soup_chili", "vegetarian", "healthy", "meal_prep", "hall_expansion"],
    hookLine: "A one-pot vegetarian chili with enough lentils and beans that nobody misses the meat.",
    description:
      "Lentils, kidney beans, and fire-roasted tomatoes simmer together with chili spices into a thick, ladle-able chili. It is built for a big pot on a cold shift and holds beautifully for days.",
    whyCrewsLikeIt:
      "It is a genuine one-pot, low-cleanup dinner that happens to be vegetarian, and the lentils give it enough body and protein that it does not feel like a side dish.",
    mealPrepNotes:
      "Make-ahead: this chili is better on day two. Storage: refrigerate up to 5 days or freeze up to 3 months in portioned containers. Reheating: reheat covered on the stove with a splash of water or broth to loosen it back up.",
    stationWorkflow: [
      "Sweat the aromatics first so the chili base has real depth before the lentils go in.",
      "Simmer low and slow — a hard boil breaks the lentils down too much.",
      "Set the topping bar out only once the chili is close to done.",
    ],
    prepMinutes: 15,
    cookMinutes: 45,
    difficulty: "easy",
    crewSizeDefault: 8,
    ingredients: [
      ing("dried lentils", "2", { unit: "cups", notes: "rinsed", group: "Base" }),
      ing("olive oil", "3", { unit: "tbsp", group: "Base" }),
      ing("yellow onion", "1", { unit: "each", notes: "diced", group: "Base" }),
      ing("bell pepper", "2", { unit: "each", notes: "diced", group: "Base" }),
      ing("garlic", "4", { unit: "cloves", notes: "minced", group: "Base" }),
      ing("crushed tomato", "2", { unit: "cans", group: "Base" }),
      ing("kidney beans", "2", { unit: "cans", notes: "drained, rinsed", group: "Base" }),
      ing("vegetable broth", "5", { unit: "cups", group: "Base" }),
      ing("chili powder", "3", { unit: "tbsp", group: "Seasoning" }),
      ing("cumin", "2", { unit: "tbsp", group: "Seasoning" }),
      ing("smoked paprika", "1", { unit: "tbsp", group: "Seasoning" }),
      ing("shredded cheddar", "1.5", { unit: "cups", optional: true, group: "Toppings" }),
      ing("green onions", "0.5", { unit: "cup", optional: true, group: "Toppings" }),
    ],
    steps: [
      step(1, "Build the aromatic base", "Heat oil in a large pot over medium. Cook onion and bell pepper 5–6 minutes until softened, then add garlic and cook 1 more minute until fragrant.", { minutes: 8, heatLevel: "medium" }),
      step(2, "Add lentils, tomatoes, and spices", "Stir in rinsed lentils, crushed tomato, chili powder, cumin, and smoked paprika until everything is coated in the spiced tomato base.", { minutes: 4, heatLevel: "medium" }),
      step(3, "Simmer until the lentils soften", "Pour in vegetable broth, bring to a gentle boil, then reduce to a low simmer. Cook 30–35 minutes, stirring occasionally, until lentils are tender and the chili has thickened.", { minutes: 35, heatLevel: "low" }),
      step(4, "Fold in the beans", "Stir in kidney beans during the last 8 minutes of simmering, just long enough to heat through without breaking them down.", { minutes: 8, heatLevel: "low" }),
      step(5, "Adjust seasoning and thickness", "Taste and add salt, more chili powder, or a splash of broth if it has gotten too thick. A good chili should hold its shape on a spoon but still pour easily from a ladle.", { minutes: 5 }),
      step(6, "Hold and set the topping bar", "Keep chili at a bare simmer, covered, for holding. Set cheddar and green onions out only once it's close to service so the toppings stay fresh.", { minutes: 5, heatLevel: "low" }),
      CALL_INTERRUPTION_STEP(7, "lentil chili base"),
      LEFTOVERS_PACK_DOWN_STEP(8, "lentil chili"),
    ],
    proTips: [
      "Prep tip: Rinse lentils well and pick through for any small stones before cooking.",
      "Rookie tip: Resist boiling the chili hard — a gentle simmer keeps the lentils intact instead of turning to mush.",
      "This chili freezes exceptionally well; portion it before storing for fast reheats.",
      "Add a spoonful of cocoa powder or a square of dark chocolate for a deeper, restaurant-style chili flavor.",
    ],
    tonightSpread: buildStructuredTonightSpread(
      "Lentil chili",
      ["Cornbread", "simple green salad"],
      ["Shredded cheddar", "sour cream", "hot sauce"],
    ),
    leftovers: standardLeftovers("lentil chili", [
      "Freezes well in individual portions for up to 3 months.",
    ]),
    equipment: ["Large soup pot", "Wooden spoon", "Ladle"],
    nutrition: { calories: 272, protein: 14, carbs: 40, fats: 7, fiber: 16 },
    spiceLevel: "medium",
    cleanupDifficulty: "easy",
    searchTerms: [
      "lentil chili",
      "vegetarian chili",
      "high fiber vegetarian chili",
      "high fiber chili",
      "meal prep chili",
      "firehouse lentil chili",
    ],
    substitutions: [
      "Use black beans or pinto beans instead of kidney beans.",
      "Use diced sweet potato in place of half the lentils for a heartier texture.",
      "Add ground turkey if the crew wants a hybrid, still lighter chili.",
    ],
  }),

  def({
    slug: "chickpea-pasta-primavera-white-beans",
    title: "Chickpea Pasta Primavera with White Beans",
    subtitle: "High-protein chickpea pasta tossed with roasted vegetables, white beans, and parmesan",
    category: "crew_feeders",
    protein: "vegetarian",
    cuisine: "italian",
    mealFormat: "pasta",
    explorePools: ["pasta", "vegetarian", "healthy", "high_protein", "hall_expansion"],
    hookLine: "A pasta night with real protein built in, from the noodles all the way to the beans folded through.",
    description:
      "Chickpea pasta is tossed with roasted zucchini, bell pepper, and cherry tomatoes, then finished with white beans, garlic, and parmesan. It looks and eats like a normal pasta primavera with a genuinely higher protein count.",
    whyCrewsLikeIt:
      "It keeps the comfort of a pasta dinner while quietly doubling the protein of a standard vegetable pasta, and it is fully vegetarian without anyone needing to be told.",
    mealPrepNotes:
      "Make-ahead: roast vegetables up to two days ahead. Storage: keep pasta, vegetables, and beans together up to 4 days. Reheating: reheat with a splash of water or broth so the chickpea pasta doesn't dry out or turn gummy.",
    stationWorkflow: [
      "Roast vegetables while the pasta water comes to a boil so both finish close together.",
      "Cook chickpea pasta slightly under the package time — it firms up fast once tossed with hot vegetables.",
      "Toss everything together off heat so the parmesan melts without clumping.",
    ],
    prepMinutes: 15,
    cookMinutes: 25,
    difficulty: "easy",
    crewSizeDefault: 8,
    ingredients: [
      ing("chickpea pasta", "2", { unit: "lb", notes: "penne or rotini", group: "Base" }),
      ing("zucchini", "3", { unit: "each", notes: "sliced", group: "Vegetables" }),
      ing("bell pepper", "3", { unit: "each", notes: "sliced", group: "Vegetables" }),
      ing("cherry tomatoes", "3", { unit: "cups", group: "Vegetables" }),
      ing("olive oil", "0.33", { unit: "cup", group: "Vegetables" }),
      ing("cannellini beans", "2", { unit: "cans", notes: "drained, rinsed", group: "Base" }),
      ing("garlic", "4", { unit: "cloves", notes: "minced", group: "Base" }),
      ing("parmesan cheese", "1", { unit: "cup", notes: "grated", group: "Finish" }),
      ing("fresh basil", "0.5", { unit: "cup", notes: "torn", optional: true, group: "Finish" }),
      ing("red pepper flakes", "0.5", { unit: "tsp", optional: true, group: "Finish" }),
    ],
    steps: [
      step(1, "Roast the vegetables", "Heat the oven to 425°F. Toss zucchini, bell pepper, and cherry tomatoes with 3 tablespoons olive oil, salt, and pepper on a sheet pan. Roast 18–20 minutes until softened and lightly browned.", { minutes: 20, heatLevel: "medium-high", tempF: 425 }),
      step(2, "Cook the chickpea pasta", "Bring a large pot of salted water to a boil. Cook chickpea pasta 1–2 minutes under the package time — it firms and can turn mushy fast if overcooked. Drain, reserving 1/2 cup pasta water.", { minutes: 10, heatLevel: "high" }),
      step(3, "Warm the beans and garlic", "While pasta cooks, warm remaining olive oil in a large skillet over medium. Add garlic and cook 30 seconds until fragrant, then stir in cannellini beans and warm through, 3–4 minutes.", { minutes: 5, heatLevel: "medium" }),
      step(4, "Combine everything", "Add drained pasta, roasted vegetables, and a splash of reserved pasta water to the skillet with the beans. Toss over low heat 2 minutes so everything comes together and coats lightly.", { minutes: 4, heatLevel: "low" }),
      step(5, "Finish off heat", "Remove from heat and fold in parmesan so it melts into the sauce without clumping into a hot pan. Add basil and red pepper flakes if using.", { minutes: 4 }),
      step(6, "Hold and serve", "Hold covered at 140°F or above with a splash of extra pasta water if it thickens on standby. Serve with extra parmesan on the side.", { minutes: 5, heatLevel: "low" }),
      CALL_INTERRUPTION_STEP(7, "chickpea pasta and white beans"),
      LEFTOVERS_PACK_DOWN_STEP(8, "chickpea pasta primavera"),
    ],
    proTips: [
      "Prep tip: Chickpea pasta cooks faster than wheat pasta and turns mushy quickly — watch it closely near the end.",
      "Rookie tip: Reserve pasta water before draining; it is the easiest way to loosen the sauce without adding more fat.",
      "Add grilled chicken or shrimp on top for crews who want extra protein beyond the pasta and beans.",
      "Swap in whatever roastable vegetables are on hand — this recipe is forgiving.",
    ],
    tonightSpread: buildStructuredTonightSpread(
      "Chickpea pasta primavera",
      ["Simple green salad", "garlic bread"],
      ["Extra parmesan", "red pepper flakes"],
    ),
    leftovers: standardLeftovers("chickpea pasta primavera", [
      "Reheat with a splash of water or broth — chickpea pasta dries out faster than wheat pasta.",
    ]),
    equipment: ["Large pot", "Sheet pan", "Large skillet", "Colander"],
    nutrition: { calories: 636, protein: 39, carbs: 86, fats: 20, fiber: 12 },
    spiceLevel: "mild",
    cleanupDifficulty: "easy",
    searchTerms: [
      "chickpea pasta",
      "high protein pasta",
      "vegetarian pasta primavera",
      "high protein vegetarian dinner",
      "chickpea pasta recipe",
      "firehouse pasta primavera",
    ],
    substitutions: [
      "Use lentil pasta or regular whole wheat pasta if chickpea pasta isn't available.",
      "Use great northern beans instead of cannellini beans.",
      "Add spinach in the last minute of tossing for extra greens.",
    ],
  }),

  def({
    slug: "southwest-black-bean-corn-bowls",
    title: "Southwest Black Bean & Corn Bowls",
    subtitle: "A cold, meal-prep-friendly bowl of black beans, corn, quinoa, and avocado with lime dressing",
    category: "crew_feeders",
    protein: "vegetarian",
    cuisine: "mexican",
    mealFormat: "salad",
    explorePools: ["salad", "vegetarian", "healthy", "meal_prep", "hall_expansion"],
    hookLine: "A fully vegetarian, no-reheat bowl that holds in the fridge as well as it holds up on flavor.",
    description:
      "Quinoa, black beans, roasted corn, bell pepper, and avocado come together with a lime-cumin dressing. It is served cold or at room temperature and is built specifically to pack well for several days.",
    whyCrewsLikeIt:
      "No stove time is needed at the point of service, it travels well in individual containers, and it gives the crew a genuine vegetarian option that still reads as a full meal.",
    mealPrepNotes:
      "Make-ahead: this bowl is designed entirely for advance prep. Storage: keep quinoa, beans, corn, and pepper together up to 5 days; add avocado and dressing just before eating. Reheating: none required — serve cold or room temperature.",
    stationWorkflow: [
      "Cook quinoa ahead of time and let it cool fully before mixing with dressing.",
      "Char corn in a dry skillet for real flavor rather than just heating it through.",
      "Add avocado only at serving time so it doesn't brown in storage.",
    ],
    prepMinutes: 20,
    cookMinutes: 15,
    difficulty: "easy",
    crewSizeDefault: 8,
    ingredients: [
      ing("quinoa", "2", { unit: "cups", notes: "uncooked, rinsed", group: "Base" }),
      ing("black beans", "2", { unit: "cans", notes: "drained, rinsed", group: "Base" }),
      ing("corn", "3", { unit: "cups", group: "Base" }),
      ing("bell pepper", "2", { unit: "each", notes: "diced", group: "Base" }),
      ing("red onion", "0.5", { unit: "each", notes: "finely diced", group: "Base" }),
      ing("avocado", "3", { unit: "each", notes: "diced", group: "Finish" }),
      ing("fresh cilantro", "0.5", { unit: "cup", notes: "chopped", group: "Finish" }),
      ing("lime juice", "0.33", { unit: "cup", group: "Dressing" }),
      ing("olive oil", "0.25", { unit: "cup", group: "Dressing" }),
      ing("cumin", "1", { unit: "tbsp", group: "Dressing" }),
      ing("chili powder", "1", { unit: "tsp", group: "Dressing" }),
    ],
    steps: [
      step(1, "Cook the quinoa", "Rinse quinoa well, then simmer with water in a lidded pot 15 minutes until tender and the liquid is absorbed. Fluff and spread on a sheet pan to cool quickly so it doesn't turn mushy in the dressing.", { minutes: 20, heatLevel: "low" }),
      step(2, "Char the corn", "Toast corn in a dry, wide skillet over medium-high 4–5 minutes, stirring occasionally, until several kernels brown. Set aside to cool.", { minutes: 6, heatLevel: "medium-high" }),
      step(3, "Dice the vegetables", "Dice bell pepper and red onion into a small, even size so they distribute evenly through the grain base.", { minutes: 8 }),
      step(4, "Mix the lime-cumin dressing", "Whisk lime juice, olive oil, cumin, chili powder, and a pinch of salt until combined.", { minutes: 4 }),
      step(5, "Combine and dress the base", "Toss cooled quinoa with black beans, charred corn, bell pepper, and red onion. Pour dressing over and toss well to coat everything evenly.", { minutes: 6 }),
      step(6, "Add avocado and cilantro at the end", "Fold in diced avocado and cilantro right before serving, or hold them separately if packing ahead so the avocado doesn't brown or turn mushy.", { minutes: 4 }),
    ],
    proTips: [
      "Prep tip: Cool quinoa fully before dressing it, or the heat will wilt the vegetables and dull the lime flavor.",
      "Rookie tip: Pack avocado in its own small container for multi-day meal prep and add it fresh each time.",
      "Add grilled chicken or shrimp on top for crews who want more protein than the beans and quinoa provide alone.",
      "A squeeze of extra lime right before eating brightens up bowls that have been in the fridge a couple of days.",
    ],
    tonightSpread: buildStructuredTonightSpread(
      "Southwest black bean and corn bowls",
      ["Tortilla chips", "extra lime wedges"],
      ["Hot sauce", "extra cilantro"],
    ),
    leftovers: [
      "Keeps well covered and cold for up to 5 days without the avocado.",
      "Add avocado fresh to each portion rather than mixing it into the full batch ahead of time.",
      "Serve leftovers over greens or wrapped in a tortilla for variety.",
    ],
    equipment: ["Medium pot", "Sheet pan", "Skillet", "Mixing bowls"],
    nutrition: { calories: 458, protein: 15, carbs: 63, fats: 19, fiber: 14 },
    spiceLevel: "mild",
    cleanupDifficulty: "easy",
    searchTerms: [
      "black bean corn bowl",
      "vegetarian meal prep bowl",
      "quinoa black bean bowl",
      "high fiber meal prep",
      "southwest quinoa salad",
      "firehouse black bean bowl",
    ],
    substitutions: [
      "Use brown rice instead of quinoa.",
      "Use pinto beans instead of black beans.",
      "Add crumbled feta or cotija for extra flavor and protein.",
    ],
  }),

  def({
    slug: "firehouse-turkey-white-bean-soup",
    title: "Firehouse Turkey & White Bean Soup",
    subtitle: "A hearty, lower-fat soup built on lean ground turkey, white beans, and greens",
    category: "crew_feeders",
    protein: "turkey",
    cuisine: "american",
    mealFormat: "soup_chili",
    explorePools: ["soup_chili", "turkey", "healthy", "high_protein", "meal_prep", "hall_expansion"],
    hookLine: "A big-pot soup that trades heavy cream and sausage for lean turkey and beans without losing body.",
    description:
      "Ground turkey browns with onion, carrot, and celery, then simmers with white beans, chicken broth, and kale into a thick, ladle-able soup. It is a lighter alternative to the hall's cream-based soup nights.",
    whyCrewsLikeIt:
      "It still feels like a real cold-weather soup night, holds well in a big pot for staggered eating, and comes in noticeably lighter than a cream-based chowder without sacrificing how filling it is.",
    mealPrepNotes:
      "Make-ahead: this soup holds and reheats exceptionally well. Storage: refrigerate up to 5 days or freeze up to 3 months. Reheating: reheat covered on the stove, adding a splash of broth since it thickens as it sits.",
    stationWorkflow: [
      "Brown the turkey in batches so it browns instead of steaming in its own liquid.",
      "Simmer gently once the broth goes in — a hard boil breaks down the beans too much.",
      "Add kale at the very end so it stays bright, not gray and overcooked.",
    ],
    prepMinutes: 15,
    cookMinutes: 35,
    difficulty: "easy",
    crewSizeDefault: 8,
    ingredients: [
      ing("ground turkey", "2", { unit: "lb", group: "Protein" }),
      ing("olive oil", "2", { unit: "tbsp", group: "Base" }),
      ing("yellow onion", "1", { unit: "each", notes: "diced", group: "Base" }),
      ing("carrots", "3", { unit: "each", notes: "diced", group: "Base" }),
      ing("celery", "3", { unit: "stalks", notes: "diced", group: "Base" }),
      ing("garlic", "4", { unit: "cloves", notes: "minced", group: "Base" }),
      ing("chicken broth", "8", { unit: "cups", group: "Base" }),
      ing("cannellini beans", "3", { unit: "cans", notes: "drained, rinsed", group: "Base" }),
      ing("dried thyme", "1", { unit: "tsp", group: "Seasoning" }),
      ing("bay leaf", "1", { unit: "whole", group: "Seasoning" }),
      ing("kale", "4", { unit: "cups", notes: "chopped, stems removed", group: "Greens" }),
      ing("parmesan cheese", "0.5", { unit: "cup", notes: "grated", optional: true, group: "Finish" }),
    ],
    steps: [
      step(1, "Brown the turkey", "Heat 1 tablespoon oil in a large pot over medium-high. Brown ground turkey in batches 6–7 minutes per batch, breaking it into crumbles, until no pink remains. Set aside.", { minutes: 12, heatLevel: "medium-high" }),
      step(2, "Sweat the vegetables", "Add remaining oil to the same pot with onion, carrots, and celery. Cook 6–7 minutes until softened, then add garlic and cook 1 more minute.", { minutes: 8, heatLevel: "medium" }),
      step(3, "Build the soup base", "Return turkey to the pot along with chicken broth, cannellini beans, thyme, and bay leaf. Bring to a boil, then reduce to a gentle simmer.", { minutes: 5, heatLevel: "medium" }),
      step(4, "Simmer to develop flavor", "Simmer uncovered 20–25 minutes, stirring occasionally, until the vegetables are tender and the broth has thickened slightly from the beans breaking down at the edges.", { minutes: 25, heatLevel: "low" }),
      step(5, "Finish with kale", "Remove the bay leaf. Stir in kale during the last 3–4 minutes just until wilted and bright green — overcooking turns it dull and bitter.", { minutes: 4, heatLevel: "low" }),
      step(6, "Hold and serve", "Keep the soup at a bare simmer for holding, stirring occasionally. Serve with parmesan on the side if using.", { minutes: 5, heatLevel: "low" }),
      CALL_INTERRUPTION_STEP(7, "turkey and white bean soup"),
      LEFTOVERS_PACK_DOWN_STEP(8, "turkey and white bean soup"),
    ],
    proTips: [
      "Prep tip: Brown the turkey in batches — crowding the pot steams it instead of browning it.",
      "Rookie tip: Add kale at the very end; it only needs a few minutes to wilt properly.",
      "This soup thickens overnight — add extra broth when reheating leftovers.",
      "Swap kale for spinach if that's what's on hand; add it off heat since spinach wilts almost instantly.",
    ],
    tonightSpread: buildStructuredTonightSpread(
      "Turkey and white bean soup",
      ["Crusty bread", "simple green salad"],
      ["Grated parmesan", "red pepper flakes"],
    ),
    leftovers: standardLeftovers("turkey and white bean soup", [
      "Freezes well in individual portions for up to 3 months.",
    ]),
    equipment: ["Large soup pot", "Wooden spoon", "Ladle"],
    nutrition: { calories: 405, protein: 37, carbs: 29, fats: 14, fiber: 9 },
    spiceLevel: "mild",
    cleanupDifficulty: "easy",
    searchTerms: [
      "turkey white bean soup",
      "high protein soup",
      "lean turkey soup",
      "healthy soup recipe",
      "meal prep soup",
      "firehouse turkey soup",
    ],
    substitutions: [
      "Use ground chicken instead of turkey.",
      "Use great northern beans or navy beans instead of cannellini beans.",
      "Use spinach instead of kale.",
    ],
  }),

  def({
    slug: "sheet-pan-lemon-chicken-broccoli-sweet-potatoes",
    title: "Sheet-Pan Lemon Chicken with Broccoli & Sweet Potatoes",
    subtitle: "A one-pan, lighter dinner of lemon-herb chicken with roasted broccoli and sweet potato",
    category: "crew_feeders",
    protein: "chicken",
    cuisine: "american",
    mealFormat: "sheet_pan",
    explorePools: ["sheet_pan", "chicken", "healthy", "high_protein", "hall_expansion"],
    hookLine: "A genuinely lighter sheet-pan dinner with real lemon-herb flavor and almost no cleanup.",
    description:
      "Chicken breast, broccoli, and sweet potato roast together on sheet pans with a lemon-herb marinade, finished with a squeeze of fresh lemon. It is a straightforward, lower-calorie dinner with one pan per station and little cleanup.",
    whyCrewsLikeIt:
      "It is fast to put together, uses one or two pans total, and gives crews a genuinely lighter dinner night without feeling like a diet plate.",
    mealPrepNotes:
      "Make-ahead: marinate chicken up to a day ahead. Storage: keep chicken and vegetables together up to 4 days. Reheating: reheat covered at 350°F for 10 minutes, or in a skillet to re-crisp the vegetables.",
    stationWorkflow: [
      "Marinate chicken while vegetables are being cut so nothing sits idle.",
      "Give broccoli and sweet potato their own pan or side of the pan — they cook at different rates.",
      "Finish with fresh lemon juice off the oven, not before, so it stays bright.",
    ],
    prepMinutes: 15,
    cookMinutes: 30,
    difficulty: "easy",
    crewSizeDefault: 8,
    ingredients: [
      ing("chicken breast", "3", { unit: "lb", notes: "cut into even pieces", group: "Protein" }),
      ing("lemon juice", "0.33", { unit: "cup", group: "Marinade" }),
      ing("olive oil", "0.33", { unit: "cup", group: "Marinade" }),
      ing("dried oregano", "1", { unit: "tbsp", group: "Marinade" }),
      ing("garlic", "4", { unit: "cloves", notes: "minced", group: "Marinade" }),
      ing("sweet potato", "3", { unit: "lb", notes: "3/4-inch cubes", group: "Vegetables" }),
      ing("broccoli florets", "2.5", { unit: "lb", group: "Vegetables" }),
      ing("olive oil", "3", { unit: "tbsp", group: "Vegetables" }),
      ing("lemon", "2", { unit: "each", notes: "for zest and wedges", group: "Finish" }),
    ],
    steps: [
      step(1, "Marinate the chicken", "Whisk lemon juice, olive oil, oregano, garlic, salt, and pepper. Add chicken and turn to coat. Let it marinate at least 15 minutes while the oven heats and vegetables are cut.", { minutes: 15 }),
      step(2, "Start the sweet potato", "Heat the oven to 425°F. Toss sweet potato with 2 tablespoons olive oil, salt, and pepper on a sheet pan and roast 12 minutes to give it a head start over the faster-cooking broccoli and chicken.", { minutes: 12, heatLevel: "medium-high", tempF: 425 }),
      step(3, "Add chicken and broccoli", "Toss broccoli with remaining oil, salt, and pepper. Add marinated chicken and broccoli to the pan with the sweet potato, spreading everything into a single layer across one or two pans as needed.", { minutes: 5 }),
      step(4, "Roast until everything is cooked through", "Roast 16–18 minutes, until chicken reaches 165°F, broccoli is browned at the tips, and sweet potato is fork-tender. Rotate pans halfway if using two ovens racks.", { minutes: 18, heatLevel: "medium-high", tempF: 425 }),
      step(5, "Finish with lemon", "Pull the pan from the oven and immediately zest a lemon over everything while it's hot — the citrus oils bloom in the heat. Squeeze lemon wedges over individual portions at serving.", { minutes: 4 }),
      step(6, "Hold for a delayed line", "If service is delayed, hold everything loosely covered in a 200°F oven. Add the lemon zest and juice only right before serving so it doesn't turn bitter sitting on hot food.", { minutes: 5, tempF: 200 }),
      CALL_INTERRUPTION_STEP(7, "lemon-herb chicken"),
      LEFTOVERS_PACK_DOWN_STEP(8, "lemon-herb chicken"),
    ],
    proTips: [
      "Prep tip: Give the sweet potato a head start — it takes longer than chicken and broccoli.",
      "Rookie tip: Add lemon zest right when the pan comes out of the oven; the heat brings out more citrus flavor.",
      "Cut chicken into even pieces so everything finishes cooking at the same time.",
      "Use two sheet pans rather than crowding one — crowded vegetables steam instead of roast.",
    ],
    tonightSpread: buildStructuredTonightSpread(
      "Sheet-pan lemon chicken with broccoli and sweet potatoes",
      ["Simple green salad", "crusty bread"],
      ["Extra lemon wedges", "hot sauce"],
    ),
    leftovers: standardLeftovers("lemon-herb chicken", [
      "Reheat in a skillet over medium heat to re-crisp the vegetables rather than microwaving them soft.",
    ]),
    equipment: ["Two sheet pans", "Mixing bowls", "Instant-read thermometer"],
    nutrition: { calories: 615, protein: 59, carbs: 47, fats: 21, fiber: 7 },
    spiceLevel: "mild",
    cleanupDifficulty: "easy",
    searchTerms: [
      "sheet pan chicken dinner",
      "lighter chicken dinner",
      "high protein sheet pan dinner",
      "lemon chicken broccoli sweet potato",
      "healthy sheet pan dinner",
      "firehouse sheet pan chicken",
    ],
    substitutions: [
      "Use chicken thighs instead of breast for a juicier result.",
      "Use cauliflower instead of broccoli.",
      "Use white fish in place of chicken for an even lighter option.",
    ],
  }),

  def({
    slug: "high-protein-chicken-quinoa-meal-prep-bowls",
    title: "High-Protein Chicken & Quinoa Meal-Prep Bowls",
    subtitle: "Roasted chicken and quinoa with vegetables, built specifically for individual meal-prep containers",
    category: "crew_feeders",
    protein: "chicken",
    cuisine: "american",
    mealFormat: "bowl",
    explorePools: ["bowl", "chicken", "healthy", "high_protein", "meal_prep", "hall_expansion"],
    hookLine: "A no-frills, high-protein bowl built to portion straight into containers for the week.",
    description:
      "Roasted chicken thighs, quinoa, and roasted vegetables are portioned into individual containers with a simple herb dressing on the side, designed specifically for crews prepping meals ahead of a shift.",
    whyCrewsLikeIt:
      "It is built for the reality of shift work — portioned, labeled, and ready to grab — with a protein and fiber count that holds crews over during a long stretch without a real meal break.",
    mealPrepNotes:
      "Make-ahead: this recipe is built entirely for advance portioning. Storage: pack into 8 individual containers; refrigerate up to 4 days or freeze up to 2 months without the dressing. Reheating: heat to 165°F, then add dressing after.",
    stationWorkflow: [
      "Roast chicken and vegetables on separate pans since they cook at different rates.",
      "Cook quinoa while everything else roasts to keep the timeline tight.",
      "Portion into containers while everything is still slightly warm, then cool with lids off before sealing.",
    ],
    prepMinutes: 20,
    cookMinutes: 30,
    difficulty: "easy",
    crewSizeDefault: 8,
    ingredients: [
      ing("chicken thighs", "3", { unit: "lb", notes: "boneless, skinless", group: "Protein" }),
      ing("olive oil", "3", { unit: "tbsp", group: "Protein" }),
      ing("garlic powder", "1", { unit: "tbsp", group: "Protein" }),
      ing("smoked paprika", "1", { unit: "tbsp", group: "Protein" }),
      ing("quinoa", "2", { unit: "cups", notes: "uncooked, rinsed", group: "Base" }),
      ing("broccoli florets", "2", { unit: "lb", group: "Vegetables" }),
      ing("bell pepper", "3", { unit: "each", notes: "sliced", group: "Vegetables" }),
      ing("olive oil", "2", { unit: "tbsp", group: "Vegetables" }),
      ing("lemon juice", "3", { unit: "tbsp", group: "Dressing" }),
      ing("olive oil", "3", { unit: "tbsp", group: "Dressing" }),
      ing("dried oregano", "1", { unit: "tsp", group: "Dressing" }),
    ],
    steps: [
      step(1, "Season and roast the chicken", "Heat the oven to 425°F. Toss chicken thighs with olive oil, garlic powder, smoked paprika, salt, and pepper on a sheet pan. Roast 22–25 minutes until 165°F at the thickest point.", { minutes: 25, heatLevel: "medium-high", tempF: 425 }),
      step(2, "Cook the quinoa", "Rinse quinoa and simmer with water in a lidded pot 15 minutes until tender. Fluff and spread on a sheet pan to cool.", { minutes: 20, heatLevel: "low" }),
      step(3, "Roast the vegetables", "Toss broccoli and bell pepper with olive oil, salt, and pepper on a separate sheet pan. Roast 16–18 minutes alongside the chicken until tender with browned edges.", { minutes: 18, heatLevel: "medium-high", tempF: 425 }),
      step(4, "Mix the dressing", "Whisk lemon juice, olive oil, oregano, salt, and pepper in a small container. Keep it separate from the bowls until eating time.", { minutes: 4 }),
      step(5, "Slice the chicken", "Rest chicken 5 minutes, then slice into strips for even portioning across containers.", { minutes: 5 }),
      step(6, "Portion into containers", "Divide quinoa, roasted vegetables, and sliced chicken evenly across 8 containers. Let everything cool with lids off for 15–20 minutes before sealing and refrigerating.", { minutes: 15 }),
    ],
    proTips: [
      "Prep tip: Let food cool before sealing containers — trapped steam leads to soggy quinoa and shortens shelf life.",
      "Rookie tip: Keep the dressing in small separate cups so vegetables stay crisp until the moment of eating.",
      "Weigh or eyeball even portions across containers so everyone gets a consistent amount of protein.",
      "Label containers with the date — this recipe is meant for the fridge, not indefinite storage.",
    ],
    tonightSpread: buildStructuredTonightSpread(
      "Chicken and quinoa meal-prep bowls",
      ["Extra roasted vegetables", "fresh fruit"],
      ["Hot sauce", "extra lemon dressing"],
    ),
    leftovers: [
      "Refrigerate portioned containers up to 4 days, or freeze without dressing up to 2 months.",
      "Reheat covered to 165°F, then add dressing after reheating so vegetables don't turn soggy.",
      "Thaw frozen portions overnight in the refrigerator before reheating.",
    ],
    equipment: ["Two sheet pans", "Medium pot", "Meal-prep containers", "Instant-read thermometer"],
    nutrition: { calories: 621, protein: 62, carbs: 39, fats: 23, fiber: 7 },
    spiceLevel: "mild",
    cleanupDifficulty: "easy",
    searchTerms: [
      "high protein meal prep bowl",
      "chicken quinoa meal prep",
      "meal prep containers",
      "high protein lunch prep",
      "healthy meal prep bowl",
      "firehouse meal prep",
    ],
    substitutions: [
      "Use chicken breast instead of thighs for a leaner version.",
      "Use brown rice instead of quinoa.",
      "Use zucchini or green beans instead of broccoli.",
    ],
  }),

  def({
    slug: "lemon-herb-cod-roasted-vegetables",
    title: "Lemon-Herb Cod with Roasted Vegetables",
    subtitle: "Flaky baked cod with roasted zucchini, tomatoes, and potatoes in a lemon-herb butter",
    category: "crew_feeders",
    protein: "seafood",
    cuisine: "american",
    mealFormat: "bake",
    explorePools: ["bake", "seafood", "healthy", "high_protein", "hall_expansion"],
    hookLine: "A lean, lighter fish dinner that still feels like a real cooked meal, not a diet substitute.",
    description:
      "Cod fillets bake under a lemon-herb butter alongside zucchini, cherry tomatoes, and baby potatoes. It is a genuinely lighter dinner option with lean protein and roasted vegetables, built to be simple rather than fussy.",
    whyCrewsLikeIt:
      "It gives crews a real lighter-calorie option on nights when the hall wants to ease off heavier meals, without turning dinner into a salad — everything still comes out of the oven hot and finished.",
    mealPrepNotes:
      "Make-ahead: potatoes can be par-cooked a day ahead. Storage: keep cod and vegetables together up to 3 days. Reheating: reheat covered at 300°F just until warm — cod dries out fast at high heat.",
    stationWorkflow: [
      "Par-cook potatoes first since they take longer than the cod or other vegetables.",
      "Add cod to the pan last so it doesn't overcook while other vegetables finish.",
      "Check cod for doneness by flake, not just time — thickness varies fillet to fillet.",
    ],
    prepMinutes: 15,
    cookMinutes: 30,
    difficulty: "easy",
    crewSizeDefault: 8,
    ingredients: [
      ing("cod fillet", "3", { unit: "lb", notes: "cut into 8 portions", group: "Protein" }),
      ing("baby potatoes", "2.5", { unit: "lb", notes: "halved", group: "Vegetables" }),
      ing("zucchini", "3", { unit: "each", notes: "sliced", group: "Vegetables" }),
      ing("cherry tomatoes", "2", { unit: "cups", group: "Vegetables" }),
      ing("butter", "4", { unit: "tbsp", notes: "melted", group: "Sauce" }),
      ing("lemon juice", "3", { unit: "tbsp", group: "Sauce" }),
      ing("garlic", "3", { unit: "cloves", notes: "minced", group: "Sauce" }),
      ing("fresh parsley", "0.25", { unit: "cup", notes: "chopped", group: "Sauce" }),
      ing("dried thyme", "1", { unit: "tsp", group: "Sauce" }),
      ing("olive oil", "3", { unit: "tbsp", group: "Vegetables" }),
    ],
    steps: [
      step(1, "Par-cook the potatoes", "Heat the oven to 400°F. Toss halved baby potatoes with olive oil, salt, and pepper on a sheet pan and roast 15 minutes to give them a head start over the faster-cooking vegetables.", { minutes: 15, heatLevel: "medium-high", tempF: 400 }),
      step(2, "Mix the lemon-herb butter", "Whisk melted butter with lemon juice, garlic, parsley, and thyme in a small bowl until combined.", { minutes: 4 }),
      step(3, "Add zucchini and tomatoes", "Add zucchini and cherry tomatoes to the pan with the potatoes, tossing lightly with a bit more oil, salt, and pepper.", { minutes: 3 }),
      step(4, "Add the cod and butter sauce", "Pat cod dry and season with salt and pepper. Nestle cod portions among the vegetables and spoon the lemon-herb butter evenly over the fish.", { minutes: 5 }),
      step(5, "Bake until cod flakes easily", "Bake 12–15 minutes until cod is opaque and flakes easily with a fork and vegetables are tender. Cod is done by texture, not just a clock — check the thickest fillet.", { minutes: 15, heatLevel: "medium-high", tempF: 400 }),
      step(6, "Hold and serve", "If service is delayed, hold covered loosely at 200°F for no more than 15 minutes — cod continues to firm up and can dry out if held too long.", { minutes: 5, tempF: 200 }),
    ],
    proTips: [
      "Prep tip: Pat cod completely dry before seasoning so the butter sauce actually clings instead of sliding off.",
      "Rookie tip: Check cod a few minutes early — it goes from tender to dry quickly once it passes done.",
      "Use haddock or tilapia if cod isn't available; cook times are similar.",
      "Squeeze fresh lemon over the finished dish right before serving for extra brightness.",
    ],
    tonightSpread: buildStructuredTonightSpread(
      "Lemon-herb cod with roasted vegetables",
      ["Crusty bread", "simple green salad"],
      ["Extra lemon wedges", "melted butter"],
    ),
    leftovers: [
      "Cool cod and vegetables in a shallow pan within two hours; reheat gently at 300°F, not high heat.",
      "Store cod and vegetables together — they hold reasonably well for up to 3 days.",
      "Flake leftover cod over greens for a fast, no-cook next-day lunch.",
    ],
    equipment: ["Sheet pan", "Mixing bowls", "Fish spatula"],
    nutrition: { calories: 574, protein: 41, carbs: 28, fats: 32, fiber: 5 },
    spiceLevel: "mild",
    cleanupDifficulty: "easy",
    searchTerms: [
      "baked cod dinner",
      "lighter fish dinner",
      "lemon herb cod",
      "healthy sheet pan fish",
      "lean protein dinner",
      "firehouse cod dinner",
    ],
    substitutions: [
      "Use haddock, tilapia, or halibut instead of cod.",
      "Use olive oil instead of butter for a dairy-free version.",
      "Add asparagus in place of zucchini when in season.",
    ],
  }),

  def({
    slug: "garlic-steak-broccoli-cottage-cheese-bowls",
    title: "Garlic Steak & Broccoli Bowls with Herbed Cottage Cheese",
    subtitle: "Seared steak strips and roasted broccoli over rice with a garlic-herb cottage cheese sauce",
    category: "crew_feeders",
    protein: "beef",
    cuisine: "american",
    mealFormat: "bowl",
    explorePools: ["bowl", "beef", "healthy", "high_protein", "hall_expansion"],
    hookLine: "A steak-and-broccoli bowl that swaps a heavy cream sauce for a garlic-herb cottage cheese blend.",
    description:
      "Seared sirloin strips and roasted broccoli sit over rice, finished with a smooth garlic-herb cottage cheese sauce blended until creamy. It reads like a steakhouse plate with a real per-serving protein boost.",
    whyCrewsLikeIt:
      "It gives steak-night fans a genuine reason to try cottage cheese — blended smooth, it tastes like a herb sauce, not a diet ingredient — while keeping the protein count well above a normal steak dinner.",
    mealPrepNotes:
      "Make-ahead: the cottage cheese sauce holds 4 days blended and covered. Storage: keep steak, rice, broccoli, and sauce in separate containers up to 3 days. Reheating: reheat steak and rice to 165°F; add sauce cold or gently warmed, never boiled.",
    stationWorkflow: [
      "Start rice first, then roast broccoli while the steak rests before slicing.",
      "Sear steak hard and fast — overcooking is the main risk with thin strips.",
      "Blend the cottage cheese sauce while the steak rests so it's ready to plate immediately.",
    ],
    prepMinutes: 15,
    cookMinutes: 25,
    difficulty: "medium",
    crewSizeDefault: 8,
    ingredients: [
      ing("sirloin steak", "3", { unit: "lb", notes: "sliced into strips", group: "Protein" }),
      ing("olive oil", "2", { unit: "tbsp", group: "Protein" }),
      ing("garlic powder", "1", { unit: "tbsp", group: "Protein" }),
      ing("jasmine rice", "2.5", { unit: "cups", notes: "uncooked", group: "Base" }),
      ing("broccoli florets", "2.5", { unit: "lb", group: "Vegetables" }),
      ing("olive oil", "3", { unit: "tbsp", group: "Vegetables" }),
      ing("cottage cheese", "2", { unit: "cups", group: "Sauce" }),
      ing("garlic", "3", { unit: "cloves", group: "Sauce" }),
      ing("fresh chives", "0.25", { unit: "cup", notes: "chopped", group: "Sauce" }),
      ing("lemon juice", "1", { unit: "tbsp", group: "Sauce" }),
    ],
    steps: [
      step(1, "Cook the rice", "Rinse rice, bring it with water to a boil in a lidded pot, then reduce to low and simmer 18 minutes. Rest 10 minutes, then fluff.", { minutes: 28, heatLevel: "low" }),
      step(2, "Roast the broccoli", "Heat the oven to 425°F. Toss broccoli with oil, salt, and pepper on a sheet pan and roast 15–18 minutes until browned at the tips and crisp-tender.", { minutes: 18, heatLevel: "medium-high", tempF: 425 }),
      step(3, "Blend the cottage cheese sauce", "Blend cottage cheese, garlic, chives, lemon juice, and a pinch of salt until completely smooth. Thin with a splash of water if it's too thick to drizzle.", { minutes: 5 }),
      step(4, "Sear the steak", "Pat steak strips dry and season with garlic powder, salt, and pepper. Sear in a very hot skillet in batches, 60–90 seconds per side, until browned outside and medium-rare to medium inside.", { minutes: 10, heatLevel: "high" }),
      step(5, "Rest the steak", "Rest steak 5 minutes on a plate before serving — cutting or plating it immediately loses the juices onto the board instead of the bowl.", { minutes: 5 }),
      step(6, "Build the bowls", "Layer rice and broccoli in each bowl, top with seared steak strips, and finish with a generous drizzle of the garlic-herb cottage cheese sauce.", { minutes: 8 }),
      CALL_INTERRUPTION_STEP(7, "seared steak strips"),
      LEFTOVERS_PACK_DOWN_STEP(8, "seared steak strips"),
    ],
    proTips: [
      "Prep tip: Slice steak thin and against the grain so it stays tender through a fast, hot sear.",
      "Rookie tip: Blend the cottage cheese sauce until fully smooth — a few seconds longer than you think it needs.",
      "Use flank or flat iron steak as a budget-friendly swap for sirloin.",
      "Keep the skillet very hot; thin steak strips need speed more than time.",
    ],
    tonightSpread: buildStructuredTonightSpread(
      "Garlic steak and broccoli bowls",
      ["Simple green salad", "crusty bread"],
      ["Extra cottage cheese sauce", "hot sauce"],
    ),
    leftovers: standardLeftovers("seared steak strips", [
      "Reheat steak gently in a covered skillet rather than the microwave to avoid overcooking it further.",
    ]),
    equipment: ["Rice pot", "Sheet pan", "Blender", "Large skillet"],
    nutrition: { calories: 855, protein: 58, carbs: 59, fats: 43, fiber: 6 },
    spiceLevel: "mild",
    cleanupDifficulty: "medium",
    searchTerms: [
      "steak broccoli bowl",
      "cottage cheese sauce",
      "high protein steak bowl",
      "steak rice bowl",
      "high protein dinner bowl",
      "firehouse steak bowl",
    ],
    substitutions: [
      "Use flank steak or flat iron steak instead of sirloin.",
      "Use Greek yogurt instead of cottage cheese for the sauce.",
      "Use cauliflower rice for a lower-carb base.",
    ],
  }),

  def({
    slug: "honey-mustard-turkey-meatball-bowls",
    title: "Honey Mustard Turkey Meatball Bowls",
    subtitle: "Baked turkey meatballs with roasted vegetables and rice in a honey mustard drizzle",
    category: "crew_feeders",
    protein: "turkey",
    cuisine: "american",
    mealFormat: "bowl",
    explorePools: ["bowl", "turkey", "healthy", "high_protein", "meal_prep", "hall_expansion"],
    hookLine: "A meatball night rebuilt into a bowl format with a genuinely different sauce than the usual marinara.",
    description:
      "Baked lean turkey meatballs sit over rice and roasted green beans with a tangy honey mustard drizzle. It gives the hall's meatball rotation a real change of pace without extra complexity.",
    whyCrewsLikeIt:
      "It reuses a familiar format — meatballs and a starch — with a completely different flavor direction, and the leaner turkey keeps the protein count high without a heavy sauce weighing it down.",
    mealPrepNotes:
      "Make-ahead: meatballs can be baked up to 2 days ahead and reheated. Storage: keep meatballs, rice, and vegetables together up to 4 days; keep sauce separate if packing for multiple days. Reheating: reheat to 165°F, then top with sauce.",
    stationWorkflow: [
      "Bake meatballs and roast green beans on separate pans at the same time to save oven time.",
      "Cook rice while the oven is working so everything lands together.",
      "Mix the honey mustard sauce last so it stays fresh and doesn't separate.",
    ],
    prepMinutes: 20,
    cookMinutes: 25,
    difficulty: "easy",
    crewSizeDefault: 8,
    ingredients: [
      ing("ground turkey", "2.5", { unit: "lb", group: "Protein" }),
      ing("breadcrumbs", "1", { unit: "cup", group: "Protein" }),
      ing("egg", "2", { unit: "each", group: "Protein" }),
      ing("garlic", "3", { unit: "cloves", notes: "minced", group: "Protein" }),
      ing("dried oregano", "1", { unit: "tbsp", group: "Protein" }),
      ing("jasmine rice", "2.5", { unit: "cups", notes: "uncooked", group: "Base" }),
      ing("green beans", "2.5", { unit: "lb", notes: "trimmed", group: "Vegetables" }),
      ing("olive oil", "3", { unit: "tbsp", group: "Vegetables" }),
      ing("dijon mustard", "0.33", { unit: "cup", group: "Sauce" }),
      ing("honey", "0.25", { unit: "cup", group: "Sauce" }),
      ing("apple cider vinegar", "1", { unit: "tbsp", group: "Sauce" }),
    ],
    steps: [
      step(1, "Mix and shape the meatballs", "Combine ground turkey, breadcrumbs, egg, garlic, oregano, salt, and pepper. Mix just until combined and shape into 1.5-inch meatballs — overmixing makes them dense.", { minutes: 15 }),
      step(2, "Bake the meatballs", "Heat the oven to 425°F. Arrange meatballs with space between them on a sheet pan and bake 16–18 minutes until browned outside and 165°F in the center.", { minutes: 18, heatLevel: "medium-high", tempF: 425 }),
      step(3, "Roast the green beans", "Toss green beans with olive oil, salt, and pepper on a separate sheet pan and roast alongside the meatballs 14–16 minutes until tender with browned edges.", { minutes: 16, heatLevel: "medium-high", tempF: 425 }),
      step(4, "Cook the rice", "Rinse rice, bring it with water to a boil in a lidded pot, then reduce to low and simmer 18 minutes. Rest 10 minutes, then fluff.", { minutes: 28, heatLevel: "low" }),
      step(5, "Mix the honey mustard sauce", "Whisk dijon mustard, honey, and apple cider vinegar until smooth. Taste and adjust sweetness or tang to the crew's preference.", { minutes: 4 }),
      step(6, "Build the bowls", "Layer rice and green beans in each bowl, add a portion of meatballs, and finish with a generous drizzle of honey mustard sauce.", { minutes: 6 }),
      CALL_INTERRUPTION_STEP(7, "baked turkey meatballs"),
      LEFTOVERS_PACK_DOWN_STEP(8, "baked turkey meatballs"),
    ],
    proTips: [
      "Prep tip: Wet hands slightly when shaping meatballs so the mixture doesn't stick to your fingers.",
      "Rookie tip: Space meatballs apart on the pan so they roast instead of steaming against each other.",
      "Double the honey mustard sauce — it tends to disappear fast.",
      "Swap green beans for roasted carrots or Brussels sprouts depending on what's on hand.",
    ],
    tonightSpread: buildStructuredTonightSpread(
      "Honey mustard turkey meatball bowls",
      ["Simple green salad", "crusty bread"],
      ["Extra honey mustard sauce", "hot sauce"],
    ),
    leftovers: standardLeftovers("baked turkey meatballs", [
      "Meatballs freeze well on their own for up to 3 months — thaw and reheat to 165°F.",
    ]),
    equipment: ["Two sheet pans", "Rice pot", "Mixing bowls", "Instant-read thermometer"],
    nutrition: { calories: 659, protein: 43, carbs: 76, fats: 20, fiber: 6 },
    spiceLevel: "mild",
    cleanupDifficulty: "easy",
    searchTerms: [
      "turkey meatball bowl",
      "honey mustard meatballs",
      "high protein turkey meatballs",
      "meal prep meatball bowl",
      "lean turkey dinner",
      "firehouse turkey meatballs",
    ],
    substitutions: [
      "Use ground chicken instead of turkey.",
      "Use panko instead of standard breadcrumbs.",
      "Use maple syrup instead of honey for a slightly different sweetness.",
    ],
  }),

  def({
    slug: "cajun-lime-shrimp-black-bean-bowls",
    title: "Cajun Lime Shrimp & Black Bean Bowls",
    subtitle: "Cajun-seared shrimp with black beans, corn, and rice in a bright lime dressing",
    category: "crew_feeders",
    protein: "seafood",
    cuisine: "cajun",
    mealFormat: "bowl",
    explorePools: ["bowl", "seafood", "healthy", "high_protein", "hall_expansion"],
    hookLine: "A fast, lean shrimp bowl with real Cajun heat and a bean-and-corn base that holds up as a full meal.",
    description:
      "Shrimp gets a quick Cajun sear, then joins black beans, charred corn, and rice with a lime dressing. It cooks fast enough for a busy shift and gives crews a lean seafood option beyond salmon and cod.",
    whyCrewsLikeIt:
      "Shrimp cooks in minutes, so this comes together fast on a night the hall doesn't have a lot of prep time, and the beans and rice keep it filling despite the lean protein.",
    mealPrepNotes:
      "Make-ahead: rice, beans, and corn all hold well up to 4 days. Storage: keep shrimp separate and reheat gently — it toughens fast if overcooked a second time. Reheating: warm shrimp briefly in a skillet just until hot, not longer.",
    stationWorkflow: [
      "Start rice and beans first since shrimp only takes a few minutes right before service.",
      "Sear shrimp last, in batches, so the pan stays hot enough for a real char.",
      "Mix the lime dressing while the shrimp cooks so everything is ready together.",
    ],
    prepMinutes: 15,
    cookMinutes: 20,
    difficulty: "easy",
    crewSizeDefault: 8,
    ingredients: [
      ing("shrimp", "3", { unit: "lb", notes: "peeled, deveined", group: "Protein" }),
      ing("cajun seasoning", "3", { unit: "tbsp", group: "Protein" }),
      ing("olive oil", "3", { unit: "tbsp", group: "Protein" }),
      ing("jasmine rice", "2.5", { unit: "cups", notes: "uncooked", group: "Base" }),
      ing("black beans", "2", { unit: "cans", notes: "drained, rinsed", group: "Base" }),
      ing("corn", "3", { unit: "cups", group: "Base" }),
      ing("bell pepper", "2", { unit: "each", notes: "diced", group: "Base" }),
      ing("lime juice", "0.33", { unit: "cup", group: "Dressing" }),
      ing("olive oil", "2", { unit: "tbsp", group: "Dressing" }),
      ing("fresh cilantro", "0.25", { unit: "cup", notes: "chopped", optional: true, group: "Finish" }),
    ],
    steps: [
      step(1, "Cook the rice", "Rinse rice, bring it with water to a boil in a lidded pot, then reduce to low and simmer 18 minutes. Rest 10 minutes, then fluff.", { minutes: 28, heatLevel: "low" }),
      step(2, "Warm the beans and char the corn", "Warm black beans in a saucepan with a splash of water. In a separate dry skillet, toast corn over medium-high 4–5 minutes until a few kernels brown. Combine with diced bell pepper.", { minutes: 8, heatLevel: "medium-high" }),
      step(3, "Season the shrimp", "Pat shrimp dry and toss with cajun seasoning until evenly coated. Dry shrimp sears better than wet shrimp.", { minutes: 5 }),
      step(4, "Sear the shrimp", "Heat oil in a wide skillet over medium-high until shimmering. Sear shrimp in a single layer, 90 seconds per side, until pink, opaque, and lightly charred at the edges. Do not overcrowd or overcook — shrimp turns rubbery fast.", { minutes: 6, heatLevel: "medium-high" }),
      step(5, "Mix the lime dressing", "Whisk lime juice, olive oil, and a pinch of salt. Toss half with the bean and corn mixture and reserve the rest for drizzling.", { minutes: 4 }),
      step(6, "Build the bowls", "Layer rice, black beans, and corn-pepper mix in each bowl, top with seared shrimp, and finish with the remaining lime dressing and cilantro if using.", { minutes: 6 }),
    ],
    proTips: [
      "Prep tip: Pat shrimp completely dry before seasoning so it sears instead of steams.",
      "Rookie tip: Pull shrimp the moment it turns pink and opaque — a few extra seconds turns it tough.",
      "Cook shrimp in batches rather than crowding the pan for real color and char.",
      "Swap shrimp for chicken or tofu using the same seasoning and timing adjustments.",
    ],
    tonightSpread: buildStructuredTonightSpread(
      "Cajun lime shrimp and black bean bowls",
      ["Tortilla chips", "extra lime wedges"],
      ["Hot sauce", "extra cilantro"],
    ),
    leftovers: [
      "Store shrimp separately from rice and beans; reheat gently in a skillet just until warm.",
      "Cool rice and beans in shallow containers within two hours of cooking.",
      "Shrimp is best eaten within 2 days — it toughens more than other proteins on repeated reheats.",
    ],
    equipment: ["Rice pot", "Large skillet", "Small saucepan", "Mixing bowls"],
    nutrition: { calories: 788, protein: 50, carbs: 76, fats: 31, fiber: 9 },
    spiceLevel: "medium",
    cleanupDifficulty: "easy",
    searchTerms: [
      "shrimp bowl",
      "cajun shrimp bowl",
      "high protein shrimp bowl",
      "shrimp black bean bowl",
      "lean seafood dinner",
      "firehouse shrimp bowl",
    ],
    substitutions: [
      "Use chicken breast instead of shrimp.",
      "Use tofu for a vegetarian version with the same seasoning.",
      "Use brown rice instead of jasmine rice.",
    ],
  }),
];
